/*****************************************************************************
 Copyright 2016-2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/

/**
    @defgroup grp_pinmux_table PinMux Table 
    @ingroup grp_pinmuxdrv

    @addtogroup grp_pinmux_table
    @{

    @limitations None

    @file pinmux_table.c
    @brief PINMUX table implementation

    @version 0.01 Initial draft
*/

#include <stdlib.h>
#include <bcm_err.h>
#include <bcm_utils.h>
#include <string.h>

#include <pinmux_osil.h>
#include <cfg_rdb.h>

/**
    @name PINMUX Table Design IDs
    @{
    @brief API IDs for PIOCFG
*/
#define BRCM_SWDSGN_PINMUX_INVALID_CFG_MACRO             (0x80U) /**< @brief #PINMUX_INVAL_CFG */
#define BRCM_SWDSGN_PINMUX_PINTOMODEMAPPING_GLOBAL       (0x81U) /**< @brief #PIOCFG_PinToModeMapping */
#define BRCM_SWDSGN_PINMUX_SETPADCONFIG_MACRO            (0x82U) /**< @brief #PINMUX_SetPadCfg */
/** @} */

/**
    @brief Chip specific Pin Table to use this value when the specific mode
    is invalid

    @trace  #BRCM_SWARCH_PINMUX_SETPADCONFIG_PROC
    @trace  #BRCM_SWREQ_PINMUX_KERNEL_INTERFACE
*/
#define PINMUX_INVAL_CFG                       (0xFFU)  /**< Invalid Configuration */

/**
    @trace  #BRCM_SWARCH_PINMUX_SETPADCONFIG_PROC
    @trace  #BRCM_SWREQ_PINMUX
*/
static const uint8_t PINMUX_PinToModeMapping[GPIO_MAX_CHANNELS][PINMUX_PIN_MODE_COUNT] = {
    /* Pin 0 */
    {0U, PINMUX_INVAL_CFG, 7U, 6U, 5U, 4U, PINMUX_INVAL_CFG, 3U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 1 */
    {0U, PINMUX_INVAL_CFG, 7U, 6U, 5U, 4U, PINMUX_INVAL_CFG, 3U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 2 */
    {0U, PINMUX_INVAL_CFG, 7U, 3U, 5U, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 3 */
    {0U, PINMUX_INVAL_CFG, 7U, 3U, 5U, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 4 */
    {0U, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 5 */
    {0U, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, 3U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 6 */
    {0U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 7 */
    {0U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 8 */
    {0U, 6U, PINMUX_INVAL_CFG, 3U, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 9 */
    {0U, 6U, PINMUX_INVAL_CFG, 3U, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 10 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 6U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, PINMUX_INVAL_CFG},
    /* Pin 11 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 6U, 2U, 3U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, PINMUX_INVAL_CFG},
    /* Pin 12 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 6U, 2U, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, PINMUX_INVAL_CFG},
    /* Pin 13 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 6U, 2U, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, PINMUX_INVAL_CFG},
    /* Pin 14 */
    {0U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 15 */
    {0U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 16 */
    {0U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 17 */
    {0U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 18 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 19 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 20 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 21 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
#if (GPIO_MAX_CHANNELS > 22)
    /* Pin 22 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 23 */
    {0U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 5U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 3U, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 24 */
    {0U, PINMUX_INVAL_CFG, 3U, 5U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 25 */
    {0U, PINMUX_INVAL_CFG, 3U, 5U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 26 */
    {0U, 5U, 3U, PINMUX_INVAL_CFG, 6U, PINMUX_INVAL_CFG, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 27 */
    {0U, 5U, 3U, PINMUX_INVAL_CFG, 6U, 4U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 28 */
    {0U, 5U, 3U, 4U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
    /* Pin 29 */
    {0U, 5U, 3U, 4U, 6U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 2U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG, 7U, PINMUX_INVAL_CFG, PINMUX_INVAL_CFG},
#endif
};


/**
    @trace  #BRCM_SWARCH_PINMUX_SETPADCONFIG_PROC
    @trace  #BRCM_SWREQ_PINMUX
*/
int32_t PINMUX_SetPadCfg(PINMUX_PinType aPin, PINMUX_PinModeType aMode)
{
    uint8_t cfgVal;
    int32_t ret = BCM_ERR_INVAL_PARAMS;
    CFG_RDBType *const regs = (CFG_RDBType * const)CFG_BASE;

    if ((GPIO_MAX_CHANNELS > aPin) && (PINMUX_PIN_MODE_COUNT > aMode)) {

        cfgVal = PINMUX_PinToModeMapping[aPin][aMode];

        if (PINMUX_INVAL_CFG != cfgVal) {
            ret = BCM_ERR_OK;
            if (aPin < BCM_MIN(GPIO_CHANNEL_16, GPIO_MAX_CHANNELS)) {
                regs->cfg_periph_a &= ~(PIOCFG_PAD_GRP_MASK <<
                                        ((aPin & 0xFEUL) * 2UL));
                regs->cfg_periph_a |= ((uint32_t)cfgVal <<
                                        ((aPin & 0xFEUL) * 2UL));
#if (GPIO_MAX_CHANNELS >= GPIO_CHANNEL_16)
            } else if (aPin < BCM_MIN(GPIO_CHANNEL_32, GPIO_MAX_CHANNELS)) {
                regs->cfg_periph_b &= ~(PIOCFG_PAD_GRP_MASK <<
                                        (((aPin % 16UL) & 0xFEUL) * 2UL));
                regs->cfg_periph_b |= ((uint32_t)cfgVal <<
                                        (((aPin % 16UL) & 0xFEUL) * 2UL));
#endif
#if (GPIO_MAX_CHANNELS >= GPIO_CHANNEL_32)
            } else if (aPin <= BCM_MIN(GPIO_CHANNEL_39, GPIO_MAX_CHANNELS)) {
                regs->cfg_periph_c &= ~(PIOCFG_PAD_GRP_MASK <<
                                        (((aPin % 32UL) & 0xFEUL) * 2UL));
                regs->cfg_periph_c |= ((uint32_t)cfgVal <<
                                        (((aPin % 32UL) & 0xFEUL) * 2UL));
#endif
            }
        }
    }

    return ret;
}

/** @} */
