/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file amac_rdb.h
    @brief RDB File for AMAC

    @version 2018May25_rdb
*/

#ifndef AMAC_RDB_H
#define AMAC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t AMAC_GMAC0_DEVCONTROL_TYPE;
#define AMAC_GMAC0_DEVCONTROL_RSVD_12_MASK (0xffc00000UL)
#define AMAC_GMAC0_DEVCONTROL_RSVD_12_SHIFT (22UL)
#define AMAC_GMAC0_DEVCONTROL_ENABLE_DEL_G_TXC_MASK (0x200000UL)
#define AMAC_GMAC0_DEVCONTROL_ENABLE_DEL_G_TXC_SHIFT (21UL)
#define AMAC_GMAC0_DEVCONTROL_ENABLE_DEL_G_RXC_MASK (0x100000UL)
#define AMAC_GMAC0_DEVCONTROL_ENABLE_DEL_G_RXC_SHIFT (20UL)
#define AMAC_GMAC0_DEVCONTROL_TXC_DRNG_MASK (0xc0000UL)
#define AMAC_GMAC0_DEVCONTROL_TXC_DRNG_SHIFT (18UL)
#define AMAC_GMAC0_DEVCONTROL_RXC_DRNG_MASK (0x30000UL)
#define AMAC_GMAC0_DEVCONTROL_RXC_DRNG_SHIFT (16UL)
#define AMAC_GMAC0_DEVCONTROL_RSVD_8_MASK (0xfe00UL)
#define AMAC_GMAC0_DEVCONTROL_RSVD_8_SHIFT (9UL)
#define AMAC_GMAC0_DEVCONTROL_TXQ_FLUSH_MASK (0x100UL)
#define AMAC_GMAC0_DEVCONTROL_TXQ_FLUSH_SHIFT (8UL)
#define AMAC_GMAC0_DEVCONTROL_NWAY_AUTO_POLLING_EN_MASK (0x80UL)
#define AMAC_GMAC0_DEVCONTROL_NWAY_AUTO_POLLING_EN_SHIFT (7UL)
#define AMAC_GMAC0_DEVCONTROL_FLOW_CNTL_MODE_MASK (0x60UL)
#define AMAC_GMAC0_DEVCONTROL_FLOW_CNTL_MODE_SHIFT (5UL)
#define AMAC_GMAC0_DEVCONTROL_MIB_RD_RESET_EN_MASK (0x10UL)
#define AMAC_GMAC0_DEVCONTROL_MIB_RD_RESET_EN_SHIFT (4UL)
#define AMAC_GMAC0_DEVCONTROL_RGMII_LINK_STATUS_SEL_MASK (0x8UL)
#define AMAC_GMAC0_DEVCONTROL_RGMII_LINK_STATUS_SEL_SHIFT (3UL)
#define AMAC_GMAC0_DEVCONTROL_CPU_FLOW_CNTL_ON_MASK (0x4UL)
#define AMAC_GMAC0_DEVCONTROL_CPU_FLOW_CNTL_ON_SHIFT (2UL)
#define AMAC_GMAC0_DEVCONTROL_RXQ_OVERFLOW_CTRL_SEL_MASK (0x2UL)
#define AMAC_GMAC0_DEVCONTROL_RXQ_OVERFLOW_CTRL_SEL_SHIFT (1UL)
#define AMAC_GMAC0_DEVCONTROL_TXARB_STRICT_MODE_MASK (0x1UL)
#define AMAC_GMAC0_DEVCONTROL_TXARB_STRICT_MODE_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_DEVSTATUS_TYPE;
#define AMAC_GMAC0_DEVSTATUS_RSVD_10_MASK (0xff000000UL)
#define AMAC_GMAC0_DEVSTATUS_RSVD_10_SHIFT (24UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_QUEUE_SIZE_MASK (0xf00000UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_QUEUE_SIZE_SHIFT (20UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_QUEUE_SIZE_MASK (0xf0000UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_QUEUE_SIZE_SHIFT (16UL)
#define AMAC_GMAC0_DEVSTATUS_RSVD_8_MASK (0xe000UL)
#define AMAC_GMAC0_DEVSTATUS_RSVD_8_SHIFT (13UL)
#define AMAC_GMAC0_DEVSTATUS_INTERFACE_MODE_MASK (0x1f00UL)
#define AMAC_GMAC0_DEVSTATUS_INTERFACE_MODE_SHIFT (8UL)
#define AMAC_GMAC0_DEVSTATUS_RSVD_7_MASK (0x80UL)
#define AMAC_GMAC0_DEVSTATUS_RSVD_7_SHIFT (7UL)
#define AMAC_GMAC0_DEVSTATUS_PAUSE_ON_MASK (0x40UL)
#define AMAC_GMAC0_DEVSTATUS_PAUSE_ON_SHIFT (6UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_INFO_BUF_FULL_MASK (0x20UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_INFO_BUF_FULL_SHIFT (5UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_DATA_BUF_FULL_MASK (0x10UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_DATA_BUF_FULL_SHIFT (4UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_BURST_FIFO_FULL_MASK (0x8UL)
#define AMAC_GMAC0_DEVSTATUS_TXQ_BURST_FIFO_FULL_SHIFT (3UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_INFO_BUF_FULL_MASK (0x4UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_INFO_BUF_FULL_SHIFT (2UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_DATA_BUF_FULL_MASK (0x2UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_DATA_BUF_FULL_SHIFT (1UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_BURST_FIFO_FULL_MASK (0x1UL)
#define AMAC_GMAC0_DEVSTATUS_RXQ_BURST_FIFO_FULL_SHIFT (0UL)




typedef uint8_t AMAC_RESERVED_TYPE;




typedef uint32_t AMAC_GMAC0_BISTSTATUS_TYPE;
#define AMAC_GMAC0_BISTSTATUS_RSVD_10_MASK (0xfffff000UL)
#define AMAC_GMAC0_BISTSTATUS_RSVD_10_SHIFT (12UL)
#define AMAC_GMAC0_BISTSTATUS_SWITCHFAIL_MASK (0x800UL)
#define AMAC_GMAC0_BISTSTATUS_SWITCHFAIL_SHIFT (11UL)
#define AMAC_GMAC0_BISTSTATUS_RSVD_MASK (0x700UL)
#define AMAC_GMAC0_BISTSTATUS_RSVD_SHIFT (8UL)
#define AMAC_GMAC0_BISTSTATUS_RXQ_BURST_FIFO_MASK (0x80UL)
#define AMAC_GMAC0_BISTSTATUS_RXQ_BURST_FIFO_SHIFT (7UL)
#define AMAC_GMAC0_BISTSTATUS_RXQ_INFO_BUFFER_MASK (0x40UL)
#define AMAC_GMAC0_BISTSTATUS_RXQ_INFO_BUFFER_SHIFT (6UL)
#define AMAC_GMAC0_BISTSTATUS_RXQ_DATA_BUFFER_MASK (0x20UL)
#define AMAC_GMAC0_BISTSTATUS_RXQ_DATA_BUFFER_SHIFT (5UL)
#define AMAC_GMAC0_BISTSTATUS_TXQ_BURST_FIFO_MASK (0x10UL)
#define AMAC_GMAC0_BISTSTATUS_TXQ_BURST_FIFO_SHIFT (4UL)
#define AMAC_GMAC0_BISTSTATUS_TXQ_INFO_BUFFER_MASK (0x8UL)
#define AMAC_GMAC0_BISTSTATUS_TXQ_INFO_BUFFER_SHIFT (3UL)
#define AMAC_GMAC0_BISTSTATUS_TXQ_DATA_BUFFER_MASK (0x4UL)
#define AMAC_GMAC0_BISTSTATUS_TXQ_DATA_BUFFER_SHIFT (2UL)
#define AMAC_GMAC0_BISTSTATUS_MIB_RX_FIFO_MASK (0x2UL)
#define AMAC_GMAC0_BISTSTATUS_MIB_RX_FIFO_SHIFT (1UL)
#define AMAC_GMAC0_BISTSTATUS_MIB_TX_FIFO_MASK (0x1UL)
#define AMAC_GMAC0_BISTSTATUS_MIB_TX_FIFO_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_INTSTATUS_TYPE;
#define AMAC_GMAC0_INTSTATUS_TXQECCUNCORRECTED_MASK (0x80000000UL)
#define AMAC_GMAC0_INTSTATUS_TXQECCUNCORRECTED_SHIFT (31UL)
#define AMAC_GMAC0_INTSTATUS_TXQECCCORRECTED_MASK (0x40000000UL)
#define AMAC_GMAC0_INTSTATUS_TXQECCCORRECTED_SHIFT (30UL)
#define AMAC_GMAC0_INTSTATUS_RXQECCUNCORRECTED_MASK (0x20000000UL)
#define AMAC_GMAC0_INTSTATUS_RXQECCUNCORRECTED_SHIFT (29UL)
#define AMAC_GMAC0_INTSTATUS_RXQECCCORRECTED_MASK (0x10000000UL)
#define AMAC_GMAC0_INTSTATUS_RXQECCCORRECTED_SHIFT (28UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_3_MASK (0x8000000UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_3_SHIFT (27UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_2_MASK (0x4000000UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_2_SHIFT (26UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_1_MASK (0x2000000UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_1_SHIFT (25UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_0_MASK (0x1000000UL)
#define AMAC_GMAC0_INTSTATUS_XMTINT_0_SHIFT (24UL)
#define AMAC_GMAC0_INTSTATUS_RSVD_16_MASK (0xfe0000UL)
#define AMAC_GMAC0_INTSTATUS_RSVD_16_SHIFT (17UL)
#define AMAC_GMAC0_INTSTATUS_RCVINT_MASK (0x10000UL)
#define AMAC_GMAC0_INTSTATUS_RCVINT_SHIFT (16UL)
#define AMAC_GMAC0_INTSTATUS_XMTFIFOUF_MASK (0x8000UL)
#define AMAC_GMAC0_INTSTATUS_XMTFIFOUF_SHIFT (15UL)
#define AMAC_GMAC0_INTSTATUS_RCVFIFOOF_MASK (0x4000UL)
#define AMAC_GMAC0_INTSTATUS_RCVFIFOOF_SHIFT (14UL)
#define AMAC_GMAC0_INTSTATUS_RCVDESCUF_MASK (0x2000UL)
#define AMAC_GMAC0_INTSTATUS_RCVDESCUF_SHIFT (13UL)
#define AMAC_GMAC0_INTSTATUS_DESCPROTOERR_MASK (0x1000UL)
#define AMAC_GMAC0_INTSTATUS_DESCPROTOERR_SHIFT (12UL)
#define AMAC_GMAC0_INTSTATUS_DATAERR_MASK (0x800UL)
#define AMAC_GMAC0_INTSTATUS_DATAERR_SHIFT (11UL)
#define AMAC_GMAC0_INTSTATUS_DESCRERR_MASK (0x400UL)
#define AMAC_GMAC0_INTSTATUS_DESCRERR_SHIFT (10UL)
#define AMAC_GMAC0_INTSTATUS_RSVD_9_MASK (0x200UL)
#define AMAC_GMAC0_INTSTATUS_RSVD_9_SHIFT (9UL)
#define AMAC_GMAC0_INTSTATUS_INT_SW_LINK_ST_CHGEN_MASK (0x100UL)
#define AMAC_GMAC0_INTSTATUS_INT_SW_LINK_ST_CHGEN_SHIFT (8UL)
#define AMAC_GMAC0_INTSTATUS_INT_TIMEOUT_MASK (0x80UL)
#define AMAC_GMAC0_INTSTATUS_INT_TIMEOUT_SHIFT (7UL)
#define AMAC_GMAC0_INTSTATUS_MIB_TX_INT_MASK (0x40UL)
#define AMAC_GMAC0_INTSTATUS_MIB_TX_INT_SHIFT (6UL)
#define AMAC_GMAC0_INTSTATUS_MIB_RX_INT_MASK (0x20UL)
#define AMAC_GMAC0_INTSTATUS_MIB_RX_INT_SHIFT (5UL)
#define AMAC_GMAC0_INTSTATUS_MDIOINT_MASK (0x10UL)
#define AMAC_GMAC0_INTSTATUS_MDIOINT_SHIFT (4UL)
#define AMAC_GMAC0_INTSTATUS_NWAYLINKSTATUSINT_MASK (0x8UL)
#define AMAC_GMAC0_INTSTATUS_NWAYLINKSTATUSINT_SHIFT (3UL)
#define AMAC_GMAC0_INTSTATUS_TXQ_FLUSH_DONEINT_MASK (0x4UL)
#define AMAC_GMAC0_INTSTATUS_TXQ_FLUSH_DONEINT_SHIFT (2UL)
#define AMAC_GMAC0_INTSTATUS_MIB_TX_OVERFLOWINT_MASK (0x2UL)
#define AMAC_GMAC0_INTSTATUS_MIB_TX_OVERFLOWINT_SHIFT (1UL)
#define AMAC_GMAC0_INTSTATUS_MIB_RX_OVERFLOWINT_MASK (0x1UL)
#define AMAC_GMAC0_INTSTATUS_MIB_RX_OVERFLOWINT_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_INTMASK_TYPE;
#define AMAC_GMAC0_INTMASK_TXQECCUNCORRECTEDEN_MASK (0x80000000UL)
#define AMAC_GMAC0_INTMASK_TXQECCUNCORRECTEDEN_SHIFT (31UL)
#define AMAC_GMAC0_INTMASK_TXQECCCORRECTEDEN_MASK (0x40000000UL)
#define AMAC_GMAC0_INTMASK_TXQECCCORRECTEDEN_SHIFT (30UL)
#define AMAC_GMAC0_INTMASK_RXQECCUNCORRECTEDEN_MASK (0x20000000UL)
#define AMAC_GMAC0_INTMASK_RXQECCUNCORRECTEDEN_SHIFT (29UL)
#define AMAC_GMAC0_INTMASK_RXQECCCORRECTEDEN_MASK (0x10000000UL)
#define AMAC_GMAC0_INTMASK_RXQECCCORRECTEDEN_SHIFT (28UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_3_MASK (0x8000000UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_3_SHIFT (27UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_2_MASK (0x4000000UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_2_SHIFT (26UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_1_MASK (0x2000000UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_1_SHIFT (25UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_0_MASK (0x1000000UL)
#define AMAC_GMAC0_INTMASK_XMTINTEN_0_SHIFT (24UL)
#define AMAC_GMAC0_INTMASK_RSVD_16_MASK (0xfe0000UL)
#define AMAC_GMAC0_INTMASK_RSVD_16_SHIFT (17UL)
#define AMAC_GMAC0_INTMASK_RCVINTEN_MASK (0x10000UL)
#define AMAC_GMAC0_INTMASK_RCVINTEN_SHIFT (16UL)
#define AMAC_GMAC0_INTMASK_XMTUFEN_MASK (0x8000UL)
#define AMAC_GMAC0_INTMASK_XMTUFEN_SHIFT (15UL)
#define AMAC_GMAC0_INTMASK_RCVFIFOOFEN_MASK (0x4000UL)
#define AMAC_GMAC0_INTMASK_RCVFIFOOFEN_SHIFT (14UL)
#define AMAC_GMAC0_INTMASK_RCVDESCUFEN_MASK (0x2000UL)
#define AMAC_GMAC0_INTMASK_RCVDESCUFEN_SHIFT (13UL)
#define AMAC_GMAC0_INTMASK_DESCPROTOERREN_MASK (0x1000UL)
#define AMAC_GMAC0_INTMASK_DESCPROTOERREN_SHIFT (12UL)
#define AMAC_GMAC0_INTMASK_DATAERREN_MASK (0x800UL)
#define AMAC_GMAC0_INTMASK_DATAERREN_SHIFT (11UL)
#define AMAC_GMAC0_INTMASK_DESCRERREN_MASK (0x400UL)
#define AMAC_GMAC0_INTMASK_DESCRERREN_SHIFT (10UL)
#define AMAC_GMAC0_INTMASK_RSVD_9_MASK (0x200UL)
#define AMAC_GMAC0_INTMASK_RSVD_9_SHIFT (9UL)
#define AMAC_GMAC0_INTMASK_INT_SW_LINK_ST_CHGEN_MASK (0x100UL)
#define AMAC_GMAC0_INTMASK_INT_SW_LINK_ST_CHGEN_SHIFT (8UL)
#define AMAC_GMAC0_INTMASK_INT_TIMEOUTEN_MASK (0x80UL)
#define AMAC_GMAC0_INTMASK_INT_TIMEOUTEN_SHIFT (7UL)
#define AMAC_GMAC0_INTMASK_MIB_TX_INTEN_MASK (0x40UL)
#define AMAC_GMAC0_INTMASK_MIB_TX_INTEN_SHIFT (6UL)
#define AMAC_GMAC0_INTMASK_MIB_RX_INTEN_MASK (0x20UL)
#define AMAC_GMAC0_INTMASK_MIB_RX_INTEN_SHIFT (5UL)
#define AMAC_GMAC0_INTMASK_MDIOINTEN_MASK (0x10UL)
#define AMAC_GMAC0_INTMASK_MDIOINTEN_SHIFT (4UL)
#define AMAC_GMAC0_INTMASK_NWAYLINKSTATUSINTEN_MASK (0x8UL)
#define AMAC_GMAC0_INTMASK_NWAYLINKSTATUSINTEN_SHIFT (3UL)
#define AMAC_GMAC0_INTMASK_TXQ_FLUSH_DONEINTEN_MASK (0x4UL)
#define AMAC_GMAC0_INTMASK_TXQ_FLUSH_DONEINTEN_SHIFT (2UL)
#define AMAC_GMAC0_INTMASK_MIB_TX_OVERFLOWINTEN_MASK (0x2UL)
#define AMAC_GMAC0_INTMASK_MIB_TX_OVERFLOWINTEN_SHIFT (1UL)
#define AMAC_GMAC0_INTMASK_MIB_RX_OVERFLOWINTEN_MASK (0x1UL)
#define AMAC_GMAC0_INTMASK_MIB_RX_OVERFLOWINTEN_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_GPTIMER_TYPE;
#define AMAC_GMAC0_GPTIMER_GPTIMER_MASK (0xffffffffUL)
#define AMAC_GMAC0_GPTIMER_GPTIMER_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_INTRCVLAZY_TYPE;
#define AMAC_GMAC0_INTRCVLAZY_FRAMECOUNT_MASK (0xff000000UL)
#define AMAC_GMAC0_INTRCVLAZY_FRAMECOUNT_SHIFT (24UL)
#define AMAC_GMAC0_INTRCVLAZY_TIMEOUT_MASK (0xffffffUL)
#define AMAC_GMAC0_INTRCVLAZY_TIMEOUT_SHIFT (0UL)




typedef uint32_t AMAC_G0X0_TYPE;
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_11_MASK (0xfc000000UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_11_SHIFT (26UL)
#define AMAC_G0X0_XMTCONTROL_0_PREFETCHTHRESH_MASK (0x3000000UL)
#define AMAC_G0X0_XMTCONTROL_0_PREFETCHTHRESH_SHIFT (24UL)
#define AMAC_G0X0_XMTCONTROL_0_PREFETCHCTL_MASK (0xe00000UL)
#define AMAC_G0X0_XMTCONTROL_0_PREFETCHCTL_SHIFT (21UL)
#define AMAC_G0X0_XMTCONTROL_0_BURSTLEN_0_MASK (0x1c0000UL)
#define AMAC_G0X0_XMTCONTROL_0_BURSTLEN_0_SHIFT (18UL)
#define AMAC_G0X0_XMTCONTROL_0_ADDREXT_0_MASK (0x30000UL)
#define AMAC_G0X0_XMTCONTROL_0_ADDREXT_0_SHIFT (16UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_7_MASK (0xc000UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_7_SHIFT (14UL)
#define AMAC_G0X0_XMTCONTROL_0_SELECTBUFFERACTIVEINDEX_MASK (0x2000UL)
#define AMAC_G0X0_XMTCONTROL_0_SELECTBUFFERACTIVEINDEX_SHIFT (13UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_6_MASK (0x1000UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_6_SHIFT (12UL)
#define AMAC_G0X0_XMTCONTROL_0_TXPARITYCHECKDISABLE_0_MASK (0x800UL)
#define AMAC_G0X0_XMTCONTROL_0_TXPARITYCHECKDISABLE_0_SHIFT (11UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_5_MASK (0x700UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_5_SHIFT (8UL)
#define AMAC_G0X0_XMTCONTROL_0_MULTIPLEOUTSTANDINGREADS_MASK (0xc0UL)
#define AMAC_G0X0_XMTCONTROL_0_MULTIPLEOUTSTANDINGREADS_SHIFT (6UL)
#define AMAC_G0X0_XMTCONTROL_0_BURSTALIGNEN_0_MASK (0x20UL)
#define AMAC_G0X0_XMTCONTROL_0_BURSTALIGNEN_0_SHIFT (5UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_3_MASK (0x18UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTCONTROL_0_RSVD_3_SHIFT (3UL)
#define AMAC_G0X0_XMTCONTROL_0_DMA_LOOPBACK_MODE_MASK (0x4UL)
#define AMAC_G0X0_XMTCONTROL_0_DMA_LOOPBACK_MODE_SHIFT (2UL)
#define AMAC_G0X0_XMTCONTROL_0_TXSUSPEND_0_MASK (0x2UL)
#define AMAC_G0X0_XMTCONTROL_0_TXSUSPEND_0_SHIFT (1UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTEN_0_MASK (0x1UL)
#define AMAC_G0X0_XMTCONTROL_0_XMTEN_0_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_XMTPTR_0_TYPE;
#define AMAC_GMAC0_XMTPTR_0_RSVD_1_MASK (0xffffe000UL)
#define AMAC_GMAC0_XMTPTR_0_RSVD_1_SHIFT (13UL)
#define AMAC_GMAC0_XMTPTR_0_LASTDSCR_0_MASK (0x1fffUL)
#define AMAC_GMAC0_XMTPTR_0_LASTDSCR_0_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_XMTADDR_LOW_0_TYPE;
#define AMAC_GMAC0_XMTADDR_LOW_0_0_MASK (0xfffffff0UL)
#define AMAC_GMAC0_XMTADDR_LOW_0_0_SHIFT (4UL)
#define AMAC_GMAC0_XMTADDR_LOW_0_RESERVED_MASK (0xfUL)
#define AMAC_GMAC0_XMTADDR_LOW_0_RESERVED_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_XMTADDR_HIGH_0_TYPE;
#define AMAC_GMAC0_XMTADDR_HIGH_0_0_MASK (0xffffffffUL)
#define AMAC_GMAC0_XMTADDR_HIGH_0_0_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_XMTSTATUS0_0_TYPE;
#define AMAC_GMAC0_XMTSTATUS0_0_XMTSTATE_0_MASK (0xf0000000UL)
#define AMAC_GMAC0_XMTSTATUS0_0_XMTSTATE_0_SHIFT (28UL)
#define AMAC_GMAC0_XMTSTATUS0_0_RSVD_1_MASK (0xfffe000UL)
#define AMAC_GMAC0_XMTSTATUS0_0_RSVD_1_SHIFT (13UL)
#define AMAC_GMAC0_XMTSTATUS0_0_CURRDSCR_0_MASK (0x1fffUL)
#define AMAC_GMAC0_XMTSTATUS0_0_CURRDSCR_0_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_XMTSTATUS1_0_TYPE;
#define AMAC_GMAC0_XMTSTATUS1_0_XMTERR_0_MASK (0xf0000000UL)
#define AMAC_GMAC0_XMTSTATUS1_0_XMTERR_0_SHIFT (28UL)
#define AMAC_GMAC0_XMTSTATUS1_0_RSVD_1_MASK (0xfffe000UL)
#define AMAC_GMAC0_XMTSTATUS1_0_RSVD_1_SHIFT (13UL)
#define AMAC_GMAC0_XMTSTATUS1_0_ACTIVEDESCR_0_MASK (0x1fffUL)
#define AMAC_GMAC0_XMTSTATUS1_0_ACTIVEDESCR_0_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RCVCONTROL_TYPE;
#define AMAC_GMAC0_RCVCONTROL_RSVD_11_MASK (0xfc000000UL)
#define AMAC_GMAC0_RCVCONTROL_RSVD_11_SHIFT (26UL)
#define AMAC_GMAC0_RCVCONTROL_PREFETCHTHRESH_MASK (0x3000000UL)
#define AMAC_GMAC0_RCVCONTROL_PREFETCHTHRESH_SHIFT (24UL)
#define AMAC_GMAC0_RCVCONTROL_PREFETCHCTL_MASK (0xe00000UL)
#define AMAC_GMAC0_RCVCONTROL_PREFETCHCTL_SHIFT (21UL)
#define AMAC_GMAC0_RCVCONTROL_BURSTLEN_MASK (0x1c0000UL)
#define AMAC_GMAC0_RCVCONTROL_BURSTLEN_SHIFT (18UL)
#define AMAC_GMAC0_RCVCONTROL_ADDREXT_MASK (0x30000UL)
#define AMAC_GMAC0_RCVCONTROL_ADDREXT_SHIFT (16UL)
#define AMAC_GMAC0_RCVCONTROL_RSVD_7_MASK (0xc000UL)
#define AMAC_GMAC0_RCVCONTROL_RSVD_7_SHIFT (14UL)
#define AMAC_GMAC0_RCVCONTROL_SELECTBUFFERACTIVEINDEX_MASK (0x2000UL)
#define AMAC_GMAC0_RCVCONTROL_SELECTBUFFERACTIVEINDEX_SHIFT (13UL)
#define AMAC_GMAC0_RCVCONTROL_WAITFORCOMPLETE_MASK (0x1000UL)
#define AMAC_GMAC0_RCVCONTROL_WAITFORCOMPLETE_SHIFT (12UL)
#define AMAC_GMAC0_RCVCONTROL_RXPARITYCHECKDISABLE_MASK (0x800UL)
#define AMAC_GMAC0_RCVCONTROL_RXPARITYCHECKDISABLE_SHIFT (11UL)
#define AMAC_GMAC0_RCVCONTROL_OFLOWCONTINUE_MASK (0x400UL)
#define AMAC_GMAC0_RCVCONTROL_OFLOWCONTINUE_SHIFT (10UL)
#define AMAC_GMAC0_RCVCONTROL_SEPRXHDRDESCEN_MASK (0x200UL)
#define AMAC_GMAC0_RCVCONTROL_SEPRXHDRDESCEN_SHIFT (9UL)
#define AMAC_GMAC0_RCVCONTROL_RSVD_2_MASK (0x100UL)
#define AMAC_GMAC0_RCVCONTROL_RSVD_2_SHIFT (8UL)
#define AMAC_GMAC0_RCVCONTROL_RCVOFFSET_MASK (0xfeUL)
#define AMAC_GMAC0_RCVCONTROL_RCVOFFSET_SHIFT (1UL)
#define AMAC_GMAC0_RCVCONTROL_REVEN_MASK (0x1UL)
#define AMAC_GMAC0_RCVCONTROL_REVEN_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RCVPTR_TYPE;
#define AMAC_GMAC0_RCVPTR_RSVD_1_MASK (0xffffe000UL)
#define AMAC_GMAC0_RCVPTR_RSVD_1_SHIFT (13UL)
#define AMAC_GMAC0_RCVPTR_RCVPTR_MASK (0x1fffUL)
#define AMAC_GMAC0_RCVPTR_RCVPTR_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RCVADDR_LOW_TYPE;
#define AMAC_GMAC0_RCVADDR_LOW_LOW_MASK (0xfffffff0UL)
#define AMAC_GMAC0_RCVADDR_LOW_LOW_SHIFT (4UL)
#define AMAC_GMAC0_RCVADDR_LOW_RESERVED_MASK (0xfUL)
#define AMAC_GMAC0_RCVADDR_LOW_RESERVED_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RCVADDR_HIGH_TYPE;
#define AMAC_GMAC0_RCVADDR_HIGH_HIGH_MASK (0xffffffffUL)
#define AMAC_GMAC0_RCVADDR_HIGH_HIGH_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RCVSTATUS0_TYPE;
#define AMAC_GMAC0_RCVSTATUS0_RCVSTATE_MASK (0xf0000000UL)
#define AMAC_GMAC0_RCVSTATUS0_RCVSTATE_SHIFT (28UL)
#define AMAC_GMAC0_RCVSTATUS0_RSVD_1_MASK (0xfffe000UL)
#define AMAC_GMAC0_RCVSTATUS0_RSVD_1_SHIFT (13UL)
#define AMAC_GMAC0_RCVSTATUS0_CURRDSCR_MASK (0x1fffUL)
#define AMAC_GMAC0_RCVSTATUS0_CURRDSCR_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RCVSTATUS1_TYPE;
#define AMAC_GMAC0_RCVSTATUS1_RCVERR_MASK (0xf0000000UL)
#define AMAC_GMAC0_RCVSTATUS1_RCVERR_SHIFT (28UL)
#define AMAC_GMAC0_RCVSTATUS1_RSVD_1_MASK (0xfffe000UL)
#define AMAC_GMAC0_RCVSTATUS1_RSVD_1_SHIFT (13UL)
#define AMAC_GMAC0_RCVSTATUS1_ACTIVEDESCR_MASK (0x1fffUL)
#define AMAC_GMAC0_RCVSTATUS1_ACTIVEDESCR_SHIFT (0UL)




typedef uint32_t AMAC_G0X1_TYPE;
#define AMAC_G0X1_XMTCONTROL_0_ADDREXT_0_MASK (0x30000UL)
#define AMAC_G0X1_XMTCONTROL_0_ADDREXT_0_SHIFT (16UL)
#define AMAC_G0X1_XMTCONTROL_0_TXPARITYCHECKDISABLE_0_MASK (0x800UL)
#define AMAC_G0X1_XMTCONTROL_0_TXPARITYCHECKDISABLE_0_SHIFT (11UL)
#define AMAC_G0X1_XMTCONTROL_0_TXSUSPEND_0_MASK (0x2UL)
#define AMAC_G0X1_XMTCONTROL_0_TXSUSPEND_0_SHIFT (1UL)
#define AMAC_G0X1_XMTCONTROL_0_XMTEN_0_MASK (0x1UL)
#define AMAC_G0X1_XMTCONTROL_0_XMTEN_0_SHIFT (0UL)




typedef uint32_t AMAC_G0RGOL_TYPE;
#define AMAC_G0RGOL_RX_GD_OCTETS_LO_RX_GD_OCTETS_LO_MASK (0xffffffffUL)
#define AMAC_G0RGOL_RX_GD_OCTETS_LO_RX_GD_OCTETS_LO_SHIFT (0UL)




typedef uint32_t AMAC_G0RGOH_TYPE;
#define AMAC_G0RGOH_RX_GD_OCTETS_HI_RX_GD_OCTETS_HI_MASK (0xffffffffUL)
#define AMAC_G0RGOH_RX_GD_OCTETS_HI_RX_GD_OCTETS_HI_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_GD_PKTS_TYPE;
#define AMAC_GMAC0_RX_GD_PKTS_PKTS_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_GD_PKTS_PKTS_SHIFT (0UL)




typedef uint32_t AMAC_G0RAOL_TYPE;
#define AMAC_G0RAOL_RX_ALL_OCTETS_LO_RX_ALL_OCTETS_LO_MASK (0xffffffffUL)
#define AMAC_G0RAOL_RX_ALL_OCTETS_LO_RX_ALL_OCTETS_LO_SHIFT (0UL)




typedef uint32_t AMAC_G0RAOH_TYPE;
#define AMAC_G0RAOH_RX_ALL_OCTETS_HI_RX_ALL_OCTETS_HI_MASK (0xffffffffUL)
#define AMAC_G0RAOH_RX_ALL_OCTETS_HI_RX_ALL_OCTETS_HI_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_ALL_PKTS_TYPE;
#define AMAC_GMAC0_RX_ALL_PKTS_PKTS_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_ALL_PKTS_PKTS_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_BRDCAST_TYPE;
#define AMAC_GMAC0_RX_BRDCAST_BRDCAST_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_BRDCAST_BRDCAST_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_MULT_TYPE;
#define AMAC_GMAC0_RX_MULT_MULT_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_MULT_MULT_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_64_TYPE;
#define AMAC_GMAC0_RX_64_64_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_64_64_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_65_127_TYPE;
#define AMAC_GMAC0_RX_65_127_127_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_65_127_127_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_128_255_TYPE;
#define AMAC_GMAC0_RX_128_255_255_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_128_255_255_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_256_511_TYPE;
#define AMAC_GMAC0_RX_256_511_511_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_256_511_511_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_512_1023_TYPE;
#define AMAC_GMAC0_RX_512_1023_1023_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_512_1023_1023_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_1024_1522_TYPE;
#define AMAC_GMAC0_RX_1024_1522_1522_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_1024_1522_1522_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_1523_2047_TYPE;
#define AMAC_GMAC0_RX_1523_2047_2047_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_1523_2047_2047_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_2048_4095_TYPE;
#define AMAC_GMAC0_RX_2048_4095_4095_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_2048_4095_4095_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_4096_8191_TYPE;
#define AMAC_GMAC0_RX_4096_8191_8191_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_4096_8191_8191_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_8192_MAX_TYPE;
#define AMAC_GMAC0_RX_8192_MAX_MAX_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_8192_MAX_MAX_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_JAB_TYPE;
#define AMAC_GMAC0_RX_JAB_JAB_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_JAB_JAB_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_OVR_TYPE;
#define AMAC_GMAC0_RX_OVR_OVR_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_OVR_OVR_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_FRAG_TYPE;
#define AMAC_GMAC0_RX_FRAG_FRAG_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_FRAG_FRAG_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_DROP_TYPE;
#define AMAC_GMAC0_RX_DROP_DROP_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_DROP_DROP_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_CRC_ALIGN_TYPE;
#define AMAC_GMAC0_RX_CRC_ALIGN_ALIGN_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_CRC_ALIGN_ALIGN_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_UND_TYPE;
#define AMAC_GMAC0_RX_UND_UND_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_UND_UND_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_CRC_TYPE;
#define AMAC_GMAC0_RX_CRC_CRC_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_CRC_CRC_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_ALIGN_TYPE;
#define AMAC_GMAC0_RX_ALIGN_ALIGN_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_ALIGN_ALIGN_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_SYM_TYPE;
#define AMAC_GMAC0_RX_SYM_SYM_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_SYM_SYM_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_PAUS_TYPE;
#define AMAC_GMAC0_RX_PAUS_PAUS_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_PAUS_PAUS_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RX_CNTRL_TYPE;
#define AMAC_GMAC0_RX_CNTRL_CNTRL_MASK (0xffffffffUL)
#define AMAC_GMAC0_RX_CNTRL_CNTRL_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RXSACHANGES_TYPE;
#define AMAC_GMAC0_RXSACHANGES_RXSACHANGES_MASK (0xffffffffUL)
#define AMAC_GMAC0_RXSACHANGES_RXSACHANGES_SHIFT (0UL)




typedef uint32_t AMAC_GMAC0_RXUNICASTPKTS_TYPE;
#define AMAC_GMAC0_RXUNICASTPKTS_RXUNICASTPKTS_MASK (0xffffffffUL)
#define AMAC_GMAC0_RXUNICASTPKTS_RXUNICASTPKTS_SHIFT (0UL)




typedef uint32_t AMAC_U0IHBC_TYPE;
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_IPG_HD_BKP_CNTL_RSVD_3_MASK (0xffffff80UL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_IPG_HD_BKP_CNTL_RSVD_3_SHIFT (7UL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_IPG_CONFIG_RX_MASK (0x7cUL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_IPG_CONFIG_RX_SHIFT (2UL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_HD_FC_BKOFF_OK_MASK (0x2UL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_HD_FC_BKOFF_OK_SHIFT (1UL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_HD_FC_ENA_MASK (0x1UL)
#define AMAC_U0IHBC_IPG_HD_BKP_CNTL_HD_FC_ENA_SHIFT (0UL)




typedef uint32_t AMAC_U0CC_TYPE;
#define AMAC_U0CC_COMMAND_CONFIG_COMMAND_CONFIG_RSVD_28_MASK (0x80000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_COMMAND_CONFIG_RSVD_28_SHIFT (31UL)
#define AMAC_U0CC_COMMAND_CONFIG_RUNT_FILTER_DIS_MASK (0x40000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_RUNT_FILTER_DIS_SHIFT (30UL)
#define AMAC_U0CC_COMMAND_CONFIG_OOB_EFC_EN_MASK (0x20000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_OOB_EFC_EN_SHIFT (29UL)
#define AMAC_U0CC_COMMAND_CONFIG_IGNORE_TX_PAUSE_MASK (0x10000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_IGNORE_TX_PAUSE_SHIFT (28UL)
#define AMAC_U0CC_COMMAND_CONFIG_FD_TX_URUN_FIX_EN_MASK (0x8000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_FD_TX_URUN_FIX_EN_SHIFT (27UL)
#define AMAC_U0CC_COMMAND_CONFIG_RX_ERR_DISC_MASK (0x4000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_RX_ERR_DISC_SHIFT (26UL)
#define AMAC_U0CC_COMMAND_CONFIG_LINE_LOOPBACK_MASK (0x2000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_LINE_LOOPBACK_SHIFT (25UL)
#define AMAC_U0CC_COMMAND_CONFIG_NO_LGTH_CHECK_MASK (0x1000000UL)
#define AMAC_U0CC_COMMAND_CONFIG_NO_LGTH_CHECK_SHIFT (24UL)
#define AMAC_U0CC_COMMAND_CONFIG_CNTL_FRM_ENA_MASK (0x800000UL)
#define AMAC_U0CC_COMMAND_CONFIG_CNTL_FRM_ENA_SHIFT (23UL)
#define AMAC_U0CC_COMMAND_CONFIG_ENA_EXT_CONFIG_MASK (0x400000UL)
#define AMAC_U0CC_COMMAND_CONFIG_ENA_EXT_CONFIG_SHIFT (22UL)
#define AMAC_U0CC_COMMAND_CONFIG_EN_INTERNAL_TX_CRS_MASK (0x200000UL)
#define AMAC_U0CC_COMMAND_CONFIG_EN_INTERNAL_TX_CRS_SHIFT (21UL)
#define AMAC_U0CC_COMMAND_CONFIG_COMMAND_CONFIG_RSVD_18_MASK (0x180000UL)
#define AMAC_U0CC_COMMAND_CONFIG_COMMAND_CONFIG_RSVD_18_SHIFT (19UL)
#define AMAC_U0CC_COMMAND_CONFIG_SW_OVERRIDE_RX_MASK (0x40000UL)
#define AMAC_U0CC_COMMAND_CONFIG_SW_OVERRIDE_RX_SHIFT (18UL)
#define AMAC_U0CC_COMMAND_CONFIG_SW_OVERRIDE_TX_MASK (0x20000UL)
#define AMAC_U0CC_COMMAND_CONFIG_SW_OVERRIDE_TX_SHIFT (17UL)
#define AMAC_U0CC_COMMAND_CONFIG_MAC_LOOP_CON_MASK (0x10000UL)
#define AMAC_U0CC_COMMAND_CONFIG_MAC_LOOP_CON_SHIFT (16UL)
#define AMAC_U0CC_COMMAND_CONFIG_LOOP_ENA_MASK (0x8000UL)
#define AMAC_U0CC_COMMAND_CONFIG_LOOP_ENA_SHIFT (15UL)
#define AMAC_U0CC_COMMAND_CONFIG_FCS_CORRUPT_URUN_EN_MASK (0x4000UL)
#define AMAC_U0CC_COMMAND_CONFIG_FCS_CORRUPT_URUN_EN_SHIFT (14UL)
#define AMAC_U0CC_COMMAND_CONFIG_SW_RESET_MASK (0x2000UL)
#define AMAC_U0CC_COMMAND_CONFIG_SW_RESET_SHIFT (13UL)
#define AMAC_U0CC_COMMAND_CONFIG_OVERFLOW_EN_MASK (0x1000UL)
#define AMAC_U0CC_COMMAND_CONFIG_OVERFLOW_EN_SHIFT (12UL)
#define AMAC_U0CC_COMMAND_CONFIG_RX_LOW_LATENCY_EN_MASK (0x800UL)
#define AMAC_U0CC_COMMAND_CONFIG_RX_LOW_LATENCY_EN_SHIFT (11UL)
#define AMAC_U0CC_COMMAND_CONFIG_HD_ENA_MASK (0x400UL)
#define AMAC_U0CC_COMMAND_CONFIG_HD_ENA_SHIFT (10UL)
#define AMAC_U0CC_COMMAND_CONFIG_TX_ADDR_INS_MASK (0x200UL)
#define AMAC_U0CC_COMMAND_CONFIG_TX_ADDR_INS_SHIFT (9UL)
#define AMAC_U0CC_COMMAND_CONFIG_PAUSE_IGNORE_MASK (0x100UL)
#define AMAC_U0CC_COMMAND_CONFIG_PAUSE_IGNORE_SHIFT (8UL)
#define AMAC_U0CC_COMMAND_CONFIG_PAUSE_FWD_MASK (0x80UL)
#define AMAC_U0CC_COMMAND_CONFIG_PAUSE_FWD_SHIFT (7UL)
#define AMAC_U0CC_COMMAND_CONFIG_CRC_FWD_MASK (0x40UL)
#define AMAC_U0CC_COMMAND_CONFIG_CRC_FWD_SHIFT (6UL)
#define AMAC_U0CC_COMMAND_CONFIG_PAD_EN_MASK (0x20UL)
#define AMAC_U0CC_COMMAND_CONFIG_PAD_EN_SHIFT (5UL)
#define AMAC_U0CC_COMMAND_CONFIG_PROMIS_EN_MASK (0x10UL)
#define AMAC_U0CC_COMMAND_CONFIG_PROMIS_EN_SHIFT (4UL)
#define AMAC_U0CC_COMMAND_CONFIG_ETH_SPEED_MASK (0xcUL)
#define AMAC_U0CC_COMMAND_CONFIG_ETH_SPEED_SHIFT (2UL)
#define AMAC_U0CC_COMMAND_CONFIG_RX_ENA_MASK (0x2UL)
#define AMAC_U0CC_COMMAND_CONFIG_RX_ENA_SHIFT (1UL)
#define AMAC_U0CC_COMMAND_CONFIG_TX_ENA_MASK (0x1UL)
#define AMAC_U0CC_COMMAND_CONFIG_TX_ENA_SHIFT (0UL)




typedef uint32_t AMAC_UNIMAC0_MAC_0_TYPE;
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_0_MASK (0xff000000UL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_0_SHIFT (24UL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_1_MASK (0xff0000UL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_1_SHIFT (16UL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_2_MASK (0xff00UL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_2_SHIFT (8UL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_3_MASK (0xffUL)
#define AMAC_UNIMAC0_MAC_0_SA_BYTE_3_SHIFT (0UL)




typedef uint32_t AMAC_UNIMAC0_MAC_1_TYPE;
#define AMAC_UNIMAC0_MAC_1_SA_BYTE_4_MASK (0xff00UL)
#define AMAC_UNIMAC0_MAC_1_SA_BYTE_4_SHIFT (8UL)
#define AMAC_UNIMAC0_MAC_1_SA_BYTE_5_MASK (0xffUL)
#define AMAC_UNIMAC0_MAC_1_SA_BYTE_5_SHIFT (0UL)




typedef uint32_t AMAC_UNIMAC0_FRM_LENGTH_TYPE;
#define AMAC_UNIMAC0_FRM_LENGTH_RSVD_1_MASK (0xffffc000UL)
#define AMAC_UNIMAC0_FRM_LENGTH_RSVD_1_SHIFT (14UL)
#define AMAC_UNIMAC0_FRM_LENGTH_MAXFR_MASK (0x3fffUL)
#define AMAC_UNIMAC0_FRM_LENGTH_MAXFR_SHIFT (0UL)


typedef volatile struct COMP_PACKED _AMAC_TX_CHAN0_RDBType {
    AMAC_G0X0_TYPE gmac0_xmtcontrol_0; /* OFFSET: 0x200 */
    AMAC_GMAC0_XMTPTR_0_TYPE gmac0_xmtptr_0; /* OFFSET: 0x204 */
    AMAC_GMAC0_XMTADDR_LOW_0_TYPE gmac0_xmtaddr_low_0; /* OFFSET: 0x208 */
    AMAC_GMAC0_XMTADDR_HIGH_0_TYPE gmac0_xmtaddr_high_0; /* OFFSET: 0x20c */
    AMAC_GMAC0_XMTSTATUS0_0_TYPE gmac0_xmtstatus0_0; /* OFFSET: 0x210 */
    AMAC_GMAC0_XMTSTATUS1_0_TYPE gmac0_xmtstatus1_0; /* OFFSET: 0x214 */
} AMAC_TX_CHAN0_RDBType;

typedef volatile struct COMP_PACKED _AMAC_TX_CHAN1_RDBType {
    AMAC_G0X1_TYPE gmac0_xmtcontrol_1; /* OFFSET: 0x240 */
    AMAC_GMAC0_XMTPTR_0_TYPE gmac0_xmtptr_1; /* OFFSET: 0x244 */
    AMAC_GMAC0_XMTADDR_LOW_0_TYPE gmac0_xmtaddr_low_1; /* OFFSET: 0x248 */
    AMAC_GMAC0_XMTADDR_HIGH_0_TYPE gmac0_xmtaddr_high_1; /* OFFSET: 0x24c */
    AMAC_GMAC0_XMTSTATUS0_0_TYPE gmac0_xmtstatus0_1; /* OFFSET: 0x250 */
    AMAC_GMAC0_XMTSTATUS1_0_TYPE gmac0_xmtstatus1_1; /* OFFSET: 0x254 */
} AMAC_TX_CHAN1_RDBType;

typedef volatile struct COMP_PACKED _AMAC_TX_CHAN2_RDBType {
    AMAC_G0X1_TYPE gmac0_xmtcontrol_2; /* OFFSET: 0x280 */
    AMAC_GMAC0_XMTPTR_0_TYPE gmac0_xmtptr_2; /* OFFSET: 0x284 */
    AMAC_GMAC0_XMTADDR_LOW_0_TYPE gmac0_xmtaddr_low_2; /* OFFSET: 0x288 */
    AMAC_GMAC0_XMTADDR_HIGH_0_TYPE gmac0_xmtaddr_high_2; /* OFFSET: 0x28c */
    AMAC_GMAC0_XMTSTATUS0_0_TYPE gmac0_xmtstatus0_2; /* OFFSET: 0x290 */
    AMAC_GMAC0_XMTSTATUS1_0_TYPE gmac0_xmtstatus1_2; /* OFFSET: 0x294 */
} AMAC_TX_CHAN2_RDBType;

typedef volatile struct COMP_PACKED _AMAC_TX_CHAN3_RDBType {
    AMAC_G0X1_TYPE gmac0_xmtcontrol_3; /* OFFSET: 0x2c0 */
    AMAC_GMAC0_XMTPTR_0_TYPE gmac0_xmtptr_3; /* OFFSET: 0x2c4 */
    AMAC_GMAC0_XMTADDR_LOW_0_TYPE gmac0_xmtaddr_low_3; /* OFFSET: 0x2c8 */
    AMAC_GMAC0_XMTADDR_HIGH_0_TYPE gmac0_xmtaddr_high_3; /* OFFSET: 0x2cc */
    AMAC_GMAC0_XMTSTATUS0_0_TYPE gmac0_xmtstatus0_3; /* OFFSET: 0x2d0 */
    AMAC_GMAC0_XMTSTATUS1_0_TYPE gmac0_xmtstatus1_3; /* OFFSET: 0x2d4 */
} AMAC_TX_CHAN3_RDBType;



typedef volatile struct COMP_PACKED _AMAC_RDBType {
    AMAC_GMAC0_DEVCONTROL_TYPE gmac0_devcontrol; /* OFFSET: 0x0 */
    AMAC_GMAC0_DEVSTATUS_TYPE gmac0_devstatus; /* OFFSET: 0x4 */
    AMAC_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x8 */
    AMAC_GMAC0_BISTSTATUS_TYPE gmac0_biststatus; /* OFFSET: 0xc */
    AMAC_RESERVED_TYPE rsvd1[16]; /* OFFSET: 0x10 */
    AMAC_GMAC0_INTSTATUS_TYPE gmac0_intstatus; /* OFFSET: 0x20 */
    AMAC_GMAC0_INTMASK_TYPE gmac0_intmask; /* OFFSET: 0x24 */
    AMAC_GMAC0_GPTIMER_TYPE gmac0_gptimer; /* OFFSET: 0x28 */
    AMAC_RESERVED_TYPE rsvd2[212]; /* OFFSET: 0x2c */
    AMAC_GMAC0_INTRCVLAZY_TYPE gmac0_intrcvlazy; /* OFFSET: 0x100 */
    AMAC_RESERVED_TYPE rsvd3[252]; /* OFFSET: 0x104 */
    AMAC_TX_CHAN0_RDBType tx_chan0_regs; /* OFFSET: 0x200 */
    AMAC_RESERVED_TYPE rsvd4[8]; /* OFFSET: 0x218 */
    AMAC_GMAC0_RCVCONTROL_TYPE gmac0_rcvcontrol; /* OFFSET: 0x220 */
    AMAC_GMAC0_RCVPTR_TYPE gmac0_rcvptr; /* OFFSET: 0x224 */
    AMAC_GMAC0_RCVADDR_LOW_TYPE gmac0_rcvaddr_low; /* OFFSET: 0x228 */
    AMAC_GMAC0_RCVADDR_HIGH_TYPE gmac0_rcvaddr_high; /* OFFSET: 0x22c */
    AMAC_GMAC0_RCVSTATUS0_TYPE gmac0_rcvstatus0; /* OFFSET: 0x230 */
    AMAC_GMAC0_RCVSTATUS1_TYPE gmac0_rcvstatus1; /* OFFSET: 0x234 */
    AMAC_RESERVED_TYPE rsvd5[8]; /* OFFSET: 0x238 */
    AMAC_TX_CHAN1_RDBType tx_chan1_regs; /* OFFSET: 0x240 */
    AMAC_RESERVED_TYPE rsvd6[40]; /* OFFSET: 0x258 */
    AMAC_TX_CHAN2_RDBType tx_chan2_regs; /* OFFSET: 0x280 */
    AMAC_RESERVED_TYPE rsvd7[40]; /* OFFSET: 0x298 */
    AMAC_TX_CHAN3_RDBType tx_chan3_regs; /* OFFSET: 0x2c0 */
    AMAC_RESERVED_TYPE rsvd8[216]; /* OFFSET: 0x2d8 */
    AMAC_G0RGOL_TYPE gmac0_rx_gd_octets_lo; /* OFFSET: 0x3b0 */
    AMAC_G0RGOH_TYPE gmac0_rx_gd_octets_hi; /* OFFSET: 0x3b4 */
    AMAC_GMAC0_RX_GD_PKTS_TYPE gmac0_rx_gd_pkts; /* OFFSET: 0x3b8 */
    AMAC_G0RAOL_TYPE gmac0_rx_all_octets_lo; /* OFFSET: 0x3bc */
    AMAC_G0RAOH_TYPE gmac0_rx_all_octets_hi; /* OFFSET: 0x3c0 */
    AMAC_GMAC0_RX_ALL_PKTS_TYPE gmac0_rx_all_pkts; /* OFFSET: 0x3c4 */
    AMAC_GMAC0_RX_BRDCAST_TYPE gmac0_rx_brdcast; /* OFFSET: 0x3c8 */
    AMAC_GMAC0_RX_MULT_TYPE gmac0_rx_mult; /* OFFSET: 0x3cc */
    AMAC_GMAC0_RX_64_TYPE gmac0_rx_64; /* OFFSET: 0x3d0 */
    AMAC_GMAC0_RX_65_127_TYPE gmac0_rx_65_127; /* OFFSET: 0x3d4 */
    AMAC_GMAC0_RX_128_255_TYPE gmac0_rx_128_255; /* OFFSET: 0x3d8 */
    AMAC_GMAC0_RX_256_511_TYPE gmac0_rx_256_511; /* OFFSET: 0x3dc */
    AMAC_GMAC0_RX_512_1023_TYPE gmac0_rx_512_1023; /* OFFSET: 0x3e0 */
    AMAC_GMAC0_RX_1024_1522_TYPE gmac0_rx_1024_1522; /* OFFSET: 0x3e4 */
    AMAC_GMAC0_RX_1523_2047_TYPE gmac0_rx_1523_2047; /* OFFSET: 0x3e8 */
    AMAC_GMAC0_RX_2048_4095_TYPE gmac0_rx_2048_4095; /* OFFSET: 0x3ec */
    AMAC_GMAC0_RX_4096_8191_TYPE gmac0_rx_4096_8191; /* OFFSET: 0x3f0 */
    AMAC_GMAC0_RX_8192_MAX_TYPE gmac0_rx_8192_max; /* OFFSET: 0x3f4 */
    AMAC_GMAC0_RX_JAB_TYPE gmac0_rx_jab; /* OFFSET: 0x3f8 */
    AMAC_GMAC0_RX_OVR_TYPE gmac0_rx_ovr; /* OFFSET: 0x3fc */
    AMAC_GMAC0_RX_FRAG_TYPE gmac0_rx_frag; /* OFFSET: 0x400 */
    AMAC_GMAC0_RX_DROP_TYPE gmac0_rx_drop; /* OFFSET: 0x404 */
    AMAC_GMAC0_RX_CRC_ALIGN_TYPE gmac0_rx_crc_align; /* OFFSET: 0x408 */
    AMAC_GMAC0_RX_UND_TYPE gmac0_rx_und; /* OFFSET: 0x40c */
    AMAC_GMAC0_RX_CRC_TYPE gmac0_rx_crc; /* OFFSET: 0x410 */
    AMAC_GMAC0_RX_ALIGN_TYPE gmac0_rx_align; /* OFFSET: 0x414 */
    AMAC_GMAC0_RX_SYM_TYPE gmac0_rx_sym; /* OFFSET: 0x418 */
    AMAC_GMAC0_RX_PAUS_TYPE gmac0_rx_paus; /* OFFSET: 0x41c */
    AMAC_GMAC0_RX_CNTRL_TYPE gmac0_rx_cntrl; /* OFFSET: 0x420 */
    AMAC_GMAC0_RXSACHANGES_TYPE gmac0_rxsachanges; /* OFFSET: 0x424 */
    AMAC_GMAC0_RXUNICASTPKTS_TYPE gmac0_rxunicastpkts; /* OFFSET: 0x428 */
    AMAC_RESERVED_TYPE rsvd9[984]; /* OFFSET: 0x42c */
    AMAC_U0IHBC_TYPE unimac0_ipg_hd_bkp_cntl; /* OFFSET: 0x804 */
    AMAC_U0CC_TYPE unimac0_command_config; /* OFFSET: 0x808 */
    AMAC_UNIMAC0_MAC_0_TYPE unimac0_mac_0; /* OFFSET: 0x80c */
    AMAC_UNIMAC0_MAC_1_TYPE unimac0_mac_1; /* OFFSET: 0x810 */
    AMAC_UNIMAC0_FRM_LENGTH_TYPE unimac0_frm_length; /* OFFSET: 0x814 */
    AMAC_RESERVED_TYPE rsvd10[816]; /* OFFSET: 0x818 */
} AMAC_RDBType;


#define AMAC_BASE                       (0x40012000UL)

#define AMAC_TX_CHAN0_RDBTYPE_OFFSET    (0x40012200UL)

#define AMAC_TX_CHAN1_RDBTYPE_OFFSET    (0x40012240UL)

#define AMAC_TX_CHAN2_RDBTYPE_OFFSET    (0x40012280UL)

#define AMAC_TX_CHAN3_RDBTYPE_OFFSET    (0x400122c0UL)



#define AMAC_MAX_HW_ID                  (1UL)


#define ETHER_TX_CHAN_CNT               (4UL)


#define ETHER_RX_CHAN_CNT               (1UL)


#define AMAC_TIMER_FREQ_MHZ             (100UL)


#define AMAC_TXDMA_FLAG_CRC_MASK        (0x3UL)


#define AMAC_TXDMA_FLAG_CRC_APPEND      (0x0UL)


#define AMAC_TXDMA_FLAG_CRC_OVERWRITE   (0x1UL)


#define AMAC_TXDMA_FLAG_CRC_FORWARD     (0x2UL)


#define AMAC_TXDMA_FLAG_CRC_RSVD        (0x3UL)


#define AMAC_CHAN_STATE_DISABLED        (0UL)


#define AMAC_CHAN_STATE_ACTIVE          (1UL)


#define AMAC_CHAN_STATE_IDLE            (2UL)


#define AMAC_CHAN_STATE_STOPPED         (3UL)


#define AMAC_CHAN_STATE_SUSPEND         (4UL)


#define AMAC_CHAN_ERR_NOERR             (0UL)


#define AMAC_CHAN_ERR_PROT_ERR          (1UL)


#define AMAC_CHAN_ERR_FIFO_UNDERRUN     (2UL)


#define AMAC_CHAN_ERR_TRANSFER_ERR      (3UL)


#define AMAC_CHAN_ERR_DESC_READ_ERR     (4UL)


#define AMAC_CHAN_ERR_CORE_ERR          (5UL)


#define AMAC_CHAN_ERR_DESC_PARITY_ERR   (6UL)


#define AMAC_CHAN_ERR_MIN               (1UL)


#define AMAC_CHAN_DESC_PROTO_ERR        (CHAN_ERR_MIN)


#define AMAC_CHAN_FIFO_UN_ON_ERR        (2UL)


#define AMAC_CHAN_DATA_TRANS_ERR        (3UL)


#define AMAC_CHAN_DESC_READ_ERR         (4UL)


#define AMAC_CHAN_CORE_ERR              (5UL)


#define AMAC_CHAN_DESC_PARITY_ERR       (6UL)


#define AMAC_CHAN_ERR_MAX               (AMAC_CHAN_DESC_PARITY_ERR)


#define AMAC_DMA_DESC_EOT_EN            (1UL)


#define AMAC_DMA_DESC_EOT_DIS           (0UL)


#define AMAC_DMA_DESC_IOC_EN            (1UL)


#define AMAC_DMA_DESC_IOC_DIS           (0UL)


#define AMAC_DMA_DESC_EOF_EN            (1UL)


#define AMAC_DMA_DESC_EOF_DIS           (0UL)


#define AMAC_DMA_DESC_SOF_EN            (1UL)


#define AMAC_DMA_DESC_SOF_DIS           (0UL)


#define AMAC_DMA_DESC_BUFCOUNT_ZERO     (0UL)


#define AMAC_DMA_DESC_DATAPTRLOW_ZERO   (0UL)


#define AMAC_DMA_DESC_DATAPTRHIGH_ZERO  (0UL)


#define UMAC_CMDCFG_ETH_SPEED_10MBPS    (0UL)


#define UMAC_CMDCFG_ETH_SPEED_100MBPS   (1UL)


#define UMAC_CMDCFG_ETH_SPEED_1GBPS     (2UL)


#define UMAC_CMDCFG_ETH_SPEED_2_5GBPS   (3UL)


#define UMAC_CMDCFG_HD_HALF_DUPLEX      (1UL)


#define UMAC_CMDCFG_HD_FULL_DUPLEX      (0UL)

#endif /* AMAC_RDB_H */
