/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy_core_rdb.h
    @brief RDB File for BRPHY_CORE

    @version 2018May25_rdb
*/

#ifndef BRPHY_CORE_RDB_H
#define BRPHY_CORE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY_CORE_BASE10_TYPE;
#define BRPHY_CORE_BASE10_MAC_PHY_IF_MASK (0x8000U)
#define BRPHY_CORE_BASE10_MAC_PHY_IF_SHIFT (15U)
#define BRPHY_CORE_BASE10_AUTO_MDIX_DIS_MASK (0x4000U)
#define BRPHY_CORE_BASE10_AUTO_MDIX_DIS_SHIFT (14U)
#define BRPHY_CORE_BASE10_TX_DIS_MASK (0x2000U)
#define BRPHY_CORE_BASE10_TX_DIS_SHIFT (13U)
#define BRPHY_CORE_BASE10_INT_DIS_MASK (0x1000U)
#define BRPHY_CORE_BASE10_INT_DIS_SHIFT (12U)
#define BRPHY_CORE_BASE10_FORCE_INT_MASK (0x800U)
#define BRPHY_CORE_BASE10_FORCE_INT_SHIFT (11U)
#define BRPHY_CORE_BASE10_BYPASS_ENCODER_MASK (0x400U)
#define BRPHY_CORE_BASE10_BYPASS_ENCODER_SHIFT (10U)
#define BRPHY_CORE_BASE10_BYPASS_SCRAMBLER_MASK (0x200U)
#define BRPHY_CORE_BASE10_BYPASS_SCRAMBLER_SHIFT (9U)
#define BRPHY_CORE_BASE10_BYPASS_NRZI_MLT3_MASK (0x100U)
#define BRPHY_CORE_BASE10_BYPASS_NRZI_MLT3_SHIFT (8U)
#define BRPHY_CORE_BASE10_BYPASS_ALIGNMENT_MASK (0x80U)
#define BRPHY_CORE_BASE10_BYPASS_ALIGNMENT_SHIFT (7U)
#define BRPHY_CORE_BASE10_RESET_SCRAMBLER_MASK (0x40U)
#define BRPHY_CORE_BASE10_RESET_SCRAMBLER_SHIFT (6U)
#define BRPHY_CORE_BASE10_LED_TRAFFIC_EN_MASK (0x20U)
#define BRPHY_CORE_BASE10_LED_TRAFFIC_EN_SHIFT (5U)
#define BRPHY_CORE_BASE10_FORCE_LEDS_ON_MASK (0x10U)
#define BRPHY_CORE_BASE10_FORCE_LEDS_ON_SHIFT (4U)
#define BRPHY_CORE_BASE10_FORCE_LEDS_OFF_MASK (0x8U)
#define BRPHY_CORE_BASE10_FORCE_LEDS_OFF_SHIFT (3U)
#define BRPHY_CORE_BASE10_BLOCK_TXEN_MASK (0x4U)
#define BRPHY_CORE_BASE10_BLOCK_TXEN_SHIFT (2U)
#define BRPHY_CORE_BASE10_UNIDIR_EN_MASK (0x2U)
#define BRPHY_CORE_BASE10_UNIDIR_EN_SHIFT (1U)
#define BRPHY_CORE_BASE10_GMII_RGMII_FIFO_ELASTICITY_MASK (0x1U)
#define BRPHY_CORE_BASE10_GMII_RGMII_FIFO_ELASTICITY_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE11_TYPE;
#define BRPHY_CORE_BASE11_AUTONEG_FIELD_MISMATCH_MASK (0x8000U)
#define BRPHY_CORE_BASE11_AUTONEG_FIELD_MISMATCH_SHIFT (15U)
#define BRPHY_CORE_BASE11_WIRESPD_DOWNGRADE_MASK (0x4000U)
#define BRPHY_CORE_BASE11_WIRESPD_DOWNGRADE_SHIFT (14U)
#define BRPHY_CORE_BASE11_MDIX_STATE_MASK (0x2000U)
#define BRPHY_CORE_BASE11_MDIX_STATE_SHIFT (13U)
#define BRPHY_CORE_BASE11_INT_STATUS_MASK (0x1000U)
#define BRPHY_CORE_BASE11_INT_STATUS_SHIFT (12U)
#define BRPHY_CORE_BASE11_RMT_RCVR_STATUS_MASK (0x800U)
#define BRPHY_CORE_BASE11_RMT_RCVR_STATUS_SHIFT (11U)
#define BRPHY_CORE_BASE11_LOCAL_RCVR_STATUS_MASK (0x400U)
#define BRPHY_CORE_BASE11_LOCAL_RCVR_STATUS_SHIFT (10U)
#define BRPHY_CORE_BASE11_LOCKED_MASK (0x200U)
#define BRPHY_CORE_BASE11_LOCKED_SHIFT (9U)
#define BRPHY_CORE_BASE11_LINK_STATUS_MASK (0x100U)
#define BRPHY_CORE_BASE11_LINK_STATUS_SHIFT (8U)
#define BRPHY_CORE_BASE11_CRC_ERR_DET_MASK (0x80U)
#define BRPHY_CORE_BASE11_CRC_ERR_DET_SHIFT (7U)
#define BRPHY_CORE_BASE11_CR_EXT_ERR_DET_MASK (0x40U)
#define BRPHY_CORE_BASE11_CR_EXT_ERR_DET_SHIFT (6U)
#define BRPHY_CORE_BASE11_BAD_SSD_DET_CR_MASK (0x20U)
#define BRPHY_CORE_BASE11_BAD_SSD_DET_CR_SHIFT (5U)
#define BRPHY_CORE_BASE11_BAD_ESD_DET_END_MASK (0x10U)
#define BRPHY_CORE_BASE11_BAD_ESD_DET_END_SHIFT (4U)
#define BRPHY_CORE_BASE11_RCV_ERR_DET_MASK (0x8U)
#define BRPHY_CORE_BASE11_RCV_ERR_DET_SHIFT (3U)
#define BRPHY_CORE_BASE11_TX_ERR_DET_MASK (0x4U)
#define BRPHY_CORE_BASE11_TX_ERR_DET_SHIFT (2U)
#define BRPHY_CORE_BASE11_LOCK_ERR_DET_MASK (0x2U)
#define BRPHY_CORE_BASE11_LOCK_ERR_DET_SHIFT (1U)
#define BRPHY_CORE_BASE11_MLT3_ERR_DET_MASK (0x1U)
#define BRPHY_CORE_BASE11_MLT3_ERR_DET_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE12_TYPE;
#define BRPHY_CORE_BASE12_RCV_ERR_CNTR_MASK (0xffffU)
#define BRPHY_CORE_BASE12_RCV_ERR_CNTR_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE13_TYPE;
#define BRPHY_CORE_BASE13_SERDES_BER_CNTR_MASK (0xff00U)
#define BRPHY_CORE_BASE13_SERDES_BER_CNTR_SHIFT (8U)
#define BRPHY_CORE_BASE13_FALSE_CRS_CNTR_MASK (0xffU)
#define BRPHY_CORE_BASE13_FALSE_CRS_CNTR_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE14_TYPE;
#define BRPHY_CORE_BASE14_LOCAL_RCVR_NOK_CNTR_MASK (0xff00U)
#define BRPHY_CORE_BASE14_LOCAL_RCVR_NOK_CNTR_SHIFT (8U)
#define BRPHY_CORE_BASE14_REMOTE_RCVR_NOK_CNTR_MASK (0xffU)
#define BRPHY_CORE_BASE14_REMOTE_RCVR_NOK_CNTR_SHIFT (0U)




typedef uint16_t BRPHY_CORE_EXP45_TYPE;
#define BRPHY_CORE_EXP45_SEL_SERDES_TX_MASK (0x8000U)
#define BRPHY_CORE_EXP45_SEL_SERDES_TX_SHIFT (15U)
#define BRPHY_CORE_EXP45_TX_ERR_MASK (0x4000U)
#define BRPHY_CORE_EXP45_TX_ERR_SHIFT (14U)
#define BRPHY_CORE_EXP45_SKIP_CRC_MASK (0x2000U)
#define BRPHY_CORE_EXP45_SKIP_CRC_SHIFT (13U)
#define BRPHY_CORE_EXP45_TX_CRC_CHECKER_EN_MASK (0x1000U)
#define BRPHY_CORE_EXP45_TX_CRC_CHECKER_EN_SHIFT (12U)
#define BRPHY_CORE_EXP45_IPG_SEL_MASK (0xe00U)
#define BRPHY_CORE_EXP45_IPG_SEL_SHIFT (9U)
#define BRPHY_CORE_EXP45_PKT_SIZE_MASK (0x1f8U)
#define BRPHY_CORE_EXP45_PKT_SIZE_SHIFT (3U)
#define BRPHY_CORE_EXP45_SINGLE_PASS_MASK (0x4U)
#define BRPHY_CORE_EXP45_SINGLE_PASS_SHIFT (2U)
#define BRPHY_CORE_EXP45_RUN_PAT_GEN_MASK (0x2U)
#define BRPHY_CORE_EXP45_RUN_PAT_GEN_SHIFT (1U)
#define BRPHY_CORE_EXP45_SEL_PAT_GEN_DATA_MASK (0x1U)
#define BRPHY_CORE_EXP45_SEL_PAT_GEN_DATA_SHIFT (0U)




typedef uint16_t BRPHY_CORE_EXP46_TYPE;
#define BRPHY_CORE_EXP46_GMII_FIFO_ELASTICITY_1_MASK (0x8000U)
#define BRPHY_CORE_EXP46_GMII_FIFO_ELASTICITY_1_SHIFT (15U)
#define BRPHY_CORE_EXP46_GMII_RGMII_FIFO_ELASTICITY_1_MASK (0x4000U)
#define BRPHY_CORE_EXP46_GMII_RGMII_FIFO_ELASTICITY_1_SHIFT (14U)
#define BRPHY_CORE_EXP46_PKT_SIZE_6_MASK (0x2000U)
#define BRPHY_CORE_EXP46_PKT_SIZE_6_SHIFT (13U)
#define BRPHY_CORE_EXP46_CR_EXT_MASK (0x1000U)
#define BRPHY_CORE_EXP46_CR_EXT_SHIFT (12U)
#define BRPHY_CORE_EXP46_RGMII_FIFO_FREQ_LOCK_MASK (0x40U)
#define BRPHY_CORE_EXP46_RGMII_FIFO_FREQ_LOCK_SHIFT (6U)
#define BRPHY_CORE_EXP46_SEL_PATGEN_ON_RXD_MASK (0x10U)
#define BRPHY_CORE_EXP46_SEL_PATGEN_ON_RXD_SHIFT (4U)
#define BRPHY_CORE_EXP46_PAT_GEN_ACTIVE_MASK (0x8U)
#define BRPHY_CORE_EXP46_PAT_GEN_ACTIVE_SHIFT (3U)
#define BRPHY_CORE_EXP46_PAT_GEN_FSM_MASK (0x7U)
#define BRPHY_CORE_EXP46_PAT_GEN_FSM_SHIFT (0U)




typedef uint8_t BRPHY_CORE_RESERVED_TYPE;




typedef uint16_t BRPHY_CORE_BASE19_TYPE;
#define BRPHY_CORE_BASE19_AUTONEG_COMPLETE_MASK (0x8000U)
#define BRPHY_CORE_BASE19_AUTONEG_COMPLETE_SHIFT (15U)
#define BRPHY_CORE_BASE19_AUTONEG_COMPLETE_ACK_MASK (0x4000U)
#define BRPHY_CORE_BASE19_AUTONEG_COMPLETE_ACK_SHIFT (14U)
#define BRPHY_CORE_BASE19_AUTONEG_ACK_DET_MASK (0x2000U)
#define BRPHY_CORE_BASE19_AUTONEG_ACK_DET_SHIFT (13U)
#define BRPHY_CORE_BASE19_AUTONEG_ABILITY_DET_MASK (0x1000U)
#define BRPHY_CORE_BASE19_AUTONEG_ABILITY_DET_SHIFT (12U)
#define BRPHY_CORE_BASE19_AUTONEG_NEXT_PAGE_WAIT_MASK (0x800U)
#define BRPHY_CORE_BASE19_AUTONEG_NEXT_PAGE_WAIT_SHIFT (11U)
#define BRPHY_CORE_BASE19_AUTONEG_HCD_MASK (0x700U)
#define BRPHY_CORE_BASE19_AUTONEG_HCD_SHIFT (8U)
#define BRPHY_CORE_BASE19_PARALLEL_DET_FAULT_MASK (0x80U)
#define BRPHY_CORE_BASE19_PARALLEL_DET_FAULT_SHIFT (7U)
#define BRPHY_CORE_BASE19_REMOTE_FAULT_MASK (0x40U)
#define BRPHY_CORE_BASE19_REMOTE_FAULT_SHIFT (6U)
#define BRPHY_CORE_BASE19_PAGE_RECEIVED_MASK (0x20U)
#define BRPHY_CORE_BASE19_PAGE_RECEIVED_SHIFT (5U)
#define BRPHY_CORE_BASE19_LINK_PARTNER_AN_ABILITY_MASK (0x10U)
#define BRPHY_CORE_BASE19_LINK_PARTNER_AN_ABILITY_SHIFT (4U)
#define BRPHY_CORE_BASE19_LINK_PARTNER_NP_ABILITY_MASK (0x8U)
#define BRPHY_CORE_BASE19_LINK_PARTNER_NP_ABILITY_SHIFT (3U)
#define BRPHY_CORE_BASE19_LINK_STATUS_MASK (0x4U)
#define BRPHY_CORE_BASE19_LINK_STATUS_SHIFT (2U)
#define BRPHY_CORE_BASE19_PAUSE_RESOLUTION_RX_MASK (0x2U)
#define BRPHY_CORE_BASE19_PAUSE_RESOLUTION_RX_SHIFT (1U)
#define BRPHY_CORE_BASE19_PAUSE_RESOLUTION_TX_MASK (0x1U)
#define BRPHY_CORE_BASE19_PAUSE_RESOLUTION_TX_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE1A_TYPE;
#define BRPHY_CORE_BASE1A_IP_STATUS_CHANGE_MASK (0x8000U)
#define BRPHY_CORE_BASE1A_IP_STATUS_CHANGE_SHIFT (15U)
#define BRPHY_CORE_BASE1A_ILLEGAL_PAIR_SWAP_MASK (0x4000U)
#define BRPHY_CORE_BASE1A_ILLEGAL_PAIR_SWAP_SHIFT (14U)
#define BRPHY_CORE_BASE1A_MDIX_STATUS_CHANGE_MASK (0x2000U)
#define BRPHY_CORE_BASE1A_MDIX_STATUS_CHANGE_SHIFT (13U)
#define BRPHY_CORE_BASE1A_EXCEED_HIGH_CNTR_THD_MASK (0x1000U)
#define BRPHY_CORE_BASE1A_EXCEED_HIGH_CNTR_THD_SHIFT (12U)
#define BRPHY_CORE_BASE1A_EXCEED_LOW_CNTR_THD_MASK (0x800U)
#define BRPHY_CORE_BASE1A_EXCEED_LOW_CNTR_THD_SHIFT (11U)
#define BRPHY_CORE_BASE1A_AUTONEG_PAGE_RX_MASK (0x400U)
#define BRPHY_CORE_BASE1A_AUTONEG_PAGE_RX_SHIFT (10U)
#define BRPHY_CORE_BASE1A_HCD_NO_LINK_MASK (0x200U)
#define BRPHY_CORE_BASE1A_HCD_NO_LINK_SHIFT (9U)
#define BRPHY_CORE_BASE1A_NO_HCD_MASK (0x100U)
#define BRPHY_CORE_BASE1A_NO_HCD_SHIFT (8U)
#define BRPHY_CORE_BASE1A_NEGOTIATED_UNSUPPORTED_HCD_MASK (0x80U)
#define BRPHY_CORE_BASE1A_NEGOTIATED_UNSUPPORTED_HCD_SHIFT (7U)
#define BRPHY_CORE_BASE1A_SCR_SYNC_ERROR_MASK (0x40U)
#define BRPHY_CORE_BASE1A_SCR_SYNC_ERROR_SHIFT (6U)
#define BRPHY_CORE_BASE1A_RMT_RCVR_STATUS_CHANGE_MASK (0x20U)
#define BRPHY_CORE_BASE1A_RMT_RCVR_STATUS_CHANGE_SHIFT (5U)
#define BRPHY_CORE_BASE1A_LOCAL_RCVR_STATUS_CHANGE_MASK (0x10U)
#define BRPHY_CORE_BASE1A_LOCAL_RCVR_STATUS_CHANGE_SHIFT (4U)
#define BRPHY_CORE_BASE1A_DUPLEX_CHANGE_MASK (0x8U)
#define BRPHY_CORE_BASE1A_DUPLEX_CHANGE_SHIFT (3U)
#define BRPHY_CORE_BASE1A_LINK_SPEED_CHANGE_MASK (0x4U)
#define BRPHY_CORE_BASE1A_LINK_SPEED_CHANGE_SHIFT (2U)
#define BRPHY_CORE_BASE1A_LINK_STATUS_CHANGE_MASK (0x2U)
#define BRPHY_CORE_BASE1A_LINK_STATUS_CHANGE_SHIFT (1U)
#define BRPHY_CORE_BASE1A_CRC_ERROR_MASK (0x1U)
#define BRPHY_CORE_BASE1A_CRC_ERROR_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE1B_TYPE;
#define BRPHY_CORE_BASE1B_INT_MASK_VECTOR_MASK (0xffffU)
#define BRPHY_CORE_BASE1B_INT_MASK_VECTOR_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE1D_SHD_TYPE;
#define BRPHY_CORE_BASE1D_SHD_ENABLE_SHADOW_REGISTER_MASK (0x8000U)
#define BRPHY_CORE_BASE1D_SHD_ENABLE_SHADOW_REGISTER_SHIFT (15U)
#define BRPHY_CORE_BASE1D_SHD_GB_ADV_DIS_MASK (0x4000U)
#define BRPHY_CORE_BASE1D_SHD_GB_ADV_DIS_SHIFT (14U)
#define BRPHY_CORE_BASE1D_SHD_TX_ADV_DIS_MASK (0x2000U)
#define BRPHY_CORE_BASE1D_SHD_TX_ADV_DIS_SHIFT (13U)
#define BRPHY_CORE_BASE1D_SHD_WIRESPEED_DOWNGRADE_MASK (0x1000U)
#define BRPHY_CORE_BASE1D_SHD_WIRESPEED_DOWNGRADE_SHIFT (12U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_FDX_MASK (0x800U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_FDX_SHIFT (11U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_MASK (0x400U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_SHIFT (10U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_FDX_MASK (0x200U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_FDX_SHIFT (9U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_MASK (0x100U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_SHIFT (8U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_FDX_MASK (0x80U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_FDX_SHIFT (7U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_MASK (0x40U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_SHIFT (6U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_FDX_NL_MASK (0x20U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_FDX_NL_SHIFT (5U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_NL_MASK (0x10U)
#define BRPHY_CORE_BASE1D_SHD_HCD_1000T_NL_SHIFT (4U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_FDX_NL_MASK (0x8U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_FDX_NL_SHIFT (3U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_NL_MASK (0x4U)
#define BRPHY_CORE_BASE1D_SHD_HCD_100T_NL_SHIFT (2U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_FDX_NL_MASK (0x2U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_FDX_NL_SHIFT (1U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_NL_MASK (0x1U)
#define BRPHY_CORE_BASE1D_SHD_HCD_10T_NL_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE1D_TYPE;
#define BRPHY_CORE_BASE1D_ENABLE_SHADOW_REGISTER_MASK (0x8000U)
#define BRPHY_CORE_BASE1D_ENABLE_SHADOW_REGISTER_SHIFT (15U)
#define BRPHY_CORE_BASE1D_MASTER_SLAVE_SEED_MATCH_MASK (0x4000U)
#define BRPHY_CORE_BASE1D_MASTER_SLAVE_SEED_MATCH_SHIFT (14U)
#define BRPHY_CORE_BASE1D_LINK_PARTNER_RD_BIT_MASK (0x2000U)
#define BRPHY_CORE_BASE1D_LINK_PARTNER_RD_BIT_SHIFT (13U)
#define BRPHY_CORE_BASE1D_LINK_PARTNER_MS_VALUE_MASK (0x1000U)
#define BRPHY_CORE_BASE1D_LINK_PARTNER_MS_VALUE_SHIFT (12U)
#define BRPHY_CORE_BASE1D_LINK_PARTNER_MS_CFG_EN_MASK (0x800U)
#define BRPHY_CORE_BASE1D_LINK_PARTNER_MS_CFG_EN_SHIFT (11U)
#define BRPHY_CORE_BASE1D_LOCAL_MS_SEED_VALUE_MASK (0x7ffU)
#define BRPHY_CORE_BASE1D_LOCAL_MS_SEED_VALUE_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE1E_TYPE;
#define BRPHY_CORE_BASE1E_CRC_ERR_CNT_MASK (0x8000U)
#define BRPHY_CORE_BASE1E_CRC_ERR_CNT_SHIFT (15U)
#define BRPHY_CORE_BASE1E_TX_ERR_CODE_MASK (0x4000U)
#define BRPHY_CORE_BASE1E_TX_ERR_CODE_SHIFT (14U)
#define BRPHY_CORE_BASE1E_CNTR_TEST_MASK (0x2000U)
#define BRPHY_CORE_BASE1E_CNTR_TEST_SHIFT (13U)
#define BRPHY_CORE_BASE1E_FORCE_LINK_MASK (0x1000U)
#define BRPHY_CORE_BASE1E_FORCE_LINK_SHIFT (12U)
#define BRPHY_CORE_BASE1E_FORCE_LOCK_MASK (0x800U)
#define BRPHY_CORE_BASE1E_FORCE_LOCK_SHIFT (11U)
#define BRPHY_CORE_BASE1E_SCR_TEST_MASK (0x400U)
#define BRPHY_CORE_BASE1E_SCR_TEST_SHIFT (10U)
#define BRPHY_CORE_BASE1E_EXT_LINK_MASK (0x200U)
#define BRPHY_CORE_BASE1E_EXT_LINK_SHIFT (9U)
#define BRPHY_CORE_BASE1E_FAST_TIMERS_MASK (0x100U)
#define BRPHY_CORE_BASE1E_FAST_TIMERS_SHIFT (8U)
#define BRPHY_CORE_BASE1E_MANUAL_SWAP_MDI_MASK (0x80U)
#define BRPHY_CORE_BASE1E_MANUAL_SWAP_MDI_SHIFT (7U)
#define BRPHY_CORE_BASE1E_RX_WATCHDOG_TIMER_DIS_MASK (0x40U)
#define BRPHY_CORE_BASE1E_RX_WATCHDOG_TIMER_DIS_SHIFT (6U)
#define BRPHY_CORE_BASE1E_POLARITY_ENCODE_DIS_MASK (0x20U)
#define BRPHY_CORE_BASE1E_POLARITY_ENCODE_DIS_SHIFT (5U)
#define BRPHY_CORE_BASE1E_SOFT_TRIM_SETTING_EN_MASK (0x10U)
#define BRPHY_CORE_BASE1E_SOFT_TRIM_SETTING_EN_SHIFT (4U)
#define BRPHY_CORE_BASE1E_TRIM_MAIN_DAC_MASK (0xfU)
#define BRPHY_CORE_BASE1E_TRIM_MAIN_DAC_SHIFT (0U)




typedef uint16_t BRPHY_CORE_BASE1F_TYPE;
#define BRPHY_CORE_BASE1F_TEST_SEL_AUTONEG_FSM_MASK (0xe000U)
#define BRPHY_CORE_BASE1F_TEST_SEL_AUTONEG_FSM_SHIFT (13U)
#define BRPHY_CORE_BASE1F_TEST_AUTONEG_TIMER_MASK (0x1000U)
#define BRPHY_CORE_BASE1F_TEST_AUTONEG_TIMER_SHIFT (12U)
#define BRPHY_CORE_BASE1F_TEST_MS_SEED_MASK (0x800U)
#define BRPHY_CORE_BASE1F_TEST_MS_SEED_SHIFT (11U)
#define BRPHY_CORE_BASE1F_WR_LINK_PARTNER_ABILITY_EN_MASK (0x400U)
#define BRPHY_CORE_BASE1F_WR_LINK_PARTNER_ABILITY_EN_SHIFT (10U)
#define BRPHY_CORE_BASE1F_FORCE_HCD_MASK (0x200U)
#define BRPHY_CORE_BASE1F_FORCE_HCD_SHIFT (9U)
#define BRPHY_CORE_BASE1F_WR_LINK_PARTNER_MS_SEED_EN_MASK (0x100U)
#define BRPHY_CORE_BASE1F_WR_LINK_PARTNER_MS_SEED_EN_SHIFT (8U)
#define BRPHY_CORE_BASE1F_TX_10B_MASK (0x80U)
#define BRPHY_CORE_BASE1F_TX_10B_SHIFT (7U)
#define BRPHY_CORE_BASE1F_RX_10B_MASK (0x40U)
#define BRPHY_CORE_BASE1F_RX_10B_SHIFT (6U)
#define BRPHY_CORE_BASE1F_BYPASS_TXFIFO_MASK (0x20U)
#define BRPHY_CORE_BASE1F_BYPASS_TXFIFO_SHIFT (5U)
#define BRPHY_CORE_BASE1F_SAME_SCR_SEEDS_MASK (0x10U)
#define BRPHY_CORE_BASE1F_SAME_SCR_SEEDS_SHIFT (4U)
#define BRPHY_CORE_BASE1F_JITTER_TEST_MASK (0x8U)
#define BRPHY_CORE_BASE1F_JITTER_TEST_SHIFT (3U)
#define BRPHY_CORE_BASE1F_TEST_ATMP_CNTR_MASK (0x4U)
#define BRPHY_CORE_BASE1F_TEST_ATMP_CNTR_SHIFT (2U)
#define BRPHY_CORE_BASE1F_LATENCY_MEASURE_MASK (0x2U)
#define BRPHY_CORE_BASE1F_LATENCY_MEASURE_SHIFT (1U)
#define BRPHY_CORE_BASE1F_ACTIVE_HYBRID_DIS_MASK (0x1U)
#define BRPHY_CORE_BASE1F_ACTIVE_HYBRID_DIS_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_00_TYPE;
#define BRPHY_CORE_SHD1C_00_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_00_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_00_CABLETRON_LED_MASK (0xffU)
#define BRPHY_CORE_SHD1C_00_CABLETRON_LED_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_01_TYPE;
#define BRPHY_CORE_SHD1C_01_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_01_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_01_TVCO_OUTPUT_MASK (0x7fU)
#define BRPHY_CORE_SHD1C_01_TVCO_OUTPUT_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_02_TYPE;
#define BRPHY_CORE_SHD1C_02_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_02_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_02_SD_STATUS_MASK (0x200U)
#define BRPHY_CORE_SHD1C_02_SD_STATUS_SHIFT (9U)
#define BRPHY_CORE_SHD1C_02_FORCE_SD_ON_MASK (0x100U)
#define BRPHY_CORE_SHD1C_02_FORCE_SD_ON_SHIFT (8U)
#define BRPHY_CORE_SHD1C_02_INVERT_SD_PIN_MASK (0x80U)
#define BRPHY_CORE_SHD1C_02_INVERT_SD_PIN_SHIFT (7U)
#define BRPHY_CORE_SHD1C_02_CFC_INITFILTER_EN_MASK (0x40U)
#define BRPHY_CORE_SHD1C_02_CFC_INITFILTER_EN_SHIFT (6U)
#define BRPHY_CORE_SHD1C_02_USE_FILTERED_SD_MASK (0x20U)
#define BRPHY_CORE_SHD1C_02_USE_FILTERED_SD_SHIFT (5U)
#define BRPHY_CORE_SHD1C_02_FX_COPPER_PATH_MASK (0x10U)
#define BRPHY_CORE_SHD1C_02_FX_COPPER_PATH_SHIFT (4U)
#define BRPHY_CORE_SHD1C_02_SPARE_REG_MASK (0x8U)
#define BRPHY_CORE_SHD1C_02_SPARE_REG_SHIFT (3U)
#define BRPHY_CORE_SHD1C_02_BC_LINK_SPEED_LED_MASK (0x4U)
#define BRPHY_CORE_SHD1C_02_BC_LINK_SPEED_LED_SHIFT (2U)
#define BRPHY_CORE_SHD1C_02_LOST_TOKEN_FIX_DIS_MASK (0x2U)
#define BRPHY_CORE_SHD1C_02_LOST_TOKEN_FIX_DIS_SHIFT (1U)
#define BRPHY_CORE_SHD1C_02_LINK_LED_MASK (0x1U)
#define BRPHY_CORE_SHD1C_02_LINK_LED_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_03_TYPE;
#define BRPHY_CORE_SHD1C_03_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_03_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_03_GTXCLK_DLY_EN_MASK (0x200U)
#define BRPHY_CORE_SHD1C_03_GTXCLK_DLY_EN_SHIFT (9U)
#define BRPHY_CORE_SHD1C_03_GMII_CLK_ALIGN_STRB_MASK (0x100U)
#define BRPHY_CORE_SHD1C_03_GMII_CLK_ALIGN_STRB_SHIFT (8U)
#define BRPHY_CORE_SHD1C_03_RXCLK_ALIGN_STRB_MASK (0x80U)
#define BRPHY_CORE_SHD1C_03_RXCLK_ALIGN_STRB_SHIFT (7U)
#define BRPHY_CORE_SHD1C_03_DLY_VALUE_MASK (0x70U)
#define BRPHY_CORE_SHD1C_03_DLY_VALUE_SHIFT (4U)
#define BRPHY_CORE_SHD1C_03_DLY_LINE_SEL_MASK (0xfU)
#define BRPHY_CORE_SHD1C_03_DLY_LINE_SEL_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_04_TYPE;
#define BRPHY_CORE_SHD1C_04_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_04_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_04_SPARE_REG_MASK (0x200U)
#define BRPHY_CORE_SHD1C_04_SPARE_REG_SHIFT (9U)
#define BRPHY_CORE_SHD1C_04_WIRESPEED_RETRY_DIS_MASK (0x100U)
#define BRPHY_CORE_SHD1C_04_WIRESPEED_RETRY_DIS_SHIFT (8U)
#define BRPHY_CORE_SHD1C_04_SELECT_TPOUT_RXD_MASK (0x80U)
#define BRPHY_CORE_SHD1C_04_SELECT_TPOUT_RXD_SHIFT (7U)
#define BRPHY_CORE_SHD1C_04_DISABLE_PHYA2_MASK (0x40U)
#define BRPHY_CORE_SHD1C_04_DISABLE_PHYA2_SHIFT (6U)
#define BRPHY_CORE_SHD1C_04_RBC_TXC_RXC_TRI_MASK (0x20U)
#define BRPHY_CORE_SHD1C_04_RBC_TXC_RXC_TRI_SHIFT (5U)
#define BRPHY_CORE_SHD1C_04_WIRESPEED_RETRY_LIMIT_MASK (0x1cU)
#define BRPHY_CORE_SHD1C_04_WIRESPEED_RETRY_LIMIT_SHIFT (2U)
#define BRPHY_CORE_SHD1C_04_ENG_DET_ON_INTR_PIN_MASK (0x2U)
#define BRPHY_CORE_SHD1C_04_ENG_DET_ON_INTR_PIN_SHIFT (1U)
#define BRPHY_CORE_SHD1C_04_TESTONBYTE7_0_MASK (0x1U)
#define BRPHY_CORE_SHD1C_04_TESTONBYTE7_0_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_05_TYPE;
#define BRPHY_CORE_SHD1C_05_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_05_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_05_DLL_LOCK_EN_MASK (0x200U)
#define BRPHY_CORE_SHD1C_05_DLL_LOCK_EN_SHIFT (9U)
#define BRPHY_CORE_SHD1C_05_TXC_RXC_DIS_MASK (0x100U)
#define BRPHY_CORE_SHD1C_05_TXC_RXC_DIS_SHIFT (8U)
#define BRPHY_CORE_SHD1C_05_BT_R_REJECT_FILTER_MASK (0x80U)
#define BRPHY_CORE_SHD1C_05_BT_R_REJECT_FILTER_SHIFT (7U)
#define BRPHY_CORE_SHD1C_05_TXC_OFF_EN_MASK (0x40U)
#define BRPHY_CORE_SHD1C_05_TXC_OFF_EN_SHIFT (6U)
#define BRPHY_CORE_SHD1C_05_SD_CHANGE_MUX_SEL_MASK (0x20U)
#define BRPHY_CORE_SHD1C_05_SD_CHANGE_MUX_SEL_SHIFT (5U)
#define BRPHY_CORE_SHD1C_05_LOW_POWER_ENC_DIS_MASK (0x10U)
#define BRPHY_CORE_SHD1C_05_LOW_POWER_ENC_DIS_SHIFT (4U)
#define BRPHY_CORE_SHD1C_05_LOW_POWER_BT_DIS_MASK (0x8U)
#define BRPHY_CORE_SHD1C_05_LOW_POWER_BT_DIS_SHIFT (3U)
#define BRPHY_CORE_SHD1C_05_SD_DEASSERT_TIMER_LEN_MASK (0x4U)
#define BRPHY_CORE_SHD1C_05_SD_DEASSERT_TIMER_LEN_SHIFT (2U)
#define BRPHY_CORE_SHD1C_05_AUTO_PWRDN_DLL_DIS_MASK (0x2U)
#define BRPHY_CORE_SHD1C_05_AUTO_PWRDN_DLL_DIS_SHIFT (1U)
#define BRPHY_CORE_SHD1C_05_CLK125_OUTPUT_EN_MASK (0x1U)
#define BRPHY_CORE_SHD1C_05_CLK125_OUTPUT_EN_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_06_TYPE;
#define BRPHY_CORE_SHD1C_06_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_06_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_06_SPARE_REG_MASK (0x200U)
#define BRPHY_CORE_SHD1C_06_SPARE_REG_SHIFT (9U)
#define BRPHY_CORE_SHD1C_06_TDR_LINK_TIME_OUT_MASK (0x100U)
#define BRPHY_CORE_SHD1C_06_TDR_LINK_TIME_OUT_SHIFT (8U)
#define BRPHY_CORE_SHD1C_06_TEST_PULSE_SIZE_MASK (0xe0U)
#define BRPHY_CORE_SHD1C_06_TEST_PULSE_SIZE_SHIFT (5U)
#define BRPHY_CORE_SHD1C_06_TX_CHANNEL_SEL_MASK (0x18U)
#define BRPHY_CORE_SHD1C_06_TX_CHANNEL_SEL_SHIFT (3U)
#define BRPHY_CORE_SHD1C_06_RX_CHANNEL_SEL_MASK (0x6U)
#define BRPHY_CORE_SHD1C_06_RX_CHANNEL_SEL_SHIFT (1U)
#define BRPHY_CORE_SHD1C_06_TDR_START_MASK (0x1U)
#define BRPHY_CORE_SHD1C_06_TDR_START_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_07_TYPE;
#define BRPHY_CORE_SHD1C_07_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_07_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_07_SPARE_REG_MASK (0x300U)
#define BRPHY_CORE_SHD1C_07_SPARE_REG_SHIFT (8U)
#define BRPHY_CORE_SHD1C_07_PHASE_STATUS_MASK (0x80U)
#define BRPHY_CORE_SHD1C_07_PHASE_STATUS_SHIFT (7U)
#define BRPHY_CORE_SHD1C_07_PHASE_STATUS_CLEAR_MASK (0x40U)
#define BRPHY_CORE_SHD1C_07_PHASE_STATUS_CLEAR_SHIFT (6U)
#define BRPHY_CORE_SHD1C_07_FASTTIMERS_MASK (0x20U)
#define BRPHY_CORE_SHD1C_07_FASTTIMERS_SHIFT (5U)
#define BRPHY_CORE_SHD1C_07_FEXT_MASK (0x10U)
#define BRPHY_CORE_SHD1C_07_FEXT_SHIFT (4U)
#define BRPHY_CORE_SHD1C_07_MASTER_MASK (0x8U)
#define BRPHY_CORE_SHD1C_07_MASTER_SHIFT (3U)
#define BRPHY_CORE_SHD1C_07_EXT_PHY_NO_AUTONEG_MASK (0x4U)
#define BRPHY_CORE_SHD1C_07_EXT_PHY_NO_AUTONEG_SHIFT (2U)
#define BRPHY_CORE_SHD1C_07_EXT_PHY_MASK (0x2U)
#define BRPHY_CORE_SHD1C_07_EXT_PHY_SHIFT (1U)
#define BRPHY_CORE_SHD1C_07_TDR_EN_MASK (0x1U)
#define BRPHY_CORE_SHD1C_07_TDR_EN_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_08_TYPE;
#define BRPHY_CORE_SHD1C_08_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_08_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_08_SLAVE_N_MASK (0x100U)
#define BRPHY_CORE_SHD1C_08_SLAVE_N_SHIFT (8U)
#define BRPHY_CORE_SHD1C_08_FDXLED_N_MASK (0x80U)
#define BRPHY_CORE_SHD1C_08_FDXLED_N_SHIFT (7U)
#define BRPHY_CORE_SHD1C_08_INTR_N_MASK (0x40U)
#define BRPHY_CORE_SHD1C_08_INTR_N_SHIFT (6U)
#define BRPHY_CORE_SHD1C_08_LINKSPD_N_MASK (0x18U)
#define BRPHY_CORE_SHD1C_08_LINKSPD_N_SHIFT (3U)
#define BRPHY_CORE_SHD1C_08_TRANSMIT_LED_MASK (0x4U)
#define BRPHY_CORE_SHD1C_08_TRANSMIT_LED_SHIFT (2U)
#define BRPHY_CORE_SHD1C_08_RECEIVE_LED_MASK (0x2U)
#define BRPHY_CORE_SHD1C_08_RECEIVE_LED_SHIFT (1U)
#define BRPHY_CORE_SHD1C_08_QUALITY_LED_MASK (0x1U)
#define BRPHY_CORE_SHD1C_08_QUALITY_LED_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_09_TYPE;
#define BRPHY_CORE_SHD1C_09_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_09_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_09_COL_BLINK_MASK (0x200U)
#define BRPHY_CORE_SHD1C_09_COL_BLINK_SHIFT (9U)
#define BRPHY_CORE_SHD1C_09_ACT_LINK_MSB_MASK (0x100U)
#define BRPHY_CORE_SHD1C_09_ACT_LINK_MSB_SHIFT (8U)
#define BRPHY_CORE_SHD1C_09_SPARE_REG_MASK (0x80U)
#define BRPHY_CORE_SHD1C_09_SPARE_REG_SHIFT (7U)
#define BRPHY_CORE_SHD1C_09_EXT_SERDES_INUSE_MASK (0x40U)
#define BRPHY_CORE_SHD1C_09_EXT_SERDES_INUSE_SHIFT (6U)
#define BRPHY_CORE_SHD1C_09_OV_GBIC_LED_MASK (0x20U)
#define BRPHY_CORE_SHD1C_09_OV_GBIC_LED_SHIFT (5U)
#define BRPHY_CORE_SHD1C_09_ACT_LINK_LSB_MASK (0x10U)
#define BRPHY_CORE_SHD1C_09_ACT_LINK_LSB_SHIFT (4U)
#define BRPHY_CORE_SHD1C_09_ACTIVITY_LED_EN_MASK (0x8U)
#define BRPHY_CORE_SHD1C_09_ACTIVITY_LED_EN_SHIFT (3U)
#define BRPHY_CORE_SHD1C_09_RMT_FAULT_LED_EN_MASK (0x4U)
#define BRPHY_CORE_SHD1C_09_RMT_FAULT_LED_EN_SHIFT (2U)
#define BRPHY_CORE_SHD1C_09_LINK_UTIL_LED_SEL_MASK (0x3U)
#define BRPHY_CORE_SHD1C_09_LINK_UTIL_LED_SEL_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_0A_TYPE;
#define BRPHY_CORE_SHD1C_0A_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_0A_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_0A_APD_SINGLELP_ENABLE_MASK (0x100U)
#define BRPHY_CORE_SHD1C_0A_APD_SINGLELP_ENABLE_SHIFT (8U)
#define BRPHY_CORE_SHD1C_0A_LOWPWR136_ENC_EN_MASK (0x80U)
#define BRPHY_CORE_SHD1C_0A_LOWPWR136_ENC_EN_SHIFT (7U)
#define BRPHY_CORE_SHD1C_0A_AUTO_PWRDN_IGNORE_AUTONEG_MASK (0x40U)
#define BRPHY_CORE_SHD1C_0A_AUTO_PWRDN_IGNORE_AUTONEG_SHIFT (6U)
#define BRPHY_CORE_SHD1C_0A_AUTO_PWRDN_EN_MASK (0x20U)
#define BRPHY_CORE_SHD1C_0A_AUTO_PWRDN_EN_SHIFT (5U)
#define BRPHY_CORE_SHD1C_0A_SLEEP_TIMER_SEL_MASK (0x10U)
#define BRPHY_CORE_SHD1C_0A_SLEEP_TIMER_SEL_SHIFT (4U)
#define BRPHY_CORE_SHD1C_0A_WAKE_UP_TIMER_SEL_MASK (0xfU)
#define BRPHY_CORE_SHD1C_0A_WAKE_UP_TIMER_SEL_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_0B_TYPE;
#define BRPHY_CORE_SHD1C_0B_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_0B_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_0B_SPARE_CTL4_MASK (0xfeU)
#define BRPHY_CORE_SHD1C_0B_SPARE_CTL4_SHIFT (1U)
#define BRPHY_CORE_SHD1C_0B_DIS_CL45_MASK (0x1U)
#define BRPHY_CORE_SHD1C_0B_DIS_CL45_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_0D_TYPE;
#define BRPHY_CORE_SHD1C_0D_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_0D_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_0D_LED2_SEL_MASK (0xf0U)
#define BRPHY_CORE_SHD1C_0D_LED2_SEL_SHIFT (4U)
#define BRPHY_CORE_SHD1C_0D_LED1_SEL_MASK (0xfU)
#define BRPHY_CORE_SHD1C_0D_LED1_SEL_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_0E_TYPE;
#define BRPHY_CORE_SHD1C_0E_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_0E_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_0E_LED4_SEL_MASK (0xf0U)
#define BRPHY_CORE_SHD1C_0E_LED4_SEL_SHIFT (4U)
#define BRPHY_CORE_SHD1C_0E_LED3_SEL_MASK (0xfU)
#define BRPHY_CORE_SHD1C_0E_LED3_SEL_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_0F_TYPE;
#define BRPHY_CORE_SHD1C_0F_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_0F_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_0F_CURRENT_MODE_LED_EN_MASK (0xfU)
#define BRPHY_CORE_SHD1C_0F_CURRENT_MODE_LED_EN_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_10_TYPE;
#define BRPHY_CORE_SHD1C_10_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_10_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_10_SPARE_REG_MASK (0x80U)
#define BRPHY_CORE_SHD1C_10_SPARE_REG_SHIFT (7U)
#define BRPHY_CORE_SHD1C_10_USE_ALT_LINKFLT_MASK (0x40U)
#define BRPHY_CORE_SHD1C_10_USE_ALT_LINKFLT_SHIFT (6U)
#define BRPHY_CORE_SHD1C_10_VISIBLE_BLINK_MASK (0x20U)
#define BRPHY_CORE_SHD1C_10_VISIBLE_BLINK_SHIFT (5U)
#define BRPHY_CORE_SHD1C_10_ENHANCED_PWR_MASK (0x10U)
#define BRPHY_CORE_SHD1C_10_ENHANCED_PWR_SHIFT (4U)
#define BRPHY_CORE_SHD1C_10_DISCONNECT_TIMER_VALUE_MASK (0xfU)
#define BRPHY_CORE_SHD1C_10_DISCONNECT_TIMER_VALUE_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD1C_1F_TYPE;
#define BRPHY_CORE_SHD1C_1F_SHD1C_SEL_MASK (0x7c00U)
#define BRPHY_CORE_SHD1C_1F_SHD1C_SEL_SHIFT (10U)
#define BRPHY_CORE_SHD1C_1F_DUAL_SERDES_CAPABLE_MASK (0x200U)
#define BRPHY_CORE_SHD1C_1F_DUAL_SERDES_CAPABLE_SHIFT (9U)
#define BRPHY_CORE_SHD1C_1F_MODE_SEL_CHANGE_MASK (0x100U)
#define BRPHY_CORE_SHD1C_1F_MODE_SEL_CHANGE_SHIFT (8U)
#define BRPHY_CORE_SHD1C_1F_COPPER_LINK_MASK (0x80U)
#define BRPHY_CORE_SHD1C_1F_COPPER_LINK_SHIFT (7U)
#define BRPHY_CORE_SHD1C_1F_SERDES_LINK_MASK (0x40U)
#define BRPHY_CORE_SHD1C_1F_SERDES_LINK_SHIFT (6U)
#define BRPHY_CORE_SHD1C_1F_COPPER_ENG_DET_MASK (0x20U)
#define BRPHY_CORE_SHD1C_1F_COPPER_ENG_DET_SHIFT (5U)
#define BRPHY_CORE_SHD1C_1F_FIBER_SIGNAL_DET_MASK (0x10U)
#define BRPHY_CORE_SHD1C_1F_FIBER_SIGNAL_DET_SHIFT (4U)
#define BRPHY_CORE_SHD1C_1F_SERDES_CAPABLE_MASK (0x8U)
#define BRPHY_CORE_SHD1C_1F_SERDES_CAPABLE_SHIFT (3U)
#define BRPHY_CORE_SHD1C_1F_MODE_SEL_MASK (0x6U)
#define BRPHY_CORE_SHD1C_1F_MODE_SEL_SHIFT (1U)
#define BRPHY_CORE_SHD1C_1F_REG_1000X_EN_MASK (0x1U)
#define BRPHY_CORE_SHD1C_1F_REG_1000X_EN_SHIFT (0U)




typedef uint16_t BRPHY_CORE_SHD18_000_TYPE;
#define BRPHY_CORE_SHD18_000_EXT_LPBK_MASK (0x8000U)
#define BRPHY_CORE_SHD18_000_EXT_LPBK_SHIFT (15U)
#define BRPHY_CORE_SHD18_000_EXT_PKT_LEN_MASK (0x4000U)
#define BRPHY_CORE_SHD18_000_EXT_PKT_LEN_SHIFT (14U)
#define BRPHY_CORE_SHD18_000_EDGERATE_CTL_1000T_MASK (0x3000U)
#define BRPHY_CORE_SHD18_000_EDGERATE_CTL_1000T_SHIFT (12U)
#define BRPHY_CORE_SHD18_000_SM_DSP_CLK_EN_MASK (0x800U)
#define BRPHY_CORE_SHD18_000_SM_DSP_CLK_EN_SHIFT (11U)
#define BRPHY_CORE_SHD18_000_TX_6DB_CODING_MASK (0x400U)
#define BRPHY_CORE_SHD18_000_TX_6DB_CODING_SHIFT (10U)
#define BRPHY_CORE_SHD18_000_RCV_SLICING_MASK (0x300U)
#define BRPHY_CORE_SHD18_000_RCV_SLICING_SHIFT (8U)
#define BRPHY_CORE_SHD18_000_PRF_DIS_MASK (0x80U)
#define BRPHY_CORE_SHD18_000_PRF_DIS_SHIFT (7U)
#define BRPHY_CORE_SHD18_000_INVERSE_PRF_DIS_MASK (0x40U)
#define BRPHY_CORE_SHD18_000_INVERSE_PRF_DIS_SHIFT (6U)
#define BRPHY_CORE_SHD18_000_EDGERATE_CTL_100TX_MASK (0x30U)
#define BRPHY_CORE_SHD18_000_EDGERATE_CTL_100TX_SHIFT (4U)
#define BRPHY_CORE_SHD18_000_DIAGNOSTIC_MASK (0x8U)
#define BRPHY_CORE_SHD18_000_DIAGNOSTIC_SHIFT (3U)
#define BRPHY_CORE_SHD18_000_SHD18_SEL_MASK (0x7U)
#define BRPHY_CORE_SHD18_000_SHD18_SEL_SHIFT (0U)




typedef volatile struct COMP_PACKED _BRPHY_CORE_RDBType {
    BRPHY_CORE_BASE10_TYPE base10; /* OFFSET: 0x0 */
    BRPHY_CORE_BASE11_TYPE base11; /* OFFSET: 0x2 */
    BRPHY_CORE_BASE12_TYPE base12; /* OFFSET: 0x4 */
    BRPHY_CORE_BASE13_TYPE base13; /* OFFSET: 0x6 */
    BRPHY_CORE_BASE14_TYPE base14; /* OFFSET: 0x8 */
    BRPHY_CORE_EXP45_TYPE exp45; /* OFFSET: 0xa */
    BRPHY_CORE_EXP46_TYPE exp46; /* OFFSET: 0xc */
    BRPHY_CORE_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0xe */
    BRPHY_CORE_BASE19_TYPE base19; /* OFFSET: 0x12 */
    BRPHY_CORE_BASE1A_TYPE base1a; /* OFFSET: 0x14 */
    BRPHY_CORE_BASE1B_TYPE base1b; /* OFFSET: 0x16 */
    BRPHY_CORE_BASE1D_SHD_TYPE base1d_shd; /* OFFSET: 0x18 */
    BRPHY_CORE_BASE1D_TYPE base1d; /* OFFSET: 0x1a */
    BRPHY_CORE_BASE1E_TYPE base1e; /* OFFSET: 0x1c */
    BRPHY_CORE_BASE1F_TYPE base1f; /* OFFSET: 0x1e */
    BRPHY_CORE_SHD1C_00_TYPE shd1c_00; /* OFFSET: 0x20 */
    BRPHY_CORE_SHD1C_01_TYPE shd1c_01; /* OFFSET: 0x22 */
    BRPHY_CORE_SHD1C_02_TYPE shd1c_02; /* OFFSET: 0x24 */
    BRPHY_CORE_SHD1C_03_TYPE shd1c_03; /* OFFSET: 0x26 */
    BRPHY_CORE_SHD1C_04_TYPE shd1c_04; /* OFFSET: 0x28 */
    BRPHY_CORE_SHD1C_05_TYPE shd1c_05; /* OFFSET: 0x2a */
    BRPHY_CORE_SHD1C_06_TYPE shd1c_06; /* OFFSET: 0x2c */
    BRPHY_CORE_SHD1C_07_TYPE shd1c_07; /* OFFSET: 0x2e */
    BRPHY_CORE_SHD1C_08_TYPE shd1c_08; /* OFFSET: 0x30 */
    BRPHY_CORE_SHD1C_09_TYPE shd1c_09; /* OFFSET: 0x32 */
    BRPHY_CORE_SHD1C_0A_TYPE shd1c_0a; /* OFFSET: 0x34 */
    BRPHY_CORE_SHD1C_0B_TYPE shd1c_0b; /* OFFSET: 0x36 */
    BRPHY_CORE_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x38 */
    BRPHY_CORE_SHD1C_0D_TYPE shd1c_0d; /* OFFSET: 0x3a */
    BRPHY_CORE_SHD1C_0E_TYPE shd1c_0e; /* OFFSET: 0x3c */
    BRPHY_CORE_SHD1C_0F_TYPE shd1c_0f; /* OFFSET: 0x3e */
    BRPHY_CORE_SHD1C_10_TYPE shd1c_10; /* OFFSET: 0x40 */
    BRPHY_CORE_SHD1C_1F_TYPE shd1c_1f; /* OFFSET: 0x42 */
    BRPHY_CORE_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x44 */
    BRPHY_CORE_SHD18_000_TYPE shd18_000; /* OFFSET: 0x50 */
    BRPHY_CORE_RESERVED_TYPE rsvd3[430]; /* OFFSET: 0x52 */
} BRPHY_CORE_RDBType;


#define BRPHY_CORE_BASE                 (0x410F2000UL)



#define BRPHY_CORE_MAX_HW_ID            (1UL)


#define BRPHY0_CORE_BASE                (BRPHY_CORE_BASE)


#define BRPHY1_CORE_BASE                (0x0UL)


#define BRPHY2_CORE_BASE                (0x0UL)


#define BRPHY3_CORE_BASE                (0x0UL)


#define BRPHY4_CORE_BASE                (0x0UL)

#endif /* BRPHY_CORE_RDB_H */
