/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cct_rdb.h
    @brief RDB File for CCT

    @version 2018May25_rdb
*/

#ifndef CCT_RDB_H
#define CCT_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CCT_CTRLA_TYPE;
#define CCT_CTRLA_EN_MASK (0x1UL)
#define CCT_CTRLA_EN_SHIFT (0UL)




typedef uint32_t CCT_PSC_RATIO_TYPE;
#define CCT_PSC_RATIO_RATIO_MASK (0xffffUL)
#define CCT_PSC_RATIO_RATIO_SHIFT (0UL)




typedef uint32_t CCT_PSC_TRIG_TYPE;
#define CCT_PSC_TRIG_TRIG_MASK (0x1UL)
#define CCT_PSC_TRIG_TRIG_SHIFT (0UL)




typedef uint32_t CCT_PSC_CTRL_TYPE;
#define CCT_PSC_CTRL_MASK_EVT3_MASK (0x200000UL)
#define CCT_PSC_CTRL_MASK_EVT3_SHIFT (21UL)
#define CCT_PSC_CTRL_MASK_EVT2_MASK (0x100000UL)
#define CCT_PSC_CTRL_MASK_EVT2_SHIFT (20UL)
#define CCT_PSC_CTRL_MASK_EVT1_MASK (0x80000UL)
#define CCT_PSC_CTRL_MASK_EVT1_SHIFT (19UL)
#define CCT_PSC_CTRL_MASK_EVT0_MASK (0x40000UL)
#define CCT_PSC_CTRL_MASK_EVT0_SHIFT (18UL)
#define CCT_PSC_CTRL_MASK_OUT3N_MASK (0x20000UL)
#define CCT_PSC_CTRL_MASK_OUT3N_SHIFT (17UL)
#define CCT_PSC_CTRL_MASK_OUT3_MASK (0x10000UL)
#define CCT_PSC_CTRL_MASK_OUT3_SHIFT (16UL)
#define CCT_PSC_CTRL_MASK_OUT2N_MASK (0x8000UL)
#define CCT_PSC_CTRL_MASK_OUT2N_SHIFT (15UL)
#define CCT_PSC_CTRL_MASK_OUT2_MASK (0x4000UL)
#define CCT_PSC_CTRL_MASK_OUT2_SHIFT (14UL)
#define CCT_PSC_CTRL_MASK_OUT1N_MASK (0x2000UL)
#define CCT_PSC_CTRL_MASK_OUT1N_SHIFT (13UL)
#define CCT_PSC_CTRL_MASK_OUT1_MASK (0x1000UL)
#define CCT_PSC_CTRL_MASK_OUT1_SHIFT (12UL)
#define CCT_PSC_CTRL_MASK_OUT0N_MASK (0x800UL)
#define CCT_PSC_CTRL_MASK_OUT0N_SHIFT (11UL)
#define CCT_PSC_CTRL_MASK_OUT0_MASK (0x400UL)
#define CCT_PSC_CTRL_MASK_OUT0_SHIFT (10UL)
#define CCT_PSC_CTRL_MASK_IN3_FE_MASK (0x200UL)
#define CCT_PSC_CTRL_MASK_IN3_FE_SHIFT (9UL)
#define CCT_PSC_CTRL_MASK_IN3_RE_MASK (0x100UL)
#define CCT_PSC_CTRL_MASK_IN3_RE_SHIFT (8UL)
#define CCT_PSC_CTRL_MASK_IN2_FE_MASK (0x80UL)
#define CCT_PSC_CTRL_MASK_IN2_FE_SHIFT (7UL)
#define CCT_PSC_CTRL_MASK_IN2_RE_MASK (0x40UL)
#define CCT_PSC_CTRL_MASK_IN2_RE_SHIFT (6UL)
#define CCT_PSC_CTRL_MASK_IN1_FE_MASK (0x20UL)
#define CCT_PSC_CTRL_MASK_IN1_FE_SHIFT (5UL)
#define CCT_PSC_CTRL_MASK_IN1_RE_MASK (0x10UL)
#define CCT_PSC_CTRL_MASK_IN1_RE_SHIFT (4UL)
#define CCT_PSC_CTRL_MASK_IN0_FE_MASK (0x8UL)
#define CCT_PSC_CTRL_MASK_IN0_FE_SHIFT (3UL)
#define CCT_PSC_CTRL_MASK_IN0_RE_MASK (0x4UL)
#define CCT_PSC_CTRL_MASK_IN0_RE_SHIFT (2UL)
#define CCT_PSC_CTRL_MASK_ETR_FE_MASK (0x2UL)
#define CCT_PSC_CTRL_MASK_ETR_FE_SHIFT (1UL)
#define CCT_PSC_CTRL_MASK_ETR_RE_MASK (0x1UL)
#define CCT_PSC_CTRL_MASK_ETR_RE_SHIFT (0UL)




typedef uint32_t CCT_UDC_CTRL_TYPE;
#define CCT_UDC_CTRL_ARR_MASK (0xffff0000UL)
#define CCT_UDC_CTRL_ARR_SHIFT (16UL)
#define CCT_UDC_CTRL_UDEN_MASK (0x40UL)
#define CCT_UDC_CTRL_UDEN_SHIFT (6UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT3_MASK (0x20UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT3_SHIFT (5UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT2_MASK (0x10UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT2_SHIFT (4UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT1_MASK (0x8UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT1_SHIFT (3UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT0_MASK (0x4UL)
#define CCT_UDC_CTRL_UDC_MASK_EVT0_SHIFT (2UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_FE_MASK (0x2UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_FE_SHIFT (1UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_RE_MASK (0x1UL)
#define CCT_UDC_CTRL_UDC_MASK_ETR_RE_SHIFT (0UL)




typedef uint32_t CCT_UDC_TRIG_TYPE;
#define CCT_UDC_TRIG_TRIG_MASK (0x1UL)
#define CCT_UDC_TRIG_TRIG_SHIFT (0UL)




typedef uint32_t CCT_CCR_VAL_TYPE;
#define CCT_CCR_VAL_B_VAL_MASK (0xffff0000UL)
#define CCT_CCR_VAL_B_VAL_SHIFT (16UL)
#define CCT_CCR_VAL_A_VAL_MASK (0xffffUL)
#define CCT_CCR_VAL_A_VAL_SHIFT (0UL)




typedef uint32_t CCT_CCR_CTRL_TYPE;
#define CCT_CCR_CTRL_B_OUT_OEB_MASK (0x4000000UL)
#define CCT_CCR_CTRL_B_OUT_OEB_SHIFT (26UL)
#define CCT_CCR_CTRL_B_POL_MASK (0x2000000UL)
#define CCT_CCR_CTRL_B_POL_SHIFT (25UL)
#define CCT_CCR_CTRL_B_CCSEL_MASK (0x1000000UL)
#define CCT_CCR_CTRL_B_CCSEL_SHIFT (24UL)
#define CCT_CCR_CTRL_B_MASK_IN3_FE_MASK (0x800000UL)
#define CCT_CCR_CTRL_B_MASK_IN3_FE_SHIFT (23UL)
#define CCT_CCR_CTRL_B_MASK_IN3_RE_MASK (0x400000UL)
#define CCT_CCR_CTRL_B_MASK_IN3_RE_SHIFT (22UL)
#define CCT_CCR_CTRL_B_MASK_IN2_FE_MASK (0x200000UL)
#define CCT_CCR_CTRL_B_MASK_IN2_FE_SHIFT (21UL)
#define CCT_CCR_CTRL_B_MASK_IN2_RE_MASK (0x100000UL)
#define CCT_CCR_CTRL_B_MASK_IN2_RE_SHIFT (20UL)
#define CCT_CCR_CTRL_B_MASK_IN1_FE_MASK (0x80000UL)
#define CCT_CCR_CTRL_B_MASK_IN1_FE_SHIFT (19UL)
#define CCT_CCR_CTRL_B_MASK_IN1_RE_MASK (0x40000UL)
#define CCT_CCR_CTRL_B_MASK_IN1_RE_SHIFT (18UL)
#define CCT_CCR_CTRL_B_MASK_IN0_FE_MASK (0x20000UL)
#define CCT_CCR_CTRL_B_MASK_IN0_FE_SHIFT (17UL)
#define CCT_CCR_CTRL_B_MASK_IN0_RE_MASK (0x10000UL)
#define CCT_CCR_CTRL_B_MASK_IN0_RE_SHIFT (16UL)
#define CCT_CCR_CTRL_A_OUT_OEB_MASK (0x400UL)
#define CCT_CCR_CTRL_A_OUT_OEB_SHIFT (10UL)
#define CCT_CCR_CTRL_A_POL_MASK (0x200UL)
#define CCT_CCR_CTRL_A_POL_SHIFT (9UL)
#define CCT_CCR_CTRL_A_CCSEL_MASK (0x100UL)
#define CCT_CCR_CTRL_A_CCSEL_SHIFT (8UL)
#define CCT_CCR_CTRL_A_MASK_IN3_FE_MASK (0x80UL)
#define CCT_CCR_CTRL_A_MASK_IN3_FE_SHIFT (7UL)
#define CCT_CCR_CTRL_A_MASK_IN3_RE_MASK (0x40UL)
#define CCT_CCR_CTRL_A_MASK_IN3_RE_SHIFT (6UL)
#define CCT_CCR_CTRL_A_MASK_IN2_FE_MASK (0x20UL)
#define CCT_CCR_CTRL_A_MASK_IN2_FE_SHIFT (5UL)
#define CCT_CCR_CTRL_A_MASK_IN2_RE_MASK (0x10UL)
#define CCT_CCR_CTRL_A_MASK_IN2_RE_SHIFT (4UL)
#define CCT_CCR_CTRL_A_MASK_IN1_FE_MASK (0x8UL)
#define CCT_CCR_CTRL_A_MASK_IN1_FE_SHIFT (3UL)
#define CCT_CCR_CTRL_A_MASK_IN1_RE_MASK (0x4UL)
#define CCT_CCR_CTRL_A_MASK_IN1_RE_SHIFT (2UL)
#define CCT_CCR_CTRL_A_MASK_IN0_FE_MASK (0x2UL)
#define CCT_CCR_CTRL_A_MASK_IN0_FE_SHIFT (1UL)
#define CCT_CCR_CTRL_A_MASK_IN0_RE_MASK (0x1UL)
#define CCT_CCR_CTRL_A_MASK_IN0_RE_SHIFT (0UL)




typedef uint32_t CCT_CCR_INPUT_PSC_TYPE;
#define CCT_CCR_INPUT_PSC_B_MASK (0xffff0000UL)
#define CCT_CCR_INPUT_PSC_B_SHIFT (16UL)
#define CCT_CCR_INPUT_PSC_A_MASK (0xffffUL)
#define CCT_CCR_INPUT_PSC_A_SHIFT (0UL)




typedef uint32_t CCT_CCR_TRIG_TYPE;
#define CCT_CCR_TRIG_B_TRIG_MASK (0x2UL)
#define CCT_CCR_TRIG_B_TRIG_SHIFT (1UL)
#define CCT_CCR_TRIG_A_TRIG_MASK (0x1UL)
#define CCT_CCR_TRIG_A_TRIG_SHIFT (0UL)




typedef uint32_t CCT_IRQ_CTRL_TYPE;
#define CCT_IRQ_CTRL_ETR_FE_EN_MASK (0x400UL)
#define CCT_IRQ_CTRL_ETR_FE_EN_SHIFT (10UL)
#define CCT_IRQ_CTRL_ETR_RE_EN_MASK (0x200UL)
#define CCT_IRQ_CTRL_ETR_RE_EN_SHIFT (9UL)
#define CCT_IRQ_CTRL_UDC_EN_MASK (0x100UL)
#define CCT_IRQ_CTRL_UDC_EN_SHIFT (8UL)
#define CCT_IRQ_CTRL_CCR3_B_EN_MASK (0x80UL)
#define CCT_IRQ_CTRL_CCR3_B_EN_SHIFT (7UL)
#define CCT_IRQ_CTRL_CCR3_A_EN_MASK (0x40UL)
#define CCT_IRQ_CTRL_CCR3_A_EN_SHIFT (6UL)
#define CCT_IRQ_CTRL_CCR2_B_EN_MASK (0x20UL)
#define CCT_IRQ_CTRL_CCR2_B_EN_SHIFT (5UL)
#define CCT_IRQ_CTRL_CCR2_A_EN_MASK (0x10UL)
#define CCT_IRQ_CTRL_CCR2_A_EN_SHIFT (4UL)
#define CCT_IRQ_CTRL_CCR1_B_EN_MASK (0x8UL)
#define CCT_IRQ_CTRL_CCR1_B_EN_SHIFT (3UL)
#define CCT_IRQ_CTRL_CCR1_A_EN_MASK (0x4UL)
#define CCT_IRQ_CTRL_CCR1_A_EN_SHIFT (2UL)
#define CCT_IRQ_CTRL_CCR0_B_EN_MASK (0x2UL)
#define CCT_IRQ_CTRL_CCR0_B_EN_SHIFT (1UL)
#define CCT_IRQ_CTRL_CCR0_A_EN_MASK (0x1UL)
#define CCT_IRQ_CTRL_CCR0_A_EN_SHIFT (0UL)




typedef uint32_t CCT_IRQ_STAT_TYPE;
#define CCT_IRQ_STAT_ETR_FE_STAT_MASK (0x400UL)
#define CCT_IRQ_STAT_ETR_FE_STAT_SHIFT (10UL)
#define CCT_IRQ_STAT_ETR_RE_STAT_MASK (0x200UL)
#define CCT_IRQ_STAT_ETR_RE_STAT_SHIFT (9UL)
#define CCT_IRQ_STAT_UDC_STAT_MASK (0x100UL)
#define CCT_IRQ_STAT_UDC_STAT_SHIFT (8UL)
#define CCT_IRQ_STAT_CCR3_B_STAT_MASK (0x80UL)
#define CCT_IRQ_STAT_CCR3_B_STAT_SHIFT (7UL)
#define CCT_IRQ_STAT_CCR3_A_STAT_MASK (0x40UL)
#define CCT_IRQ_STAT_CCR3_A_STAT_SHIFT (6UL)
#define CCT_IRQ_STAT_CCR2_B_STAT_MASK (0x20UL)
#define CCT_IRQ_STAT_CCR2_B_STAT_SHIFT (5UL)
#define CCT_IRQ_STAT_CCR2_A_STAT_MASK (0x10UL)
#define CCT_IRQ_STAT_CCR2_A_STAT_SHIFT (4UL)
#define CCT_IRQ_STAT_CCR1_B_STAT_MASK (0x8UL)
#define CCT_IRQ_STAT_CCR1_B_STAT_SHIFT (3UL)
#define CCT_IRQ_STAT_CCR1_A_STAT_MASK (0x4UL)
#define CCT_IRQ_STAT_CCR1_A_STAT_SHIFT (2UL)
#define CCT_IRQ_STAT_CCR0_B_STAT_MASK (0x2UL)
#define CCT_IRQ_STAT_CCR0_B_STAT_SHIFT (1UL)
#define CCT_IRQ_STAT_CCR0_A_STAT_MASK (0x1UL)
#define CCT_IRQ_STAT_CCR0_A_STAT_SHIFT (0UL)




typedef uint8_t CCT_RESERVED_TYPE;


typedef volatile struct COMP_PACKED _CCT_CCR_RDBType {
    CCT_CCR_VAL_TYPE ccr0_val; /* OFFSET: 0x18 */
    CCT_CCR_CTRL_TYPE ccr0_ctrl; /* OFFSET: 0x1c */
    CCT_CCR_INPUT_PSC_TYPE ccr0_input_psc; /* OFFSET: 0x20 */
    CCT_CCR_TRIG_TYPE ccr0_trig; /* OFFSET: 0x24 */
} CCT_CCR_RDBType;



typedef volatile struct COMP_PACKED _CCT_RDBType {
    CCT_CTRLA_TYPE ctrla; /* OFFSET: 0x0 */
    CCT_PSC_RATIO_TYPE psc_ratio; /* OFFSET: 0x4 */
    CCT_PSC_TRIG_TYPE psc_trig; /* OFFSET: 0x8 */
    CCT_PSC_CTRL_TYPE psc_ctrl; /* OFFSET: 0xc */
    CCT_UDC_CTRL_TYPE udc_ctrl; /* OFFSET: 0x10 */
    CCT_UDC_TRIG_TYPE udc_trig; /* OFFSET: 0x14 */
    CCT_CCR_RDBType cct_ccr_regs[4]; /* OFFSET: 0x18 */
    CCT_IRQ_CTRL_TYPE irq_ctrl; /* OFFSET: 0x58 */
    CCT_IRQ_STAT_TYPE irq_stat; /* OFFSET: 0x5c */
    CCT_RESERVED_TYPE rsvd0[3984]; /* OFFSET: 0x60 */
    CCT_RESERVED_TYPE reserved[4]; /* OFFSET: 0xff0 */
} CCT_RDBType;


#define CCT_BASE                        (0x40026000UL)

#define CCT_CCR_RDBTYPE_OFFSET          (0x40026018UL)



#define CCT_MAX_HW_ID                   (1UL)


#define CCT_MAX_CHAN_CNT                (4UL)

#endif /* CCT_RDB_H */
