/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cfg_rdb.h
    @brief RDB File for CFG

    @version 2018May25_rdb
*/

#ifndef CFG_RDB_H
#define CFG_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t CFG_PERIPH_A_TYPE;
#define CFG_PERIPH_A_RSVD_07_MASK (0x80000000UL)
#define CFG_PERIPH_A_RSVD_07_SHIFT (31UL)
#define CFG_PERIPH_A_CFG_07_MASK (0x70000000UL)
#define CFG_PERIPH_A_CFG_07_SHIFT (28UL)
#define CFG_PERIPH_A_RSVD_06_MASK (0x8000000UL)
#define CFG_PERIPH_A_RSVD_06_SHIFT (27UL)
#define CFG_PERIPH_A_CFG_06_MASK (0x7000000UL)
#define CFG_PERIPH_A_CFG_06_SHIFT (24UL)
#define CFG_PERIPH_A_RSVD_05_MASK (0x800000UL)
#define CFG_PERIPH_A_RSVD_05_SHIFT (23UL)
#define CFG_PERIPH_A_CFG_05_MASK (0x700000UL)
#define CFG_PERIPH_A_CFG_05_SHIFT (20UL)
#define CFG_PERIPH_A_RSVD_04_MASK (0x80000UL)
#define CFG_PERIPH_A_RSVD_04_SHIFT (19UL)
#define CFG_PERIPH_A_CFG_04_MASK (0x70000UL)
#define CFG_PERIPH_A_CFG_04_SHIFT (16UL)
#define CFG_PERIPH_A_RSVD_03_MASK (0x8000UL)
#define CFG_PERIPH_A_RSVD_03_SHIFT (15UL)
#define CFG_PERIPH_A_CFG_03_MASK (0x7000UL)
#define CFG_PERIPH_A_CFG_03_SHIFT (12UL)
#define CFG_PERIPH_A_RSVD_02_MASK (0x800UL)
#define CFG_PERIPH_A_RSVD_02_SHIFT (11UL)
#define CFG_PERIPH_A_CFG_02_MASK (0x700UL)
#define CFG_PERIPH_A_CFG_02_SHIFT (8UL)
#define CFG_PERIPH_A_RSVD_01_MASK (0x80UL)
#define CFG_PERIPH_A_RSVD_01_SHIFT (7UL)
#define CFG_PERIPH_A_CFG_01_MASK (0x70UL)
#define CFG_PERIPH_A_CFG_01_SHIFT (4UL)
#define CFG_PERIPH_A_RSVD_00_MASK (0x8UL)
#define CFG_PERIPH_A_RSVD_00_SHIFT (3UL)
#define CFG_PERIPH_A_CFG_00_MASK (0x7UL)
#define CFG_PERIPH_A_CFG_00_SHIFT (0UL)




typedef uint32_t CFG_PERIPH_B_TYPE;
#define CFG_PERIPH_B_RSVD_15_MASK (0x80000000UL)
#define CFG_PERIPH_B_RSVD_15_SHIFT (31UL)
#define CFG_PERIPH_B_CFG_15_MASK (0x70000000UL)
#define CFG_PERIPH_B_CFG_15_SHIFT (28UL)
#define CFG_PERIPH_B_RSVD_14_MASK (0x8000000UL)
#define CFG_PERIPH_B_RSVD_14_SHIFT (27UL)
#define CFG_PERIPH_B_CFG_14_MASK (0x7000000UL)
#define CFG_PERIPH_B_CFG_14_SHIFT (24UL)
#define CFG_PERIPH_B_RSVD_13_MASK (0x800000UL)
#define CFG_PERIPH_B_RSVD_13_SHIFT (23UL)
#define CFG_PERIPH_B_CFG_13_MASK (0x700000UL)
#define CFG_PERIPH_B_CFG_13_SHIFT (20UL)
#define CFG_PERIPH_B_RSVD_12_MASK (0x80000UL)
#define CFG_PERIPH_B_RSVD_12_SHIFT (19UL)
#define CFG_PERIPH_B_CFG_12_MASK (0x70000UL)
#define CFG_PERIPH_B_CFG_12_SHIFT (16UL)
#define CFG_PERIPH_B_RSVD_11_MASK (0x8000UL)
#define CFG_PERIPH_B_RSVD_11_SHIFT (15UL)
#define CFG_PERIPH_B_CFG_11_MASK (0x7000UL)
#define CFG_PERIPH_B_CFG_11_SHIFT (12UL)
#define CFG_PERIPH_B_RSVD_10_MASK (0x800UL)
#define CFG_PERIPH_B_RSVD_10_SHIFT (11UL)
#define CFG_PERIPH_B_CFG_10_MASK (0x700UL)
#define CFG_PERIPH_B_CFG_10_SHIFT (8UL)
#define CFG_PERIPH_B_RSVD_09_MASK (0x80UL)
#define CFG_PERIPH_B_RSVD_09_SHIFT (7UL)
#define CFG_PERIPH_B_CFG_09_MASK (0x70UL)
#define CFG_PERIPH_B_CFG_09_SHIFT (4UL)
#define CFG_PERIPH_B_RSVD_08_MASK (0x8UL)
#define CFG_PERIPH_B_RSVD_08_SHIFT (3UL)
#define CFG_PERIPH_B_CFG_08_MASK (0x7UL)
#define CFG_PERIPH_B_CFG_08_SHIFT (0UL)




typedef uint32_t CFG_PERIPH_C_TYPE;
#define CFG_PERIPH_C_RSVD_20_MASK (0xffff0000UL)
#define CFG_PERIPH_C_RSVD_20_SHIFT (16UL)
#define CFG_PERIPH_C_RSVD_19_MASK (0x8000UL)
#define CFG_PERIPH_C_RSVD_19_SHIFT (15UL)
#define CFG_PERIPH_C_CFG_19_MASK (0x7000UL)
#define CFG_PERIPH_C_CFG_19_SHIFT (12UL)
#define CFG_PERIPH_C_RSVD_18_MASK (0x800UL)
#define CFG_PERIPH_C_RSVD_18_SHIFT (11UL)
#define CFG_PERIPH_C_CFG_18_MASK (0x700UL)
#define CFG_PERIPH_C_CFG_18_SHIFT (8UL)
#define CFG_PERIPH_C_RSVD_17_MASK (0x80UL)
#define CFG_PERIPH_C_RSVD_17_SHIFT (7UL)
#define CFG_PERIPH_C_CFG_17_MASK (0x70UL)
#define CFG_PERIPH_C_CFG_17_SHIFT (4UL)
#define CFG_PERIPH_C_RSVD_16_MASK (0x8UL)
#define CFG_PERIPH_C_RSVD_16_SHIFT (3UL)
#define CFG_PERIPH_C_CFG_16_MASK (0x7UL)
#define CFG_PERIPH_C_CFG_16_SHIFT (0UL)




typedef uint32_t CFG_PERIPH_PWRDN_TYPE;
#define CFG_PERIPH_PWRDN_PWRDN_ADC_MASK (0x1000000UL)
#define CFG_PERIPH_PWRDN_PWRDN_ADC_SHIFT (24UL)
#define CFG_PERIPH_PWRDN_TIM0_REFDIV4_PCLKEN_MASK (0x800000UL)
#define CFG_PERIPH_PWRDN_TIM0_REFDIV4_PCLKEN_SHIFT (23UL)
#define CFG_PERIPH_PWRDN_WDT_REFDIV4_PCLKEN_MASK (0x400000UL)
#define CFG_PERIPH_PWRDN_WDT_REFDIV4_PCLKEN_SHIFT (22UL)
#define CFG_PERIPH_PWRDN_PWRDN_TMR0_MASK (0x200000UL)
#define CFG_PERIPH_PWRDN_PWRDN_TMR0_SHIFT (21UL)
#define CFG_PERIPH_PWRDN_PWRDN_GIO1_MASK (0x100000UL)
#define CFG_PERIPH_PWRDN_PWRDN_GIO1_SHIFT (20UL)
#define CFG_PERIPH_PWRDN_PWRDN_GIO0_MASK (0x80000UL)
#define CFG_PERIPH_PWRDN_PWRDN_GIO0_SHIFT (19UL)
#define CFG_PERIPH_PWRDN_PWRDN_PWM_MASK (0x40000UL)
#define CFG_PERIPH_PWRDN_PWRDN_PWM_SHIFT (18UL)
#define CFG_PERIPH_PWRDN_PWRDN_TIM0_MASK (0x20000UL)
#define CFG_PERIPH_PWRDN_PWRDN_TIM0_SHIFT (17UL)
#define CFG_PERIPH_PWRDN_PWRDN_WDT_MASK (0x10000UL)
#define CFG_PERIPH_PWRDN_PWRDN_WDT_SHIFT (16UL)
#define CFG_PERIPH_PWRDN_PWRDN_URT_2_MASK (0x8000UL)
#define CFG_PERIPH_PWRDN_PWRDN_URT_2_SHIFT (15UL)
#define CFG_PERIPH_PWRDN_PWRDN_URT_1_MASK (0x4000UL)
#define CFG_PERIPH_PWRDN_PWRDN_URT_1_SHIFT (14UL)
#define CFG_PERIPH_PWRDN_PWRDN_URT_0_MASK (0x2000UL)
#define CFG_PERIPH_PWRDN_PWRDN_URT_0_SHIFT (13UL)
#define CFG_PERIPH_PWRDN_PWRDN_SPI_2_MASK (0x1000UL)
#define CFG_PERIPH_PWRDN_PWRDN_SPI_2_SHIFT (12UL)
#define CFG_PERIPH_PWRDN_PWRDN_SPI_1_MASK (0x800UL)
#define CFG_PERIPH_PWRDN_PWRDN_SPI_1_SHIFT (11UL)
#define CFG_PERIPH_PWRDN_PWRDN_SPI_0_MASK (0x400UL)
#define CFG_PERIPH_PWRDN_PWRDN_SPI_0_SHIFT (10UL)
#define CFG_PERIPH_PWRDN_PWRDN_MMI_MASK (0x200UL)
#define CFG_PERIPH_PWRDN_PWRDN_MMI_SHIFT (9UL)
#define CFG_PERIPH_PWRDN_PWRDN_CAN_MASK (0x100UL)
#define CFG_PERIPH_PWRDN_PWRDN_CAN_SHIFT (8UL)
#define CFG_PERIPH_PWRDN_PWRDN_AVT_MASK (0x80UL)
#define CFG_PERIPH_PWRDN_PWRDN_AVT_SHIFT (7UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2S_0_MASK (0x10UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2S_0_SHIFT (4UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_3_MASK (0x8UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_3_SHIFT (3UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_2_MASK (0x4UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_2_SHIFT (2UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_1_MASK (0x2UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_1_SHIFT (1UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_0_MASK (0x1UL)
#define CFG_PERIPH_PWRDN_PWRDN_I2C_0_SHIFT (0UL)




typedef uint32_t CFG_PERIPH_RESET_TYPE;
#define CFG_PERIPH_RESET_AMAC_MASK (0x8000000UL)
#define CFG_PERIPH_RESET_AMAC_SHIFT (27UL)
#define CFG_PERIPH_RESET_QSPI_1_MASK (0x4000000UL)
#define CFG_PERIPH_RESET_QSPI_1_SHIFT (26UL)
#define CFG_PERIPH_RESET_QSPI_0_MASK (0x2000000UL)
#define CFG_PERIPH_RESET_QSPI_0_SHIFT (25UL)
#define CFG_PERIPH_RESET_ADC_MASK (0x1000000UL)
#define CFG_PERIPH_RESET_ADC_SHIFT (24UL)
#define CFG_PERIPH_RESET_RESERVED_1_MASK (0x800000UL)
#define CFG_PERIPH_RESET_RESERVED_1_SHIFT (23UL)
#define CFG_PERIPH_RESET_RESERVED_0_MASK (0x400000UL)
#define CFG_PERIPH_RESET_RESERVED_0_SHIFT (22UL)
#define CFG_PERIPH_RESET_TMR0_MASK (0x200000UL)
#define CFG_PERIPH_RESET_TMR0_SHIFT (21UL)
#define CFG_PERIPH_RESET_GIO1_MASK (0x100000UL)
#define CFG_PERIPH_RESET_GIO1_SHIFT (20UL)
#define CFG_PERIPH_RESET_GIO0_MASK (0x80000UL)
#define CFG_PERIPH_RESET_GIO0_SHIFT (19UL)
#define CFG_PERIPH_RESET_PWM_MASK (0x40000UL)
#define CFG_PERIPH_RESET_PWM_SHIFT (18UL)
#define CFG_PERIPH_RESET_TIM0_MASK (0x20000UL)
#define CFG_PERIPH_RESET_TIM0_SHIFT (17UL)
#define CFG_PERIPH_RESET_WDT_MASK (0x10000UL)
#define CFG_PERIPH_RESET_WDT_SHIFT (16UL)
#define CFG_PERIPH_RESET_URT_2_MASK (0x8000UL)
#define CFG_PERIPH_RESET_URT_2_SHIFT (15UL)
#define CFG_PERIPH_RESET_URT_1_MASK (0x4000UL)
#define CFG_PERIPH_RESET_URT_1_SHIFT (14UL)
#define CFG_PERIPH_RESET_URT_0_MASK (0x2000UL)
#define CFG_PERIPH_RESET_URT_0_SHIFT (13UL)
#define CFG_PERIPH_RESET_SPI_2_MASK (0x1000UL)
#define CFG_PERIPH_RESET_SPI_2_SHIFT (12UL)
#define CFG_PERIPH_RESET_SPI_1_MASK (0x800UL)
#define CFG_PERIPH_RESET_SPI_1_SHIFT (11UL)
#define CFG_PERIPH_RESET_SPI_0_MASK (0x400UL)
#define CFG_PERIPH_RESET_SPI_0_SHIFT (10UL)
#define CFG_PERIPH_RESET_MMI_MASK (0x200UL)
#define CFG_PERIPH_RESET_MMI_SHIFT (9UL)
#define CFG_PERIPH_RESET_CAN_MASK (0x100UL)
#define CFG_PERIPH_RESET_CAN_SHIFT (8UL)
#define CFG_PERIPH_RESET_AVT_MASK (0x80UL)
#define CFG_PERIPH_RESET_AVT_SHIFT (7UL)
#define CFG_PERIPH_RESET_I2S_0_MASK (0x10UL)
#define CFG_PERIPH_RESET_I2S_0_SHIFT (4UL)
#define CFG_PERIPH_RESET_I2C_3_MASK (0x8UL)
#define CFG_PERIPH_RESET_I2C_3_SHIFT (3UL)
#define CFG_PERIPH_RESET_I2C_2_MASK (0x4UL)
#define CFG_PERIPH_RESET_I2C_2_SHIFT (2UL)
#define CFG_PERIPH_RESET_I2C_1_MASK (0x2UL)
#define CFG_PERIPH_RESET_I2C_1_SHIFT (1UL)
#define CFG_PERIPH_RESET_I2C_0_MASK (0x1UL)
#define CFG_PERIPH_RESET_I2C_0_SHIFT (0UL)




typedef uint32_t CFG_PERIPH_BUSY_TYPE;
#define CFG_PERIPH_BUSY_DMU_MASK (0x80000000UL)
#define CFG_PERIPH_BUSY_DMU_SHIFT (31UL)
#define CFG_PERIPH_BUSY_ADC_MASK (0x1000000UL)
#define CFG_PERIPH_BUSY_ADC_SHIFT (24UL)
#define CFG_PERIPH_BUSY_RESERVED_1_MASK (0x800000UL)
#define CFG_PERIPH_BUSY_RESERVED_1_SHIFT (23UL)
#define CFG_PERIPH_BUSY_RESERVED_0_MASK (0x400000UL)
#define CFG_PERIPH_BUSY_RESERVED_0_SHIFT (22UL)
#define CFG_PERIPH_BUSY_TMR0_MASK (0x200000UL)
#define CFG_PERIPH_BUSY_TMR0_SHIFT (21UL)
#define CFG_PERIPH_BUSY_GIO1_MASK (0x100000UL)
#define CFG_PERIPH_BUSY_GIO1_SHIFT (20UL)
#define CFG_PERIPH_BUSY_GIO0_MASK (0x80000UL)
#define CFG_PERIPH_BUSY_GIO0_SHIFT (19UL)
#define CFG_PERIPH_BUSY_PWM_MASK (0x40000UL)
#define CFG_PERIPH_BUSY_PWM_SHIFT (18UL)
#define CFG_PERIPH_BUSY_TIM0_MASK (0x20000UL)
#define CFG_PERIPH_BUSY_TIM0_SHIFT (17UL)
#define CFG_PERIPH_BUSY_WDT_MASK (0x10000UL)
#define CFG_PERIPH_BUSY_WDT_SHIFT (16UL)
#define CFG_PERIPH_BUSY_URT_2_MASK (0x8000UL)
#define CFG_PERIPH_BUSY_URT_2_SHIFT (15UL)
#define CFG_PERIPH_BUSY_URT_1_MASK (0x4000UL)
#define CFG_PERIPH_BUSY_URT_1_SHIFT (14UL)
#define CFG_PERIPH_BUSY_URT_0_MASK (0x2000UL)
#define CFG_PERIPH_BUSY_URT_0_SHIFT (13UL)
#define CFG_PERIPH_BUSY_SPI_2_MASK (0x1000UL)
#define CFG_PERIPH_BUSY_SPI_2_SHIFT (12UL)
#define CFG_PERIPH_BUSY_SPI_1_MASK (0x800UL)
#define CFG_PERIPH_BUSY_SPI_1_SHIFT (11UL)
#define CFG_PERIPH_BUSY_SPI_0_MASK (0x400UL)
#define CFG_PERIPH_BUSY_SPI_0_SHIFT (10UL)
#define CFG_PERIPH_BUSY_MMI_MASK (0x200UL)
#define CFG_PERIPH_BUSY_MMI_SHIFT (9UL)
#define CFG_PERIPH_BUSY_CAN_MASK (0x100UL)
#define CFG_PERIPH_BUSY_CAN_SHIFT (8UL)
#define CFG_PERIPH_BUSY_AVT_MASK (0x80UL)
#define CFG_PERIPH_BUSY_AVT_SHIFT (7UL)
#define CFG_PERIPH_BUSY_I2S_0_MASK (0x10UL)
#define CFG_PERIPH_BUSY_I2S_0_SHIFT (4UL)
#define CFG_PERIPH_BUSY_I2C_3_MASK (0x8UL)
#define CFG_PERIPH_BUSY_I2C_3_SHIFT (3UL)
#define CFG_PERIPH_BUSY_I2C_2_MASK (0x4UL)
#define CFG_PERIPH_BUSY_I2C_2_SHIFT (2UL)
#define CFG_PERIPH_BUSY_I2C_1_MASK (0x2UL)
#define CFG_PERIPH_BUSY_I2C_1_SHIFT (1UL)
#define CFG_PERIPH_BUSY_I2C_0_MASK (0x1UL)
#define CFG_PERIPH_BUSY_I2C_0_SHIFT (0UL)




typedef uint32_t CFG_RGMII_CTRL_TYPE;
#define CFG_RGMII_CTRL_SPEED_MASK (0x300UL)
#define CFG_RGMII_CTRL_SPEED_SHIFT (8UL)
#define CFG_RGMII_CTRL_DLL_IDDQ_MASK (0x80UL)
#define CFG_RGMII_CTRL_DLL_IDDQ_SHIFT (7UL)
#define CFG_RGMII_CTRL_DLL_RXC_BYPASS_MASK (0x40UL)
#define CFG_RGMII_CTRL_DLL_RXC_BYPASS_SHIFT (6UL)
#define CFG_RGMII_CTRL_BYPASS_IMP_2NS_DEL_MASK (0x20UL)
#define CFG_RGMII_CTRL_BYPASS_IMP_2NS_DEL_SHIFT (5UL)
#define CFG_RGMII_CTRL_TESTONRXD_MASK (0x10UL)
#define CFG_RGMII_CTRL_TESTONRXD_SHIFT (4UL)
#define CFG_RGMII_CTRL_EN10B_MASK (0x8UL)
#define CFG_RGMII_CTRL_EN10B_SHIFT (3UL)
#define CFG_RGMII_CTRL_OOBDIS_MASK (0x4UL)
#define CFG_RGMII_CTRL_OOBDIS_SHIFT (2UL)
#define CFG_RGMII_CTRL_TIMING_SEL_MASK (0x2UL)
#define CFG_RGMII_CTRL_TIMING_SEL_SHIFT (1UL)
#define CFG_RGMII_CTRL_EN_MASK (0x1UL)
#define CFG_RGMII_CTRL_EN_SHIFT (0UL)




typedef uint32_t CFG_AMAC_CTRL_TYPE;
#define CFG_AMAC_CTRL_AMAC_MDIO_ENABLE_MASK (0x400000UL)
#define CFG_AMAC_CTRL_AMAC_MDIO_ENABLE_SHIFT (22UL)
#define CFG_AMAC_CTRL_TM_SP_MASK (0x3ff000UL)
#define CFG_AMAC_CTRL_TM_SP_SHIFT (12UL)
#define CFG_AMAC_CTRL_TM_RF_MASK (0xff0UL)
#define CFG_AMAC_CTRL_TM_RF_SHIFT (4UL)
#define CFG_AMAC_CTRL_OOB_FLOW_CTRL_EN_MASK (0x8UL)
#define CFG_AMAC_CTRL_OOB_FLOW_CTRL_EN_SHIFT (3UL)
#define CFG_AMAC_CTRL_EN_AUTOCONFIG_MASK (0x4UL)
#define CFG_AMAC_CTRL_EN_AUTOCONFIG_SHIFT (2UL)
#define CFG_AMAC_CTRL_EEE_EN_MASK (0x2UL)
#define CFG_AMAC_CTRL_EEE_EN_SHIFT (1UL)
#define CFG_AMAC_CTRL_DISABLE_AMAC_MASK (0x1UL)
#define CFG_AMAC_CTRL_DISABLE_AMAC_SHIFT (0UL)




typedef uint32_t CFG_AMAC_IO_CTRL_TYPE;
#define CFG_AMAC_IO_CTRL_ADDR_MSB_MASK (0x80000000UL)
#define CFG_AMAC_IO_CTRL_ADDR_MSB_SHIFT (31UL)
#define CFG_AMAC_IO_CTRL_ADDR_MSB_SEL_MASK (0x40000000UL)
#define CFG_AMAC_IO_CTRL_ADDR_MSB_SEL_SHIFT (30UL)
#define CFG_AMAC_IO_CTRL_ARUSER_MASK (0x3e000000UL)
#define CFG_AMAC_IO_CTRL_ARUSER_SHIFT (25UL)
#define CFG_AMAC_IO_CTRL_AWUSER_MASK (0x1f00000UL)
#define CFG_AMAC_IO_CTRL_AWUSER_SHIFT (20UL)
#define CFG_AMAC_IO_CTRL_ARCACHE_MASK (0xf0000UL)
#define CFG_AMAC_IO_CTRL_ARCACHE_SHIFT (16UL)
#define CFG_AMAC_IO_CTRL_RSVD_1_MASK (0xc000UL)
#define CFG_AMAC_IO_CTRL_RSVD_1_SHIFT (14UL)
#define CFG_AMAC_IO_CTRL_LEDSCAN_FLOP_STAGES_MASK (0x3800UL)
#define CFG_AMAC_IO_CTRL_LEDSCAN_FLOP_STAGES_SHIFT (11UL)
#define CFG_AMAC_IO_CTRL_AWCACHE_MASK (0x780UL)
#define CFG_AMAC_IO_CTRL_AWCACHE_SHIFT (7UL)
#define CFG_AMAC_IO_CTRL_INTERFACE_MODE_STRAP_MASK (0x7cUL)
#define CFG_AMAC_IO_CTRL_INTERFACE_MODE_STRAP_SHIFT (2UL)
#define CFG_AMAC_IO_CTRL_RSVD_0_MASK (0x2UL)
#define CFG_AMAC_IO_CTRL_RSVD_0_SHIFT (1UL)
#define CFG_AMAC_IO_CTRL_CLK_ENABLE_MASK (0x1UL)
#define CFG_AMAC_IO_CTRL_CLK_ENABLE_SHIFT (0UL)




typedef uint8_t CFG_RESERVED_TYPE;




typedef uint32_t CFG_AMAC_IO_STAT_TYPE;
#define CFG_AMAC_IO_STAT_STAT_MASK (0xffffffffUL)
#define CFG_AMAC_IO_STAT_STAT_SHIFT (0UL)




typedef uint32_t CFG_AMAC_IP_REVID_TYPE;
#define CFG_AMAC_IP_REVID_REVID_MASK (0xffUL)
#define CFG_AMAC_IP_REVID_REVID_SHIFT (0UL)




typedef uint32_t CFG_CAN_CTRL_TYPE;
#define CFG_CAN_CTRL_TM_PD_MASK (0x3ffUL)
#define CFG_CAN_CTRL_TM_PD_SHIFT (0UL)




typedef uint32_t CFG_QSPI_IO_CONTROL_TYPE;
#define CFG_QSPI_IO_CONTROL_DISABLE_MSPI_FLUSH_MASK (0x400UL)
#define CFG_QSPI_IO_CONTROL_DISABLE_MSPI_FLUSH_SHIFT (10UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_RBUS_ARBITER_TIMER_MASK (0x200UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_RBUS_ARBITER_TIMER_SHIFT (9UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_HALT_SET_TRANSACTION_DONE_MASK (0x100UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_HALT_SET_TRANSACTION_DONE_SHIFT (8UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_DONE_MASK (0x80UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_DONE_SHIFT (7UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_OVERREAD_MASK (0x40UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_OVERREAD_SHIFT (6UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_SESSION_DONE_MASK (0x20UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_SESSION_DONE_SHIFT (5UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_IMPATIENT_MASK (0x10UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_IMPATIENT_SHIFT (4UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_TRUNCATED_MASK (0x8UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_TRUNCATED_SHIFT (3UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_FULLNESS_REACHED_MASK (0x4UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_FULLNESS_REACHED_SHIFT (2UL)
#define CFG_QSPI_IO_CONTROL_CLK_ENABLE_MASK (0x1UL)
#define CFG_QSPI_IO_CONTROL_CLK_ENABLE_SHIFT (0UL)




typedef uint32_t CFG_QSPI_CLK_CTRL_TYPE;
#define CFG_QSPI_CLK_CTRL_SELDIV_DONE_1_MASK (0x8000UL)
#define CFG_QSPI_CLK_CTRL_SELDIV_DONE_1_SHIFT (15UL)
#define CFG_QSPI_CLK_CTRL_DIV_SEL_1_MASK (0x7000UL)
#define CFG_QSPI_CLK_CTRL_DIV_SEL_1_SHIFT (12UL)
#define CFG_QSPI_CLK_CTRL_CLK_SEL_1_MASK (0x300UL)
#define CFG_QSPI_CLK_CTRL_CLK_SEL_1_SHIFT (8UL)
#define CFG_QSPI_CLK_CTRL_SELDIV_DONE_0_MASK (0x80UL)
#define CFG_QSPI_CLK_CTRL_SELDIV_DONE_0_SHIFT (7UL)
#define CFG_QSPI_CLK_CTRL_DIV_SEL_0_MASK (0x70UL)
#define CFG_QSPI_CLK_CTRL_DIV_SEL_0_SHIFT (4UL)
#define CFG_QSPI_CLK_CTRL_CLK_SEL_0_MASK (0x3UL)
#define CFG_QSPI_CLK_CTRL_CLK_SEL_0_SHIFT (0UL)




typedef uint32_t CFG_QSPI_IO_STATUS_TYPE;
#define CFG_QSPI_IO_STATUS_STRAP_IP_DISABLE_QSPI_MASK (0x8UL)
#define CFG_QSPI_IO_STATUS_STRAP_IP_DISABLE_QSPI_SHIFT (3UL)
#define CFG_QSPI_IO_STATUS_STRAP_4BYTE_ADDR_MODE_MASK (0x4UL)
#define CFG_QSPI_IO_STATUS_STRAP_4BYTE_ADDR_MODE_SHIFT (2UL)
#define CFG_QSPI_IO_STATUS_STRAP_QUAD_LANE_MASK (0x2UL)
#define CFG_QSPI_IO_STATUS_STRAP_QUAD_LANE_SHIFT (1UL)
#define CFG_QSPI_IO_STATUS_STRAP_DUAL_LANE_MASK (0x1UL)
#define CFG_QSPI_IO_STATUS_STRAP_DUAL_LANE_SHIFT (0UL)




typedef uint32_t CFG_QSPI_IP_REVID_TYPE;
#define CFG_QSPI_IP_REVID_REVID_MASK (0xffUL)
#define CFG_QSPI_IP_REVID_REVID_SHIFT (0UL)




typedef uint32_t CFG_QSPI_FLASH_0_BASE_ADDR_TYPE;
#define CFG_QSPI_FLASH_0_BASE_ADDR_MEM_ADDR_MASK (0xffffffffUL)
#define CFG_QSPI_FLASH_0_BASE_ADDR_MEM_ADDR_SHIFT (0UL)




typedef uint32_t CFG_QSPI_FLASH_0_SIZE_TYPE;
#define CFG_QSPI_FLASH_0_SIZE_MEM_BYTE_SIZE_MASK (0xffffffffUL)
#define CFG_QSPI_FLASH_0_SIZE_MEM_BYTE_SIZE_SHIFT (0UL)




typedef uint32_t CFG_QSPI_FLASH_1_BASE_ADDR_TYPE;
#define CFG_QSPI_FLASH_1_BASE_ADDR_MEM_ADDR_MASK (0xffffffffUL)
#define CFG_QSPI_FLASH_1_BASE_ADDR_MEM_ADDR_SHIFT (0UL)




typedef uint32_t CFG_QSPI_FLASH_1_SIZE_TYPE;
#define CFG_QSPI_FLASH_1_SIZE_MEM_BYTE_SIZE_MASK (0xffffffffUL)
#define CFG_QSPI_FLASH_1_SIZE_MEM_BYTE_SIZE_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_RAW_31_00_TYPE;
#define CFG_PIO_SYS_INTR_RAW_31_00_RAW_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_RAW_31_00_RAW_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_RAW_63_32_TYPE;
#define CFG_PIO_SYS_INTR_RAW_63_32_RAW_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_RAW_63_32_RAW_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_RAW_95_64_TYPE;
#define CFG_PIO_SYS_INTR_RAW_95_64_RAW_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_RAW_95_64_RAW_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_STAT_31_00_TYPE;
#define CFG_PIO_SYS_INTR_STAT_31_00_STAT_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_STAT_31_00_STAT_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_STAT_63_32_TYPE;
#define CFG_PIO_SYS_INTR_STAT_63_32_STAT_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_STAT_63_32_STAT_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_STAT_95_64_TYPE;
#define CFG_PIO_SYS_INTR_STAT_95_64_STAT_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_STAT_95_64_STAT_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_MASK_31_00_TYPE;
#define CFG_PIO_SYS_INTR_MASK_31_00_MASK_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_MASK_31_00_MASK_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_MASK_63_32_TYPE;
#define CFG_PIO_SYS_INTR_MASK_63_32_MASK_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_MASK_63_32_MASK_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_MASK_95_64_TYPE;
#define CFG_PIO_SYS_INTR_MASK_95_64_MASK_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_MASK_95_64_MASK_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_FORCE_31_00_TYPE;
#define CFG_PIO_SYS_INTR_FORCE_31_00_FORCE_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_FORCE_31_00_FORCE_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_FORCE_63_32_TYPE;
#define CFG_PIO_SYS_INTR_FORCE_63_32_FORCE_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_FORCE_63_32_FORCE_SHIFT (0UL)




typedef uint32_t CFG_PIO_SYS_INTR_FORCE_95_64_TYPE;
#define CFG_PIO_SYS_INTR_FORCE_95_64_FORCE_MASK (0xffffffffUL)
#define CFG_PIO_SYS_INTR_FORCE_95_64_FORCE_SHIFT (0UL)




typedef uint32_t CFG_AHB_MONITOR_CTRL_TYPE;
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_IRQ_MASK_MASK (0x80000000UL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_IRQ_MASK_SHIFT (31UL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_ERR_RESP_EN_MASK (0x40000000UL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_ERR_RESP_EN_SHIFT (30UL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_EN_MASK (0x100UL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_EN_SHIFT (8UL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_SEL_MASK (0xfUL)
#define CFG_AHB_MONITOR_CTRL_TIMEOUT_SEL_SHIFT (0UL)




typedef uint32_t CFG_AHB_TIMEOUT_ADDRESS_TYPE;
#define CFG_AHB_TIMEOUT_ADDRESS_ADDRESS_MASK (0xffffffffUL)
#define CFG_AHB_TIMEOUT_ADDRESS_ADDRESS_SHIFT (0UL)




typedef uint32_t CFG_AHB_TIMEOUT_IRQ_STATUS_TYPE;
#define CFG_AHB_TIMEOUT_IRQ_STATUS_STATUS_MASK (0x1UL)
#define CFG_AHB_TIMEOUT_IRQ_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t CFG_APB_MONITOR_CTRL_TYPE;
#define CFG_APB_MONITOR_CTRL_TIMEOUT_IRQ_MASK_MASK (0x80000000UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_IRQ_MASK_SHIFT (31UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_ERR_RESP_EN_MASK (0x40000000UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_ERR_RESP_EN_SHIFT (30UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_EN_MASK (0x100UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_EN_SHIFT (8UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_SEL_MASK (0xfUL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_SEL_SHIFT (0UL)




typedef uint32_t CFG_APB_TIMEOUT_ADDRESS_TYPE;
#define CFG_APB_TIMEOUT_ADDRESS_ADDRESS_MASK (0xffffffffUL)
#define CFG_APB_TIMEOUT_ADDRESS_ADDRESS_SHIFT (0UL)




typedef uint32_t CFG_APB_TIMEOUT_IRQ_STATUS_TYPE;
#define CFG_APB_TIMEOUT_IRQ_STATUS_STATUS_MASK (0x1UL)
#define CFG_APB_TIMEOUT_IRQ_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t CFG_WR_DISABLE_PROTECT_STATUS_TYPE;
#define CFG_WR_DISABLE_PROTECT_STATUS_WRITE_PROTECTION_STATUS_MASK (0x1UL)
#define CFG_WR_DISABLE_PROTECT_STATUS_WRITE_PROTECTION_STATUS_SHIFT (0UL)




typedef uint32_t CFG_WR_ENABLE_PROTECT_STATUS_TYPE;
#define CFG_WR_ENABLE_PROTECT_STATUS_WRITE_PROTECTION_STATUS_MASK (0x1UL)
#define CFG_WR_ENABLE_PROTECT_STATUS_WRITE_PROTECTION_STATUS_SHIFT (0UL)




typedef uint32_t CFG_ADDR_START_PROT_0_TYPE;
#define CFG_ADDR_START_PROT_0_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_START_PROT_0_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_END_PROT_0_TYPE;
#define CFG_ADDR_END_PROT_0_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_END_PROT_0_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_START_PROT_1_TYPE;
#define CFG_ADDR_START_PROT_1_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_START_PROT_1_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_END_PROT_1_TYPE;
#define CFG_ADDR_END_PROT_1_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_END_PROT_1_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_START_PROT_2_TYPE;
#define CFG_ADDR_START_PROT_2_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_START_PROT_2_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_END_PROT_2_TYPE;
#define CFG_ADDR_END_PROT_2_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_END_PROT_2_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_START_PROT_3_TYPE;
#define CFG_ADDR_START_PROT_3_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_START_PROT_3_PROT_SHIFT (0UL)




typedef uint32_t CFG_ADDR_END_PROT_3_TYPE;
#define CFG_ADDR_END_PROT_3_PROT_MASK (0xffffffffUL)
#define CFG_ADDR_END_PROT_3_PROT_SHIFT (0UL)




typedef uint32_t CFG_MISC_CTRL_TYPE;
#define CFG_MISC_CTRL_VREG_MDIO_EN_MASK (0x1UL)
#define CFG_MISC_CTRL_VREG_MDIO_EN_SHIFT (0UL)




typedef uint32_t CFG_DEBUG_CTRL_TYPE;
#define CFG_DEBUG_CTRL_BUS_SEL_MASK (0xfUL)
#define CFG_DEBUG_CTRL_BUS_SEL_SHIFT (0UL)




typedef uint32_t CFG_FEATURE_ENABLE_TYPE;
#define CFG_FEATURE_ENABLE_URT_2_MASK (0x8000UL)
#define CFG_FEATURE_ENABLE_URT_2_SHIFT (15UL)
#define CFG_FEATURE_ENABLE_URT_1_MASK (0x4000UL)
#define CFG_FEATURE_ENABLE_URT_1_SHIFT (14UL)
#define CFG_FEATURE_ENABLE_URT_0_MASK (0x2000UL)
#define CFG_FEATURE_ENABLE_URT_0_SHIFT (13UL)
#define CFG_FEATURE_ENABLE_SPI_2_MASK (0x1000UL)
#define CFG_FEATURE_ENABLE_SPI_2_SHIFT (12UL)
#define CFG_FEATURE_ENABLE_SPI_1_MASK (0x800UL)
#define CFG_FEATURE_ENABLE_SPI_1_SHIFT (11UL)
#define CFG_FEATURE_ENABLE_SPI_0_MASK (0x400UL)
#define CFG_FEATURE_ENABLE_SPI_0_SHIFT (10UL)
#define CFG_FEATURE_ENABLE_MMI_MASK (0x200UL)
#define CFG_FEATURE_ENABLE_MMI_SHIFT (9UL)
#define CFG_FEATURE_ENABLE_CAN_MASK (0x100UL)
#define CFG_FEATURE_ENABLE_CAN_SHIFT (8UL)
#define CFG_FEATURE_ENABLE_AVT_MASK (0x80UL)
#define CFG_FEATURE_ENABLE_AVT_SHIFT (7UL)
#define CFG_FEATURE_ENABLE_I2S_0_MASK (0x10UL)
#define CFG_FEATURE_ENABLE_I2S_0_SHIFT (4UL)
#define CFG_FEATURE_ENABLE_I2C_3_MASK (0x8UL)
#define CFG_FEATURE_ENABLE_I2C_3_SHIFT (3UL)
#define CFG_FEATURE_ENABLE_I2C_2_MASK (0x4UL)
#define CFG_FEATURE_ENABLE_I2C_2_SHIFT (2UL)
#define CFG_FEATURE_ENABLE_I2C_1_MASK (0x2UL)
#define CFG_FEATURE_ENABLE_I2C_1_SHIFT (1UL)
#define CFG_FEATURE_ENABLE_I2C_0_MASK (0x1UL)
#define CFG_FEATURE_ENABLE_I2C_0_SHIFT (0UL)




typedef uint32_t CFG_IND_REGS_CTRL_TYPE;
#define CFG_IND_REGS_CTRL_RESERVED1_MASK (0xffffff00UL)
#define CFG_IND_REGS_CTRL_RESERVED1_SHIFT (8UL)
#define CFG_IND_REGS_CTRL_DONE_MASK (0x80UL)
#define CFG_IND_REGS_CTRL_DONE_SHIFT (7UL)
#define CFG_IND_REGS_CTRL_RESERVED0_MASK (0x40UL)
#define CFG_IND_REGS_CTRL_RESERVED0_SHIFT (6UL)
#define CFG_IND_REGS_CTRL_COMMIT_ON_RDWR_MASK (0x20UL)
#define CFG_IND_REGS_CTRL_COMMIT_ON_RDWR_SHIFT (5UL)
#define CFG_IND_REGS_CTRL_COMMIT_MASK (0x10UL)
#define CFG_IND_REGS_CTRL_COMMIT_SHIFT (4UL)
#define CFG_IND_REGS_CTRL_AUTO_INCR_MASK (0x8UL)
#define CFG_IND_REGS_CTRL_AUTO_INCR_SHIFT (3UL)
#define CFG_IND_REGS_CTRL_RDB_WR_MASK (0x4UL)
#define CFG_IND_REGS_CTRL_RDB_WR_SHIFT (2UL)
#define CFG_IND_REGS_CTRL_SIZE_MASK (0x3UL)
#define CFG_IND_REGS_CTRL_SIZE_SHIFT (0UL)




typedef uint32_t CFG_IND_REGS_ADDR_TYPE;
#define CFG_IND_REGS_ADDR_ADDRESS_MASK (0xffffffffUL)
#define CFG_IND_REGS_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t CFG_IND_REGS_DATA_L_TYPE;
#define CFG_IND_REGS_DATA_L_L_MASK (0xffffffffUL)
#define CFG_IND_REGS_DATA_L_L_SHIFT (0UL)




typedef uint32_t CFG_IND_REGS_DATA_H_TYPE;
#define CFG_IND_REGS_DATA_H_H_MASK (0xffffffffUL)
#define CFG_IND_REGS_DATA_H_H_SHIFT (0UL)




typedef volatile struct COMP_PACKED _CFG_RDBType {
    CFG_PERIPH_A_TYPE cfg_periph_a; /* OFFSET: 0x0 */
    CFG_PERIPH_B_TYPE cfg_periph_b; /* OFFSET: 0x4 */
    CFG_PERIPH_C_TYPE cfg_periph_c; /* OFFSET: 0x8 */
    CFG_PERIPH_PWRDN_TYPE periph_pwrdn; /* OFFSET: 0xc */
    CFG_PERIPH_RESET_TYPE periph_reset; /* OFFSET: 0x10 */
    CFG_PERIPH_BUSY_TYPE periph_busy; /* OFFSET: 0x14 */
    CFG_RGMII_CTRL_TYPE rgmii_ctrl; /* OFFSET: 0x18 */
    CFG_AMAC_CTRL_TYPE amac_ctrl; /* OFFSET: 0x1c */
    CFG_AMAC_IO_CTRL_TYPE amac_io_ctrl; /* OFFSET: 0x20 */
    CFG_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x24 */
    CFG_AMAC_IO_STAT_TYPE amac_io_stat; /* OFFSET: 0x28 */
    CFG_AMAC_IP_REVID_TYPE amac_ip_revid; /* OFFSET: 0x2c */
    CFG_CAN_CTRL_TYPE can_ctrl; /* OFFSET: 0x30 */
    CFG_RESERVED_TYPE rsvd1[28]; /* OFFSET: 0x34 */
    CFG_QSPI_IO_CONTROL_TYPE qspi_io_control_0; /* OFFSET: 0x50 */
    CFG_QSPI_IO_CONTROL_TYPE qspi_io_control_1; /* OFFSET: 0x54 */
    CFG_QSPI_CLK_CTRL_TYPE qspi_clk_ctrl; /* OFFSET: 0x58 */
    CFG_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x5c */
    CFG_QSPI_IO_STATUS_TYPE qspi_io_status; /* OFFSET: 0x60 */
    CFG_QSPI_IP_REVID_TYPE qspi_ip_revid; /* OFFSET: 0x64 */
    CFG_RESERVED_TYPE rsvd3[8]; /* OFFSET: 0x68 */
    CFG_QSPI_FLASH_0_BASE_ADDR_TYPE qspi_flash_0_base_addr; /* OFFSET: 0x70 */
    CFG_QSPI_FLASH_0_SIZE_TYPE qspi_flash_0_size; /* OFFSET: 0x74 */
    CFG_QSPI_FLASH_1_BASE_ADDR_TYPE qspi_flash_1_base_addr; /* OFFSET: 0x78 */
    CFG_QSPI_FLASH_1_SIZE_TYPE qspi_flash_1_size; /* OFFSET: 0x7c */
    CFG_PIO_SYS_INTR_RAW_31_00_TYPE pio_sys_intr_raw_31_00; /* OFFSET: 0x80 */
    CFG_PIO_SYS_INTR_RAW_63_32_TYPE pio_sys_intr_raw_63_32; /* OFFSET: 0x84 */
    CFG_PIO_SYS_INTR_RAW_95_64_TYPE pio_sys_intr_raw_95_64; /* OFFSET: 0x88 */
    CFG_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x8c */
    CFG_PIO_SYS_INTR_STAT_31_00_TYPE pio_sys_intr_stat_31_00; /* OFFSET: 0x90 */
    CFG_PIO_SYS_INTR_STAT_63_32_TYPE pio_sys_intr_stat_63_32; /* OFFSET: 0x94 */
    CFG_PIO_SYS_INTR_STAT_95_64_TYPE pio_sys_intr_stat_95_64; /* OFFSET: 0x98 */
    CFG_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0x9c */
    CFG_PIO_SYS_INTR_MASK_31_00_TYPE pio_sys_intr_mask_31_00; /* OFFSET: 0xa0 */
    CFG_PIO_SYS_INTR_MASK_63_32_TYPE pio_sys_intr_mask_63_32; /* OFFSET: 0xa4 */
    CFG_PIO_SYS_INTR_MASK_95_64_TYPE pio_sys_intr_mask_95_64; /* OFFSET: 0xa8 */
    CFG_RESERVED_TYPE rsvd6[4]; /* OFFSET: 0xac */
    CFG_PIO_SYS_INTR_FORCE_31_00_TYPE pio_sys_intr_force_31_00; /* OFFSET: 0xb0 */
    CFG_PIO_SYS_INTR_FORCE_63_32_TYPE pio_sys_intr_force_63_32; /* OFFSET: 0xb4 */
    CFG_PIO_SYS_INTR_FORCE_95_64_TYPE pio_sys_intr_force_95_64; /* OFFSET: 0xb8 */
    CFG_RESERVED_TYPE rsvd7[4]; /* OFFSET: 0xbc */
    CFG_AHB_MONITOR_CTRL_TYPE ahb_monitor_ctrl; /* OFFSET: 0xc0 */
    CFG_AHB_TIMEOUT_ADDRESS_TYPE ahb_timeout_address; /* OFFSET: 0xc4 */
    CFG_AHB_TIMEOUT_IRQ_STATUS_TYPE ahb_timeout_irq_status; /* OFFSET: 0xc8 */
    CFG_RESERVED_TYPE rsvd8[4]; /* OFFSET: 0xcc */
    CFG_APB_MONITOR_CTRL_TYPE apb_monitor_ctrl; /* OFFSET: 0xd0 */
    CFG_APB_TIMEOUT_ADDRESS_TYPE apb_timeout_address; /* OFFSET: 0xd4 */
    CFG_APB_TIMEOUT_IRQ_STATUS_TYPE apb_timeout_irq_status; /* OFFSET: 0xd8 */
    CFG_RESERVED_TYPE rsvd9[36]; /* OFFSET: 0xdc */
    CFG_WR_DISABLE_PROTECT_STATUS_TYPE wr_disable_protect_status_0; /* OFFSET: 0x100 */
    CFG_WR_ENABLE_PROTECT_STATUS_TYPE wr_en_protect_status_0; /* OFFSET: 0x104 */
    CFG_ADDR_START_PROT_0_TYPE addr_start_prot_0; /* OFFSET: 0x108 */
    CFG_ADDR_END_PROT_0_TYPE addr_end_prot_0; /* OFFSET: 0x10c */
    CFG_WR_DISABLE_PROTECT_STATUS_TYPE wr_disable_protect_status_1; /* OFFSET: 0x110 */
    CFG_WR_ENABLE_PROTECT_STATUS_TYPE wr_en_protect_status_1; /* OFFSET: 0x114 */
    CFG_ADDR_START_PROT_1_TYPE addr_start_prot_1; /* OFFSET: 0x118 */
    CFG_ADDR_END_PROT_1_TYPE addr_end_prot_1; /* OFFSET: 0x11c */
    CFG_WR_DISABLE_PROTECT_STATUS_TYPE wr_disable_protect_status_2; /* OFFSET: 0x120 */
    CFG_WR_ENABLE_PROTECT_STATUS_TYPE wr_en_protect_status_2; /* OFFSET: 0x124 */
    CFG_ADDR_START_PROT_2_TYPE addr_start_prot_2; /* OFFSET: 0x128 */
    CFG_ADDR_END_PROT_2_TYPE addr_end_prot_2; /* OFFSET: 0x12c */
    CFG_WR_DISABLE_PROTECT_STATUS_TYPE wr_disable_protect_status_3; /* OFFSET: 0x130 */
    CFG_WR_ENABLE_PROTECT_STATUS_TYPE wr_en_protect_status_3; /* OFFSET: 0x134 */
    CFG_ADDR_START_PROT_3_TYPE addr_start_prot_3; /* OFFSET: 0x138 */
    CFG_ADDR_END_PROT_3_TYPE addr_end_prot_3; /* OFFSET: 0x13c */
    CFG_RESERVED_TYPE rsvd10[192]; /* OFFSET: 0x140 */
    CFG_MISC_CTRL_TYPE misc_ctrl; /* OFFSET: 0x200 */
    CFG_DEBUG_CTRL_TYPE debug_ctrl; /* OFFSET: 0x204 */
    CFG_RESERVED_TYPE rsvd11[3320]; /* OFFSET: 0x208 */
    CFG_FEATURE_ENABLE_TYPE feature_enable; /* OFFSET: 0xf00 */
    CFG_RESERVED_TYPE rsvd12[236]; /* OFFSET: 0xf04 */
    CFG_IND_REGS_CTRL_TYPE ind_regs_ctrl_ser; /* OFFSET: 0xff0 */
    CFG_IND_REGS_ADDR_TYPE ind_regs_addr_ser; /* OFFSET: 0xff4 */
    CFG_IND_REGS_DATA_L_TYPE ind_regs_data_ser_l; /* OFFSET: 0xff8 */
    CFG_IND_REGS_DATA_H_TYPE ind_regs_data_ser_h; /* OFFSET: 0xffc */
} CFG_RDBType;


#define CFG_BASE                        (0x40000000UL)



#define CFG_MAX_HW_ID                   (1UL)


#define PIOCFG_PAD_GRP_MASK             (0x7UL)


#define PIOCFG_AMAC_IO_CTRL_SRC_SYNC_MODE_MASK  (0x4UL)


#define PIOCFG_AMAC_IO_CTRL_SRC_SYNC_MODE_SHIFT  (2UL)


#define PIOCFG_AMAC_IO_CTRL_DEST_SYNC_MODE_MASK  (0x8UL)


#define PIOCFG_AMAC_IO_CTRL_DEST_SYNC_MODE_SHIFT  (3UL)


#define PIOCFG_AMAC_IO_CTRL_CLK_250_EN_MASK  (0x40UL)


#define PIOCFG_AMAC_IO_CTRL_CLK_250_EN_SHIFT  (6UL)


#define PIOCFG_RGMII_CTRL_RGMII_SPEED_1000MBPS  (2UL)


#define PIOCFG_RGMII_CTRL_RGMII_SPEED_100MBPS  (1UL)

#endif /* CFG_RDB_H */
