/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file disp_misc_rdb.h
    @brief RDB File for DISP_MISC

    @version 2018May25_rdb
*/

#ifndef DISP_MISC_RDB_H
#define DISP_MISC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t DISP_MISC_ISPO_CTRL_TYPE;
#define DISP_MISC_ISPO_CTRL_ISP_CTRL_MASK (0xc0000000UL)
#define DISP_MISC_ISPO_CTRL_ISP_CTRL_SHIFT (30UL)
#define DISP_MISC_ISPO_CTRL_SHIFT3_MASK (0x3c000000UL)
#define DISP_MISC_ISPO_CTRL_SHIFT3_SHIFT (26UL)
#define DISP_MISC_ISPO_CTRL_SHIFT2_MASK (0x3c00000UL)
#define DISP_MISC_ISPO_CTRL_SHIFT2_SHIFT (22UL)
#define DISP_MISC_ISPO_CTRL_SHIFT1_MASK (0x3c0000UL)
#define DISP_MISC_ISPO_CTRL_SHIFT1_SHIFT (18UL)
#define DISP_MISC_ISPO_CTRL_RAW_FORMAT_MASK (0x3e000UL)
#define DISP_MISC_ISPO_CTRL_RAW_FORMAT_SHIFT (13UL)
#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_MASK (0x1e00UL)
#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_SHIFT (9UL)
#define DISP_MISC_ISPO_CTRL_OUTPUT_WIDTH_MASK (0x100UL)
#define DISP_MISC_ISPO_CTRL_OUTPUT_WIDTH_SHIFT (8UL)
#define DISP_MISC_ISPO_CTRL_COL_MODE_MASK (0x80UL)
#define DISP_MISC_ISPO_CTRL_COL_MODE_SHIFT (7UL)
#define DISP_MISC_ISPO_CTRL_COL_WIDTH_MASK (0x60UL)
#define DISP_MISC_ISPO_CTRL_COL_WIDTH_SHIFT (5UL)
#define DISP_MISC_ISPO_CTRL_VFLIP_MASK (0x10UL)
#define DISP_MISC_ISPO_CTRL_VFLIP_SHIFT (4UL)
#define DISP_MISC_ISPO_CTRL_BIG_ENDIAN_MASK (0x8UL)
#define DISP_MISC_ISPO_CTRL_BIG_ENDIAN_SHIFT (3UL)
#define DISP_MISC_ISPO_CTRL_PLANE_ENABLES_MASK (0x7UL)
#define DISP_MISC_ISPO_CTRL_PLANE_ENABLES_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_ADDRESS1_TYPE;
#define DISP_MISC_ISPO_ADDRESS1_ADDRESS1_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_ADDRESS1_ADDRESS1_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_ADDRESS2_TYPE;
#define DISP_MISC_ISPO_ADDRESS2_ADDRESS2_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_ADDRESS2_ADDRESS2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_ADDRESS3_TYPE;
#define DISP_MISC_ISPO_ADDRESS3_ADDRESS3_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_ADDRESS3_ADDRESS3_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_STRIDE1_TYPE;
#define DISP_MISC_ISPO_STRIDE1_STRIDE1_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_STRIDE1_STRIDE1_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_STRIDE2_TYPE;
#define DISP_MISC_ISPO_STRIDE2_STRIDE2_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_STRIDE2_STRIDE2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_STRIDE3_TYPE;
#define DISP_MISC_ISPO_STRIDE3_STRIDE3_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_STRIDE3_STRIDE3_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_COL_STRIDE1_TYPE;
#define DISP_MISC_ISPO_COL_STRIDE1_STRIDE1_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_COL_STRIDE1_STRIDE1_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_COL_STRIDE2_TYPE;
#define DISP_MISC_ISPO_COL_STRIDE2_STRIDE2_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_COL_STRIDE2_STRIDE2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_ENDADDR1_TYPE;
#define DISP_MISC_ISPO_ENDADDR1_ENDADDR1_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_ENDADDR1_ENDADDR1_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_ENDADDR2_TYPE;
#define DISP_MISC_ISPO_ENDADDR2_ENDADDR2_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_ENDADDR2_ENDADDR2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_ENDADDR3_TYPE;
#define DISP_MISC_ISPO_ENDADDR3_ENDADDR3_MASK (0xffffffffUL)
#define DISP_MISC_ISPO_ENDADDR3_ENDADDR3_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_FIFO_TYPE;
#define DISP_MISC_ISPO_FIFO_MIN3_MASK (0x3f80UL)
#define DISP_MISC_ISPO_FIFO_MIN3_SHIFT (7UL)
#define DISP_MISC_ISPO_FIFO_MIN2_MASK (0x7fUL)
#define DISP_MISC_ISPO_FIFO_MIN2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_SYNC_CTRL_TYPE;
#define DISP_MISC_ISPO_SYNC_CTRL_CTRL_RSVD_B_MASK (0xf0000000UL)
#define DISP_MISC_ISPO_SYNC_CTRL_CTRL_RSVD_B_SHIFT (28UL)
#define DISP_MISC_ISPO_SYNC_CTRL_THRESH_MASK (0xfff0000UL)
#define DISP_MISC_ISPO_SYNC_CTRL_THRESH_SHIFT (16UL)
#define DISP_MISC_ISPO_SYNC_CTRL_CTRL_RSVD_A_MASK (0xe000UL)
#define DISP_MISC_ISPO_SYNC_CTRL_CTRL_RSVD_A_SHIFT (13UL)
#define DISP_MISC_ISPO_SYNC_CTRL_LINES_FRAME_END_OPTION_MASK (0x1000UL)
#define DISP_MISC_ISPO_SYNC_CTRL_LINES_FRAME_END_OPTION_SHIFT (12UL)
#define DISP_MISC_ISPO_SYNC_CTRL_LINES_MASK (0xfffUL)
#define DISP_MISC_ISPO_SYNC_CTRL_LINES_SHIFT (0UL)




typedef uint32_t DISP_MISC_IWTWH_TYPE;
#define DISP_MISC_IWTWH_WRITEBACK_TILE_WIDTH_MASK (0xffff0000UL)
#define DISP_MISC_IWTWH_WRITEBACK_TILE_WIDTH_SHIFT (16UL)
#define DISP_MISC_IWTWH_WRITEBACK_TILE_HEIGHT_MASK (0xffffUL)
#define DISP_MISC_IWTWH_WRITEBACK_TILE_HEIGHT_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPO_WRITEBACK_TILE_MISC_TYPE;
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_FLUSH_MASK (0x4000UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_FLUSH_SHIFT (14UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_ACTIVE_MASK (0x2000UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_ACTIVE_SHIFT (13UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_ENABLE_MASK (0x1000UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_ENABLE_SHIFT (12UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_PIPESTAGE_EN_MASK (0x800UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_ISPO_PIPESTAGE_EN_SHIFT (11UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_WRITEBACK_TILE_X_MASK (0x600UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_WRITEBACK_TILE_X_SHIFT (9UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_WRITEBACK_TILE_Y_MASK (0x100UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_WRITEBACK_TILE_Y_SHIFT (8UL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_MAX_BURST_LEN_MASK (0xffUL)
#define DISP_MISC_ISPO_WRITEBACK_TILE_MISC_MAX_BURST_LEN_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_CTRL_TYPE;
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_D_MASK (0xc0000000UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_D_SHIFT (30UL)
#define DISP_MISC_ISPYI_CTRL_MAX_BURST_LEN_MASK (0x3c000000UL)
#define DISP_MISC_ISPYI_CTRL_MAX_BURST_LEN_SHIFT (26UL)
#define DISP_MISC_ISPYI_CTRL_COL_WIDTH_MASK (0x3000000UL)
#define DISP_MISC_ISPYI_CTRL_COL_WIDTH_SHIFT (24UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_A_MASK (0xf80000UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_A_SHIFT (19UL)
#define DISP_MISC_ISPYI_CTRL_TILE_X_MASK (0x70000UL)
#define DISP_MISC_ISPYI_CTRL_TILE_X_SHIFT (16UL)
#define DISP_MISC_ISPYI_CTRL_FLUSH_MASK (0x8000UL)
#define DISP_MISC_ISPYI_CTRL_FLUSH_SHIFT (15UL)
#define DISP_MISC_ISPYI_CTRL_ENABLE_MASK (0x4000UL)
#define DISP_MISC_ISPYI_CTRL_ENABLE_SHIFT (14UL)
#define DISP_MISC_ISPYI_CTRL_ACTIVE_MASK (0x2000UL)
#define DISP_MISC_ISPYI_CTRL_ACTIVE_SHIFT (13UL)
#define DISP_MISC_ISPYI_CTRL_COL_MODE_MASK (0x1000UL)
#define DISP_MISC_ISPYI_CTRL_COL_MODE_SHIFT (12UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_B_MASK (0xc00UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_B_SHIFT (10UL)
#define DISP_MISC_ISPYI_CTRL_CC_ORDER_MASK (0x380UL)
#define DISP_MISC_ISPYI_CTRL_CC_ORDER_SHIFT (7UL)
#define DISP_MISC_ISPYI_CTRL_DATA_FORMAT_MASK (0x70UL)
#define DISP_MISC_ISPYI_CTRL_DATA_FORMAT_SHIFT (4UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_C_MASK (0x8UL)
#define DISP_MISC_ISPYI_CTRL_ISPYI_CTRL_RSVD_C_SHIFT (3UL)
#define DISP_MISC_ISPYI_CTRL_BYTES_SAMPLE_MASK (0x4UL)
#define DISP_MISC_ISPYI_CTRL_BYTES_SAMPLE_SHIFT (2UL)
#define DISP_MISC_ISPYI_CTRL_CS_FORMAT_MASK (0x3UL)
#define DISP_MISC_ISPYI_CTRL_CS_FORMAT_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_RY_ADDR_TYPE;
#define DISP_MISC_ISPYI_RY_ADDR_ADDR_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_RY_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_GU_ADDR_TYPE;
#define DISP_MISC_ISPYI_GU_ADDR_ADDR_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_GU_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_BV_ADDR_TYPE;
#define DISP_MISC_ISPYI_BV_ADDR_ADDR_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_BV_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_STRIDE1_TYPE;
#define DISP_MISC_ISPYI_STRIDE1_STRIDE1_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_STRIDE1_STRIDE1_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_STRIDE2_TYPE;
#define DISP_MISC_ISPYI_STRIDE2_STRIDE2_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_STRIDE2_STRIDE2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_COL_STRIDE1_TYPE;
#define DISP_MISC_ISPYI_COL_STRIDE1_STRIDE1_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_COL_STRIDE1_STRIDE1_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_COL_STRIDE2_TYPE;
#define DISP_MISC_ISPYI_COL_STRIDE2_STRIDE2_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_COL_STRIDE2_STRIDE2_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_RY_EADDR_TYPE;
#define DISP_MISC_ISPYI_RY_EADDR_EADDR_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_RY_EADDR_EADDR_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_GU_EADDR_TYPE;
#define DISP_MISC_ISPYI_GU_EADDR_EADDR_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_GU_EADDR_EADDR_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_BV_EADDR_TYPE;
#define DISP_MISC_ISPYI_BV_EADDR_EADDR_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_BV_EADDR_EADDR_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_TOP_CTRL_TYPE;
#define DISP_MISC_DISP_TOP_CTRL_DISP_LOW_LATENCY_MODE_MASK (0x80000000UL)
#define DISP_MISC_DISP_TOP_CTRL_DISP_LOW_LATENCY_MODE_SHIFT (31UL)
#define DISP_MISC_DISP_TOP_CTRL_AXI_IO_FLUSH_MASK (0x40000000UL)
#define DISP_MISC_DISP_TOP_CTRL_AXI_IO_FLUSH_SHIFT (30UL)
#define DISP_MISC_DISP_TOP_CTRL_GFD_CLK_FREERUN_MODE_MASK (0x20000000UL)
#define DISP_MISC_DISP_TOP_CTRL_GFD_CLK_FREERUN_MODE_SHIFT (29UL)
#define DISP_MISC_DISP_TOP_CTRL_GFD_BRIDGE_BIG_ENDIAN_MODE_MASK (0x10000000UL)
#define DISP_MISC_DISP_TOP_CTRL_GFD_BRIDGE_BIG_ENDIAN_MODE_SHIFT (28UL)
#define DISP_MISC_DISP_TOP_CTRL_SW_INIT_MASK (0x8000000UL)
#define DISP_MISC_DISP_TOP_CTRL_SW_INIT_SHIFT (27UL)
#define DISP_MISC_DISP_TOP_CTRL_AXI_BRIDGE_BIG_ENDIAN_MODE_MASK (0x4000000UL)
#define DISP_MISC_DISP_TOP_CTRL_AXI_BRIDGE_BIG_ENDIAN_MODE_SHIFT (26UL)
#define DISP_MISC_DISP_TOP_CTRL_CMP_2_PV_MODULE_INIT_MASK (0x2000000UL)
#define DISP_MISC_DISP_TOP_CTRL_CMP_2_PV_MODULE_INIT_SHIFT (25UL)
#define DISP_MISC_DISP_TOP_CTRL_VSYNC_MASK_MASK (0x1000000UL)
#define DISP_MISC_DISP_TOP_CTRL_VSYNC_MASK_SHIFT (24UL)
#define DISP_MISC_DISP_TOP_CTRL_DMA_MASK_MASK (0x800000UL)
#define DISP_MISC_DISP_TOP_CTRL_DMA_MASK_SHIFT (23UL)
#define DISP_MISC_DISP_TOP_CTRL_DMA_TRIGGER_SEL_MASK (0x600000UL)
#define DISP_MISC_DISP_TOP_CTRL_DMA_TRIGGER_SEL_SHIFT (21UL)
#define DISP_MISC_DISP_TOP_CTRL_CMP_DOWNSTREAM_SEL_MASK (0x100000UL)
#define DISP_MISC_DISP_TOP_CTRL_CMP_DOWNSTREAM_SEL_SHIFT (20UL)
#define DISP_MISC_DISP_TOP_CTRL_AWCACHE_MASK (0xf0000UL)
#define DISP_MISC_DISP_TOP_CTRL_AWCACHE_SHIFT (16UL)
#define DISP_MISC_DISP_TOP_CTRL_ARCACHE_MASK (0xf000UL)
#define DISP_MISC_DISP_TOP_CTRL_ARCACHE_SHIFT (12UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_11_PWRDN_MASK (0x800UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_11_PWRDN_SHIFT (11UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_10_PWRDN_MASK (0x400UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_10_PWRDN_SHIFT (10UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_9_PWRDN_MASK (0x200UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_9_PWRDN_SHIFT (9UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_8_PWRDN_MASK (0x100UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_8_PWRDN_SHIFT (8UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_7_PWRDN_MASK (0x80UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_7_PWRDN_SHIFT (7UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_6_PWRDN_MASK (0x40UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_6_PWRDN_SHIFT (6UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_5_PWRDN_MASK (0x20UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_5_PWRDN_SHIFT (5UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_4_PWRDN_MASK (0x10UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_4_PWRDN_SHIFT (4UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_3_PWRDN_MASK (0x8UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_3_PWRDN_SHIFT (3UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_2_PWRDN_MASK (0x4UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_2_PWRDN_SHIFT (2UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_1_PWRDN_MASK (0x2UL)
#define DISP_MISC_DISP_TOP_CTRL_MEM_1_PWRDN_SHIFT (1UL)
#define DISP_MISC_DISP_TOP_CTRL_DISP_CTRL_EN_MASK (0x1UL)
#define DISP_MISC_DISP_TOP_CTRL_DISP_CTRL_EN_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_TILE_WIDTH_TYPE;
#define DISP_MISC_ISPYI_TILE_WIDTH_WIDTH_MASK (0x1fffUL)
#define DISP_MISC_ISPYI_TILE_WIDTH_WIDTH_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_TILE_HEIGHT_TYPE;
#define DISP_MISC_ISPYI_TILE_HEIGHT_HEIGHT_MASK (0x1fffUL)
#define DISP_MISC_ISPYI_TILE_HEIGHT_HEIGHT_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_LUMA_OFFSET_TYPE;
#define DISP_MISC_ISPYI_LUMA_OFFSET_OFFSET_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_LUMA_OFFSET_OFFSET_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPYI_CHROMA_OFFSET_TYPE;
#define DISP_MISC_ISPYI_CHROMA_OFFSET_OFFSET_MASK (0xffffffffUL)
#define DISP_MISC_ISPYI_CHROMA_OFFSET_OFFSET_SHIFT (0UL)




typedef uint32_t DISP_MISC_IWTO1_TYPE;
#define DISP_MISC_IWTO1_WRITEBACK_TILE_OFFSET1_MASK (0xffffffffUL)
#define DISP_MISC_IWTO1_WRITEBACK_TILE_OFFSET1_SHIFT (0UL)




typedef uint32_t DISP_MISC_IWTO2_TYPE;
#define DISP_MISC_IWTO2_WRITEBACK_TILE_OFFSET2_MASK (0xffffffffUL)
#define DISP_MISC_IWTO2_WRITEBACK_TILE_OFFSET2_SHIFT (0UL)




typedef uint32_t DISP_MISC_IWTO3_TYPE;
#define DISP_MISC_IWTO3_WRITEBACK_TILE_OFFSET3_MASK (0xffffffffUL)
#define DISP_MISC_IWTO3_WRITEBACK_TILE_OFFSET3_SHIFT (0UL)




typedef uint32_t DISP_MISC_IWTCI_TYPE;
#define DISP_MISC_IWTCI_WRITEBACK_TILE_COL_IDX_MASK (0xffUL)
#define DISP_MISC_IWTCI_WRITEBACK_TILE_COL_IDX_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_LVDS_FRAMER_TYPE;
#define DISP_MISC_DISP_LVDS_FRAMER_MISC_CONTROL_MASK (0xfffcUL)
#define DISP_MISC_DISP_LVDS_FRAMER_MISC_CONTROL_SHIFT (2UL)
#define DISP_MISC_DISP_LVDS_FRAMER_MAPSEL_MASK (0x2UL)
#define DISP_MISC_DISP_LVDS_FRAMER_MAPSEL_SHIFT (1UL)
#define DISP_MISC_DISP_LVDS_FRAMER_MODE_24BIT_MASK (0x1UL)
#define DISP_MISC_DISP_LVDS_FRAMER_MODE_24BIT_SHIFT (0UL)




typedef uint32_t DISP_MISC_BMC_TYPE;
#define DISP_MISC_BMC_BACKEND_SPARE_MASK (0xfff80000UL)
#define DISP_MISC_BMC_BACKEND_SPARE_SHIFT (19UL)
#define DISP_MISC_BMC_BT656_CHROMA_INTERP_EN_MASK (0x40000UL)
#define DISP_MISC_BMC_BT656_CHROMA_INTERP_EN_SHIFT (18UL)
#define DISP_MISC_BMC_BT656_LUMA_SHIFT_MASK (0x20000UL)
#define DISP_MISC_BMC_BT656_LUMA_SHIFT_SHIFT (17UL)
#define DISP_MISC_BMC_LVDS_CR_CB_SWAP_MASK (0x10000UL)
#define DISP_MISC_BMC_LVDS_CR_CB_SWAP_SHIFT (16UL)
#define DISP_MISC_BMC_BT656_PARALLEL_CLK_DELAY_SEL_MASK (0xe000UL)
#define DISP_MISC_BMC_BT656_PARALLEL_CLK_DELAY_SEL_SHIFT (13UL)
#define DISP_MISC_BMC_BT656_PARALLEL_CLK_SEL_MASK (0x1000UL)
#define DISP_MISC_BMC_BT656_PARALLEL_CLK_SEL_SHIFT (12UL)
#define DISP_MISC_BMC_BT656_PARALLEL_CLK_PHASE_SHIFT_MASK (0x800UL)
#define DISP_MISC_BMC_BT656_PARALLEL_CLK_PHASE_SHIFT_SHIFT (11UL)
#define DISP_MISC_BMC_BT656_OUTPUT_DATA_SEL_MASK (0x400UL)
#define DISP_MISC_BMC_BT656_OUTPUT_DATA_SEL_SHIFT (10UL)
#define DISP_MISC_BMC_YUV_2_RGB_BYPASS_MASK (0x200UL)
#define DISP_MISC_BMC_YUV_2_RGB_BYPASS_SHIFT (9UL)
#define DISP_MISC_BMC_PIXEL_VID_EN_MASK (0x100UL)
#define DISP_MISC_BMC_PIXEL_VID_EN_SHIFT (8UL)
#define DISP_MISC_BMC_PIXEL_CLK_SEL_MASK (0xe0UL)
#define DISP_MISC_BMC_PIXEL_CLK_SEL_SHIFT (5UL)
#define DISP_MISC_BMC_DSI_TE1_TRIG_MASK (0x10UL)
#define DISP_MISC_BMC_DSI_TE1_TRIG_SHIFT (4UL)
#define DISP_MISC_BMC_DSI_TE0_TRIG_MASK (0x8UL)
#define DISP_MISC_BMC_DSI_TE0_TRIG_SHIFT (3UL)
#define DISP_MISC_BMC_DSI_TE1_LEVEL_MASK (0x4UL)
#define DISP_MISC_BMC_DSI_TE1_LEVEL_SHIFT (2UL)
#define DISP_MISC_BMC_DSI_TE0_LEVEL_MASK (0x2UL)
#define DISP_MISC_BMC_DSI_TE0_LEVEL_SHIFT (1UL)
#define DISP_MISC_BMC_RGB_COLOR_SHIFT_MASK (0x1UL)
#define DISP_MISC_BMC_RGB_COLOR_SHIFT_SHIFT (0UL)




typedef uint32_t DISP_MISC_TEST_CTRL_TYPE;
#define DISP_MISC_TEST_CTRL_DISP_START_TEST_MASK (0x1000UL)
#define DISP_MISC_TEST_CTRL_DISP_START_TEST_SHIFT (12UL)
#define DISP_MISC_TEST_CTRL_TPOUT_TOP_SEL_MASK (0xf00UL)
#define DISP_MISC_TEST_CTRL_TPOUT_TOP_SEL_SHIFT (8UL)
#define DISP_MISC_TEST_CTRL_TPOUT_BACK_SEL_MASK (0xf0UL)
#define DISP_MISC_TEST_CTRL_TPOUT_BACK_SEL_SHIFT (4UL)
#define DISP_MISC_TEST_CTRL_TPOUT_FRONT_SEL_MASK (0xfUL)
#define DISP_MISC_TEST_CTRL_TPOUT_FRONT_SEL_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_TOP_CTRL2_TYPE;
#define DISP_MISC_DISP_TOP_CTRL2_DISP_SYS_CLK_EN_MASK (0x80000000UL)
#define DISP_MISC_DISP_TOP_CTRL2_DISP_SYS_CLK_EN_SHIFT (31UL)
#define DISP_MISC_DISP_TOP_CTRL2_PV_BKGD_EN_MASK (0x40000000UL)
#define DISP_MISC_DISP_TOP_CTRL2_PV_BKGD_EN_SHIFT (30UL)
#define DISP_MISC_DISP_TOP_CTRL2_TOP_CTRL2_SPARE_MASK (0x3fc00000UL)
#define DISP_MISC_DISP_TOP_CTRL2_TOP_CTRL2_SPARE_SHIFT (22UL)
#define DISP_MISC_DISP_TOP_CTRL2_CMP_TO_IOF_DATA_FORMAT_MASK (0x300000UL)
#define DISP_MISC_DISP_TOP_CTRL2_CMP_TO_IOF_DATA_FORMAT_SHIFT (20UL)
#define DISP_MISC_DISP_TOP_CTRL2_SWAP_CMP_CR_CB_OUTPUT_MASK (0x80000UL)
#define DISP_MISC_DISP_TOP_CTRL2_SWAP_CMP_CR_CB_OUTPUT_SHIFT (19UL)
#define DISP_MISC_DISP_TOP_CTRL2_SPARE1_MASK (0x40000UL)
#define DISP_MISC_DISP_TOP_CTRL2_SPARE1_SHIFT (18UL)
#define DISP_MISC_DISP_TOP_CTRL2_SWAP_IIF_CR_CB_MASK (0x20000UL)
#define DISP_MISC_DISP_TOP_CTRL2_SWAP_IIF_CR_CB_SHIFT (17UL)
#define DISP_MISC_DISP_TOP_CTRL2_MFD_TIMEBASE_MASK (0x1fffeUL)
#define DISP_MISC_DISP_TOP_CTRL2_MFD_TIMEBASE_SHIFT (1UL)
#define DISP_MISC_DISP_TOP_CTRL2_ENA_PV_START_MASK (0x1UL)
#define DISP_MISC_DISP_TOP_CTRL2_ENA_PV_START_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_AXI_IO_CTRL_TYPE;
#define DISP_MISC_DISP_AXI_IO_CTRL_CONTROL_MASK (0xffffffffUL)
#define DISP_MISC_DISP_AXI_IO_CTRL_CONTROL_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_AXI_IO_CTRL2_TYPE;
#define DISP_MISC_DISP_AXI_IO_CTRL2_CONFIG_MASK (0x1ffUL)
#define DISP_MISC_DISP_AXI_IO_CTRL2_CONFIG_SHIFT (0UL)




typedef uint32_t DISP_MISC_EN_PV_STATUS_TYPE;
#define DISP_MISC_EN_PV_STATUS_PV_STATE_MASK (0x38UL)
#define DISP_MISC_EN_PV_STATUS_PV_STATE_SHIFT (3UL)
#define DISP_MISC_EN_PV_STATUS_WB_STATE_MASK (0x7UL)
#define DISP_MISC_EN_PV_STATUS_WB_STATE_SHIFT (0UL)




typedef uint32_t DISP_MISC_PV_BKGD_COLOR_TYPE;
#define DISP_MISC_PV_BKGD_COLOR_Y_MASK (0xff0000UL)
#define DISP_MISC_PV_BKGD_COLOR_Y_SHIFT (16UL)
#define DISP_MISC_PV_BKGD_COLOR_U_MASK (0xff00UL)
#define DISP_MISC_PV_BKGD_COLOR_U_SHIFT (8UL)
#define DISP_MISC_PV_BKGD_COLOR_V_MASK (0xffUL)
#define DISP_MISC_PV_BKGD_COLOR_V_SHIFT (0UL)




typedef uint32_t DISP_MISC_ISPI_FIFO_TYPE;
#define DISP_MISC_ISPI_FIFO_MIN3_MASK (0x3f80UL)
#define DISP_MISC_ISPI_FIFO_MIN3_SHIFT (7UL)
#define DISP_MISC_ISPI_FIFO_MIN2_MASK (0x7fUL)
#define DISP_MISC_ISPI_FIFO_MIN2_SHIFT (0UL)




typedef uint32_t DISP_MISC_AXI_STATUS_TYPE;
#define DISP_MISC_AXI_STATUS_GFD_ERR_MASK (0x100UL)
#define DISP_MISC_AXI_STATUS_GFD_ERR_SHIFT (8UL)
#define DISP_MISC_AXI_STATUS_GFD_RD_ERR_RESP_MASK (0xc0UL)
#define DISP_MISC_AXI_STATUS_GFD_RD_ERR_RESP_SHIFT (6UL)
#define DISP_MISC_AXI_STATUS_IIF_IOF_ERR_MASK (0x20UL)
#define DISP_MISC_AXI_STATUS_IIF_IOF_ERR_SHIFT (5UL)
#define DISP_MISC_AXI_STATUS_IIF_RD_ERR_RESP_MASK (0x18UL)
#define DISP_MISC_AXI_STATUS_IIF_RD_ERR_RESP_SHIFT (3UL)
#define DISP_MISC_AXI_STATUS_IOF_WR_ERR_RESP_MASK (0x6UL)
#define DISP_MISC_AXI_STATUS_IOF_WR_ERR_RESP_SHIFT (1UL)
#define DISP_MISC_AXI_STATUS_CLR_ERR_FIELD_MASK (0x1UL)
#define DISP_MISC_AXI_STATUS_CLR_ERR_FIELD_SHIFT (0UL)




typedef uint32_t DISP_MISC_SCB_AXI_BRIDGE_TYPE;
#define DISP_MISC_SCB_AXI_BRIDGE_SCB_BRIDGE_AXI_ARCACHE_MASK (0xf00UL)
#define DISP_MISC_SCB_AXI_BRIDGE_SCB_BRIDGE_AXI_ARCACHE_SHIFT (8UL)
#define DISP_MISC_SCB_AXI_BRIDGE_SCB_BRIDGE_AXI_ID_MASK (0xf0UL)
#define DISP_MISC_SCB_AXI_BRIDGE_SCB_BRIDGE_AXI_ID_SHIFT (4UL)
#define DISP_MISC_SCB_AXI_BRIDGE_BRIDGE_MISC_MASK (0xcUL)
#define DISP_MISC_SCB_AXI_BRIDGE_BRIDGE_MISC_SHIFT (2UL)
#define DISP_MISC_SCB_AXI_BRIDGE_MAX_BURST_LEN_CONTROL_MASK (0x3UL)
#define DISP_MISC_SCB_AXI_BRIDGE_MAX_BURST_LEN_CONTROL_SHIFT (0UL)




typedef uint8_t DISP_MISC_RESERVED_TYPE;




typedef uint32_t DISP_MISC_DISP_SPARE_0_TYPE;
#define DISP_MISC_DISP_SPARE_0_0_MASK (0xffffffffUL)
#define DISP_MISC_DISP_SPARE_0_0_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_SPARE_1_TYPE;
#define DISP_MISC_DISP_SPARE_1_1_MASK (0xffffffffUL)
#define DISP_MISC_DISP_SPARE_1_1_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_SPARE_2_TYPE;
#define DISP_MISC_DISP_SPARE_2_2_MASK (0xffffffffUL)
#define DISP_MISC_DISP_SPARE_2_2_SHIFT (0UL)




typedef uint32_t DISP_MISC_DISP_SPARE_3_TYPE;
#define DISP_MISC_DISP_SPARE_3_3_MASK (0xffffffffUL)
#define DISP_MISC_DISP_SPARE_3_3_SHIFT (0UL)




typedef volatile struct COMP_PACKED _DISP_MISC_RDBType {
    DISP_MISC_ISPO_CTRL_TYPE ispo_ctrl; /* OFFSET: 0x0 */
    DISP_MISC_ISPO_ADDRESS1_TYPE ispo_address1; /* OFFSET: 0x4 */
    DISP_MISC_ISPO_ADDRESS2_TYPE ispo_address2; /* OFFSET: 0x8 */
    DISP_MISC_ISPO_ADDRESS3_TYPE ispo_address3; /* OFFSET: 0xc */
    DISP_MISC_ISPO_STRIDE1_TYPE ispo_stride1; /* OFFSET: 0x10 */
    DISP_MISC_ISPO_STRIDE2_TYPE ispo_stride2; /* OFFSET: 0x14 */
    DISP_MISC_ISPO_STRIDE3_TYPE ispo_stride3; /* OFFSET: 0x18 */
    DISP_MISC_ISPO_COL_STRIDE1_TYPE ispo_col_stride1; /* OFFSET: 0x1c */
    DISP_MISC_ISPO_COL_STRIDE2_TYPE ispo_col_stride2; /* OFFSET: 0x20 */
    DISP_MISC_ISPO_ENDADDR1_TYPE ispo_endaddr1; /* OFFSET: 0x24 */
    DISP_MISC_ISPO_ENDADDR2_TYPE ispo_endaddr2; /* OFFSET: 0x28 */
    DISP_MISC_ISPO_ENDADDR3_TYPE ispo_endaddr3; /* OFFSET: 0x2c */
    DISP_MISC_ISPO_FIFO_TYPE ispo_fifo; /* OFFSET: 0x30 */
    DISP_MISC_ISPO_SYNC_CTRL_TYPE ispo_sync_ctrl; /* OFFSET: 0x34 */
    DISP_MISC_IWTWH_TYPE ispo_writeback_tile_width_height; /* OFFSET: 0x38 */
    DISP_MISC_ISPO_WRITEBACK_TILE_MISC_TYPE ispo_writeback_tile_misc; /* OFFSET: 0x3c */
    DISP_MISC_ISPYI_CTRL_TYPE ispyi_ctrl; /* OFFSET: 0x40 */
    DISP_MISC_ISPYI_RY_ADDR_TYPE ispyi_ry_addr; /* OFFSET: 0x44 */
    DISP_MISC_ISPYI_GU_ADDR_TYPE ispyi_gu_addr; /* OFFSET: 0x48 */
    DISP_MISC_ISPYI_BV_ADDR_TYPE ispyi_bv_addr; /* OFFSET: 0x4c */
    DISP_MISC_ISPYI_STRIDE1_TYPE ispyi_stride1; /* OFFSET: 0x50 */
    DISP_MISC_ISPYI_STRIDE2_TYPE ispyi_stride2; /* OFFSET: 0x54 */
    DISP_MISC_ISPYI_COL_STRIDE1_TYPE ispyi_col_stride1; /* OFFSET: 0x58 */
    DISP_MISC_ISPYI_COL_STRIDE2_TYPE ispyi_col_stride2; /* OFFSET: 0x5c */
    DISP_MISC_ISPYI_RY_EADDR_TYPE ispyi_ry_eaddr; /* OFFSET: 0x60 */
    DISP_MISC_ISPYI_GU_EADDR_TYPE ispyi_gu_eaddr; /* OFFSET: 0x64 */
    DISP_MISC_ISPYI_BV_EADDR_TYPE ispyi_bv_eaddr; /* OFFSET: 0x68 */
    DISP_MISC_DISP_TOP_CTRL_TYPE top_control; /* OFFSET: 0x6c */
    DISP_MISC_ISPYI_TILE_WIDTH_TYPE ispyi_tile_width; /* OFFSET: 0x70 */
    DISP_MISC_ISPYI_TILE_HEIGHT_TYPE ispyi_tile_height; /* OFFSET: 0x74 */
    DISP_MISC_ISPYI_LUMA_OFFSET_TYPE ispyi_luma_offset; /* OFFSET: 0x78 */
    DISP_MISC_ISPYI_CHROMA_OFFSET_TYPE ispyi_chroma_offset; /* OFFSET: 0x7c */
    DISP_MISC_IWTO1_TYPE ispo_writeback_tile_offset1; /* OFFSET: 0x80 */
    DISP_MISC_IWTO2_TYPE ispo_writeback_tile_offset2; /* OFFSET: 0x84 */
    DISP_MISC_IWTO3_TYPE ispo_writeback_tile_offset3; /* OFFSET: 0x88 */
    DISP_MISC_IWTCI_TYPE ispo_writeback_tile_col_idx; /* OFFSET: 0x8c */
    DISP_MISC_DISP_LVDS_FRAMER_TYPE lvds_framer; /* OFFSET: 0x90 */
    DISP_MISC_BMC_TYPE backend_misc_ctrl; /* OFFSET: 0x94 */
    DISP_MISC_TEST_CTRL_TYPE test_ctrl; /* OFFSET: 0x98 */
    DISP_MISC_DISP_TOP_CTRL2_TYPE top_control2; /* OFFSET: 0x9c */
    DISP_MISC_DISP_AXI_IO_CTRL_TYPE axi_io_ctrl; /* OFFSET: 0xa0 */
    DISP_MISC_DISP_AXI_IO_CTRL2_TYPE axi_io_ctrl2; /* OFFSET: 0xa4 */
    DISP_MISC_EN_PV_STATUS_TYPE ev_pv_status; /* OFFSET: 0xa8 */
    DISP_MISC_PV_BKGD_COLOR_TYPE pv_bkgd_color; /* OFFSET: 0xac */
    DISP_MISC_ISPI_FIFO_TYPE ispi_fifo; /* OFFSET: 0xb0 */
    DISP_MISC_AXI_STATUS_TYPE axi_status; /* OFFSET: 0xb4 */
    DISP_MISC_SCB_AXI_BRIDGE_TYPE scb_axi_bridge; /* OFFSET: 0xb8 */
    DISP_MISC_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0xbc */
    DISP_MISC_DISP_SPARE_0_TYPE spare_0; /* OFFSET: 0xc0 */
    DISP_MISC_DISP_SPARE_1_TYPE spare_1; /* OFFSET: 0xc4 */
    DISP_MISC_DISP_SPARE_2_TYPE spare_2; /* OFFSET: 0xc8 */
    DISP_MISC_DISP_SPARE_3_TYPE spare_3; /* OFFSET: 0xcc */
} DISP_MISC_RDBType;


#define FMISC_BASE                      (0x400A3000UL)



#define DISP_MISC_MAX_HW_ID             (1UL)


#define MISC_ISPO_SYNC_LINES            (16UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_422P  (5UL)


#define DISP_MISC_ISPO_CTRL_OUTPUT_WIDTH_8BIT  (0UL)


#define DISP_MISC_ISPO_CTRL_SHIFT_8BIT  (8UL)


#define DISP_MISC_ISPO_CTRL_OUTPUT_WIDTH_16BIT  (1UL)


#define DISP_MISC_ISPO_CTRL_SHIFT_0BIT  (0UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_444P  (4UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_420P  (6UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_IL  (0UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_420H  (7UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_YUYV422  (8UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_YVYU422  (9UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_UYVY422  (10UL)


#define DISP_MISC_ISPO_CTRL_DATA_FORMAT_VYUY422  (11UL)


#define DISP_MISC_TOP_C_ARCACHE_3       (0x00000003UL)


#define DISP_MISC_TOP_C_AWCACHE_3       (0x00000003UL)


#define DISP_MISC_LVDS_FRAMER_LVDS_MODE_18BIT_MASK  (0UL)


#define DISP_MISC_DISP_LVDS_FRAMER_MODE_18BIT_SHIFT  (0UL)


#define DISP_MISC_LVDS_FRAMER_LVDS_MAPSEL_24_1  (1UL)


#define DISP_MISC_LVDS_FRAMER_LVDS_MAPSEL_24_0  (0UL)


#define DISP_MISC_LVDS_FRAMER_MASK_SYNC_MASK  (0x00000100UL)


#define DISP_MISC_LVDS_FRAMER_DE_SHIFT  (6UL)


#define DISP_MISC_LVDS_FRAMER_DE_MASK   (0x000000C0UL)


#define DISP_MISC_LVDS_FRAMER_PIX_REQ_NO_3  (3UL)


#define DISP_MISC_LVDS_FRAMER_PIX_REQ_NO_SHIFT  (2UL)


#define DISP_MISC_LVDS_FRAMER_PIX_REQ_NO_MASK  (0x0000001cUL)


#define DISP_MISC_LVDS_FRAMER_PIX_CLK_EN_MASK  (0x00000020UL)


#define DISP_MISC_BE_MISC_CTRL_BT656_O_DATA_SEL_1X  (1UL  << DISP_MISC_BMC_BT656_OUTPUT_DATA_SEL_SHIFT)


#define DISP_MISC_ISPYI_CTRL_CS_FORMAT_444  (1UL)


#define DISP_MISC_ISPYI_CTRL_CS_FORMAT_422  (2UL)


#define DISP_MISC_ISPYI_CTRL_CS_FORMAT_420  (3UL)


#define DISP_MISC_ISPYI_CTRL_BYTES_SAMPLE_16_BIT  (0x00000001UL)


#define DISP_MISC_ISPYI_CTRL_DATA_FORMAT_PLANAR  (0x0UL)


#define DISP_MISC_ISPYI_CTRL_CC_ORDER_RGB_YUV  (0x0UL)


#define DISP_MISC_ISPYI_CTRL_MAX_BURST_LEN_16  (0xFUL)


#define DISP_MISC_ISPYI_CTRL_MAX_BURST_LEN_8  (0x7UL)

#endif /* DISP_MISC_RDB_H */
