/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file dsi_rdb.h
    @brief RDB File for DSI

    @version 2018May25_rdb
*/

#ifndef DSI_RDB_H
#define DSI_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t DSI_CTRL_TYPE;
#define DSI_CTRL_TE_LEVEL_EN_MASK (0x180000UL)
#define DSI_CTRL_TE_LEVEL_EN_SHIFT (19UL)
#define DSI_CTRL_ESC_CLK_EN_MASK (0x40000UL)
#define DSI_CTRL_ESC_CLK_EN_SHIFT (18UL)
#define DSI_CTRL_TE_TRIGC_MASK (0x30000UL)
#define DSI_CTRL_TE_TRIGC_SHIFT (16UL)
#define DSI_CTRL_HS_CLKC_MASK (0xc000UL)
#define DSI_CTRL_HS_CLKC_SHIFT (14UL)
#define DSI_CTRL_RX_LPDT_EOT_EN_MASK (0x2000UL)
#define DSI_CTRL_RX_LPDT_EOT_EN_SHIFT (13UL)
#define DSI_CTRL_LPDT_EOT_EN_MASK (0x1000UL)
#define DSI_CTRL_LPDT_EOT_EN_SHIFT (12UL)
#define DSI_CTRL_HSDT_EOT_EN_MASK (0x800UL)
#define DSI_CTRL_HSDT_EOT_EN_SHIFT (11UL)
#define DSI_CTRL_SOFT_RESET_CFG_MASK (0x400UL)
#define DSI_CTRL_SOFT_RESET_CFG_SHIFT (10UL)
#define DSI_CTRL_CAL_BYTE_EN_MASK (0x200UL)
#define DSI_CTRL_CAL_BYTE_EN_SHIFT (9UL)
#define DSI_CTRL_INV_BYTE_EN_MASK (0x100UL)
#define DSI_CTRL_INV_BYTE_EN_SHIFT (8UL)
#define DSI_CTRL_CLR_LDF_MASK (0x80UL)
#define DSI_CTRL_CLR_LDF_SHIFT (7UL)
#define DSI_CTRL_CLR_RXF_MASK (0x40UL)
#define DSI_CTRL_CLR_RXF_SHIFT (6UL)
#define DSI_CTRL_CLR_PDF_MASK (0x20UL)
#define DSI_CTRL_CLR_PDF_SHIFT (5UL)
#define DSI_CTRL_CLR_CDF_MASK (0x10UL)
#define DSI_CTRL_CLR_CDF_SHIFT (4UL)
#define DSI_CTRL_DIS_DISP_CRCC_MASK (0x4UL)
#define DSI_CTRL_DIS_DISP_CRCC_SHIFT (2UL)
#define DSI_CTRL_DIS_DISP_ECCC_MASK (0x2UL)
#define DSI_CTRL_DIS_DISP_ECCC_SHIFT (1UL)
#define DSI_CTRL_DSI1_EN_MASK (0x1UL)
#define DSI_CTRL_DSI1_EN_SHIFT (0UL)




typedef uint32_t DSI_TXPKT1_C_TYPE;
#define DSI_TXPKT1_C_TRIG_CMD_MASK (0xff000000UL)
#define DSI_TXPKT1_C_TRIG_CMD_SHIFT (24UL)
#define DSI_TXPKT1_C_CMD_REPEAT_MASK (0xfffc00UL)
#define DSI_TXPKT1_C_CMD_REPEAT_SHIFT (10UL)
#define DSI_TXPKT1_C_DISPLAY_NO_MASK (0x300UL)
#define DSI_TXPKT1_C_DISPLAY_NO_SHIFT (8UL)
#define DSI_TXPKT1_C_CMD_TX_TIME_MASK (0xc0UL)
#define DSI_TXPKT1_C_CMD_TX_TIME_SHIFT (6UL)
#define DSI_TXPKT1_C_CMD_CTRL_MASK (0x30UL)
#define DSI_TXPKT1_C_CMD_CTRL_SHIFT (4UL)
#define DSI_TXPKT1_C_CMD_MODE_MASK (0x8UL)
#define DSI_TXPKT1_C_CMD_MODE_SHIFT (3UL)
#define DSI_TXPKT1_C_CMD_TYPE_MASK (0x4UL)
#define DSI_TXPKT1_C_CMD_TYPE_SHIFT (2UL)
#define DSI_TXPKT1_C_CMD_TE_EN_MASK (0x2UL)
#define DSI_TXPKT1_C_CMD_TE_EN_SHIFT (1UL)
#define DSI_TXPKT1_C_CMD_EN_MASK (0x1UL)
#define DSI_TXPKT1_C_CMD_EN_SHIFT (0UL)




typedef uint32_t DSI_TXPKT1_H_TYPE;
#define DSI_TXPKT1_H_BC_CMDFIFO_MASK (0xff000000UL)
#define DSI_TXPKT1_H_BC_CMDFIFO_SHIFT (24UL)
#define DSI_TXPKT1_H_BC_PARAM_MASK (0xffff00UL)
#define DSI_TXPKT1_H_BC_PARAM_SHIFT (8UL)
#define DSI_TXPKT1_H_DT_MASK (0xffUL)
#define DSI_TXPKT1_H_DT_SHIFT (0UL)




typedef uint32_t DSI_TXPKT2_C_TYPE;
#define DSI_TXPKT2_C_TRIG_CMD_MASK (0xff000000UL)
#define DSI_TXPKT2_C_TRIG_CMD_SHIFT (24UL)
#define DSI_TXPKT2_C_CMD_REPEAT_MASK (0xfffc00UL)
#define DSI_TXPKT2_C_CMD_REPEAT_SHIFT (10UL)
#define DSI_TXPKT2_C_DISPLAY_NO_MASK (0x300UL)
#define DSI_TXPKT2_C_DISPLAY_NO_SHIFT (8UL)
#define DSI_TXPKT2_C_CMD_TX_TIME_MASK (0xc0UL)
#define DSI_TXPKT2_C_CMD_TX_TIME_SHIFT (6UL)
#define DSI_TXPKT2_C_CMD_CTRL_MASK (0x30UL)
#define DSI_TXPKT2_C_CMD_CTRL_SHIFT (4UL)
#define DSI_TXPKT2_C_CMD_MODE_MASK (0x8UL)
#define DSI_TXPKT2_C_CMD_MODE_SHIFT (3UL)
#define DSI_TXPKT2_C_CMD_TYPE_MASK (0x4UL)
#define DSI_TXPKT2_C_CMD_TYPE_SHIFT (2UL)
#define DSI_TXPKT2_C_CMD_TE_EN_MASK (0x2UL)
#define DSI_TXPKT2_C_CMD_TE_EN_SHIFT (1UL)
#define DSI_TXPKT2_C_CMD_EN_MASK (0x1UL)
#define DSI_TXPKT2_C_CMD_EN_SHIFT (0UL)




typedef uint32_t DSI_TXPKT2_H_TYPE;
#define DSI_TXPKT2_H_BC_CMDFIFO_MASK (0xff000000UL)
#define DSI_TXPKT2_H_BC_CMDFIFO_SHIFT (24UL)
#define DSI_TXPKT2_H_BC_PARAM_MASK (0xffff00UL)
#define DSI_TXPKT2_H_BC_PARAM_SHIFT (8UL)
#define DSI_TXPKT2_H_DT_MASK (0xffUL)
#define DSI_TXPKT2_H_DT_SHIFT (0UL)




typedef uint32_t DSI_RXPKT1_H_TYPE;
#define DSI_RXPKT1_H_CRC_ERR_MASK (0x80000000UL)
#define DSI_RXPKT1_H_CRC_ERR_SHIFT (31UL)
#define DSI_RXPKT1_H_DET_ERR_MASK (0x40000000UL)
#define DSI_RXPKT1_H_DET_ERR_SHIFT (30UL)
#define DSI_RXPKT1_H_ECC_ERR_MASK (0x20000000UL)
#define DSI_RXPKT1_H_ECC_ERR_SHIFT (29UL)
#define DSI_RXPKT1_H_COR_ERR_MASK (0x10000000UL)
#define DSI_RXPKT1_H_COR_ERR_SHIFT (28UL)
#define DSI_RXPKT1_H_INCOMP_PKT_MASK (0x2000000UL)
#define DSI_RXPKT1_H_INCOMP_PKT_SHIFT (25UL)
#define DSI_RXPKT1_H_PKT_TYPE_MASK (0x1000000UL)
#define DSI_RXPKT1_H_PKT_TYPE_SHIFT (24UL)
#define DSI_RXPKT1_H_BC_PARAM_MASK (0xffff00UL)
#define DSI_RXPKT1_H_BC_PARAM_SHIFT (8UL)
#define DSI_RXPKT1_H_DT_LP_CMD_MASK (0xffUL)
#define DSI_RXPKT1_H_DT_LP_CMD_SHIFT (0UL)




typedef uint32_t DSI_RXPKT2_H_TYPE;
#define DSI_RXPKT2_H_DET_ERR_MASK (0x40000000UL)
#define DSI_RXPKT2_H_DET_ERR_SHIFT (30UL)
#define DSI_RXPKT2_H_ECC_ERR_MASK (0x20000000UL)
#define DSI_RXPKT2_H_ECC_ERR_SHIFT (29UL)
#define DSI_RXPKT2_H_COR_ERR_MASK (0x10000000UL)
#define DSI_RXPKT2_H_COR_ERR_SHIFT (28UL)
#define DSI_RXPKT2_H_INCOMP_PKT_MASK (0x2000000UL)
#define DSI_RXPKT2_H_INCOMP_PKT_SHIFT (25UL)
#define DSI_RXPKT2_H_PARAM_MASK (0xffff00UL)
#define DSI_RXPKT2_H_PARAM_SHIFT (8UL)
#define DSI_RXPKT2_H_DT_MASK (0xffUL)
#define DSI_RXPKT2_H_DT_SHIFT (0UL)




typedef uint32_t DSI_TXPKT_CMD_FIFO_TYPE;
#define DSI_TXPKT_CMD_FIFO_DATA_MASK (0xffUL)
#define DSI_TXPKT_CMD_FIFO_DATA_SHIFT (0UL)




typedef uint32_t DSI_TXPKT_PIXD_FIFO_TYPE;
#define DSI_TXPKT_PIXD_FIFO_WORD_MASK (0xffffffffUL)
#define DSI_TXPKT_PIXD_FIFO_WORD_SHIFT (0UL)




typedef uint32_t DSI_RXPKT_FIFO_TYPE;
#define DSI_RXPKT_FIFO_RX_DATA_MASK (0xffUL)
#define DSI_RXPKT_FIFO_RX_DATA_SHIFT (0UL)




typedef uint32_t DSI_DISP0_CTRL_TYPE;
#define DSI_DISP0_CTRL_PFORMAT_EXTRA_MASK (0x30000000UL)
#define DSI_DISP0_CTRL_PFORMAT_EXTRA_SHIFT (28UL)
#define DSI_DISP0_CTRL_DLANE_HSENT_MARGIN_MASK (0xf800000UL)
#define DSI_DISP0_CTRL_DLANE_HSENT_MARGIN_SHIFT (23UL)
#define DSI_DISP0_CTRL_VID_ST_VACTO_MASK (0x400000UL)
#define DSI_DISP0_CTRL_VID_ST_VACTO_SHIFT (22UL)
#define DSI_DISP0_CTRL_PIX_CLK_DIV_MASK (0x3fe000UL)
#define DSI_DISP0_CTRL_PIX_CLK_DIV_SHIFT (13UL)
#define DSI_DISP0_CTRL_LP_STOP_CTRL_MASK (0x1800UL)
#define DSI_DISP0_CTRL_LP_STOP_CTRL_SHIFT (11UL)
#define DSI_DISP0_CTRL_HACTIVE_NULL_MASK (0x400UL)
#define DSI_DISP0_CTRL_HACTIVE_NULL_SHIFT (10UL)
#define DSI_DISP0_CTRL_VBLP_CTRL_MASK (0x200UL)
#define DSI_DISP0_CTRL_VBLP_CTRL_SHIFT (9UL)
#define DSI_DISP0_CTRL_HFP_CTRL_MASK (0x100UL)
#define DSI_DISP0_CTRL_HFP_CTRL_SHIFT (8UL)
#define DSI_DISP0_CTRL_HBP_CTRL_MASK (0x80UL)
#define DSI_DISP0_CTRL_HBP_CTRL_SHIFT (7UL)
#define DSI_DISP0_CTRL_VC_MASK (0x60UL)
#define DSI_DISP0_CTRL_VC_SHIFT (5UL)
#define DSI_DISP0_CTRL_ST_END_MASK (0x10UL)
#define DSI_DISP0_CTRL_ST_END_SHIFT (4UL)
#define DSI_DISP0_CTRL_PFORMAT_MASK (0xcUL)
#define DSI_DISP0_CTRL_PFORMAT_SHIFT (2UL)
#define DSI_DISP0_CTRL_MODE_MASK (0x2UL)
#define DSI_DISP0_CTRL_MODE_SHIFT (1UL)
#define DSI_DISP0_CTRL_EN_MASK (0x1UL)
#define DSI_DISP0_CTRL_EN_SHIFT (0UL)




typedef uint32_t DSI_DISP1_CTRL_TYPE;
#define DSI_DISP1_CTRL_DMA_THRESH_MASK (0x1ff0UL)
#define DSI_DISP1_CTRL_DMA_THRESH_SHIFT (4UL)
#define DSI_DISP1_CTRL_PFORMAT_MASK (0x6UL)
#define DSI_DISP1_CTRL_PFORMAT_SHIFT (1UL)
#define DSI_DISP1_CTRL_EN_MASK (0x1UL)
#define DSI_DISP1_CTRL_EN_SHIFT (0UL)




typedef uint32_t DSI_INT_STAT_TYPE;
#define DSI_INT_STAT_TEST_MASK (0x80000000UL)
#define DSI_INT_STAT_TEST_SHIFT (31UL)
#define DSI_INT_STAT_PHY_D3_ULPS_MASK (0x40000000UL)
#define DSI_INT_STAT_PHY_D3_ULPS_SHIFT (30UL)
#define DSI_INT_STAT_PHY_D3_STOP_MASK (0x20000000UL)
#define DSI_INT_STAT_PHY_D3_STOP_SHIFT (29UL)
#define DSI_INT_STAT_PHY_D2_ULPS_MASK (0x10000000UL)
#define DSI_INT_STAT_PHY_D2_ULPS_SHIFT (28UL)
#define DSI_INT_STAT_PHY_D2_STOP_MASK (0x8000000UL)
#define DSI_INT_STAT_PHY_D2_STOP_SHIFT (27UL)
#define DSI_INT_STAT_PHY_D1_ULPS_MASK (0x4000000UL)
#define DSI_INT_STAT_PHY_D1_ULPS_SHIFT (26UL)
#define DSI_INT_STAT_PHY_D1_STOP_MASK (0x2000000UL)
#define DSI_INT_STAT_PHY_D1_STOP_SHIFT (25UL)
#define DSI_INT_STAT_PHY_D0_ULPS_MASK (0x1000000UL)
#define DSI_INT_STAT_PHY_D0_ULPS_SHIFT (24UL)
#define DSI_INT_STAT_PHY_D0_STOP_MASK (0x800000UL)
#define DSI_INT_STAT_PHY_D0_STOP_SHIFT (23UL)
#define DSI_INT_STAT_FIFO_ERR_MASK (0x400000UL)
#define DSI_INT_STAT_FIFO_ERR_SHIFT (22UL)
#define DSI_INT_STAT_PHY_DIR_RTF_MASK (0x200000UL)
#define DSI_INT_STAT_PHY_DIR_RTF_SHIFT (21UL)
#define DSI_INT_STAT_PHY_RXLPDT_MASK (0x100000UL)
#define DSI_INT_STAT_PHY_RXLPDT_SHIFT (20UL)
#define DSI_INT_STAT_PHY_RXTRIG_MASK (0x80000UL)
#define DSI_INT_STAT_PHY_RXTRIG_SHIFT (19UL)
#define DSI_INT_STAT_PHY_D0_LPDT_MASK (0x40000UL)
#define DSI_INT_STAT_PHY_D0_LPDT_SHIFT (18UL)
#define DSI_INT_STAT_PHY_DIR_FTR_MASK (0x20000UL)
#define DSI_INT_STAT_PHY_DIR_FTR_SHIFT (17UL)
#define DSI_INT_STAT_PHY_CLK_ULPS_MASK (0x10000UL)
#define DSI_INT_STAT_PHY_CLK_ULPS_SHIFT (16UL)
#define DSI_INT_STAT_PHY_CLK_HS_MASK (0x8000UL)
#define DSI_INT_STAT_PHY_CLK_HS_SHIFT (15UL)
#define DSI_INT_STAT_PHY_CLK_STOP_MASK (0x4000UL)
#define DSI_INT_STAT_PHY_CLK_STOP_SHIFT (14UL)
#define DSI_INT_STAT_PR_TO_MASK (0x2000UL)
#define DSI_INT_STAT_PR_TO_SHIFT (13UL)
#define DSI_INT_STAT_TA_TO_MASK (0x1000UL)
#define DSI_INT_STAT_TA_TO_SHIFT (12UL)
#define DSI_INT_STAT_LPRX_TO_MASK (0x800UL)
#define DSI_INT_STAT_LPRX_TO_SHIFT (11UL)
#define DSI_INT_STAT_HSTX_TO_MASK (0x400UL)
#define DSI_INT_STAT_HSTX_TO_SHIFT (10UL)
#define DSI_INT_STAT_ERRCONTLP1_MASK (0x200UL)
#define DSI_INT_STAT_ERRCONTLP1_SHIFT (9UL)
#define DSI_INT_STAT_ERRCONTLP0_MASK (0x100UL)
#define DSI_INT_STAT_ERRCONTLP0_SHIFT (8UL)
#define DSI_INT_STAT_ERRCONTROL_MASK (0x80UL)
#define DSI_INT_STAT_ERRCONTROL_SHIFT (7UL)
#define DSI_INT_STAT_ERRSYNCESC_MASK (0x40UL)
#define DSI_INT_STAT_ERRSYNCESC_SHIFT (6UL)
#define DSI_INT_STAT_RX2_PKT_MASK (0x20UL)
#define DSI_INT_STAT_RX2_PKT_SHIFT (5UL)
#define DSI_INT_STAT_RX1_PKT_MASK (0x10UL)
#define DSI_INT_STAT_RX1_PKT_SHIFT (4UL)
#define DSI_INT_STAT_TXPKT2_DONE_MASK (0x8UL)
#define DSI_INT_STAT_TXPKT2_DONE_SHIFT (3UL)
#define DSI_INT_STAT_TXPKT2_END_MASK (0x4UL)
#define DSI_INT_STAT_TXPKT2_END_SHIFT (2UL)
#define DSI_INT_STAT_TXPKT1_DONE_MASK (0x2UL)
#define DSI_INT_STAT_TXPKT1_DONE_SHIFT (1UL)
#define DSI_INT_STAT_TXPKT1_END_MASK (0x1UL)
#define DSI_INT_STAT_TXPKT1_END_SHIFT (0UL)




typedef uint32_t DSI_INT_EN_TYPE;
#define DSI_INT_EN_TEST_MASK (0x80000000UL)
#define DSI_INT_EN_TEST_SHIFT (31UL)
#define DSI_INT_EN_PHY_D3_ULPS_MASK (0x40000000UL)
#define DSI_INT_EN_PHY_D3_ULPS_SHIFT (30UL)
#define DSI_INT_EN_PHY_D3_STOP_MASK (0x20000000UL)
#define DSI_INT_EN_PHY_D3_STOP_SHIFT (29UL)
#define DSI_INT_EN_PHY_D2_ULPS_MASK (0x10000000UL)
#define DSI_INT_EN_PHY_D2_ULPS_SHIFT (28UL)
#define DSI_INT_EN_PHY_D2_STOP_MASK (0x8000000UL)
#define DSI_INT_EN_PHY_D2_STOP_SHIFT (27UL)
#define DSI_INT_EN_PHY_D1_ULPS_MASK (0x4000000UL)
#define DSI_INT_EN_PHY_D1_ULPS_SHIFT (26UL)
#define DSI_INT_EN_PHY_D1_STOP_MASK (0x2000000UL)
#define DSI_INT_EN_PHY_D1_STOP_SHIFT (25UL)
#define DSI_INT_EN_PHY_D0_ULPS_MASK (0x1000000UL)
#define DSI_INT_EN_PHY_D0_ULPS_SHIFT (24UL)
#define DSI_INT_EN_PHY_D0_STOP_MASK (0x800000UL)
#define DSI_INT_EN_PHY_D0_STOP_SHIFT (23UL)
#define DSI_INT_EN_FIFO_ERR_MASK (0x400000UL)
#define DSI_INT_EN_FIFO_ERR_SHIFT (22UL)
#define DSI_INT_EN_PHY_DIR_RTF_MASK (0x200000UL)
#define DSI_INT_EN_PHY_DIR_RTF_SHIFT (21UL)
#define DSI_INT_EN_PHY_RXLPDT_MASK (0x100000UL)
#define DSI_INT_EN_PHY_RXLPDT_SHIFT (20UL)
#define DSI_INT_EN_PHY_RXTRIG_MASK (0x80000UL)
#define DSI_INT_EN_PHY_RXTRIG_SHIFT (19UL)
#define DSI_INT_EN_PHY_D0_LPDT_MASK (0x40000UL)
#define DSI_INT_EN_PHY_D0_LPDT_SHIFT (18UL)
#define DSI_INT_EN_PHY_DIR_FTR_MASK (0x20000UL)
#define DSI_INT_EN_PHY_DIR_FTR_SHIFT (17UL)
#define DSI_INT_EN_PHY_CLK_ULPS_MASK (0x10000UL)
#define DSI_INT_EN_PHY_CLK_ULPS_SHIFT (16UL)
#define DSI_INT_EN_PHY_CLK_HS_MASK (0x8000UL)
#define DSI_INT_EN_PHY_CLK_HS_SHIFT (15UL)
#define DSI_INT_EN_PHY_CLK_STOP_MASK (0x4000UL)
#define DSI_INT_EN_PHY_CLK_STOP_SHIFT (14UL)
#define DSI_INT_EN_PR_TO_MASK (0x2000UL)
#define DSI_INT_EN_PR_TO_SHIFT (13UL)
#define DSI_INT_EN_TA_TO_MASK (0x1000UL)
#define DSI_INT_EN_TA_TO_SHIFT (12UL)
#define DSI_INT_EN_LRX_H_TO_MASK (0x800UL)
#define DSI_INT_EN_LRX_H_TO_SHIFT (11UL)
#define DSI_INT_EN_HTX_TO_MASK (0x400UL)
#define DSI_INT_EN_HTX_TO_SHIFT (10UL)
#define DSI_INT_EN_ERRCONTLP1_MASK (0x200UL)
#define DSI_INT_EN_ERRCONTLP1_SHIFT (9UL)
#define DSI_INT_EN_ERRCONTLP0_MASK (0x100UL)
#define DSI_INT_EN_ERRCONTLP0_SHIFT (8UL)
#define DSI_INT_EN_ERRCONTROL_MASK (0x80UL)
#define DSI_INT_EN_ERRCONTROL_SHIFT (7UL)
#define DSI_INT_EN_ERRSYNCESC_MASK (0x40UL)
#define DSI_INT_EN_ERRSYNCESC_SHIFT (6UL)
#define DSI_INT_EN_RX2_PKT_MASK (0x20UL)
#define DSI_INT_EN_RX2_PKT_SHIFT (5UL)
#define DSI_INT_EN_RX1_PKT_MASK (0x10UL)
#define DSI_INT_EN_RX1_PKT_SHIFT (4UL)
#define DSI_INT_EN_TXPKT3_DONE_MASK (0x8UL)
#define DSI_INT_EN_TXPKT3_DONE_SHIFT (3UL)
#define DSI_INT_EN_TXPKT2_END_MASK (0x4UL)
#define DSI_INT_EN_TXPKT2_END_SHIFT (2UL)
#define DSI_INT_EN_TXPKT1_DONE_MASK (0x2UL)
#define DSI_INT_EN_TXPKT1_DONE_SHIFT (1UL)
#define DSI_INT_EN_TXPKT1_END_MASK (0x1UL)
#define DSI_INT_EN_TXPKT1_END_SHIFT (0UL)




typedef uint32_t DSI_STAT_TYPE;
#define DSI_STAT_PHY_D3_ULPS_MASK (0x80000000UL)
#define DSI_STAT_PHY_D3_ULPS_SHIFT (31UL)
#define DSI_STAT_PHY_D3_STOP_MASK (0x40000000UL)
#define DSI_STAT_PHY_D3_STOP_SHIFT (30UL)
#define DSI_STAT_PHY_D2_ULPS_MASK (0x20000000UL)
#define DSI_STAT_PHY_D2_ULPS_SHIFT (29UL)
#define DSI_STAT_PHY_D2_STOP_MASK (0x10000000UL)
#define DSI_STAT_PHY_D2_STOP_SHIFT (28UL)
#define DSI_STAT_PHY_D1_ULPS_MASK (0x8000000UL)
#define DSI_STAT_PHY_D1_ULPS_SHIFT (27UL)
#define DSI_STAT_PHY_D1_STOP_MASK (0x4000000UL)
#define DSI_STAT_PHY_D1_STOP_SHIFT (26UL)
#define DSI_STAT_PHY_D0_ULPS_MASK (0x2000000UL)
#define DSI_STAT_PHY_D0_ULPS_SHIFT (25UL)
#define DSI_STAT_PHY_D0_STOP_MASK (0x1000000UL)
#define DSI_STAT_PHY_D0_STOP_SHIFT (24UL)
#define DSI_STAT_FIFO_ERR_MASK (0x800000UL)
#define DSI_STAT_FIFO_ERR_SHIFT (23UL)
#define DSI_STAT_PHY_RXLPDT_MASK (0x400000UL)
#define DSI_STAT_PHY_RXLPDT_SHIFT (22UL)
#define DSI_STAT_PHY_RXTRIG_MASK (0x200000UL)
#define DSI_STAT_PHY_RXTRIG_SHIFT (21UL)
#define DSI_STAT_PHY_D0_LPDT_MASK (0x100000UL)
#define DSI_STAT_PHY_D0_LPDT_SHIFT (20UL)
#define DSI_STAT_PHY_DIR_MASK (0x80000UL)
#define DSI_STAT_PHY_DIR_SHIFT (19UL)
#define DSI_STAT_PHY_CLK_ULPS_MASK (0x40000UL)
#define DSI_STAT_PHY_CLK_ULPS_SHIFT (18UL)
#define DSI_STAT_PHY_CLK_HS_MASK (0x20000UL)
#define DSI_STAT_PHY_CLK_HS_SHIFT (17UL)
#define DSI_STAT_PHY_CLK_STOP_MASK (0x10000UL)
#define DSI_STAT_PHY_CLK_STOP_SHIFT (16UL)
#define DSI_STAT_PR_TO_MASK (0x8000UL)
#define DSI_STAT_PR_TO_SHIFT (15UL)
#define DSI_STAT_TA_TO_MASK (0x4000UL)
#define DSI_STAT_TA_TO_SHIFT (14UL)
#define DSI_STAT_LPRX_TO_MASK (0x2000UL)
#define DSI_STAT_LPRX_TO_SHIFT (13UL)
#define DSI_STAT_HSTX_TO_MASK (0x1000UL)
#define DSI_STAT_HSTX_TO_SHIFT (12UL)
#define DSI_STAT_ERRCONTLP1_MASK (0x800UL)
#define DSI_STAT_ERRCONTLP1_SHIFT (11UL)
#define DSI_STAT_ERRCONTLP0_MASK (0x400UL)
#define DSI_STAT_ERRCONTLP0_SHIFT (10UL)
#define DSI_STAT_ERRCONTROL_MASK (0x200UL)
#define DSI_STAT_ERRCONTROL_SHIFT (9UL)
#define DSI_STAT_ERRSYNCESC_MASK (0x100UL)
#define DSI_STAT_ERRSYNCESC_SHIFT (8UL)
#define DSI_STAT_RX2_PKT_MASK (0x80UL)
#define DSI_STAT_RX2_PKT_SHIFT (7UL)
#define DSI_STAT_RX1_PKT_MASK (0x40UL)
#define DSI_STAT_RX1_PKT_SHIFT (6UL)
#define DSI_STAT_TXPKT2_BUSY_MASK (0x20UL)
#define DSI_STAT_TXPKT2_BUSY_SHIFT (5UL)
#define DSI_STAT_TXPKT2_DONE_MASK (0x10UL)
#define DSI_STAT_TXPKT2_DONE_SHIFT (4UL)
#define DSI_STAT_TXPKT2_END_MASK (0x8UL)
#define DSI_STAT_TXPKT2_END_SHIFT (3UL)
#define DSI_STAT_TXPKT1_BUSY_MASK (0x4UL)
#define DSI_STAT_TXPKT1_BUSY_SHIFT (2UL)
#define DSI_STAT_TXPKT1_DONE_MASK (0x2UL)
#define DSI_STAT_TXPKT1_DONE_SHIFT (1UL)
#define DSI_STAT_TXPKT1_END_MASK (0x1UL)
#define DSI_STAT_TXPKT1_END_SHIFT (0UL)




typedef uint32_t DSI_HSTX_TO_CNT_TYPE;
#define DSI_HSTX_TO_CNT_TO_MASK (0xffffffUL)
#define DSI_HSTX_TO_CNT_TO_SHIFT (0UL)




typedef uint32_t DSI_LPRX_TO_CNT_TYPE;
#define DSI_LPRX_TO_CNT_TO_MASK (0xffffffUL)
#define DSI_LPRX_TO_CNT_TO_SHIFT (0UL)




typedef uint32_t DSI_TA_TO_CNT_TYPE;
#define DSI_TA_TO_CNT_TO_MASK (0xffffffUL)
#define DSI_TA_TO_CNT_TO_SHIFT (0UL)




typedef uint32_t DSI_PR_TO_CNT_TYPE;
#define DSI_PR_TO_CNT_TO_MASK (0xffffffUL)
#define DSI_PR_TO_CNT_TO_SHIFT (0UL)




typedef uint32_t DSI_PHYC_TYPE;
#define DSI_PHYC_ESC_CLK_LPDT_MASK (0x3f00000UL)
#define DSI_PHYC_ESC_CLK_LPDT_SHIFT (20UL)
#define DSI_PHYC_TX_HSCLK_CONT_MASK (0x40000UL)
#define DSI_PHYC_TX_HSCLK_CONT_SHIFT (18UL)
#define DSI_PHYC_TXULPSCLK_MASK (0x20000UL)
#define DSI_PHYC_TXULPSCLK_SHIFT (17UL)
#define DSI_PHYC_PHY_CLANE_EN_MASK (0x10000UL)
#define DSI_PHYC_PHY_CLANE_EN_SHIFT (16UL)
#define DSI_PHYC_TXULPSESC_3_MASK (0x2000UL)
#define DSI_PHYC_TXULPSESC_3_SHIFT (13UL)
#define DSI_PHYC_PHY_DLANE3_EN_MASK (0x1000UL)
#define DSI_PHYC_PHY_DLANE3_EN_SHIFT (12UL)
#define DSI_PHYC_TXULPSESC_2_MASK (0x200UL)
#define DSI_PHYC_TXULPSESC_2_SHIFT (9UL)
#define DSI_PHYC_PHY_DLANE2_EN_MASK (0x100UL)
#define DSI_PHYC_PHY_DLANE2_EN_SHIFT (8UL)
#define DSI_PHYC_TXULPSESC_1_MASK (0x20UL)
#define DSI_PHYC_TXULPSESC_1_SHIFT (5UL)
#define DSI_PHYC_PHY_DLANE1_EN_MASK (0x10UL)
#define DSI_PHYC_PHY_DLANE1_EN_SHIFT (4UL)
#define DSI_PHYC_FORCE_TXSTOP_0_MASK (0x4UL)
#define DSI_PHYC_FORCE_TXSTOP_0_SHIFT (2UL)
#define DSI_PHYC_TXULPSESC_0_MASK (0x2UL)
#define DSI_PHYC_TXULPSESC_0_SHIFT (1UL)
#define DSI_PHYC_PHY_DLANE0_EN_MASK (0x1UL)
#define DSI_PHYC_PHY_DLANE0_EN_SHIFT (0UL)




typedef uint32_t DSI_HS_CLT0_TYPE;
#define DSI_HS_CLT0_CZERO_MASK (0x7fc0000UL)
#define DSI_HS_CLT0_CZERO_SHIFT (18UL)
#define DSI_HS_CLT0_CPRE_MASK (0x3fe00UL)
#define DSI_HS_CLT0_CPRE_SHIFT (9UL)
#define DSI_HS_CLT0_CPREP_MASK (0x1ffUL)
#define DSI_HS_CLT0_CPREP_SHIFT (0UL)




typedef uint32_t DSI_HS_CLT1_TYPE;
#define DSI_HS_CLT1_CTRAIL_MASK (0x3fe00UL)
#define DSI_HS_CLT1_CTRAIL_SHIFT (9UL)
#define DSI_HS_CLT1_CPOST_MASK (0x1ffUL)
#define DSI_HS_CLT1_CPOST_SHIFT (0UL)




typedef uint32_t DSI_HS_CLT2_TYPE;
#define DSI_HS_CLT2_WUP_MASK (0xffffffUL)
#define DSI_HS_CLT2_WUP_SHIFT (0UL)




typedef uint32_t DSI_HS_DLT3_TYPE;
#define DSI_HS_DLT3_EXIT_MASK (0x7fc0000UL)
#define DSI_HS_DLT3_EXIT_SHIFT (18UL)
#define DSI_HS_DLT3_ZERO_MASK (0x3fe00UL)
#define DSI_HS_DLT3_ZERO_SHIFT (9UL)
#define DSI_HS_DLT3_PRE_MASK (0x1ffUL)
#define DSI_HS_DLT3_PRE_SHIFT (0UL)




typedef uint32_t DSI_HS_DLT4_TYPE;
#define DSI_HS_DLT4_ANLAT_MASK (0x7c0000UL)
#define DSI_HS_DLT4_ANLAT_SHIFT (18UL)
#define DSI_HS_DLT4_TRAIL_MASK (0x3fe00UL)
#define DSI_HS_DLT4_TRAIL_SHIFT (9UL)
#define DSI_HS_DLT4_LPX_MASK (0x1ffUL)
#define DSI_HS_DLT4_LPX_SHIFT (0UL)




typedef uint32_t DSI_HS_DLT5_TYPE;
#define DSI_HS_DLT5_INIT_MASK (0xffffffUL)
#define DSI_HS_DLT5_INIT_SHIFT (0UL)




typedef uint32_t DSI_LP_DLT6_TYPE;
#define DSI_LP_DLT6_TA_GET_MASK (0xff000000UL)
#define DSI_LP_DLT6_TA_GET_SHIFT (24UL)
#define DSI_LP_DLT6_TA_SURE_MASK (0xff0000UL)
#define DSI_LP_DLT6_TA_SURE_SHIFT (16UL)
#define DSI_LP_DLT6_TA_GO_MASK (0xff00UL)
#define DSI_LP_DLT6_TA_GO_SHIFT (8UL)
#define DSI_LP_DLT6_LP_LPX_MASK (0xffUL)
#define DSI_LP_DLT6_LP_LPX_SHIFT (0UL)




typedef uint32_t DSI_LP_DLT7_TYPE;
#define DSI_LP_DLT7_WUP_MASK (0xffffffUL)
#define DSI_LP_DLT7_WUP_SHIFT (0UL)




typedef uint32_t DSI_PHY_AFEC0_TYPE;
#define DSI_PHY_AFEC0_DPHY_ACNTL_31_30_MASK (0xc0000000UL)
#define DSI_PHY_AFEC0_DPHY_ACNTL_31_30_SHIFT (30UL)
#define DSI_PHY_AFEC0_LPTX_SLEW_MASK (0x38000000UL)
#define DSI_PHY_AFEC0_LPTX_SLEW_SHIFT (27UL)
#define DSI_PHY_AFEC0_LOOPBACK_ENABLE_MASK (0x4000000UL)
#define DSI_PHY_AFEC0_LOOPBACK_ENABLE_SHIFT (26UL)
#define DSI_PHY_AFEC0_TEST_MODE_A_MASK (0x2000000UL)
#define DSI_PHY_AFEC0_TEST_MODE_A_SHIFT (25UL)
#define DSI_PHY_AFEC0_TEST_MODE_B_MASK (0x1000000UL)
#define DSI_PHY_AFEC0_TEST_MODE_B_SHIFT (24UL)
#define DSI_PHY_AFEC0_PULLDOWN_EN_MASK (0x800000UL)
#define DSI_PHY_AFEC0_PULLDOWN_EN_SHIFT (23UL)
#define DSI_PHY_AFEC0_TEST_MODE_C_MASK (0x400000UL)
#define DSI_PHY_AFEC0_TEST_MODE_C_SHIFT (22UL)
#define DSI_PHY_AFEC0_LANE_SKEW_CONTROL_MASK (0x3c0000UL)
#define DSI_PHY_AFEC0_LANE_SKEW_CONTROL_SHIFT (18UL)
#define DSI_PHY_AFEC0_SLEW_RATE_CONTROL_MASK (0x30000UL)
#define DSI_PHY_AFEC0_SLEW_RATE_CONTROL_SHIFT (16UL)
#define DSI_PHY_AFEC0_OUTPUT_SWING_CONTROL_MASK (0xc000UL)
#define DSI_PHY_AFEC0_OUTPUT_SWING_CONTROL_SHIFT (14UL)
#define DSI_PHY_AFEC0_RX_RESISTOR_CAL_MASK (0x3c00UL)
#define DSI_PHY_AFEC0_RX_RESISTOR_CAL_SHIFT (10UL)
#define DSI_PHY_AFEC0_PRE_EMPHASIS_CONTROL_MASK (0x3f0UL)
#define DSI_PHY_AFEC0_PRE_EMPHASIS_CONTROL_SHIFT (4UL)
#define DSI_PHY_AFEC0_TX_RESISTOR_CAL_MASK (0xfUL)
#define DSI_PHY_AFEC0_TX_RESISTOR_CAL_SHIFT (0UL)




typedef uint32_t DSI_PHY_AFEC1_TYPE;




typedef uint32_t DSI_TST_SEL_TYPE;
#define DSI_TST_SEL_SEL_MASK (0x1fUL)
#define DSI_TST_SEL_SEL_SHIFT (0UL)




typedef uint32_t DSI_TST_MON_TYPE;
#define DSI_TST_MON_MON_MASK (0xffffffffUL)
#define DSI_TST_MON_MON_SHIFT (0UL)




typedef uint32_t DSI_PHY_TST1_TYPE;
#define DSI_PHY_TST1_PHYC_TEST_HSRST_MASK (0x100000UL)
#define DSI_PHY_TST1_PHYC_TEST_HSRST_SHIFT (20UL)
#define DSI_PHY_TST1_PHYC_TEST_DM_MASK (0x80000UL)
#define DSI_PHY_TST1_PHYC_TEST_DM_SHIFT (19UL)
#define DSI_PHY_TST1_PHYC_TEST_DP_MASK (0x40000UL)
#define DSI_PHY_TST1_PHYC_TEST_DP_SHIFT (18UL)
#define DSI_PHY_TST1_PHYC_TEST_LP_MASK (0x20000UL)
#define DSI_PHY_TST1_PHYC_TEST_LP_SHIFT (17UL)
#define DSI_PHY_TST1_PHYC_TEST_EN_MASK (0x10000UL)
#define DSI_PHY_TST1_PHYC_TEST_EN_SHIFT (16UL)
#define DSI_PHY_TST1_PHYD3_TEST_DM_MASK (0x8000UL)
#define DSI_PHY_TST1_PHYD3_TEST_DM_SHIFT (15UL)
#define DSI_PHY_TST1_PHYD3_TEST_DP_MASK (0x4000UL)
#define DSI_PHY_TST1_PHYD3_TEST_DP_SHIFT (14UL)
#define DSI_PHY_TST1_PHYD3_TEST_LP_MASK (0x2000UL)
#define DSI_PHY_TST1_PHYD3_TEST_LP_SHIFT (13UL)
#define DSI_PHY_TST1_PHYD3_TEST_EN_MASK (0x1000UL)
#define DSI_PHY_TST1_PHYD3_TEST_EN_SHIFT (12UL)
#define DSI_PHY_TST1_PHYD2_TEST_DM_MASK (0x800UL)
#define DSI_PHY_TST1_PHYD2_TEST_DM_SHIFT (11UL)
#define DSI_PHY_TST1_PHYD2_TEST_DP_MASK (0x400UL)
#define DSI_PHY_TST1_PHYD2_TEST_DP_SHIFT (10UL)
#define DSI_PHY_TST1_PHYD2_TEST_LP_MASK (0x200UL)
#define DSI_PHY_TST1_PHYD2_TEST_LP_SHIFT (9UL)
#define DSI_PHY_TST1_PHYD2_TEST_EN_MASK (0x100UL)
#define DSI_PHY_TST1_PHYD2_TEST_EN_SHIFT (8UL)
#define DSI_PHY_TST1_PHYD1_TEST_DM_MASK (0x80UL)
#define DSI_PHY_TST1_PHYD1_TEST_DM_SHIFT (7UL)
#define DSI_PHY_TST1_PHYD1_TEST_DP_MASK (0x40UL)
#define DSI_PHY_TST1_PHYD1_TEST_DP_SHIFT (6UL)
#define DSI_PHY_TST1_PHYD1_TEST_LP_MASK (0x20UL)
#define DSI_PHY_TST1_PHYD1_TEST_LP_SHIFT (5UL)
#define DSI_PHY_TST1_PHYD1_TEST_EN_MASK (0x10UL)
#define DSI_PHY_TST1_PHYD1_TEST_EN_SHIFT (4UL)
#define DSI_PHY_TST1_PHYD0_TEST_DM_MASK (0x8UL)
#define DSI_PHY_TST1_PHYD0_TEST_DM_SHIFT (3UL)
#define DSI_PHY_TST1_PHYD0_TEST_DP_MASK (0x4UL)
#define DSI_PHY_TST1_PHYD0_TEST_DP_SHIFT (2UL)
#define DSI_PHY_TST1_PHYD0_TEST_LP_MASK (0x2UL)
#define DSI_PHY_TST1_PHYD0_TEST_LP_SHIFT (1UL)
#define DSI_PHY_TST1_PHYD0_TEST_EN_MASK (0x1UL)
#define DSI_PHY_TST1_PHYD0_TEST_EN_SHIFT (0UL)




typedef uint32_t DSI_PHY_TST2_TYPE;
#define DSI_PHY_TST2_PHYD3_HSDATA_MASK (0xff000000UL)
#define DSI_PHY_TST2_PHYD3_HSDATA_SHIFT (24UL)
#define DSI_PHY_TST2_PHYD2_HSDATA_MASK (0xff0000UL)
#define DSI_PHY_TST2_PHYD2_HSDATA_SHIFT (16UL)
#define DSI_PHY_TST2_PHYD1_HSDATA_MASK (0xff00UL)
#define DSI_PHY_TST2_PHYD1_HSDATA_SHIFT (8UL)
#define DSI_PHY_TST2_PHYD0_HSDATA_MASK (0xffUL)
#define DSI_PHY_TST2_PHYD0_HSDATA_SHIFT (0UL)




typedef uint32_t DSI_FIFO_STAT_TYPE;
#define DSI_FIFO_STAT_TXPKT_CMD_FULL_MASK (0x1UL)
#define DSI_FIFO_STAT_TXPKT_CMD_FULL_SHIFT (0UL)
#define DSI_FIFO_STAT_TXPKT_CMD_EMPTY_MASK (0x2UL)
#define DSI_FIFO_STAT_TXPKT_CMD_EMPTY_SHIFT (1UL)
#define DSI_FIFO_STAT_TXPKT_CMD_ERROR_MASK (0x4UL)
#define DSI_FIFO_STAT_TXPKT_CMD_ERROR_SHIFT (2UL)
#define DSI_FIFO_STAT_TXPKT_CMD_COUNT_MASK (0xf8UL)
#define DSI_FIFO_STAT_TXPKT_CMD_COUNT_SHIFT (3UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_FULL_MASK (0x10000UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_FULL_SHIFT (16UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_EMPTY_MASK (0x20000UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_EMPTY_SHIFT (17UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_ERROR_MASK (0x40000UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_ERROR_SHIFT (18UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_COUNT_MASK (0x1ff00000UL)
#define DSI_FIFO_STAT_TXPKT_PIXEL_COUNT_SHIFT (20UL)




typedef uint32_t DSI_ID_TYPE;
#define DSI_ID_DSI1_ID_MASK (0xffffffffUL)
#define DSI_ID_DSI1_ID_SHIFT (0UL)




typedef uint32_t DSI_DISP0_PL_VSS_TYPE;
#define DSI_DISP0_PL_VSS_VSS_MASK (0xffffUL)
#define DSI_DISP0_PL_VSS_VSS_SHIFT (0UL)




typedef uint32_t DSI_DISP0_PL_VSE_TYPE;
#define DSI_DISP0_PL_VSE_VSE_MASK (0xffffUL)
#define DSI_DISP0_PL_VSE_VSE_SHIFT (0UL)




typedef uint32_t DSI_DISP0_PL_HSS_TYPE;
#define DSI_DISP0_PL_HSS_HSS_MASK (0xffffUL)
#define DSI_DISP0_PL_HSS_HSS_SHIFT (0UL)




typedef uint32_t DSI_DISP0_PL_HSE_TYPE;
#define DSI_DISP0_PL_HSE_HSE_MASK (0xffffUL)
#define DSI_DISP0_PL_HSE_HSE_SHIFT (0UL)




typedef uint32_t DSI_DISP0_CTRL1_TYPE;
#define DSI_DISP0_CTRL1_CSI2_MODE_EN_MASK (0x80000000UL)
#define DSI_DISP0_CTRL1_CSI2_MODE_EN_SHIFT (31UL)
#define DSI_DISP0_CTRL1_DISP0_DATA_TYPE_OV_MASK (0x3f000000UL)
#define DSI_DISP0_CTRL1_DISP0_DATA_TYPE_OV_SHIFT (24UL)
#define DSI_DISP0_CTRL1_DISP0_DATA_TYPE_OV_EN_MASK (0x800000UL)
#define DSI_DISP0_CTRL1_DISP0_DATA_TYPE_OV_EN_SHIFT (23UL)
#define DSI_DISP0_CTRL1_DISP0_NBLP_MIN_WC_MASK (0x7c0000UL)
#define DSI_DISP0_CTRL1_DISP0_NBLP_MIN_WC_SHIFT (18UL)
#define DSI_DISP0_CTRL1_DISP0_HFP_MAN_NBLP_MASK (0x20000UL)
#define DSI_DISP0_CTRL1_DISP0_HFP_MAN_NBLP_SHIFT (17UL)
#define DSI_DISP0_CTRL1_DISP0_HFP_GAP_NBLP_MASK (0x10000UL)
#define DSI_DISP0_CTRL1_DISP0_HFP_GAP_NBLP_SHIFT (16UL)
#define DSI_DISP0_CTRL1_DISP0_HFP_GAP_EN_MASK (0x8000UL)
#define DSI_DISP0_CTRL1_DISP0_HFP_GAP_EN_SHIFT (15UL)
#define DSI_DISP0_CTRL1_DISP0_HACT_MAN_NBLP_MASK (0x4000UL)
#define DSI_DISP0_CTRL1_DISP0_HACT_MAN_NBLP_SHIFT (14UL)
#define DSI_DISP0_CTRL1_DISP0_HACT_GAP_NBLP_MASK (0x2000UL)
#define DSI_DISP0_CTRL1_DISP0_HACT_GAP_NBLP_SHIFT (13UL)
#define DSI_DISP0_CTRL1_DISP0_HACT_GAP_EN_MASK (0x1000UL)
#define DSI_DISP0_CTRL1_DISP0_HACT_GAP_EN_SHIFT (12UL)
#define DSI_DISP0_CTRL1_DISP0_HBP_MAN_NBLP_MASK (0x800UL)
#define DSI_DISP0_CTRL1_DISP0_HBP_MAN_NBLP_SHIFT (11UL)
#define DSI_DISP0_CTRL1_DISP0_HBP_GAP_NBLP_MASK (0x400UL)
#define DSI_DISP0_CTRL1_DISP0_HBP_GAP_NBLP_SHIFT (10UL)
#define DSI_DISP0_CTRL1_DISP0_HBP_GAP_EN_MASK (0x200UL)
#define DSI_DISP0_CTRL1_DISP0_HBP_GAP_EN_SHIFT (9UL)
#define DSI_DISP0_CTRL1_DISP0_HSA_MAN_NBLP_MASK (0x100UL)
#define DSI_DISP0_CTRL1_DISP0_HSA_MAN_NBLP_SHIFT (8UL)
#define DSI_DISP0_CTRL1_DISP0_VBLP_MAN_NBLP_MASK (0x80UL)
#define DSI_DISP0_CTRL1_DISP0_VBLP_MAN_NBLP_SHIFT (7UL)
#define DSI_DISP0_CTRL1_DISP0_VBLP_GAP_NBLP_MASK (0x40UL)
#define DSI_DISP0_CTRL1_DISP0_VBLP_GAP_NBLP_SHIFT (6UL)
#define DSI_DISP0_CTRL1_DISP0_VBLP_GAP_EN_MASK (0x20UL)
#define DSI_DISP0_CTRL1_DISP0_VBLP_GAP_EN_SHIFT (5UL)
#define DSI_DISP0_CTRL1_DISP0_VS_GAP_NBLP_MASK (0x10UL)
#define DSI_DISP0_CTRL1_DISP0_VS_GAP_NBLP_SHIFT (4UL)
#define DSI_DISP0_CTRL1_DISP0_VS_LL_GAP_EN_MASK (0x8UL)
#define DSI_DISP0_CTRL1_DISP0_VS_LL_GAP_EN_SHIFT (3UL)
#define DSI_DISP0_CTRL1_DISP0_VS_GAP_EN_MASK (0x4UL)
#define DSI_DISP0_CTRL1_DISP0_VS_GAP_EN_SHIFT (2UL)
#define DSI_DISP0_CTRL1_DISP0_CLANE_HS_EN_MASK (0x2UL)
#define DSI_DISP0_CTRL1_DISP0_CLANE_HS_EN_SHIFT (1UL)
#define DSI_DISP0_CTRL1_DISP0_CTRL1_EN_MASK (0x1UL)
#define DSI_DISP0_CTRL1_DISP0_CTRL1_EN_SHIFT (0UL)




typedef uint32_t DSI_TXPKT1_LP_TIME_TYPE;
#define DSI_TXPKT1_LP_TIME_TYPE_DSI1_TIME_MASK (0x7ffffffUL)
#define DSI_TXPKT1_LP_TIME_TYPE_DSI1_TIME_SHIFT (0UL)




typedef uint32_t DSI_TXPKT2_LP_TIME_TYPE;
#define DSI_TXPKT2_LP_TIME_TYPE_DSI1_TIME_MASK (0x7ffffffUL)
#define DSI_TXPKT2_LP_TIME_TYPE_DSI1_TIME_SHIFT (0UL)




typedef uint32_t DSI_DISP0_NBLP_DI_TYPE;
#define DSI_DISP0_NBLP_DI_NULL_DI_MASK (0xff00UL)
#define DSI_DISP0_NBLP_DI_NULL_DI_SHIFT (8UL)
#define DSI_DISP0_NBLP_DI_BLP_DI_MASK (0xffUL)
#define DSI_DISP0_NBLP_DI_BLP_DI_SHIFT (0UL)




typedef uint8_t DSI_RESERVED_TYPE;




typedef uint32_t DSI_REV_ID_TYPE;
#define DSI_REV_ID_CORE_ID_MASK (0xff0000UL)
#define DSI_REV_ID_CORE_ID_SHIFT (16UL)
#define DSI_REV_ID_REL_ID_MASK (0xff00UL)
#define DSI_REV_ID_REL_ID_SHIFT (8UL)
#define DSI_REV_ID_METAL_ID_MASK (0xffUL)
#define DSI_REV_ID_METAL_ID_SHIFT (0UL)




typedef volatile struct COMP_PACKED _DSI_RDBType {
    DSI_CTRL_TYPE ctrl; /* OFFSET: 0x0 */
    DSI_TXPKT1_C_TYPE txpkt1_c; /* OFFSET: 0x4 */
    DSI_TXPKT1_H_TYPE txpkt1_h; /* OFFSET: 0x8 */
    DSI_TXPKT2_C_TYPE txpkt2_c; /* OFFSET: 0xc */
    DSI_TXPKT2_H_TYPE txpkt2_h; /* OFFSET: 0x10 */
    DSI_RXPKT1_H_TYPE rxpkt1_h; /* OFFSET: 0x14 */
    DSI_RXPKT2_H_TYPE rxpkt2_h; /* OFFSET: 0x18 */
    DSI_TXPKT_CMD_FIFO_TYPE txpkt_cmd_fifo; /* OFFSET: 0x1c */
    DSI_TXPKT_PIXD_FIFO_TYPE txpkt_pixd_fifo; /* OFFSET: 0x20 */
    DSI_RXPKT_FIFO_TYPE rxpkt_fifo; /* OFFSET: 0x24 */
    DSI_DISP0_CTRL_TYPE disp0_ctrl; /* OFFSET: 0x28 */
    DSI_DISP1_CTRL_TYPE disp1_ctrl; /* OFFSET: 0x2c */
    DSI_INT_STAT_TYPE int_stat; /* OFFSET: 0x30 */
    DSI_INT_EN_TYPE int_en; /* OFFSET: 0x34 */
    DSI_STAT_TYPE stat; /* OFFSET: 0x38 */
    DSI_HSTX_TO_CNT_TYPE hstx_to_cnt; /* OFFSET: 0x3c */
    DSI_LPRX_TO_CNT_TYPE lprx_to_cnt; /* OFFSET: 0x40 */
    DSI_TA_TO_CNT_TYPE ta_to_cnt; /* OFFSET: 0x44 */
    DSI_PR_TO_CNT_TYPE pr_to_cnt; /* OFFSET: 0x48 */
    DSI_PHYC_TYPE phyc; /* OFFSET: 0x4c */
    DSI_HS_CLT0_TYPE hs_clt0; /* OFFSET: 0x50 */
    DSI_HS_CLT1_TYPE hs_clt1; /* OFFSET: 0x54 */
    DSI_HS_CLT2_TYPE hs_clt2; /* OFFSET: 0x58 */
    DSI_HS_DLT3_TYPE hs_dlt3; /* OFFSET: 0x5c */
    DSI_HS_DLT4_TYPE hs_dlt4; /* OFFSET: 0x60 */
    DSI_HS_DLT5_TYPE hs_dlt5; /* OFFSET: 0x64 */
    DSI_LP_DLT6_TYPE lp_dlt6; /* OFFSET: 0x68 */
    DSI_LP_DLT7_TYPE lp_dlt7; /* OFFSET: 0x6c */
    DSI_PHY_AFEC0_TYPE phy_afec0; /* OFFSET: 0x70 */
    DSI_PHY_AFEC1_TYPE phy_afec1; /* OFFSET: 0x74 */
    DSI_TST_SEL_TYPE tst_sel; /* OFFSET: 0x78 */
    DSI_TST_MON_TYPE tst_mon; /* OFFSET: 0x7c */
    DSI_PHY_TST1_TYPE phy_tst1; /* OFFSET: 0x80 */
    DSI_PHY_TST2_TYPE phy_tst2; /* OFFSET: 0x84 */
    DSI_FIFO_STAT_TYPE fifo_stat; /* OFFSET: 0x88 */
    DSI_ID_TYPE id; /* OFFSET: 0x8c */
    DSI_DISP0_PL_VSS_TYPE pl_vss; /* OFFSET: 0x90 */
    DSI_DISP0_PL_VSE_TYPE pl_vse; /* OFFSET: 0x94 */
    DSI_DISP0_PL_HSS_TYPE pl_hss; /* OFFSET: 0x98 */
    DSI_DISP0_PL_HSE_TYPE pl_hse; /* OFFSET: 0x9c */
    DSI_DISP0_CTRL1_TYPE disp0_ctrl1; /* OFFSET: 0xa0 */
    DSI_TXPKT1_LP_TIME_TYPE txpkt1_lp_time; /* OFFSET: 0xa4 */
    DSI_TXPKT2_LP_TIME_TYPE txpkt2_lp_time; /* OFFSET: 0xa8 */
    DSI_DISP0_NBLP_DI_TYPE disp0_nblp_di; /* OFFSET: 0xac */
    DSI_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0xb0 */
    DSI_REV_ID_TYPE rev_id; /* OFFSET: 0xb4 */
} DSI_RDBType;


#define DSI_BASE                        (0x400A6000UL)



#define DSI_MAX_HW_ID                   (1UL)


#define DSI_CTRL_HS_CLKC_BYTE           (0UL)


#define DSI_DISP0_CTRL_MODE_VID         (0UL)


#define DSI_DISP0_CTRL_PFORMAT_24       (3UL)


#define DSI_ESC_CLK_LPDT_VAL            (0x14UL)


#define DSI_PIX_CLK_DIV                 (0x08UL)

#endif /* DSI_RDB_H */
