/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file i2s_rdb.h
    @brief RDB File for I2S

    @version 2018May25_rdb
*/

#ifndef I2S_RDB_H
#define I2S_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t I2S_RESERVED_TYPE;




typedef uint32_t I2S_TXCTRLA_TYPE;
#define I2S_TXCTRLA_PLAYEN_TRIG_EN_MASK (0x8UL)
#define I2S_TXCTRLA_PLAYEN_TRIG_EN_SHIFT (3UL)
#define I2S_TXCTRLA_I2S_OFFSET_MASK (0x4UL)
#define I2S_TXCTRLA_I2S_OFFSET_SHIFT (2UL)
#define I2S_TXCTRLA_PLAYEN_MASK (0x2UL)
#define I2S_TXCTRLA_PLAYEN_SHIFT (1UL)
#define I2S_TXCTRLA_TXENABLE_MASK (0x1UL)
#define I2S_TXCTRLA_TXENABLE_SHIFT (0UL)




typedef uint32_t I2S_TXCTRLB_TYPE;
#define I2S_TXCTRLB_SLOT_CONFIG_MASK (0xffffUL)
#define I2S_TXCTRLB_SLOT_CONFIG_SHIFT (0UL)




typedef uint32_t I2S_TXCTRLC_TYPE;
#define I2S_TXCTRLC_LEFTRGHT_SWAP_MASK (0x2000000UL)
#define I2S_TXCTRLC_LEFTRGHT_SWAP_SHIFT (25UL)
#define I2S_TXCTRLC_TDM_MODE_MASK (0x1000000UL)
#define I2S_TXCTRLC_TDM_MODE_SHIFT (24UL)
#define I2S_TXCTRLC_SAMPLE_LENGTH_MASK (0x1f0000UL)
#define I2S_TXCTRLC_SAMPLE_LENGTH_SHIFT (16UL)
#define I2S_TXCTRLC_RIGHT_JUST_MASK (0x1f00UL)
#define I2S_TXCTRLC_RIGHT_JUST_SHIFT (8UL)
#define I2S_TXCTRLC_LEFT_JUST_MASK (0xf0UL)
#define I2S_TXCTRLC_LEFT_JUST_SHIFT (4UL)
#define I2S_TXCTRLC_SLOTS_PER_FRAME_MASK (0xfUL)
#define I2S_TXCTRLC_SLOTS_PER_FRAME_SHIFT (0UL)




typedef uint32_t I2S_TXCTRLD_TYPE;
#define I2S_TXCTRLD_FRAME_LENGTH_MASK (0x1ffUL)
#define I2S_TXCTRLD_FRAME_LENGTH_SHIFT (0UL)




typedef uint32_t I2S_RXCTRLA_TYPE;
#define I2S_RXCTRLA_SLOT_CONFIG_MASK (0xffff0000UL)
#define I2S_RXCTRLA_SLOT_CONFIG_SHIFT (16UL)
#define I2S_RXCTRLA_LOOPBACK_MASK (0x10UL)
#define I2S_RXCTRLA_LOOPBACK_SHIFT (4UL)
#define I2S_RXCTRLA_RECEN_TRIG_EN_MASK (0x8UL)
#define I2S_RXCTRLA_RECEN_TRIG_EN_SHIFT (3UL)
#define I2S_RXCTRLA_I2S_OFFSET_MASK (0x4UL)
#define I2S_RXCTRLA_I2S_OFFSET_SHIFT (2UL)
#define I2S_RXCTRLA_RECEN_MASK (0x2UL)
#define I2S_RXCTRLA_RECEN_SHIFT (1UL)




typedef uint32_t I2S_WSCTRL_TYPE;
#define I2S_WSCTRL_BCLK_DIV_SEL_MASK (0x3800UL)
#define I2S_WSCTRL_BCLK_DIV_SEL_SHIFT (11UL)
#define I2S_WSCTRL_MCLK_SELECT_MASK (0x400UL)
#define I2S_WSCTRL_MCLK_SELECT_SHIFT (10UL)
#define I2S_WSCTRL_BCLK_WS_MASTER_EN_MASK (0x200UL)
#define I2S_WSCTRL_BCLK_WS_MASTER_EN_SHIFT (9UL)
#define I2S_WSCTRL_BCLK_WS_EN_MASK (0x100UL)
#define I2S_WSCTRL_BCLK_WS_EN_SHIFT (8UL)
#define I2S_WSCTRL_WS_LENGTH_MASK (0xffUL)
#define I2S_WSCTRL_WS_LENGTH_SHIFT (0UL)




typedef uint32_t I2S_STATUS_TYPE;
#define I2S_STATUS_TXUNDERFLOW_MASK (0x200UL)
#define I2S_STATUS_TXUNDERFLOW_SHIFT (9UL)
#define I2S_STATUS_TXFULL_MASK (0x100UL)
#define I2S_STATUS_TXFULL_SHIFT (8UL)
#define I2S_STATUS_TXHALFEMPTY_MASK (0x80UL)
#define I2S_STATUS_TXHALFEMPTY_SHIFT (7UL)
#define I2S_STATUS_TXEMPTY_MASK (0x40UL)
#define I2S_STATUS_TXEMPTY_SHIFT (6UL)
#define I2S_STATUS_TXPLAYING_MASK (0x20UL)
#define I2S_STATUS_TXPLAYING_SHIFT (5UL)
#define I2S_STATUS_RXOVERFLOW_MASK (0x10UL)
#define I2S_STATUS_RXOVERFLOW_SHIFT (4UL)
#define I2S_STATUS_RXFULL_MASK (0x8UL)
#define I2S_STATUS_RXFULL_SHIFT (3UL)
#define I2S_STATUS_RXHALFFULL_MASK (0x4UL)
#define I2S_STATUS_RXHALFFULL_SHIFT (2UL)
#define I2S_STATUS_RXEMPTY_MASK (0x2UL)
#define I2S_STATUS_RXEMPTY_SHIFT (1UL)
#define I2S_STATUS_RXRECORDING_MASK (0x1UL)
#define I2S_STATUS_RXRECORDING_SHIFT (0UL)




typedef uint32_t I2S_INT_TYPE;
#define I2S_INT_TXUNDERFLOW_MASK (0x200UL)
#define I2S_INT_TXUNDERFLOW_SHIFT (9UL)
#define I2S_INT_TXFULL_MASK (0x100UL)
#define I2S_INT_TXFULL_SHIFT (8UL)
#define I2S_INT_TXHALFEMPTY_MASK (0x80UL)
#define I2S_INT_TXHALFEMPTY_SHIFT (7UL)
#define I2S_INT_TXEMPTY_MASK (0x40UL)
#define I2S_INT_TXEMPTY_SHIFT (6UL)
#define I2S_INT_RXOVERFLOW_MASK (0x10UL)
#define I2S_INT_RXOVERFLOW_SHIFT (4UL)
#define I2S_INT_RXFULL_MASK (0x8UL)
#define I2S_INT_RXFULL_SHIFT (3UL)
#define I2S_INT_RXHALFFULL_MASK (0x4UL)
#define I2S_INT_RXHALFFULL_SHIFT (2UL)
#define I2S_INT_RXEMPTY_MASK (0x2UL)
#define I2S_INT_RXEMPTY_SHIFT (1UL)




typedef uint32_t I2S_INTMASK_TYPE;
#define I2S_INTMASK_TXUNDERFLOWMASK_MASK (0x200UL)
#define I2S_INTMASK_TXUNDERFLOWMASK_SHIFT (9UL)
#define I2S_INTMASK_TXFULLMASK_MASK (0x100UL)
#define I2S_INTMASK_TXFULLMASK_SHIFT (8UL)
#define I2S_INTMASK_TXHALFEMPTYMASK_MASK (0x80UL)
#define I2S_INTMASK_TXHALFEMPTYMASK_SHIFT (7UL)
#define I2S_INTMASK_TXEMPTYMASK_MASK (0x40UL)
#define I2S_INTMASK_TXEMPTYMASK_SHIFT (6UL)
#define I2S_INTMASK_RXOVERFLOWMASK_MASK (0x10UL)
#define I2S_INTMASK_RXOVERFLOWMASK_SHIFT (4UL)
#define I2S_INTMASK_RXFULLMASK_MASK (0x8UL)
#define I2S_INTMASK_RXFULLMASK_SHIFT (3UL)
#define I2S_INTMASK_RXHALFFULLMASK_MASK (0x4UL)
#define I2S_INTMASK_RXHALFFULLMASK_SHIFT (2UL)
#define I2S_INTMASK_RXEMPTYMASK_MASK (0x2UL)
#define I2S_INTMASK_RXEMPTYMASK_SHIFT (1UL)




typedef uint32_t I2S_DATAREGISTER_TYPE;
#define I2S_DATAREGISTER_DATAREGITER_MASK (0xffffffffUL)
#define I2S_DATAREGISTER_DATAREGITER_SHIFT (0UL)




typedef uint32_t I2S_SPAREREGISTER_TYPE;
#define I2S_SPAREREGISTER_SPAREREG_MASK (0xffffffffUL)
#define I2S_SPAREREGISTER_SPAREREG_SHIFT (0UL)


typedef volatile struct COMP_PACKED _I2S_CHANNEL_TYPE {
    I2S_TXCTRLA_TYPE i2stxctrla_ch0; /* OFFSET: 0x120 */
    I2S_TXCTRLB_TYPE i2stxctrlb_ch0; /* OFFSET: 0x124 */
    I2S_TXCTRLC_TYPE i2stxctrlc_ch0; /* OFFSET: 0x128 */
    I2S_TXCTRLD_TYPE i2stxctrld_ch0; /* OFFSET: 0x12c */
    I2S_RXCTRLA_TYPE i2srxctrla_ch0; /* OFFSET: 0x130 */
    I2S_WSCTRL_TYPE i2swsctrl_ch0; /* OFFSET: 0x134 */
    I2S_STATUS_TYPE i2sstatus_ch0; /* OFFSET: 0x138 */
    I2S_INT_TYPE i2sint_ch0; /* OFFSET: 0x13c */
    I2S_INTMASK_TYPE i2sintmask_ch0; /* OFFSET: 0x140 */
    I2S_DATAREGISTER_TYPE dataregister_ch0; /* OFFSET: 0x144 */
    I2S_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x148 */
} I2S_CHANNEL_TYPE;



typedef volatile struct COMP_PACKED _I2S_RDBType {
    I2S_RESERVED_TYPE rsvd0[288]; /* OFFSET: 0x0 */
    I2S_CHANNEL_TYPE channel[3]; /* OFFSET: 0x120 */
    I2S_RESERVED_TYPE rsvd3[3408]; /* OFFSET: 0x1b0 */
    I2S_SPAREREGISTER_TYPE spareregister0; /* OFFSET: 0xf00 */
    I2S_SPAREREGISTER_TYPE spareregister1; /* OFFSET: 0xf04 */
    I2S_SPAREREGISTER_TYPE spareregister2; /* OFFSET: 0xf08 */
    I2S_SPAREREGISTER_TYPE spareregister3; /* OFFSET: 0xf0c */
} I2S_RDBType;


#define I2S_BASE                        (0x40022000UL)

#define I2S_CHANNEL_TYPE_OFFSET         (0x40022120UL)



#define I2S_MAX_HW_ID                   (1UL)


#define I2S_MAX_CHAN_CNT                (3UL)


#define I2S_INTMASK_TX_ALL_INT_MASK     (I2S_INTMASK_TXUNDERFLOWMASK_MASK | I2S_INTMASK_TXFULLMASK_MASK | I2S_INTMASK_TXHALFEMPTYMASK_MASK | I2S_INTMASK_TXEMPTYMASK_MASK)


#define I2S_INTMASK_RX_ALL_INT_MASK     (I2S_INTMASK_RXOVERFLOWMASK_MASK | I2S_INTMASK_RXFULLMASK_MASK | I2S_INTMASK_RXHALFFULLMASK_MASK | I2S_INTMASK_RXEMPTYMASK_MASK)


#define I2S_INTMASK_ALL_INT_MASK        (I2S_INTMASK_TX_ALL_INT_MASK | I2S_INTMASK_RX_ALL_INT_MASK)

#endif /* I2S_RDB_H */
