/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file isp_rdb.h
    @brief RDB File for ISP

    @version 2018May25_rdb
*/

#ifndef ISP_RDB_H
#define ISP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t ISP_CTRL_TYPE;
#define ISP_CTRL_DISABLE_256B_CROSS_LORES_MASK (0x10000000UL)
#define ISP_CTRL_DISABLE_256B_CROSS_LORES_SHIFT (28UL)
#define ISP_CTRL_DISABLE_256B_CROSS_HIRES_MASK (0x8000000UL)
#define ISP_CTRL_DISABLE_256B_CROSS_HIRES_SHIFT (27UL)
#define ISP_CTRL_DISABLE_256B_CROSS_INPF_MASK (0x4000000UL)
#define ISP_CTRL_DISABLE_256B_CROSS_INPF_SHIFT (26UL)
#define ISP_CTRL_STBY_OVERRIDE_MASK (0x2000000UL)
#define ISP_CTRL_STBY_OVERRIDE_SHIFT (25UL)
#define ISP_CTRL_HDR_OUT_LORES_MASK (0x1000000UL)
#define ISP_CTRL_HDR_OUT_LORES_SHIFT (24UL)
#define ISP_CTRL_HDR_STATS_MUX_SEL_MASK (0xe00000UL)
#define ISP_CTRL_HDR_STATS_MUX_SEL_SHIFT (21UL)
#define ISP_CTRL_FORCE_CLKEN_MASK (0x100000UL)
#define ISP_CTRL_FORCE_CLKEN_SHIFT (20UL)
#define ISP_CTRL_TRANSFER_MASK (0x10000UL)
#define ISP_CTRL_TRANSFER_SHIFT (16UL)
#define ISP_CTRL_RD_256B_CROSS_ERR_MASK (0x8000UL)
#define ISP_CTRL_RD_256B_CROSS_ERR_SHIFT (15UL)
#define ISP_CTRL_WR_256B_CROSS_ERR_MASK (0x4000UL)
#define ISP_CTRL_WR_256B_CROSS_ERR_SHIFT (14UL)
#define ISP_CTRL_NLINES_INT_LORES_IMASK_MASK (0x2000UL)
#define ISP_CTRL_NLINES_INT_LORES_IMASK_SHIFT (13UL)
#define ISP_CTRL_NLINES_INT_HIRES_IMASK_MASK (0x1000UL)
#define ISP_CTRL_NLINES_INT_HIRES_IMASK_SHIFT (12UL)
#define ISP_CTRL_STATS_IMASK_MASK (0x100UL)
#define ISP_CTRL_STATS_IMASK_SHIFT (8UL)
#define ISP_CTRL_SW_IMASK_MASK (0x40UL)
#define ISP_CTRL_SW_IMASK_SHIFT (6UL)
#define ISP_CTRL_EOD_IMASK_MASK (0x20UL)
#define ISP_CTRL_EOD_IMASK_SHIFT (5UL)
#define ISP_CTRL_EOT_IMASK_MASK (0x10UL)
#define ISP_CTRL_EOT_IMASK_SHIFT (4UL)
#define ISP_CTRL_ERROR_IMASK_MASK (0x8UL)
#define ISP_CTRL_ERROR_IMASK_SHIFT (3UL)
#define ISP_CTRL_CLR_STATS_MASK (0x4UL)
#define ISP_CTRL_CLR_STATS_SHIFT (2UL)
#define ISP_CTRL_FLUSH_MASK (0x2UL)
#define ISP_CTRL_FLUSH_SHIFT (1UL)
#define ISP_CTRL_ENABLE_MASK (0x1UL)
#define ISP_CTRL_ENABLE_SHIFT (0UL)




typedef uint32_t ISP_STATUS_TYPE;
#define ISP_STATUS_RD_256B_CROSS_ERR_MASK (0x8000UL)
#define ISP_STATUS_RD_256B_CROSS_ERR_SHIFT (15UL)
#define ISP_STATUS_WR_256B_CROSS_ERR_MASK (0x4000UL)
#define ISP_STATUS_WR_256B_CROSS_ERR_SHIFT (14UL)
#define ISP_STATUS_NLINES_INT_LORES_MASK (0x2000UL)
#define ISP_STATUS_NLINES_INT_LORES_SHIFT (13UL)
#define ISP_STATUS_NLINES_INT_HIRES_MASK (0x1000UL)
#define ISP_STATUS_NLINES_INT_HIRES_SHIFT (12UL)
#define ISP_STATUS_STATS_EXP_CAPT_MASK (0xe00UL)
#define ISP_STATUS_STATS_EXP_CAPT_SHIFT (9UL)
#define ISP_STATUS_STATS_INT_MASK (0x100UL)
#define ISP_STATUS_STATS_INT_SHIFT (8UL)
#define ISP_STATUS_SW_INT_MASK (0x40UL)
#define ISP_STATUS_SW_INT_SHIFT (6UL)
#define ISP_STATUS_EOD_INT_MASK (0x20UL)
#define ISP_STATUS_EOD_INT_SHIFT (5UL)
#define ISP_STATUS_EOT_INT_MASK (0x10UL)
#define ISP_STATUS_EOT_INT_SHIFT (4UL)
#define ISP_STATUS_ERROR_INT_MASK (0x8UL)
#define ISP_STATUS_ERROR_INT_SHIFT (3UL)
#define ISP_STATUS_STATE_MASK (0x3UL)
#define ISP_STATUS_STATE_SHIFT (0UL)




typedef uint32_t ISP_ID_TYPE;
#define ISP_ID_SIGNATURE_MASK (0xffff0000UL)
#define ISP_ID_SIGNATURE_SHIFT (16UL)
#define ISP_ID_VERSION_MASK (0xff00UL)
#define ISP_ID_VERSION_SHIFT (8UL)
#define ISP_ID_REVISION_MASK (0xffUL)
#define ISP_ID_REVISION_SHIFT (0UL)




typedef uint8_t ISP_RESERVED_TYPE;




typedef uint32_t ISP_TILE_CTRL_TYPE;
#define ISP_TILE_CTRL_COUNT_MASK (0xfffUL)
#define ISP_TILE_CTRL_COUNT_SHIFT (0UL)




typedef uint32_t ISP_TILE_STATUS_TYPE;
#define ISP_TILE_STATUS_INT_COUNT_MASK (0xfffUL)
#define ISP_TILE_STATUS_INT_COUNT_SHIFT (0UL)




typedef uint32_t ISP_TILE_ADDR_TYPE;
#define ISP_TILE_ADDR_ADDRESS_MASK (0xffffffe0UL)
#define ISP_TILE_ADDR_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LEGACY_CTRL_TYPE;
#define ISP_LEGACY_CTRL_STATS_LEGACY_FLUSH_BEHAV_ENABLE_MASK (0x10UL)
#define ISP_LEGACY_CTRL_STATS_LEGACY_FLUSH_BEHAV_ENABLE_SHIFT (4UL)
#define ISP_LEGACY_CTRL_STATS_HW_SYNC_TRIGGER_DISABLE_MASK (0x8UL)
#define ISP_LEGACY_CTRL_STATS_HW_SYNC_TRIGGER_DISABLE_SHIFT (3UL)
#define ISP_LEGACY_CTRL_FRAME_HW_SYNC_DISABLE_MASK (0x4UL)
#define ISP_LEGACY_CTRL_FRAME_HW_SYNC_DISABLE_SHIFT (2UL)
#define ISP_LEGACY_CTRL_LINE_HW_SYNC_DISABLE_MASK (0x2UL)
#define ISP_LEGACY_CTRL_LINE_HW_SYNC_DISABLE_SHIFT (1UL)
#define ISP_LEGACY_CTRL_NEW_PIPELINE_DISABLE_MASK (0x1UL)
#define ISP_LEGACY_CTRL_NEW_PIPELINE_DISABLE_SHIFT (0UL)




typedef uint32_t ISP_FR_SIZE_TYPE;
#define ISP_FR_SIZE_HEIGHT_MASK (0xffff0000UL)
#define ISP_FR_SIZE_HEIGHT_SHIFT (16UL)
#define ISP_FR_SIZE_ISPFR_WIDTH_MASK (0xffffUL)
#define ISP_FR_SIZE_ISPFR_WIDTH_SHIFT (0UL)




typedef uint32_t ISP_FR_CTRL_TYPE;
#define ISP_FR_CTRL_SW_IN_POS_MASK (0xf000UL)
#define ISP_FR_CTRL_SW_IN_POS_SHIFT (12UL)
#define ISP_FR_CTRL_SW_OUT_POS_MASK (0xf00UL)
#define ISP_FR_CTRL_SW_OUT_POS_SHIFT (8UL)
#define ISP_FR_CTRL_TRANSPOSED_MASK (0x4UL)
#define ISP_FR_CTRL_TRANSPOSED_SHIFT (2UL)




typedef uint32_t ISP_FR_BAYER_EN_TYPE;
#define ISP_FR_BAYER_EN_HDR_MASK (0x10000UL)
#define ISP_FR_BAYER_EN_HDR_SHIFT (16UL)
#define ISP_FR_BAYER_EN_CDN_MASK (0x8000UL)
#define ISP_FR_BAYER_EN_CDN_SHIFT (15UL)
#define ISP_FR_BAYER_EN_FG_MASK (0x2000UL)
#define ISP_FR_BAYER_EN_FG_SHIFT (13UL)
#define ISP_FR_BAYER_EN_SW_MASK (0x1000UL)
#define ISP_FR_BAYER_EN_SW_SHIFT (12UL)
#define ISP_FR_BAYER_EN_DM_MASK (0x800UL)
#define ISP_FR_BAYER_EN_DM_SHIFT (11UL)
#define ISP_FR_BAYER_EN_BD_MASK (0x400UL)
#define ISP_FR_BAYER_EN_BD_SHIFT (10UL)
#define ISP_FR_BAYER_EN_XC_MASK (0x200UL)
#define ISP_FR_BAYER_EN_XC_SHIFT (9UL)
#define ISP_FR_BAYER_EN_RS_MASK (0x100UL)
#define ISP_FR_BAYER_EN_RS_SHIFT (8UL)
#define ISP_FR_BAYER_EN_DPA_MASK (0x80UL)
#define ISP_FR_BAYER_EN_DPA_SHIFT (7UL)
#define ISP_FR_BAYER_EN_DPP_MASK (0x40UL)
#define ISP_FR_BAYER_EN_DPP_SHIFT (6UL)
#define ISP_FR_BAYER_EN_WG_MASK (0x20UL)
#define ISP_FR_BAYER_EN_WG_SHIFT (5UL)
#define ISP_FR_BAYER_EN_ST_MASK (0x10UL)
#define ISP_FR_BAYER_EN_ST_SHIFT (4UL)
#define ISP_FR_BAYER_EN_LS_MASK (0x8UL)
#define ISP_FR_BAYER_EN_LS_SHIFT (3UL)
#define ISP_FR_BAYER_EN_BL_MASK (0x4UL)
#define ISP_FR_BAYER_EN_BL_SHIFT (2UL)
#define ISP_FR_BAYER_EN_DI_MASK (0x2UL)
#define ISP_FR_BAYER_EN_DI_SHIFT (1UL)
#define ISP_FR_BAYER_EN_II_MASK (0x1UL)
#define ISP_FR_BAYER_EN_II_SHIFT (0UL)




typedef uint32_t ISP_FR_YCBCR_EN_TYPE;
#define ISP_FR_YCBCR_EN_LTM_MASK (0x2000000UL)
#define ISP_FR_YCBCR_EN_LTM_SHIFT (25UL)
#define ISP_FR_YCBCR_EN_LO_MASK (0x2000UL)
#define ISP_FR_YCBCR_EN_LO_SHIFT (13UL)
#define ISP_FR_YCBCR_EN_HO_MASK (0x1000UL)
#define ISP_FR_YCBCR_EN_HO_SHIFT (12UL)
#define ISP_FR_YCBCR_EN_LR_MASK (0x800UL)
#define ISP_FR_YCBCR_EN_LR_SHIFT (11UL)
#define ISP_FR_YCBCR_EN_CC_MASK (0x400UL)
#define ISP_FR_YCBCR_EN_CC_SHIFT (10UL)
#define ISP_FR_YCBCR_EN_HR_MASK (0x200UL)
#define ISP_FR_YCBCR_EN_HR_SHIFT (9UL)
#define ISP_FR_YCBCR_EN_CP_MASK (0x100UL)
#define ISP_FR_YCBCR_EN_CP_SHIFT (8UL)
#define ISP_FR_YCBCR_EN_GD_MASK (0x80UL)
#define ISP_FR_YCBCR_EN_GD_SHIFT (7UL)
#define ISP_FR_YCBCR_EN_SH_MASK (0x40UL)
#define ISP_FR_YCBCR_EN_SH_SHIFT (6UL)
#define ISP_FR_YCBCR_EN_FC_MASK (0x20UL)
#define ISP_FR_YCBCR_EN_FC_SHIFT (5UL)
#define ISP_FR_YCBCR_EN_YG_MASK (0x8UL)
#define ISP_FR_YCBCR_EN_YG_SHIFT (3UL)
#define ISP_FR_YCBCR_EN_GM_MASK (0x4UL)
#define ISP_FR_YCBCR_EN_GM_SHIFT (2UL)
#define ISP_FR_YCBCR_EN_YC_MASK (0x2UL)
#define ISP_FR_YCBCR_EN_YC_SHIFT (1UL)
#define ISP_FR_YCBCR_EN_YI_MASK (0x1UL)
#define ISP_FR_YCBCR_EN_YI_SHIFT (0UL)




typedef uint32_t ISP_FR_MOSAIC_TYPE;




typedef uint32_t ISP_WG_RED_TYPE;
#define ISP_WG_RED_OFFSET_MASK (0xffff0000UL)
#define ISP_WG_RED_OFFSET_SHIFT (16UL)
#define ISP_WG_RED_GAIN_MASK (0xffffUL)
#define ISP_WG_RED_GAIN_SHIFT (0UL)




typedef uint32_t ISP_WG_BLUE_TYPE;
#define ISP_WG_BLUE_OFFSET_MASK (0xffff0000UL)
#define ISP_WG_BLUE_OFFSET_SHIFT (16UL)
#define ISP_WG_BLUE_GAIN_MASK (0xffffUL)
#define ISP_WG_BLUE_GAIN_SHIFT (0UL)




typedef uint32_t ISP_WG_OFFSETG_TYPE;
#define ISP_WG_OFFSETG_OFFSET_MASK (0x1ffffUL)
#define ISP_WG_OFFSETG_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_WG_GAIN_TYPE;
#define ISP_WG_GAIN_GAIN_MASK (0xffffUL)
#define ISP_WG_GAIN_GAIN_SHIFT (0UL)




typedef uint32_t ISP_WG_THRESH_TYPE;
#define ISP_WG_THRESH_THRESH_MASK (0xffffUL)
#define ISP_WG_THRESH_THRESH_SHIFT (0UL)




typedef uint32_t ISP_WG_OFFSETR_TYPE;
#define ISP_WG_OFFSETR_OFFSET_MASK (0x1ffffUL)
#define ISP_WG_OFFSETR_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_WG_OFFSETB_TYPE;
#define ISP_WG_OFFSETB_OFFSET_MASK (0x1ffffUL)
#define ISP_WG_OFFSETB_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_YG_MATRIX0_TYPE;
#define ISP_YG_MATRIX0_COEFF0_1_MASK (0x7fff0000UL)
#define ISP_YG_MATRIX0_COEFF0_1_SHIFT (16UL)
#define ISP_YG_MATRIX0_COEFF0_0_MASK (0x7fffUL)
#define ISP_YG_MATRIX0_COEFF0_0_SHIFT (0UL)




typedef uint32_t ISP_YG_OFFSET0_TYPE;
#define ISP_YG_OFFSET0_OFFSET0_MASK (0x1ffffUL)
#define ISP_YG_OFFSET0_OFFSET0_SHIFT (0UL)




typedef uint32_t ISP_YG_OFFSET1_TYPE;
#define ISP_YG_OFFSET1_OFFSET1_MASK (0x1ffffUL)
#define ISP_YG_OFFSET1_OFFSET1_SHIFT (0UL)




typedef uint32_t ISP_YG_OFFSET2_TYPE;
#define ISP_YG_OFFSET2_OFFSET2_MASK (0x1ffffUL)
#define ISP_YG_OFFSET2_OFFSET2_SHIFT (0UL)




typedef uint32_t ISP_II_CTRL_TYPE;
#define ISP_II_CTRL_STRIDE_MASK (0xffff8000UL)
#define ISP_II_CTRL_STRIDE_SHIFT (15UL)
#define ISP_II_CTRL_FORMAT_MASK (0x1f00UL)
#define ISP_II_CTRL_FORMAT_SHIFT (8UL)




typedef uint32_t ISP_II_ADDRESS_TYPE;
#define ISP_II_ADDRESS_ADDRESS_MASK (0xffffffe0UL)
#define ISP_II_ADDRESS_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_II_ENDADDR_TYPE;
#define ISP_II_ENDADDR_ENDADDR_MASK (0xffffffe0UL)
#define ISP_II_ENDADDR_ENDADDR_SHIFT (5UL)




typedef uint32_t ISP_II_DPCM_TYPE;
#define ISP_II_DPCM_MODE_MASK (0x1e00UL)
#define ISP_II_DPCM_MODE_SHIFT (9UL)
#define ISP_II_DPCM_BLOCKLEN_MASK (0x1ffUL)
#define ISP_II_DPCM_BLOCKLEN_SHIFT (0UL)




typedef uint32_t ISP_II_FIFO_TYPE;
#define ISP_II_FIFO_MIN3_MASK (0x3f00UL)
#define ISP_II_FIFO_MIN3_SHIFT (8UL)
#define ISP_II_FIFO_MIN2_MASK (0x3fUL)
#define ISP_II_FIFO_MIN2_SHIFT (0UL)




typedef uint32_t ISP_DI_ADDRESS_TYPE;
#define ISP_DI_ADDRESS_ADDRESS_MASK (0xffffffe0UL)
#define ISP_DI_ADDRESS_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_DI_ENDADDR_TYPE;
#define ISP_DI_ENDADDR_ENDADDR_MASK (0xffffffe0UL)
#define ISP_DI_ENDADDR_ENDADDR_SHIFT (5UL)




typedef uint32_t ISP_BL_LVL_R_TYPE;
#define ISP_BL_LVL_R_R_MASK (0xffffUL)
#define ISP_BL_LVL_R_R_SHIFT (0UL)




typedef uint32_t ISP_BL_LVL_GR_TYPE;
#define ISP_BL_LVL_GR_GR_MASK (0xffffUL)
#define ISP_BL_LVL_GR_GR_SHIFT (0UL)




typedef uint32_t ISP_BL_LVL_B_TYPE;
#define ISP_BL_LVL_B_B_MASK (0xffffUL)
#define ISP_BL_LVL_B_B_SHIFT (0UL)




typedef uint32_t ISP_BL_LVL_GB_TYPE;
#define ISP_BL_LVL_GB_GB_MASK (0xffffUL)
#define ISP_BL_LVL_GB_GB_SHIFT (0UL)




typedef uint32_t ISP_BL1_LVL_R_TYPE;
#define ISP_BL1_LVL_R_R_MASK (0xffffUL)
#define ISP_BL1_LVL_R_R_SHIFT (0UL)




typedef uint32_t ISP_BL1_LVL_GR_TYPE;
#define ISP_BL1_LVL_GR_GR_MASK (0xffffUL)
#define ISP_BL1_LVL_GR_GR_SHIFT (0UL)




typedef uint32_t ISP_BL1_LVL_B_TYPE;
#define ISP_BL1_LVL_B_B_MASK (0xffffUL)
#define ISP_BL1_LVL_B_B_SHIFT (0UL)




typedef uint32_t ISP_BL1_LVL_GB_TYPE;
#define ISP_BL1_LVL_GB_GB_MASK (0xffffUL)
#define ISP_BL1_LVL_GB_GB_SHIFT (0UL)




typedef uint32_t ISP_BL_ABSC_RN_TYPE;
#define ISP_BL_ABSC_RN_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL_ABSC_RN_ABSCISSA1_SHIFT (16UL)
#define ISP_BL_ABSC_RN_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL_ABSC_RN_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL_ABSC_GRN_TYPE;
#define ISP_BL_ABSC_GRN_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL_ABSC_GRN_ABSCISSA1_SHIFT (16UL)
#define ISP_BL_ABSC_GRN_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL_ABSC_GRN_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL_ABSC_BN_TYPE;
#define ISP_BL_ABSC_BN_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL_ABSC_BN_ABSCISSA1_SHIFT (16UL)
#define ISP_BL_ABSC_BN_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL_ABSC_BN_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL_ORD_SLOPE_RN_TYPE;
#define ISP_BL_ORD_SLOPE_RN_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL_ORD_SLOPE_RN_ORDINATE_SHIFT (16UL)
#define ISP_BL_ORD_SLOPE_RN_SLOPE_MASK (0xffffUL)
#define ISP_BL_ORD_SLOPE_RN_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_BL_ORD_SLOPE_GRN_TYPE;
#define ISP_BL_ORD_SLOPE_GRN_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL_ORD_SLOPE_GRN_ORDINATE_SHIFT (16UL)
#define ISP_BL_ORD_SLOPE_GRN_SLOPE_MASK (0xffffUL)
#define ISP_BL_ORD_SLOPE_GRN_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_BL_ORD_SLOPE_BN_TYPE;
#define ISP_BL_ORD_SLOPE_BN_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL_ORD_SLOPE_BN_ORDINATE_SHIFT (16UL)
#define ISP_BL_ORD_SLOPE_BN_SLOPE_MASK (0xffffUL)
#define ISP_BL_ORD_SLOPE_BN_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_BL_TB_TYPE;
#define ISP_BL_TB_BOTTOM_MASK (0xffff0000UL)
#define ISP_BL_TB_BOTTOM_SHIFT (16UL)
#define ISP_BL_TB_TOP_MASK (0xffUL)
#define ISP_BL_TB_TOP_SHIFT (0UL)




typedef uint32_t ISP_BL_LR_TYPE;
#define ISP_BL_LR_RIGHT_MASK (0xffff0000UL)
#define ISP_BL_LR_RIGHT_SHIFT (16UL)
#define ISP_BL_LR_LEFT_MASK (0xffUL)
#define ISP_BL_LR_LEFT_SHIFT (0UL)




typedef uint32_t ISP_BL_MT_TYPE;
#define ISP_BL_MT_THRESHOLD_MASK (0xffff0000UL)
#define ISP_BL_MT_THRESHOLD_SHIFT (16UL)
#define ISP_BL_MT_MULTIPLIER_MASK (0xffffUL)
#define ISP_BL_MT_MULTIPLIER_SHIFT (0UL)




typedef uint32_t ISP_BL_SHIFT_TYPE;
#define ISP_BL_SHIFT_GB_MASK (0x1000000UL)
#define ISP_BL_SHIFT_GB_SHIFT (24UL)
#define ISP_BL_SHIFT_B_MASK (0x10000UL)
#define ISP_BL_SHIFT_B_SHIFT (16UL)
#define ISP_BL_SHIFT_GR_MASK (0x100UL)
#define ISP_BL_SHIFT_GR_SHIFT (8UL)
#define ISP_BL_SHIFT_R_MASK (0x1UL)
#define ISP_BL_SHIFT_R_SHIFT (0UL)




typedef uint32_t ISP_BL_SUM_LO_TYPE;
#define ISP_BL_SUM_LO_LO_MASK (0xffffffffUL)
#define ISP_BL_SUM_LO_LO_SHIFT (0UL)




typedef uint32_t ISP_BL_SUM_HI_TYPE;
#define ISP_BL_SUM_HI_HI_MASK (0xffffUL)
#define ISP_BL_SUM_HI_HI_SHIFT (0UL)




typedef uint32_t ISP_BL_COUNT_TYPE;
#define ISP_BL_COUNT_COUNT_MASK (0xffffffffUL)
#define ISP_BL_COUNT_COUNT_SHIFT (0UL)




typedef uint32_t ISP_BL1_MT_TYPE;
#define ISP_BL1_MT_THRESHOLD_MASK (0xffff0000UL)
#define ISP_BL1_MT_THRESHOLD_SHIFT (16UL)
#define ISP_BL1_MT_MULTIPLIER_MASK (0xffffUL)
#define ISP_BL1_MT_MULTIPLIER_SHIFT (0UL)




typedef uint32_t ISP_BL1_SUM_LO_TYPE;
#define ISP_BL1_SUM_LO_LO_MASK (0xffffffffUL)
#define ISP_BL1_SUM_LO_LO_SHIFT (0UL)




typedef uint32_t ISP_BL1_SUM_HI_TYPE;
#define ISP_BL1_SUM_HI_HI_MASK (0xffffUL)
#define ISP_BL1_SUM_HI_HI_SHIFT (0UL)




typedef uint32_t ISP_BL1_COUNT_TYPE;
#define ISP_BL1_COUNT_COUNT_MASK (0xffffffffUL)
#define ISP_BL1_COUNT_COUNT_SHIFT (0UL)




typedef uint32_t ISP_BL1_SHIFT_TYPE;
#define ISP_BL1_SHIFT_GB_MASK (0x1000000UL)
#define ISP_BL1_SHIFT_GB_SHIFT (24UL)
#define ISP_BL1_SHIFT_B_MASK (0x10000UL)
#define ISP_BL1_SHIFT_B_SHIFT (16UL)
#define ISP_BL1_SHIFT_GR_MASK (0x100UL)
#define ISP_BL1_SHIFT_GR_SHIFT (8UL)
#define ISP_BL1_SHIFT_R_MASK (0x1UL)
#define ISP_BL1_SHIFT_R_SHIFT (0UL)




typedef uint32_t ISP_DP_HI_TYPE;
#define ISP_DP_HI_OFFSET_MASK (0xffff0000UL)
#define ISP_DP_HI_OFFSET_SHIFT (16UL)
#define ISP_DP_HI_SCALE_MASK (0x3f00UL)
#define ISP_DP_HI_SCALE_SHIFT (8UL)




typedef uint32_t ISP_DP_LO_TYPE;
#define ISP_DP_LO_OFFSET_MASK (0xffff0000UL)
#define ISP_DP_LO_OFFSET_SHIFT (16UL)
#define ISP_DP_LO_SCALE_MASK (0x3f00UL)
#define ISP_DP_LO_SCALE_SHIFT (8UL)




typedef uint32_t ISP_DP_REPLO_TYPE;
#define ISP_DP_REPLO_INDEX_MASK (0xf0000UL)
#define ISP_DP_REPLO_INDEX_SHIFT (16UL)
#define ISP_DP_REPLO_SCALE_MASK (0xff0UL)
#define ISP_DP_REPLO_SCALE_SHIFT (4UL)




typedef uint32_t ISP_DP_REPHI_TYPE;
#define ISP_DP_REPHI_INDEX_MASK (0xf0000UL)
#define ISP_DP_REPHI_INDEX_SHIFT (16UL)
#define ISP_DP_REPHI_SCALE_MASK (0xff0UL)
#define ISP_DP_REPHI_SCALE_SHIFT (4UL)




typedef uint32_t ISP_BL_ABSC_GB_TYPE;
#define ISP_BL_ABSC_GB_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL_ABSC_GB_ABSCISSA1_SHIFT (16UL)
#define ISP_BL_ABSC_GB_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL_ABSC_GB_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL_ORD_SLOPE_GB_TYPE;
#define ISP_BL_ORD_SLOPE_GB_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL_ORD_SLOPE_GB_ORDINATE_SHIFT (16UL)
#define ISP_BL_ORD_SLOPE_GB_SLOPE_MASK (0xffffUL)
#define ISP_BL_ORD_SLOPE_GB_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_HF_CTRL_TYPE;
#define ISP_HF_CTRL_PWL_SHIFT_MASK (0x2UL)
#define ISP_HF_CTRL_PWL_SHIFT_SHIFT (1UL)
#define ISP_HF_CTRL_SWAP_EXP_MASK (0x1UL)
#define ISP_HF_CTRL_SWAP_EXP_SHIFT (0UL)




typedef uint32_t ISP_HF_EXP_RATIO_TYPE;
#define ISP_HF_EXP_RATIO_RATIO_MASK (0xffffUL)
#define ISP_HF_EXP_RATIO_RATIO_SHIFT (0UL)




typedef uint32_t ISP_HF_THR_HI_TYPE;
#define ISP_HF_THR_HI_HI_MASK (0xffffUL)
#define ISP_HF_THR_HI_HI_SHIFT (0UL)




typedef uint32_t ISP_HF_THR_LO_TYPE;
#define ISP_HF_THR_LO_LO_MASK (0xffffUL)
#define ISP_HF_THR_LO_LO_SHIFT (0UL)




typedef uint32_t ISP_HF_WT_SC_TYPE;
#define ISP_HF_WT_SC_SC_MASK (0xfffffUL)
#define ISP_HF_WT_SC_SC_SHIFT (0UL)




typedef uint32_t ISP_HF_WB_RG_TYPE;
#define ISP_HF_WB_RG_RG_MASK (0xffffUL)
#define ISP_HF_WB_RG_RG_SHIFT (0UL)




typedef uint32_t ISP_HF_WB_BG_TYPE;
#define ISP_HF_WB_BG_BG_MASK (0xffffUL)
#define ISP_HF_WB_BG_BG_SHIFT (0UL)




typedef uint32_t ISP_HF_WB_TH_TYPE;
#define ISP_HF_WB_TH_TH_MASK (0xffffffffUL)
#define ISP_HF_WB_TH_TH_SHIFT (0UL)




typedef uint32_t ISP_HF_ABSC_TYPE;
#define ISP_HF_ABSC_ABSCISSA_MASK (0x3fffffUL)
#define ISP_HF_ABSC_ABSCISSA_SHIFT (0UL)




typedef uint32_t ISP_HF_ORD_SLOPE_TYPE;
#define ISP_HF_ORD_SLOPE_ORDINATE_MASK (0xffff0000UL)
#define ISP_HF_ORD_SLOPE_ORDINATE_SHIFT (16UL)
#define ISP_HF_ORD_SLOPE_SLOPE_MASK (0xffffUL)
#define ISP_HF_ORD_SLOPE_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_TD_CTRL_TYPE;
#define ISP_TD_CTRL_DESC_COUNT_MASK (0xfffUL)
#define ISP_TD_CTRL_DESC_COUNT_SHIFT (0UL)




typedef uint32_t ISP_TD_STATUS_TYPE;
#define ISP_TD_STATUS_INT_COUNT_MASK (0xfffUL)
#define ISP_TD_STATUS_INT_COUNT_SHIFT (0UL)




typedef uint32_t ISP_TD_ADDR_TYPE;
#define ISP_TD_ADDR_ADDRESS_MASK (0xffffffe0UL)
#define ISP_TD_ADDR_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_TD_DESC_TYPE[8];




typedef uint32_t ISP_TD_INIT0_TYPE;
#define ISP_TD_INIT0_LS_SET_MASK (0x80000000UL)
#define ISP_TD_INIT0_LS_SET_SHIFT (31UL)
#define ISP_TD_INIT0_LS_COUNT_MASK (0xfff0000UL)
#define ISP_TD_INIT0_LS_COUNT_SHIFT (16UL)
#define ISP_TD_INIT0_SET_MASK (0x8000UL)
#define ISP_TD_INIT0_SET_SHIFT (15UL)
#define ISP_TD_INIT0_COUNT_MASK (0xfffUL)
#define ISP_TD_INIT0_COUNT_SHIFT (0UL)




typedef uint32_t ISP_TD_INIT1_TYPE;
#define ISP_TD_INIT1_GD_SET_MASK (0x80000000UL)
#define ISP_TD_INIT1_GD_SET_SHIFT (31UL)
#define ISP_TD_INIT1_GD_COUNT_MASK (0xfff0000UL)
#define ISP_TD_INIT1_GD_COUNT_SHIFT (16UL)
#define ISP_TD_INIT1_ST_SET_MASK (0x8000UL)
#define ISP_TD_INIT1_ST_SET_SHIFT (15UL)
#define ISP_TD_INIT1_ST_COUNT_MASK (0xfffUL)
#define ISP_TD_INIT1_ST_COUNT_SHIFT (0UL)




typedef uint32_t ISP_TD_INIT2_TYPE;
#define ISP_TD_INIT2_PP_SET_MASK (0x8000UL)
#define ISP_TD_INIT2_PP_SET_SHIFT (15UL)
#define ISP_TD_INIT2_PP_COUNT_MASK (0xfffUL)
#define ISP_TD_INIT2_PP_COUNT_SHIFT (0UL)




typedef uint32_t ISP_LS_CTRL_TYPE;
#define ISP_LS_CTRL_PITCH_MASK (0x3ff0000UL)
#define ISP_LS_CTRL_PITCH_SHIFT (16UL)
#define ISP_LS_CTRL_CELL_SZ_POW_Y_MASK (0xf0UL)
#define ISP_LS_CTRL_CELL_SZ_POW_Y_SHIFT (4UL)
#define ISP_LS_CTRL_CELL_SZ_POW_X_MASK (0xfUL)
#define ISP_LS_CTRL_CELL_SZ_POW_X_SHIFT (0UL)




typedef uint32_t ISP_LS_OFFSETS_TYPE;
#define ISP_LS_OFFSETS_Y_OFFSET_MASK (0xffff0000UL)
#define ISP_LS_OFFSETS_Y_OFFSET_SHIFT (16UL)
#define ISP_LS_OFFSETS_X_OFFSET_MASK (0xffffUL)
#define ISP_LS_OFFSETS_X_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_XC_ABSC_LIM_TYPE;
#define ISP_XC_ABSC_LIM_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_XC_ABSC_LIM_ABSCISSA1_SHIFT (16UL)
#define ISP_XC_ABSC_LIM_ABSCISSA0_MASK (0xffffUL)
#define ISP_XC_ABSC_LIM_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_XC_ORD_LIM_TYPE;
#define ISP_XC_ORD_LIM_ORDINATE1_MASK (0xffff0000UL)
#define ISP_XC_ORD_LIM_ORDINATE1_SHIFT (16UL)
#define ISP_XC_ORD_LIM_ORDINATE0_MASK (0xffffUL)
#define ISP_XC_ORD_LIM_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_XC_SLOPE_LIM_TYPE;
#define ISP_XC_SLOPE_LIM_SLOPE1_MASK (0xffff0000UL)
#define ISP_XC_SLOPE_LIM_SLOPE1_SHIFT (16UL)
#define ISP_XC_SLOPE_LIM_SLOPE0_MASK (0xffffUL)
#define ISP_XC_SLOPE_LIM_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_FG_R_POS_TYPE;
#define ISP_FG_R_POS_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_R_POS_STRENGTH_SHIFT (16UL)
#define ISP_FG_R_POS_LIMIT_MASK (0xffffUL)
#define ISP_FG_R_POS_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_R_NEG_TYPE;
#define ISP_FG_R_NEG_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_R_NEG_STRENGTH_SHIFT (16UL)
#define ISP_FG_R_NEG_LIMIT_MASK (0xffffUL)
#define ISP_FG_R_NEG_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_GR_POS_TYPE;
#define ISP_FG_GR_POS_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_GR_POS_STRENGTH_SHIFT (16UL)
#define ISP_FG_GR_POS_LIMIT_MASK (0xffffUL)
#define ISP_FG_GR_POS_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_GR_NEG_TYPE;
#define ISP_FG_GR_NEG_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_GR_NEG_STRENGTH_SHIFT (16UL)
#define ISP_FG_GR_NEG_LIMIT_MASK (0xffffUL)
#define ISP_FG_GR_NEG_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_B_POS_TYPE;
#define ISP_FG_B_POS_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_B_POS_STRENGTH_SHIFT (16UL)
#define ISP_FG_B_POS_LIMIT_MASK (0xffffUL)
#define ISP_FG_B_POS_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_B_NEG_TYPE;
#define ISP_FG_B_NEG_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_B_NEG_STRENGTH_SHIFT (16UL)
#define ISP_FG_B_NEG_LIMIT_MASK (0xffffUL)
#define ISP_FG_B_NEG_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_GB_POS_TYPE;
#define ISP_FG_GB_POS_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_GB_POS_STRENGTH_SHIFT (16UL)
#define ISP_FG_GB_POS_LIMIT_MASK (0xffffUL)
#define ISP_FG_GB_POS_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_FG_GB_NEG_TYPE;
#define ISP_FG_GB_NEG_STRENGTH_MASK (0xffff0000UL)
#define ISP_FG_GB_NEG_STRENGTH_SHIFT (16UL)
#define ISP_FG_GB_NEG_LIMIT_MASK (0xffffUL)
#define ISP_FG_GB_NEG_LIMIT_SHIFT (0UL)




typedef uint32_t ISP_DN_CTRL_TYPE;




typedef uint32_t ISP_DN_ABSC_TYPE;
#define ISP_DN_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_DN_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_DN_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_DN_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_DN_ORD_TYPE;
#define ISP_DN_ORD_ORDINATE1_MASK (0xffff0000UL)
#define ISP_DN_ORD_ORDINATE1_SHIFT (16UL)
#define ISP_DN_ORD_ORDINATE0_MASK (0xffffUL)
#define ISP_DN_ORD_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_DN_SLOPE_TYPE;
#define ISP_DN_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_DN_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_DN_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_DN_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_DN_MASK0_TYPE;
#define ISP_DN_MASK0_MASK0_MASK (0xffffffffUL)
#define ISP_DN_MASK0_MASK0_SHIFT (0UL)




typedef uint32_t ISP_DN_MASK1_TYPE;
#define ISP_DN_MASK1_MASK1_MASK (0x1ffffUL)
#define ISP_DN_MASK1_MASK1_SHIFT (0UL)




typedef uint32_t ISP_DN_STRENGTH_TYPE;
#define ISP_DN_STRENGTH_B_STR_MASK (0xfc000000UL)
#define ISP_DN_STRENGTH_B_STR_SHIFT (26UL)
#define ISP_DN_STRENGTH_R_STR_MASK (0xc0000UL)
#define ISP_DN_STRENGTH_R_STR_SHIFT (18UL)
#define ISP_DN_STRENGTH_GB_STR_MASK (0xfc00UL)
#define ISP_DN_STRENGTH_GB_STR_SHIFT (10UL)
#define ISP_DN_STRENGTH_GR_STR_MASK (0xfcUL)
#define ISP_DN_STRENGTH_GR_STR_SHIFT (2UL)




typedef uint32_t ISP_DN_THRGAIN_TYPE;
#define ISP_DN_THRGAIN_B_GAIN_MASK (0x3f000000UL)
#define ISP_DN_THRGAIN_B_GAIN_SHIFT (24UL)
#define ISP_DN_THRGAIN_R_GAIN_MASK (0x3f0000UL)
#define ISP_DN_THRGAIN_R_GAIN_SHIFT (16UL)
#define ISP_DN_THRGAIN_GB_GAIN_MASK (0x3f00UL)
#define ISP_DN_THRGAIN_GB_GAIN_SHIFT (8UL)
#define ISP_DN_THRGAIN_GR_GAIN_MASK (0x3fUL)
#define ISP_DN_THRGAIN_GR_GAIN_SHIFT (0UL)




typedef uint32_t ISP_DM_CTRL_TYPE;
#define ISP_DM_CTRL_HV_BIAS_MASK (0x1ff00000UL)
#define ISP_DM_CTRL_HV_BIAS_SHIFT (20UL)
#define ISP_DM_CTRL_G_OFF_SH_MASK (0xf00UL)
#define ISP_DM_CTRL_G_OFF_SH_SHIFT (8UL)
#define ISP_DM_CTRL_V_COSITED_MASK (0x2UL)
#define ISP_DM_CTRL_V_COSITED_SHIFT (1UL)
#define ISP_DM_CTRL_H_COSITED_MASK (0x1UL)
#define ISP_DM_CTRL_H_COSITED_SHIFT (0UL)




typedef uint32_t ISP_DM_THRESH_TYPE;
#define ISP_DM_THRESH_THRESH_MASK (0xffffffffUL)
#define ISP_DM_THRESH_THRESH_SHIFT (0UL)




typedef uint32_t ISP_YI_CTRL_TYPE;
#define ISP_YI_CTRL_COL_WIDTH_MASK (0x3000000UL)
#define ISP_YI_CTRL_COL_WIDTH_SHIFT (24UL)
#define ISP_YI_CTRL_COL_MODE_MASK (0x1000UL)
#define ISP_YI_CTRL_COL_MODE_SHIFT (12UL)
#define ISP_YI_CTRL_CC_ORDER_MASK (0x380UL)
#define ISP_YI_CTRL_CC_ORDER_SHIFT (7UL)
#define ISP_YI_CTRL_DATA_FORMAT_MASK (0x70UL)
#define ISP_YI_CTRL_DATA_FORMAT_SHIFT (4UL)
#define ISP_YI_CTRL_BYTES_SAMPLE_MASK (0x4UL)
#define ISP_YI_CTRL_BYTES_SAMPLE_SHIFT (2UL)
#define ISP_YI_CTRL_CS_FORMAT_MASK (0x3UL)
#define ISP_YI_CTRL_CS_FORMAT_SHIFT (0UL)




typedef uint32_t ISP_YI_RY_ADDR_TYPE;
#define ISP_YI_RY_ADDR_ADDRESS_MASK (0xffffffe0UL)
#define ISP_YI_RY_ADDR_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_YI_GU_ADDR_TYPE;
#define ISP_YI_GU_ADDR_ADDRESS_MASK (0xffffffe0UL)
#define ISP_YI_GU_ADDR_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_YI_BV_ADDR_TYPE;
#define ISP_YI_BV_ADDR_ADDRESS_MASK (0xffffffe0UL)
#define ISP_YI_BV_ADDR_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_YI_STRIDE1_TYPE;
#define ISP_YI_STRIDE1_Y_STRIDE_MASK (0xfffe0UL)
#define ISP_YI_STRIDE1_Y_STRIDE_SHIFT (5UL)




typedef uint32_t ISP_YI_STRIDE2_TYPE;
#define ISP_YI_STRIDE2_UV_STRIDE_MASK (0xffff0UL)
#define ISP_YI_STRIDE2_UV_STRIDE_SHIFT (4UL)




typedef uint32_t ISP_YI_COL_STRIDE1_TYPE;
#define ISP_YI_COL_STRIDE1_STRIDE_MASK (0x1fffe00UL)
#define ISP_YI_COL_STRIDE1_STRIDE_SHIFT (9UL)




typedef uint32_t ISP_YI_COL_STRIDE2_TYPE;
#define ISP_YI_COL_STRIDE2_STRIDE_MASK (0x1fffe00UL)
#define ISP_YI_COL_STRIDE2_STRIDE_SHIFT (9UL)




typedef uint32_t ISP_YI_RY_EADDR_TYPE;
#define ISP_YI_RY_EADDR_ENDADDR_MASK (0xffffffe0UL)
#define ISP_YI_RY_EADDR_ENDADDR_SHIFT (5UL)




typedef uint32_t ISP_YI_GU_EADDR_TYPE;
#define ISP_YI_GU_EADDR_ENDADDR_MASK (0xffffffe0UL)
#define ISP_YI_GU_EADDR_ENDADDR_SHIFT (5UL)




typedef uint32_t ISP_YI_BV_EADDR_TYPE;
#define ISP_YI_BV_EADDR_ENDADDR_MASK (0xffffffe0UL)
#define ISP_YI_BV_EADDR_ENDADDR_SHIFT (5UL)




typedef uint32_t ISP_YC_MATRIX_TYPE;
#define ISP_YC_MATRIX_ELEMENT1_MASK (0xffff0000UL)
#define ISP_YC_MATRIX_ELEMENT1_SHIFT (16UL)
#define ISP_YC_MATRIX_ELEMENT0_MASK (0xffffUL)
#define ISP_YC_MATRIX_ELEMENT0_SHIFT (0UL)




typedef uint32_t ISP_YC_OFFSET_TYPE;
#define ISP_YC_OFFSET_OFFSET_MASK (0x1ffffUL)
#define ISP_YC_OFFSET_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_GM_ABSC_R_TYPE;
#define ISP_GM_ABSC_R_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_GM_ABSC_R_ABSCISSA1_SHIFT (16UL)
#define ISP_GM_ABSC_R_ABSCISSA0_MASK (0xffffUL)
#define ISP_GM_ABSC_R_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_GM_ABSC_G_TYPE;
#define ISP_GM_ABSC_G_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_GM_ABSC_G_ABSCISSA1_SHIFT (16UL)
#define ISP_GM_ABSC_G_ABSCISSA0_MASK (0xffffUL)
#define ISP_GM_ABSC_G_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_GM_ABSC_B_TYPE;
#define ISP_GM_ABSC_B_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_GM_ABSC_B_ABSCISSA1_SHIFT (16UL)
#define ISP_GM_ABSC_B_ABSCISSA0_MASK (0xffffUL)
#define ISP_GM_ABSC_B_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_GM_SHIFT_TYPE;
#define ISP_GM_SHIFT_SHIFT_MASK (0x1UL)
#define ISP_GM_SHIFT_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_FC_STRENGTH_TYPE;
#define ISP_FC_STRENGTH_STRENGTH2_MASK (0xff00000UL)
#define ISP_FC_STRENGTH_STRENGTH2_SHIFT (20UL)
#define ISP_FC_STRENGTH_STRENGTH1_MASK (0xff0UL)
#define ISP_FC_STRENGTH_STRENGTH1_SHIFT (4UL)




typedef uint32_t ISP_FC_FMIX_TYPE;
#define ISP_FC_FMIX_ABSOLUTE_MASK (0x8000UL)
#define ISP_FC_FMIX_ABSOLUTE_SHIFT (15UL)
#define ISP_FC_FMIX_WEIGHT_MASK (0x1fe0UL)
#define ISP_FC_FMIX_WEIGHT_SHIFT (5UL)




typedef uint32_t ISP_FC_FMIX_THRESH_TYPE;
#define ISP_FC_FMIX_THRESH_HI_MASK (0xffff0000UL)
#define ISP_FC_FMIX_THRESH_HI_SHIFT (16UL)
#define ISP_FC_FMIX_THRESH_LO_MASK (0xffffUL)
#define ISP_FC_FMIX_THRESH_LO_SHIFT (0UL)




typedef uint32_t ISP_FC_FMIX_NORM_TYPE;
#define ISP_FC_FMIX_NORM_NORM2_MASK (0xfff0000UL)
#define ISP_FC_FMIX_NORM_NORM2_SHIFT (16UL)
#define ISP_FC_FMIX_NORM_NORM_MASK (0xfffUL)
#define ISP_FC_FMIX_NORM_NORM_SHIFT (0UL)




typedef uint32_t ISP_FC_FDESAT_TYPE;
#define ISP_FC_FDESAT_ABSOLUTE_MASK (0x8000UL)
#define ISP_FC_FDESAT_ABSOLUTE_SHIFT (15UL)
#define ISP_FC_FDESAT_WEIGHT_MASK (0x1fe0UL)
#define ISP_FC_FDESAT_WEIGHT_SHIFT (5UL)




typedef uint32_t ISP_FC_FDESAT_THRESH_TYPE;
#define ISP_FC_FDESAT_THRESH_HI_MASK (0xffff0000UL)
#define ISP_FC_FDESAT_THRESH_HI_SHIFT (16UL)
#define ISP_FC_FDESAT_THRESH_LO_MASK (0xffffUL)
#define ISP_FC_FDESAT_THRESH_LO_SHIFT (0UL)




typedef uint32_t ISP_FC_FDESAT_NORM_TYPE;
#define ISP_FC_FDESAT_NORM_NORM2_MASK (0xfff0000UL)
#define ISP_FC_FDESAT_NORM_NORM2_SHIFT (16UL)
#define ISP_FC_FDESAT_NORM_NORM_MASK (0xfffUL)
#define ISP_FC_FDESAT_NORM_NORM_SHIFT (0UL)




typedef uint32_t ISP_SH_STRENGTH_TYPE;
#define ISP_SH_STRENGTH_ISOTROPIC_STR_MASK (0xffff0000UL)
#define ISP_SH_STRENGTH_ISOTROPIC_STR_SHIFT (16UL)
#define ISP_SH_STRENGTH_AVG_G_SH_MASK (0xf800UL)
#define ISP_SH_STRENGTH_AVG_G_SH_SHIFT (11UL)




typedef uint32_t ISP_SH_CENTRE_TYPE;
#define ISP_SH_CENTRE_Y_CENTRE_MASK (0xffff0000UL)
#define ISP_SH_CENTRE_Y_CENTRE_SHIFT (16UL)
#define ISP_SH_CENTRE_X_CENTRE_MASK (0xffffUL)
#define ISP_SH_CENTRE_X_CENTRE_SHIFT (0UL)




typedef uint32_t ISP_LR_TSCALEX_TYPE;
#define ISP_LR_TSCALEX_SCALE_MASK (0x3fffffUL)
#define ISP_LR_TSCALEX_SCALE_SHIFT (0UL)




typedef uint32_t ISP_LR_TSCALEY_TYPE;
#define ISP_LR_TSCALEY_SCALE_MASK (0x3fffffUL)
#define ISP_LR_TSCALEY_SCALE_SHIFT (0UL)




typedef uint32_t ISP_LR_NORM_0_1_TYPE;
#define ISP_LR_NORM_0_1_Y_MASK (0xfff0000UL)
#define ISP_LR_NORM_0_1_Y_SHIFT (16UL)
#define ISP_LR_NORM_0_1_X_MASK (0xfffUL)
#define ISP_LR_NORM_0_1_X_SHIFT (0UL)




typedef uint32_t ISP_LR_NORM_2_3_TYPE;
#define ISP_LR_NORM_2_3_Y_MASK (0xfff0000UL)
#define ISP_LR_NORM_2_3_Y_SHIFT (16UL)
#define ISP_LR_NORM_2_3_X_MASK (0xfffUL)
#define ISP_LR_NORM_2_3_X_SHIFT (0UL)




typedef uint32_t ISP_LR_SHIFT_TYPE;
#define ISP_LR_SHIFT_RB_SWAP_MASK (0x100UL)
#define ISP_LR_SHIFT_RB_SWAP_SHIFT (8UL)
#define ISP_LR_SHIFT_SHIFT_MASK (0xfUL)
#define ISP_LR_SHIFT_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_CC_MATRIX_TYPE;
#define ISP_CC_MATRIX_ELEMENT1_MASK (0xffff0000UL)
#define ISP_CC_MATRIX_ELEMENT1_SHIFT (16UL)
#define ISP_CC_MATRIX_ELEMENT0_MASK (0xffffUL)
#define ISP_CC_MATRIX_ELEMENT0_SHIFT (0UL)




typedef uint32_t ISP_CC_OFFSET_TYPE;
#define ISP_CC_OFFSET_OFFSET_MASK (0x3ffffUL)
#define ISP_CC_OFFSET_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_ST_FOC_CTRL_TYPE;
#define ISP_ST_FOC_CTRL_R_B_MODE_MASK (0x1UL)
#define ISP_ST_FOC_CTRL_R_B_MODE_SHIFT (0UL)




typedef uint32_t ISP_ST_FOC_FILTEX_TYPE;
#define ISP_ST_FOC_FILTEX_COEFF1_MASK (0xff0000UL)
#define ISP_ST_FOC_FILTEX_COEFF1_SHIFT (16UL)
#define ISP_ST_FOC_FILTEX_COEFF0_MASK (0xffUL)
#define ISP_ST_FOC_FILTEX_COEFF0_SHIFT (0UL)




typedef uint32_t ISP_ST_SHIFT_TYPE;
#define ISP_ST_SHIFT_PIX_SHIFT_MASK (0x3000000UL)
#define ISP_ST_SHIFT_PIX_SHIFT_SHIFT (24UL)
#define ISP_ST_SHIFT_SHIFT_MASK (0xffffUL)
#define ISP_ST_SHIFT_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_ST_R_OFF_TYPE;
#define ISP_ST_R_OFF_Y_OFFSET_MASK (0xffff0000UL)
#define ISP_ST_R_OFF_Y_OFFSET_SHIFT (16UL)
#define ISP_ST_R_OFF_X_OFFSET_MASK (0xffffUL)
#define ISP_ST_R_OFF_X_OFFSET_SHIFT (0UL)




typedef uint32_t ISP_ST_R_RECT_TYPE;
#define ISP_ST_R_RECT_HEIGHT_MASK (0xffff0000UL)
#define ISP_ST_R_RECT_HEIGHT_SHIFT (16UL)
#define ISP_ST_R_RECT_ISPST_WIDTH_MASK (0xffffUL)
#define ISP_ST_R_RECT_ISPST_WIDTH_SHIFT (0UL)




typedef uint32_t ISP_ST_HMASK0_TYPE;
#define ISP_ST_HMASK0_HIST1_MASK (0xffff0000UL)
#define ISP_ST_HMASK0_HIST1_SHIFT (16UL)
#define ISP_ST_HMASK0_HIST0_MASK (0xffffUL)
#define ISP_ST_HMASK0_HIST0_SHIFT (0UL)




typedef uint32_t ISP_ST_FOC_FILT_TYPE;
#define ISP_ST_FOC_FILT_COEFF1_MASK (0xff0000UL)
#define ISP_ST_FOC_FILT_COEFF1_SHIFT (16UL)
#define ISP_ST_FOC_FILT_COEFF0_MASK (0xffUL)
#define ISP_ST_FOC_FILT_COEFF0_SHIFT (0UL)




typedef uint32_t ISP_ST_FILT_GAINS_TYPE;
#define ISP_ST_FILT_GAINS_GAIN1_MASK (0xff0000UL)
#define ISP_ST_FILT_GAINS_GAIN1_SHIFT (16UL)
#define ISP_ST_FILT_GAINS_GAIN0_MASK (0xffUL)
#define ISP_ST_FILT_GAINS_GAIN0_SHIFT (0UL)




typedef uint32_t ISP_ST_FILT_TH_TYPE;
#define ISP_ST_FILT_TH_THRESHOLD_MASK (0xffffUL)
#define ISP_ST_FILT_TH_THRESHOLD_SHIFT (0UL)




typedef uint32_t ISP_ST_ROW_NUM_TYPE;
#define ISP_ST_ROW_NUM_COL_MASK (0x10000UL)
#define ISP_ST_ROW_NUM_COL_SHIFT (16UL)
#define ISP_ST_ROW_NUM_ROW_NUM_MASK (0xffffUL)
#define ISP_ST_ROW_NUM_ROW_NUM_SHIFT (0UL)




typedef uint32_t ISP_ST_R_TH_TYPE;
#define ISP_ST_R_TH_HI_MASK (0xffff0000UL)
#define ISP_ST_R_TH_HI_SHIFT (16UL)
#define ISP_ST_R_TH_LO_MASK (0xffffUL)
#define ISP_ST_R_TH_LO_SHIFT (0UL)




typedef uint32_t ISP_ST_G_TH_TYPE;
#define ISP_ST_G_TH_HI_MASK (0xffff0000UL)
#define ISP_ST_G_TH_HI_SHIFT (16UL)
#define ISP_ST_G_TH_LO_MASK (0xffffUL)
#define ISP_ST_G_TH_LO_SHIFT (0UL)




typedef uint32_t ISP_ST_B_TH_TYPE;
#define ISP_ST_B_TH_HI_MASK (0xffff0000UL)
#define ISP_ST_B_TH_HI_SHIFT (16UL)
#define ISP_ST_B_TH_LO_MASK (0xffffUL)
#define ISP_ST_B_TH_LO_SHIFT (0UL)




typedef uint32_t ISP_ST_R_G_TH_TYPE;
#define ISP_ST_R_G_TH_HI_MASK (0xffff0000UL)
#define ISP_ST_R_G_TH_HI_SHIFT (16UL)
#define ISP_ST_R_G_TH_LO_MASK (0xffffUL)
#define ISP_ST_R_G_TH_LO_SHIFT (0UL)




typedef uint32_t ISP_ST_B_G_TH_TYPE;
#define ISP_ST_B_G_TH_HI_MASK (0xffff0000UL)
#define ISP_ST_B_G_TH_HI_SHIFT (16UL)
#define ISP_ST_B_G_TH_LO_MASK (0xffffUL)
#define ISP_ST_B_G_TH_LO_SHIFT (0UL)




typedef uint32_t ISP_ST_GROUP_0_X_TYPE;
#define ISP_ST_GROUP_0_X_X1_MASK (0xffff0000UL)
#define ISP_ST_GROUP_0_X_X1_SHIFT (16UL)
#define ISP_ST_GROUP_0_X_X0_MASK (0xffffUL)
#define ISP_ST_GROUP_0_X_X0_SHIFT (0UL)




typedef uint32_t ISP_ST_GROUP_0_Y_TYPE;
#define ISP_ST_GROUP_0_Y_Y1_MASK (0xffff0000UL)
#define ISP_ST_GROUP_0_Y_Y1_SHIFT (16UL)
#define ISP_ST_GROUP_0_Y_Y0_MASK (0xffffUL)
#define ISP_ST_GROUP_0_Y_Y0_SHIFT (0UL)




typedef uint32_t ISP_ST_GRP0_CTRL_TYPE;
#define ISP_ST_GRP0_CTRL_PITCH_MASK (0x3fUL)
#define ISP_ST_GRP0_CTRL_PITCH_SHIFT (0UL)




typedef uint32_t ISP_ST_HGAIN0_TYPE;
#define ISP_ST_HGAIN0_HGAIN_MASK (0xffffffffUL)
#define ISP_ST_HGAIN0_HGAIN_SHIFT (0UL)




typedef uint32_t ISP_ST_HGAIN1_TYPE;
#define ISP_ST_HGAIN1_HGAIN_MASK (0xffffffffUL)
#define ISP_ST_HGAIN1_HGAIN_SHIFT (0UL)




typedef uint32_t ISP_HO_CTRL_TYPE;
#define ISP_HO_CTRL_BYTE_SWAP_EN_MASK (0x80000000UL)
#define ISP_HO_CTRL_BYTE_SWAP_EN_SHIFT (31UL)
#define ISP_HO_CTRL_SAT_DEPTH_MASK (0x70000000UL)
#define ISP_HO_CTRL_SAT_DEPTH_SHIFT (28UL)
#define ISP_HO_CTRL_CBUF_EN_MASK (0x8000000UL)
#define ISP_HO_CTRL_CBUF_EN_SHIFT (27UL)
#define ISP_HO_CTRL_COL_WIDTH_MASK (0x3000000UL)
#define ISP_HO_CTRL_COL_WIDTH_SHIFT (24UL)
#define ISP_HO_CTRL_SHIFT_MASK (0x1e0000UL)
#define ISP_HO_CTRL_SHIFT_SHIFT (17UL)
#define ISP_HO_CTRL_DATA_FORMAT_MSB_MASK (0x8000UL)
#define ISP_HO_CTRL_DATA_FORMAT_MSB_SHIFT (15UL)
#define ISP_HO_CTRL_VFLIP_MASK (0x4000UL)
#define ISP_HO_CTRL_VFLIP_SHIFT (14UL)
#define ISP_HO_CTRL_COL_MODE_MASK (0x1000UL)
#define ISP_HO_CTRL_COL_MODE_SHIFT (12UL)
#define ISP_HO_CTRL_DATA_FORMAT_MASK (0xe00UL)
#define ISP_HO_CTRL_DATA_FORMAT_SHIFT (9UL)
#define ISP_HO_CTRL_OUTPUT_WIDTH_MASK (0x100UL)
#define ISP_HO_CTRL_OUTPUT_WIDTH_SHIFT (8UL)
#define ISP_HO_CTRL_PLANE_DISABLES_MASK (0x7UL)
#define ISP_HO_CTRL_PLANE_DISABLES_SHIFT (0UL)




typedef uint32_t ISP_HO_COL_STRIDE1_TYPE;
#define ISP_HO_COL_STRIDE1_STRIDE_MASK (0x1fffe00UL)
#define ISP_HO_COL_STRIDE1_STRIDE_SHIFT (9UL)




typedef uint32_t ISP_HO_COL_STRIDE2_TYPE;
#define ISP_HO_COL_STRIDE2_STRIDE_MASK (0x1fffe00UL)
#define ISP_HO_COL_STRIDE2_STRIDE_SHIFT (9UL)




typedef uint32_t ISP_HO_ADDRESS1_TYPE;
#define ISP_HO_ADDRESS1_ADDRESS_MASK (0xffffffe0UL)
#define ISP_HO_ADDRESS1_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_HO_ADDRESS2_TYPE;
#define ISP_HO_ADDRESS2_ADDRESS_MASK (0xffffffe0UL)
#define ISP_HO_ADDRESS2_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_HO_ADDRESS3_TYPE;
#define ISP_HO_ADDRESS3_ADDRESS_MASK (0xffffffe0UL)
#define ISP_HO_ADDRESS3_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_HO_STRIDE1_TYPE;
#define ISP_HO_STRIDE1_STRIDE_MASK (0x1fffe0UL)
#define ISP_HO_STRIDE1_STRIDE_SHIFT (5UL)




typedef uint32_t ISP_HO_STRIDE2_TYPE;
#define ISP_HO_STRIDE2_STRIDE_MASK (0x1ffff0UL)
#define ISP_HO_STRIDE2_STRIDE_SHIFT (4UL)




typedef uint32_t ISP_HO_END_ADDRESS1_TYPE;
#define ISP_HO_END_ADDRESS1_ADDRESS_MASK (0xffffffe0UL)
#define ISP_HO_END_ADDRESS1_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_HO_END_ADDRESS2_TYPE;
#define ISP_HO_END_ADDRESS2_ADDRESS_MASK (0xffffffe0UL)
#define ISP_HO_END_ADDRESS2_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_HO_END_ADDRESS3_TYPE;
#define ISP_HO_END_ADDRESS3_ADDRESS_MASK (0xffffffe0UL)
#define ISP_HO_END_ADDRESS3_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_HO_SYNC_CTRL_TYPE;
#define ISP_HO_SYNC_CTRL_THRESH_MASK (0xfff0000UL)
#define ISP_HO_SYNC_CTRL_THRESH_SHIFT (16UL)
#define ISP_HO_SYNC_CTRL_LINES_MASK (0xfffUL)
#define ISP_HO_SYNC_CTRL_LINES_SHIFT (0UL)




typedef uint32_t ISP_LO_CTRL_TYPE;
#define ISP_LO_CTRL_BYTE_SWAP_EN_MASK (0x80000000UL)
#define ISP_LO_CTRL_BYTE_SWAP_EN_SHIFT (31UL)
#define ISP_LO_CTRL_SAT_DEPTH_MASK (0x70000000UL)
#define ISP_LO_CTRL_SAT_DEPTH_SHIFT (28UL)
#define ISP_LO_CTRL_CBUF_EN_MASK (0x8000000UL)
#define ISP_LO_CTRL_CBUF_EN_SHIFT (27UL)
#define ISP_LO_CTRL_COL_WIDTH_MASK (0x3000000UL)
#define ISP_LO_CTRL_COL_WIDTH_SHIFT (24UL)
#define ISP_LO_CTRL_SHIFT_MASK (0x1e0000UL)
#define ISP_LO_CTRL_SHIFT_SHIFT (17UL)
#define ISP_LO_CTRL_DATA_FORMAT_MSB_MASK (0x8000UL)
#define ISP_LO_CTRL_DATA_FORMAT_MSB_SHIFT (15UL)
#define ISP_LO_CTRL_VFLIP_MASK (0x4000UL)
#define ISP_LO_CTRL_VFLIP_SHIFT (14UL)
#define ISP_LO_CTRL_COL_MODE_MASK (0x1000UL)
#define ISP_LO_CTRL_COL_MODE_SHIFT (12UL)
#define ISP_LO_CTRL_DATA_FORMAT_MASK (0xe00UL)
#define ISP_LO_CTRL_DATA_FORMAT_SHIFT (9UL)
#define ISP_LO_CTRL_OUTPUT_WIDTH_MASK (0x100UL)
#define ISP_LO_CTRL_OUTPUT_WIDTH_SHIFT (8UL)
#define ISP_LO_CTRL_PLANE_DISABLES_MASK (0x7UL)
#define ISP_LO_CTRL_PLANE_DISABLES_SHIFT (0UL)




typedef uint32_t ISP_LO_COL_STRIDE1_TYPE;
#define ISP_LO_COL_STRIDE1_STRIDE_MASK (0x1fffe00UL)
#define ISP_LO_COL_STRIDE1_STRIDE_SHIFT (9UL)




typedef uint32_t ISP_LO_COL_STRIDE2_TYPE;
#define ISP_LO_COL_STRIDE2_STRIDE_MASK (0x1fffe00UL)
#define ISP_LO_COL_STRIDE2_STRIDE_SHIFT (9UL)




typedef uint32_t ISP_LO_ADDRESS1_TYPE;
#define ISP_LO_ADDRESS1_ADDRESS_MASK (0xffffffe0UL)
#define ISP_LO_ADDRESS1_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LO_ADDRESS2_TYPE;
#define ISP_LO_ADDRESS2_ADDRESS_MASK (0xffffffe0UL)
#define ISP_LO_ADDRESS2_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LO_ADDRESS3_TYPE;
#define ISP_LO_ADDRESS3_ADDRESS_MASK (0xffffffe0UL)
#define ISP_LO_ADDRESS3_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LO_STRIDE1_TYPE;
#define ISP_LO_STRIDE1_STRIDE_MASK (0x1fffe0UL)
#define ISP_LO_STRIDE1_STRIDE_SHIFT (5UL)




typedef uint32_t ISP_LO_STRIDE2_TYPE;
#define ISP_LO_STRIDE2_STRIDE_MASK (0x1ffff0UL)
#define ISP_LO_STRIDE2_STRIDE_SHIFT (4UL)




typedef uint32_t ISP_LO_END_ADDRESS1_TYPE;
#define ISP_LO_END_ADDRESS1_ADDRESS_MASK (0xffffffe0UL)
#define ISP_LO_END_ADDRESS1_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LO_END_ADDRESS2_TYPE;
#define ISP_LO_END_ADDRESS2_ADDRESS_MASK (0xffffffe0UL)
#define ISP_LO_END_ADDRESS2_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LO_END_ADDRESS3_TYPE;
#define ISP_LO_END_ADDRESS3_ADDRESS_MASK (0xffffffe0UL)
#define ISP_LO_END_ADDRESS3_ADDRESS_SHIFT (5UL)




typedef uint32_t ISP_LO_SYNC_CTRL_TYPE;
#define ISP_LO_SYNC_CTRL_THRESH_MASK (0xfff0000UL)
#define ISP_LO_SYNC_CTRL_THRESH_SHIFT (16UL)
#define ISP_LO_SYNC_CTRL_LINES_MASK (0xfffUL)
#define ISP_LO_SYNC_CTRL_LINES_SHIFT (0UL)




typedef uint32_t ISP_CK_ADDR_TYPE;
#define ISP_CK_ADDR_ADDR_MASK (0xffffffffUL)
#define ISP_CK_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t ISP_CK_STATUS_TYPE;
#define ISP_CK_STATUS_STATUS_MASK (0xffffffffUL)
#define ISP_CK_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t ISP_CK_DATA_TYPE;
#define ISP_CK_DATA_DATA_MASK (0xffffffffUL)
#define ISP_CK_DATA_DATA_SHIFT (0UL)




typedef uint32_t ISP_CA_CTRL_TYPE;
#define ISP_CA_CTRL_CTRL_MASK (0xffffffffUL)
#define ISP_CA_CTRL_CTRL_SHIFT (0UL)




typedef uint32_t ISP_CA_STATUS_TYPE;
#define ISP_CA_STATUS_STATUS_MASK (0xffffffffUL)
#define ISP_CA_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t ISP_CA_DATA_LOW_TYPE;
#define ISP_CA_DATA_LOW_LOW_MASK (0xffffffffUL)
#define ISP_CA_DATA_LOW_LOW_SHIFT (0UL)




typedef uint32_t ISP_CA_DATA_HIGH_TYPE;
#define ISP_CA_DATA_HIGH_HIGH_MASK (0xffffffffUL)
#define ISP_CA_DATA_HIGH_HIGH_SHIFT (0UL)




typedef uint32_t ISP_CA_PIXEL_CNT_TYPE;
#define ISP_CA_PIXEL_CNT_CNT_MASK (0xffffffffUL)
#define ISP_CA_PIXEL_CNT_CNT_SHIFT (0UL)




typedef uint32_t ISP_CA_LINE_TILE_CNT_TYPE;
#define ISP_CA_LINE_TILE_CNT_CNT_MASK (0xffffffffUL)
#define ISP_CA_LINE_TILE_CNT_CNT_SHIFT (0UL)




typedef uint32_t ISP_DG_CTRL_TYPE;
#define ISP_DG_CTRL_CTRL_MASK (0xffffffffUL)
#define ISP_DG_CTRL_CTRL_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_CNT0_TYPE;
#define ISP_DG_TILE_CNT0_CNT0_MASK (0xffffffffUL)
#define ISP_DG_TILE_CNT0_CNT0_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_CNT1_TYPE;
#define ISP_DG_TILE_CNT1_CNT1_MASK (0xffffffffUL)
#define ISP_DG_TILE_CNT1_CNT1_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_CNT2_TYPE;
#define ISP_DG_TILE_CNT2_CNT2_MASK (0xffffffffUL)
#define ISP_DG_TILE_CNT2_CNT2_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_CNT3_TYPE;
#define ISP_DG_TILE_CNT3_CNT3_MASK (0xffffffffUL)
#define ISP_DG_TILE_CNT3_CNT3_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_CNT4_TYPE;
#define ISP_DG_TILE_CNT4_CNT4_MASK (0xffffffffUL)
#define ISP_DG_TILE_CNT4_CNT4_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_CNT5_TYPE;
#define ISP_DG_TILE_CNT5_CNT5_MASK (0xffffffffUL)
#define ISP_DG_TILE_CNT5_CNT5_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT0_TYPE;
#define ISP_DG_LINE_CNT0_CNT0_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT0_CNT0_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT1_TYPE;
#define ISP_DG_LINE_CNT1_CNT1_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT1_CNT1_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT2_TYPE;
#define ISP_DG_LINE_CNT2_CNT2_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT2_CNT2_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT3_TYPE;
#define ISP_DG_LINE_CNT3_CNT3_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT3_CNT3_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT4_TYPE;
#define ISP_DG_LINE_CNT4_CNT4_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT4_CNT4_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT5_TYPE;
#define ISP_DG_LINE_CNT5_CNT5_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT5_CNT5_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT6_TYPE;
#define ISP_DG_LINE_CNT6_CNT6_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT6_CNT6_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT7_TYPE;
#define ISP_DG_LINE_CNT7_CNT7_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT7_CNT7_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT8_TYPE;
#define ISP_DG_LINE_CNT8_CNT8_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT8_CNT8_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT9_TYPE;
#define ISP_DG_LINE_CNT9_CNT9_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT9_CNT9_SHIFT (0UL)




typedef uint32_t ISP_DG_LINE_CNT10_TYPE;
#define ISP_DG_LINE_CNT10_CNT10_MASK (0xffffffffUL)
#define ISP_DG_LINE_CNT10_CNT10_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT0_TYPE;
#define ISP_DG_PIXEL_CNT0_CNT0_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT0_CNT0_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT1_TYPE;
#define ISP_DG_PIXEL_CNT1_CNT1_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT1_CNT1_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT2_TYPE;
#define ISP_DG_PIXEL_CNT2_CNT2_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT2_CNT2_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT3_TYPE;
#define ISP_DG_PIXEL_CNT3_CNT3_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT3_CNT3_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT4_TYPE;
#define ISP_DG_PIXEL_CNT4_CNT4_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT4_CNT4_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT5_TYPE;
#define ISP_DG_PIXEL_CNT5_CNT5_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT5_CNT5_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT6_TYPE;
#define ISP_DG_PIXEL_CNT6_CNT6_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT6_CNT6_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT7_TYPE;
#define ISP_DG_PIXEL_CNT7_CNT7_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT7_CNT7_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT8_TYPE;
#define ISP_DG_PIXEL_CNT8_CNT8_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT8_CNT8_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT9_TYPE;
#define ISP_DG_PIXEL_CNT9_CNT9_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT9_CNT9_SHIFT (0UL)




typedef uint32_t ISP_DG_PIXEL_CNT10_TYPE;
#define ISP_DG_PIXEL_CNT10_CNT10_MASK (0xffffffffUL)
#define ISP_DG_PIXEL_CNT10_CNT10_SHIFT (0UL)




typedef uint32_t ISP_DG_TILE_NUM_TYPE;
#define ISP_DG_TILE_NUM_NUM_MASK (0xffffffffUL)
#define ISP_DG_TILE_NUM_NUM_SHIFT (0UL)




typedef uint32_t ISP_DG_STALL_TYPE;
#define ISP_DG_STALL_STALL_MASK (0xffffffffUL)
#define ISP_DG_STALL_STALL_SHIFT (0UL)




typedef uint32_t ISP_DG_MASTERS_TYPE;
#define ISP_DG_MASTERS_MASTERS_MASK (0xffffffffUL)
#define ISP_DG_MASTERS_MASTERS_SHIFT (0UL)




typedef uint32_t ISP_DG_DONE_CNT0_TYPE;
#define ISP_DG_DONE_CNT0_CNT0_MASK (0xffffffffUL)
#define ISP_DG_DONE_CNT0_CNT0_SHIFT (0UL)




typedef uint32_t ISP_DG_EOT_CNT1_TYPE;
#define ISP_DG_EOT_CNT1_CNT1_MASK (0xffffffffUL)
#define ISP_DG_EOT_CNT1_CNT1_SHIFT (0UL)




typedef uint32_t ISP_DG_ACK_CNT0_TYPE;
#define ISP_DG_ACK_CNT0_CNT0_MASK (0xffffffffUL)
#define ISP_DG_ACK_CNT0_CNT0_SHIFT (0UL)




typedef uint32_t ISP_DG_EOT_CNT0_TYPE;
#define ISP_DG_EOT_CNT0_CNT0_MASK (0xffffffffUL)
#define ISP_DG_EOT_CNT0_CNT0_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_IDLE0_TYPE;
#define ISP_DG_UTIL_IDLE0_IDLE0_MASK (0xffffffffUL)
#define ISP_DG_UTIL_IDLE0_IDLE0_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_STALL0_TYPE;
#define ISP_DG_UTIL_STALL0_STALL0_MASK (0xffffffffUL)
#define ISP_DG_UTIL_STALL0_STALL0_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_TRANS0_TYPE;
#define ISP_DG_UTIL_TRANS0_TRANS0_MASK (0xffffffffUL)
#define ISP_DG_UTIL_TRANS0_TRANS0_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_IDLE1_TYPE;
#define ISP_DG_UTIL_IDLE1_IDLE1_MASK (0xffffffffUL)
#define ISP_DG_UTIL_IDLE1_IDLE1_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_STALL1_TYPE;
#define ISP_DG_UTIL_STALL1_STALL1_MASK (0xffffffffUL)
#define ISP_DG_UTIL_STALL1_STALL1_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_TRANS1_TYPE;
#define ISP_DG_UTIL_TRANS1_TRANS1_MASK (0xffffffffUL)
#define ISP_DG_UTIL_TRANS1_TRANS1_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_IDLE2_TYPE;
#define ISP_DG_UTIL_IDLE2_IDLE2_MASK (0xffffffffUL)
#define ISP_DG_UTIL_IDLE2_IDLE2_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_STALL2_TYPE;
#define ISP_DG_UTIL_STALL2_STALL2_MASK (0xffffffffUL)
#define ISP_DG_UTIL_STALL2_STALL2_SHIFT (0UL)




typedef uint32_t ISP_DG_UTIL_TRANS2_TYPE;
#define ISP_DG_UTIL_TRANS2_TRANS2_MASK (0xffffffffUL)
#define ISP_DG_UTIL_TRANS2_TRANS2_SHIFT (0UL)




typedef uint32_t ISP_DG_ERROR_TYPE;
#define ISP_DG_ERROR_ERROR_MASK (0xffffffffUL)
#define ISP_DG_ERROR_ERROR_SHIFT (0UL)




typedef uint32_t ISP_DG_TCB_SEL_TYPE;
#define ISP_DG_TCB_SEL_SEL_MASK (0xffffffffUL)
#define ISP_DG_TCB_SEL_SEL_SHIFT (0UL)




typedef uint32_t ISP_DG_TCB_DATA_TYPE;
#define ISP_DG_TCB_DATA_DATA_MASK (0xffffffffUL)
#define ISP_DG_TCB_DATA_DATA_SHIFT (0UL)




typedef uint32_t ISP_DG_AXI_CONFIG_TYPE;
#define ISP_DG_AXI_CONFIG_CONFIG_MASK (0xffffffffUL)
#define ISP_DG_AXI_CONFIG_CONFIG_SHIFT (0UL)




typedef uint32_t ISP_DG_TCB_MASTER_TYPE;
#define ISP_DG_TCB_MASTER_MASTER_MASK (0xffffffffUL)
#define ISP_DG_TCB_MASTER_MASTER_SHIFT (0UL)




typedef uint32_t ISP_DG_CFG_ACCESS_TYPE;
#define ISP_DG_CFG_ACCESS_ACCESS_MASK (0xffffffffUL)
#define ISP_DG_CFG_ACCESS_ACCESS_SHIFT (0UL)




typedef uint64_t ISP_LS_CV_TYPE;
#define ISP_LS_CV_GB_MASK (0xfff0000000000000ULL)
#define ISP_LS_CV_GB_SHIFT (52ULL)
#define ISP_LS_CV_B_MASK (0xfff000000000ULL)
#define ISP_LS_CV_B_SHIFT (36ULL)
#define ISP_LS_CV_GR_MASK (0xfff00000ULL)
#define ISP_LS_CV_GR_SHIFT (20ULL)
#define ISP_LS_CV_R_MASK (0xfff0ULL)
#define ISP_LS_CV_R_SHIFT (4ULL)




typedef uint32_t ISP_GM_SLOPE_R_TYPE;
#define ISP_GM_SLOPE_R_SLOPE_MASK (0x1ffffUL)
#define ISP_GM_SLOPE_R_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_GM_SLOPE_G_TYPE;
#define ISP_GM_SLOPE_G_SLOPE_MASK (0x1ffffUL)
#define ISP_GM_SLOPE_G_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_GM_SLOPE_B_TYPE;
#define ISP_GM_SLOPE_B_SLOPE_MASK (0x1ffffUL)
#define ISP_GM_SLOPE_B_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_TM_Y_ABSC_TYPE;
#define ISP_TM_Y_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_TM_Y_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_TM_Y_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_TM_Y_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_CP_CB_ABSC_TYPE;
#define ISP_CP_CB_ABSC_ABSCISSA0_MASK (0x1ffffUL)
#define ISP_CP_CB_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_CP_CR_ABSC_TYPE;
#define ISP_CP_CR_ABSC_ABSCISSA0_MASK (0x1ffffUL)
#define ISP_CP_CR_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_TM_SHIFT_TYPE;
#define ISP_TM_SHIFT_SHIFT_MASK (0x1UL)
#define ISP_TM_SHIFT_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_CP_SHIFT_TYPE;
#define ISP_CP_SHIFT_SHIFT_MASK (0x1UL)
#define ISP_CP_SHIFT_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_CP_CB_ORD_SLOPE_TYPE;
#define ISP_CP_CB_ORD_SLOPE_ORDINATE_MASK (0xffff0000UL)
#define ISP_CP_CB_ORD_SLOPE_ORDINATE_SHIFT (16UL)
#define ISP_CP_CB_ORD_SLOPE_SLOPE_MASK (0xffffUL)
#define ISP_CP_CB_ORD_SLOPE_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_CP_CR_ORD_SLOPE_TYPE;
#define ISP_CP_CR_ORD_SLOPE_ORDINATE_MASK (0xffff0000UL)
#define ISP_CP_CR_ORD_SLOPE_ORDINATE_SHIFT (16UL)
#define ISP_CP_CR_ORD_SLOPE_SLOPE_MASK (0xffffUL)
#define ISP_CP_CR_ORD_SLOPE_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_TM_Y_ORD_SLOPE_TYPE;
#define ISP_TM_Y_ORD_SLOPE_ORDINATE_MASK (0xffff0000UL)
#define ISP_TM_Y_ORD_SLOPE_ORDINATE_SHIFT (16UL)
#define ISP_TM_Y_ORD_SLOPE_SLOPE_MASK (0xffffUL)
#define ISP_TM_Y_ORD_SLOPE_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_SH_VGAIN_ABSC_TYPE;
#define ISP_SH_VGAIN_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_SH_VGAIN_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_SH_VGAIN_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_SH_VGAIN_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_SH_VGAIN_ORD_TYPE;
#define ISP_SH_VGAIN_ORD_ORDINATE1_MASK (0xffff0000UL)
#define ISP_SH_VGAIN_ORD_ORDINATE1_SHIFT (16UL)
#define ISP_SH_VGAIN_ORD_ORDINATE0_MASK (0xffffUL)
#define ISP_SH_VGAIN_ORD_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_SH_VGAIN_SLOPE_TYPE;
#define ISP_SH_VGAIN_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_SH_VGAIN_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_SH_VGAIN_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_SH_VGAIN_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_SH_POSGAIN_ABSC_TYPE;
#define ISP_SH_POSGAIN_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_SH_POSGAIN_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_SH_POSGAIN_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_SH_POSGAIN_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_SH_POSGAIN_ORD_TYPE;
#define ISP_SH_POSGAIN_ORD_ORDINATE1_MASK (0xffff0000UL)
#define ISP_SH_POSGAIN_ORD_ORDINATE1_SHIFT (16UL)
#define ISP_SH_POSGAIN_ORD_ORDINATE0_MASK (0xffffUL)
#define ISP_SH_POSGAIN_ORD_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_SH_POSGAIN_SLOPE_TYPE;
#define ISP_SH_POSGAIN_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_SH_POSGAIN_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_SH_POSGAIN_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_SH_POSGAIN_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESPGAIN_ABSC_TYPE;
#define ISP_SH_RESPGAIN_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_SH_RESPGAIN_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_SH_RESPGAIN_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_SH_RESPGAIN_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESPGAIN_ORD_TYPE;
#define ISP_SH_RESPGAIN_ORD_ORDINATE1_MASK (0xffff0000UL)
#define ISP_SH_RESPGAIN_ORD_ORDINATE1_SHIFT (16UL)
#define ISP_SH_RESPGAIN_ORD_ORDINATE0_MASK (0xffffUL)
#define ISP_SH_RESPGAIN_ORD_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESPGAIN_SLOPE_TYPE;
#define ISP_SH_RESPGAIN_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_SH_RESPGAIN_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_SH_RESPGAIN_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_SH_RESPGAIN_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESP_ABSC_TYPE;
#define ISP_SH_RESP_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_SH_RESP_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_SH_RESP_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_SH_RESP_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESP_ORD_TYPE;
#define ISP_SH_RESP_ORD_ORDINATE1_MASK (0xffff0000UL)
#define ISP_SH_RESP_ORD_ORDINATE1_SHIFT (16UL)
#define ISP_SH_RESP_ORD_ORDINATE0_MASK (0xffffUL)
#define ISP_SH_RESP_ORD_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESP_SLOPE_TYPE;
#define ISP_SH_RESP_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_SH_RESP_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_SH_RESP_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_SH_RESP_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESP1_ABSC_TYPE;
#define ISP_SH_RESP1_ABSC_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_SH_RESP1_ABSC_ABSCISSA1_SHIFT (16UL)
#define ISP_SH_RESP1_ABSC_ABSCISSA0_MASK (0xffffUL)
#define ISP_SH_RESP1_ABSC_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESP1_ORD_TYPE;
#define ISP_SH_RESP1_ORD_ORDINATE1_MASK (0xffff0000UL)
#define ISP_SH_RESP1_ORD_ORDINATE1_SHIFT (16UL)
#define ISP_SH_RESP1_ORD_ORDINATE0_MASK (0xffffUL)
#define ISP_SH_RESP1_ORD_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_SH_RESP1_SLOPE_TYPE;
#define ISP_SH_RESP1_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_SH_RESP1_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_SH_RESP1_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_SH_RESP1_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_GM_ORD_R_TYPE;
#define ISP_GM_ORD_R_ORDINATE1_MASK (0xffff0000UL)
#define ISP_GM_ORD_R_ORDINATE1_SHIFT (16UL)
#define ISP_GM_ORD_R_ORDINATE0_MASK (0xffffUL)
#define ISP_GM_ORD_R_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_GM_ORD_G_TYPE;
#define ISP_GM_ORD_G_ORDINATE1_MASK (0xffff0000UL)
#define ISP_GM_ORD_G_ORDINATE1_SHIFT (16UL)
#define ISP_GM_ORD_G_ORDINATE0_MASK (0xffffUL)
#define ISP_GM_ORD_G_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_GM_ORD_B_TYPE;
#define ISP_GM_ORD_B_ORDINATE1_MASK (0xffff0000UL)
#define ISP_GM_ORD_B_ORDINATE1_SHIFT (16UL)
#define ISP_GM_ORD_B_ORDINATE0_MASK (0xffffUL)
#define ISP_GM_ORD_B_ORDINATE0_SHIFT (0UL)




typedef uint32_t ISP_BL1_ABSC_RN_TYPE;
#define ISP_BL1_ABSC_RN_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL1_ABSC_RN_ABSCISSA1_SHIFT (16UL)
#define ISP_BL1_ABSC_RN_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL1_ABSC_RN_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL1_ABSC_GRN_TYPE;
#define ISP_BL1_ABSC_GRN_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL1_ABSC_GRN_ABSCISSA1_SHIFT (16UL)
#define ISP_BL1_ABSC_GRN_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL1_ABSC_GRN_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL1_ABSC_BN_TYPE;
#define ISP_BL1_ABSC_BN_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL1_ABSC_BN_ABSCISSA1_SHIFT (16UL)
#define ISP_BL1_ABSC_BN_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL1_ABSC_BN_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL1_ORD_SLOPE_RN_TYPE;
#define ISP_BL1_ORD_SLOPE_RN_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL1_ORD_SLOPE_RN_ORDINATE_SHIFT (16UL)
#define ISP_BL1_ORD_SLOPE_RN_SLOPE_MASK (0xffffUL)
#define ISP_BL1_ORD_SLOPE_RN_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_BL1_ORD_SLOPE_GRN_TYPE;
#define ISP_BL1_ORD_SLOPE_GRN_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL1_ORD_SLOPE_GRN_ORDINATE_SHIFT (16UL)
#define ISP_BL1_ORD_SLOPE_GRN_SLOPE_MASK (0xffffUL)
#define ISP_BL1_ORD_SLOPE_GRN_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_BL1_ORD_SLOPE_BN_TYPE;
#define ISP_BL1_ORD_SLOPE_BN_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL1_ORD_SLOPE_BN_ORDINATE_SHIFT (16UL)
#define ISP_BL1_ORD_SLOPE_BN_SLOPE_MASK (0xffffUL)
#define ISP_BL1_ORD_SLOPE_BN_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_LTM_KHP_TYPE;
#define ISP_LTM_KHP_KHP_MASK (0xffUL)
#define ISP_LTM_KHP_KHP_SHIFT (0UL)




typedef uint32_t ISP_LTM_KCOLOR_TYPE;
#define ISP_LTM_KCOLOR_KCOLOR_MASK (0xffUL)
#define ISP_LTM_KCOLOR_KCOLOR_SHIFT (0UL)




typedef uint32_t ISP_LTM_GF_CTRL_TYPE;
#define ISP_LTM_GF_CTRL_EPSILON_MASK (0xffff0000UL)
#define ISP_LTM_GF_CTRL_EPSILON_SHIFT (16UL)
#define ISP_LTM_GF_CTRL_EN_GF_MASK (0x1UL)
#define ISP_LTM_GF_CTRL_EN_GF_SHIFT (0UL)




typedef uint32_t ISP_LTM_DIV_SAT_TYPE;
#define ISP_LTM_DIV_SAT_SAT_MASK (0xffffffffUL)
#define ISP_LTM_DIV_SAT_SAT_SHIFT (0UL)




typedef uint32_t ISP_LTM_GKER_COEFF_TYPE;
#define ISP_LTM_GKER_COEFF_COEFF_MASK (0x3ffffUL)
#define ISP_LTM_GKER_COEFF_COEFF_SHIFT (0UL)




typedef uint32_t ISP_LTM_SHIFT_BGM_TYPE;
#define ISP_LTM_SHIFT_BGM_SHIFT_MASK (0x1UL)
#define ISP_LTM_SHIFT_BGM_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_LTM_SHIFT_DGM_G_TYPE;
#define ISP_LTM_SHIFT_DGM_G_SHIFT_MASK (0x1UL)
#define ISP_LTM_SHIFT_DGM_G_SHIFT_SHIFT (0UL)




typedef uint32_t ISP_LTM_BGM_ABSC_TYPE;
#define ISP_LTM_BGM_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_LTM_BGM_ABSC_ABSC1_SHIFT (16UL)
#define ISP_LTM_BGM_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_LTM_BGM_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_LTM_DGM_G_ABSC_TYPE;
#define ISP_LTM_DGM_G_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_LTM_DGM_G_ABSC_ABSC1_SHIFT (16UL)
#define ISP_LTM_DGM_G_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_LTM_DGM_G_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_LTM_BGM_ORD_SLOPE_TYPE;
#define ISP_LTM_BGM_ORD_SLOPE_ORD_MASK (0xffff0000UL)
#define ISP_LTM_BGM_ORD_SLOPE_ORD_SHIFT (16UL)
#define ISP_LTM_BGM_ORD_SLOPE_SLOPE_MASK (0xffffUL)
#define ISP_LTM_BGM_ORD_SLOPE_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_LTM_DGM_G_ORD_SLOPE_TYPE;
#define ISP_LTM_DGM_G_ORD_SLOPE_ORD_MASK (0xffff0000UL)
#define ISP_LTM_DGM_G_ORD_SLOPE_ORD_SHIFT (16UL)
#define ISP_LTM_DGM_G_ORD_SLOPE_SLOPE_MASK (0xffffUL)
#define ISP_LTM_DGM_G_ORD_SLOPE_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_BL1_ABSC_GB_TYPE;
#define ISP_BL1_ABSC_GB_ABSCISSA1_MASK (0xffff0000UL)
#define ISP_BL1_ABSC_GB_ABSCISSA1_SHIFT (16UL)
#define ISP_BL1_ABSC_GB_ABSCISSA0_MASK (0xffffUL)
#define ISP_BL1_ABSC_GB_ABSCISSA0_SHIFT (0UL)




typedef uint32_t ISP_BL1_ORD_SLOPE_GB_TYPE;
#define ISP_BL1_ORD_SLOPE_GB_ORDINATE_MASK (0xffff0000UL)
#define ISP_BL1_ORD_SLOPE_GB_ORDINATE_SHIFT (16UL)
#define ISP_BL1_ORD_SLOPE_GB_SLOPE_MASK (0xffffUL)
#define ISP_BL1_ORD_SLOPE_GB_SLOPE_SHIFT (0UL)




typedef uint32_t ISP_CD_FIR_BG_ABSC_TYPE;
#define ISP_CD_FIR_BG_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_FIR_BG_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_FIR_BG_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_FIR_BG_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_FIR_BG_ORD_TYPE;
#define ISP_CD_FIR_BG_ORD_ORD1_MASK (0x3f0000UL)
#define ISP_CD_FIR_BG_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_FIR_BG_ORD_ABSC0_MASK (0x3fUL)
#define ISP_CD_FIR_BG_ORD_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_FIR_BG_SLOPE_TYPE;
#define ISP_CD_FIR_BG_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_CD_FIR_BG_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_CD_FIR_BG_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_CD_FIR_BG_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_CD_FIR_RG_ABSC_TYPE;
#define ISP_CD_FIR_RG_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_FIR_RG_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_FIR_RG_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_FIR_RG_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_FIR_RG_ORD_TYPE;
#define ISP_CD_FIR_RG_ORD_ORD1_MASK (0x3f0000UL)
#define ISP_CD_FIR_RG_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_FIR_RG_ORD_ABSC0_MASK (0x3fUL)
#define ISP_CD_FIR_RG_ORD_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_FIR_RG_SLOPE_TYPE;
#define ISP_CD_FIR_RG_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_CD_FIR_RG_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_CD_FIR_RG_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_CD_FIR_RG_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_CD_IIR_BG_ABSC_TYPE;
#define ISP_CD_IIR_BG_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_IIR_BG_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_IIR_BG_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_IIR_BG_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_IIR_BG_ORD_TYPE;
#define ISP_CD_IIR_BG_ORD_ORD1_MASK (0xff0000UL)
#define ISP_CD_IIR_BG_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_IIR_BG_ORD_ABSC0_MASK (0xffUL)
#define ISP_CD_IIR_BG_ORD_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_IIR_BG_SLOPE_TYPE;
#define ISP_CD_IIR_BG_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_CD_IIR_BG_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_CD_IIR_BG_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_CD_IIR_BG_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_CD_IIR_RG_ABSC_TYPE;
#define ISP_CD_IIR_RG_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_IIR_RG_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_IIR_RG_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_IIR_RG_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_IIR_RG_ORD_TYPE;
#define ISP_CD_IIR_RG_ORD_ORD1_MASK (0xff0000UL)
#define ISP_CD_IIR_RG_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_IIR_RG_ORD_ABSC0_MASK (0xffUL)
#define ISP_CD_IIR_RG_ORD_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_IIR_RG_SLOPE_TYPE;
#define ISP_CD_IIR_RG_SLOPE_SLOPE1_MASK (0xffff0000UL)
#define ISP_CD_IIR_RG_SLOPE_SLOPE1_SHIFT (16UL)
#define ISP_CD_IIR_RG_SLOPE_SLOPE0_MASK (0xffffUL)
#define ISP_CD_IIR_RG_SLOPE_SLOPE0_SHIFT (0UL)




typedef uint32_t ISP_CD_WGHTS_TYPE;
#define ISP_CD_WGHTS_RG_WT_MASK (0xf0000UL)
#define ISP_CD_WGHTS_RG_WT_SHIFT (16UL)
#define ISP_CD_WGHTS_BG_WT_MASK (0xf00UL)
#define ISP_CD_WGHTS_BG_WT_SHIFT (8UL)
#define ISP_CD_WGHTS_G_WT_MASK (0xfUL)
#define ISP_CD_WGHTS_G_WT_SHIFT (0UL)




typedef uint32_t ISP_CD_DIST_ABSC_TYPE;
#define ISP_CD_DIST_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_DIST_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_DIST_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_DIST_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_DIST_ORD_TYPE;
#define ISP_CD_DIST_ORD_ORD1_MASK (0xff0000UL)
#define ISP_CD_DIST_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_DIST_ORD_ORD0_MASK (0xffUL)
#define ISP_CD_DIST_ORD_ORD0_SHIFT (0UL)




typedef uint32_t ISP_CD_DIST_SLOPE_TYPE;
#define ISP_CD_DIST_SLOPE_ORD1_MASK (0xffff0000UL)
#define ISP_CD_DIST_SLOPE_ORD1_SHIFT (16UL)
#define ISP_CD_DIST_SLOPE_ORD0_MASK (0xffffUL)
#define ISP_CD_DIST_SLOPE_ORD0_SHIFT (0UL)




typedef uint32_t ISP_CD_G_ABSC_TYPE;
#define ISP_CD_G_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_G_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_G_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_G_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_G_ORD_TYPE;
#define ISP_CD_G_ORD_ORD1_MASK (0x3f0000UL)
#define ISP_CD_G_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_G_ORD_ORD0_MASK (0x3fUL)
#define ISP_CD_G_ORD_ORD0_SHIFT (0UL)




typedef uint32_t ISP_CD_G_SLOPE_TYPE;
#define ISP_CD_G_SLOPE_ORD1_MASK (0xffff0000UL)
#define ISP_CD_G_SLOPE_ORD1_SHIFT (16UL)
#define ISP_CD_G_SLOPE_ORD0_MASK (0xffffUL)
#define ISP_CD_G_SLOPE_ORD0_SHIFT (0UL)




typedef uint32_t ISP_CD_SAT_ABSC_TYPE;
#define ISP_CD_SAT_ABSC_ABSC1_MASK (0xffff0000UL)
#define ISP_CD_SAT_ABSC_ABSC1_SHIFT (16UL)
#define ISP_CD_SAT_ABSC_ABSC0_MASK (0xffffUL)
#define ISP_CD_SAT_ABSC_ABSC0_SHIFT (0UL)




typedef uint32_t ISP_CD_SAT_ORD_TYPE;
#define ISP_CD_SAT_ORD_ORD1_MASK (0x7f0000UL)
#define ISP_CD_SAT_ORD_ORD1_SHIFT (16UL)
#define ISP_CD_SAT_ORD_ORD0_MASK (0x7fUL)
#define ISP_CD_SAT_ORD_ORD0_SHIFT (0UL)




typedef uint32_t ISP_CD_SAT_SLOPE_TYPE;
#define ISP_CD_SAT_SLOPE_ORD1_MASK (0xffff0000UL)
#define ISP_CD_SAT_SLOPE_ORD1_SHIFT (16UL)
#define ISP_CD_SAT_SLOPE_ORD0_MASK (0xffffUL)
#define ISP_CD_SAT_SLOPE_ORD0_SHIFT (0UL)




typedef uint32_t ISP_CD_CENTRE_TYPE;
#define ISP_CD_CENTRE_X_CENTRE_MASK (0xffff0000UL)
#define ISP_CD_CENTRE_X_CENTRE_SHIFT (16UL)
#define ISP_CD_CENTRE_Y_CENTRE_MASK (0xffffUL)
#define ISP_CD_CENTRE_Y_CENTRE_SHIFT (0UL)




typedef uint32_t ISP_CD_MISC_TYPE;
#define ISP_CD_MISC_FIR_SHIFT_MASK (0x30000UL)
#define ISP_CD_MISC_FIR_SHIFT_SHIFT (16UL)
#define ISP_CD_MISC_IIR_ATTEN_SHIFT_MASK (0x700UL)
#define ISP_CD_MISC_IIR_ATTEN_SHIFT_SHIFT (8UL)
#define ISP_CD_MISC_IIR_ATTEN_LINES_MASK (0xfUL)
#define ISP_CD_MISC_IIR_ATTEN_LINES_SHIFT (0UL)




typedef uint32_t ISP_CD_EDGE_THRESH_TYPE;
#define ISP_CD_EDGE_THRESH_THRESH_MASK (0xffffUL)
#define ISP_CD_EDGE_THRESH_THRESH_SHIFT (0UL)




typedef uint32_t ISP_CD_EDGE_STRENGTH_MIN_TYPE;
#define ISP_CD_EDGE_STRENGTH_MIN_MIN_MASK (0xffff0000UL)
#define ISP_CD_EDGE_STRENGTH_MIN_MIN_SHIFT (16UL)
#define ISP_CD_EDGE_STRENGTH_MIN_STRENGTH_MASK (0xffffUL)
#define ISP_CD_EDGE_STRENGTH_MIN_STRENGTH_SHIFT (0UL)




typedef volatile struct COMP_PACKED _ISP_RDBType {
    ISP_CTRL_TYPE ctrl; /* OFFSET: 0x0 */
    ISP_STATUS_TYPE status; /* OFFSET: 0x4 */
    ISP_ID_TYPE id; /* OFFSET: 0x8 */
    ISP_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0xc */
    ISP_TILE_CTRL_TYPE tile_ctrl; /* OFFSET: 0x10 */
    ISP_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x14 */
    ISP_TILE_STATUS_TYPE tile_status; /* OFFSET: 0x18 */
    ISP_TILE_ADDR_TYPE tile_addr; /* OFFSET: 0x1c */
    ISP_LEGACY_CTRL_TYPE legacy_ctrl; /* OFFSET: 0x20 */
    ISP_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x24 */
    ISP_FR_SIZE_TYPE fr_size; /* OFFSET: 0x30 */
    ISP_FR_CTRL_TYPE fr_ctrl; /* OFFSET: 0x34 */
    ISP_FR_BAYER_EN_TYPE fr_bayer_en; /* OFFSET: 0x38 */
    ISP_FR_YCBCR_EN_TYPE fr_ycbcr_en; /* OFFSET: 0x3c */
    ISP_RESERVED_TYPE rsvd3[16]; /* OFFSET: 0x40 */
    ISP_FR_MOSAIC_TYPE fr_mosaic; /* OFFSET: 0x50 */
    ISP_RESERVED_TYPE rsvd4[60]; /* OFFSET: 0x54 */
    ISP_WG_RED_TYPE wg_red; /* OFFSET: 0x90 */
    ISP_WG_BLUE_TYPE wg_blue; /* OFFSET: 0x94 */
    ISP_WG_OFFSETG_TYPE wg_offsetg; /* OFFSET: 0x98 */
    ISP_WG_GAIN_TYPE wg_gain; /* OFFSET: 0x9c */
    ISP_WG_THRESH_TYPE wg_thresh; /* OFFSET: 0xa0 */
    ISP_WG_OFFSETR_TYPE wg_offsetr; /* OFFSET: 0xa4 */
    ISP_WG_OFFSETB_TYPE wg_offsetb; /* OFFSET: 0xa8 */
    ISP_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0xac */
    ISP_YG_MATRIX0_TYPE yg_matrix[5]; /* OFFSET: 0xb0 */
    ISP_YG_OFFSET0_TYPE yg_offset0; /* OFFSET: 0xc4 */
    ISP_YG_OFFSET1_TYPE yg_offset1; /* OFFSET: 0xc8 */
    ISP_YG_OFFSET2_TYPE yg_offset2; /* OFFSET: 0xcc */
    ISP_RESERVED_TYPE rsvd6[48]; /* OFFSET: 0xd0 */
    ISP_II_CTRL_TYPE ii_ctrl; /* OFFSET: 0x100 */
    ISP_II_ADDRESS_TYPE ii_address; /* OFFSET: 0x104 */
    ISP_II_ENDADDR_TYPE ii_endaddr; /* OFFSET: 0x108 */
    ISP_II_DPCM_TYPE ii_dpcm; /* OFFSET: 0x10c */
    ISP_II_FIFO_TYPE ii_fifo; /* OFFSET: 0x110 */
    ISP_RESERVED_TYPE rsvd7[28]; /* OFFSET: 0x114 */
    ISP_DI_ADDRESS_TYPE di_address; /* OFFSET: 0x130 */
    ISP_DI_ENDADDR_TYPE di_endaddr; /* OFFSET: 0x134 */
    ISP_RESERVED_TYPE rsvd8[8]; /* OFFSET: 0x138 */
    ISP_BL_LVL_R_TYPE bl_lvl_r; /* OFFSET: 0x140 */
    ISP_BL_LVL_GR_TYPE bl_lvl_gr; /* OFFSET: 0x144 */
    ISP_BL_LVL_B_TYPE bl_lvl_b; /* OFFSET: 0x148 */
    ISP_BL_LVL_GB_TYPE bl_lvl_gb; /* OFFSET: 0x14c */
    ISP_BL1_LVL_R_TYPE bl1_lvl_r; /* OFFSET: 0x150 */
    ISP_BL1_LVL_GR_TYPE bl1_lvl_gr; /* OFFSET: 0x154 */
    ISP_BL1_LVL_B_TYPE bl1_lvl_b; /* OFFSET: 0x158 */
    ISP_BL1_LVL_GB_TYPE bl1_lvl_gb; /* OFFSET: 0x15c */
    ISP_BL_ABSC_RN_TYPE bl_absc_r[8]; /* OFFSET: 0x160 */
    ISP_BL_ABSC_GRN_TYPE bl_absc_gr[8]; /* OFFSET: 0x180 */
    ISP_BL_ABSC_BN_TYPE bl_absc_b[8]; /* OFFSET: 0x1a0 */
    ISP_BL_ORD_SLOPE_RN_TYPE bl_ord_slope_r[16]; /* OFFSET: 0x1c0 */
    ISP_BL_ORD_SLOPE_GRN_TYPE bl_ord_slope_gr[16]; /* OFFSET: 0x200 */
    ISP_BL_ORD_SLOPE_BN_TYPE bl_ord_slope_b[16]; /* OFFSET: 0x240 */
    ISP_BL_TB_TYPE bl_tb; /* OFFSET: 0x280 */
    ISP_BL_LR_TYPE bl_lr; /* OFFSET: 0x284 */
    ISP_BL_MT_TYPE bl_mt; /* OFFSET: 0x288 */
    ISP_BL_SHIFT_TYPE bl_shift; /* OFFSET: 0x28c */
    ISP_BL_SUM_LO_TYPE bl_sum_lo; /* OFFSET: 0x290 */
    ISP_BL_SUM_HI_TYPE bl_sum_hi; /* OFFSET: 0x294 */
    ISP_BL_COUNT_TYPE bl_count; /* OFFSET: 0x298 */
    ISP_BL1_MT_TYPE bl1_mt; /* OFFSET: 0x29c */
    ISP_BL1_SUM_LO_TYPE bl1_sum_lo; /* OFFSET: 0x2a0 */
    ISP_BL1_SUM_HI_TYPE bl1_sum_hi; /* OFFSET: 0x2a4 */
    ISP_BL1_COUNT_TYPE bl1_count; /* OFFSET: 0x2a8 */
    ISP_BL1_SHIFT_TYPE bl1_shift; /* OFFSET: 0x2ac */
    ISP_RESERVED_TYPE rsvd9[32]; /* OFFSET: 0x2b0 */
    ISP_DP_HI_TYPE dp_hi[3]; /* OFFSET: 0x2d0 */
    ISP_DP_LO_TYPE dp_lo[3]; /* OFFSET: 0x2dc */
    ISP_DP_REPLO_TYPE dp_replo; /* OFFSET: 0x2e8 */
    ISP_DP_REPHI_TYPE dp_rephi; /* OFFSET: 0x2ec */
    ISP_RESERVED_TYPE rsvd10[16]; /* OFFSET: 0x2f0 */
    ISP_BL_ABSC_GB_TYPE bl_absc_gb[8]; /* OFFSET: 0x300 */
    ISP_RESERVED_TYPE rsvd11[32]; /* OFFSET: 0x320 */
    ISP_BL_ORD_SLOPE_GB_TYPE bl_ord_slope_gb[16]; /* OFFSET: 0x340 */
    ISP_RESERVED_TYPE rsvd12[32]; /* OFFSET: 0x380 */
    ISP_HF_CTRL_TYPE hf_ctrl; /* OFFSET: 0x3a0 */
    ISP_HF_EXP_RATIO_TYPE isphf_exp_ratio; /* OFFSET: 0x3a4 */
    ISP_HF_THR_HI_TYPE isphf_thr_hi; /* OFFSET: 0x3a8 */
    ISP_HF_THR_LO_TYPE isphf_thr_lo; /* OFFSET: 0x3ac */
    ISP_HF_WT_SC_TYPE isphf_wt_sc; /* OFFSET: 0x3b0 */
    ISP_HF_WB_RG_TYPE isphf_wb_rg; /* OFFSET: 0x3b4 */
    ISP_HF_WB_BG_TYPE isphf_wb_bg; /* OFFSET: 0x3b8 */
    ISP_HF_WB_TH_TYPE isphf_wb_th; /* OFFSET: 0x3bc */
    ISP_HF_ABSC_TYPE isphf_absc[16]; /* OFFSET: 0x3c0 */
    ISP_HF_ORD_SLOPE_TYPE isphf_ord_slope[16]; /* OFFSET: 0x400 */
    ISP_TD_CTRL_TYPE td_ctrl; /* OFFSET: 0x440 */
    ISP_TD_STATUS_TYPE td_status; /* OFFSET: 0x444 */
    ISP_TD_ADDR_TYPE td_addr; /* OFFSET: 0x448 */
    ISP_TD_DESC_TYPE td_desc; /* OFFSET: 0x44c */
    ISP_TD_INIT0_TYPE td_init0; /* OFFSET: 0x46c */
    ISP_TD_INIT1_TYPE td_init1; /* OFFSET: 0x470 */
    ISP_TD_INIT2_TYPE td_init2; /* OFFSET: 0x474 */
    ISP_RESERVED_TYPE rsvd13[88]; /* OFFSET: 0x478 */
    ISP_LS_CTRL_TYPE ls_ctrl; /* OFFSET: 0x4d0 */
    ISP_LS_OFFSETS_TYPE ls_offsets; /* OFFSET: 0x4d4 */
    ISP_RESERVED_TYPE rsvd14[40]; /* OFFSET: 0x4d8 */
    ISP_XC_ABSC_LIM_TYPE xc_absc_lim[4]; /* OFFSET: 0x500 */
    ISP_XC_ORD_LIM_TYPE xc_ord_lim[4]; /* OFFSET: 0x510 */
    ISP_XC_SLOPE_LIM_TYPE xc_slope_lim[4]; /* OFFSET: 0x520 */
    ISP_RESERVED_TYPE rsvd15[32]; /* OFFSET: 0x530 */
    ISP_FG_R_POS_TYPE fg_r_pos; /* OFFSET: 0x550 */
    ISP_FG_R_NEG_TYPE fg_r_neg; /* OFFSET: 0x554 */
    ISP_FG_GR_POS_TYPE fg_gr_pos; /* OFFSET: 0x558 */
    ISP_FG_GR_NEG_TYPE fg_gr_neg; /* OFFSET: 0x55c */
    ISP_FG_B_POS_TYPE fg_b_pos; /* OFFSET: 0x560 */
    ISP_FG_B_NEG_TYPE fg_b_neg; /* OFFSET: 0x564 */
    ISP_FG_GB_POS_TYPE fg_gb_pos; /* OFFSET: 0x568 */
    ISP_FG_GB_NEG_TYPE fg_gb_neg; /* OFFSET: 0x56c */
    ISP_RESERVED_TYPE rsvd16[16]; /* OFFSET: 0x570 */
    ISP_DN_CTRL_TYPE dn_ctrl; /* OFFSET: 0x580 */
    ISP_RESERVED_TYPE rsvd17[12]; /* OFFSET: 0x584 */
    ISP_DN_ABSC_TYPE dn_absc[6]; /* OFFSET: 0x590 */
    ISP_RESERVED_TYPE rsvd18[8]; /* OFFSET: 0x5a8 */
    ISP_DN_ORD_TYPE dn_ord[6]; /* OFFSET: 0x5b0 */
    ISP_RESERVED_TYPE rsvd19[8]; /* OFFSET: 0x5c8 */
    ISP_DN_SLOPE_TYPE dn_slope[6]; /* OFFSET: 0x5d0 */
    ISP_DN_MASK0_TYPE dn_mask0; /* OFFSET: 0x5e8 */
    ISP_DN_MASK1_TYPE dn_mask1; /* OFFSET: 0x5ec */
    ISP_DN_STRENGTH_TYPE dn_strength; /* OFFSET: 0x5f0 */
    ISP_DN_THRGAIN_TYPE dn_thrgain; /* OFFSET: 0x5f4 */
    ISP_RESERVED_TYPE rsvd20[216]; /* OFFSET: 0x5f8 */
    ISP_DM_CTRL_TYPE dm_ctrl; /* OFFSET: 0x6d0 */
    ISP_DM_THRESH_TYPE dm_thresh; /* OFFSET: 0x6d4 */
    ISP_RESERVED_TYPE rsvd21[40]; /* OFFSET: 0x6d8 */
    ISP_YI_CTRL_TYPE yi_ctrl; /* OFFSET: 0x700 */
    ISP_YI_RY_ADDR_TYPE yi_ry_addr; /* OFFSET: 0x704 */
    ISP_YI_GU_ADDR_TYPE yi_gu_addr; /* OFFSET: 0x708 */
    ISP_YI_BV_ADDR_TYPE yi_bv_addr; /* OFFSET: 0x70c */
    ISP_YI_STRIDE1_TYPE yi_stride1; /* OFFSET: 0x710 */
    ISP_YI_STRIDE2_TYPE yi_stride2; /* OFFSET: 0x714 */
    ISP_YI_COL_STRIDE1_TYPE yi_col_stride1; /* OFFSET: 0x718 */
    ISP_YI_COL_STRIDE2_TYPE yi_col_stride2; /* OFFSET: 0x71c */
    ISP_YI_RY_EADDR_TYPE yi_ry_eaddr; /* OFFSET: 0x720 */
    ISP_YI_GU_EADDR_TYPE yi_gu_eaddr; /* OFFSET: 0x724 */
    ISP_YI_BV_EADDR_TYPE yi_bv_eaddr; /* OFFSET: 0x728 */
    ISP_RESERVED_TYPE rsvd22[36]; /* OFFSET: 0x72c */
    ISP_YC_MATRIX_TYPE yc_matrix[5]; /* OFFSET: 0x750 */
    ISP_YC_OFFSET_TYPE yc_offset[3]; /* OFFSET: 0x764 */
    ISP_RESERVED_TYPE rsvd23[144]; /* OFFSET: 0x770 */
    ISP_GM_ABSC_R_TYPE gm_absc_r[16]; /* OFFSET: 0x800 */
    ISP_GM_ABSC_G_TYPE gm_absc_g[16]; /* OFFSET: 0x840 */
    ISP_GM_ABSC_B_TYPE gm_absc_b[16]; /* OFFSET: 0x880 */
    ISP_GM_SHIFT_TYPE gm_shift; /* OFFSET: 0x8c0 */
    ISP_RESERVED_TYPE rsvd24[172]; /* OFFSET: 0x8c4 */
    ISP_FC_STRENGTH_TYPE fc_strength; /* OFFSET: 0x970 */
    ISP_FC_FMIX_TYPE fc_fmix; /* OFFSET: 0x974 */
    ISP_FC_FMIX_THRESH_TYPE fc_fmix_thresh; /* OFFSET: 0x978 */
    ISP_FC_FMIX_NORM_TYPE fc_fmix_norm; /* OFFSET: 0x97c */
    ISP_FC_FDESAT_TYPE fc_fdesat; /* OFFSET: 0x980 */
    ISP_FC_FDESAT_THRESH_TYPE fc_fdesat_thresh; /* OFFSET: 0x984 */
    ISP_FC_FDESAT_NORM_TYPE fc_fdesat_norm; /* OFFSET: 0x988 */
    ISP_RESERVED_TYPE rsvd25[40]; /* OFFSET: 0x98c */
    ISP_SH_STRENGTH_TYPE sh_strength; /* OFFSET: 0x9b4 */
    ISP_SH_CENTRE_TYPE sh_centre; /* OFFSET: 0x9b8 */
    ISP_RESERVED_TYPE rsvd26[372]; /* OFFSET: 0x9bc */
    ISP_LR_TSCALEX_TYPE lr_tscalex; /* OFFSET: 0xb30 */
    ISP_LR_TSCALEY_TYPE lr_tscaley; /* OFFSET: 0xb34 */
    ISP_LR_NORM_0_1_TYPE lr_norm_0_1; /* OFFSET: 0xb38 */
    ISP_LR_NORM_2_3_TYPE lr_norm_2_3; /* OFFSET: 0xb3c */
    ISP_LR_SHIFT_TYPE lr_shift; /* OFFSET: 0xb40 */
    ISP_RESERVED_TYPE rsvd27[12]; /* OFFSET: 0xb44 */
    ISP_CC_MATRIX_TYPE cc_matrix[5]; /* OFFSET: 0xb50 */
    ISP_CC_OFFSET_TYPE cc_offset[3]; /* OFFSET: 0xb64 */
    ISP_RESERVED_TYPE rsvd28[16]; /* OFFSET: 0xb70 */
    ISP_ST_FOC_CTRL_TYPE st_foc_ctrl; /* OFFSET: 0xb80 */
    ISP_ST_FOC_FILTEX_TYPE st_foc_filtex[4]; /* OFFSET: 0xb84 */
    ISP_RESERVED_TYPE rsvd29[12]; /* OFFSET: 0xb94 */
    ISP_ST_SHIFT_TYPE st_shift; /* OFFSET: 0xba0 */
    ISP_ST_R_OFF_TYPE st_r_off[32]; /* OFFSET: 0xba4 */
    ISP_ST_R_RECT_TYPE st_r_rect[32]; /* OFFSET: 0xc24 */
    ISP_ST_HMASK0_TYPE st_hmask0; /* OFFSET: 0xca4 */
    ISP_RESERVED_TYPE rsvd30[4]; /* OFFSET: 0xca8 */
    ISP_ST_FOC_FILT_TYPE st_foc_filt[9]; /* OFFSET: 0xcac */
    ISP_ST_FILT_GAINS_TYPE st_filt_gains; /* OFFSET: 0xcd0 */
    ISP_ST_FILT_TH_TYPE st_filt_th; /* OFFSET: 0xcd4 */
    ISP_RESERVED_TYPE rsvd31[4]; /* OFFSET: 0xcd8 */
    ISP_ST_ROW_NUM_TYPE st_row_num; /* OFFSET: 0xcdc */
    ISP_ST_R_TH_TYPE st_r_th[3]; /* OFFSET: 0xce0 */
    ISP_ST_G_TH_TYPE st_g_th[3]; /* OFFSET: 0xcec */
    ISP_ST_B_TH_TYPE st_b_th[3]; /* OFFSET: 0xcf8 */
    ISP_ST_R_G_TH_TYPE st_r_g_th[3]; /* OFFSET: 0xd04 */
    ISP_ST_B_G_TH_TYPE st_b_g_th[3]; /* OFFSET: 0xd10 */
    ISP_ST_GROUP_0_X_TYPE st_group_0_x[9]; /* OFFSET: 0xd1c */
    ISP_ST_GROUP_0_Y_TYPE st_group_0_y[9]; /* OFFSET: 0xd40 */
    ISP_ST_GRP0_CTRL_TYPE st_grp0_ctrl; /* OFFSET: 0xd64 */
    ISP_ST_HGAIN0_TYPE st_hgain0; /* OFFSET: 0xd68 */
    ISP_ST_HGAIN1_TYPE st_hgain1; /* OFFSET: 0xd6c */
    ISP_HO_CTRL_TYPE ho_ctrl; /* OFFSET: 0xd70 */
    ISP_HO_COL_STRIDE1_TYPE ho_col_stride1; /* OFFSET: 0xd74 */
    ISP_HO_COL_STRIDE2_TYPE ho_col_stride2; /* OFFSET: 0xd78 */
    ISP_HO_ADDRESS1_TYPE ho_address1; /* OFFSET: 0xd7c */
    ISP_HO_ADDRESS2_TYPE ho_address2; /* OFFSET: 0xd80 */
    ISP_HO_ADDRESS3_TYPE ho_address3; /* OFFSET: 0xd84 */
    ISP_HO_STRIDE1_TYPE ho_stride1; /* OFFSET: 0xd88 */
    ISP_HO_STRIDE2_TYPE ho_stride2; /* OFFSET: 0xd8c */
    ISP_RESERVED_TYPE rsvd32[12]; /* OFFSET: 0xd90 */
    ISP_HO_END_ADDRESS1_TYPE ho_end_address1; /* OFFSET: 0xd9c */
    ISP_HO_END_ADDRESS2_TYPE ho_end_address2; /* OFFSET: 0xda0 */
    ISP_HO_END_ADDRESS3_TYPE ho_end_address3; /* OFFSET: 0xda4 */
    ISP_HO_SYNC_CTRL_TYPE ho_sync_ctrl; /* OFFSET: 0xda8 */
    ISP_RESERVED_TYPE rsvd33[20]; /* OFFSET: 0xdac */
    ISP_LO_CTRL_TYPE lo_ctrl; /* OFFSET: 0xdc0 */
    ISP_LO_COL_STRIDE1_TYPE lo_col_stride1; /* OFFSET: 0xdc4 */
    ISP_LO_COL_STRIDE2_TYPE lo_col_stride2; /* OFFSET: 0xdc8 */
    ISP_LO_ADDRESS1_TYPE lo_address1; /* OFFSET: 0xdcc */
    ISP_LO_ADDRESS2_TYPE lo_address2; /* OFFSET: 0xdd0 */
    ISP_LO_ADDRESS3_TYPE lo_address3; /* OFFSET: 0xdd4 */
    ISP_LO_STRIDE1_TYPE lo_stride1; /* OFFSET: 0xdd8 */
    ISP_LO_STRIDE2_TYPE lo_stride2; /* OFFSET: 0xddc */
    ISP_RESERVED_TYPE rsvd34[12]; /* OFFSET: 0xde0 */
    ISP_LO_END_ADDRESS1_TYPE lo_end_address1; /* OFFSET: 0xdec */
    ISP_LO_END_ADDRESS2_TYPE lo_end_address2; /* OFFSET: 0xdf0 */
    ISP_LO_END_ADDRESS3_TYPE lo_end_address3; /* OFFSET: 0xdf4 */
    ISP_LO_SYNC_CTRL_TYPE lo_sync_ctrl; /* OFFSET: 0xdf8 */
    ISP_RESERVED_TYPE rsvd35[132]; /* OFFSET: 0xdfc */
    ISP_CK_ADDR_TYPE ck_addr; /* OFFSET: 0xe80 */
    ISP_CK_STATUS_TYPE ck_status; /* OFFSET: 0xe84 */
    ISP_CK_DATA_TYPE ck_data; /* OFFSET: 0xe88 */
    ISP_RESERVED_TYPE rsvd36[20]; /* OFFSET: 0xe8c */
    ISP_CA_CTRL_TYPE ca_ctrl; /* OFFSET: 0xea0 */
    ISP_CA_STATUS_TYPE ca_status; /* OFFSET: 0xea4 */
    ISP_CA_DATA_LOW_TYPE ca_data_low; /* OFFSET: 0xea8 */
    ISP_CA_DATA_HIGH_TYPE ca_data_high; /* OFFSET: 0xeac */
    ISP_CA_PIXEL_CNT_TYPE ca_pixel_cnt; /* OFFSET: 0xeb0 */
    ISP_CA_LINE_TILE_CNT_TYPE ca_line_tile_cnt; /* OFFSET: 0xeb4 */
    ISP_RESERVED_TYPE rsvd37[72]; /* OFFSET: 0xeb8 */
    ISP_DG_CTRL_TYPE dg_ctrl; /* OFFSET: 0xf00 */
    ISP_DG_TILE_CNT0_TYPE dg_tile_cnt0; /* OFFSET: 0xf04 */
    ISP_DG_TILE_CNT1_TYPE dg_tile_cnt1; /* OFFSET: 0xf08 */
    ISP_DG_TILE_CNT2_TYPE dg_tile_cnt2; /* OFFSET: 0xf0c */
    ISP_DG_TILE_CNT3_TYPE dg_tile_cnt3; /* OFFSET: 0xf10 */
    ISP_DG_TILE_CNT4_TYPE dg_tile_cnt4; /* OFFSET: 0xf14 */
    ISP_DG_TILE_CNT5_TYPE dg_tile_cnt5; /* OFFSET: 0xf18 */
    ISP_RESERVED_TYPE rsvd38[4]; /* OFFSET: 0xf1c */
    ISP_DG_LINE_CNT0_TYPE dg_line_cnt0; /* OFFSET: 0xf20 */
    ISP_DG_LINE_CNT1_TYPE dg_line_cnt1; /* OFFSET: 0xf24 */
    ISP_DG_LINE_CNT2_TYPE dg_line_cnt2; /* OFFSET: 0xf28 */
    ISP_DG_LINE_CNT3_TYPE dg_line_cnt3; /* OFFSET: 0xf2c */
    ISP_DG_LINE_CNT4_TYPE dg_line_cnt4; /* OFFSET: 0xf30 */
    ISP_DG_LINE_CNT5_TYPE dg_line_cnt5; /* OFFSET: 0xf34 */
    ISP_DG_LINE_CNT6_TYPE dg_line_cnt6; /* OFFSET: 0xf38 */
    ISP_DG_LINE_CNT7_TYPE dg_line_cnt7; /* OFFSET: 0xf3c */
    ISP_DG_LINE_CNT8_TYPE dg_line_cnt8; /* OFFSET: 0xf40 */
    ISP_DG_LINE_CNT9_TYPE dg_line_cnt9; /* OFFSET: 0xf44 */
    ISP_DG_LINE_CNT10_TYPE dg_line_cnt10; /* OFFSET: 0xf48 */
    ISP_DG_PIXEL_CNT0_TYPE dg_pixel_cnt0; /* OFFSET: 0xf4c */
    ISP_DG_PIXEL_CNT1_TYPE dg_pixel_cnt1; /* OFFSET: 0xf50 */
    ISP_DG_PIXEL_CNT2_TYPE dg_pixel_cnt2; /* OFFSET: 0xf54 */
    ISP_DG_PIXEL_CNT3_TYPE dg_pixel_cnt3; /* OFFSET: 0xf58 */
    ISP_DG_PIXEL_CNT4_TYPE dg_pixel_cnt4; /* OFFSET: 0xf5c */
    ISP_DG_PIXEL_CNT5_TYPE dg_pixel_cnt5; /* OFFSET: 0xf60 */
    ISP_DG_PIXEL_CNT6_TYPE dg_pixel_cnt6; /* OFFSET: 0xf64 */
    ISP_DG_PIXEL_CNT7_TYPE dg_pixel_cnt7; /* OFFSET: 0xf68 */
    ISP_DG_PIXEL_CNT8_TYPE dg_pixel_cnt8; /* OFFSET: 0xf6c */
    ISP_DG_PIXEL_CNT9_TYPE dg_pixel_cnt9; /* OFFSET: 0xf70 */
    ISP_DG_PIXEL_CNT10_TYPE dg_pixel_cnt10; /* OFFSET: 0xf74 */
    ISP_DG_TILE_NUM_TYPE dg_tile_num; /* OFFSET: 0xf78 */
    ISP_DG_STALL_TYPE dg_stall; /* OFFSET: 0xf7c */
    ISP_DG_MASTERS_TYPE dg_masters; /* OFFSET: 0xf80 */
    ISP_DG_DONE_CNT0_TYPE dg_done_cnt0; /* OFFSET: 0xf84 */
    ISP_DG_EOT_CNT1_TYPE dg_eot_cnt1; /* OFFSET: 0xf88 */
    ISP_DG_ACK_CNT0_TYPE dg_ack_cnt0; /* OFFSET: 0xf8c */
    ISP_DG_EOT_CNT0_TYPE dg_eot_cnt0; /* OFFSET: 0xf90 */
    ISP_DG_UTIL_IDLE0_TYPE dg_util_idle0; /* OFFSET: 0xf94 */
    ISP_DG_UTIL_STALL0_TYPE dg_util_stall0; /* OFFSET: 0xf98 */
    ISP_DG_UTIL_TRANS0_TYPE dg_util_trans0; /* OFFSET: 0xf9c */
    ISP_DG_UTIL_IDLE1_TYPE dg_util_idle1; /* OFFSET: 0xfa0 */
    ISP_DG_UTIL_STALL1_TYPE dg_util_stall1; /* OFFSET: 0xfa4 */
    ISP_DG_UTIL_TRANS1_TYPE dg_util_trans1; /* OFFSET: 0xfa8 */
    ISP_DG_UTIL_IDLE2_TYPE dg_util_idle2; /* OFFSET: 0xfac */
    ISP_DG_UTIL_STALL2_TYPE dg_util_stall2; /* OFFSET: 0xfb0 */
    ISP_DG_UTIL_TRANS2_TYPE dg_util_trans2; /* OFFSET: 0xfb4 */
    ISP_DG_ERROR_TYPE dg_error; /* OFFSET: 0xfb8 */
    ISP_DG_TCB_SEL_TYPE dg_tcb_sel; /* OFFSET: 0xfbc */
    ISP_DG_TCB_DATA_TYPE dg_tcb_data; /* OFFSET: 0xfc0 */
    ISP_DG_AXI_CONFIG_TYPE dg_axi_config; /* OFFSET: 0xfc4 */
    ISP_DG_TCB_MASTER_TYPE dg_tcb_master; /* OFFSET: 0xfc8 */
    ISP_RESERVED_TYPE rsvd39[4]; /* OFFSET: 0xfcc */
    ISP_DG_CFG_ACCESS_TYPE dg_cfg_access; /* OFFSET: 0xfd0 */
    ISP_RESERVED_TYPE rsvd40[44]; /* OFFSET: 0xfd4 */
    ISP_LS_CV_TYPE ls_cv[1089]; /* OFFSET: 0x1000 */
    ISP_RESERVED_TYPE rsvd41[248]; /* OFFSET: 0x3208 */
    ISP_GM_SLOPE_R_TYPE gm_slope_r[32]; /* OFFSET: 0x3300 */
    ISP_GM_SLOPE_G_TYPE gm_slope_g[32]; /* OFFSET: 0x3380 */
    ISP_GM_SLOPE_B_TYPE gm_slope_b[32]; /* OFFSET: 0x3400 */
    ISP_RESERVED_TYPE rsvd42[128]; /* OFFSET: 0x3480 */
    ISP_TM_Y_ABSC_TYPE tm_y_absc[16]; /* OFFSET: 0x3500 */
    ISP_CP_CB_ABSC_TYPE cp_cb_absc[8]; /* OFFSET: 0x3540 */
    ISP_CP_CR_ABSC_TYPE cp_cr_absc[8]; /* OFFSET: 0x3560 */
    ISP_TM_SHIFT_TYPE tm_shift; /* OFFSET: 0x3580 */
    ISP_CP_SHIFT_TYPE cp_shift; /* OFFSET: 0x3584 */
    ISP_RESERVED_TYPE rsvd43[56]; /* OFFSET: 0x3588 */
    ISP_CP_CB_ORD_SLOPE_TYPE cp_cb_ord_slope[8]; /* OFFSET: 0x35c0 */
    ISP_CP_CR_ORD_SLOPE_TYPE cp_cr_ord_slope[8]; /* OFFSET: 0x35e0 */
    ISP_TM_Y_ORD_SLOPE_TYPE tm_y_ord_slope[32]; /* OFFSET: 0x3600 */
    ISP_RESERVED_TYPE rsvd44[384]; /* OFFSET: 0x3680 */
    ISP_SH_VGAIN_ABSC_TYPE sh_vgain_absc[4]; /* OFFSET: 0x3800 */
    ISP_SH_VGAIN_ORD_TYPE sh_vgain_ord[4]; /* OFFSET: 0x3810 */
    ISP_SH_VGAIN_SLOPE_TYPE sh_vgain_slope[4]; /* OFFSET: 0x3820 */
    ISP_SH_POSGAIN_ABSC_TYPE sh_posgain_absc[4]; /* OFFSET: 0x3830 */
    ISP_SH_POSGAIN_ORD_TYPE sh_posgain_ord[4]; /* OFFSET: 0x3840 */
    ISP_SH_POSGAIN_SLOPE_TYPE sh_posgain_slope[4]; /* OFFSET: 0x3850 */
    ISP_SH_RESPGAIN_ABSC_TYPE sh_respgain_absc[8]; /* OFFSET: 0x3860 */
    ISP_SH_RESPGAIN_ORD_TYPE sh_respgain_ord[8]; /* OFFSET: 0x3880 */
    ISP_SH_RESPGAIN_SLOPE_TYPE sh_respgain_slope[8]; /* OFFSET: 0x38a0 */
    ISP_SH_RESP_ABSC_TYPE sh_resp_absc[6]; /* OFFSET: 0x38c0 */
    ISP_SH_RESP_ORD_TYPE sh_resp_ord[6]; /* OFFSET: 0x38d8 */
    ISP_SH_RESP_SLOPE_TYPE sh_resp_slope[6]; /* OFFSET: 0x38f0 */
    ISP_SH_RESP1_ABSC_TYPE sh_resp1_absc[6]; /* OFFSET: 0x3908 */
    ISP_SH_RESP1_ORD_TYPE sh_resp1_ord[6]; /* OFFSET: 0x3920 */
    ISP_SH_RESP1_SLOPE_TYPE sh_resp1_slope[6]; /* OFFSET: 0x3938 */
    ISP_RESERVED_TYPE rsvd45[176]; /* OFFSET: 0x3950 */
    ISP_GM_ORD_R_TYPE gm_ord_r[16]; /* OFFSET: 0x3a00 */
    ISP_GM_ORD_G_TYPE gm_ord_g[16]; /* OFFSET: 0x3a40 */
    ISP_GM_ORD_B_TYPE gm_ord_b[16]; /* OFFSET: 0x3a80 */
    ISP_RESERVED_TYPE rsvd46[64]; /* OFFSET: 0x3ac0 */
    ISP_BL1_ABSC_RN_TYPE bl1_absc_r[8]; /* OFFSET: 0x3b00 */
    ISP_BL1_ABSC_GRN_TYPE bl1_absc_gr[8]; /* OFFSET: 0x3b20 */
    ISP_BL1_ABSC_BN_TYPE bl1_absc_b[8]; /* OFFSET: 0x3b40 */
    ISP_RESERVED_TYPE rsvd47[32]; /* OFFSET: 0x3b60 */
    ISP_BL1_ORD_SLOPE_RN_TYPE bl1_ord_slope_r[16]; /* OFFSET: 0x3b80 */
    ISP_BL1_ORD_SLOPE_GRN_TYPE bl1_ord_slope_gr[16]; /* OFFSET: 0x3bc0 */
    ISP_BL1_ORD_SLOPE_BN_TYPE bl1_ord_slope_b[16]; /* OFFSET: 0x3c00 */
    ISP_RESERVED_TYPE rsvd48[64]; /* OFFSET: 0x3c40 */
    ISP_LTM_KHP_TYPE ispltm_khp; /* OFFSET: 0x3c80 */
    ISP_LTM_KCOLOR_TYPE ispltm_kcolor; /* OFFSET: 0x3c84 */
    ISP_LTM_GF_CTRL_TYPE ispltm_gf_ctrl; /* OFFSET: 0x3c88 */
    ISP_LTM_DIV_SAT_TYPE ispltm_div_sat; /* OFFSET: 0x3c8c */
    ISP_LTM_GKER_COEFF_TYPE ispltm_gker_coeff[81]; /* OFFSET: 0x3c90 */
    ISP_LTM_SHIFT_BGM_TYPE ltm_shift_bgm; /* OFFSET: 0x3dd4 */
    ISP_LTM_SHIFT_DGM_G_TYPE ltm_shift_dgm_g; /* OFFSET: 0x3dd8 */
    ISP_RESERVED_TYPE rsvd49[164]; /* OFFSET: 0x3ddc */
    ISP_LTM_BGM_ABSC_TYPE ispltm_bgm_absc[16]; /* OFFSET: 0x3e80 */
    ISP_LTM_DGM_G_ABSC_TYPE ispltm_dgm_g_absc[16]; /* OFFSET: 0x3ec0 */
    ISP_LTM_BGM_ORD_SLOPE_TYPE ispltm_bgm_ord_slope[32]; /* OFFSET: 0x3f00 */
    ISP_LTM_DGM_G_ORD_SLOPE_TYPE ispltm_dgm_g_ord_slope[32]; /* OFFSET: 0x3f80 */
    ISP_BL1_ABSC_GB_TYPE bl1_absc_gb[8]; /* OFFSET: 0x4000 */
    ISP_RESERVED_TYPE rsvd50[32]; /* OFFSET: 0x4020 */
    ISP_BL1_ORD_SLOPE_GB_TYPE bl1_ord_slope_gb[16]; /* OFFSET: 0x4040 */
    ISP_RESERVED_TYPE rsvd51[2944]; /* OFFSET: 0x4080 */
    ISP_CD_FIR_BG_ABSC_TYPE ispcd_fir_bg_absc[3]; /* OFFSET: 0x4c00 */
    ISP_CD_FIR_BG_ORD_TYPE ispcd_fir_bg_ord[3]; /* OFFSET: 0x4c0c */
    ISP_CD_FIR_BG_SLOPE_TYPE ispcd_fir_bg_slope[3]; /* OFFSET: 0x4c18 */
    ISP_CD_FIR_RG_ABSC_TYPE ispcd_fir_rg_absc[3]; /* OFFSET: 0x4c24 */
    ISP_CD_FIR_RG_ORD_TYPE ispcd_fir_rg_ord[3]; /* OFFSET: 0x4c30 */
    ISP_CD_FIR_RG_SLOPE_TYPE ispcd_fir_rg_slope[3]; /* OFFSET: 0x4c3c */
    ISP_CD_IIR_BG_ABSC_TYPE ispcd_iir_bg_absc[3]; /* OFFSET: 0x4c48 */
    ISP_CD_IIR_BG_ORD_TYPE ispcd_iir_bg_ord[3]; /* OFFSET: 0x4c54 */
    ISP_CD_IIR_BG_SLOPE_TYPE ispcd_iir_bg_slope[3]; /* OFFSET: 0x4c60 */
    ISP_CD_IIR_RG_ABSC_TYPE ispcd_iir_rg_absc[3]; /* OFFSET: 0x4c6c */
    ISP_CD_IIR_RG_ORD_TYPE ispcd_iir_rg_ord[3]; /* OFFSET: 0x4c78 */
    ISP_CD_IIR_RG_SLOPE_TYPE ispcd_iir_rg_slope[3]; /* OFFSET: 0x4c84 */
    ISP_CD_WGHTS_TYPE ispcd_wghts; /* OFFSET: 0x4c90 */
    ISP_CD_DIST_ABSC_TYPE ispcd_dist_absc[3]; /* OFFSET: 0x4c94 */
    ISP_CD_DIST_ORD_TYPE ispcd_dist_ord[3]; /* OFFSET: 0x4ca0 */
    ISP_CD_DIST_SLOPE_TYPE ispcd_dist_slope[3]; /* OFFSET: 0x4cac */
    ISP_CD_G_ABSC_TYPE ispcd_g_absc[3]; /* OFFSET: 0x4cb8 */
    ISP_CD_G_ORD_TYPE ispcd_g_ord[3]; /* OFFSET: 0x4cc4 */
    ISP_CD_G_SLOPE_TYPE ispcd_g_slope[3]; /* OFFSET: 0x4cd0 */
    ISP_CD_SAT_ABSC_TYPE ispcd_sat_absc[3]; /* OFFSET: 0x4cdc */
    ISP_CD_SAT_ORD_TYPE ispcd_sat_ord[3]; /* OFFSET: 0x4ce8 */
    ISP_CD_SAT_SLOPE_TYPE ispcd_sat_slope[3]; /* OFFSET: 0x4cf4 */
    ISP_CD_CENTRE_TYPE ispcd_centre; /* OFFSET: 0x4d00 */
    ISP_CD_MISC_TYPE ispcd_misc; /* OFFSET: 0x4d04 */
    ISP_CD_EDGE_THRESH_TYPE ispcd_edge_thresh; /* OFFSET: 0x4d08 */
    ISP_CD_EDGE_STRENGTH_MIN_TYPE ispcd_edge_strength_min; /* OFFSET: 0x4d0c */
} ISP_RDBType;


#define ISP_BASE                        (0x40090000UL)



#define ISP_MAX_HW_ID                   (1UL)


#define ISP_VERSION                     (421UL)


#define ISP_SIGNATURE                   (0x4953UL)


#define ISP_STATS_OFFSET                (0x80000UL)


#define ISP_TCB_SIZE                    (112UL)


#define ISP_STATUS_ACTIVE               (0x1UL)


#define ISP_DISABLE_PLANE_RY            (0x1UL)


#define ISP_DISABLE_PLANE_GU            (0x2UL)


#define ISP_DISABLE_PLANE_BV            (0x4UL)


#define ISP_DCTRL_TO_ISP                (0x001UL)


#define ISP_DCTRL_INIT                  (0x002UL)


#define ISP_DCTRL_EOT_INT               (0x004UL)


#define ISP_DCTRL_ALL_BANKS             (0x008UL)


#define ISP_DSTAGE_NONE                 (0x0UL)


#define ISP_DSTAGE_TILE_ISSUE           (0x1UL)


#define ISP_DSTAGE_LENS_SHADING         (0x2UL)


#define ISP_DSTAGE_STATISTICS           (0x3UL)


#define ISP_DSTAGE_DISTORTION           (0x4UL)


#define ISP_DSTAGE_DEFPIX_PROG          (0x5UL)


#define ISP_DSTAGE_BLACK_LEVEL          (0x6UL)


#define ISP_DSTAGE_CROSSTALK            (0x7UL)


#define ISP_DSTAGE_FOCUS_STATS          (0x8UL)


#define ISP_DSTAGE_COUNT                (0x9UL)

#endif /* ISP_RDB_H */
