/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file mcu_cpu_rdb.h
    @brief RDB File for MCU_CPU

    @version 2018May25_rdb
*/

#ifndef MCU_CPU_RDB_H
#define MCU_CPU_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MCU_CPU_DCACHE_ERR_TYPE;
#define MCU_CPU_DCACHE_ERR_DCERR_MASK (0x3fffff0UL)
#define MCU_CPU_DCACHE_ERR_DCERR_SHIFT (4UL)
#define MCU_CPU_DCACHE_ERR_DCDET_MASK (0xfUL)
#define MCU_CPU_DCACHE_ERR_DCDET_SHIFT (0UL)




typedef uint32_t MCU_CPU_ICACHE_ERR_TYPE;
#define MCU_CPU_ICACHE_ERR_ICERR_MASK (0x3fffff0UL)
#define MCU_CPU_ICACHE_ERR_ICERR_SHIFT (4UL)
#define MCU_CPU_ICACHE_ERR_ICDET_MASK (0xfUL)
#define MCU_CPU_ICACHE_ERR_ICDET_SHIFT (0UL)




typedef uint32_t MCU_CPU_MEMCTL_TYPE;
#define MCU_CPU_MEMCTL_ROM_TM_MASK (0x1f800UL)
#define MCU_CPU_MEMCTL_ROM_TM_SHIFT (11UL)
#define MCU_CPU_MEMCTL_MEM_POWERONIN_MASK (0x400UL)
#define MCU_CPU_MEMCTL_MEM_POWERONIN_SHIFT (10UL)
#define MCU_CPU_MEMCTL_MEM_POWEROKIN_MASK (0x200UL)
#define MCU_CPU_MEMCTL_MEM_POWEROKIN_SHIFT (9UL)
#define MCU_CPU_MEMCTL_MEM_ISO_MASK (0x100UL)
#define MCU_CPU_MEMCTL_MEM_ISO_SHIFT (8UL)
#define MCU_CPU_MEMCTL_MEM_PDA_MASK (0x80UL)
#define MCU_CPU_MEMCTL_MEM_PDA_SHIFT (7UL)
#define MCU_CPU_MEMCTL_MEM_TM_MASK (0x7fUL)
#define MCU_CPU_MEMCTL_MEM_TM_SHIFT (0UL)




typedef uint32_t MCU_CPU_DBG_SCRATCH_TYPE;
#define MCU_CPU_DBG_SCRATCH_SCRATCH_MASK (0xffffffffUL)
#define MCU_CPU_DBG_SCRATCH_SCRATCH_SHIFT (0UL)




typedef uint32_t MCU_CPU_MBIST_CTL_TYPE;
#define MCU_CPU_MBIST_CTL_WR_ENABLE_MASK (0x2UL)
#define MCU_CPU_MBIST_CTL_WR_ENABLE_SHIFT (1UL)
#define MCU_CPU_MBIST_CTL_ENABLE_MASK (0x1UL)
#define MCU_CPU_MBIST_CTL_ENABLE_SHIFT (0UL)




typedef uint32_t MCU_CPU_MBIST_WDATA_TYPE;
#define MCU_CPU_MBIST_WDATA_WDATA_MASK (0xffffffffUL)
#define MCU_CPU_MBIST_WDATA_WDATA_SHIFT (0UL)




typedef uint32_t MCU_CPU_MBIST_RDATA_TYPE;
#define MCU_CPU_MBIST_RDATA_RDATA_MASK (0xffffffffUL)
#define MCU_CPU_MBIST_RDATA_RDATA_SHIFT (0UL)




typedef uint32_t MCU_CPU_ID_CACHE_SEC_CNT_TYPE;
#define MCU_CPU_ID_CACHE_SEC_CNT_CNT_MASK (0xfUL)
#define MCU_CPU_ID_CACHE_SEC_CNT_CNT_SHIFT (0UL)




typedef uint32_t MCU_CPU_MISC_CTL_TYPE;
#define MCU_CPU_MISC_CTL_TIMESTAMP_START_MASK (0x80000000UL)
#define MCU_CPU_MISC_CTL_TIMESTAMP_START_SHIFT (31UL)
#define MCU_CPU_MISC_CTL_TIMESTAMP_STOP_MASK (0x40000000UL)
#define MCU_CPU_MISC_CTL_TIMESTAMP_STOP_SHIFT (30UL)
#define MCU_CPU_MISC_CTL_CPU_CLKEN_OVR_MASK (0x10UL)
#define MCU_CPU_MISC_CTL_CPU_CLKEN_OVR_SHIFT (4UL)
#define MCU_CPU_MISC_CTL_ROM_CLKEN_OVR_MASK (0x8UL)
#define MCU_CPU_MISC_CTL_ROM_CLKEN_OVR_SHIFT (3UL)
#define MCU_CPU_MISC_CTL_ATB_CLKEN_OVR_MASK (0x4UL)
#define MCU_CPU_MISC_CTL_ATB_CLKEN_OVR_SHIFT (2UL)
#define MCU_CPU_MISC_CTL_TRACE_SFT_RST_MASK (0x2UL)
#define MCU_CPU_MISC_CTL_TRACE_SFT_RST_SHIFT (1UL)
#define MCU_CPU_MISC_CTL_TRACECLK_SEL_MASK (0x1UL)
#define MCU_CPU_MISC_CTL_TRACECLK_SEL_SHIFT (0UL)




typedef uint32_t MCU_CPU_MSPI_CTL_TYPE;
#define MCU_CPU_MSPI_CTL_WRDISABLE_MASK (0x3UL)
#define MCU_CPU_MSPI_CTL_WRDISABLE_SHIFT (0UL)




typedef uint32_t MCU_CPU_DHS_CTL_TYPE;
#define MCU_CPU_DHS_CTL_1_ACK_MASK (0x800UL)
#define MCU_CPU_DHS_CTL_1_ACK_SHIFT (11UL)
#define MCU_CPU_DHS_CTL_1_READY_MASK (0x400UL)
#define MCU_CPU_DHS_CTL_1_READY_SHIFT (10UL)
#define MCU_CPU_DHS_CTL_1_BA_MASK (0x300UL)
#define MCU_CPU_DHS_CTL_1_BA_SHIFT (8UL)
#define MCU_CPU_DHS_CTL_1_SEL_MASK (0xc0UL)
#define MCU_CPU_DHS_CTL_1_SEL_SHIFT (6UL)
#define MCU_CPU_DHS_CTL_0_ACK_MASK (0x20UL)
#define MCU_CPU_DHS_CTL_0_ACK_SHIFT (5UL)
#define MCU_CPU_DHS_CTL_0_READY_MASK (0x10UL)
#define MCU_CPU_DHS_CTL_0_READY_SHIFT (4UL)
#define MCU_CPU_DHS_CTL_0_BA_MASK (0xcUL)
#define MCU_CPU_DHS_CTL_0_BA_SHIFT (2UL)
#define MCU_CPU_DHS_CTL_0_SEL_MASK (0x3UL)
#define MCU_CPU_DHS_CTL_0_SEL_SHIFT (0UL)




typedef uint8_t MCU_CPU_RESERVED_TYPE;




typedef uint32_t MCU_CPU_NMI_STS_CTL_TYPE;
#define MCU_CPU_NMI_STS_CTL_NMI_CLEAR_MASK (0x80000000UL)
#define MCU_CPU_NMI_STS_CTL_NMI_CLEAR_SHIFT (31UL)
#define MCU_CPU_NMI_STS_CTL_WDOG_MASK (0x4UL)
#define MCU_CPU_NMI_STS_CTL_WDOG_SHIFT (2UL)
#define MCU_CPU_NMI_STS_CTL_ID_CACHE_ERR_MASK (0x2UL)
#define MCU_CPU_NMI_STS_CTL_ID_CACHE_ERR_SHIFT (1UL)
#define MCU_CPU_NMI_STS_CTL_SRAM_ECC_UNCOR_MASK (0x1UL)
#define MCU_CPU_NMI_STS_CTL_SRAM_ECC_UNCOR_SHIFT (0UL)




typedef uint32_t MCU_CPU_NMI_STS_SHD_TYPE;
#define MCU_CPU_NMI_STS_SHD_WDOG_POR_MASK (0x40UL)
#define MCU_CPU_NMI_STS_SHD_WDOG_POR_SHIFT (6UL)
#define MCU_CPU_NMI_STS_SHD_ID_CACHE_ERR_POR_MASK (0x20UL)
#define MCU_CPU_NMI_STS_SHD_ID_CACHE_ERR_POR_SHIFT (5UL)
#define MCU_CPU_NMI_STS_SHD_SRAM_ECC_UNCOR_POR_MASK (0x10UL)
#define MCU_CPU_NMI_STS_SHD_SRAM_ECC_UNCOR_POR_SHIFT (4UL)
#define MCU_CPU_NMI_STS_SHD_WDOG_SHD_MASK (0x4UL)
#define MCU_CPU_NMI_STS_SHD_WDOG_SHD_SHIFT (2UL)
#define MCU_CPU_NMI_STS_SHD_ID_CACHE_ERR_SHD_MASK (0x2UL)
#define MCU_CPU_NMI_STS_SHD_ID_CACHE_ERR_SHD_SHIFT (1UL)
#define MCU_CPU_NMI_STS_SHD_SRAM_ECC_UNCOR_SHD_MASK (0x1UL)
#define MCU_CPU_NMI_STS_SHD_SRAM_ECC_UNCOR_SHD_SHIFT (0UL)




typedef uint32_t MCU_CPU_RESET_OUT_TYPE;
#define MCU_CPU_RESET_OUT_VAL_MASK (0x80000000UL)
#define MCU_CPU_RESET_OUT_VAL_SHIFT (31UL)
#define MCU_CPU_RESET_OUT_KEY_MASK (0x7fffffffUL)
#define MCU_CPU_RESET_OUT_KEY_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MCU_CPU_RDBType {
    MCU_CPU_DCACHE_ERR_TYPE dcache_err; /* OFFSET: 0x0 */
    MCU_CPU_ICACHE_ERR_TYPE icache_err; /* OFFSET: 0x4 */
    MCU_CPU_MEMCTL_TYPE memctl; /* OFFSET: 0x8 */
    MCU_CPU_DBG_SCRATCH_TYPE dbg_scratch; /* OFFSET: 0xc */
    MCU_CPU_MBIST_CTL_TYPE mbist_ctl; /* OFFSET: 0x10 */
    MCU_CPU_MBIST_WDATA_TYPE mbist_wdata; /* OFFSET: 0x14 */
    MCU_CPU_MBIST_RDATA_TYPE mbist_rdata; /* OFFSET: 0x18 */
    MCU_CPU_ID_CACHE_SEC_CNT_TYPE id_cache_sec_cnt; /* OFFSET: 0x1c */
    MCU_CPU_MISC_CTL_TYPE misc_ctl; /* OFFSET: 0x20 */
    MCU_CPU_MSPI_CTL_TYPE mspi_ctl; /* OFFSET: 0x24 */
    MCU_CPU_DHS_CTL_TYPE dhs_ctl; /* OFFSET: 0x28 */
    MCU_CPU_RESERVED_TYPE rsvd0[212]; /* OFFSET: 0x2c */
    MCU_CPU_NMI_STS_CTL_TYPE nmi_sts_ctl; /* OFFSET: 0x100 */
    MCU_CPU_NMI_STS_SHD_TYPE nmi_sts_shd; /* OFFSET: 0x104 */
    MCU_CPU_RESERVED_TYPE rsvd1[3576]; /* OFFSET: 0x108 */
    MCU_CPU_RESET_OUT_TYPE cpu_reset_out; /* OFFSET: 0xf00 */
} MCU_CPU_RDBType;


#define MCU_CPU_BASE                    (0xE0102000UL)



#define MCU_CPU_MAX_HW_ID               (1UL)


#define MCU_CPU_DHSCTL_DHS0SELCPU_MASK  (0x00000000UL)


#define MCU_CPU_DHSCTL_DHS0SELDISPLAY_MASK  (0x00000001UL)


#define MCU_CPU_DHSCTL_DHS0SELIMG_MASK  (0x00000002UL)


#define MCU_CPU_DHSCTL_DHS1SELCPU_MASK  (0x00000000UL)


#define MCU_CPU_DHSCTL_DHS1SELDISPLAY_MASK  (0x00000040UL)


#define MCU_CPU_DHSCTL_DHS1SELIMG_MASK  (0x00000080UL)

#endif /* MCU_CPU_RDB_H */
