/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file mcu_rdb.h
    @brief RDB File for MCU

    @version 2018May25_rdb
*/

#ifndef MCU_RDB_H
#define MCU_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t MCU_SPARE_REG_0_TYPE;
#define MCU_SPARE_REG_0_DBG_RESET_KEY_MASK (0xff00U)
#define MCU_SPARE_REG_0_DBG_RESET_KEY_SHIFT (8U)
#define MCU_SPARE_REG_0_SPARE_REG_MASK (0xe0U)
#define MCU_SPARE_REG_0_SPARE_REG_SHIFT (5U)
#define MCU_SPARE_REG_0_DBG_SRAM_RESET_N_MASK (0x10U)
#define MCU_SPARE_REG_0_DBG_SRAM_RESET_N_SHIFT (4U)
#define MCU_SPARE_REG_0_DBG_L1_RESET_N_MASK (0x8U)
#define MCU_SPARE_REG_0_DBG_L1_RESET_N_SHIFT (3U)
#define MCU_SPARE_REG_0_DBG_VIDEANTIS_RESET_N_MASK (0x4U)
#define MCU_SPARE_REG_0_DBG_VIDEANTIS_RESET_N_SHIFT (2U)
#define MCU_SPARE_REG_0_DBG_DDR_RESET_N_MASK (0x2U)
#define MCU_SPARE_REG_0_DBG_DDR_RESET_N_SHIFT (1U)
#define MCU_SPARE_REG_0_DBG_ISP_RESET_N_MASK (0x1U)
#define MCU_SPARE_REG_0_DBG_ISP_RESET_N_SHIFT (0U)




typedef uint16_t MCU_XTAL_CTRL_1_TYPE;
#define MCU_XTAL_CTRL_1_SPARE_MASK (0xe000U)
#define MCU_XTAL_CTRL_1_SPARE_SHIFT (13U)
#define MCU_XTAL_CTRL_1_LDO_TAIL_MASK (0x1000U)
#define MCU_XTAL_CTRL_1_LDO_TAIL_SHIFT (12U)
#define MCU_XTAL_CTRL_1_LDO_BIAS_MASK (0xc00U)
#define MCU_XTAL_CTRL_1_LDO_BIAS_SHIFT (10U)
#define MCU_XTAL_CTRL_1_LDO_VCTRL_MASK (0x300U)
#define MCU_XTAL_CTRL_1_LDO_VCTRL_SHIFT (8U)
#define MCU_XTAL_CTRL_1_XTAL_ISO_IN_MASK (0x80U)
#define MCU_XTAL_CTRL_1_XTAL_ISO_IN_SHIFT (7U)
#define MCU_XTAL_CTRL_1_XTAL_RESETB_MASK (0x40U)
#define MCU_XTAL_CTRL_1_XTAL_RESETB_SHIFT (6U)
#define MCU_XTAL_CTRL_1_XTAL_PD_MASK (0x20U)
#define MCU_XTAL_CTRL_1_XTAL_PD_SHIFT (5U)
#define MCU_XTAL_CTRL_1_XTAL_HIPASS_MASK (0x10U)
#define MCU_XTAL_CTRL_1_XTAL_HIPASS_SHIFT (4U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_3_MASK (0x8U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_3_SHIFT (3U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_2_MASK (0x4U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_2_SHIFT (2U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_1_MASK (0x2U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_1_SHIFT (1U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_0_MASK (0x1U)
#define MCU_XTAL_CTRL_1_XTAL_XCORE_BIAS_0_SHIFT (0U)




typedef uint16_t MCU_XTAL_CTRL_2_TYPE;
#define MCU_XTAL_CTRL_2_SPARE_MASK (0xc000U)
#define MCU_XTAL_CTRL_2_SPARE_SHIFT (14U)
#define MCU_XTAL_CTRL_2_XTAL_CMOS_EN_ALL_MASK (0x2000U)
#define MCU_XTAL_CTRL_2_XTAL_CMOS_EN_ALL_SHIFT (13U)
#define MCU_XTAL_CTRL_2_XTAL_XCORE_CM_SEL_MASK (0x1000U)
#define MCU_XTAL_CTRL_2_XTAL_XCORE_CM_SEL_SHIFT (12U)
#define MCU_XTAL_CTRL_2_XTAL_D2C_BIAS_MASK (0xe00U)
#define MCU_XTAL_CTRL_2_XTAL_D2C_BIAS_SHIFT (9U)
#define MCU_XTAL_CTRL_2_XTAL_BIAS_MASK (0x1c0U)
#define MCU_XTAL_CTRL_2_XTAL_BIAS_SHIFT (6U)
#define MCU_XTAL_CTRL_2_XTAL_CMOS_EN_CH_MASK (0x3fU)
#define MCU_XTAL_CTRL_2_XTAL_CMOS_EN_CH_SHIFT (0U)




typedef uint16_t MCU_XTAL_CTRL_3_TYPE;
#define MCU_XTAL_CTRL_3_OSC_CORE_CTRL_MASK (0x3ffU)
#define MCU_XTAL_CTRL_3_OSC_CORE_CTRL_SHIFT (0U)




typedef uint16_t MCU_RCOSC_CFG_TYPE;
#define MCU_RCOSC_CFG_LFO_PD_MASK (0x100U)
#define MCU_RCOSC_CFG_LFO_PD_SHIFT (8U)
#define MCU_RCOSC_CFG_LFO_CAL_MASK (0xffU)
#define MCU_RCOSC_CFG_LFO_CAL_SHIFT (0U)




typedef uint16_t MCU_RCOSC_STAT_TYPE;
#define MCU_RCOSC_STAT_LFO_STATUS_MASK (0xffU)
#define MCU_RCOSC_STAT_LFO_STATUS_SHIFT (0U)




typedef uint8_t MCU_RESERVED_TYPE;




typedef uint16_t MCU_RCOSC_CTRL_TYPE;
#define MCU_RCOSC_CTRL_LFO_CTRL_MASK (0xffffU)
#define MCU_RCOSC_CTRL_LFO_CTRL_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_CTRL_1_TYPE;
#define MCU_PLLSYS_CTRL_1_PLL_15_0_MASK (0xffffU)
#define MCU_PLLSYS_CTRL_1_PLL_15_0_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_CTRL_2_TYPE;
#define MCU_PLLSYS_CTRL_2_PLL_31_16_MASK (0xffffU)
#define MCU_PLLSYS_CTRL_2_PLL_31_16_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_CTRL_3_TYPE;
#define MCU_PLLSYS_CTRL_3_SPARE_MASK (0xff00U)
#define MCU_PLLSYS_CTRL_3_SPARE_SHIFT (8U)
#define MCU_PLLSYS_CTRL_3_PLL_CTRL_39_32_MASK (0xffU)
#define MCU_PLLSYS_CTRL_3_PLL_CTRL_39_32_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_NDIV_FRAC_TYPE;
#define MCU_PLLSYS_NDIV_FRAC_15_0_MASK (0xffffU)
#define MCU_PLLSYS_NDIV_FRAC_15_0_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_NDIV_TYPE;
#define MCU_PLLSYS_NDIV_SPARE_MASK (0xc000U)
#define MCU_PLLSYS_NDIV_SPARE_SHIFT (14U)
#define MCU_PLLSYS_NDIV_NDIV_FRAC_19_16_MASK (0x3c00U)
#define MCU_PLLSYS_NDIV_NDIV_FRAC_19_16_SHIFT (10U)
#define MCU_PLLSYS_NDIV_NDIV_INT_MASK (0x3ffU)
#define MCU_PLLSYS_NDIV_NDIV_INT_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_CFG_1_TYPE;
#define MCU_PLLSYS_CFG_1_SPARE_MASK (0xff80U)
#define MCU_PLLSYS_CFG_1_SPARE_SHIFT (7U)
#define MCU_PLLSYS_CFG_1_CH3_MDEL_MASK (0x40U)
#define MCU_PLLSYS_CFG_1_CH3_MDEL_SHIFT (6U)
#define MCU_PLLSYS_CFG_1_CH2_MDEL_MASK (0x20U)
#define MCU_PLLSYS_CFG_1_CH2_MDEL_SHIFT (5U)
#define MCU_PLLSYS_CFG_1_CH1_MDEL_MASK (0x10U)
#define MCU_PLLSYS_CFG_1_CH1_MDEL_SHIFT (4U)
#define MCU_PLLSYS_CFG_1_CH0_MDEL_MASK (0x8U)
#define MCU_PLLSYS_CFG_1_CH0_MDEL_SHIFT (3U)
#define MCU_PLLSYS_CFG_1_POST_RESETB_MASK (0x4U)
#define MCU_PLLSYS_CFG_1_POST_RESETB_SHIFT (2U)
#define MCU_PLLSYS_CFG_1_RESETB_MASK (0x2U)
#define MCU_PLLSYS_CFG_1_RESETB_SHIFT (1U)
#define MCU_PLLSYS_CFG_1_PWR_ON_MASK (0x1U)
#define MCU_PLLSYS_CFG_1_PWR_ON_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_CFG_2_TYPE;
#define MCU_PLLSYS_CFG_2_KP_MASK (0x3c00U)
#define MCU_PLLSYS_CFG_2_KP_SHIFT (10U)
#define MCU_PLLSYS_CFG_2_KI_MASK (0x380U)
#define MCU_PLLSYS_CFG_2_KI_SHIFT (7U)
#define MCU_PLLSYS_CFG_2_KA_MASK (0x70U)
#define MCU_PLLSYS_CFG_2_KA_SHIFT (4U)
#define MCU_PLLSYS_CFG_2_PDIV_MASK (0xfU)
#define MCU_PLLSYS_CFG_2_PDIV_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_CFG_3_TYPE;
#define MCU_PLLSYS_CFG_3_HOLD_CH_MASK (0xf000U)
#define MCU_PLLSYS_CFG_3_HOLD_CH_SHIFT (12U)
#define MCU_PLLSYS_CFG_3_ENABLEB_CH_MASK (0xf00U)
#define MCU_PLLSYS_CFG_3_ENABLEB_CH_SHIFT (8U)
#define MCU_PLLSYS_CFG_3_BYP_CLK_CH_MASK (0xf0U)
#define MCU_PLLSYS_CFG_3_BYP_CLK_CH_SHIFT (4U)
#define MCU_PLLSYS_CFG_3_BYP_EN_CH_MASK (0xfU)
#define MCU_PLLSYS_CFG_3_BYP_EN_CH_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_MDIV_1_TYPE;
#define MCU_PLLSYS_MDIV_1_CH1_MDIV_MASK (0xff00U)
#define MCU_PLLSYS_MDIV_1_CH1_MDIV_SHIFT (8U)
#define MCU_PLLSYS_MDIV_1_CH0_MDIV_MASK (0xffU)
#define MCU_PLLSYS_MDIV_1_CH0_MDIV_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_MDIV_2_TYPE;
#define MCU_PLLSYS_MDIV_2_CH3_MDIV_MASK (0xff00U)
#define MCU_PLLSYS_MDIV_2_CH3_MDIV_SHIFT (8U)
#define MCU_PLLSYS_MDIV_2_CH2_MDIV_MASK (0xffU)
#define MCU_PLLSYS_MDIV_2_CH2_MDIV_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_SSC_1_TYPE;
#define MCU_PLLSYS_SSC_1_STEP_MASK (0xffffU)
#define MCU_PLLSYS_SSC_1_STEP_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_SSC_2_TYPE;
#define MCU_PLLSYS_SSC_2_LIMIT_14_0_MASK (0xfffeU)
#define MCU_PLLSYS_SSC_2_LIMIT_14_0_SHIFT (1U)
#define MCU_PLLSYS_SSC_2_SSC_MODE_MASK (0x1U)
#define MCU_PLLSYS_SSC_2_SSC_MODE_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_SSC_3_TYPE;
#define MCU_PLLSYS_SSC_3_LIMIT_21_15_MASK (0x7fU)
#define MCU_PLLSYS_SSC_3_LIMIT_21_15_SHIFT (0U)




typedef uint16_t MCU_PLLSYS_STATUS_TYPE;
#define MCU_PLLSYS_STATUS_STATUS_MASK (0x3ffcU)
#define MCU_PLLSYS_STATUS_STATUS_SHIFT (2U)
#define MCU_PLLSYS_STATUS_LOCK_LOST_MASK (0x2U)
#define MCU_PLLSYS_STATUS_LOCK_LOST_SHIFT (1U)
#define MCU_PLLSYS_STATUS_LOCK_MASK (0x1U)
#define MCU_PLLSYS_STATUS_LOCK_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_CTRL_1_TYPE;
#define MCU_PLLDISP_CTRL_1_PLL_15_0_MASK (0xffffU)
#define MCU_PLLDISP_CTRL_1_PLL_15_0_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_CTRL_2_TYPE;
#define MCU_PLLDISP_CTRL_2_PLL_31_16_MASK (0xffffU)
#define MCU_PLLDISP_CTRL_2_PLL_31_16_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_CTRL_3_TYPE;
#define MCU_PLLDISP_CTRL_3_SPARE_MASK (0xff00U)
#define MCU_PLLDISP_CTRL_3_SPARE_SHIFT (8U)
#define MCU_PLLDISP_CTRL_3_PLL_CTRL_39_32_MASK (0xffU)
#define MCU_PLLDISP_CTRL_3_PLL_CTRL_39_32_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_NDIV_FRAC_TYPE;
#define MCU_PLLDISP_NDIV_FRAC_15_0_MASK (0xffffU)
#define MCU_PLLDISP_NDIV_FRAC_15_0_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_NDIV_TYPE;
#define MCU_PLLDISP_NDIV_SPARE_MASK (0xc000U)
#define MCU_PLLDISP_NDIV_SPARE_SHIFT (14U)
#define MCU_PLLDISP_NDIV_NDIV_FRAC_19_16_MASK (0x3c00U)
#define MCU_PLLDISP_NDIV_NDIV_FRAC_19_16_SHIFT (10U)
#define MCU_PLLDISP_NDIV_NDIV_INT_MASK (0x3ffU)
#define MCU_PLLDISP_NDIV_NDIV_INT_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_CFG_1_TYPE;
#define MCU_PLLDISP_CFG_1_SPARE_MASK (0xfff8U)
#define MCU_PLLDISP_CFG_1_SPARE_SHIFT (3U)
#define MCU_PLLDISP_CFG_1_POST_RESETB_MASK (0x4U)
#define MCU_PLLDISP_CFG_1_POST_RESETB_SHIFT (2U)
#define MCU_PLLDISP_CFG_1_RESETB_MASK (0x2U)
#define MCU_PLLDISP_CFG_1_RESETB_SHIFT (1U)
#define MCU_PLLDISP_CFG_1_PWR_ON_MASK (0x1U)
#define MCU_PLLDISP_CFG_1_PWR_ON_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_CFG_2_TYPE;
#define MCU_PLLDISP_CFG_2_KP_MASK (0x3c00U)
#define MCU_PLLDISP_CFG_2_KP_SHIFT (10U)
#define MCU_PLLDISP_CFG_2_KI_MASK (0x380U)
#define MCU_PLLDISP_CFG_2_KI_SHIFT (7U)
#define MCU_PLLDISP_CFG_2_KA_MASK (0x70U)
#define MCU_PLLDISP_CFG_2_KA_SHIFT (4U)
#define MCU_PLLDISP_CFG_2_PDIV_MASK (0xfU)
#define MCU_PLLDISP_CFG_2_PDIV_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_CFG_3_TYPE;
#define MCU_PLLDISP_CFG_3_SPARE_MASK (0xe000U)
#define MCU_PLLDISP_CFG_3_SPARE_SHIFT (13U)
#define MCU_PLLDISP_CFG_3_CH0_MDEL_MASK (0x1000U)
#define MCU_PLLDISP_CFG_3_CH0_MDEL_SHIFT (12U)
#define MCU_PLLDISP_CFG_3_CH0_MDIV_MASK (0xff0U)
#define MCU_PLLDISP_CFG_3_CH0_MDIV_SHIFT (4U)
#define MCU_PLLDISP_CFG_3_HOLD_CH0_MASK (0x8U)
#define MCU_PLLDISP_CFG_3_HOLD_CH0_SHIFT (3U)
#define MCU_PLLDISP_CFG_3_ENABLEB_CH0_MASK (0x4U)
#define MCU_PLLDISP_CFG_3_ENABLEB_CH0_SHIFT (2U)
#define MCU_PLLDISP_CFG_3_BYP_CLK_CH0_MASK (0x2U)
#define MCU_PLLDISP_CFG_3_BYP_CLK_CH0_SHIFT (1U)
#define MCU_PLLDISP_CFG_3_BYP_EN_CH0_MASK (0x1U)
#define MCU_PLLDISP_CFG_3_BYP_EN_CH0_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_SSC_1_TYPE;
#define MCU_PLLDISP_SSC_1_STEP_MASK (0xffffU)
#define MCU_PLLDISP_SSC_1_STEP_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_SSC_2_TYPE;
#define MCU_PLLDISP_SSC_2_LIMIT_14_0_MASK (0xfffeU)
#define MCU_PLLDISP_SSC_2_LIMIT_14_0_SHIFT (1U)
#define MCU_PLLDISP_SSC_2_SSC_MODE_MASK (0x1U)
#define MCU_PLLDISP_SSC_2_SSC_MODE_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_SSC_3_TYPE;
#define MCU_PLLDISP_SSC_3_LIMIT_21_15_MASK (0x7fU)
#define MCU_PLLDISP_SSC_3_LIMIT_21_15_SHIFT (0U)




typedef uint16_t MCU_PLLDISP_STATUS_TYPE;
#define MCU_PLLDISP_STATUS_STATUS_MASK (0x3ffcU)
#define MCU_PLLDISP_STATUS_STATUS_SHIFT (2U)
#define MCU_PLLDISP_STATUS_LOCK_LOST_MASK (0x2U)
#define MCU_PLLDISP_STATUS_LOCK_LOST_SHIFT (1U)
#define MCU_PLLDISP_STATUS_LOCK_MASK (0x1U)
#define MCU_PLLDISP_STATUS_LOCK_SHIFT (0U)




typedef uint16_t MCU_PLLVID_CTRL_1_TYPE;
#define MCU_PLLVID_CTRL_1_PLL_15_0_MASK (0xffffU)
#define MCU_PLLVID_CTRL_1_PLL_15_0_SHIFT (0U)




typedef uint16_t MCU_PLLVID_CTRL_2_TYPE;
#define MCU_PLLVID_CTRL_2_PLL_31_16_MASK (0xffffU)
#define MCU_PLLVID_CTRL_2_PLL_31_16_SHIFT (0U)




typedef uint16_t MCU_PLLVID_CTRL_3_TYPE;
#define MCU_PLLVID_CTRL_3_SPARE_MASK (0xff00U)
#define MCU_PLLVID_CTRL_3_SPARE_SHIFT (8U)
#define MCU_PLLVID_CTRL_3_PLL_CTRL_39_32_MASK (0xffU)
#define MCU_PLLVID_CTRL_3_PLL_CTRL_39_32_SHIFT (0U)




typedef uint16_t MCU_PLLVID_NDIV_FRAC_TYPE;
#define MCU_PLLVID_NDIV_FRAC_15_0_MASK (0xffffU)
#define MCU_PLLVID_NDIV_FRAC_15_0_SHIFT (0U)




typedef uint16_t MCU_PLLVID_NDIV_TYPE;
#define MCU_PLLVID_NDIV_SPARE_MASK (0xc000U)
#define MCU_PLLVID_NDIV_SPARE_SHIFT (14U)
#define MCU_PLLVID_NDIV_NDIV_FRAC_19_16_MASK (0x3c00U)
#define MCU_PLLVID_NDIV_NDIV_FRAC_19_16_SHIFT (10U)
#define MCU_PLLVID_NDIV_NDIV_INT_MASK (0x3ffU)
#define MCU_PLLVID_NDIV_NDIV_INT_SHIFT (0U)




typedef uint16_t MCU_PLLVID_CFG_1_TYPE;
#define MCU_PLLVID_CFG_1_SPARE_MASK (0xfff8U)
#define MCU_PLLVID_CFG_1_SPARE_SHIFT (3U)
#define MCU_PLLVID_CFG_1_POST_RESETB_MASK (0x4U)
#define MCU_PLLVID_CFG_1_POST_RESETB_SHIFT (2U)
#define MCU_PLLVID_CFG_1_RESETB_MASK (0x2U)
#define MCU_PLLVID_CFG_1_RESETB_SHIFT (1U)
#define MCU_PLLVID_CFG_1_PWR_ON_MASK (0x1U)
#define MCU_PLLVID_CFG_1_PWR_ON_SHIFT (0U)




typedef uint16_t MCU_PLLVID_CFG_2_TYPE;
#define MCU_PLLVID_CFG_2_KP_MASK (0x3c00U)
#define MCU_PLLVID_CFG_2_KP_SHIFT (10U)
#define MCU_PLLVID_CFG_2_KI_MASK (0x380U)
#define MCU_PLLVID_CFG_2_KI_SHIFT (7U)
#define MCU_PLLVID_CFG_2_KA_MASK (0x70U)
#define MCU_PLLVID_CFG_2_KA_SHIFT (4U)
#define MCU_PLLVID_CFG_2_PDIV_MASK (0xfU)
#define MCU_PLLVID_CFG_2_PDIV_SHIFT (0U)




typedef uint16_t MCU_PLLVID_CFG_3_TYPE;
#define MCU_PLLVID_CFG_3_SPARE_MASK (0xe000U)
#define MCU_PLLVID_CFG_3_SPARE_SHIFT (13U)
#define MCU_PLLVID_CFG_3_CH0_MDEL_MASK (0x1000U)
#define MCU_PLLVID_CFG_3_CH0_MDEL_SHIFT (12U)
#define MCU_PLLVID_CFG_3_CH0_MDIV_MASK (0xff0U)
#define MCU_PLLVID_CFG_3_CH0_MDIV_SHIFT (4U)
#define MCU_PLLVID_CFG_3_HOLD_CH0_MASK (0x8U)
#define MCU_PLLVID_CFG_3_HOLD_CH0_SHIFT (3U)
#define MCU_PLLVID_CFG_3_ENABLEB_CH0_MASK (0x4U)
#define MCU_PLLVID_CFG_3_ENABLEB_CH0_SHIFT (2U)
#define MCU_PLLVID_CFG_3_BYP_CLK_CH0_MASK (0x2U)
#define MCU_PLLVID_CFG_3_BYP_CLK_CH0_SHIFT (1U)
#define MCU_PLLVID_CFG_3_BYP_EN_CH0_MASK (0x1U)
#define MCU_PLLVID_CFG_3_BYP_EN_CH0_SHIFT (0U)




typedef uint16_t MCU_PLLVID_SSC_1_TYPE;
#define MCU_PLLVID_SSC_1_STEP_MASK (0xffffU)
#define MCU_PLLVID_SSC_1_STEP_SHIFT (0U)




typedef uint16_t MCU_PLLVID_SSC_2_TYPE;
#define MCU_PLLVID_SSC_2_LIMIT_14_0_MASK (0xfffeU)
#define MCU_PLLVID_SSC_2_LIMIT_14_0_SHIFT (1U)
#define MCU_PLLVID_SSC_2_SSC_MODE_MASK (0x1U)
#define MCU_PLLVID_SSC_2_SSC_MODE_SHIFT (0U)




typedef uint16_t MCU_PLLVID_SSC_3_TYPE;
#define MCU_PLLVID_SSC_3_LIMIT_21_15_MASK (0x7fU)
#define MCU_PLLVID_SSC_3_LIMIT_21_15_SHIFT (0U)




typedef uint16_t MCU_PLLVID_STATUS_TYPE;
#define MCU_PLLVID_STATUS_STATUS_MASK (0x3ffcU)
#define MCU_PLLVID_STATUS_STATUS_SHIFT (2U)
#define MCU_PLLVID_STATUS_LOCK_LOST_MASK (0x2U)
#define MCU_PLLVID_STATUS_LOCK_LOST_SHIFT (1U)
#define MCU_PLLVID_STATUS_LOCK_MASK (0x1U)
#define MCU_PLLVID_STATUS_LOCK_SHIFT (0U)




typedef uint16_t MCU_DDRLDO_CFG_TYPE;
#define MCU_DDRLDO_CFG_VREG1P8_PMU_STABLE_MASK (0x40U)
#define MCU_DDRLDO_CFG_VREG1P8_PMU_STABLE_SHIFT (6U)
#define MCU_DDRLDO_CFG_VREG1P2_PMU_STABLE_MASK (0x20U)
#define MCU_DDRLDO_CFG_VREG1P2_PMU_STABLE_SHIFT (5U)
#define MCU_DDRLDO_CFG_VREG1P0_PMU_STABLE_MASK (0x10U)
#define MCU_DDRLDO_CFG_VREG1P0_PMU_STABLE_SHIFT (4U)
#define MCU_DDRLDO_CFG_EN_PULL_DWN_MASK (0x8U)
#define MCU_DDRLDO_CFG_EN_PULL_DWN_SHIFT (3U)
#define MCU_DDRLDO_CFG_BYP_REF_FIL_MASK (0x4U)
#define MCU_DDRLDO_CFG_BYP_REF_FIL_SHIFT (2U)
#define MCU_DDRLDO_CFG_LDO_CNTL_EN_MASK (0x2U)
#define MCU_DDRLDO_CFG_LDO_CNTL_EN_SHIFT (1U)
#define MCU_DDRLDO_CFG_ENB_VDDC_TRACK_MASK (0x1U)
#define MCU_DDRLDO_CFG_ENB_VDDC_TRACK_SHIFT (0U)




typedef uint16_t MCU_DDRLDO_LDO_CNTL_MSB_TYPE;
#define MCU_DDRLDO_LDO_CNTL_MSB_CNTRL_MSB_MASK (0xffffU)
#define MCU_DDRLDO_LDO_CNTL_MSB_CNTRL_MSB_SHIFT (0U)




typedef uint16_t MCU_DDRLDO_LDO_CNTL_LSB_TYPE;
#define MCU_DDRLDO_LDO_CNTL_LSB_CNTRL_LSB_MASK (0xffffU)
#define MCU_DDRLDO_LDO_CNTL_LSB_CNTRL_LSB_SHIFT (0U)




typedef uint16_t MCU_PAD_CFG_TYPE;
#define MCU_PAD_CFG_DISP_IF_EN_MASK (0x800U)
#define MCU_PAD_CFG_DISP_IF_EN_SHIFT (11U)
#define MCU_PAD_CFG_CAM_MODEHV_MASK (0x400U)
#define MCU_PAD_CFG_CAM_MODEHV_SHIFT (10U)
#define MCU_PAD_CFG_GPIO_MODEHV_MASK (0x200U)
#define MCU_PAD_CFG_GPIO_MODEHV_SHIFT (9U)
#define MCU_PAD_CFG_SDIO_MODEHV_MASK (0x100U)
#define MCU_PAD_CFG_SDIO_MODEHV_SHIFT (8U)
#define MCU_PAD_CFG_RGMII_SEL_MASK (0xe0U)
#define MCU_PAD_CFG_RGMII_SEL_SHIFT (5U)
#define MCU_PAD_CFG_RGMII_SRC_MASK (0x18U)
#define MCU_PAD_CFG_RGMII_SRC_SHIFT (3U)
#define MCU_PAD_CFG_RGMII_GMII_SEL_MASK (0x4U)
#define MCU_PAD_CFG_RGMII_GMII_SEL_SHIFT (2U)
#define MCU_PAD_CFG_HSTL_EN_MASK (0x2U)
#define MCU_PAD_CFG_HSTL_EN_SHIFT (1U)
#define MCU_PAD_CFG_RGMII_MODEHV_MASK (0x1U)
#define MCU_PAD_CFG_RGMII_MODEHV_SHIFT (0U)




typedef uint16_t MCU_IMG_TEST_TYPE;
#define MCU_IMG_TEST_PIXELCLK_SEL_MASK (0x600U)
#define MCU_IMG_TEST_PIXELCLK_SEL_SHIFT (9U)
#define MCU_IMG_TEST_VSYNC_SEL_MASK (0x100U)
#define MCU_IMG_TEST_VSYNC_SEL_SHIFT (8U)
#define MCU_IMG_TEST_AWCACHE_MASK (0xf0U)
#define MCU_IMG_TEST_AWCACHE_SHIFT (4U)
#define MCU_IMG_TEST_ARCACHE_MASK (0xfU)
#define MCU_IMG_TEST_ARCACHE_SHIFT (0U)




typedef uint16_t MCU_CHIP_TEST_MODE_TYPE;
#define MCU_CHIP_TEST_MODE_BRPHY_MDIO_BUSY_CTRL_MASK (0x300U)
#define MCU_CHIP_TEST_MODE_BRPHY_MDIO_BUSY_CTRL_SHIFT (8U)
#define MCU_CHIP_TEST_MODE_TEST_ENABLE_MASK (0x7fU)
#define MCU_CHIP_TEST_MODE_TEST_ENABLE_SHIFT (0U)




typedef uint16_t MCU_CLK_PINSTRAP_TYPE;
#define MCU_CLK_PINSTRAP_PLLDISP_REFCLK_SEL_MASK (0x10U)
#define MCU_CLK_PINSTRAP_PLLDISP_REFCLK_SEL_SHIFT (4U)
#define MCU_CLK_PINSTRAP_XTAL_MODE_MASK (0x8U)
#define MCU_CLK_PINSTRAP_XTAL_MODE_SHIFT (3U)
#define MCU_CLK_PINSTRAP_REFCLK_SEL_2_MASK (0x4U)
#define MCU_CLK_PINSTRAP_REFCLK_SEL_2_SHIFT (2U)
#define MCU_CLK_PINSTRAP_REFCLK_SEL_1_MASK (0x2U)
#define MCU_CLK_PINSTRAP_REFCLK_SEL_1_SHIFT (1U)
#define MCU_CLK_PINSTRAP_REFCLK_SEL_0_MASK (0x1U)
#define MCU_CLK_PINSTRAP_REFCLK_SEL_0_SHIFT (0U)




typedef uint16_t MCU_DEBUG_PINSTRAP_TYPE;
#define MCU_DEBUG_PINSTRAP_SW_BOOTUP_STAT_OUT_MASK (0x8U)
#define MCU_DEBUG_PINSTRAP_SW_BOOTUP_STAT_OUT_SHIFT (3U)
#define MCU_DEBUG_PINSTRAP_BOOTUP_FLASH_MASK (0x4U)
#define MCU_DEBUG_PINSTRAP_BOOTUP_FLASH_SHIFT (2U)
#define MCU_DEBUG_PINSTRAP_BOOTUP_CLKDIV_DIS_MASK (0x2U)
#define MCU_DEBUG_PINSTRAP_BOOTUP_CLKDIV_DIS_SHIFT (1U)
#define MCU_DEBUG_PINSTRAP_TESTPIN_DIS_MASK (0x1U)
#define MCU_DEBUG_PINSTRAP_TESTPIN_DIS_SHIFT (0U)




typedef uint16_t MCU_CPU_TEST_TYPE;
#define MCU_CPU_TEST_DFT_CPUINT_MASK (0x10U)
#define MCU_CPU_TEST_DFT_CPUINT_SHIFT (4U)
#define MCU_CPU_TEST_LV_JTAG_BYPASS_MASK (0x8U)
#define MCU_CPU_TEST_LV_JTAG_BYPASS_SHIFT (3U)
#define MCU_CPU_TEST_BRPHY_RDB_RDCLR_EN_MASK (0x4U)
#define MCU_CPU_TEST_BRPHY_RDB_RDCLR_EN_SHIFT (2U)
#define MCU_CPU_TEST_RESET_ENB_MASK (0x2U)
#define MCU_CPU_TEST_RESET_ENB_SHIFT (1U)
#define MCU_CPU_TEST_INITVTOR_SEL_MASK (0x1U)
#define MCU_CPU_TEST_INITVTOR_SEL_SHIFT (0U)




typedef uint16_t MCU_INITVTOR_DBG_0_TYPE;
#define MCU_INITVTOR_DBG_0_0_MASK (0xffffU)
#define MCU_INITVTOR_DBG_0_0_SHIFT (0U)




typedef uint16_t MCU_INITVTOR_DBG_1_TYPE;
#define MCU_INITVTOR_DBG_1_1_MASK (0x1ffU)
#define MCU_INITVTOR_DBG_1_1_SHIFT (0U)




typedef uint16_t MCU_VID_RESET_STAT_TYPE;
#define MCU_VID_RESET_STAT_STAT_MASK (0x3ffU)
#define MCU_VID_RESET_STAT_STAT_SHIFT (0U)




typedef uint16_t MCU_TEST_PIN_SEL_0_TYPE;
#define MCU_TEST_PIN_SEL_0_EN_MASK (0xffffU)
#define MCU_TEST_PIN_SEL_0_EN_SHIFT (0U)




typedef uint16_t MCU_TEST_PIN_SEL_1_TYPE;
#define MCU_TEST_PIN_SEL_1_EN_MASK (0xffffU)
#define MCU_TEST_PIN_SEL_1_EN_SHIFT (0U)




typedef uint16_t MCU_TEST_PIN_SEL_2_TYPE;
#define MCU_TEST_PIN_SEL_2_EN_MASK (0xffffU)
#define MCU_TEST_PIN_SEL_2_EN_SHIFT (0U)




typedef uint16_t MCU_TPIN_REG_0_TYPE;
#define MCU_TPIN_REG_0_15_00_MASK (0xffffU)
#define MCU_TPIN_REG_0_15_00_SHIFT (0U)




typedef uint16_t MCU_TPIN_REG_1_TYPE;
#define MCU_TPIN_REG_1_31_16_MASK (0xffffU)
#define MCU_TPIN_REG_1_31_16_SHIFT (0U)




typedef uint16_t MCU_TPOUT_REG_0_TYPE;
#define MCU_TPOUT_REG_0_15_00_MASK (0xffffU)
#define MCU_TPOUT_REG_0_15_00_SHIFT (0U)




typedef uint16_t MCU_TPOUT_REG_1_TYPE;
#define MCU_TPOUT_REG_1_31_16_MASK (0xffffU)
#define MCU_TPOUT_REG_1_31_16_SHIFT (0U)




typedef uint16_t MCU_PLL_INTR_TYPE;
#define MCU_PLL_INTR_PLLVID_MASK_MASK (0x200U)
#define MCU_PLL_INTR_PLLVID_MASK_SHIFT (9U)
#define MCU_PLL_INTR_PLLDISP_MASK_MASK (0x100U)
#define MCU_PLL_INTR_PLLDISP_MASK_SHIFT (8U)
#define MCU_PLL_INTR_PLLVID_INTR_MASK (0x2U)
#define MCU_PLL_INTR_PLLVID_INTR_SHIFT (1U)
#define MCU_PLL_INTR_PLLDISP_INTR_MASK (0x1U)
#define MCU_PLL_INTR_PLLDISP_INTR_SHIFT (0U)




typedef uint16_t MCU_DDR_MISC_TYPE;
#define MCU_DDR_MISC_MEMC_SELFREF_MASK (0x4U)
#define MCU_DDR_MISC_MEMC_SELFREF_SHIFT (2U)
#define MCU_DDR_MISC_FORCE_DDR_IDDQ_MASK (0x2U)
#define MCU_DDR_MISC_FORCE_DDR_IDDQ_SHIFT (1U)
#define MCU_DDR_MISC_FORCE_DDR_RESET_MASK (0x1U)
#define MCU_DDR_MISC_FORCE_DDR_RESET_SHIFT (0U)




typedef uint16_t MCU_LED_CTRL_TYPE;
#define MCU_LED_CTRL_DRV_MASK (0x70U)
#define MCU_LED_CTRL_DRV_SHIFT (4U)
#define MCU_LED_CTRL_SELECT_MASK (0xcU)
#define MCU_LED_CTRL_SELECT_SHIFT (2U)
#define MCU_LED_CTRL_POLARITY_MASK (0x2U)
#define MCU_LED_CTRL_POLARITY_SHIFT (1U)
#define MCU_LED_CTRL_ENABLE_MASK (0x1U)
#define MCU_LED_CTRL_ENABLE_SHIFT (0U)




typedef uint16_t MCU_SPARE_REG_1_TYPE;
#define MCU_SPARE_REG_1_OSC_LFO_CTRL2_MASK (0xff00U)
#define MCU_SPARE_REG_1_OSC_LFO_CTRL2_SHIFT (8U)
#define MCU_SPARE_REG_1_SPARE_REG_MASK (0xf0U)
#define MCU_SPARE_REG_1_SPARE_REG_SHIFT (4U)
#define MCU_SPARE_REG_1_DBG_HILO_SWAP_MASK (0x8U)
#define MCU_SPARE_REG_1_DBG_HILO_SWAP_SHIFT (3U)
#define MCU_SPARE_REG_1_DBG_BLK_MUX_SEL_MASK (0x7U)
#define MCU_SPARE_REG_1_DBG_BLK_MUX_SEL_SHIFT (0U)




typedef volatile struct COMP_PACKED _MCU_RDBType {
    MCU_SPARE_REG_0_TYPE spare_reg_0; /* OFFSET: 0x0 */
    MCU_XTAL_CTRL_1_TYPE xtal_ctrl_1; /* OFFSET: 0x2 */
    MCU_XTAL_CTRL_2_TYPE xtal_ctrl_2; /* OFFSET: 0x4 */
    MCU_XTAL_CTRL_3_TYPE xtal_ctrl_3; /* OFFSET: 0x6 */
    MCU_RCOSC_CFG_TYPE rcosc_cfg; /* OFFSET: 0x8 */
    MCU_RCOSC_STAT_TYPE rcosc_stat; /* OFFSET: 0xa */
    MCU_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0xc */
    MCU_RCOSC_CTRL_TYPE rcosc_ctrl; /* OFFSET: 0x10 */
    MCU_PLLSYS_CTRL_1_TYPE pllsys_ctrl_1; /* OFFSET: 0x12 */
    MCU_PLLSYS_CTRL_2_TYPE pllsys_ctrl_2; /* OFFSET: 0x14 */
    MCU_PLLSYS_CTRL_3_TYPE pllsys_ctrl_3; /* OFFSET: 0x16 */
    MCU_PLLSYS_NDIV_FRAC_TYPE pllsys_ndiv_frac; /* OFFSET: 0x18 */
    MCU_PLLSYS_NDIV_TYPE pllsys_ndiv; /* OFFSET: 0x1a */
    MCU_PLLSYS_CFG_1_TYPE pllsys_cfg_1; /* OFFSET: 0x1c */
    MCU_PLLSYS_CFG_2_TYPE pllsys_cfg_2; /* OFFSET: 0x1e */
    MCU_PLLSYS_CFG_3_TYPE pllsys_cfg_3; /* OFFSET: 0x20 */
    MCU_PLLSYS_MDIV_1_TYPE pllsys_mdiv_1; /* OFFSET: 0x22 */
    MCU_PLLSYS_MDIV_2_TYPE pllsys_mdiv_2; /* OFFSET: 0x24 */
    MCU_PLLSYS_SSC_1_TYPE pllsys_ssc_1; /* OFFSET: 0x26 */
    MCU_PLLSYS_SSC_2_TYPE pllsys_ssc_2; /* OFFSET: 0x28 */
    MCU_PLLSYS_SSC_3_TYPE pllsys_ssc_3; /* OFFSET: 0x2a */
    MCU_PLLSYS_STATUS_TYPE pllsys_status; /* OFFSET: 0x2c */
    MCU_PLLDISP_CTRL_1_TYPE plldisp_ctrl_1; /* OFFSET: 0x2e */
    MCU_PLLDISP_CTRL_2_TYPE plldisp_ctrl_2; /* OFFSET: 0x30 */
    MCU_PLLDISP_CTRL_3_TYPE plldisp_ctrl_3; /* OFFSET: 0x32 */
    MCU_PLLDISP_NDIV_FRAC_TYPE plldisp_ndiv_frac; /* OFFSET: 0x34 */
    MCU_PLLDISP_NDIV_TYPE plldisp_ndiv; /* OFFSET: 0x36 */
    MCU_PLLDISP_CFG_1_TYPE plldisp_cfg_1; /* OFFSET: 0x38 */
    MCU_PLLDISP_CFG_2_TYPE plldisp_cfg_2; /* OFFSET: 0x3a */
    MCU_PLLDISP_CFG_3_TYPE plldisp_cfg_3; /* OFFSET: 0x3c */
    MCU_PLLDISP_SSC_1_TYPE plldisp_ssc_1; /* OFFSET: 0x3e */
    MCU_PLLDISP_SSC_2_TYPE plldisp_ssc_2; /* OFFSET: 0x40 */
    MCU_PLLDISP_SSC_3_TYPE plldisp_ssc_3; /* OFFSET: 0x42 */
    MCU_PLLDISP_STATUS_TYPE plldisp_status; /* OFFSET: 0x44 */
    MCU_PLLVID_CTRL_1_TYPE pllvid_ctrl_1; /* OFFSET: 0x46 */
    MCU_PLLVID_CTRL_2_TYPE pllvid_ctrl_2; /* OFFSET: 0x48 */
    MCU_PLLVID_CTRL_3_TYPE pllvid_ctrl_3; /* OFFSET: 0x4a */
    MCU_PLLVID_NDIV_FRAC_TYPE pllvid_ndiv_frac; /* OFFSET: 0x4c */
    MCU_PLLVID_NDIV_TYPE pllvid_ndiv; /* OFFSET: 0x4e */
    MCU_PLLVID_CFG_1_TYPE pllvid_cfg_1; /* OFFSET: 0x50 */
    MCU_PLLVID_CFG_2_TYPE pllvid_cfg_2; /* OFFSET: 0x52 */
    MCU_PLLVID_CFG_3_TYPE pllvid_cfg_3; /* OFFSET: 0x54 */
    MCU_PLLVID_SSC_1_TYPE pllvid_ssc_1; /* OFFSET: 0x56 */
    MCU_PLLVID_SSC_2_TYPE pllvid_ssc_2; /* OFFSET: 0x58 */
    MCU_PLLVID_SSC_3_TYPE pllvid_ssc_3; /* OFFSET: 0x5a */
    MCU_PLLVID_STATUS_TYPE pllvid_status; /* OFFSET: 0x5c */
    MCU_RESERVED_TYPE rsvd1[18]; /* OFFSET: 0x5e */
    MCU_DDRLDO_CFG_TYPE ddrldo_cfg; /* OFFSET: 0x70 */
    MCU_DDRLDO_LDO_CNTL_MSB_TYPE ddrldo_ldo_cntl_msb; /* OFFSET: 0x72 */
    MCU_DDRLDO_LDO_CNTL_LSB_TYPE ddrldo_ldo_cntl_lsb; /* OFFSET: 0x74 */
    MCU_PAD_CFG_TYPE pad_cfg; /* OFFSET: 0x76 */
    MCU_IMG_TEST_TYPE img_test; /* OFFSET: 0x78 */
    MCU_RESERVED_TYPE rsvd2[38]; /* OFFSET: 0x7a */
    MCU_CHIP_TEST_MODE_TYPE chip_test_mode; /* OFFSET: 0xa0 */
    MCU_CLK_PINSTRAP_TYPE clk_pinstrap; /* OFFSET: 0xa2 */
    MCU_DEBUG_PINSTRAP_TYPE debug_pinstrap; /* OFFSET: 0xa4 */
    MCU_CPU_TEST_TYPE cpu_test; /* OFFSET: 0xa6 */
    MCU_INITVTOR_DBG_0_TYPE initvtor_dbg_0; /* OFFSET: 0xa8 */
    MCU_INITVTOR_DBG_1_TYPE initvtor_dbg_1; /* OFFSET: 0xaa */
    MCU_VID_RESET_STAT_TYPE vid_reset_stat; /* OFFSET: 0xac */
    MCU_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xae */
    MCU_TEST_PIN_SEL_0_TYPE test_pin_sel_0; /* OFFSET: 0xb0 */
    MCU_TEST_PIN_SEL_1_TYPE test_pin_sel_1; /* OFFSET: 0xb2 */
    MCU_TEST_PIN_SEL_2_TYPE test_pin_sel_2; /* OFFSET: 0xb4 */
    MCU_TPIN_REG_0_TYPE tpin_reg_0; /* OFFSET: 0xb6 */
    MCU_TPIN_REG_1_TYPE tpin_reg_1; /* OFFSET: 0xb8 */
    MCU_TPOUT_REG_0_TYPE tpout_reg_0; /* OFFSET: 0xba */
    MCU_TPOUT_REG_1_TYPE tpout_reg_1; /* OFFSET: 0xbc */
    MCU_RESERVED_TYPE rsvd4[2]; /* OFFSET: 0xbe */
    MCU_PLL_INTR_TYPE pll_intr; /* OFFSET: 0xc0 */
    MCU_DDR_MISC_TYPE ddr_misc; /* OFFSET: 0xc2 */
    MCU_LED_CTRL_TYPE led_ctrl; /* OFFSET: 0xc4 */
    MCU_SPARE_REG_1_TYPE spare_reg_1; /* OFFSET: 0xc6 */
    MCU_RESERVED_TYPE rsvd5[1848]; /* OFFSET: 0xc8 */
} MCU_RDBType;


#define MCU_BASE                        (0x42800000UL)



#define MCU_MAX_HW_ID                   (1UL)


#define MCU_TEST_PIN_SEL_2_GTX_CLK_MASK  (0x0400U)


#define MCU_TEST_PIN_SEL_2_TX_EN_MASK   (0x0200U)


#define MCU_TEST_PIN_SEL_2_TXD_3_MASK   (0x0100U)


#define MCU_TEST_PIN_SEL_2_TXD_2_MASK   (0x0080U)


#define MCU_TEST_PIN_SEL_2_TXD_1_MASK   (0x0040U)


#define MCU_TEST_PIN_SEL_2_TXD_0_MASK   (0x0020U)


#define MCU_REVISION_A0                 (0x0UL)


#define MCU_REVISION_B0                 (0x1UL)


#define MCU_REVISION_C0                 (0x2UL)

#endif /* MCU_RDB_H */
