/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_lpmmemc_rdb.h
    @brief RDB File for MEMC_LPMMEMC

    @version 2018May25_rdb
*/

#ifndef MEMC_LPMMEMC_RDB_H
#define MEMC_LPMMEMC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t MEMC_LPMMEMC_INTERRUPT_STATUS_TYPE;
#define MEMC_LPMMEMC_INTERRUPT_STATUS_MEASURE_STATUS_MASK (0x4000U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_MEASURE_STATUS_SHIFT (14U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_VREQ_STATUS_MASK (0x2000U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_VREQ_STATUS_SHIFT (13U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_WASP_STATUS_MASK (0x1000U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_WASP_STATUS_SHIFT (12U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_GPIOSUBSYSTEM_STATUS_MASK (0x800U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_GPIOSUBSYSTEM_STATUS_SHIFT (11U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_GPIOSUBSYSTEM2_STATUS_MASK (0x400U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_GPIOSUBSYSTEM2_STATUS_SHIFT (10U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_CLOCK_STATUS_MASK (0x200U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_CLOCK_STATUS_SHIFT (9U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_RESETN_STATUS_MASK (0x80U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_RESETN_STATUS_SHIFT (7U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PLL1_STATUS_MASK (0x20U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PLL1_STATUS_SHIFT (5U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PLL0_STATUS_MASK (0x10U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PLL0_STATUS_SHIFT (4U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PWROK_STATUS_MASK (0x2U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PWROK_STATUS_SHIFT (1U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PWRON_STATUS_MASK (0x1U)
#define MEMC_LPMMEMC_INTERRUPT_STATUS_PWRON_STATUS_SHIFT (0U)




typedef uint8_t MEMC_LPMMEMC_RESERVED_TYPE;




typedef uint16_t MEMC_LPMMEMC_INTERRUPT_ENABLE_TYPE;
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_MEASURE_INT_ENABLE_MASK (0x4000U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_MEASURE_INT_ENABLE_SHIFT (14U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_VREQ_INT_ENABLE_MASK (0x2000U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_VREQ_INT_ENABLE_SHIFT (13U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_WASP_INT_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_WASP_INT_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_GPIOSUBSYSTEM_INT_ENABLE_MASK (0x800U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_GPIOSUBSYSTEM_INT_ENABLE_SHIFT (11U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_GPIOSUBSYSTEM2_INT_ENABLE_MASK (0x400U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_GPIOSUBSYSTEM2_INT_ENABLE_SHIFT (10U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_CLOCK_INT_ENABLE_MASK (0x200U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_CLOCK_INT_ENABLE_SHIFT (9U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_RESETN_INT_ENABLE_MASK (0x80U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_RESETN_INT_ENABLE_SHIFT (7U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PLL1_INT_ENABLE_MASK (0x20U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PLL1_INT_ENABLE_SHIFT (5U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PLL0_INT_ENABLE_MASK (0x10U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PLL0_INT_ENABLE_SHIFT (4U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PWROK_INT_ENABLE_MASK (0x2U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PWROK_INT_ENABLE_SHIFT (1U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PWRON_INT_ENABLE_MASK (0x1U)
#define MEMC_LPMMEMC_INTERRUPT_ENABLE_PWRON_INT_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CRYSTAL_CONTROL_TYPE;
#define MEMC_LPMMEMC_CRYSTAL_CONTROL_DIG_HW_SW_ENABLE_SEL_MASK (0x300U)
#define MEMC_LPMMEMC_CRYSTAL_CONTROL_DIG_HW_SW_ENABLE_SEL_SHIFT (8U)
#define MEMC_LPMMEMC_CRYSTAL_CONTROL_52M_26M_MASK (0x1U)
#define MEMC_LPMMEMC_CRYSTAL_CONTROL_52M_26M_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_MODE_CONTROL_TYPE;
#define MEMC_LPMMEMC_CLOCK_MODE_CONTROL_TRIGGER_CNTD_MASK (0x1U)
#define MEMC_LPMMEMC_CLOCK_MODE_CONTROL_TRIGGER_CNTD_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_RESETN_CONTROL_TYPE;
#define MEMC_LPMMEMC_RESETN_CONTROL_COUNT_MASK (0x3fU)
#define MEMC_LPMMEMC_RESETN_CONTROL_COUNT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_WASP_CONTROL_TYPE;
#define MEMC_LPMMEMC_WASP_CONTROL_WASP_STATUS_MASK (0x8000U)
#define MEMC_LPMMEMC_WASP_CONTROL_WASP_STATUS_SHIFT (15U)
#define MEMC_LPMMEMC_WASP_CONTROL_CFG_SPM_HARDWARE_ENABLE_MASK (0x1U)
#define MEMC_LPMMEMC_WASP_CONTROL_CFG_SPM_HARDWARE_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_APB_BRIDGE_CONTROL_TYPE;
#define MEMC_LPMMEMC_APB_BRIDGE_CONTROL_TIMEOUT_MASK (0xffffU)
#define MEMC_LPMMEMC_APB_BRIDGE_CONTROL_TIMEOUT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_IDLE_STATUS_TYPE;
#define MEMC_LPMMEMC_IDLE_STATUS_EXT_SOURCE_IDLE_MASK (0xff00U)
#define MEMC_LPMMEMC_IDLE_STATUS_EXT_SOURCE_IDLE_SHIFT (8U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_DIG_ENABLED_MASK (0x80U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_DIG_ENABLED_SHIFT (7U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_MEASUREMENT_IS_IDLE_MASK (0x8U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_MEASUREMENT_IS_IDLE_SHIFT (3U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_DIG_IDLE_MASK (0x4U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_DIG_IDLE_SHIFT (2U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_PLL_IDLE_MASK (0x2U)
#define MEMC_LPMMEMC_IDLE_STATUS_CRYSTAL_PLL_IDLE_SHIFT (1U)
#define MEMC_LPMMEMC_IDLE_STATUS_CK32K_IDLE_MASK (0x1U)
#define MEMC_LPMMEMC_IDLE_STATUS_CK32K_IDLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CSD_TYPE;
#define MEMC_LPMMEMC_CSD_DETECT_COUNTER_MASK (0xff00U)
#define MEMC_LPMMEMC_CSD_DETECT_COUNTER_SHIFT (8U)
#define MEMC_LPMMEMC_CSD_PLL_CHANNEL1_ENABLE_DETECTION_MASK (0x2U)
#define MEMC_LPMMEMC_CSD_PLL_CHANNEL1_ENABLE_DETECTION_SHIFT (1U)
#define MEMC_LPMMEMC_CSD_PLL_CHANNEL0_ENABLE_DETECTION_MASK (0x1U)
#define MEMC_LPMMEMC_CSD_PLL_CHANNEL0_ENABLE_DETECTION_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL_PWR_ON_TYPE;
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_POST_RESETB_MASK (0x20U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_POST_RESETB_SHIFT (5U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_RESETB_MASK (0x10U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_RESETB_SHIFT (4U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_ISO_PLL_OUT_MASK (0x8U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_ISO_PLL_OUT_SHIFT (3U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_ISO_PLL_MASK (0x4U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_ISO_PLL_SHIFT (2U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_PWRON_LDO_MASK (0x2U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_PWRON_LDO_SHIFT (1U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_PWRON_PLL_MASK (0x1U)
#define MEMC_LPMMEMC_PLL_PWR_ON_PLL0_PWRON_PLL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL_COMMAND_TYPE;
#define MEMC_LPMMEMC_PLL_COMMAND_UPDATE_PLL0_FREQUENCY_POST_MASK (0x2U)
#define MEMC_LPMMEMC_PLL_COMMAND_UPDATE_PLL0_FREQUENCY_POST_SHIFT (1U)
#define MEMC_LPMMEMC_PLL_COMMAND_UPDATE_PLL0_FREQUENCY_VCO_MASK (0x1U)
#define MEMC_LPMMEMC_PLL_COMMAND_UPDATE_PLL0_FREQUENCY_VCO_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL_STATUS_TYPE;
#define MEMC_LPMMEMC_PLL_STATUS_PLL0_LOCK_MASK (0x200U)
#define MEMC_LPMMEMC_PLL_STATUS_PLL0_LOCK_SHIFT (9U)
#define MEMC_LPMMEMC_PLL_STATUS_PLL0_LOCK_LOST_MASK (0x100U)
#define MEMC_LPMMEMC_PLL_STATUS_PLL0_LOCK_LOST_SHIFT (8U)




typedef uint16_t MEMC_LPMMEMC_PIE_TYPE;
#define MEMC_LPMMEMC_PIE_PLL0_LOCK_STATUS_INT_ENB_MASK (0x200U)
#define MEMC_LPMMEMC_PIE_PLL0_LOCK_STATUS_INT_ENB_SHIFT (9U)
#define MEMC_LPMMEMC_PIE_PLL0_LOCK_LOST_STATUS_INT_ENB_MASK (0x100U)
#define MEMC_LPMMEMC_PIE_PLL0_LOCK_LOST_STATUS_INT_ENB_SHIFT (8U)




typedef uint16_t MEMC_LPMMEMC_PLL_INTERRUPT_STATUS_TYPE;
#define MEMC_LPMMEMC_PLL_INTERRUPT_STATUS_PLL0_LOCK_STATUS_MASK (0x200U)
#define MEMC_LPMMEMC_PLL_INTERRUPT_STATUS_PLL0_LOCK_STATUS_SHIFT (9U)
#define MEMC_LPMMEMC_PLL_INTERRUPT_STATUS_PLL0_LOCK_LOST_STATUS_MASK (0x100U)
#define MEMC_LPMMEMC_PLL_INTERRUPT_STATUS_PLL0_LOCK_LOST_STATUS_SHIFT (8U)




typedef uint16_t MEMC_LPMMEMC_P0CC_TYPE;
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL5_ENABLE_SEL_MASK (0xc00U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL5_ENABLE_SEL_SHIFT (10U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL4_ENABLE_SEL_MASK (0x300U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL4_ENABLE_SEL_SHIFT (8U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL3_ENABLE_SEL_MASK (0xc0U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL3_ENABLE_SEL_SHIFT (6U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL2_ENABLE_SEL_MASK (0x30U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL2_ENABLE_SEL_SHIFT (4U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL1_ENABLE_SEL_MASK (0xcU)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL1_ENABLE_SEL_SHIFT (2U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL0_ENABLE_SEL_MASK (0x3U)
#define MEMC_LPMMEMC_P0CC_PLL0_CHANNEL0_ENABLE_SEL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL_CHANNEL_STATUS_TYPE;
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_5_ENABLED_MASK (0x20U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_5_ENABLED_SHIFT (5U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_4_ENABLED_MASK (0x10U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_4_ENABLED_SHIFT (4U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_3_ENABLED_MASK (0x8U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_3_ENABLED_SHIFT (3U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_2_ENABLED_MASK (0x4U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_2_ENABLED_SHIFT (2U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_1_ENABLED_MASK (0x2U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_1_ENABLED_SHIFT (1U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_0_ENABLED_MASK (0x1U)
#define MEMC_LPMMEMC_PLL_CHANNEL_STATUS_0_0_ENABLED_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PCABE_TYPE;
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_5_BYPASS_ENABLE_MASK (0x20U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_5_BYPASS_ENABLE_SHIFT (5U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_4_BYPASS_ENABLE_MASK (0x10U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_4_BYPASS_ENABLE_SHIFT (4U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_3_BYPASS_ENABLE_MASK (0x8U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_3_BYPASS_ENABLE_SHIFT (3U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_2_BYPASS_ENABLE_MASK (0x4U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_2_BYPASS_ENABLE_SHIFT (2U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_1_BYPASS_ENABLE_MASK (0x2U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_1_BYPASS_ENABLE_SHIFT (1U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_0_BYPASS_ENABLE_MASK (0x1U)
#define MEMC_LPMMEMC_PCABE_PLL_0_CHANNEL_0_BYPASS_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL1_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL1_NDIV_FRAC_LSB_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CTRL1_NDIV_FRAC_LSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL2_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL2_NDIV_FRAC_MSB_MASK (0xfU)
#define MEMC_LPMMEMC_PLL0_CTRL2_NDIV_FRAC_MSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL3_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL3_PDIV_MASK (0xf000U)
#define MEMC_LPMMEMC_PLL0_CTRL3_PDIV_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CTRL3_NDIV_INT_MASK (0x3ffU)
#define MEMC_LPMMEMC_PLL0_CTRL3_NDIV_INT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL4_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL4_KA_MASK (0x380U)
#define MEMC_LPMMEMC_PLL0_CTRL4_KA_SHIFT (7U)
#define MEMC_LPMMEMC_PLL0_CTRL4_KI_MASK (0x70U)
#define MEMC_LPMMEMC_PLL0_CTRL4_KI_SHIFT (4U)
#define MEMC_LPMMEMC_PLL0_CTRL4_KP_MASK (0xfU)
#define MEMC_LPMMEMC_PLL0_CTRL4_KP_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL_SSC0_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL_SSC0_PLL0SSC_STEP_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CTRL_SSC0_PLL0SSC_STEP_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL_SSC1_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL_SSC1_SSC_LIMIT_LSB_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CTRL_SSC1_SSC_LIMIT_LSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CTRL_SSC2_TYPE;
#define MEMC_LPMMEMC_PLL0_CTRL_SSC2_SCC_MODE_MASK (0x8000U)
#define MEMC_LPMMEMC_PLL0_CTRL_SSC2_SCC_MODE_SHIFT (15U)
#define MEMC_LPMMEMC_PLL0_CTRL_SSC2_SSC_LIMIT_MSB_MASK (0x3fU)
#define MEMC_LPMMEMC_PLL0_CTRL_SSC2_SSC_LIMIT_MSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_STATUS_OUT_TYPE;
#define MEMC_LPMMEMC_PLL0_STATUS_OUT_VALUE_MASK (0xfffU)
#define MEMC_LPMMEMC_PLL0_STATUS_OUT_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CFG0_CTRL_TYPE;
#define MEMC_LPMMEMC_PLL0_CFG0_CTRL_CFG_VALUE_A0_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CFG0_CTRL_CFG_VALUE_A0_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CFG1_CTRL_TYPE;
#define MEMC_LPMMEMC_PLL0_CFG1_CTRL_CFG_VALUE_A1_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CFG1_CTRL_CFG_VALUE_A1_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CFG2_CTRL_TYPE;
#define MEMC_LPMMEMC_PLL0_CFG2_CTRL_CFG_VALUE_A2_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CFG2_CTRL_CFG_VALUE_A2_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CFG3_CTRL_TYPE;
#define MEMC_LPMMEMC_PLL0_CFG3_CTRL_CFG_VALUE_A3_MASK (0xffffU)
#define MEMC_LPMMEMC_PLL0_CFG3_CTRL_CFG_VALUE_A3_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CHANNEL0_DESCRIPTION_TYPE;
#define MEMC_LPMMEMC_PLL0_CHANNEL0_DESCRIPTION_MDEL_MASK (0x7000U)
#define MEMC_LPMMEMC_PLL0_CHANNEL0_DESCRIPTION_MDEL_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CHANNEL0_DESCRIPTION_MDIV_MASK (0xffU)
#define MEMC_LPMMEMC_PLL0_CHANNEL0_DESCRIPTION_MDIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CHANNEL1_DESCRIPTION_TYPE;
#define MEMC_LPMMEMC_PLL0_CHANNEL1_DESCRIPTION_MDEL_MASK (0x7000U)
#define MEMC_LPMMEMC_PLL0_CHANNEL1_DESCRIPTION_MDEL_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CHANNEL1_DESCRIPTION_MDIV_MASK (0xffU)
#define MEMC_LPMMEMC_PLL0_CHANNEL1_DESCRIPTION_MDIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CHANNEL2_DESCRIPTION_TYPE;
#define MEMC_LPMMEMC_PLL0_CHANNEL2_DESCRIPTION_MDEL_MASK (0x7000U)
#define MEMC_LPMMEMC_PLL0_CHANNEL2_DESCRIPTION_MDEL_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CHANNEL2_DESCRIPTION_MDIV_MASK (0xffU)
#define MEMC_LPMMEMC_PLL0_CHANNEL2_DESCRIPTION_MDIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CHANNEL3_DESCRIPTION_TYPE;
#define MEMC_LPMMEMC_PLL0_CHANNEL3_DESCRIPTION_MDEL_MASK (0x7000U)
#define MEMC_LPMMEMC_PLL0_CHANNEL3_DESCRIPTION_MDEL_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CHANNEL3_DESCRIPTION_MDIV_MASK (0xffU)
#define MEMC_LPMMEMC_PLL0_CHANNEL3_DESCRIPTION_MDIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CHANNEL4_DESCRIPTION_TYPE;
#define MEMC_LPMMEMC_PLL0_CHANNEL4_DESCRIPTION_MDEL_MASK (0x7000U)
#define MEMC_LPMMEMC_PLL0_CHANNEL4_DESCRIPTION_MDEL_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CHANNEL4_DESCRIPTION_MDIV_MASK (0xffU)
#define MEMC_LPMMEMC_PLL0_CHANNEL4_DESCRIPTION_MDIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PLL0_CHANNEL5_DESCRIPTION_TYPE;
#define MEMC_LPMMEMC_PLL0_CHANNEL5_DESCRIPTION_MDEL_MASK (0x7000U)
#define MEMC_LPMMEMC_PLL0_CHANNEL5_DESCRIPTION_MDEL_SHIFT (12U)
#define MEMC_LPMMEMC_PLL0_CHANNEL5_DESCRIPTION_MDIV_MASK (0xffU)
#define MEMC_LPMMEMC_PLL0_CHANNEL5_DESCRIPTION_MDIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CIS_TYPE;
#define MEMC_LPMMEMC_CIS_CLOCKS_DISABLED_STATUS_MASK (0x100U)
#define MEMC_LPMMEMC_CIS_CLOCKS_DISABLED_STATUS_SHIFT (8U)
#define MEMC_LPMMEMC_CIS_CLOCKS_STABLE_STATUS_MASK (0x1U)
#define MEMC_LPMMEMC_CIS_CLOCKS_STABLE_STATUS_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_INT_ENABLE_TYPE;
#define MEMC_LPMMEMC_CLOCK_INT_ENABLE_CLOCKS_DISABLED_ENB_MASK (0x100U)
#define MEMC_LPMMEMC_CLOCK_INT_ENABLE_CLOCKS_DISABLED_ENB_SHIFT (8U)
#define MEMC_LPMMEMC_CLOCK_INT_ENABLE_CLOCKS_STABLE_ENB_MASK (0x1U)
#define MEMC_LPMMEMC_CLOCK_INT_ENABLE_CLOCKS_STABLE_ENB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_STATUS_TYPE;
#define MEMC_LPMMEMC_CLOCK_STATUS_CLOCKS_CLK_DISABLED_MASK (0x100U)
#define MEMC_LPMMEMC_CLOCK_STATUS_CLOCKS_CLK_DISABLED_SHIFT (8U)
#define MEMC_LPMMEMC_CLOCK_STATUS_CLOCKS_CLK_STABLE_MASK (0x1U)
#define MEMC_LPMMEMC_CLOCK_STATUS_CLOCKS_CLK_STABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOC_CONT_0_TYPE;
#define MEMC_LPMMEMC_CLOC_CONT_0_DFT_OBSERVE_CLK_HW_SW_ENABLE_SEL_MASK (0xc000U)
#define MEMC_LPMMEMC_CLOC_CONT_0_DFT_OBSERVE_CLK_HW_SW_ENABLE_SEL_SHIFT (14U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PHY_CTL_RD_HW_SW_ENABLE_SEL_MASK (0xc00U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PHY_CTL_RD_HW_SW_ENABLE_SEL_SHIFT (10U)
#define MEMC_LPMMEMC_CLOC_CONT_0_MEMC_DDRCLK_HW_SW_ENABLE_SEL_MASK (0x300U)
#define MEMC_LPMMEMC_CLOC_CONT_0_MEMC_DDRCLK_HW_SW_ENABLE_SEL_SHIFT (8U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_PCLK_HW_SW_ENABLE_SEL_MASK (0xc0U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_PCLK_HW_SW_ENABLE_SEL_SHIFT (6U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_CTL_SDR_HW_SW_ENABLE_SEL_MASK (0x30U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_CTL_SDR_HW_SW_ENABLE_SEL_SHIFT (4U)
#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_CTL_HW_SW_ENABLE_SEL_MASK (0xcU)
#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_CTL_HW_SW_ENABLE_SEL_SHIFT (2U)
#define MEMC_LPMMEMC_CLOC_CONT_0_MEMC_PCLK_HW_SW_ENABLE_SEL_MASK (0x3U)
#define MEMC_LPMMEMC_CLOC_CONT_0_MEMC_PCLK_HW_SW_ENABLE_SEL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOC_CONT_1_TYPE;
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK6_HW_SW_ENABLE_SEL_MASK (0xc000U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK6_HW_SW_ENABLE_SEL_SHIFT (14U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK5_HW_SW_ENABLE_SEL_MASK (0x3000U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK5_HW_SW_ENABLE_SEL_SHIFT (12U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK4_HW_SW_ENABLE_SEL_MASK (0xc00U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK4_HW_SW_ENABLE_SEL_SHIFT (10U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK3_HW_SW_ENABLE_SEL_MASK (0x300U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK3_HW_SW_ENABLE_SEL_SHIFT (8U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK2_HW_SW_ENABLE_SEL_MASK (0xc0U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK2_HW_SW_ENABLE_SEL_SHIFT (6U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK1_HW_SW_ENABLE_SEL_MASK (0x30U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK1_HW_SW_ENABLE_SEL_SHIFT (4U)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK0_HW_SW_ENABLE_SEL_MASK (0xcU)
#define MEMC_LPMMEMC_CLOC_CONT_1_DFT_SCAN_CLK0_HW_SW_ENABLE_SEL_SHIFT (2U)
#define MEMC_LPMMEMC_CLOC_CONT_1_ATB_CLK_HW_SW_ENABLE_SEL_MASK (0x3U)
#define MEMC_LPMMEMC_CLOC_CONT_1_ATB_CLK_HW_SW_ENABLE_SEL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CIE0_TYPE;
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK6_INT_ENABLE_MASK (0x8000U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK6_INT_ENABLE_SHIFT (15U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK5_INT_ENABLE_MASK (0x4000U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK5_INT_ENABLE_SHIFT (14U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK4_INT_ENABLE_MASK (0x2000U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK4_INT_ENABLE_SHIFT (13U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK3_INT_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK3_INT_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK2_INT_ENABLE_MASK (0x800U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK2_INT_ENABLE_SHIFT (11U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK1_INT_ENABLE_MASK (0x400U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK1_INT_ENABLE_SHIFT (10U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK0_INT_ENABLE_MASK (0x200U)
#define MEMC_LPMMEMC_CIE0_DFT_SCAN_CLK0_INT_ENABLE_SHIFT (9U)
#define MEMC_LPMMEMC_CIE0_ATB_CLK_INT_ENABLE_MASK (0x100U)
#define MEMC_LPMMEMC_CIE0_ATB_CLK_INT_ENABLE_SHIFT (8U)
#define MEMC_LPMMEMC_CIE0_DFT_OBSERVE_CLK_INT_ENABLE_MASK (0x80U)
#define MEMC_LPMMEMC_CIE0_DFT_OBSERVE_CLK_INT_ENABLE_SHIFT (7U)
#define MEMC_LPMMEMC_CIE0_PHY_PLL_BYPASS1X_CLK_INT_ENABLE_MASK (0x40U)
#define MEMC_LPMMEMC_CIE0_PHY_PLL_BYPASS1X_CLK_INT_ENABLE_SHIFT (6U)
#define MEMC_LPMMEMC_CIE0_PHY_CTL_RD_CLK_INT_ENABLE_MASK (0x20U)
#define MEMC_LPMMEMC_CIE0_PHY_CTL_RD_CLK_INT_ENABLE_SHIFT (5U)
#define MEMC_LPMMEMC_CIE0_MEMC_DDRCLK_INT_ENABLE_MASK (0x10U)
#define MEMC_LPMMEMC_CIE0_MEMC_DDRCLK_INT_ENABLE_SHIFT (4U)
#define MEMC_LPMMEMC_CIE0_PUB_PCLK_INT_ENABLE_MASK (0x8U)
#define MEMC_LPMMEMC_CIE0_PUB_PCLK_INT_ENABLE_SHIFT (3U)
#define MEMC_LPMMEMC_CIE0_PUB_CTL_SDR_CLK_INT_ENABLE_MASK (0x4U)
#define MEMC_LPMMEMC_CIE0_PUB_CTL_SDR_CLK_INT_ENABLE_SHIFT (2U)
#define MEMC_LPMMEMC_CIE0_PUB_CTL_CLK_INT_ENABLE_MASK (0x2U)
#define MEMC_LPMMEMC_CIE0_PUB_CTL_CLK_INT_ENABLE_SHIFT (1U)
#define MEMC_LPMMEMC_CIE0_MEMC_PCLK_INT_ENABLE_MASK (0x1U)
#define MEMC_LPMMEMC_CIE0_MEMC_PCLK_INT_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_ENABLED_0_TYPE;
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK6_ENABLED_MASK (0x8000U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK6_ENABLED_SHIFT (15U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK5_ENABLED_MASK (0x4000U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK5_ENABLED_SHIFT (14U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK4_ENABLED_MASK (0x2000U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK4_ENABLED_SHIFT (13U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK3_ENABLED_MASK (0x1000U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK3_ENABLED_SHIFT (12U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK2_ENABLED_MASK (0x800U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK2_ENABLED_SHIFT (11U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK1_ENABLED_MASK (0x400U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK1_ENABLED_SHIFT (10U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK0_ENABLED_MASK (0x200U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_SCAN_CLK0_ENABLED_SHIFT (9U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_ATB_CLK_ENABLED_MASK (0x100U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_ATB_CLK_ENABLED_SHIFT (8U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_OBSERVE_CLK_ENABLED_MASK (0x80U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_DFT_OBSERVE_CLK_ENABLED_SHIFT (7U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PHY_PLL_BYPASS1X_CLK_ENABLED_MASK (0x40U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PHY_PLL_BYPASS1X_CLK_ENABLED_SHIFT (6U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PHY_CTL_RD_CLK_ENABLED_MASK (0x20U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PHY_CTL_RD_CLK_ENABLED_SHIFT (5U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_MEMC_DDRCLK_ENABLED_MASK (0x10U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_MEMC_DDRCLK_ENABLED_SHIFT (4U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PUB_PCLK_ENABLED_MASK (0x8U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PUB_PCLK_ENABLED_SHIFT (3U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PUB_CTL_SDR_CLK_ENABLED_MASK (0x4U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PUB_CTL_SDR_CLK_ENABLED_SHIFT (2U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PUB_CTL_CLK_ENABLED_MASK (0x2U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_PUB_CTL_CLK_ENABLED_SHIFT (1U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_MEMC_PCLK_ENABLED_MASK (0x1U)
#define MEMC_LPMMEMC_CLOCK_ENABLED_0_MEMC_PCLK_ENABLED_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_IDLE_0_TYPE;
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK6_IDLE_MASK (0x8000U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK6_IDLE_SHIFT (15U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK5_IDLE_MASK (0x4000U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK5_IDLE_SHIFT (14U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK4_IDLE_MASK (0x2000U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK4_IDLE_SHIFT (13U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK3_IDLE_MASK (0x1000U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK3_IDLE_SHIFT (12U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK2_IDLE_MASK (0x800U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK2_IDLE_SHIFT (11U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK1_IDLE_MASK (0x400U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK1_IDLE_SHIFT (10U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK0_IDLE_MASK (0x200U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_SCAN_CLK0_IDLE_SHIFT (9U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_ATB_CLK_IDLE_MASK (0x100U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_ATB_CLK_IDLE_SHIFT (8U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_OBSERVE_CLK_IDLE_MASK (0x80U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_DFT_OBSERVE_CLK_IDLE_SHIFT (7U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PHY_CTL_RD_CLK_IDLE_MASK (0x20U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PHY_CTL_RD_CLK_IDLE_SHIFT (5U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_MEMC_DDRCLK_IDLE_MASK (0x10U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_MEMC_DDRCLK_IDLE_SHIFT (4U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PUB_PCLK_IDLE_MASK (0x8U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PUB_PCLK_IDLE_SHIFT (3U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PUB_CTL_SDR_CLK_IDLE_MASK (0x4U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PUB_CTL_SDR_CLK_IDLE_SHIFT (2U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PUB_CTL_CLK_IDLE_MASK (0x2U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_PUB_CTL_CLK_IDLE_SHIFT (1U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_MEMC_PCLK_IDLE_MASK (0x1U)
#define MEMC_LPMMEMC_CLOCK_IDLE_0_MEMC_PCLK_IDLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_STATUS_0_TYPE;
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK6_STABLE_MASK (0x8000U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK6_STABLE_SHIFT (15U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK5_STABLE_MASK (0x4000U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK5_STABLE_SHIFT (14U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK4_STABLE_MASK (0x2000U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK4_STABLE_SHIFT (13U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK3_STABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK3_STABLE_SHIFT (12U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK2_STABLE_MASK (0x800U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK2_STABLE_SHIFT (11U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK1_STABLE_MASK (0x400U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK1_STABLE_SHIFT (10U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK0_STABLE_MASK (0x200U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_SCAN_CLK0_STABLE_SHIFT (9U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_ATB_CLK_STABLE_MASK (0x100U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_ATB_CLK_STABLE_SHIFT (8U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_OBSERVE_CLK_STABLE_MASK (0x80U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_DFT_OBSERVE_CLK_STABLE_SHIFT (7U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PHY_PLL_BYPASS1X_CLK_STABLE_MASK (0x40U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PHY_PLL_BYPASS1X_CLK_STABLE_SHIFT (6U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PHY_CTL_RD_CLK_STABLE_MASK (0x20U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PHY_CTL_RD_CLK_STABLE_SHIFT (5U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_MEMC_DDRCLK_STABLE_MASK (0x10U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_MEMC_DDRCLK_STABLE_SHIFT (4U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PUB_PCLK_STABLE_MASK (0x8U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PUB_PCLK_STABLE_SHIFT (3U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PUB_CTL_SDR_CLK_STABLE_MASK (0x4U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PUB_CTL_SDR_CLK_STABLE_SHIFT (2U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PUB_CTL_CLK_STABLE_MASK (0x2U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_PUB_CTL_CLK_STABLE_SHIFT (1U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_MEMC_PCLK_STABLE_MASK (0x1U)
#define MEMC_LPMMEMC_CLOCK_STATUS_0_MEMC_PCLK_STABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEMC_PCLK_DESC_TYPE;
#define MEMC_LPMMEMC_MEMC_PCLK_DESC_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_MEMC_PCLK_DESC_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_MEMC_PCLK_DESC_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_MEMC_PCLK_DESC_DFT_CLK_ENABLE_SHIFT (12U)




typedef uint16_t MEMC_LPMMEMC_PUB_CTL_CLK_DESC_TYPE;
#define MEMC_LPMMEMC_PUB_CTL_CLK_DESC_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_PUB_CTL_CLK_DESC_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_PUB_CTL_CLK_DESC_DFT_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_PUB_CTL_CLK_DESC_DFT_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_PUB_CTL_CLK_DESC_DIVIDER_MASK (0x1U)
#define MEMC_LPMMEMC_PUB_CTL_CLK_DESC_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PCSCD_TYPE;
#define MEMC_LPMMEMC_PCSCD_PUB_CTL_SDR_CLK_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_PCSCD_PUB_CTL_SDR_CLK_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_PCSCD_PUB_CTL_SDR_CLK_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_PCSCD_PUB_CTL_SDR_CLK_DFT_CLK_ENABLE_SHIFT (12U)




typedef uint16_t MEMC_LPMMEMC_PUB_PCLK_DESC_TYPE;
#define MEMC_LPMMEMC_PUB_PCLK_DESC_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_PUB_PCLK_DESC_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_PUB_PCLK_DESC_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_PUB_PCLK_DESC_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_PUB_PCLK_DESC_DIVIDER_MASK (0x1U)
#define MEMC_LPMMEMC_PUB_PCLK_DESC_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEMC_DDRCLK_DESC_TYPE;
#define MEMC_LPMMEMC_MEMC_DDRCLK_DESC_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_MEMC_DDRCLK_DESC_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_MEMC_DDRCLK_DESC_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_MEMC_DDRCLK_DESC_DFT_CLK_ENABLE_SHIFT (12U)




typedef uint16_t MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_TYPE;
#define MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_SELECT_MASK (0x4000U)
#define MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_SELECT_SHIFT (14U)
#define MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_DIVIDER_MASK (0x1U)
#define MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PPB1D_TYPE;
#define MEMC_LPMMEMC_PPB1D_PHY_PLL_BYPASS1X_DIVIDER_MASK (0x3U)
#define MEMC_LPMMEMC_PPB1D_PHY_PLL_BYPASS1X_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DOCD_TYPE;
#define MEMC_LPMMEMC_DOCD_DFT_OBSERVE_CLK_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DOCD_DFT_OBSERVE_CLK_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DOCD_DFT_OBSERVE_CLK_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DOCD_DFT_OBSERVE_CLK_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DOCD_DFT_OBSERVE_CLK_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DOCD_DFT_OBSERVE_CLK_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_ATB_CLK_DESC_TYPE;
#define MEMC_LPMMEMC_ATB_CLK_DESC_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_ATB_CLK_DESC_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_ATB_CLK_DESC_DFT_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_ATB_CLK_DESC_DFT_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_ATB_CLK_DESC_DIVIDER_MASK (0x3U)
#define MEMC_LPMMEMC_ATB_CLK_DESC_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC0D_TYPE;
#define MEMC_LPMMEMC_DSC0D_DFT_SCAN_CLK0_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC0D_DFT_SCAN_CLK0_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC0D_DFT_SCAN_CLK0_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC0D_DFT_SCAN_CLK0_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC0D_DFT_SCAN_CLK0_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC0D_DFT_SCAN_CLK0_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC1D_TYPE;
#define MEMC_LPMMEMC_DSC1D_DFT_SCAN_CLK1_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC1D_DFT_SCAN_CLK1_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC1D_DFT_SCAN_CLK1_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC1D_DFT_SCAN_CLK1_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC1D_DFT_SCAN_CLK1_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC1D_DFT_SCAN_CLK1_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC2D_TYPE;
#define MEMC_LPMMEMC_DSC2D_DFT_SCAN_CLK2_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC2D_DFT_SCAN_CLK2_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC2D_DFT_SCAN_CLK2_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC2D_DFT_SCAN_CLK2_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC2D_DFT_SCAN_CLK2_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC2D_DFT_SCAN_CLK2_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC3D_TYPE;
#define MEMC_LPMMEMC_DSC3D_DFT_SCAN_CLK3_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC3D_DFT_SCAN_CLK3_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC3D_DFT_SCAN_CLK3_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC3D_DFT_SCAN_CLK3_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC3D_DFT_SCAN_CLK3_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC3D_DFT_SCAN_CLK3_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC4D_TYPE;
#define MEMC_LPMMEMC_DSC4D_DFT_SCAN_CLK4_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC4D_DFT_SCAN_CLK4_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC4D_DFT_SCAN_CLK4_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC4D_DFT_SCAN_CLK4_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC4D_DFT_SCAN_CLK4_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC4D_DFT_SCAN_CLK4_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC5D_TYPE;
#define MEMC_LPMMEMC_DSC5D_DFT_SCAN_CLK5_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC5D_DFT_SCAN_CLK5_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC5D_DFT_SCAN_CLK5_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC5D_DFT_SCAN_CLK5_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC5D_DFT_SCAN_CLK5_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC5D_DFT_SCAN_CLK5_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DSC6D_TYPE;
#define MEMC_LPMMEMC_DSC6D_DFT_SCAN_CLK6_HYST_MASK (0x2000U)
#define MEMC_LPMMEMC_DSC6D_DFT_SCAN_CLK6_HYST_SHIFT (13U)
#define MEMC_LPMMEMC_DSC6D_DFT_SCAN_CLK6_DFT_CLK_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_DSC6D_DFT_SCAN_CLK6_DFT_CLK_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_DSC6D_DFT_SCAN_CLK6_DIVIDER_MASK (0xfU)
#define MEMC_LPMMEMC_DSC6D_DFT_SCAN_CLK6_DIVIDER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_RIS_TYPE;
#define MEMC_LPMMEMC_RIS_RESETN_DEASSERT_STATUS_MASK (0x1U)
#define MEMC_LPMMEMC_RIS_RESETN_DEASSERT_STATUS_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_RSIE_TYPE;
#define MEMC_LPMMEMC_RSIE_RESETN_DEASSERT_INT_ENB_MASK (0x1U)
#define MEMC_LPMMEMC_RSIE_RESETN_DEASSERT_INT_ENB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_RESETN_STATUS_TYPE;
#define MEMC_LPMMEMC_RESETN_STATUS_DEASSERTED_MASK (0x1U)
#define MEMC_LPMMEMC_RESETN_STATUS_DEASSERTED_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SOFTRESETN_0_TYPE;
#define MEMC_LPMMEMC_SOFTRESETN_0_ATB_SOFTRESETN_MASK (0x2000U)
#define MEMC_LPMMEMC_SOFTRESETN_0_ATB_SOFTRESETN_SHIFT (13U)
#define MEMC_LPMMEMC_SOFTRESETN_0_LPM_PLL0_SOFTRESETN_MASK (0x1000U)
#define MEMC_LPMMEMC_SOFTRESETN_0_LPM_PLL0_SOFTRESETN_SHIFT (12U)
#define MEMC_LPMMEMC_SOFTRESETN_0_BYPASS_CLK_SOFTRESETN_MASK (0x800U)
#define MEMC_LPMMEMC_SOFTRESETN_0_BYPASS_CLK_SOFTRESETN_SHIFT (11U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PHY_SOFTRESETN_MASK (0x400U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PHY_SOFTRESETN_SHIFT (10U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_RFF_DDRCLK_SOFTRESETN_MASK (0x200U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_RFF_DDRCLK_SOFTRESETN_SHIFT (9U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_DDRCLK_SOFTRESETN_MASK (0x100U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_DDRCLK_SOFTRESETN_SHIFT (8U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PUB_SOFTRESETN_MASK (0x80U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PUB_SOFTRESETN_SHIFT (7U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PUB_CTL_SDR_SOFTRESETN_MASK (0x40U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PUB_CTL_SDR_SOFTRESETN_SHIFT (6U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PUB_CTL_SOFTRESETN_MASK (0x20U)
#define MEMC_LPMMEMC_SOFTRESETN_0_PUB_CTL_SOFTRESETN_SHIFT (5U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_RFF_HARD_SOFTRESETN_MASK (0x10U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_RFF_HARD_SOFTRESETN_SHIFT (4U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_HARD_SOFTRESETN_MASK (0x8U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_HARD_SOFTRESETN_SHIFT (3U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_RFF_SOFTRESETN_MASK (0x4U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_RFF_SOFTRESETN_SHIFT (2U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_SOFTRESETN_MASK (0x2U)
#define MEMC_LPMMEMC_SOFTRESETN_0_MEMC_SOFTRESETN_SHIFT (1U)
#define MEMC_LPMMEMC_SOFTRESETN_0_LPM_CLKGEN_SOFTRESETN_MASK (0x1U)
#define MEMC_LPMMEMC_SOFTRESETN_0_LPM_CLKGEN_SOFTRESETN_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_RESETN_STATUS_0_TYPE;
#define MEMC_LPMMEMC_RESETN_STATUS_0_ATB_RESETN_VALUE_MASK (0x2000U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_ATB_RESETN_VALUE_SHIFT (13U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_LPM_PLL0_RESETN_VALUE_MASK (0x1000U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_LPM_PLL0_RESETN_VALUE_SHIFT (12U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_BYPASS_CLK_RESETN_VALUE_MASK (0x800U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_BYPASS_CLK_RESETN_VALUE_SHIFT (11U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_RFF_DDRCLK_RSTN_VALUE_MASK (0x400U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_RFF_DDRCLK_RSTN_VALUE_SHIFT (10U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_DDRCLK_RSTN_VALUE_MASK (0x200U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_DDRCLK_RSTN_VALUE_SHIFT (9U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PHY_RSTN_VALUE_MASK (0x100U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PHY_RSTN_VALUE_SHIFT (8U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PUB_PRESETN_VALUE_MASK (0x80U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PUB_PRESETN_VALUE_SHIFT (7U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PUB_CTL_SDR_RSTN_VALUE_MASK (0x40U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PUB_CTL_SDR_RSTN_VALUE_SHIFT (6U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PUB_CTL_RSTN_VALUE_MASK (0x20U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_PUB_CTL_RSTN_VALUE_SHIFT (5U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_RFF_HARD_RSTN_VALUE_MASK (0x10U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_RFF_HARD_RSTN_VALUE_SHIFT (4U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_HARD_RSTN_VALUE_MASK (0x8U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_HARD_RSTN_VALUE_SHIFT (3U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_RFF_PCLK_RSTN_VALUE_MASK (0x4U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_RFF_PCLK_RSTN_VALUE_SHIFT (2U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_PCLK_RSTN_VALUE_MASK (0x2U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_MEMC_PCLK_RSTN_VALUE_SHIFT (1U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_CLKGEN_RSTN_VALUE_MASK (0x1U)
#define MEMC_LPMMEMC_RESETN_STATUS_0_CLKGEN_RSTN_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_RIE0_TYPE;
#define MEMC_LPMMEMC_RIE0_ATB_RESETN_INT_ENABLE_MASK (0x2000U)
#define MEMC_LPMMEMC_RIE0_ATB_RESETN_INT_ENABLE_SHIFT (13U)
#define MEMC_LPMMEMC_RIE0_LPM_PLL0_RESETN_INT_ENABLE_MASK (0x1000U)
#define MEMC_LPMMEMC_RIE0_LPM_PLL0_RESETN_INT_ENABLE_SHIFT (12U)
#define MEMC_LPMMEMC_RIE0_BYPASS_CLK_RESETN_INT_ENABLE_MASK (0x800U)
#define MEMC_LPMMEMC_RIE0_BYPASS_CLK_RESETN_INT_ENABLE_SHIFT (11U)
#define MEMC_LPMMEMC_RIE0_MEMC_RFF_DDRCLK_RSTN_INT_ENABLE_MASK (0x400U)
#define MEMC_LPMMEMC_RIE0_MEMC_RFF_DDRCLK_RSTN_INT_ENABLE_SHIFT (10U)
#define MEMC_LPMMEMC_RIE0_MEMC_DDRCLK_RSTN_INT_ENABLE_MASK (0x200U)
#define MEMC_LPMMEMC_RIE0_MEMC_DDRCLK_RSTN_INT_ENABLE_SHIFT (9U)
#define MEMC_LPMMEMC_RIE0_PHY_RSTN_INT_ENABLE_MASK (0x100U)
#define MEMC_LPMMEMC_RIE0_PHY_RSTN_INT_ENABLE_SHIFT (8U)
#define MEMC_LPMMEMC_RIE0_PUB_PRESETN_INT_ENABLE_MASK (0x80U)
#define MEMC_LPMMEMC_RIE0_PUB_PRESETN_INT_ENABLE_SHIFT (7U)
#define MEMC_LPMMEMC_RIE0_PUB_CTL_SDR_RSTN_INT_ENABLE_MASK (0x40U)
#define MEMC_LPMMEMC_RIE0_PUB_CTL_SDR_RSTN_INT_ENABLE_SHIFT (6U)
#define MEMC_LPMMEMC_RIE0_PUB_CTL_RSTN_INT_ENABLE_MASK (0x20U)
#define MEMC_LPMMEMC_RIE0_PUB_CTL_RSTN_INT_ENABLE_SHIFT (5U)
#define MEMC_LPMMEMC_RIE0_MEMC_RFF_HARD_RSTN_INT_ENABLE_MASK (0x10U)
#define MEMC_LPMMEMC_RIE0_MEMC_RFF_HARD_RSTN_INT_ENABLE_SHIFT (4U)
#define MEMC_LPMMEMC_RIE0_MEMC_HARD_RSTN_INT_ENABLE_MASK (0x8U)
#define MEMC_LPMMEMC_RIE0_MEMC_HARD_RSTN_INT_ENABLE_SHIFT (3U)
#define MEMC_LPMMEMC_RIE0_MEMC_RFF_PCLK_RSTN_INT_ENABLE_MASK (0x4U)
#define MEMC_LPMMEMC_RIE0_MEMC_RFF_PCLK_RSTN_INT_ENABLE_SHIFT (2U)
#define MEMC_LPMMEMC_RIE0_MEMC_PCLK_RSTN_INT_ENABLE_MASK (0x2U)
#define MEMC_LPMMEMC_RIE0_MEMC_PCLK_RSTN_INT_ENABLE_SHIFT (1U)
#define MEMC_LPMMEMC_RIE0_CLKGEN_RSTN_INT_ENABLE_MASK (0x1U)
#define MEMC_LPMMEMC_RIE0_CLKGEN_RSTN_INT_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_COMMAND_TYPE;
#define MEMC_LPMMEMC_MEASURE_COMMAND_RESET_MASK (0x8000U)
#define MEMC_LPMMEMC_MEASURE_COMMAND_RESET_SHIFT (15U)
#define MEMC_LPMMEMC_MEASURE_COMMAND_STOP_MASK (0x2U)
#define MEMC_LPMMEMC_MEASURE_COMMAND_STOP_SHIFT (1U)
#define MEMC_LPMMEMC_MEASURE_COMMAND_START_MASK (0x1U)
#define MEMC_LPMMEMC_MEASURE_COMMAND_START_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MCS_TYPE;
#define MEMC_LPMMEMC_MCS_MEASURE_RESULTS_OVERFLOW_STATUS_MASK (0x8000U)
#define MEMC_LPMMEMC_MCS_MEASURE_RESULTS_OVERFLOW_STATUS_SHIFT (15U)
#define MEMC_LPMMEMC_MCS_MEASURE_EVENT_OVERFLOW_STATUS_MASK (0x4000U)
#define MEMC_LPMMEMC_MCS_MEASURE_EVENT_OVERFLOW_STATUS_SHIFT (14U)
#define MEMC_LPMMEMC_MCS_MEASURE_TIMER_OVERFLOW_STATUS_MASK (0x2000U)
#define MEMC_LPMMEMC_MCS_MEASURE_TIMER_OVERFLOW_STATUS_SHIFT (13U)
#define MEMC_LPMMEMC_MCS_MEASURE_FREQ_OVERFLOW_STATUS_MASK (0x1000U)
#define MEMC_LPMMEMC_MCS_MEASURE_FREQ_OVERFLOW_STATUS_SHIFT (12U)
#define MEMC_LPMMEMC_MCS_MEASURE_FREQUENCY_DONE_MASK (0x4U)
#define MEMC_LPMMEMC_MCS_MEASURE_FREQUENCY_DONE_SHIFT (2U)
#define MEMC_LPMMEMC_MCS_MEASURE_STOP_BYTIMER_MASK (0x2U)
#define MEMC_LPMMEMC_MCS_MEASURE_STOP_BYTIMER_SHIFT (1U)
#define MEMC_LPMMEMC_MCS_MEASURE_STOP_BY_SW_MASK (0x1U)
#define MEMC_LPMMEMC_MCS_MEASURE_STOP_BY_SW_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_CONTROL_TYPE;
#define MEMC_LPMMEMC_MEASURE_CONTROL_DIVIDE_CLOCK_MASK (0xf000U)
#define MEMC_LPMMEMC_MEASURE_CONTROL_DIVIDE_CLOCK_SHIFT (12U)
#define MEMC_LPMMEMC_MEASURE_CONTROL_SELECTION_TYPE_MASK (0x7U)
#define MEMC_LPMMEMC_MEASURE_CONTROL_SELECTION_TYPE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_CTRL_TIMER_TYPE;
#define MEMC_LPMMEMC_MEASURE_CTRL_TIMER_VALUE_MASK (0x7fffU)
#define MEMC_LPMMEMC_MEASURE_CTRL_TIMER_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_SELECTION_CLOCK_TYPE;
#define MEMC_LPMMEMC_MEASURE_SELECTION_CLOCK_SEL_CLOCK_MASK (0x7fU)
#define MEMC_LPMMEMC_MEASURE_SELECTION_CLOCK_SEL_CLOCK_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_RESULT_LSB_TYPE;
#define MEMC_LPMMEMC_MEASURE_RESULT_LSB_LSB_MASK (0xffffU)
#define MEMC_LPMMEMC_MEASURE_RESULT_LSB_LSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_RESULT_MSB_TYPE;
#define MEMC_LPMMEMC_MEASURE_RESULT_MSB_OVERFLOW_MASK (0x8000U)
#define MEMC_LPMMEMC_MEASURE_RESULT_MSB_OVERFLOW_SHIFT (15U)
#define MEMC_LPMMEMC_MEASURE_RESULT_MSB_MSB_MASK (0x7fffU)
#define MEMC_LPMMEMC_MEASURE_RESULT_MSB_MSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_RESULT_EVENT_TYPE;
#define MEMC_LPMMEMC_MEASURE_RESULT_EVENT_OVERFLOW_MASK (0x8000U)
#define MEMC_LPMMEMC_MEASURE_RESULT_EVENT_OVERFLOW_SHIFT (15U)
#define MEMC_LPMMEMC_MEASURE_RESULT_EVENT_VALUE_MASK (0x7fffU)
#define MEMC_LPMMEMC_MEASURE_RESULT_EVENT_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MEASURE_RESULT_FREQ_TYPE;
#define MEMC_LPMMEMC_MEASURE_RESULT_FREQ_OVERFLOW_MASK (0x8000U)
#define MEMC_LPMMEMC_MEASURE_RESULT_FREQ_OVERFLOW_SHIFT (15U)
#define MEMC_LPMMEMC_MEASURE_RESULT_FREQ_VALUE_MASK (0x7fffU)
#define MEMC_LPMMEMC_MEASURE_RESULT_FREQ_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MRTL_TYPE;
#define MEMC_LPMMEMC_MRTL_REFERENCE_TIMER_VALUE_LSB_MASK (0xffffU)
#define MEMC_LPMMEMC_MRTL_REFERENCE_TIMER_VALUE_LSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_MRTM_TYPE;
#define MEMC_LPMMEMC_MRTM_REFERENCE_TIMER_OVERFLOW_MASK (0x8000U)
#define MEMC_LPMMEMC_MRTM_REFERENCE_TIMER_OVERFLOW_SHIFT (15U)
#define MEMC_LPMMEMC_MRTM_REFERENCE_TIMER_VALUE_MSB_MASK (0x7fffU)
#define MEMC_LPMMEMC_MRTM_REFERENCE_TIMER_VALUE_MSB_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_MONITOR_TYPE;
#define MEMC_LPMMEMC_CLOCK_MONITOR_CLKMON_CTL_MASK (0x100U)
#define MEMC_LPMMEMC_CLOCK_MONITOR_CLKMON_CTL_SHIFT (8U)
#define MEMC_LPMMEMC_CLOCK_MONITOR_CLKMON_SEL_MASK (0x7fU)
#define MEMC_LPMMEMC_CLOCK_MONITOR_CLKMON_SEL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_CLOCK_MONITOR_DIVIDER_TYPE;
#define MEMC_LPMMEMC_CLOCK_MONITOR_DIVIDER_CLKMON_DIV_MASK (0x3fU)
#define MEMC_LPMMEMC_CLOCK_MONITOR_DIVIDER_CLKMON_DIV_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SEL_DEBUG_VECTOR_TYPE;
#define MEMC_LPMMEMC_SEL_DEBUG_VECTOR_CORE_MASK (0xf0U)
#define MEMC_LPMMEMC_SEL_DEBUG_VECTOR_CORE_SHIFT (4U)
#define MEMC_LPMMEMC_SEL_DEBUG_VECTOR_AON_MASK (0xfU)
#define MEMC_LPMMEMC_SEL_DEBUG_VECTOR_AON_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DEBUG_CONTROL_TYPE;
#define MEMC_LPMMEMC_DEBUG_CONTROL_MODE_ENABLE_MASK (0x8000U)
#define MEMC_LPMMEMC_DEBUG_CONTROL_MODE_ENABLE_SHIFT (15U)
#define MEMC_LPMMEMC_DEBUG_CONTROL_COUNT_MASK (0xfffU)
#define MEMC_LPMMEMC_DEBUG_CONTROL_COUNT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DEBUG_TRIGGER_TYPE;
#define MEMC_LPMMEMC_DEBUG_TRIGGER_TRIGGER_MASK (0x8000U)
#define MEMC_LPMMEMC_DEBUG_TRIGGER_TRIGGER_SHIFT (15U)




typedef uint16_t MEMC_LPMMEMC_DEBUG_ENABLE_0_TYPE;
#define MEMC_LPMMEMC_DEBUG_ENABLE_0_CLOCK_ENABLE_MASK (0xffffU)
#define MEMC_LPMMEMC_DEBUG_ENABLE_0_CLOCK_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_TYPE;
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_SPARE_1_MASK (0x20U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_SPARE_1_SHIFT (5U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_SPARE_0_MASK (0x10U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_SPARE_0_SHIFT (4U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_DFT_MASK (0x8U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_DFT_SHIFT (3U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_CLOCK_MASK (0x4U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_CLOCK_SHIFT (2U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_RFF_MASK (0x2U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_RFF_SHIFT (1U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_I_O_MASK (0x1U)
#define MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_ISO_I_O_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DOMAIN_ON_OK_AUTO_CONTROL_TYPE;
#define MEMC_LPMMEMC_DOMAIN_ON_OK_AUTO_CONTROL_POWERONOUT_COUNT_MASK (0x3f00U)
#define MEMC_LPMMEMC_DOMAIN_ON_OK_AUTO_CONTROL_POWERONOUT_COUNT_SHIFT (8U)
#define MEMC_LPMMEMC_DOMAIN_ON_OK_AUTO_CONTROL_POWERONIN_COUNT_MASK (0x3fU)
#define MEMC_LPMMEMC_DOMAIN_ON_OK_AUTO_CONTROL_POWERONIN_COUNT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_DOMAIN_ON2OK_AUTO_CONTROL_TYPE;
#define MEMC_LPMMEMC_DOMAIN_ON2OK_AUTO_CONTROL_POWERON2OK_COUNT_MASK (0xfffU)
#define MEMC_LPMMEMC_DOMAIN_ON2OK_AUTO_CONTROL_POWERON2OK_COUNT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PIE1_TYPE;
#define MEMC_LPMMEMC_PIE1_PWRON_INT_ENB_ALL_OFF_VECTOR_MASK (0x100U)
#define MEMC_LPMMEMC_PIE1_PWRON_INT_ENB_ALL_OFF_VECTOR_SHIFT (8U)
#define MEMC_LPMMEMC_PIE1_PWRON_INT_ENB_ALL_ON_VECTOR_MASK (0x1U)
#define MEMC_LPMMEMC_PIE1_PWRON_INT_ENB_ALL_ON_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PIE2_TYPE;
#define MEMC_LPMMEMC_PIE2_PWROK_INT_ENB_ALL_OFF_VECTOR_MASK (0x100U)
#define MEMC_LPMMEMC_PIE2_PWROK_INT_ENB_ALL_OFF_VECTOR_SHIFT (8U)
#define MEMC_LPMMEMC_PIE2_PWROK_INT_ENB_ALL_ON_VECTOR_MASK (0x1U)
#define MEMC_LPMMEMC_PIE2_PWROK_INT_ENB_ALL_ON_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PIS_TYPE;
#define MEMC_LPMMEMC_PIS_PWRON_STATUS_ALL_OFF_VECTOR_MASK (0x100U)
#define MEMC_LPMMEMC_PIS_PWRON_STATUS_ALL_OFF_VECTOR_SHIFT (8U)
#define MEMC_LPMMEMC_PIS_PWRON_STATUS_ALL_ON_VECTOR_MASK (0x1U)
#define MEMC_LPMMEMC_PIS_PWRON_STATUS_ALL_ON_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PIS1_TYPE;
#define MEMC_LPMMEMC_PIS1_PWROK_STATUS_ALL_OFF_VECTOR_MASK (0x100U)
#define MEMC_LPMMEMC_PIS1_PWROK_STATUS_ALL_OFF_VECTOR_SHIFT (8U)
#define MEMC_LPMMEMC_PIS1_PWROK_STATUS_ALL_ON_VECTOR_MASK (0x1U)
#define MEMC_LPMMEMC_PIS1_PWROK_STATUS_ALL_ON_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PWRONOUT_STATUS_TYPE;
#define MEMC_LPMMEMC_PWRONOUT_STATUS_PWRON_ALL_OFF_VECTOR_MASK (0x100U)
#define MEMC_LPMMEMC_PWRONOUT_STATUS_PWRON_ALL_OFF_VECTOR_SHIFT (8U)
#define MEMC_LPMMEMC_PWRONOUT_STATUS_PWRON_ALL_ON_VECTOR_MASK (0x1U)
#define MEMC_LPMMEMC_PWRONOUT_STATUS_PWRON_ALL_ON_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PWROKOUT_STATUS_TYPE;
#define MEMC_LPMMEMC_PWROKOUT_STATUS_PWROK_ALL_OFF_VECTOR_MASK (0x100U)
#define MEMC_LPMMEMC_PWROKOUT_STATUS_PWROK_ALL_OFF_VECTOR_SHIFT (8U)
#define MEMC_LPMMEMC_PWROKOUT_STATUS_PWROK_ALL_ON_VECTOR_MASK (0x1U)
#define MEMC_LPMMEMC_PWROKOUT_STATUS_PWROK_ALL_ON_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PWRON_IN_DOMAIN_MEMC_TYPE;
#define MEMC_LPMMEMC_PWRON_IN_DOMAIN_MEMC_VECTOR_MASK (0xffU)
#define MEMC_LPMMEMC_PWRON_IN_DOMAIN_MEMC_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PWRON_OUT_DOMAIN_MEMC_TYPE;
#define MEMC_LPMMEMC_PWRON_OUT_DOMAIN_MEMC_VECTOR_MASK (0xffU)
#define MEMC_LPMMEMC_PWRON_OUT_DOMAIN_MEMC_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PWROK_IN_DOMAIN_MEMC_TYPE;
#define MEMC_LPMMEMC_PWROK_IN_DOMAIN_MEMC_VECTOR_MASK (0xffU)
#define MEMC_LPMMEMC_PWROK_IN_DOMAIN_MEMC_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_PWROK_OUT_DOMAIN_MEMC_TYPE;
#define MEMC_LPMMEMC_PWROK_OUT_DOMAIN_MEMC_VECTOR_MASK (0xffU)
#define MEMC_LPMMEMC_PWROK_OUT_DOMAIN_MEMC_VECTOR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_MUXED_SS_CLEAR_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_MUXED_SS_CLEAR_VALUE_MASK (0xffU)
#define MEMC_LPMMEMC_SUBSYSTEM_MUXED_SS_CLEAR_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_LVM_MASK (0xc000U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_LVM_SHIFT (14U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_WTB_MASK (0x38U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_WTB_SHIFT (3U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_RDT_MASK (0x7U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_RDT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_1_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_1_PDA_MASK (0xff00U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_1_PDA_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_1_RET_MASK (0xffU)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_1_RET_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SMCT0_TYPE;
#define MEMC_LPMMEMC_SMCT0_MEMORY_TM_UDR_WORD0_MASK (0xffffU)
#define MEMC_LPMMEMC_SMCT0_MEMORY_TM_UDR_WORD0_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SMCT1_TYPE;
#define MEMC_LPMMEMC_SMCT1_MEMORY_TM_UDR_WORD1_MASK (0xffffU)
#define MEMC_LPMMEMC_SMCT1_MEMORY_TM_UDR_WORD1_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SMCT2_TYPE;
#define MEMC_LPMMEMC_SMCT2_MEMORY_TM_UDR_WORD2_MASK (0xffffU)
#define MEMC_LPMMEMC_SMCT2_MEMORY_TM_UDR_WORD2_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SMCT3_TYPE;
#define MEMC_LPMMEMC_SMCT3_MEMORY_TM_UDR_WORD3_MASK (0xffffU)
#define MEMC_LPMMEMC_SMCT3_MEMORY_TM_UDR_WORD3_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_WTB_RF_MASK (0x3800U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_WTB_RF_SHIFT (11U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_RDT_RF_MASK (0x700U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_RDT_RF_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_WTB_SP_MASK (0x38U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_WTB_SP_SHIFT (3U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_RDT_SP_MASK (0x7U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_RDT_SP_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SMCT11_TYPE;
#define MEMC_LPMMEMC_SMCT11_MEMORY_WDT_RM_MASK (0x3800U)
#define MEMC_LPMMEMC_SMCT11_MEMORY_WDT_RM_SHIFT (11U)
#define MEMC_LPMMEMC_SMCT11_MEMROY_RDT_RM_MASK (0x700U)
#define MEMC_LPMMEMC_SMCT11_MEMROY_RDT_RM_SHIFT (8U)
#define MEMC_LPMMEMC_SMCT11_MEMORY_WTB_SRF_MASK (0x38U)
#define MEMC_LPMMEMC_SMCT11_MEMORY_WTB_SRF_SHIFT (3U)
#define MEMC_LPMMEMC_SMCT11_MEMORY_RDT_SRF_MASK (0x7U)
#define MEMC_LPMMEMC_SMCT11_MEMORY_RDT_SRF_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEMORY_WTB_DP_MASK (0x3800U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEMORY_WTB_DP_SHIFT (11U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEMORY_RDT_DP_MASK (0x700U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEMORY_RDT_DP_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEMORY_WTB_PD_MASK (0x38U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEMORY_WTB_PD_SHIFT (3U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEORY_RDT_PD_MASK (0x7U)
#define MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_MEORY_RDT_PD_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SIS_TYPE;
#define MEMC_LPMMEMC_SIS_SMTEIEO_MASK (0x80U)
#define MEMC_LPMMEMC_SIS_SMTEIEO_SHIFT (7U)
#define MEMC_LPMMEMC_SIS_SMTNIEO_MASK (0x40U)
#define MEMC_LPMMEMC_SIS_SMTNIEO_SHIFT (6U)
#define MEMC_LPMMEMC_SIS_MEMC_EXIT_SREF_INT_EVENT_OCCURRED_MASK (0x20U)
#define MEMC_LPMMEMC_SIS_MEMC_EXIT_SREF_INT_EVENT_OCCURRED_SHIFT (5U)
#define MEMC_LPMMEMC_SIS_MEMC_IN_SREF_INT_EVENT_OCCURRED_MASK (0x10U)
#define MEMC_LPMMEMC_SIS_MEMC_IN_SREF_INT_EVENT_OCCURRED_SHIFT (4U)
#define MEMC_LPMMEMC_SIS_MEMC_ENTERED_SELFREFRESH_OCCURRED_MASK (0x8U)
#define MEMC_LPMMEMC_SIS_MEMC_ENTERED_SELFREFRESH_OCCURRED_SHIFT (3U)
#define MEMC_LPMMEMC_SIS_CAL_MON_ERR_EVENT_OCCURRED_MASK (0x4U)
#define MEMC_LPMMEMC_SIS_CAL_MON_ERR_EVENT_OCCURRED_SHIFT (2U)
#define MEMC_LPMMEMC_SIS_LPM_PLL_LOCK_EVENT_OCCURRED_MASK (0x2U)
#define MEMC_LPMMEMC_SIS_LPM_PLL_LOCK_EVENT_OCCURRED_SHIFT (1U)
#define MEMC_LPMMEMC_SIS_PHY_PLL_LOCK_EVENT_OCCURRED_MASK (0x1U)
#define MEMC_LPMMEMC_SIS_PHY_PLL_LOCK_EVENT_OCCURRED_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SIE_TYPE;
#define MEMC_LPMMEMC_SIE_SMTEIEE_MASK (0x80U)
#define MEMC_LPMMEMC_SIE_SMTEIEE_SHIFT (7U)
#define MEMC_LPMMEMC_SIE_SMTNIEE_MASK (0x40U)
#define MEMC_LPMMEMC_SIE_SMTNIEE_SHIFT (6U)
#define MEMC_LPMMEMC_SIE_MEMC_EXIT_SREF_INT_EVENT_ENABLED_MASK (0x20U)
#define MEMC_LPMMEMC_SIE_MEMC_EXIT_SREF_INT_EVENT_ENABLED_SHIFT (5U)
#define MEMC_LPMMEMC_SIE_MEMC_IN_SREF_INT_EVENT_ENABLED_MASK (0x10U)
#define MEMC_LPMMEMC_SIE_MEMC_IN_SREF_INT_EVENT_ENABLED_SHIFT (4U)
#define MEMC_LPMMEMC_SIE_MESIEE_MASK (0x8U)
#define MEMC_LPMMEMC_SIE_MESIEE_SHIFT (3U)
#define MEMC_LPMMEMC_SIE_CAL_MON_ERR_INT_EVENT_ENABLED_MASK (0x4U)
#define MEMC_LPMMEMC_SIE_CAL_MON_ERR_INT_EVENT_ENABLED_SHIFT (2U)
#define MEMC_LPMMEMC_SIE_LPM_PLL_LOCK_INT_EVENT_ENABLED_MASK (0x2U)
#define MEMC_LPMMEMC_SIE_LPM_PLL_LOCK_INT_EVENT_ENABLED_SHIFT (1U)
#define MEMC_LPMMEMC_SIE_PHY_PLL_LOCK_INT_EVENT_ENABLED_MASK (0x1U)
#define MEMC_LPMMEMC_SIE_PHY_PLL_LOCK_INT_EVENT_ENABLED_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SIS1_TYPE;
#define MEMC_LPMMEMC_SIS1_SMTEES_MASK (0x80U)
#define MEMC_LPMMEMC_SIS1_SMTEES_SHIFT (7U)
#define MEMC_LPMMEMC_SIS1_SEQUENCER_MIN_THRES_NOTMET_EVENT_SIGNAL_MASK (0x40U)
#define MEMC_LPMMEMC_SIS1_SEQUENCER_MIN_THRES_NOTMET_EVENT_SIGNAL_SHIFT (6U)
#define MEMC_LPMMEMC_SIS1_MEMC_EXIT_SREF_EVENT_SIGNAL_MASK (0x20U)
#define MEMC_LPMMEMC_SIS1_MEMC_EXIT_SREF_EVENT_SIGNAL_SHIFT (5U)
#define MEMC_LPMMEMC_SIS1_MEMC_IN_SREF_EVENT_SIGNAL_MASK (0x10U)
#define MEMC_LPMMEMC_SIS1_MEMC_IN_SREF_EVENT_SIGNAL_SHIFT (4U)
#define MEMC_LPMMEMC_SIS1_MEMC_ENTERED_SELFREFRESH_EVENT_SIGNAL_MASK (0x8U)
#define MEMC_LPMMEMC_SIS1_MEMC_ENTERED_SELFREFRESH_EVENT_SIGNAL_SHIFT (3U)
#define MEMC_LPMMEMC_SIS1_CAL_MON_ERR_EVENT_SIGNAL_MASK (0x4U)
#define MEMC_LPMMEMC_SIS1_CAL_MON_ERR_EVENT_SIGNAL_SHIFT (2U)
#define MEMC_LPMMEMC_SIS1_LPM_PLL_LOCK_EVENT_SIGNAL_MASK (0x2U)
#define MEMC_LPMMEMC_SIS1_LPM_PLL_LOCK_EVENT_SIGNAL_SHIFT (1U)
#define MEMC_LPMMEMC_SIS1_PHY_PLL_LOCK_EVENT_SIGNAL_MASK (0x1U)
#define MEMC_LPMMEMC_SIS1_PHY_PLL_LOCK_EVENT_SIGNAL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SISE_TYPE;
#define MEMC_LPMMEMC_SISE_EVENT_INT_STATUS_ENABLE_MASK (0xffU)
#define MEMC_LPMMEMC_SISE_EVENT_INT_STATUS_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SIC_TYPE;
#define MEMC_LPMMEMC_SIC_SMTEEC_MASK (0xc000U)
#define MEMC_LPMMEMC_SIC_SMTEEC_SHIFT (14U)
#define MEMC_LPMMEMC_SIC_SEQUENCER_MIN_THRES_NOTMET_EVENT_CONTROL_MASK (0x3000U)
#define MEMC_LPMMEMC_SIC_SEQUENCER_MIN_THRES_NOTMET_EVENT_CONTROL_SHIFT (12U)
#define MEMC_LPMMEMC_SIC_MEMC_EXIT_SREF_EVENT_CONTROL_MASK (0xc00U)
#define MEMC_LPMMEMC_SIC_MEMC_EXIT_SREF_EVENT_CONTROL_SHIFT (10U)
#define MEMC_LPMMEMC_SIC_MEMC_IN_SREF_EVENT_CONTROL_MASK (0x300U)
#define MEMC_LPMMEMC_SIC_MEMC_IN_SREF_EVENT_CONTROL_SHIFT (8U)
#define MEMC_LPMMEMC_SIC_MEMC_ENTERED_SELFREFRESH_EVENT_CONTROL_MASK (0xc0U)
#define MEMC_LPMMEMC_SIC_MEMC_ENTERED_SELFREFRESH_EVENT_CONTROL_SHIFT (6U)
#define MEMC_LPMMEMC_SIC_CAL_MON_ERR_EVENT_CONTROL_MASK (0x30U)
#define MEMC_LPMMEMC_SIC_CAL_MON_ERR_EVENT_CONTROL_SHIFT (4U)
#define MEMC_LPMMEMC_SIC_LPM_PLL_LOCK_EVENT_CONTROL_MASK (0xcU)
#define MEMC_LPMMEMC_SIC_LPM_PLL_LOCK_EVENT_CONTROL_SHIFT (2U)
#define MEMC_LPMMEMC_SIC_PHY_PLL_LOCK_EVENT_CONTROL_MASK (0x3U)
#define MEMC_LPMMEMC_SIC_PHY_PLL_LOCK_EVENT_CONTROL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SS0_TYPE;
#define MEMC_LPMMEMC_SS0_PUB_PHY_CLK_GATE_STATUS_4_0_MASK (0xf800U)
#define MEMC_LPMMEMC_SS0_PUB_PHY_CLK_GATE_STATUS_4_0_SHIFT (11U)
#define MEMC_LPMMEMC_SS0_SEQUENCER_MAX_THRES_EXCEEDED_MASK (0x400U)
#define MEMC_LPMMEMC_SS0_SEQUENCER_MAX_THRES_EXCEEDED_SHIFT (10U)
#define MEMC_LPMMEMC_SS0_SEQUENCER_MIN_THRES_NOTMET_MASK (0x200U)
#define MEMC_LPMMEMC_SS0_SEQUENCER_MIN_THRES_NOTMET_SHIFT (9U)
#define MEMC_LPMMEMC_SS0_HW_ASSIST2_DONE_MASK (0x100U)
#define MEMC_LPMMEMC_SS0_HW_ASSIST2_DONE_SHIFT (8U)
#define MEMC_LPMMEMC_SS0_HW_ASSIST1_DONE_MASK (0x80U)
#define MEMC_LPMMEMC_SS0_HW_ASSIST1_DONE_SHIFT (7U)
#define MEMC_LPMMEMC_SS0_MEMC_EXIT_SREF_MASK (0x40U)
#define MEMC_LPMMEMC_SS0_MEMC_EXIT_SREF_SHIFT (6U)
#define MEMC_LPMMEMC_SS0_MEMC_IN_SREF_MASK (0x20U)
#define MEMC_LPMMEMC_SS0_MEMC_IN_SREF_SHIFT (5U)
#define MEMC_LPMMEMC_SS0_MEMC_DFI_FREQ_RATIO_MASK (0x10U)
#define MEMC_LPMMEMC_SS0_MEMC_DFI_FREQ_RATIO_SHIFT (4U)
#define MEMC_LPMMEMC_SS0_MEMC_CLK_OFF_ACCEPT_MASK (0x8U)
#define MEMC_LPMMEMC_SS0_MEMC_CLK_OFF_ACCEPT_SHIFT (3U)
#define MEMC_LPMMEMC_SS0_MEMC_ENTERED_SELFREFRESH_MASK (0x4U)
#define MEMC_LPMMEMC_SS0_MEMC_ENTERED_SELFREFRESH_SHIFT (2U)
#define MEMC_LPMMEMC_SS0_PHY_IS_IDLE_MASK (0x2U)
#define MEMC_LPMMEMC_SS0_PHY_IS_IDLE_SHIFT (1U)
#define MEMC_LPMMEMC_SS0_MEMC_IS_IDLE_VALUE_MASK (0x1U)
#define MEMC_LPMMEMC_SS0_MEMC_IS_IDLE_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SS1_TYPE;
#define MEMC_LPMMEMC_SS1_PUB_PHY_CLK_GATE_STATUS_19_5_MASK (0x7fffU)
#define MEMC_LPMMEMC_SS1_PUB_PHY_CLK_GATE_STATUS_19_5_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_STATUS_2_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_STATUS_2_PHY_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_STATUS_2_PHY_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_STATUS_3_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_STATUS_3_PHY_RING_SWITCH_1_MASK (0x3f00U)
#define MEMC_LPMMEMC_SUBSYSTEM_STATUS_3_PHY_RING_SWITCH_1_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_STATUS_3_PHY_RING_SWITCH_0_MASK (0x3fU)
#define MEMC_LPMMEMC_SUBSYSTEM_STATUS_3_PHY_RING_SWITCH_0_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_0_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_0_REFRESH_IDLEMAX_19_4_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_0_REFRESH_IDLEMAX_19_4_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_HYSTERESIS_ON_MASK (0x8000U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_HYSTERESIS_ON_SHIFT (15U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_ISO_WAIT_MAX_3_2_MASK (0x6000U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_ISO_WAIT_MAX_3_2_SHIFT (13U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_THOLD_MAX_6_2_MASK (0x1f00U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_THOLD_MAX_6_2_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_LPM_DFI_FREQ_RATIO_VAL_MASK (0x80U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_LPM_DFI_FREQ_RATIO_VAL_SHIFT (7U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_LPM_DFI_FREQ_RATIO_SEL_MASK (0x40U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_LPM_DFI_FREQ_RATIO_SEL_SHIFT (6U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_TVSET_MAX_3_2_MASK (0x30U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_TVSET_MAX_3_2_SHIFT (4U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_LDO_WAIT_MAX_5_2_MASK (0xfU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_LDO_WAIT_MAX_5_2_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_REFCLK_STOP_MODE_EN_MASK (0x8000U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_REFCLK_STOP_MODE_EN_SHIFT (15U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_LDO_HW_PWRDN_EN_MASK (0x4000U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_LDO_HW_PWRDN_EN_SHIFT (14U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_HW_PWRDN_EN_MASK (0x800U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_HW_PWRDN_EN_SHIFT (11U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_MUX_CTL_MASK (0x400U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_MUX_CTL_SHIFT (10U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_PWRDN_CNT_2_1_MASK (0x300U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PLL_PWRDN_CNT_2_1_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_MEMC_ENTER_REFRESH_MASK (0x80U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_MEMC_ENTER_REFRESH_SHIFT (7U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_SW_CLK_OFF_READY_VALUE_MASK (0x40U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_SW_CLK_OFF_READY_VALUE_SHIFT (6U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_TLCK1_MAX_5_3_MASK (0x30U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_TLCK1_MAX_5_3_SHIFT (4U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_TLCK2_MAX_3_2_MASK (0xeU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_TLCK2_MAX_3_2_SHIFT (1U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PHY_PLL_FULL_FREQ_MASK (0x1U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_PHY_PLL_FULL_FREQ_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_3_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_3_APB_RESP_SEL_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_3_APB_RESP_SEL_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_4_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_4_PHY_RING_SWITCH_CONTROL_1_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_4_PHY_RING_SWITCH_CONTROL_1_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_5_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_5_SREF_HYSTERESIS_TIMER_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_5_SREF_HYSTERESIS_TIMER_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_START_HW_ASSIST_MASK (0x8000U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_START_HW_ASSIST_SHIFT (15U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_HW_ASSIST_START_ADDR_MASK (0x7f00U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_HW_ASSIST_START_ADDR_SHIFT (8U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_HW_ASSIST_END_ADDR_MASK (0x7fU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_HW_ASSIST_END_ADDR_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PHY_IO_RETENTION_MASK (0x8U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PHY_IO_RETENTION_SHIFT (3U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PUB_CTL_CLK_IDLE_CTRL_MASK (0x4U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PUB_CTL_CLK_IDLE_CTRL_SHIFT (2U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PUB_PCLK_IDLE_CTRL_MASK (0x2U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PUB_PCLK_IDLE_CTRL_SHIFT (1U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PUB_PSEL2_EN_MASK (0x1U)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_PUB_PSEL2_EN_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_8_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_8_PHY_RING_SWITCH_CONTROL_2_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_8_PHY_RING_SWITCH_CONTROL_2_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_CONFIG_9_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_9_PHY_RING_SWITCH_CONTROL_3_MASK (0xffffU)
#define MEMC_LPMMEMC_SUBSYSTEM_CONFIG_9_PHY_RING_SWITCH_CONTROL_3_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SUBSYSTEM_IS_ON_0_TYPE;
#define MEMC_LPMMEMC_SUBSYSTEM_IS_ON_0_ON_MASK (0xffU)
#define MEMC_LPMMEMC_SUBSYSTEM_IS_ON_0_ON_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SPARE_TYPE;
#define MEMC_LPMMEMC_SPARE_SPARE_IN_MASK (0xff00U)
#define MEMC_LPMMEMC_SPARE_SPARE_IN_SHIFT (8U)
#define MEMC_LPMMEMC_SPARE_SPARE1_OUT_MASK (0xc0U)
#define MEMC_LPMMEMC_SPARE_SPARE1_OUT_SHIFT (6U)
#define MEMC_LPMMEMC_SPARE_SPARE0_OUT_MASK (0x30U)
#define MEMC_LPMMEMC_SPARE_SPARE0_OUT_SHIFT (4U)
#define MEMC_LPMMEMC_SPARE_SPARE1UDR_OUT_MASK (0xcU)
#define MEMC_LPMMEMC_SPARE_SPARE1UDR_OUT_SHIFT (2U)
#define MEMC_LPMMEMC_SPARE_SPARE0UDR_OUT_MASK (0x3U)
#define MEMC_LPMMEMC_SPARE_SPARE0UDR_OUT_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SECURITY_TZPROT_0_TYPE;
#define MEMC_LPMMEMC_SECURITY_TZPROT_0_TRUSTZONE_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SECURITY_TZPROT_0_TRUSTZONE_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SECURITY_TZPROT_1_TYPE;
#define MEMC_LPMMEMC_SECURITY_TZPROT_1_TRUSTZONE_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SECURITY_TZPROT_1_TRUSTZONE_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SDE0_TYPE;
#define MEMC_LPMMEMC_SDE0_SECURITY_DEBUG_ENABLE_0_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SDE0_SECURITY_DEBUG_ENABLE_0_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SDE1_TYPE;
#define MEMC_LPMMEMC_SDE1_SECURITY_DEBUG_ENABLE_1_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SDE1_SECURITY_DEBUG_ENABLE_1_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SHC0_TYPE;
#define MEMC_LPMMEMC_SHC0_SECURITY_HARDWARE_0_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SHC0_SECURITY_HARDWARE_0_VALUE_SHIFT (0U)




typedef uint16_t MEMC_LPMMEMC_SHC1_TYPE;
#define MEMC_LPMMEMC_SHC1_SECURITY_HARDWARE_1_VALUE_MASK (0xffffU)
#define MEMC_LPMMEMC_SHC1_SECURITY_HARDWARE_1_VALUE_SHIFT (0U)




typedef volatile struct COMP_PACKED _MEMC_LPMMEMC_RDBType {
    MEMC_LPMMEMC_INTERRUPT_STATUS_TYPE interrupt_status; /* OFFSET: 0x0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x2 */
    MEMC_LPMMEMC_INTERRUPT_ENABLE_TYPE interrupt_enable; /* OFFSET: 0x4 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd1[50]; /* OFFSET: 0x6 */
    MEMC_LPMMEMC_CRYSTAL_CONTROL_TYPE crystal_control; /* OFFSET: 0x38 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd2[6]; /* OFFSET: 0x3a */
    MEMC_LPMMEMC_CLOCK_MODE_CONTROL_TYPE clock_mode_control; /* OFFSET: 0x40 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd3[6]; /* OFFSET: 0x42 */
    MEMC_LPMMEMC_RESETN_CONTROL_TYPE resetn_control; /* OFFSET: 0x48 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd4[6]; /* OFFSET: 0x4a */
    MEMC_LPMMEMC_WASP_CONTROL_TYPE wasp_control; /* OFFSET: 0x50 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd5[6]; /* OFFSET: 0x52 */
    MEMC_LPMMEMC_APB_BRIDGE_CONTROL_TYPE apb_bridge_control; /* OFFSET: 0x58 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd6[6]; /* OFFSET: 0x5a */
    MEMC_LPMMEMC_IDLE_STATUS_TYPE idle_status; /* OFFSET: 0x60 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd7[2]; /* OFFSET: 0x62 */
    MEMC_LPMMEMC_CSD_TYPE clock_source_detection; /* OFFSET: 0x64 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd8[10]; /* OFFSET: 0x66 */
    MEMC_LPMMEMC_PLL_PWR_ON_TYPE pll_pwr_on; /* OFFSET: 0x70 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd9[14]; /* OFFSET: 0x72 */
    MEMC_LPMMEMC_PLL_COMMAND_TYPE pll_command; /* OFFSET: 0x80 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd10[2]; /* OFFSET: 0x82 */
    MEMC_LPMMEMC_PLL_STATUS_TYPE pll_status; /* OFFSET: 0x84 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd11[2]; /* OFFSET: 0x86 */
    MEMC_LPMMEMC_PIE_TYPE pll_interrupt_enable; /* OFFSET: 0x88 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd12[2]; /* OFFSET: 0x8a */
    MEMC_LPMMEMC_PLL_INTERRUPT_STATUS_TYPE pll_interrupt_status; /* OFFSET: 0x8c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd13[18]; /* OFFSET: 0x8e */
    MEMC_LPMMEMC_P0CC_TYPE pll0_channel_control; /* OFFSET: 0xa0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd14[6]; /* OFFSET: 0xa2 */
    MEMC_LPMMEMC_PLL_CHANNEL_STATUS_TYPE pll_channel_status; /* OFFSET: 0xa8 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd15[2]; /* OFFSET: 0xaa */
    MEMC_LPMMEMC_PCABE_TYPE pll_channel_ate_bypass_enable; /* OFFSET: 0xac */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd16[82]; /* OFFSET: 0xae */
    MEMC_LPMMEMC_PLL0_CTRL1_TYPE pll0_ctrl1; /* OFFSET: 0x100 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd17[2]; /* OFFSET: 0x102 */
    MEMC_LPMMEMC_PLL0_CTRL2_TYPE pll0_ctrl2; /* OFFSET: 0x104 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd18[2]; /* OFFSET: 0x106 */
    MEMC_LPMMEMC_PLL0_CTRL3_TYPE pll0_ctrl3; /* OFFSET: 0x108 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd19[2]; /* OFFSET: 0x10a */
    MEMC_LPMMEMC_PLL0_CTRL4_TYPE pll0_ctrl4; /* OFFSET: 0x10c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd20[2]; /* OFFSET: 0x10e */
    MEMC_LPMMEMC_PLL0_CTRL_SSC0_TYPE pll0_ctrl_ssc0; /* OFFSET: 0x110 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd21[2]; /* OFFSET: 0x112 */
    MEMC_LPMMEMC_PLL0_CTRL_SSC1_TYPE pll0_ctrl_ssc1; /* OFFSET: 0x114 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd22[2]; /* OFFSET: 0x116 */
    MEMC_LPMMEMC_PLL0_CTRL_SSC2_TYPE pll0_ctrl_ssc2; /* OFFSET: 0x118 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd23[2]; /* OFFSET: 0x11a */
    MEMC_LPMMEMC_PLL0_STATUS_OUT_TYPE pll0_status_out; /* OFFSET: 0x11c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd24[2]; /* OFFSET: 0x11e */
    MEMC_LPMMEMC_PLL0_CFG0_CTRL_TYPE pll0_cfg0_ctrl; /* OFFSET: 0x120 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd25[2]; /* OFFSET: 0x122 */
    MEMC_LPMMEMC_PLL0_CFG1_CTRL_TYPE pll0_cfg1_ctrl; /* OFFSET: 0x124 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd26[2]; /* OFFSET: 0x126 */
    MEMC_LPMMEMC_PLL0_CFG2_CTRL_TYPE pll0_cfg2_ctrl; /* OFFSET: 0x128 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd27[2]; /* OFFSET: 0x12a */
    MEMC_LPMMEMC_PLL0_CFG3_CTRL_TYPE pll0_cfg3_ctrl; /* OFFSET: 0x12c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd28[18]; /* OFFSET: 0x12e */
    MEMC_LPMMEMC_PLL0_CHANNEL0_DESCRIPTION_TYPE pll0_channel0_description; /* OFFSET: 0x140 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd29[2]; /* OFFSET: 0x142 */
    MEMC_LPMMEMC_PLL0_CHANNEL1_DESCRIPTION_TYPE pll0_channel1_description; /* OFFSET: 0x144 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd30[2]; /* OFFSET: 0x146 */
    MEMC_LPMMEMC_PLL0_CHANNEL2_DESCRIPTION_TYPE pll0_channel2_description; /* OFFSET: 0x148 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd31[2]; /* OFFSET: 0x14a */
    MEMC_LPMMEMC_PLL0_CHANNEL3_DESCRIPTION_TYPE pll0_channel3_description; /* OFFSET: 0x14c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd32[2]; /* OFFSET: 0x14e */
    MEMC_LPMMEMC_PLL0_CHANNEL4_DESCRIPTION_TYPE pll0_channel4_description; /* OFFSET: 0x150 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd33[2]; /* OFFSET: 0x152 */
    MEMC_LPMMEMC_PLL0_CHANNEL5_DESCRIPTION_TYPE pll0_channel5_description; /* OFFSET: 0x154 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd34[154]; /* OFFSET: 0x156 */
    MEMC_LPMMEMC_CIS_TYPE clock_interrupt_status; /* OFFSET: 0x1f0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd35[2]; /* OFFSET: 0x1f2 */
    MEMC_LPMMEMC_CLOCK_INT_ENABLE_TYPE clock_int_enable; /* OFFSET: 0x1f4 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd36[2]; /* OFFSET: 0x1f6 */
    MEMC_LPMMEMC_CLOCK_STATUS_TYPE clock_status; /* OFFSET: 0x1f8 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd37[6]; /* OFFSET: 0x1fa */
    MEMC_LPMMEMC_CLOC_CONT_0_TYPE clock_control_0; /* OFFSET: 0x200 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd38[2]; /* OFFSET: 0x202 */
    MEMC_LPMMEMC_CLOC_CONT_1_TYPE clock_control_1; /* OFFSET: 0x204 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd39[58]; /* OFFSET: 0x206 */
    MEMC_LPMMEMC_CIE0_TYPE clock_int_enable_0; /* OFFSET: 0x240 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd40[62]; /* OFFSET: 0x242 */
    MEMC_LPMMEMC_CLOCK_ENABLED_0_TYPE clock_enabled_0; /* OFFSET: 0x280 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd41[30]; /* OFFSET: 0x282 */
    MEMC_LPMMEMC_CLOCK_IDLE_0_TYPE clock_idle_0; /* OFFSET: 0x2a0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd42[30]; /* OFFSET: 0x2a2 */
    MEMC_LPMMEMC_CLOCK_STATUS_0_TYPE clock_status_0; /* OFFSET: 0x2c0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd43[62]; /* OFFSET: 0x2c2 */
    MEMC_LPMMEMC_MEMC_PCLK_DESC_TYPE memc_pclk_desc; /* OFFSET: 0x300 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd44[2]; /* OFFSET: 0x302 */
    MEMC_LPMMEMC_PUB_CTL_CLK_DESC_TYPE pub_ctl_clk_desc; /* OFFSET: 0x304 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd45[2]; /* OFFSET: 0x306 */
    MEMC_LPMMEMC_PCSCD_TYPE pub_ctl_sdr_clk_desc; /* OFFSET: 0x308 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd46[2]; /* OFFSET: 0x30a */
    MEMC_LPMMEMC_PUB_PCLK_DESC_TYPE pub_pclk_desc; /* OFFSET: 0x30c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd47[2]; /* OFFSET: 0x30e */
    MEMC_LPMMEMC_MEMC_DDRCLK_DESC_TYPE memc_ddrclk_desc; /* OFFSET: 0x310 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd48[2]; /* OFFSET: 0x312 */
    MEMC_LPMMEMC_PHY_CTL_RD_CLK_DESC_TYPE phy_ctl_rd_clk_desc; /* OFFSET: 0x314 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd49[2]; /* OFFSET: 0x316 */
    MEMC_LPMMEMC_PPB1D_TYPE phy_pll_bypass1x_desc; /* OFFSET: 0x318 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd50[2]; /* OFFSET: 0x31a */
    MEMC_LPMMEMC_DOCD_TYPE dft_observe_clk_desc; /* OFFSET: 0x31c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd51[2]; /* OFFSET: 0x31e */
    MEMC_LPMMEMC_ATB_CLK_DESC_TYPE atb_clk_desc; /* OFFSET: 0x320 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd52[2]; /* OFFSET: 0x322 */
    MEMC_LPMMEMC_DSC0D_TYPE dft_scan_clk0_desc; /* OFFSET: 0x324 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd53[2]; /* OFFSET: 0x326 */
    MEMC_LPMMEMC_DSC1D_TYPE dft_scan_clk1_desc; /* OFFSET: 0x328 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd54[2]; /* OFFSET: 0x32a */
    MEMC_LPMMEMC_DSC2D_TYPE dft_scan_clk2_desc; /* OFFSET: 0x32c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd55[2]; /* OFFSET: 0x32e */
    MEMC_LPMMEMC_DSC3D_TYPE dft_scan_clk3_desc; /* OFFSET: 0x330 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd56[2]; /* OFFSET: 0x332 */
    MEMC_LPMMEMC_DSC4D_TYPE dft_scan_clk4_desc; /* OFFSET: 0x334 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd57[2]; /* OFFSET: 0x336 */
    MEMC_LPMMEMC_DSC5D_TYPE dft_scan_clk5_desc; /* OFFSET: 0x338 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd58[2]; /* OFFSET: 0x33a */
    MEMC_LPMMEMC_DSC6D_TYPE dft_scan_clk6_desc; /* OFFSET: 0x33c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd59[306]; /* OFFSET: 0x33e */
    MEMC_LPMMEMC_RIS_TYPE resetn_interrupt_status; /* OFFSET: 0x470 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd60[2]; /* OFFSET: 0x472 */
    MEMC_LPMMEMC_RSIE_TYPE resetn_status_int_enb; /* OFFSET: 0x474 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd61[2]; /* OFFSET: 0x476 */
    MEMC_LPMMEMC_RESETN_STATUS_TYPE resetn_status; /* OFFSET: 0x478 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd62[6]; /* OFFSET: 0x47a */
    MEMC_LPMMEMC_SOFTRESETN_0_TYPE softresetn_0; /* OFFSET: 0x480 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd63[30]; /* OFFSET: 0x482 */
    MEMC_LPMMEMC_RESETN_STATUS_0_TYPE resetn_status_0; /* OFFSET: 0x4a0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd64[30]; /* OFFSET: 0x4a2 */
    MEMC_LPMMEMC_RIE0_TYPE resetn_int_enable_0; /* OFFSET: 0x4c0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd65[62]; /* OFFSET: 0x4c2 */
    MEMC_LPMMEMC_MEASURE_COMMAND_TYPE measure_command; /* OFFSET: 0x500 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd66[2]; /* OFFSET: 0x502 */
    MEMC_LPMMEMC_MCS_TYPE measure_command_status; /* OFFSET: 0x504 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd67[2]; /* OFFSET: 0x506 */
    MEMC_LPMMEMC_MEASURE_CONTROL_TYPE measure_control; /* OFFSET: 0x508 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd68[6]; /* OFFSET: 0x50a */
    MEMC_LPMMEMC_MEASURE_CTRL_TIMER_TYPE measure_ctrl_timer; /* OFFSET: 0x510 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd69[14]; /* OFFSET: 0x512 */
    MEMC_LPMMEMC_MEASURE_SELECTION_CLOCK_TYPE measure_selection_clock; /* OFFSET: 0x520 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd70[14]; /* OFFSET: 0x522 */
    MEMC_LPMMEMC_MEASURE_RESULT_LSB_TYPE measure_result_lsb; /* OFFSET: 0x530 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd71[2]; /* OFFSET: 0x532 */
    MEMC_LPMMEMC_MEASURE_RESULT_MSB_TYPE measure_result_msb; /* OFFSET: 0x534 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd72[2]; /* OFFSET: 0x536 */
    MEMC_LPMMEMC_MEASURE_RESULT_EVENT_TYPE measure_result_event; /* OFFSET: 0x538 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd73[2]; /* OFFSET: 0x53a */
    MEMC_LPMMEMC_MEASURE_RESULT_FREQ_TYPE measure_result_freq; /* OFFSET: 0x53c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd74[2]; /* OFFSET: 0x53e */
    MEMC_LPMMEMC_MRTL_TYPE measure_reference_timer_lsb; /* OFFSET: 0x540 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd75[2]; /* OFFSET: 0x542 */
    MEMC_LPMMEMC_MRTM_TYPE measure_reference_timer_msb; /* OFFSET: 0x544 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd76[58]; /* OFFSET: 0x546 */
    MEMC_LPMMEMC_CLOCK_MONITOR_TYPE clock_monitor; /* OFFSET: 0x580 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd77[2]; /* OFFSET: 0x582 */
    MEMC_LPMMEMC_CLOCK_MONITOR_DIVIDER_TYPE clock_monitor_divider; /* OFFSET: 0x584 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd78[122]; /* OFFSET: 0x586 */
    MEMC_LPMMEMC_SEL_DEBUG_VECTOR_TYPE sel_debug_vector; /* OFFSET: 0x600 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd79[46]; /* OFFSET: 0x602 */
    MEMC_LPMMEMC_DEBUG_CONTROL_TYPE debug_control; /* OFFSET: 0x630 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd80[2]; /* OFFSET: 0x632 */
    MEMC_LPMMEMC_DEBUG_TRIGGER_TYPE debug_trigger; /* OFFSET: 0x634 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd81[10]; /* OFFSET: 0x636 */
    MEMC_LPMMEMC_DEBUG_ENABLE_0_TYPE debug_enable_0; /* OFFSET: 0x640 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd82[446]; /* OFFSET: 0x642 */
    MEMC_LPMMEMC_DOMAIN_MEMC_CONTROL_TYPE domain_memc_control; /* OFFSET: 0x800 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd83[46]; /* OFFSET: 0x802 */
    MEMC_LPMMEMC_DOMAIN_ON_OK_AUTO_CONTROL_TYPE domain_on_ok_auto_control; /* OFFSET: 0x830 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd84[2]; /* OFFSET: 0x832 */
    MEMC_LPMMEMC_DOMAIN_ON2OK_AUTO_CONTROL_TYPE domain_on2ok_auto_control; /* OFFSET: 0x834 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd85[10]; /* OFFSET: 0x836 */
    MEMC_LPMMEMC_PIE1_TYPE pwron_int_enable; /* OFFSET: 0x840 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd86[2]; /* OFFSET: 0x842 */
    MEMC_LPMMEMC_PIE2_TYPE pwrok_int_enable; /* OFFSET: 0x844 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd87[10]; /* OFFSET: 0x846 */
    MEMC_LPMMEMC_PIS_TYPE pwron_interrupt_status; /* OFFSET: 0x850 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd88[2]; /* OFFSET: 0x852 */
    MEMC_LPMMEMC_PIS1_TYPE pwrok_interrupt_status; /* OFFSET: 0x854 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd89[2]; /* OFFSET: 0x856 */
    MEMC_LPMMEMC_PWRONOUT_STATUS_TYPE pwronout_status; /* OFFSET: 0x858 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd90[2]; /* OFFSET: 0x85a */
    MEMC_LPMMEMC_PWROKOUT_STATUS_TYPE pwrokout_status; /* OFFSET: 0x85c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd91[34]; /* OFFSET: 0x85e */
    MEMC_LPMMEMC_PWRON_IN_DOMAIN_MEMC_TYPE pwron_in_domain_memc; /* OFFSET: 0x880 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd92[30]; /* OFFSET: 0x882 */
    MEMC_LPMMEMC_PWRON_OUT_DOMAIN_MEMC_TYPE pwron_out_domain_memc; /* OFFSET: 0x8a0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd93[30]; /* OFFSET: 0x8a2 */
    MEMC_LPMMEMC_PWROK_IN_DOMAIN_MEMC_TYPE pwrok_in_domain_memc; /* OFFSET: 0x8c0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd94[30]; /* OFFSET: 0x8c2 */
    MEMC_LPMMEMC_PWROK_OUT_DOMAIN_MEMC_TYPE pwrok_out_domain_memc; /* OFFSET: 0x8e0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd95[558]; /* OFFSET: 0x8e2 */
    MEMC_LPMMEMC_SUBSYSTEM_MUXED_SS_CLEAR_TYPE subsystem_muxed_ss_clear; /* OFFSET: 0xb10 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd96[46]; /* OFFSET: 0xb12 */
    MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_0_TYPE subsystem_memory_control_0; /* OFFSET: 0xb40 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd97[2]; /* OFFSET: 0xb42 */
    MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_1_TYPE subsystem_memory_control_1; /* OFFSET: 0xb44 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd98[10]; /* OFFSET: 0xb46 */
    MEMC_LPMMEMC_SMCT0_TYPE subsystem_memory_control_tm0; /* OFFSET: 0xb50 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd99[2]; /* OFFSET: 0xb52 */
    MEMC_LPMMEMC_SMCT1_TYPE subsystem_memory_control_tm1; /* OFFSET: 0xb54 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd100[2]; /* OFFSET: 0xb56 */
    MEMC_LPMMEMC_SMCT2_TYPE subsystem_memory_control_tm2; /* OFFSET: 0xb58 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd101[2]; /* OFFSET: 0xb5a */
    MEMC_LPMMEMC_SMCT3_TYPE subsystem_memory_control_tm3; /* OFFSET: 0xb5c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd102[2]; /* OFFSET: 0xb5e */
    MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH0_TYPE subsystem_memory_control_tech0; /* OFFSET: 0xb60 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd103[2]; /* OFFSET: 0xb62 */
    MEMC_LPMMEMC_SMCT11_TYPE subsystem_memory_control_tech1; /* OFFSET: 0xb64 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd104[2]; /* OFFSET: 0xb66 */
    MEMC_LPMMEMC_SUBSYSTEM_MEMORY_CONTROL_TECH2_TYPE subsystem_memory_control_tech2; /* OFFSET: 0xb68 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd105[150]; /* OFFSET: 0xb6a */
    MEMC_LPMMEMC_SIS_TYPE subsystem_interrupt_status; /* OFFSET: 0xc00 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd106[6]; /* OFFSET: 0xc02 */
    MEMC_LPMMEMC_SIE_TYPE subsystem_interrupt_enable; /* OFFSET: 0xc08 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd107[6]; /* OFFSET: 0xc0a */
    MEMC_LPMMEMC_SIS1_TYPE subsystem_interrupt_signal; /* OFFSET: 0xc10 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd108[6]; /* OFFSET: 0xc12 */
    MEMC_LPMMEMC_SISE_TYPE subsystem_interrupt_status_enable; /* OFFSET: 0xc18 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd109[6]; /* OFFSET: 0xc1a */
    MEMC_LPMMEMC_SIC_TYPE subsystem_interrupt_control; /* OFFSET: 0xc20 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd110[30]; /* OFFSET: 0xc22 */
    MEMC_LPMMEMC_SS0_TYPE subsystem_status_0; /* OFFSET: 0xc40 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd111[2]; /* OFFSET: 0xc42 */
    MEMC_LPMMEMC_SS1_TYPE subsystem_status_1; /* OFFSET: 0xc44 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd112[2]; /* OFFSET: 0xc46 */
    MEMC_LPMMEMC_SUBSYSTEM_STATUS_2_TYPE subsystem_status_2; /* OFFSET: 0xc48 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd113[2]; /* OFFSET: 0xc4a */
    MEMC_LPMMEMC_SUBSYSTEM_STATUS_3_TYPE subsystem_status_3; /* OFFSET: 0xc4c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd114[50]; /* OFFSET: 0xc4e */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_0_TYPE subsystem_config_0; /* OFFSET: 0xc80 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd115[2]; /* OFFSET: 0xc82 */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_1_TYPE subsystem_config_1; /* OFFSET: 0xc84 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd116[2]; /* OFFSET: 0xc86 */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_2_TYPE subsystem_config_2; /* OFFSET: 0xc88 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd117[2]; /* OFFSET: 0xc8a */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_3_TYPE subsystem_config_3; /* OFFSET: 0xc8c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd118[2]; /* OFFSET: 0xc8e */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_4_TYPE subsystem_config_4; /* OFFSET: 0xc90 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd119[2]; /* OFFSET: 0xc92 */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_5_TYPE subsystem_config_5; /* OFFSET: 0xc94 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd120[2]; /* OFFSET: 0xc96 */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_6_TYPE subsystem_config_6; /* OFFSET: 0xc98 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd121[2]; /* OFFSET: 0xc9a */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_7_TYPE subsystem_config_7; /* OFFSET: 0xc9c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd122[2]; /* OFFSET: 0xc9e */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_8_TYPE subsystem_config_8; /* OFFSET: 0xca0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd123[2]; /* OFFSET: 0xca2 */
    MEMC_LPMMEMC_SUBSYSTEM_CONFIG_9_TYPE subsystem_config_9; /* OFFSET: 0xca4 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd124[26]; /* OFFSET: 0xca6 */
    MEMC_LPMMEMC_SUBSYSTEM_IS_ON_0_TYPE subsystem_is_on_0; /* OFFSET: 0xcc0 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd125[318]; /* OFFSET: 0xcc2 */
    MEMC_LPMMEMC_SPARE_TYPE spare; /* OFFSET: 0xe00 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd126[254]; /* OFFSET: 0xe02 */
    MEMC_LPMMEMC_SECURITY_TZPROT_0_TYPE security_tzprot_0; /* OFFSET: 0xf00 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd127[2]; /* OFFSET: 0xf02 */
    MEMC_LPMMEMC_SECURITY_TZPROT_1_TYPE security_tzprot_1; /* OFFSET: 0xf04 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd128[2]; /* OFFSET: 0xf06 */
    MEMC_LPMMEMC_SDE0_TYPE security_debug_enable_0; /* OFFSET: 0xf08 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd129[2]; /* OFFSET: 0xf0a */
    MEMC_LPMMEMC_SDE1_TYPE security_debug_enable_1; /* OFFSET: 0xf0c */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd130[2]; /* OFFSET: 0xf0e */
    MEMC_LPMMEMC_SHC0_TYPE security_hardware_config_0; /* OFFSET: 0xf10 */
    MEMC_LPMMEMC_RESERVED_TYPE rsvd131[2]; /* OFFSET: 0xf12 */
    MEMC_LPMMEMC_SHC1_TYPE security_hardware_config_1; /* OFFSET: 0xf14 */
} MEMC_LPMMEMC_RDBType;


#define MEMC_LPMMEMC_BASE               (0xE0200000UL)



#define MEMC_LPMMEMC_MAX_HW_ID          (1UL)


#define MEMC_LPMMEMC_CRYSTAL_CONTROL_FRQ_26M  (0UL)


#define MEMC_LPMMEMC_PWRON_IN_LGC_WEAK_PWRSW_MASK  (2UL)


#define MEMC_LPMMEMC_PWRON_IN_MEM_WEAK_PWRSW_MASK  (1UL)


#define MEMC_LPMMEMC_PWRON_IN_LGC_STRG_PWRSW_MASK  (2UL)


#define MEMC_LPMMEMC_PWRON_IN_MEM_STRG_PWRSW_MASK  (1UL)


#define MEMC_LPMMEMC_ATB_CLK_DESC_DIVIDER_DIV2  (1UL)


#define MEMC_LPMMEMC_SECURITY_TZPROT_0_PHY_REG_VALUE_MASK  (8UL)


#define MEMC_LPMMEMC_SECURITY_TZPROT_0_MEMC_OPEN_VALUE_MASK  (0x0400UL)


#define MEMC_LPMMEMC_SECURITY_TZPROT_0_MMMMU_OPEN_IMG_VALUE_MASK  (0x800UL)


#define MEMC_LPMMEMC_SECURITY_TZPROT_0_MMMMU_OPEN_GPX_VALUE_MASK  (0x1000UL)


#define MEMC_LPMMEMC_CLOC_CONT_0_OFF    (2UL)


#define MEMC_LPMMEMC_CLOC_CONT_0_ALWAYS_ON  (3UL)


#define MEMC_LPMMEMC_CLOC_CONT_0_PUB_CTL_HW_SW_ENABLE  (0UL)


#define MEMC_LPMMEMC_CLOC_CONT_0_MEMC_PCLK_HW_SW_ENABLE  (0UL)

#endif /* MEMC_LPMMEMC_RDB_H */
