/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_dphy_csr_rdb.h
    @brief RDB File for MEMC_DPHY_CSR

    @version 2018May25_rdb
*/

#ifndef MEMC_DPHY_CSR_RDB_H
#define MEMC_DPHY_CSR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MEMC_DPHY_CSR_DQ_REV_ID_TYPE;
#define MEMC_DPHY_CSR_DQ_REV_ID_MAJOR_MASK (0xff00UL)
#define MEMC_DPHY_CSR_DQ_REV_ID_MAJOR_SHIFT (8UL)
#define MEMC_DPHY_CSR_DQ_REV_ID_MINOR_MASK (0xffUL)
#define MEMC_DPHY_CSR_DQ_REV_ID_MINOR_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RESET_TYPE;
#define MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RESET_RESET_MASK (0x1UL)
#define MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RESET_RESET_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RECALIBRATE_TYPE;
#define MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RECALIBRATE_RECALIBRATE_MASK (0x1UL)
#define MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RECALIBRATE_RECALIBRATE_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_GDDC_TYPE;
#define MEMC_DPHY_CSR_GDDC_DLL_RECALIBRATION_ENABLE_MASK (0x100UL)
#define MEMC_DPHY_CSR_GDDC_DLL_RECALIBRATION_ENABLE_SHIFT (8UL)
#define MEMC_DPHY_CSR_GDDC_DLL_PHASE_SEL_MASK (0x3UL)
#define MEMC_DPHY_CSR_GDDC_DLL_PHASE_SEL_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_GDDPLV_TYPE;
#define MEMC_DPHY_CSR_GDDPLV_DLL_RELOAD_PHASE_MASK (0x3fUL)
#define MEMC_DPHY_CSR_GDDPLV_DLL_RELOAD_PHASE_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_GDMDBE_TYPE;
#define MEMC_DPHY_CSR_GDMDBE_BYTE3_WRITE_MASTER_DLL_BYPASS_MASK (0x80UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE3_WRITE_MASTER_DLL_BYPASS_SHIFT (7UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE3_READ_MASTER_DLL_BYPASS_MASK (0x40UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE3_READ_MASTER_DLL_BYPASS_SHIFT (6UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE2_WRITE_MASTER_DLL_BYPASS_MASK (0x20UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE2_WRITE_MASTER_DLL_BYPASS_SHIFT (5UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE2_READ_MASTER_DLL_BYPASS_MASK (0x10UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE2_READ_MASTER_DLL_BYPASS_SHIFT (4UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE1_WRITE_MASTER_DLL_BYPASS_MASK (0x8UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE1_WRITE_MASTER_DLL_BYPASS_SHIFT (3UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE1_READ_MASTER_DLL_BYPASS_MASK (0x4UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE1_READ_MASTER_DLL_BYPASS_SHIFT (2UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE0_WRITE_MASTER_DLL_BYPASS_MASK (0x2UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE0_WRITE_MASTER_DLL_BYPASS_SHIFT (1UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE0_READ_MASTER_DLL_BYPASS_MASK (0x1UL)
#define MEMC_DPHY_CSR_GDMDBE_BYTE0_READ_MASTER_DLL_BYPASS_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_GMDLS_TYPE;
#define MEMC_DPHY_CSR_GMDLS_BYTE3_WRITE_MASTER_DLL_LOCK_P_MASK (0x8000UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_WRITE_MASTER_DLL_LOCK_P_SHIFT (15UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_WRITE_MASTER_DLL_LOCK_N_MASK (0x4000UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_WRITE_MASTER_DLL_LOCK_N_SHIFT (14UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_READ_MASTER_DLL_LOCK_P_MASK (0x2000UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_READ_MASTER_DLL_LOCK_P_SHIFT (13UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_READ_MASTER_DLL_LOCK_N_MASK (0x1000UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE3_READ_MASTER_DLL_LOCK_N_SHIFT (12UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_WRITE_MASTER_DLL_LOCK_P_MASK (0x800UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_WRITE_MASTER_DLL_LOCK_P_SHIFT (11UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_WRITE_MASTER_DLL_LOCK_N_MASK (0x400UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_WRITE_MASTER_DLL_LOCK_N_SHIFT (10UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_READ_MASTER_DLL_LOCK_P_MASK (0x200UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_READ_MASTER_DLL_LOCK_P_SHIFT (9UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_READ_MASTER_DLL_LOCK_N_MASK (0x100UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE2_READ_MASTER_DLL_LOCK_N_SHIFT (8UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_WRITE_MASTER_DLL_LOCK_P_MASK (0x80UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_WRITE_MASTER_DLL_LOCK_P_SHIFT (7UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_WRITE_MASTER_DLL_LOCK_N_MASK (0x40UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_WRITE_MASTER_DLL_LOCK_N_SHIFT (6UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_READ_MASTER_DLL_LOCK_P_MASK (0x20UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_READ_MASTER_DLL_LOCK_P_SHIFT (5UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_READ_MASTER_DLL_LOCK_N_MASK (0x10UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE1_READ_MASTER_DLL_LOCK_N_SHIFT (4UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_WRITE_MASTER_DLL_LOCK_P_MASK (0x8UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_WRITE_MASTER_DLL_LOCK_P_SHIFT (3UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_WRITE_MASTER_DLL_LOCK_N_MASK (0x4UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_WRITE_MASTER_DLL_LOCK_N_SHIFT (2UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_READ_MASTER_DLL_LOCK_P_MASK (0x2UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_READ_MASTER_DLL_LOCK_P_SHIFT (1UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_READ_MASTER_DLL_LOCK_N_MASK (0x1UL)
#define MEMC_DPHY_CSR_GMDLS_BYTE0_READ_MASTER_DLL_LOCK_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B0SDO_TYPE;
#define MEMC_DPHY_CSR_B0SDO_BYTE0_SLAVE_WRITE_OFFSET_MASK (0x7f0000UL)
#define MEMC_DPHY_CSR_B0SDO_BYTE0_SLAVE_WRITE_OFFSET_SHIFT (16UL)
#define MEMC_DPHY_CSR_B0SDO_BYTE0_SLAVE_READ_OFFSET_P_MASK (0x7f00UL)
#define MEMC_DPHY_CSR_B0SDO_BYTE0_SLAVE_READ_OFFSET_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B0SDO_BYTE0_SLAVE_READ_OFFSET_N_MASK (0x7fUL)
#define MEMC_DPHY_CSR_B0SDO_BYTE0_SLAVE_READ_OFFSET_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B1SDO_TYPE;
#define MEMC_DPHY_CSR_B1SDO_BYTE1_SLAVE_WRITE_OFFSET_MASK (0x7f0000UL)
#define MEMC_DPHY_CSR_B1SDO_BYTE1_SLAVE_WRITE_OFFSET_SHIFT (16UL)
#define MEMC_DPHY_CSR_B1SDO_BYTE1_SLAVE_READ_OFFSET_P_MASK (0x7f00UL)
#define MEMC_DPHY_CSR_B1SDO_BYTE1_SLAVE_READ_OFFSET_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B1SDO_BYTE1_SLAVE_READ_OFFSET_N_MASK (0x7fUL)
#define MEMC_DPHY_CSR_B1SDO_BYTE1_SLAVE_READ_OFFSET_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B2SDO_TYPE;
#define MEMC_DPHY_CSR_B2SDO_BYTE2_SLAVE_WRITE_OFFSET_MASK (0x7f0000UL)
#define MEMC_DPHY_CSR_B2SDO_BYTE2_SLAVE_WRITE_OFFSET_SHIFT (16UL)
#define MEMC_DPHY_CSR_B2SDO_BYTE2_SLAVE_READ_OFFSET_P_MASK (0x7f00UL)
#define MEMC_DPHY_CSR_B2SDO_BYTE2_SLAVE_READ_OFFSET_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B2SDO_BYTE2_SLAVE_READ_OFFSET_N_MASK (0x7fUL)
#define MEMC_DPHY_CSR_B2SDO_BYTE2_SLAVE_READ_OFFSET_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B3SDO_TYPE;
#define MEMC_DPHY_CSR_B3SDO_BYTE3_SLAVE_WRITE_OFFSET_MASK (0x7f0000UL)
#define MEMC_DPHY_CSR_B3SDO_BYTE3_SLAVE_WRITE_OFFSET_SHIFT (16UL)
#define MEMC_DPHY_CSR_B3SDO_BYTE3_SLAVE_READ_OFFSET_P_MASK (0x7f00UL)
#define MEMC_DPHY_CSR_B3SDO_BYTE3_SLAVE_READ_OFFSET_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B3SDO_BYTE3_SLAVE_READ_OFFSET_N_MASK (0x7fUL)
#define MEMC_DPHY_CSR_B3SDO_BYTE3_SLAVE_READ_OFFSET_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B0MDO_TYPE;
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_WRITE_PHASE_P_MASK (0x3f000000UL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_WRITE_PHASE_P_SHIFT (24UL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_WRITE_PHASE_N_MASK (0x3f0000UL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_WRITE_PHASE_N_SHIFT (16UL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_READ_PHASE_P_MASK (0x3f00UL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_READ_PHASE_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_READ_PHASE_N_MASK (0x3fUL)
#define MEMC_DPHY_CSR_B0MDO_BYTE0_MASTER_READ_PHASE_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B1MDO_TYPE;
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_WRITE_PHASE_P_MASK (0x3f000000UL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_WRITE_PHASE_P_SHIFT (24UL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_WRITE_PHASE_N_MASK (0x3f0000UL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_WRITE_PHASE_N_SHIFT (16UL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_READ_PHASE_P_MASK (0x3f00UL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_READ_PHASE_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_READ_PHASE_N_MASK (0x3fUL)
#define MEMC_DPHY_CSR_B1MDO_BYTE1_MASTER_READ_PHASE_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B2MDO_TYPE;
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_WRITE_PHASE_P_MASK (0x3f000000UL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_WRITE_PHASE_P_SHIFT (24UL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_WRITE_PHASE_N_MASK (0x3f0000UL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_WRITE_PHASE_N_SHIFT (16UL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_READ_PHASE_P_MASK (0x3f00UL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_READ_PHASE_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_READ_PHASE_N_MASK (0x3fUL)
#define MEMC_DPHY_CSR_B2MDO_BYTE2_MASTER_READ_PHASE_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_B3MDO_TYPE;
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_WRITE_PHASE_P_MASK (0x3f000000UL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_WRITE_PHASE_P_SHIFT (24UL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_WRITE_PHASE_N_MASK (0x3f0000UL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_WRITE_PHASE_N_SHIFT (16UL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_READ_PHASE_P_MASK (0x3f00UL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_READ_PHASE_P_SHIFT (8UL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_READ_PHASE_N_MASK (0x3fUL)
#define MEMC_DPHY_CSR_B3MDO_BYTE3_MASTER_READ_PHASE_N_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_NRDGC_TYPE;
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_3_MASK (0xc0000000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_3_SHIFT (30UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_3_MASK (0x30000000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_3_SHIFT (28UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_3_MASK (0xc000000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_3_SHIFT (26UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_3_MASK (0x3000000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_3_SHIFT (24UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_2_MASK (0xc00000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_2_SHIFT (22UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_2_MASK (0x300000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_2_SHIFT (20UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_2_MASK (0xc0000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_2_SHIFT (18UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_2_MASK (0x30000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_2_SHIFT (16UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_1_MASK (0xc000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_1_SHIFT (14UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_1_MASK (0x3000UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_1_SHIFT (12UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_1_MASK (0xc00UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_1_SHIFT (10UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_1_MASK (0x300UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_1_SHIFT (8UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_0_MASK (0xc0UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_TDQSCK_0_SHIFT (6UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_0_MASK (0x30UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_TDQSCK_0_SHIFT (4UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_0_MASK (0xcUL)
#define MEMC_DPHY_CSR_NRDGC_DRAM1_GATE_EDGE_SEL_0_SHIFT (2UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_0_MASK (0x3UL)
#define MEMC_DPHY_CSR_NRDGC_DRAM0_GATE_EDGE_SEL_0_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_BOOT_READ_DQS_GATE_CNTRL_TYPE;
#define MEMC_DPHY_CSR_BOOT_READ_DQS_GATE_CNTRL_TDQSCK_MASK (0x18UL)
#define MEMC_DPHY_CSR_BOOT_READ_DQS_GATE_CNTRL_TDQSCK_SHIFT (3UL)
#define MEMC_DPHY_CSR_BOOT_READ_DQS_GATE_CNTRL_GATE_EDGE_SEL_MASK (0x3UL)
#define MEMC_DPHY_CSR_BOOT_READ_DQS_GATE_CNTRL_GATE_EDGE_SEL_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_PHY_FIFO_PNTRS_TYPE;
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE3_RD_PNTR_MASK (0x30000000UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE3_RD_PNTR_SHIFT (28UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE2_RD_PNTR_MASK (0x3000000UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE2_RD_PNTR_SHIFT (24UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE1_RD_PNTR_MASK (0x300000UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE1_RD_PNTR_SHIFT (20UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE0_RD_PNTR_MASK (0x30000UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE0_RD_PNTR_SHIFT (16UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE3_WR_PNTR_MASK (0x3000UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE3_WR_PNTR_SHIFT (12UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE2_WR_PNTR_MASK (0x300UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE2_WR_PNTR_SHIFT (8UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE1_WR_PNTR_MASK (0x30UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE1_WR_PNTR_SHIFT (4UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE0_WR_PNTR_MASK (0x3UL)
#define MEMC_DPHY_CSR_PHY_FIFO_PNTRS_BYTE0_WR_PNTR_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_TYPE;
#define MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_SRC_SYNC_DQS_READ_EN_MASK (0x4UL)
#define MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_SRC_SYNC_DQS_READ_EN_SHIFT (2UL)
#define MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_DQ_DQS_OEB_OVERRIDE_MASK (0x2UL)
#define MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_DQ_DQS_OEB_OVERRIDE_SHIFT (1UL)
#define MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_RDQS_GATE_OVERRIDE_MASK (0x1UL)
#define MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_RDQS_GATE_OVERRIDE_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_TYPE;
#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_DQS_DRV_MASK (0x700UL)
#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_DQS_DRV_SHIFT (8UL)
#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_DQ_DM_DRV_MASK (0x70UL)
#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_DQ_DM_DRV_SHIFT (4UL)
#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_SLEW_MASK (0x7UL)
#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_SLEW_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_TYPE;
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_RT_EN_MASK (0x20UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_RT_EN_SHIFT (5UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_RT60_MASK (0x10UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_RT60_SHIFT (4UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_LPWR_RX_MASK (0x8UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_LPWR_RX_SHIFT (3UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_HCURR_SEL_MASK (0x4UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_HCURR_SEL_SHIFT (2UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_PDN_DQS_MASK (0x2UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_PDN_DQS_SHIFT (1UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_PDN_DQ_MASK (0x1UL)
#define MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_PDN_DQ_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_TYPE;
#define MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_OFFSET_OP_MASK (0x20UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_OFFSET_OP_SHIFT (5UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_OFFSET_EN_MASK (0x10UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_OFFSET_EN_SHIFT (4UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_EN_MASK (0x1UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_EN_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DPCOC_TYPE;
#define MEMC_DPHY_CSR_DPCOC_PVT_OVERRIDE_VAL_MASK (0xf00UL)
#define MEMC_DPHY_CSR_DPCOC_PVT_OVERRIDE_VAL_SHIFT (8UL)
#define MEMC_DPHY_CSR_DPCOC_PVT_OVERRIDE_MODE_MASK (0x70UL)
#define MEMC_DPHY_CSR_DPCOC_PVT_OVERRIDE_MODE_SHIFT (4UL)
#define MEMC_DPHY_CSR_DPCOC_PVT_OVERRIDE_EN_MASK (0x1UL)
#define MEMC_DPHY_CSR_DPCOC_PVT_OVERRIDE_EN_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PVT_COMP_STATUS_TYPE;
#define MEMC_DPHY_CSR_DQ_PVT_COMP_STATUS_DONE_MASK (0x2UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_STATUS_DONE_SHIFT (1UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_STATUS_ACK_MASK (0x1UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_STATUS_ACK_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_TYPE;
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_NCOMP_ENB_MASK (0x80000UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_NCOMP_ENB_SHIFT (19UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_PCOMP_ENB_MASK (0x40000UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_PCOMP_ENB_SHIFT (18UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_NDONE_MASK (0x20000UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_NDONE_SHIFT (17UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_PDONE_MASK (0x10000UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_PDONE_SHIFT (16UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_NCOMP_CODE_MASK (0x7000UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_NCOMP_CODE_SHIFT (12UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_PCOMP_CODE_MASK (0x700UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_PCOMP_CODE_SHIFT (8UL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_COMP_ERR_MASK (0x3fUL)
#define MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_COMP_ERR_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_TYPE;
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_DQS2CLK_BYP_RESYNC_MASK (0x400000UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_DQS2CLK_BYP_RESYNC_SHIFT (22UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_DQS2CLK_RESYNC_EDGE_SEL_MASK (0x200000UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_DQS2CLK_RESYNC_EDGE_SEL_SHIFT (21UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_EN_CLK2DQS_PH_DETECT_MASK (0x100000UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_EN_CLK2DQS_PH_DETECT_SHIFT (20UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_CLK2DQS_DQS_PH_MASK (0x3f000UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_CLK2DQS_DQS_PH_SHIFT (12UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_CLK2DQS_CLK_PH_MASK (0x3f0UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_CLK2DQS_CLK_PH_SHIFT (4UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_EN_READ_RECOVERY_MASK (0x1UL)
#define MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_EN_READ_RECOVERY_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DPRS_TYPE;
#define MEMC_DPHY_CSR_DPRS_PENDING_DQS_CNTR_MASK (0xff000000UL)
#define MEMC_DPHY_CSR_DPRS_PENDING_DQS_CNTR_SHIFT (24UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE3_MASK (0xf00000UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE3_SHIFT (20UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE2_MASK (0xf0000UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE2_SHIFT (16UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE1_MASK (0xf000UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE1_SHIFT (12UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE0_MASK (0xf00UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_SAMPLE_RESULT_BYTE0_SHIFT (8UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_DQS_EDGE_COUNT_MASK (0xf0UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_DQS_EDGE_COUNT_SHIFT (4UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE3_MASK (0x8UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE3_SHIFT (3UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE2_MASK (0x4UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE2_SHIFT (2UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE1_MASK (0x2UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE1_SHIFT (1UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE0_MASK (0x1UL)
#define MEMC_DPHY_CSR_DPRS_CLK2DQS_PH_DETECT_OUT_BYTE0_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_SPR0_RW_TYPE;
#define MEMC_DPHY_CSR_DQ_SPR0_RW_RW_MASK (0xffffffffUL)
#define MEMC_DPHY_CSR_DQ_SPR0_RW_RW_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_SPR1_RW_TYPE;
#define MEMC_DPHY_CSR_DQ_SPR1_RW_RW_MASK (0xffffffffUL)
#define MEMC_DPHY_CSR_DQ_SPR1_RW_RW_SHIFT (0UL)




typedef uint32_t MEMC_DPHY_CSR_DQ_SPR_RO_TYPE;
#define MEMC_DPHY_CSR_DQ_SPR_RO_RO_MASK (0xffffffffUL)
#define MEMC_DPHY_CSR_DQ_SPR_RO_RO_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MEMC_DPHY_CSR_RDBType {
    MEMC_DPHY_CSR_DQ_REV_ID_TYPE dq_rev_id; /* OFFSET: 0x0 */
    MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RESET_TYPE global_dq_dll_reset; /* OFFSET: 0x4 */
    MEMC_DPHY_CSR_GLOBAL_DQ_DLL_RECALIBRATE_TYPE global_dq_dll_recalibrate; /* OFFSET: 0x8 */
    MEMC_DPHY_CSR_GDDC_TYPE global_dq_dll_cntrl; /* OFFSET: 0xc */
    MEMC_DPHY_CSR_GDDPLV_TYPE global_dq_dll_phase_load_value; /* OFFSET: 0x10 */
    MEMC_DPHY_CSR_GDMDBE_TYPE global_dq_master_dll_bypass_enable; /* OFFSET: 0x14 */
    MEMC_DPHY_CSR_GMDLS_TYPE global_master_dll_lock_status; /* OFFSET: 0x18 */
    MEMC_DPHY_CSR_B0SDO_TYPE byte0_slave_dll_offset; /* OFFSET: 0x1c */
    MEMC_DPHY_CSR_B1SDO_TYPE byte1_slave_dll_offset; /* OFFSET: 0x20 */
    MEMC_DPHY_CSR_B2SDO_TYPE byte2_slave_dll_offset; /* OFFSET: 0x24 */
    MEMC_DPHY_CSR_B3SDO_TYPE byte3_slave_dll_offset; /* OFFSET: 0x28 */
    MEMC_DPHY_CSR_B0MDO_TYPE byte0_master_dll_output; /* OFFSET: 0x2c */
    MEMC_DPHY_CSR_B1MDO_TYPE byte1_master_dll_output; /* OFFSET: 0x30 */
    MEMC_DPHY_CSR_B2MDO_TYPE byte2_master_dll_output; /* OFFSET: 0x34 */
    MEMC_DPHY_CSR_B3MDO_TYPE byte3_master_dll_output; /* OFFSET: 0x38 */
    MEMC_DPHY_CSR_NRDGC_TYPE norm_read_dqs_gate_cntrl; /* OFFSET: 0x3c */
    MEMC_DPHY_CSR_BOOT_READ_DQS_GATE_CNTRL_TYPE boot_read_dqs_gate_cntrl; /* OFFSET: 0x40 */
    MEMC_DPHY_CSR_PHY_FIFO_PNTRS_TYPE phy_fifo_pntrs; /* OFFSET: 0x44 */
    MEMC_DPHY_CSR_DQ_PHY_MISC_CNTRL_TYPE dq_phy_misc_cntrl; /* OFFSET: 0x48 */
    MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_TYPE dq_pad_drv_slew_cntrl; /* OFFSET: 0x4c */
    MEMC_DPHY_CSR_DQ_PAD_MISC_CNTRL_TYPE dq_pad_misc_cntrl; /* OFFSET: 0x50 */
    MEMC_DPHY_CSR_DQ_PVT_COMP_CNTRL_TYPE dq_pvt_comp_cntrl; /* OFFSET: 0x54 */
    MEMC_DPHY_CSR_DPCOC_TYPE dq_pvt_comp_override_cntrl; /* OFFSET: 0x58 */
    MEMC_DPHY_CSR_DQ_PVT_COMP_STATUS_TYPE dq_pvt_comp_status; /* OFFSET: 0x5c */
    MEMC_DPHY_CSR_DQ_PVT_COMP_DEBUG_TYPE dq_pvt_comp_debug; /* OFFSET: 0x60 */
    MEMC_DPHY_CSR_DQ_PHY_READ_CNTRL_TYPE dq_phy_read_cntrl; /* OFFSET: 0x64 */
    MEMC_DPHY_CSR_DPRS_TYPE dq_phy_read_status; /* OFFSET: 0x68 */
    MEMC_DPHY_CSR_DQ_SPR0_RW_TYPE dq_spr0_rw; /* OFFSET: 0x6c */
    MEMC_DPHY_CSR_DQ_SPR1_RW_TYPE dq_spr1_rw; /* OFFSET: 0x70 */
    MEMC_DPHY_CSR_DQ_SPR_RO_TYPE dq_spr_ro; /* OFFSET: 0x74 */
} MEMC_DPHY_CSR_RDBType;


#define MEMC_DPHY_CSR_BASE              (0xE0203800UL)



#define MEMC_DPHY_CSR_MAX_HW_ID         (1UL)


#define MEMC_DPHY_CSR_DQ_PVT_COMP_OVERRIDE_MODE_PMOS_CNTRL_CODE  (1UL)


#define MEMC_DPHY_CSR_DQ_PVT_COMP_OVERRIDE_MODE_NMOS_CNTRL_CODE  (2UL)


#define MEMC_DPHY_CSR_GMDLS_GLOBAL_MASTER_DLL_LOCK_STATUS_LOCKED  (0xFFFFUL)


#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_48_OHM  (2UL)


#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_40_OHM  (3UL)


#define MEMC_DPHY_CSR_DQ_PAD_DRV_SLEW_CNTRL_PER_200  (7UL)

#endif /* MEMC_DPHY_CSR_RDB_H */
