/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_aphy_csr_rdb.h
    @brief RDB File for MEMC_APHY_CSR

    @version 2018May25_rdb
*/

#ifndef MEMC_APHY_CSR_RDB_H
#define MEMC_APHY_CSR_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MEMC_APHY_CSR_ADDR_REV_ID_TYPE;
#define MEMC_APHY_CSR_ADDR_REV_ID_MAJOR_MASK (0xff00UL)
#define MEMC_APHY_CSR_ADDR_REV_ID_MAJOR_SHIFT (8UL)
#define MEMC_APHY_CSR_ADDR_REV_ID_MINOR_MASK (0xffUL)
#define MEMC_APHY_CSR_ADDR_REV_ID_MINOR_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RESET_TYPE;
#define MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RESET_RESET_MASK (0x1UL)
#define MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RESET_RESET_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RECALIBRATE_TYPE;
#define MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RECALIBRATE_RECALIBRATE_MASK (0x1UL)
#define MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RECALIBRATE_RECALIBRATE_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_GADC_TYPE;
#define MEMC_APHY_CSR_GADC_DLL_RECALIBRATION_ENABLE_MASK (0x100UL)
#define MEMC_APHY_CSR_GADC_DLL_RECALIBRATION_ENABLE_SHIFT (8UL)
#define MEMC_APHY_CSR_GADC_DLL_PHASE_SEL_MASK (0x3UL)
#define MEMC_APHY_CSR_GADC_DLL_PHASE_SEL_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_GADPLV_TYPE;
#define MEMC_APHY_CSR_GADPLV_DLL_RELOAD_PHASE_MASK (0x3fUL)
#define MEMC_APHY_CSR_GADPLV_DLL_RELOAD_PHASE_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_MASTER_DLL_OUTPUT_TYPE;
#define MEMC_APHY_CSR_ADDR_MASTER_DLL_OUTPUT_PHASE_P_MASK (0x3f00UL)
#define MEMC_APHY_CSR_ADDR_MASTER_DLL_OUTPUT_PHASE_P_SHIFT (8UL)
#define MEMC_APHY_CSR_ADDR_MASTER_DLL_OUTPUT_PHASE_N_MASK (0x3fUL)
#define MEMC_APHY_CSR_ADDR_MASTER_DLL_OUTPUT_PHASE_N_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_SLAVE_DLL_OFFSET_TYPE;
#define MEMC_APHY_CSR_ADDR_SLAVE_DLL_OFFSET_OFFSET_MASK (0x7fUL)
#define MEMC_APHY_CSR_ADDR_SLAVE_DLL_OFFSET_OFFSET_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_GAMDBE_TYPE;
#define MEMC_APHY_CSR_GAMDBE_ADDR_MASTER_DLL_BYPASS_MASK (0x1UL)
#define MEMC_APHY_CSR_GAMDBE_ADDR_MASTER_DLL_BYPASS_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_GADLS_TYPE;
#define MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_P_MASK (0x2UL)
#define MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_P_SHIFT (1UL)
#define MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_N_MASK (0x1UL)
#define MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_N_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_GLOBAL_RESET_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_GLOBAL_RESET_RESETB_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_GLOBAL_RESET_RESETB_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_POST_DIVIDER_RESET_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_POST_DIVIDER_RESET_RESETB_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_POST_DIVIDER_RESET_RESETB_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL0_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL0_PDIV_MASK (0xf0000UL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL0_PDIV_SHIFT (16UL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL0_NDIV_INT_MASK (0x3ffUL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL0_NDIV_INT_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL1_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL1_NDIV_FRAC_MASK (0xfffffUL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL1_NDIV_FRAC_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_MDIV2_MASK (0xff00UL)
#define MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_MDIV2_SHIFT (8UL)
#define MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_MDIV_MASK (0xffUL)
#define MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_MDIV_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_CONFIG_CNTRL_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_CONFIG_CNTRL_CFG_CNTRL_MASK (0x1fffffUL)
#define MEMC_APHY_CSR_DDR_PLL_CONFIG_CNTRL_CFG_CNTRL_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_EIGHT_PHASE_EN_MASK (0x2000000UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_EIGHT_PHASE_EN_SHIFT (25UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_FB_PHASE_EN_MASK (0x1000000UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_FB_PHASE_EN_SHIFT (24UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_FB_PHASE_OFFSET_MASK (0xfff000UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_FB_PHASE_OFFSET_SHIFT (12UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_KP_MASK (0xf00UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_KP_SHIFT (8UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_KI_MASK (0x70UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_KI_SHIFT (4UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_KA_MASK (0x7UL)
#define MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_KA_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL0_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL0_SSC_LIMIT_MASK (0x3fffff0UL)
#define MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL0_SSC_LIMIT_SHIFT (4UL)
#define MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL0_SSC_MODE_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL0_SSC_MODE_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL1_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL1_SSC_STEP_MASK (0xffffUL)
#define MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL1_SSC_STEP_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_LOCK_LOST_MASK (0x20000UL)
#define MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_LOCK_LOST_SHIFT (17UL)
#define MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_LOCK_BIT_MASK (0x10000UL)
#define MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_LOCK_BIT_SHIFT (16UL)
#define MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_STAT_OUT_MASK (0xfffUL)
#define MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_STAT_OUT_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_HOLD_CH_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_HOLD_CH_CH_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_HOLD_CH_CH_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_ENABLE_CH_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_ENABLE_CH_ENABLEB_CH_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_ENABLE_CH_ENABLEB_CH_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_BYPASS_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_BYPASS_BYPASS_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_BYPASS_BYPASS_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_PWRDWN_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_PWRDWN_PWRDWN_MASK (0x1UL)
#define MEMC_APHY_CSR_DDR_PLL_PWRDWN_PWRDWN_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_CH0_DESKEW_CNTRL_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_CH0_DESKEW_CNTRL_MDEL_MASK (0x3fUL)
#define MEMC_APHY_CSR_DDR_PLL_CH0_DESKEW_CNTRL_MDEL_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_DDR_MDEL_MASK (0x3f000UL)
#define MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_DDR_MDEL_SHIFT (12UL)
#define MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_FBOFFS_MASK (0x1f0UL)
#define MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_FBOFFS_SHIFT (4UL)
#define MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_FBMODE_MASK (0x3UL)
#define MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_FBMODE_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_DESKEW_STATUS_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_DESKEW_STATUS_CH1_FBCLK_LOCK_MASK (0x100UL)
#define MEMC_APHY_CSR_DDR_PLL_DESKEW_STATUS_CH1_FBCLK_LOCK_SHIFT (8UL)
#define MEMC_APHY_CSR_DDR_PLL_DESKEW_STATUS_CH1_MDEL_STAT_MASK (0x3fUL)
#define MEMC_APHY_CSR_DDR_PLL_DESKEW_STATUS_CH1_MDEL_STAT_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_TYPE;
#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_CLK_DRV_MASK (0x700UL)
#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_CLK_DRV_SHIFT (8UL)
#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_CA_DRV_MASK (0x70UL)
#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_CA_DRV_SHIFT (4UL)
#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_SLEW_MASK (0x7UL)
#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_SLEW_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_TYPE;
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_PDN_CLK_MASK (0x20UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_PDN_CLK_SHIFT (5UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_RT_EN_MASK (0x10UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_RT_EN_SHIFT (4UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_RT60_MASK (0x8UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_RT60_SHIFT (3UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_LPWR_RX_MASK (0x4UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_LPWR_RX_SHIFT (2UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_HCURR_SEL_MASK (0x2UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_HCURR_SEL_SHIFT (1UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_PDN_MASK (0x1UL)
#define MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_PDN_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_TYPE;
#define MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_OFFSET_OP_MASK (0x20UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_OFFSET_OP_SHIFT (5UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_OFFSET_EN_MASK (0x10UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_OFFSET_EN_SHIFT (4UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_EN_MASK (0x1UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_EN_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_APCOC_TYPE;
#define MEMC_APHY_CSR_APCOC_PVT_OVERRIDE_VAL_MASK (0xf00UL)
#define MEMC_APHY_CSR_APCOC_PVT_OVERRIDE_VAL_SHIFT (8UL)
#define MEMC_APHY_CSR_APCOC_PVT_OVERRIDE_MODE_MASK (0x70UL)
#define MEMC_APHY_CSR_APCOC_PVT_OVERRIDE_MODE_SHIFT (4UL)
#define MEMC_APHY_CSR_APCOC_PVT_OVERRIDE_EN_MASK (0x1UL)
#define MEMC_APHY_CSR_APCOC_PVT_OVERRIDE_EN_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_PVT_COMP_STATUS_TYPE;
#define MEMC_APHY_CSR_ADDR_PVT_COMP_STATUS_DONE_MASK (0x2UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_STATUS_DONE_SHIFT (1UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_STATUS_ACK_MASK (0x1UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_STATUS_ACK_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_TYPE;
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_NCOMP_ENB_MASK (0x80000UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_NCOMP_ENB_SHIFT (19UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_PCOMP_ENB_MASK (0x40000UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_PCOMP_ENB_SHIFT (18UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_NDONE_MASK (0x20000UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_NDONE_SHIFT (17UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_PDONE_MASK (0x10000UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_PDONE_SHIFT (16UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_NCOMP_CODE_MASK (0x7000UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_NCOMP_CODE_SHIFT (12UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_PCOMP_CODE_MASK (0x700UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_PCOMP_CODE_SHIFT (8UL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_COMP_ERR_MASK (0x3fUL)
#define MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_COMP_ERR_SHIFT (0UL)




typedef uint8_t MEMC_APHY_CSR_RESERVED_TYPE;




typedef uint32_t MEMC_APHY_CSR_DSDPC_TYPE;
#define MEMC_APHY_CSR_DSDPC_DISABLE_SOFT_PLL_CNTRL_MASK (0x1UL)
#define MEMC_APHY_CSR_DSDPC_DISABLE_SOFT_PLL_CNTRL_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_PHY_BIST_CA_CRC_SPR_TYPE;
#define MEMC_APHY_CSR_PHY_BIST_CA_CRC_SPR_RISE_CRC_MASK (0xffff0000UL)
#define MEMC_APHY_CSR_PHY_BIST_CA_CRC_SPR_RISE_CRC_SHIFT (16UL)
#define MEMC_APHY_CSR_PHY_BIST_CA_CRC_SPR_FALL_CRC_MASK (0xffffUL)
#define MEMC_APHY_CSR_PHY_BIST_CA_CRC_SPR_FALL_CRC_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_SPR0_RW_TYPE;
#define MEMC_APHY_CSR_ADDR_SPR0_RW_RW_MASK (0xffffffffUL)
#define MEMC_APHY_CSR_ADDR_SPR0_RW_RW_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_SPR1_RW_TYPE;
#define MEMC_APHY_CSR_ADDR_SPR1_RW_RW_MASK (0xffffffffUL)
#define MEMC_APHY_CSR_ADDR_SPR1_RW_RW_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_ADDR_SPR_RO_TYPE;
#define MEMC_APHY_CSR_ADDR_SPR_RO_RO_MASK (0xffffffffUL)
#define MEMC_APHY_CSR_ADDR_SPR_RO_RO_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL2_TYPE;
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL2_NDIV_INT_2_MASK (0x3ff00000UL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL2_NDIV_INT_2_SHIFT (20UL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL2_NDIV_FRAC_2_MASK (0xfffffUL)
#define MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL2_NDIV_FRAC_2_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DPCC280_TYPE;
#define MEMC_APHY_CSR_DPCC280_PLL_CFG_CNTRL_28NM_0_MASK (0xffffffffUL)
#define MEMC_APHY_CSR_DPCC280_PLL_CFG_CNTRL_28NM_0_SHIFT (0UL)




typedef uint32_t MEMC_APHY_CSR_DPCC281_TYPE;
#define MEMC_APHY_CSR_DPCC281_PLL_CFG_CNTRL_28NM_1_MASK (0xffffffffUL)
#define MEMC_APHY_CSR_DPCC281_PLL_CFG_CNTRL_28NM_1_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MEMC_APHY_CSR_RDBType {
    MEMC_APHY_CSR_ADDR_REV_ID_TYPE addr_rev_id; /* OFFSET: 0x0 */
    MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RESET_TYPE global_addr_dll_reset; /* OFFSET: 0x4 */
    MEMC_APHY_CSR_GLOBAL_ADDR_DLL_RECALIBRATE_TYPE global_addr_dll_recalibrate; /* OFFSET: 0x8 */
    MEMC_APHY_CSR_GADC_TYPE global_addr_dll_cntrl; /* OFFSET: 0xc */
    MEMC_APHY_CSR_GADPLV_TYPE global_addr_dll_phase_load_value; /* OFFSET: 0x10 */
    MEMC_APHY_CSR_ADDR_MASTER_DLL_OUTPUT_TYPE addr_master_dll_output; /* OFFSET: 0x14 */
    MEMC_APHY_CSR_ADDR_SLAVE_DLL_OFFSET_TYPE addr_slave_dll_offset; /* OFFSET: 0x18 */
    MEMC_APHY_CSR_GAMDBE_TYPE global_addr_master_dll_bypass_enable; /* OFFSET: 0x1c */
    MEMC_APHY_CSR_GADLS_TYPE global_addr_dll_lock_status; /* OFFSET: 0x20 */
    MEMC_APHY_CSR_DDR_PLL_GLOBAL_RESET_TYPE ddr_pll_global_reset; /* OFFSET: 0x24 */
    MEMC_APHY_CSR_DDR_PLL_POST_DIVIDER_RESET_TYPE ddr_pll_post_divider_reset; /* OFFSET: 0x28 */
    MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL0_TYPE ddr_pll_vco_freq_cntrl0; /* OFFSET: 0x2c */
    MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL1_TYPE ddr_pll_vco_freq_cntrl1; /* OFFSET: 0x30 */
    MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_TYPE ddr_pll_mdiv_value; /* OFFSET: 0x34 */
    MEMC_APHY_CSR_DDR_PLL_CONFIG_CNTRL_TYPE ddr_pll_config_cntrl; /* OFFSET: 0x38 */
    MEMC_APHY_CSR_DDR_PLL_MISC_CNTRL_TYPE ddr_pll_misc_cntrl; /* OFFSET: 0x3c */
    MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL0_TYPE ddr_pll_spread_spect_cntrl0; /* OFFSET: 0x40 */
    MEMC_APHY_CSR_DDR_PLL_SPREAD_SPECT_CNTRL1_TYPE ddr_pll_spread_spect_cntrl1; /* OFFSET: 0x44 */
    MEMC_APHY_CSR_DDR_PLL_LOCK_STATUS_TYPE ddr_pll_lock_status; /* OFFSET: 0x48 */
    MEMC_APHY_CSR_DDR_PLL_HOLD_CH_TYPE ddr_pll_hold_ch; /* OFFSET: 0x4c */
    MEMC_APHY_CSR_DDR_PLL_ENABLE_CH_TYPE ddr_pll_enable_ch; /* OFFSET: 0x50 */
    MEMC_APHY_CSR_DDR_PLL_BYPASS_TYPE ddr_pll_bypass; /* OFFSET: 0x54 */
    MEMC_APHY_CSR_DDR_PLL_PWRDWN_TYPE ddr_pll_pwrdwn; /* OFFSET: 0x58 */
    MEMC_APHY_CSR_DDR_PLL_CH0_DESKEW_CNTRL_TYPE ddr_pll_ch0_deskew_cntrl; /* OFFSET: 0x5c */
    MEMC_APHY_CSR_DDR_PLL_CH1_DESKEW_CNTRL_TYPE ddr_pll_ch1_deskew_cntrl; /* OFFSET: 0x60 */
    MEMC_APHY_CSR_DDR_PLL_DESKEW_STATUS_TYPE ddr_pll_deskew_status; /* OFFSET: 0x64 */
    MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_CNTRL_TYPE addr_pad_drv_slew_cntrl; /* OFFSET: 0x68 */
    MEMC_APHY_CSR_ADDR_PAD_MISC_CNTRL_TYPE addr_pad_misc_cntrl; /* OFFSET: 0x6c */
    MEMC_APHY_CSR_ADDR_PVT_COMP_CNTRL_TYPE addr_pvt_comp_cntrl; /* OFFSET: 0x70 */
    MEMC_APHY_CSR_APCOC_TYPE addr_pvt_comp_override_cntrl; /* OFFSET: 0x74 */
    MEMC_APHY_CSR_ADDR_PVT_COMP_STATUS_TYPE addr_pvt_comp_status; /* OFFSET: 0x78 */
    MEMC_APHY_CSR_ADDR_PVT_COMP_DEBUG_TYPE addr_pvt_comp_debug; /* OFFSET: 0x7c */
    MEMC_APHY_CSR_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x80 */
    MEMC_APHY_CSR_DSDPC_TYPE disable_soft_ddr_pll_control; /* OFFSET: 0x84 */
    MEMC_APHY_CSR_PHY_BIST_CA_CRC_SPR_TYPE phy_bist_ca_crc_spr; /* OFFSET: 0x88 */
    MEMC_APHY_CSR_ADDR_SPR0_RW_TYPE addr_spr0_rw; /* OFFSET: 0x8c */
    MEMC_APHY_CSR_ADDR_SPR1_RW_TYPE addr_spr1_rw; /* OFFSET: 0x90 */
    MEMC_APHY_CSR_ADDR_SPR_RO_TYPE addr_spr_ro; /* OFFSET: 0x94 */
    MEMC_APHY_CSR_DDR_PLL_VCO_FREQ_CNTRL2_TYPE ddr_pll_vco_freq_cntrl2; /* OFFSET: 0x98 */
    MEMC_APHY_CSR_DPCC280_TYPE ddr_pll_config_cntrl_28nm_0; /* OFFSET: 0x9c */
    MEMC_APHY_CSR_RESERVED_TYPE rsvd1[96]; /* OFFSET: 0xa0 */
    MEMC_APHY_CSR_DPCC281_TYPE ddr_pll_config_cntrl_28nm_1; /* OFFSET: 0x100 */
} MEMC_APHY_CSR_RDBType;


#define MEMC_APHY_CSR_BASE              (0xE0203400UL)



#define MEMC_APHY_CSR_MAX_HW_ID         (1UL)


#define MEMC_APHY_CSR_ADDR_PVT_COMP_OVERRIDE_MODE_PMOS_CNTRL_CODE  (1UL)


#define MEMC_APHY_CSR_ADDR_PVT_COMP_OVERRIDE_MODE_NMOS_CNTRL_CODE  (2UL)


#define MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_STATUS_LOCKED  (MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_P_MASK \
                        | MEMC_APHY_CSR_GADLS_ADDR_MASTER_DLL_LOCK_N_MASK)


#define MEMC_APHY_CSR_DDR_PLL_MDIV_VALUE_MDIV5_VAL  (5UL)


#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_34_3_OHM  (4UL)


#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_48_OHM  (2UL)


#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_PER_200  (7UL)


#define MEMC_APHY_CSR_ADDR_PAD_DRV_SLEW_PER_25  (0UL)

#endif /* MEMC_APHY_CSR_RDB_H */
