/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_sec_rdb.h
    @brief RDB File for MEMC_SEC

    @version 2018May25_rdb
*/

#ifndef MEMC_SEC_RDB_H
#define MEMC_SEC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MEMC_SEC_GLB_CTL_TYPE;
#define MEMC_SEC_GLB_CTL_GID_CHECK_EN_LOCK_MASK (0x20UL)
#define MEMC_SEC_GLB_CTL_GID_CHECK_EN_LOCK_SHIFT (5UL)
#define MEMC_SEC_GLB_CTL_GID_CHECK_EN_MASK (0x10UL)
#define MEMC_SEC_GLB_CTL_GID_CHECK_EN_SHIFT (4UL)
#define MEMC_SEC_GLB_CTL_ADDR_SCR_EN_MASK (0x2UL)
#define MEMC_SEC_GLB_CTL_ADDR_SCR_EN_SHIFT (1UL)
#define MEMC_SEC_GLB_CTL_DATA_SCR_EN_MASK (0x1UL)
#define MEMC_SEC_GLB_CTL_DATA_SCR_EN_SHIFT (0UL)




typedef uint8_t MEMC_SEC_RESERVED_TYPE;




typedef uint32_t MEMC_SEC_RGN_0_CTL_TYPE;
#define MEMC_SEC_RGN_0_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_0_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_0_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_0_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_0_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_0_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_0_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_0_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_0_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_0_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_0_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_0_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_0_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_0_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_0_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_0_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_0_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_0_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_0_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_0_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_0_START_ADDR_TYPE;
#define MEMC_SEC_RGN_0_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_0_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_0_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_0_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_0_END_ADDR_TYPE;
#define MEMC_SEC_RGN_0_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_0_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_0_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_0_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_1_CTL_TYPE;
#define MEMC_SEC_RGN_1_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_1_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_1_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_1_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_1_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_1_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_1_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_1_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_1_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_1_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_1_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_1_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_1_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_1_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_1_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_1_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_1_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_1_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_1_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_1_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_1_START_ADDR_TYPE;
#define MEMC_SEC_RGN_1_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_1_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_1_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_1_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_1_END_ADDR_TYPE;
#define MEMC_SEC_RGN_1_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_1_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_1_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_1_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_2_CTL_TYPE;
#define MEMC_SEC_RGN_2_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_2_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_2_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_2_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_2_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_2_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_2_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_2_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_2_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_2_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_2_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_2_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_2_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_2_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_2_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_2_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_2_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_2_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_2_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_2_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_2_START_ADDR_TYPE;
#define MEMC_SEC_RGN_2_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_2_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_2_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_2_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_2_END_ADDR_TYPE;
#define MEMC_SEC_RGN_2_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_2_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_2_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_2_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_3_CTL_TYPE;
#define MEMC_SEC_RGN_3_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_3_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_3_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_3_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_3_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_3_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_3_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_3_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_3_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_3_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_3_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_3_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_3_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_3_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_3_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_3_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_3_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_3_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_3_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_3_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_3_START_ADDR_TYPE;
#define MEMC_SEC_RGN_3_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_3_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_3_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_3_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_3_END_ADDR_TYPE;
#define MEMC_SEC_RGN_3_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_3_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_3_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_3_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_4_CTL_TYPE;
#define MEMC_SEC_RGN_4_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_4_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_4_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_4_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_4_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_4_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_4_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_4_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_4_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_4_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_4_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_4_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_4_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_4_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_4_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_4_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_4_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_4_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_4_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_4_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_4_START_ADDR_TYPE;
#define MEMC_SEC_RGN_4_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_4_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_4_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_4_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_4_END_ADDR_TYPE;
#define MEMC_SEC_RGN_4_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_4_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_4_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_4_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_5_CTL_TYPE;
#define MEMC_SEC_RGN_5_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_5_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_5_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_5_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_5_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_5_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_5_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_5_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_5_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_5_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_5_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_5_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_5_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_5_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_5_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_5_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_5_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_5_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_5_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_5_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_5_START_ADDR_TYPE;
#define MEMC_SEC_RGN_5_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_5_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_5_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_5_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_5_END_ADDR_TYPE;
#define MEMC_SEC_RGN_5_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_5_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_5_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_5_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_6_CTL_TYPE;
#define MEMC_SEC_RGN_6_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_6_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_6_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_6_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_6_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_6_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_6_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_6_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_6_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_6_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_6_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_6_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_6_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_6_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_6_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_6_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_6_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_6_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_6_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_6_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_6_START_ADDR_TYPE;
#define MEMC_SEC_RGN_6_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_6_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_6_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_6_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_6_END_ADDR_TYPE;
#define MEMC_SEC_RGN_6_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_6_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_6_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_6_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_7_CTL_TYPE;
#define MEMC_SEC_RGN_7_CTL_GID_SANDBOX_EN_LOCK_MASK (0x1000000UL)
#define MEMC_SEC_RGN_7_CTL_GID_SANDBOX_EN_LOCK_SHIFT (24UL)
#define MEMC_SEC_RGN_7_CTL_GID_SANDBOX_EN_MASK (0xff0000UL)
#define MEMC_SEC_RGN_7_CTL_GID_SANDBOX_EN_SHIFT (16UL)
#define MEMC_SEC_RGN_7_CTL_BYPASS_SCR_LOCK_MASK (0x800UL)
#define MEMC_SEC_RGN_7_CTL_BYPASS_SCR_LOCK_SHIFT (11UL)
#define MEMC_SEC_RGN_7_CTL_BYPASS_SCR_MASK (0x400UL)
#define MEMC_SEC_RGN_7_CTL_BYPASS_SCR_SHIFT (10UL)
#define MEMC_SEC_RGN_7_CTL_DATA_SCR_EN_MASK (0x100UL)
#define MEMC_SEC_RGN_7_CTL_DATA_SCR_EN_SHIFT (8UL)
#define MEMC_SEC_RGN_7_CTL_END_ADDR_LOCK_MASK (0x20UL)
#define MEMC_SEC_RGN_7_CTL_END_ADDR_LOCK_SHIFT (5UL)
#define MEMC_SEC_RGN_7_CTL_START_ADDR_LOCK_MASK (0x10UL)
#define MEMC_SEC_RGN_7_CTL_START_ADDR_LOCK_SHIFT (4UL)
#define MEMC_SEC_RGN_7_CTL_MEM_TYPE_LOCK_MASK (0x8UL)
#define MEMC_SEC_RGN_7_CTL_MEM_TYPE_LOCK_SHIFT (3UL)
#define MEMC_SEC_RGN_7_CTL_MEM_TYPE_MASK (0x6UL)
#define MEMC_SEC_RGN_7_CTL_MEM_TYPE_SHIFT (1UL)
#define MEMC_SEC_RGN_7_CTL_EN_MASK (0x1UL)
#define MEMC_SEC_RGN_7_CTL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_7_START_ADDR_TYPE;
#define MEMC_SEC_RGN_7_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_7_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_7_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_7_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_RGN_7_END_ADDR_TYPE;
#define MEMC_SEC_RGN_7_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_RGN_7_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_RGN_7_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_RGN_7_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_ACC_VIO_ADDR_TYPE;
#define MEMC_SEC_ACC_VIO_ADDR_ADDR_MASK (0xffffffffUL)
#define MEMC_SEC_ACC_VIO_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t MEMC_SEC_ACC_VIO_INFO_TYPE;
#define MEMC_SEC_ACC_VIO_INFO_INTR_OVERRUN_MASK (0x80000000UL)
#define MEMC_SEC_ACC_VIO_INFO_INTR_OVERRUN_SHIFT (31UL)
#define MEMC_SEC_ACC_VIO_INFO_INTR_MASK (0x40000000UL)
#define MEMC_SEC_ACC_VIO_INFO_INTR_SHIFT (30UL)
#define MEMC_SEC_ACC_VIO_INFO_REASON_MASK (0x38000000UL)
#define MEMC_SEC_ACC_VIO_INFO_REASON_SHIFT (27UL)
#define MEMC_SEC_ACC_VIO_INFO_PORT_ID_MASK (0x3800000UL)
#define MEMC_SEC_ACC_VIO_INFO_PORT_ID_SHIFT (23UL)
#define MEMC_SEC_ACC_VIO_INFO_REGION_MASK (0x7fc000UL)
#define MEMC_SEC_ACC_VIO_INFO_REGION_SHIFT (14UL)
#define MEMC_SEC_ACC_VIO_INFO_CLIENT_ID_MASK (0x3ffeUL)
#define MEMC_SEC_ACC_VIO_INFO_CLIENT_ID_SHIFT (1UL)
#define MEMC_SEC_ACC_VIO_INFO_TYPE_MASK (0x1UL)
#define MEMC_SEC_ACC_VIO_INFO_TYPE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_0_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_0_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_0_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_0_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_0_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_1_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_1_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_1_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_1_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_1_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_2_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_2_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_2_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_2_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_2_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_3_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_3_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_3_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_3_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_3_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_4_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_4_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_4_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_4_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_4_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_5_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_5_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_5_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_5_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_5_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_6_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_6_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_6_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_6_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_6_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_VC_PROCESSOR_GID_TYPE;
#define MEMC_SEC_VC_PROCESSOR_GID_GID_MASK (0x7UL)
#define MEMC_SEC_VC_PROCESSOR_GID_GID_SHIFT (0UL)




typedef uint32_t MEMC_SEC_DRAM_CONFIG_TYPE;
#define MEMC_SEC_DRAM_CONFIG_MEMC_IF_WIDTH_MASK (0x10000UL)
#define MEMC_SEC_DRAM_CONFIG_MEMC_IF_WIDTH_SHIFT (16UL)
#define MEMC_SEC_DRAM_CONFIG_DEVICE_WIDTH_MASK (0x3000UL)
#define MEMC_SEC_DRAM_CONFIG_DEVICE_WIDTH_SHIFT (12UL)
#define MEMC_SEC_DRAM_CONFIG_DENSITY_CS1_MASK (0xf00UL)
#define MEMC_SEC_DRAM_CONFIG_DENSITY_CS1_SHIFT (8UL)
#define MEMC_SEC_DRAM_CONFIG_DENSITY_CS0_MASK (0xf0UL)
#define MEMC_SEC_DRAM_CONFIG_DENSITY_CS0_SHIFT (4UL)
#define MEMC_SEC_DRAM_CONFIG_TYPE_MASK (0x3UL)
#define MEMC_SEC_DRAM_CONFIG_TYPE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_DRAM_START_ADDR_TYPE;
#define MEMC_SEC_DRAM_START_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_DRAM_START_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_DRAM_START_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_DRAM_START_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_DRAM_END_ADDR_TYPE;
#define MEMC_SEC_DRAM_END_ADDR_ADDR_MASK (0xfffff000UL)
#define MEMC_SEC_DRAM_END_ADDR_ADDR_SHIFT (12UL)
#define MEMC_SEC_DRAM_END_ADDR_LSB_BITS_MASK (0xfffUL)
#define MEMC_SEC_DRAM_END_ADDR_LSB_BITS_SHIFT (0UL)




typedef uint32_t MEMC_SEC_ANTI_CLONING_CTRL_TYPE;
#define MEMC_SEC_ANTI_CLONING_CTRL_DRAM_ADDR_LOCK_MASK (0x1UL)
#define MEMC_SEC_ANTI_CLONING_CTRL_DRAM_ADDR_LOCK_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_7_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_7_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_7_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_7_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_7_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_0_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_0_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_0_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_0_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_0_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_1_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_1_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_1_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_1_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_1_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_2_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_2_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_2_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_2_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_2_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_3_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_3_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_3_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_3_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_3_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_4_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_4_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_4_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_4_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_4_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_5_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_5_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_5_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_5_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_5_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_6_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_6_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_6_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_6_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_6_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_PORT_8_GID_7_CMP_TYPE;
#define MEMC_SEC_PORT_8_GID_7_CMP_BITS_MASK (0x1fff0000UL)
#define MEMC_SEC_PORT_8_GID_7_CMP_BITS_SHIFT (16UL)
#define MEMC_SEC_PORT_8_GID_7_CMP_VALUE_MASK (0x1fffUL)
#define MEMC_SEC_PORT_8_GID_7_CMP_VALUE_SHIFT (0UL)




typedef uint32_t MEMC_SEC_MEMC_DEBUG_CTRL_TYPE;
#define MEMC_SEC_MEMC_DEBUG_CTRL_TZCFG_DBG_EN_MASK (0x1UL)
#define MEMC_SEC_MEMC_DEBUG_CTRL_TZCFG_DBG_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEC_ACC_VIO_ADDR_1_TYPE;
#define MEMC_SEC_ACC_VIO_ADDR_1_1_MASK (0xffffffffUL)
#define MEMC_SEC_ACC_VIO_ADDR_1_1_SHIFT (0UL)




typedef uint32_t MEMC_SEC_ACC_VIO_INFO_1_TYPE;
#define MEMC_SEC_ACC_VIO_INFO_1_INTR_OVERRUN_1_MASK (0x80000000UL)
#define MEMC_SEC_ACC_VIO_INFO_1_INTR_OVERRUN_1_SHIFT (31UL)
#define MEMC_SEC_ACC_VIO_INFO_1_INTR_1_MASK (0x40000000UL)
#define MEMC_SEC_ACC_VIO_INFO_1_INTR_1_SHIFT (30UL)
#define MEMC_SEC_ACC_VIO_INFO_1_REASON_1_MASK (0x38000000UL)
#define MEMC_SEC_ACC_VIO_INFO_1_REASON_1_SHIFT (27UL)
#define MEMC_SEC_ACC_VIO_INFO_1_PORT_ID_1_MASK (0x3800000UL)
#define MEMC_SEC_ACC_VIO_INFO_1_PORT_ID_1_SHIFT (23UL)
#define MEMC_SEC_ACC_VIO_INFO_1_REGION_1_MASK (0x7fc000UL)
#define MEMC_SEC_ACC_VIO_INFO_1_REGION_1_SHIFT (14UL)
#define MEMC_SEC_ACC_VIO_INFO_1_CLIENT_ID_1_MASK (0x3ffeUL)
#define MEMC_SEC_ACC_VIO_INFO_1_CLIENT_ID_1_SHIFT (1UL)
#define MEMC_SEC_ACC_VIO_INFO_1_TYPE_1_MASK (0x1UL)
#define MEMC_SEC_ACC_VIO_INFO_1_TYPE_1_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MEMC_SEC_RDBType {
    MEMC_SEC_GLB_CTL_TYPE glb_ctl; /* OFFSET: 0x0 */
    MEMC_SEC_RESERVED_TYPE rsvd0[12]; /* OFFSET: 0x4 */
    MEMC_SEC_RGN_0_CTL_TYPE rgn_0_ctl; /* OFFSET: 0x10 */
    MEMC_SEC_RGN_0_START_ADDR_TYPE rgn_0_start_addr; /* OFFSET: 0x14 */
    MEMC_SEC_RGN_0_END_ADDR_TYPE rgn_0_end_addr; /* OFFSET: 0x18 */
    MEMC_SEC_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x1c */
    MEMC_SEC_RGN_1_CTL_TYPE rgn_1_ctl; /* OFFSET: 0x20 */
    MEMC_SEC_RGN_1_START_ADDR_TYPE rgn_1_start_addr; /* OFFSET: 0x24 */
    MEMC_SEC_RGN_1_END_ADDR_TYPE rgn_1_end_addr; /* OFFSET: 0x28 */
    MEMC_SEC_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x2c */
    MEMC_SEC_RGN_2_CTL_TYPE rgn_2_ctl; /* OFFSET: 0x30 */
    MEMC_SEC_RGN_2_START_ADDR_TYPE rgn_2_start_addr; /* OFFSET: 0x34 */
    MEMC_SEC_RGN_2_END_ADDR_TYPE rgn_2_end_addr; /* OFFSET: 0x38 */
    MEMC_SEC_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x3c */
    MEMC_SEC_RGN_3_CTL_TYPE rgn_3_ctl; /* OFFSET: 0x40 */
    MEMC_SEC_RGN_3_START_ADDR_TYPE rgn_3_start_addr; /* OFFSET: 0x44 */
    MEMC_SEC_RGN_3_END_ADDR_TYPE rgn_3_end_addr; /* OFFSET: 0x48 */
    MEMC_SEC_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x4c */
    MEMC_SEC_RGN_4_CTL_TYPE rgn_4_ctl; /* OFFSET: 0x50 */
    MEMC_SEC_RGN_4_START_ADDR_TYPE rgn_4_start_addr; /* OFFSET: 0x54 */
    MEMC_SEC_RGN_4_END_ADDR_TYPE rgn_4_end_addr; /* OFFSET: 0x58 */
    MEMC_SEC_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0x5c */
    MEMC_SEC_RGN_5_CTL_TYPE rgn_5_ctl; /* OFFSET: 0x60 */
    MEMC_SEC_RGN_5_START_ADDR_TYPE rgn_5_start_addr; /* OFFSET: 0x64 */
    MEMC_SEC_RGN_5_END_ADDR_TYPE rgn_5_end_addr; /* OFFSET: 0x68 */
    MEMC_SEC_RESERVED_TYPE rsvd6[4]; /* OFFSET: 0x6c */
    MEMC_SEC_RGN_6_CTL_TYPE rgn_6_ctl; /* OFFSET: 0x70 */
    MEMC_SEC_RGN_6_START_ADDR_TYPE rgn_6_start_addr; /* OFFSET: 0x74 */
    MEMC_SEC_RGN_6_END_ADDR_TYPE rgn_6_end_addr; /* OFFSET: 0x78 */
    MEMC_SEC_RESERVED_TYPE rsvd7[4]; /* OFFSET: 0x7c */
    MEMC_SEC_RGN_7_CTL_TYPE rgn_7_ctl; /* OFFSET: 0x80 */
    MEMC_SEC_RGN_7_START_ADDR_TYPE rgn_7_start_addr; /* OFFSET: 0x84 */
    MEMC_SEC_RGN_7_END_ADDR_TYPE rgn_7_end_addr; /* OFFSET: 0x88 */
    MEMC_SEC_RESERVED_TYPE rsvd8[4]; /* OFFSET: 0x8c */
    MEMC_SEC_ACC_VIO_ADDR_TYPE acc_vio_addr; /* OFFSET: 0x90 */
    MEMC_SEC_ACC_VIO_INFO_TYPE acc_vio_info; /* OFFSET: 0x94 */
    MEMC_SEC_RESERVED_TYPE rsvd9[104]; /* OFFSET: 0x98 */
    MEMC_SEC_PORT_0_GID_0_CMP_TYPE port_0_gid_0_cmp; /* OFFSET: 0x100 */
    MEMC_SEC_PORT_0_GID_1_CMP_TYPE port_0_gid_1_cmp; /* OFFSET: 0x104 */
    MEMC_SEC_PORT_0_GID_2_CMP_TYPE port_0_gid_2_cmp; /* OFFSET: 0x108 */
    MEMC_SEC_PORT_0_GID_3_CMP_TYPE port_0_gid_3_cmp; /* OFFSET: 0x10c */
    MEMC_SEC_PORT_0_GID_4_CMP_TYPE port_0_gid_4_cmp; /* OFFSET: 0x110 */
    MEMC_SEC_PORT_0_GID_5_CMP_TYPE port_0_gid_5_cmp; /* OFFSET: 0x114 */
    MEMC_SEC_PORT_0_GID_6_CMP_TYPE port_0_gid_6_cmp; /* OFFSET: 0x118 */
    MEMC_SEC_PORT_0_GID_7_CMP_TYPE port_0_gid_7_cmp; /* OFFSET: 0x11c */
    MEMC_SEC_PORT_1_GID_0_CMP_TYPE port_1_gid_0_cmp; /* OFFSET: 0x120 */
    MEMC_SEC_PORT_1_GID_1_CMP_TYPE port_1_gid_1_cmp; /* OFFSET: 0x124 */
    MEMC_SEC_PORT_1_GID_2_CMP_TYPE port_1_gid_2_cmp; /* OFFSET: 0x128 */
    MEMC_SEC_PORT_1_GID_3_CMP_TYPE port_1_gid_3_cmp; /* OFFSET: 0x12c */
    MEMC_SEC_PORT_1_GID_4_CMP_TYPE port_1_gid_4_cmp; /* OFFSET: 0x130 */
    MEMC_SEC_PORT_1_GID_5_CMP_TYPE port_1_gid_5_cmp; /* OFFSET: 0x134 */
    MEMC_SEC_PORT_1_GID_6_CMP_TYPE port_1_gid_6_cmp; /* OFFSET: 0x138 */
    MEMC_SEC_PORT_1_GID_7_CMP_TYPE port_1_gid_7_cmp; /* OFFSET: 0x13c */
    MEMC_SEC_PORT_2_GID_0_CMP_TYPE port_2_gid_0_cmp; /* OFFSET: 0x140 */
    MEMC_SEC_PORT_2_GID_1_CMP_TYPE port_2_gid_1_cmp; /* OFFSET: 0x144 */
    MEMC_SEC_PORT_2_GID_2_CMP_TYPE port_2_gid_2_cmp; /* OFFSET: 0x148 */
    MEMC_SEC_PORT_2_GID_3_CMP_TYPE port_2_gid_3_cmp; /* OFFSET: 0x14c */
    MEMC_SEC_PORT_2_GID_4_CMP_TYPE port_2_gid_4_cmp; /* OFFSET: 0x150 */
    MEMC_SEC_PORT_2_GID_5_CMP_TYPE port_2_gid_5_cmp; /* OFFSET: 0x154 */
    MEMC_SEC_PORT_2_GID_6_CMP_TYPE port_2_gid_6_cmp; /* OFFSET: 0x158 */
    MEMC_SEC_PORT_2_GID_7_CMP_TYPE port_2_gid_7_cmp; /* OFFSET: 0x15c */
    MEMC_SEC_PORT_3_GID_0_CMP_TYPE port_3_gid_0_cmp; /* OFFSET: 0x160 */
    MEMC_SEC_PORT_3_GID_1_CMP_TYPE port_3_gid_1_cmp; /* OFFSET: 0x164 */
    MEMC_SEC_PORT_3_GID_2_CMP_TYPE port_3_gid_2_cmp; /* OFFSET: 0x168 */
    MEMC_SEC_PORT_3_GID_3_CMP_TYPE port_3_gid_3_cmp; /* OFFSET: 0x16c */
    MEMC_SEC_PORT_3_GID_4_CMP_TYPE port_3_gid_4_cmp; /* OFFSET: 0x170 */
    MEMC_SEC_PORT_3_GID_5_CMP_TYPE port_3_gid_5_cmp; /* OFFSET: 0x174 */
    MEMC_SEC_PORT_3_GID_6_CMP_TYPE port_3_gid_6_cmp; /* OFFSET: 0x178 */
    MEMC_SEC_PORT_3_GID_7_CMP_TYPE port_3_gid_7_cmp; /* OFFSET: 0x17c */
    MEMC_SEC_PORT_4_GID_0_CMP_TYPE port_4_gid_0_cmp; /* OFFSET: 0x180 */
    MEMC_SEC_PORT_4_GID_1_CMP_TYPE port_4_gid_1_cmp; /* OFFSET: 0x184 */
    MEMC_SEC_PORT_4_GID_2_CMP_TYPE port_4_gid_2_cmp; /* OFFSET: 0x188 */
    MEMC_SEC_PORT_4_GID_3_CMP_TYPE port_4_gid_3_cmp; /* OFFSET: 0x18c */
    MEMC_SEC_PORT_4_GID_4_CMP_TYPE port_4_gid_4_cmp; /* OFFSET: 0x190 */
    MEMC_SEC_PORT_4_GID_5_CMP_TYPE port_4_gid_5_cmp; /* OFFSET: 0x194 */
    MEMC_SEC_PORT_4_GID_6_CMP_TYPE port_4_gid_6_cmp; /* OFFSET: 0x198 */
    MEMC_SEC_PORT_4_GID_7_CMP_TYPE port_4_gid_7_cmp; /* OFFSET: 0x19c */
    MEMC_SEC_RESERVED_TYPE rsvd10[96]; /* OFFSET: 0x1a0 */
    MEMC_SEC_PORT_5_GID_0_CMP_TYPE port_5_gid_0_cmp; /* OFFSET: 0x200 */
    MEMC_SEC_PORT_5_GID_1_CMP_TYPE port_5_gid_1_cmp; /* OFFSET: 0x204 */
    MEMC_SEC_PORT_5_GID_2_CMP_TYPE port_5_gid_2_cmp; /* OFFSET: 0x208 */
    MEMC_SEC_PORT_5_GID_3_CMP_TYPE port_5_gid_3_cmp; /* OFFSET: 0x20c */
    MEMC_SEC_PORT_5_GID_4_CMP_TYPE port_5_gid_4_cmp; /* OFFSET: 0x210 */
    MEMC_SEC_PORT_5_GID_5_CMP_TYPE port_5_gid_5_cmp; /* OFFSET: 0x214 */
    MEMC_SEC_PORT_5_GID_6_CMP_TYPE port_5_gid_6_cmp; /* OFFSET: 0x218 */
    MEMC_SEC_PORT_5_GID_7_CMP_TYPE port_5_gid_7_cmp; /* OFFSET: 0x21c */
    MEMC_SEC_PORT_6_GID_0_CMP_TYPE port_6_gid_0_cmp; /* OFFSET: 0x220 */
    MEMC_SEC_PORT_6_GID_1_CMP_TYPE port_6_gid_1_cmp; /* OFFSET: 0x224 */
    MEMC_SEC_PORT_6_GID_2_CMP_TYPE port_6_gid_2_cmp; /* OFFSET: 0x228 */
    MEMC_SEC_PORT_6_GID_3_CMP_TYPE port_6_gid_3_cmp; /* OFFSET: 0x22c */
    MEMC_SEC_PORT_6_GID_4_CMP_TYPE port_6_gid_4_cmp; /* OFFSET: 0x230 */
    MEMC_SEC_PORT_6_GID_5_CMP_TYPE port_6_gid_5_cmp; /* OFFSET: 0x234 */
    MEMC_SEC_PORT_6_GID_6_CMP_TYPE port_6_gid_6_cmp; /* OFFSET: 0x238 */
    MEMC_SEC_PORT_6_GID_7_CMP_TYPE port_6_gid_7_cmp; /* OFFSET: 0x23c */
    MEMC_SEC_VC_PROCESSOR_GID_TYPE vc_processor_gid; /* OFFSET: 0x240 */
    MEMC_SEC_DRAM_CONFIG_TYPE dram_config; /* OFFSET: 0x244 */
    MEMC_SEC_DRAM_START_ADDR_TYPE dram_start_addr; /* OFFSET: 0x248 */
    MEMC_SEC_DRAM_END_ADDR_TYPE dram_end_addr; /* OFFSET: 0x24c */
    MEMC_SEC_ANTI_CLONING_CTRL_TYPE anti_cloning_ctrl; /* OFFSET: 0x250 */
    MEMC_SEC_RESERVED_TYPE rsvd11[12]; /* OFFSET: 0x254 */
    MEMC_SEC_PORT_7_GID_0_CMP_TYPE port_7_gid_0_cmp; /* OFFSET: 0x260 */
    MEMC_SEC_PORT_7_GID_1_CMP_TYPE port_7_gid_1_cmp; /* OFFSET: 0x264 */
    MEMC_SEC_PORT_7_GID_2_CMP_TYPE port_7_gid_2_cmp; /* OFFSET: 0x268 */
    MEMC_SEC_PORT_7_GID_3_CMP_TYPE port_7_gid_3_cmp; /* OFFSET: 0x26c */
    MEMC_SEC_PORT_7_GID_4_CMP_TYPE port_7_gid_4_cmp; /* OFFSET: 0x270 */
    MEMC_SEC_PORT_7_GID_5_CMP_TYPE port_7_gid_5_cmp; /* OFFSET: 0x274 */
    MEMC_SEC_PORT_7_GID_6_CMP_TYPE port_7_gid_6_cmp; /* OFFSET: 0x278 */
    MEMC_SEC_PORT_7_GID_7_CMP_TYPE port_7_gid_7_cmp; /* OFFSET: 0x27c */
    MEMC_SEC_PORT_8_GID_0_CMP_TYPE port_8_gid_0_cmp; /* OFFSET: 0x280 */
    MEMC_SEC_PORT_8_GID_1_CMP_TYPE port_8_gid_1_cmp; /* OFFSET: 0x284 */
    MEMC_SEC_PORT_8_GID_2_CMP_TYPE port_8_gid_2_cmp; /* OFFSET: 0x288 */
    MEMC_SEC_PORT_8_GID_3_CMP_TYPE port_8_gid_3_cmp; /* OFFSET: 0x28c */
    MEMC_SEC_PORT_8_GID_4_CMP_TYPE port_8_gid_4_cmp; /* OFFSET: 0x290 */
    MEMC_SEC_PORT_8_GID_5_CMP_TYPE port_8_gid_5_cmp; /* OFFSET: 0x294 */
    MEMC_SEC_PORT_8_GID_6_CMP_TYPE port_8_gid_6_cmp; /* OFFSET: 0x298 */
    MEMC_SEC_PORT_8_GID_7_CMP_TYPE port_8_gid_7_cmp; /* OFFSET: 0x29c */
    MEMC_SEC_RESERVED_TYPE rsvd12[96]; /* OFFSET: 0x2a0 */
    MEMC_SEC_MEMC_DEBUG_CTRL_TYPE memc_debug_ctrl; /* OFFSET: 0x300 */
    MEMC_SEC_ACC_VIO_ADDR_1_TYPE acc_vio_addr_1; /* OFFSET: 0x304 */
    MEMC_SEC_ACC_VIO_INFO_1_TYPE acc_vio_info_1; /* OFFSET: 0x308 */
} MEMC_SEC_RDBType;


#define MEMC_SEC_BASE                   (0xE0204000UL)



#define MEMC_SEC_MAX_HW_ID              (1UL)


#define MEMC_SEC_DRAM_CONFIG_MEMC_IF_WIDTH_32  (0UL)


#define MEMC_SEC_DRAM_CONFIG_DEVICE_WIDTH_CS0_CS1_32_NOT_DDR3  (0UL)


#define MEMC_SEC_DRAM_CONFIG_DENSITY_256MBIT  (2UL)


#define MEMC_SEC_DRAM_CONFIG_DENSITY_512MBIT  (3UL)


#define MEMC_SEC_DRAM_CONFIG_TYPE_LPDDR2  (0UL)

#endif /* MEMC_SEC_RDB_H */
