/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_misc_rdb.h
    @brief RDB File for MEMC_MISC

    @version 2018May25_rdb
*/

#ifndef MEMC_MISC_RDB_H
#define MEMC_MISC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MEMC_MISC_DRAM_INIT_CONTROL_TYPE;
#define MEMC_MISC_DRAM_INIT_CONTROL_MRW_DATA_DDR3_EXTN_MASK (0xff000000UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_MRW_DATA_DDR3_EXTN_SHIFT (24UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_CS_BITS_MASK (0x300000UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_CS_BITS_SHIFT (20UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_INIT_CMD_MASK (0xf0000UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_INIT_CMD_SHIFT (16UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_MRW_DATA_MASK (0xff00UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_MRW_DATA_SHIFT (8UL)
#define MEMC_MISC_DRAM_INIT_CONTROL_MR_ADDR_MASK (0xffUL)
#define MEMC_MISC_DRAM_INIT_CONTROL_MR_ADDR_SHIFT (0UL)




typedef uint32_t MEMC_MISC_DRAM_INIT_RESULT_TYPE;
#define MEMC_MISC_DRAM_INIT_RESULT_MRR_DATA_DEV_1_MASK (0xff0000UL)
#define MEMC_MISC_DRAM_INIT_RESULT_MRR_DATA_DEV_1_SHIFT (16UL)
#define MEMC_MISC_DRAM_INIT_RESULT_MRR_DATA_DEV_0_MASK (0xff00UL)
#define MEMC_MISC_DRAM_INIT_RESULT_MRR_DATA_DEV_0_SHIFT (8UL)
#define MEMC_MISC_DRAM_INIT_RESULT_MRR_VALID_MASK (0x2UL)
#define MEMC_MISC_DRAM_INIT_RESULT_MRR_VALID_SHIFT (1UL)
#define MEMC_MISC_DRAM_INIT_RESULT_BUSY_MASK (0x1UL)
#define MEMC_MISC_DRAM_INIT_RESULT_BUSY_SHIFT (0UL)




typedef uint8_t MEMC_MISC_RESERVED_TYPE;




typedef uint32_t MEMC_MISC_DRAM_DEV_TEMP_ADDR_TYPE;
#define MEMC_MISC_DRAM_DEV_TEMP_ADDR_MRADDR_MASK (0xffUL)
#define MEMC_MISC_DRAM_DEV_TEMP_ADDR_MRADDR_SHIFT (0UL)




typedef uint32_t MEMC_MISC_DRAM_DEV_TEMP_STATUS_TYPE;
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_UP_DEV_1_MASK (0x800UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_UP_DEV_1_SHIFT (11UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_STATUS_1_MASK (0x700UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_STATUS_1_SHIFT (8UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_UP_DEV_0_MASK (0x80UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_UP_DEV_0_SHIFT (7UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_STATUS_0_MASK (0x70UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_STATUS_0_SHIFT (4UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_CS_SELECTED_MASK (0x2UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_CS_SELECTED_SHIFT (1UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_INTR_MASK (0x1UL)
#define MEMC_MISC_DRAM_DEV_TEMP_STATUS_DEV_TEMP_INTR_SHIFT (0UL)




typedef uint32_t MEMC_MISC_REFRESH_CNTRL_TYPE;
#define MEMC_MISC_REFRESH_CNTRL_ENABLE_MASK (0x20000UL)
#define MEMC_MISC_REFRESH_CNTRL_ENABLE_SHIFT (17UL)
#define MEMC_MISC_REFRESH_CNTRL_ALL_BANK_ENABLE_MASK (0x10000UL)
#define MEMC_MISC_REFRESH_CNTRL_ALL_BANK_ENABLE_SHIFT (16UL)
#define MEMC_MISC_REFRESH_CNTRL_PERIOD_MASK (0x1fffUL)
#define MEMC_MISC_REFRESH_CNTRL_PERIOD_SHIFT (0UL)




typedef uint32_t MEMC_MISC_AXI_CONFIG_TYPE;
#define MEMC_MISC_AXI_CONFIG_AXI_BMASK_SCHEDULE_CLR_EN_MASK (0x8UL)
#define MEMC_MISC_AXI_CONFIG_AXI_BMASK_SCHEDULE_CLR_EN_SHIFT (3UL)
#define MEMC_MISC_AXI_CONFIG_JIT_HCC_DIR_CHANGE_EN_MASK (0x4UL)
#define MEMC_MISC_AXI_CONFIG_JIT_HCC_DIR_CHANGE_EN_SHIFT (2UL)
#define MEMC_MISC_AXI_CONFIG_INTER_DATA_COHERENCY_MASK (0x2UL)
#define MEMC_MISC_AXI_CONFIG_INTER_DATA_COHERENCY_SHIFT (1UL)
#define MEMC_MISC_AXI_CONFIG_WR_POSTING_MASK (0x1UL)
#define MEMC_MISC_AXI_CONFIG_WR_POSTING_SHIFT (0UL)




typedef uint32_t MEMC_MISC_SCHEDULE_OVERHEAD_TYPE;
#define MEMC_MISC_SCHEDULE_OVERHEAD_RD2WR_OVERHEAD_MASK (0xff0000UL)
#define MEMC_MISC_SCHEDULE_OVERHEAD_RD2WR_OVERHEAD_SHIFT (16UL)
#define MEMC_MISC_SCHEDULE_OVERHEAD_WR2RD_OVERHEAD_MASK (0xff00UL)
#define MEMC_MISC_SCHEDULE_OVERHEAD_WR2RD_OVERHEAD_SHIFT (8UL)
#define MEMC_MISC_SCHEDULE_OVERHEAD_MISS_OVERHEAD_MASK (0x3fUL)
#define MEMC_MISC_SCHEDULE_OVERHEAD_MISS_OVERHEAD_SHIFT (0UL)




typedef uint32_t MEMC_MISC_PAT_TYPE;
#define MEMC_MISC_PAT_HCC_PENDING_COUNT_THRESHOLD_MASK (0xf000UL)
#define MEMC_MISC_PAT_HCC_PENDING_COUNT_THRESHOLD_SHIFT (12UL)
#define MEMC_MISC_PAT_MCC2HCC_SN_DIFFERENCE_MASK (0x3ffUL)
#define MEMC_MISC_PAT_MCC2HCC_SN_DIFFERENCE_SHIFT (0UL)




typedef uint32_t MEMC_MISC_TEST_MUX_SELECT_TYPE;
#define MEMC_MISC_TEST_MUX_SELECT_SELECT_MASK (0xfffUL)
#define MEMC_MISC_TEST_MUX_SELECT_SELECT_SHIFT (0UL)




typedef uint32_t MEMC_MISC_TEST_MUX_OUT_TYPE;
#define MEMC_MISC_TEST_MUX_OUT_OUT_MASK (0xffffffffUL)
#define MEMC_MISC_TEST_MUX_OUT_OUT_SHIFT (0UL)




typedef uint32_t MEMC_MISC_APB_CLK_IDLE_CNTRL_TYPE;
#define MEMC_MISC_APB_CLK_IDLE_CNTRL_OFF_EN_MASK (0x1UL)
#define MEMC_MISC_APB_CLK_IDLE_CNTRL_OFF_EN_SHIFT (0UL)




typedef uint32_t MEMC_MISC_BMBFH_TYPE;
#define MEMC_MISC_BMBFH_DISABLE_MCC_ON_REF_URGENT_MASK (0x4UL)
#define MEMC_MISC_BMBFH_DISABLE_MCC_ON_REF_URGENT_SHIFT (2UL)
#define MEMC_MISC_BMBFH_DISABLE_HCC_ON_REF_URGENT_MASK (0x2UL)
#define MEMC_MISC_BMBFH_DISABLE_HCC_ON_REF_URGENT_SHIFT (1UL)
#define MEMC_MISC_BMBFH_BLOCK_BANK_MASK (0x1UL)
#define MEMC_MISC_BMBFH_BLOCK_BANK_SHIFT (0UL)




typedef uint32_t MEMC_MISC_MSNR_TYPE;
#define MEMC_MISC_MSNR_MCC_SCHEDULE_NUM_REPLACE_MASK (0x3ffUL)
#define MEMC_MISC_MSNR_MCC_SCHEDULE_NUM_REPLACE_SHIFT (0UL)




typedef uint32_t MEMC_MISC_REFRESH_CNTRL2_TYPE;
#define MEMC_MISC_REFRESH_CNTRL2_EN_TREFBW_CHECKS_MASK (0x1000000UL)
#define MEMC_MISC_REFRESH_CNTRL2_EN_TREFBW_CHECKS_SHIFT (24UL)
#define MEMC_MISC_REFRESH_CNTRL2_NREF_IN_TREFBW_MASK (0xf0000UL)
#define MEMC_MISC_REFRESH_CNTRL2_NREF_IN_TREFBW_SHIFT (16UL)
#define MEMC_MISC_REFRESH_CNTRL2_TREFBW_PERIOD_MASK (0x7fffUL)
#define MEMC_MISC_REFRESH_CNTRL2_TREFBW_PERIOD_SHIFT (0UL)




typedef uint32_t MEMC_MISC_DYNAMIC_RELOAD_TYPE;
#define MEMC_MISC_DYNAMIC_RELOAD_DUMMY_BIT_MASK (0x1UL)
#define MEMC_MISC_DYNAMIC_RELOAD_DUMMY_BIT_SHIFT (0UL)




typedef uint32_t MEMC_MISC_REFRESH_THRESHOLD_TYPE;
#define MEMC_MISC_REFRESH_THRESHOLD_THRESHOLD_MASK (0x3fffUL)
#define MEMC_MISC_REFRESH_THRESHOLD_THRESHOLD_SHIFT (0UL)




typedef uint32_t MEMC_MISC_MRR_BYTE_REMAP_TYPE;
#define MEMC_MISC_MRR_BYTE_REMAP_LANE_2_MASK (0x30UL)
#define MEMC_MISC_MRR_BYTE_REMAP_LANE_2_SHIFT (4UL)
#define MEMC_MISC_MRR_BYTE_REMAP_LANE_0_MASK (0x3UL)
#define MEMC_MISC_MRR_BYTE_REMAP_LANE_0_SHIFT (0UL)




typedef uint32_t MEMC_MISC_SPR_TYPE;
#define MEMC_MISC_SPR_SPR_MASK (0xffffffffUL)
#define MEMC_MISC_SPR_SPR_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MEMC_MISC_RDBType {
    MEMC_MISC_DRAM_INIT_CONTROL_TYPE dram_init_control; /* OFFSET: 0x0 */
    MEMC_MISC_DRAM_INIT_RESULT_TYPE dram_init_result; /* OFFSET: 0x4 */
    MEMC_MISC_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x8 */
    MEMC_MISC_DRAM_DEV_TEMP_ADDR_TYPE dram_dev_temp_addr; /* OFFSET: 0xc */
    MEMC_MISC_DRAM_DEV_TEMP_STATUS_TYPE dram_dev_temp_status; /* OFFSET: 0x10 */
    MEMC_MISC_REFRESH_CNTRL_TYPE refresh_cntrl; /* OFFSET: 0x14 */
    MEMC_MISC_AXI_CONFIG_TYPE axi_config; /* OFFSET: 0x18 */
    MEMC_MISC_SCHEDULE_OVERHEAD_TYPE schedule_overhead; /* OFFSET: 0x1c */
    MEMC_MISC_PAT_TYPE port_arbiter_threshold; /* OFFSET: 0x20 */
    MEMC_MISC_TEST_MUX_SELECT_TYPE test_mux_select; /* OFFSET: 0x24 */
    MEMC_MISC_TEST_MUX_OUT_TYPE test_mux_out; /* OFFSET: 0x28 */
    MEMC_MISC_APB_CLK_IDLE_CNTRL_TYPE apb_clk_idle_cntrl; /* OFFSET: 0x2c */
    MEMC_MISC_BMBFH_TYPE block_mcc_bank_for_hcc; /* OFFSET: 0x30 */
    MEMC_MISC_MSNR_TYPE mcc_schedule_num_replace; /* OFFSET: 0x34 */
    MEMC_MISC_REFRESH_CNTRL2_TYPE refresh_cntrl2; /* OFFSET: 0x38 */
    MEMC_MISC_DYNAMIC_RELOAD_TYPE dynamic_reload; /* OFFSET: 0x3c */
    MEMC_MISC_REFRESH_THRESHOLD_TYPE refresh_threshold; /* OFFSET: 0x40 */
    MEMC_MISC_MRR_BYTE_REMAP_TYPE mrr_byte_remap; /* OFFSET: 0x44 */
    MEMC_MISC_RESERVED_TYPE rsvd1[48]; /* OFFSET: 0x48 */
    MEMC_MISC_SPR_TYPE spr_ro; /* OFFSET: 0x78 */
    MEMC_MISC_SPR_TYPE spr_rw; /* OFFSET: 0x7c */
} MEMC_MISC_RDBType;


#define MEMC_MISC_BASE                  (0xE020A000UL)



#define MEMC_MISC_MAX_HW_ID             (1UL)


#define MEMC_MISC_DRAM_INIT_CONTROL_CS_BITS_CS0  (2UL)


#define MEMC_MISC_DRAM_INIT_CONTROL_INIT_CMD_MRW  (0UL)


#define MEMC_MISC_DRAM_INIT_CONTROL_MR_ADDR_ZQ_CALIBRATION  (0x0AUL)

#endif /* MEMC_MISC_RDB_H */
