/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_chip_misc_rdb.h
    @brief RDB File for MEMC_CHIP_MISC

    @version 2018May25_rdb
*/

#ifndef MEMC_CHIP_MISC_RDB_H
#define MEMC_CHIP_MISC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MEMC_CHIP_MISC_RESERVED_TYPE;




typedef uint16_t MEMC_CHIP_MISC_DDRLDO_CFG_TYPE;
#define MEMC_CHIP_MISC_DDRLDO_CFG_VREG1P8_PMU_STABLE_MASK (0x40U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_VREG1P8_PMU_STABLE_SHIFT (6U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_VREG1P2_PMU_STABLE_MASK (0x20U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_VREG1P2_PMU_STABLE_SHIFT (5U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_VREG1P0_PMU_STABLE_MASK (0x10U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_VREG1P0_PMU_STABLE_SHIFT (4U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_EN_PULL_DWN_MASK (0x8U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_EN_PULL_DWN_SHIFT (3U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_BYP_REF_FIL_MASK (0x4U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_BYP_REF_FIL_SHIFT (2U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_LDO_CNTL_EN_MASK (0x2U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_LDO_CNTL_EN_SHIFT (1U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_ENB_VDDC_TRACK_MASK (0x1U)
#define MEMC_CHIP_MISC_DDRLDO_CFG_ENB_VDDC_TRACK_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_MSB_TYPE;
#define MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_MSB_CNTRL_MSB_MASK (0xffffU)
#define MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_MSB_CNTRL_MSB_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_LSB_TYPE;
#define MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_LSB_CNTRL_LSB_MASK (0xffffU)
#define MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_LSB_CNTRL_LSB_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_PAD_CFG_TYPE;
#define MEMC_CHIP_MISC_PAD_CFG_DISP_IF_EN_MASK (0x800U)
#define MEMC_CHIP_MISC_PAD_CFG_DISP_IF_EN_SHIFT (11U)
#define MEMC_CHIP_MISC_PAD_CFG_CAM_MODEHV_MASK (0x400U)
#define MEMC_CHIP_MISC_PAD_CFG_CAM_MODEHV_SHIFT (10U)
#define MEMC_CHIP_MISC_PAD_CFG_GPIO_MODEHV_MASK (0x200U)
#define MEMC_CHIP_MISC_PAD_CFG_GPIO_MODEHV_SHIFT (9U)
#define MEMC_CHIP_MISC_PAD_CFG_SDIO_MODEHV_MASK (0x100U)
#define MEMC_CHIP_MISC_PAD_CFG_SDIO_MODEHV_SHIFT (8U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_SEL_MASK (0xe0U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_SEL_SHIFT (5U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_SRC_MASK (0x18U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_SRC_SHIFT (3U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_GMII_SEL_MASK (0x4U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_GMII_SEL_SHIFT (2U)
#define MEMC_CHIP_MISC_PAD_CFG_HSTL_EN_MASK (0x2U)
#define MEMC_CHIP_MISC_PAD_CFG_HSTL_EN_SHIFT (1U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_MODEHV_MASK (0x1U)
#define MEMC_CHIP_MISC_PAD_CFG_RGMII_MODEHV_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_IMG_TEST_TYPE;
#define MEMC_CHIP_MISC_IMG_TEST_PIXELCLK_SEL_MASK (0x600U)
#define MEMC_CHIP_MISC_IMG_TEST_PIXELCLK_SEL_SHIFT (9U)
#define MEMC_CHIP_MISC_IMG_TEST_VSYNC_SEL_MASK (0x100U)
#define MEMC_CHIP_MISC_IMG_TEST_VSYNC_SEL_SHIFT (8U)
#define MEMC_CHIP_MISC_IMG_TEST_AWCACHE_MASK (0xf0U)
#define MEMC_CHIP_MISC_IMG_TEST_AWCACHE_SHIFT (4U)
#define MEMC_CHIP_MISC_IMG_TEST_ARCACHE_MASK (0xfU)
#define MEMC_CHIP_MISC_IMG_TEST_ARCACHE_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_CHIP_TEST_MODE_TYPE;
#define MEMC_CHIP_MISC_CHIP_TEST_MODE_BRPHY_MDIO_BUSY_CTRL_MASK (0x300U)
#define MEMC_CHIP_MISC_CHIP_TEST_MODE_BRPHY_MDIO_BUSY_CTRL_SHIFT (8U)
#define MEMC_CHIP_MISC_CHIP_TEST_MODE_TEST_ENABLE_MASK (0x7fU)
#define MEMC_CHIP_MISC_CHIP_TEST_MODE_TEST_ENABLE_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_CLK_PINSTRAP_TYPE;
#define MEMC_CHIP_MISC_CLK_PINSTRAP_PLLDISP_REFCLK_SEL_MASK (0x10U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_PLLDISP_REFCLK_SEL_SHIFT (4U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_XTAL_MODE_MASK (0x8U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_XTAL_MODE_SHIFT (3U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_REFCLK_SEL_2_MASK (0x4U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_REFCLK_SEL_2_SHIFT (2U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_REFCLK_SEL_1_MASK (0x2U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_REFCLK_SEL_1_SHIFT (1U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_REFCLK_SEL_0_MASK (0x1U)
#define MEMC_CHIP_MISC_CLK_PINSTRAP_REFCLK_SEL_0_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_DEBUG_PINSTRAP_TYPE;
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_SW_BOOTUP_STAT_OUT_MASK (0x8U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_SW_BOOTUP_STAT_OUT_SHIFT (3U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_BOOTUP_FLASH_MASK (0x4U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_BOOTUP_FLASH_SHIFT (2U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_BOOTUP_CLKDIV_DIS_MASK (0x2U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_BOOTUP_CLKDIV_DIS_SHIFT (1U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_TESTPIN_DIS_MASK (0x1U)
#define MEMC_CHIP_MISC_DEBUG_PINSTRAP_TESTPIN_DIS_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_CPU_TEST_TYPE;
#define MEMC_CHIP_MISC_CPU_TEST_DFT_CPUINT_MASK (0x10U)
#define MEMC_CHIP_MISC_CPU_TEST_DFT_CPUINT_SHIFT (4U)
#define MEMC_CHIP_MISC_CPU_TEST_LV_JTAG_BYPASS_MASK (0x8U)
#define MEMC_CHIP_MISC_CPU_TEST_LV_JTAG_BYPASS_SHIFT (3U)
#define MEMC_CHIP_MISC_CPU_TEST_BRPHY_RDB_RDCLR_EN_MASK (0x4U)
#define MEMC_CHIP_MISC_CPU_TEST_BRPHY_RDB_RDCLR_EN_SHIFT (2U)
#define MEMC_CHIP_MISC_CPU_TEST_RESET_ENB_MASK (0x2U)
#define MEMC_CHIP_MISC_CPU_TEST_RESET_ENB_SHIFT (1U)
#define MEMC_CHIP_MISC_CPU_TEST_INITVTOR_SEL_MASK (0x1U)
#define MEMC_CHIP_MISC_CPU_TEST_INITVTOR_SEL_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_INITVTOR_DBG_0_TYPE;
#define MEMC_CHIP_MISC_INITVTOR_DBG_0_0_MASK (0xffffU)
#define MEMC_CHIP_MISC_INITVTOR_DBG_0_0_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_INITVTOR_DBG_1_TYPE;
#define MEMC_CHIP_MISC_INITVTOR_DBG_1_1_MASK (0x1ffU)
#define MEMC_CHIP_MISC_INITVTOR_DBG_1_1_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_VID_RESET_STAT_TYPE;
#define MEMC_CHIP_MISC_VID_RESET_STAT_STAT_MASK (0x3ffU)
#define MEMC_CHIP_MISC_VID_RESET_STAT_STAT_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TEST_PIN_SEL_0_TYPE;
#define MEMC_CHIP_MISC_TEST_PIN_SEL_0_EN_MASK (0xffffU)
#define MEMC_CHIP_MISC_TEST_PIN_SEL_0_EN_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TEST_PIN_SEL_1_TYPE;
#define MEMC_CHIP_MISC_TEST_PIN_SEL_1_EN_MASK (0xffffU)
#define MEMC_CHIP_MISC_TEST_PIN_SEL_1_EN_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TEST_PIN_SEL_2_TYPE;
#define MEMC_CHIP_MISC_TEST_PIN_SEL_2_EN_MASK (0xffffU)
#define MEMC_CHIP_MISC_TEST_PIN_SEL_2_EN_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TPIN_REG_0_TYPE;
#define MEMC_CHIP_MISC_TPIN_REG_0_15_00_MASK (0xffffU)
#define MEMC_CHIP_MISC_TPIN_REG_0_15_00_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TPIN_REG_1_TYPE;
#define MEMC_CHIP_MISC_TPIN_REG_1_31_16_MASK (0xffffU)
#define MEMC_CHIP_MISC_TPIN_REG_1_31_16_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TPOUT_REG_0_TYPE;
#define MEMC_CHIP_MISC_TPOUT_REG_0_15_00_MASK (0xffffU)
#define MEMC_CHIP_MISC_TPOUT_REG_0_15_00_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_TPOUT_REG_1_TYPE;
#define MEMC_CHIP_MISC_TPOUT_REG_1_31_16_MASK (0xffffU)
#define MEMC_CHIP_MISC_TPOUT_REG_1_31_16_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_PLL_INTR_TYPE;
#define MEMC_CHIP_MISC_PLL_INTR_PLLVID_MASK_MASK (0x200U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLVID_MASK_SHIFT (9U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLDISP_MASK_MASK (0x100U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLDISP_MASK_SHIFT (8U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLVID_INTR_MASK (0x2U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLVID_INTR_SHIFT (1U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLDISP_INTR_MASK (0x1U)
#define MEMC_CHIP_MISC_PLL_INTR_PLLDISP_INTR_SHIFT (0U)




typedef uint16_t MEMC_CHIP_MISC_DDR_MISC_TYPE;
#define MEMC_CHIP_MISC_DDR_MISC_MEMC_SELFREF_MASK (0x4U)
#define MEMC_CHIP_MISC_DDR_MISC_MEMC_SELFREF_SHIFT (2U)
#define MEMC_CHIP_MISC_DDR_MISC_FORCE_DDR_IDDQ_MASK (0x2U)
#define MEMC_CHIP_MISC_DDR_MISC_FORCE_DDR_IDDQ_SHIFT (1U)
#define MEMC_CHIP_MISC_DDR_MISC_FORCE_DDR_RESET_MASK (0x1U)
#define MEMC_CHIP_MISC_DDR_MISC_FORCE_DDR_RESET_SHIFT (0U)




typedef volatile struct COMP_PACKED _MEMC_CHIP_MISC_RDBType {
    MEMC_CHIP_MISC_RESERVED_TYPE rsvd0[112]; /* OFFSET: 0x0 */
    MEMC_CHIP_MISC_DDRLDO_CFG_TYPE ddrldo_cfg; /* OFFSET: 0x70 */
    MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_MSB_TYPE ddrldo_ldo_cntl_msb; /* OFFSET: 0x72 */
    MEMC_CHIP_MISC_DDRLDO_LDO_CNTL_LSB_TYPE ddrldo_ldo_cntl_lsb; /* OFFSET: 0x74 */
    MEMC_CHIP_MISC_PAD_CFG_TYPE pad_cfg; /* OFFSET: 0x76 */
    MEMC_CHIP_MISC_IMG_TEST_TYPE img_test; /* OFFSET: 0x78 */
    MEMC_CHIP_MISC_RESERVED_TYPE rsvd1[38]; /* OFFSET: 0x7a */
    MEMC_CHIP_MISC_CHIP_TEST_MODE_TYPE chip_test_mode; /* OFFSET: 0xa0 */
    MEMC_CHIP_MISC_CLK_PINSTRAP_TYPE clk_pinstrap; /* OFFSET: 0xa2 */
    MEMC_CHIP_MISC_DEBUG_PINSTRAP_TYPE debug_pinstrap; /* OFFSET: 0xa4 */
    MEMC_CHIP_MISC_CPU_TEST_TYPE cpu_test; /* OFFSET: 0xa6 */
    MEMC_CHIP_MISC_INITVTOR_DBG_0_TYPE initvtor_dbg_0; /* OFFSET: 0xa8 */
    MEMC_CHIP_MISC_INITVTOR_DBG_1_TYPE initvtor_dbg_1; /* OFFSET: 0xaa */
    MEMC_CHIP_MISC_VID_RESET_STAT_TYPE vid_reset_stat; /* OFFSET: 0xac */
    MEMC_CHIP_MISC_RESERVED_TYPE rsvd2[2]; /* OFFSET: 0xae */
    MEMC_CHIP_MISC_TEST_PIN_SEL_0_TYPE test_pin_sel_0; /* OFFSET: 0xb0 */
    MEMC_CHIP_MISC_TEST_PIN_SEL_1_TYPE test_pin_sel_1; /* OFFSET: 0xb2 */
    MEMC_CHIP_MISC_TEST_PIN_SEL_2_TYPE test_pin_sel_2; /* OFFSET: 0xb4 */
    MEMC_CHIP_MISC_TPIN_REG_0_TYPE tpin_reg_0; /* OFFSET: 0xb6 */
    MEMC_CHIP_MISC_TPIN_REG_1_TYPE tpin_reg_1; /* OFFSET: 0xb8 */
    MEMC_CHIP_MISC_TPOUT_REG_0_TYPE tpout_reg_0; /* OFFSET: 0xba */
    MEMC_CHIP_MISC_TPOUT_REG_1_TYPE tpout_reg_1; /* OFFSET: 0xbc */
    MEMC_CHIP_MISC_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0xbe */
    MEMC_CHIP_MISC_PLL_INTR_TYPE pll_intr; /* OFFSET: 0xc0 */
    MEMC_CHIP_MISC_DDR_MISC_TYPE ddr_misc; /* OFFSET: 0xc2 */
    MEMC_CHIP_MISC_RESERVED_TYPE rsvd4[1852]; /* OFFSET: 0xc4 */
} MEMC_CHIP_MISC_RDBType;


#define MEMC_CHIP_MISC_BASE             (0x42800000UL)



#define MEMC_CHIP_MISC_MAX_HW_ID        (1UL)

#endif /* MEMC_CHIP_MISC_RDB_H */
