/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_port_rdb.h
    @brief RDB File for MEMC_PORT

    @version 2018May25_rdb
*/

#ifndef MEMC_PORT_RDB_H
#define MEMC_PORT_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MEMC_PORT_CTRL_TYPE;
#define MEMC_PORT_CTRL_RD_WR_ORDER_MASK (0x8UL)
#define MEMC_PORT_CTRL_RD_WR_ORDER_SHIFT (3UL)
#define MEMC_PORT_CTRL_ENABLE_UNIQUIFY_NUMBER_MASK (0x4UL)
#define MEMC_PORT_CTRL_ENABLE_UNIQUIFY_NUMBER_SHIFT (2UL)
#define MEMC_PORT_CTRL_USER_BITS_CAM_SELECT_MASK (0x2UL)
#define MEMC_PORT_CTRL_USER_BITS_CAM_SELECT_SHIFT (1UL)
#define MEMC_PORT_CTRL_FIXED_SCHEDULE_NUMBER_MASK (0x1UL)
#define MEMC_PORT_CTRL_FIXED_SCHEDULE_NUMBER_SHIFT (0UL)




typedef uint32_t MEMC_PORT_DCO_TYPE;
#define MEMC_PORT_DCO_PORT_ENABLE_MASK (0x8UL)
#define MEMC_PORT_DCO_PORT_ENABLE_SHIFT (3UL)
#define MEMC_PORT_DCO_GEN_DECERR_FOR_EXLCUSIVE_AXI_ACCESSES_MASK (0x4UL)
#define MEMC_PORT_DCO_GEN_DECERR_FOR_EXLCUSIVE_AXI_ACCESSES_SHIFT (2UL)
#define MEMC_PORT_DCO_MSK_WR_DATA_INTERLEAVING_CHK_MASK (0x2UL)
#define MEMC_PORT_DCO_MSK_WR_DATA_INTERLEAVING_CHK_SHIFT (1UL)
#define MEMC_PORT_DCO_FORCE_HW_SELFREF_USE_MASK (0x1UL)
#define MEMC_PORT_DCO_FORCE_HW_SELFREF_USE_SHIFT (0UL)




typedef uint32_t MEMC_PORT_DBG_INTR_TYPE;
#define MEMC_PORT_DBG_INTR_ERR_AWID_MASK (0x3ffe0000UL)
#define MEMC_PORT_DBG_INTR_ERR_AWID_SHIFT (17UL)
#define MEMC_PORT_DBG_INTR_WR_DATA_INTERLEAVING_INTR_MASK (0x10000UL)
#define MEMC_PORT_DBG_INTR_WR_DATA_INTERLEAVING_INTR_SHIFT (16UL)
#define MEMC_PORT_DBG_INTR_ERR_WID_MASK (0x1fffUL)
#define MEMC_PORT_DBG_INTR_ERR_WID_SHIFT (0UL)




typedef uint32_t MEMC_PORT_DBG_MEMC_CONFIG_TYPE;
#define MEMC_PORT_DBG_MEMC_CONFIG_NUM_OF_DEMESH_ENTRIES_MASK (0x1f0000UL)
#define MEMC_PORT_DBG_MEMC_CONFIG_NUM_OF_DEMESH_ENTRIES_SHIFT (16UL)
#define MEMC_PORT_DBG_MEMC_CONFIG_AXI_DW_MASK (0x3UL)
#define MEMC_PORT_DBG_MEMC_CONFIG_AXI_DW_SHIFT (0UL)




typedef uint32_t MEMC_PORT_DBG_AXI_ERR_COND_TYPE;
#define MEMC_PORT_DBG_AXI_ERR_COND_COND_MASK (0xfffUL)
#define MEMC_PORT_DBG_AXI_ERR_COND_COND_SHIFT (0UL)




typedef uint32_t MEMC_PORT_SPEEDUP_TYPE;
#define MEMC_PORT_SPEEDUP_URGENT_SPEEDUP_MASK (0x3ff0000UL)
#define MEMC_PORT_SPEEDUP_URGENT_SPEEDUP_SHIFT (16UL)
#define MEMC_PORT_SPEEDUP_DEMESH_FULL_SPEEDUP_MASK (0x3ffUL)
#define MEMC_PORT_SPEEDUP_DEMESH_FULL_SPEEDUP_SHIFT (0UL)




typedef uint32_t MEMC_PORT_MISS_THRESHOLD_TYPE;
#define MEMC_PORT_MISS_THRESHOLD_THRESHOLD_MASK (0x3ffUL)
#define MEMC_PORT_MISS_THRESHOLD_THRESHOLD_SHIFT (0UL)




typedef uint8_t MEMC_PORT_RESERVED_TYPE;




typedef uint32_t MEMC_PORT_CAM_ENABLE_TYPE;
#define MEMC_PORT_CAM_ENABLE_TAG_ENABLE_MASK (0x1fff0000UL)
#define MEMC_PORT_CAM_ENABLE_TAG_ENABLE_SHIFT (16UL)
#define MEMC_PORT_CAM_ENABLE_TAG_MASK (0x1fffUL)
#define MEMC_PORT_CAM_ENABLE_TAG_SHIFT (0UL)




typedef uint32_t MEMC_PORT_CAM_ENTRY_TYPE;
#define MEMC_PORT_CAM_ENTRY_HARD_SCHEDULE_MASK (0x400000UL)
#define MEMC_PORT_CAM_ENTRY_HARD_SCHEDULE_SHIFT (22UL)
#define MEMC_PORT_CAM_ENTRY_READ_ENABLE_MASK (0x200000UL)
#define MEMC_PORT_CAM_ENTRY_READ_ENABLE_SHIFT (21UL)
#define MEMC_PORT_CAM_ENTRY_WRITE_ENABLE_MASK (0x100000UL)
#define MEMC_PORT_CAM_ENTRY_WRITE_ENABLE_SHIFT (20UL)
#define MEMC_PORT_CAM_ENTRY_LATENCY_MASK (0x10000UL)
#define MEMC_PORT_CAM_ENTRY_LATENCY_SHIFT (16UL)
#define MEMC_PORT_CAM_ENTRY_SCHEDULE_NUMBER_MASK (0x1ffUL)
#define MEMC_PORT_CAM_ENTRY_SCHEDULE_NUMBER_SHIFT (0UL)




typedef uint32_t MEMC_PORT_MEMORY_MAP_TYPE;
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_11_MASK (0x3000UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_11_SHIFT (12UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_10_MASK (0x300UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_10_SHIFT (8UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_01_MASK (0x30UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_01_SHIFT (4UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_00_MASK (0x3UL)
#define MEMC_PORT_MEMORY_MAP_MSB2_EQ_00_SHIFT (0UL)




typedef uint32_t MEMC_PORT_CLK_GATING_CNTRL_TYPE;
#define MEMC_PORT_CLK_GATING_CNTRL_IDLE_TIME_MASK (0xff00UL)
#define MEMC_PORT_CLK_GATING_CNTRL_IDLE_TIME_SHIFT (8UL)
#define MEMC_PORT_CLK_GATING_CNTRL_EN_CLK_GATING_MASK (0x1UL)
#define MEMC_PORT_CLK_GATING_CNTRL_EN_CLK_GATING_SHIFT (0UL)




typedef uint32_t MEMC_PORT_LIMIT_DEMESH_ENTRIES_TYPE;
#define MEMC_PORT_LIMIT_DEMESH_ENTRIES_ENTRIES_MASK (0x3fUL)
#define MEMC_PORT_LIMIT_DEMESH_ENTRIES_ENTRIES_SHIFT (0UL)




typedef uint32_t MEMC_PORT_WR_INTERLEAVE_ADDR_TYPE;
#define MEMC_PORT_WR_INTERLEAVE_ADDR_ADDR_MASK (0xffffffffUL)
#define MEMC_PORT_WR_INTERLEAVE_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t MEMC_PORT_LIMIT_PRE_MCC_DEP_TYPE;
#define MEMC_PORT_LIMIT_PRE_MCC_DEP_DEP_MASK (0x1fUL)
#define MEMC_PORT_LIMIT_PRE_MCC_DEP_DEP_SHIFT (0UL)




typedef uint32_t MEMC_PORT_SPR_TYPE;
#define MEMC_PORT_SPR_SPR_MASK (0xffffffffUL)
#define MEMC_PORT_SPR_SPR_SHIFT (0UL)




typedef uint32_t MEMC_PORT_SPR_RW_TYPE;
#define MEMC_PORT_SPR_RW_SPR_MASK (0xffffffffUL)
#define MEMC_PORT_SPR_RW_SPR_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MEMC_PORT_RDBType {
    MEMC_PORT_CTRL_TYPE ctrl; /* OFFSET: 0x0 */
    MEMC_PORT_DCO_TYPE dbg_control_overrides; /* OFFSET: 0x4 */
    MEMC_PORT_DBG_INTR_TYPE dbg_intr_register; /* OFFSET: 0x8 */
    MEMC_PORT_DBG_MEMC_CONFIG_TYPE dbg_memc_config; /* OFFSET: 0xc */
    MEMC_PORT_DBG_AXI_ERR_COND_TYPE dbg_port0_axi_err_cond; /* OFFSET: 0x10 */
    MEMC_PORT_SPEEDUP_TYPE port_speedup; /* OFFSET: 0x14 */
    MEMC_PORT_MISS_THRESHOLD_TYPE miss_threshold; /* OFFSET: 0x18 */
    MEMC_PORT_RESERVED_TYPE rsvd0[36]; /* OFFSET: 0x1c */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_0; /* OFFSET: 0x40 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_1; /* OFFSET: 0x44 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_2; /* OFFSET: 0x48 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_3; /* OFFSET: 0x4c */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_4; /* OFFSET: 0x50 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_5; /* OFFSET: 0x54 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_6; /* OFFSET: 0x58 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_7; /* OFFSET: 0x5c */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_8; /* OFFSET: 0x60 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_9; /* OFFSET: 0x64 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_10; /* OFFSET: 0x68 */
    MEMC_PORT_CAM_ENABLE_TYPE cam_enable_11; /* OFFSET: 0x6c */
    MEMC_PORT_RESERVED_TYPE rsvd1[16]; /* OFFSET: 0x70 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_0; /* OFFSET: 0x80 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_1; /* OFFSET: 0x84 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_2; /* OFFSET: 0x88 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_3; /* OFFSET: 0x8c */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_4; /* OFFSET: 0x90 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_5; /* OFFSET: 0x94 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_6; /* OFFSET: 0x98 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_7; /* OFFSET: 0x9c */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_8; /* OFFSET: 0xa0 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_9; /* OFFSET: 0xa4 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_10; /* OFFSET: 0xa8 */
    MEMC_PORT_CAM_ENTRY_TYPE cam_entry_11; /* OFFSET: 0xac */
    MEMC_PORT_MEMORY_MAP_TYPE msb_address_remap; /* OFFSET: 0xb0 */
    MEMC_PORT_CLK_GATING_CNTRL_TYPE port_clk_gating_cntrl; /* OFFSET: 0xb4 */
    MEMC_PORT_LIMIT_DEMESH_ENTRIES_TYPE limit_demesh_entries; /* OFFSET: 0xb8 */
    MEMC_PORT_WR_INTERLEAVE_ADDR_TYPE wr_interleave_addr; /* OFFSET: 0xbc */
    MEMC_PORT_LIMIT_PRE_MCC_DEP_TYPE limit_pre_mcc_dep; /* OFFSET: 0xc0 */
    MEMC_PORT_RESERVED_TYPE rsvd2[52]; /* OFFSET: 0xc4 */
    MEMC_PORT_SPR_TYPE spr_ro; /* OFFSET: 0xf8 */
    MEMC_PORT_SPR_RW_TYPE spr_rw; /* OFFSET: 0xfc */
} MEMC_PORT_RDBType;


#define MEMC_PORT0_BASE                 (0xE020A600UL)

#define MEMC_PORT1_BASE                 (0xE020A700UL)

#define MEMC_PORT2_BASE                 (0xE020A800UL)



#define MEMC_PORT_MAX_HW_ID             (3UL)

#endif /* MEMC_PORT_RDB_H */
