/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file memc_seq_rdb.h
    @brief RDB File for MEMC_SEQ

    @version 2018May25_rdb
*/

#ifndef MEMC_SEQ_RDB_H
#define MEMC_SEQ_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MEMC_SEQ_SW_INIT_DONE_TYPE;
#define MEMC_SEQ_SW_INIT_DONE_DONE_MASK (0x1UL)
#define MEMC_SEQ_SW_INIT_DONE_DONE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_CS_SWITCH_NOP_TYPE;
#define MEMC_SEQ_CS_SWITCH_NOP_0TO1_MASK (0x70UL)
#define MEMC_SEQ_CS_SWITCH_NOP_0TO1_SHIFT (4UL)
#define MEMC_SEQ_CS_SWITCH_NOP_1TO0_MASK (0x7UL)
#define MEMC_SEQ_CS_SWITCH_NOP_1TO0_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DDR_RL_WL_TYPE;
#define MEMC_SEQ_DDR_RL_WL_WL_MASK (0xf0UL)
#define MEMC_SEQ_DDR_RL_WL_WL_SHIFT (4UL)
#define MEMC_SEQ_DDR_RL_WL_RL_MASK (0xfUL)
#define MEMC_SEQ_DDR_RL_WL_RL_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DRAM_TIMING0_TYPE;
#define MEMC_SEQ_DRAM_TIMING0_TRTP_MASK (0x70000000UL)
#define MEMC_SEQ_DRAM_TIMING0_TRTP_SHIFT (28UL)
#define MEMC_SEQ_DRAM_TIMING0_TRP_PB_MASK (0x1f00000UL)
#define MEMC_SEQ_DRAM_TIMING0_TRP_PB_SHIFT (20UL)
#define MEMC_SEQ_DRAM_TIMING0_TRP_AB_MASK (0x1f000UL)
#define MEMC_SEQ_DRAM_TIMING0_TRP_AB_SHIFT (12UL)
#define MEMC_SEQ_DRAM_TIMING0_TRRD_MASK (0xf00UL)
#define MEMC_SEQ_DRAM_TIMING0_TRRD_SHIFT (8UL)
#define MEMC_SEQ_DRAM_TIMING0_TRCD_MASK (0x1fUL)
#define MEMC_SEQ_DRAM_TIMING0_TRCD_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DRAM_TIMING1_TYPE;
#define MEMC_SEQ_DRAM_TIMING1_TXSR_MASK (0x1ff00000UL)
#define MEMC_SEQ_DRAM_TIMING1_TXSR_SHIFT (20UL)
#define MEMC_SEQ_DRAM_TIMING1_TCKESR_MASK (0xf0000UL)
#define MEMC_SEQ_DRAM_TIMING1_TCKESR_SHIFT (16UL)
#define MEMC_SEQ_DRAM_TIMING1_TXP_MASK (0xf000UL)
#define MEMC_SEQ_DRAM_TIMING1_TXP_SHIFT (12UL)
#define MEMC_SEQ_DRAM_TIMING1_TFAW_MASK (0x3f0UL)
#define MEMC_SEQ_DRAM_TIMING1_TFAW_SHIFT (4UL)
#define MEMC_SEQ_DRAM_TIMING1_TWTR_MASK (0x7UL)
#define MEMC_SEQ_DRAM_TIMING1_TWTR_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DRAM_TIMING2_TYPE;
#define MEMC_SEQ_DRAM_TIMING2_TRFC_PB_MASK (0x7f000000UL)
#define MEMC_SEQ_DRAM_TIMING2_TRFC_PB_SHIFT (24UL)
#define MEMC_SEQ_DRAM_TIMING2_TRFC_AB_MASK (0x7fc000UL)
#define MEMC_SEQ_DRAM_TIMING2_TRFC_AB_SHIFT (14UL)
#define MEMC_SEQ_DRAM_TIMING2_TRAS_MASK (0x3f00UL)
#define MEMC_SEQ_DRAM_TIMING2_TRAS_SHIFT (8UL)
#define MEMC_SEQ_DRAM_TIMING2_TWR_MASK (0xf0UL)
#define MEMC_SEQ_DRAM_TIMING2_TWR_SHIFT (4UL)
#define MEMC_SEQ_DRAM_TIMING2_TDQSCK_MASK (0xfUL)
#define MEMC_SEQ_DRAM_TIMING2_TDQSCK_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TYPE;
#define MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TZQCL_MASK (0x1ff00UL)
#define MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TZQCL_SHIFT (8UL)
#define MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TZQCS_MASK (0x7fUL)
#define MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TZQCS_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_MEMC_SWAP_CS0_CS1_TYPE;
#define MEMC_SEQ_MEMC_SWAP_CS0_CS1_CS_MASK (0x1UL)
#define MEMC_SEQ_MEMC_SWAP_CS0_CS1_CS_SHIFT (0UL)




typedef uint8_t MEMC_SEQ_RESERVED_TYPE;




typedef uint32_t MEMC_SEQ_CLK_GATING_CONTROL_TYPE;
#define MEMC_SEQ_CLK_GATING_CONTROL_EN_MASK (0x1UL)
#define MEMC_SEQ_CLK_GATING_CONTROL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_CKE_PD_CONTROL_TYPE;
#define MEMC_SEQ_CKE_PD_CONTROL_TCKSRE_MASK (0xf00000UL)
#define MEMC_SEQ_CKE_PD_CONTROL_TCKSRE_SHIFT (20UL)
#define MEMC_SEQ_CKE_PD_CONTROL_TCKSRX_MASK (0xf0000UL)
#define MEMC_SEQ_CKE_PD_CONTROL_TCKSRX_SHIFT (16UL)
#define MEMC_SEQ_CKE_PD_CONTROL_TCKE_MASK (0x7000UL)
#define MEMC_SEQ_CKE_PD_CONTROL_TCKE_SHIFT (12UL)
#define MEMC_SEQ_CKE_PD_CONTROL_INACTIVITY_PERIOD_MASK (0x3f0UL)
#define MEMC_SEQ_CKE_PD_CONTROL_INACTIVITY_PERIOD_SHIFT (4UL)
#define MEMC_SEQ_CKE_PD_CONTROL_EN_PER_CS_MASK (0x2UL)
#define MEMC_SEQ_CKE_PD_CONTROL_EN_PER_CS_SHIFT (1UL)
#define MEMC_SEQ_CKE_PD_CONTROL_EN_MASK (0x1UL)
#define MEMC_SEQ_CKE_PD_CONTROL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_SREF_PD_CONTROL_TYPE;
#define MEMC_SEQ_SREF_PD_CONTROL_ASSERT_PHY_IDLE_MASK (0x10000000UL)
#define MEMC_SEQ_SREF_PD_CONTROL_ASSERT_PHY_IDLE_SHIFT (28UL)
#define MEMC_SEQ_SREF_PD_CONTROL_INACTIVITY_PERIOD_MASK (0x1fffff0UL)
#define MEMC_SEQ_SREF_PD_CONTROL_INACTIVITY_PERIOD_SHIFT (4UL)
#define MEMC_SEQ_SREF_PD_CONTROL_REFALL_AT_EXIT_MASK (0x4UL)
#define MEMC_SEQ_SREF_PD_CONTROL_REFALL_AT_EXIT_SHIFT (2UL)
#define MEMC_SEQ_SREF_PD_CONTROL_EN_MASK (0x1UL)
#define MEMC_SEQ_SREF_PD_CONTROL_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DDR_PD_STATUS_TYPE;
#define MEMC_SEQ_DDR_PD_STATUS_SREF_PD_MASK (0x4UL)
#define MEMC_SEQ_DDR_PD_STATUS_SREF_PD_SHIFT (2UL)
#define MEMC_SEQ_DDR_PD_STATUS_CKE_CS1_MASK (0x2UL)
#define MEMC_SEQ_DDR_PD_STATUS_CKE_CS1_SHIFT (1UL)
#define MEMC_SEQ_DDR_PD_STATUS_CKE_CS0_MASK (0x1UL)
#define MEMC_SEQ_DDR_PD_STATUS_CKE_CS0_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_ATE_MODE_CONTROL_TYPE;
#define MEMC_SEQ_ATE_MODE_CONTROL_RL_EN_MASK (0x100UL)
#define MEMC_SEQ_ATE_MODE_CONTROL_RL_EN_SHIFT (8UL)
#define MEMC_SEQ_ATE_MODE_CONTROL_RL_OFFSET_MASK (0x7fUL)
#define MEMC_SEQ_ATE_MODE_CONTROL_RL_OFFSET_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_ACC_VIO_ADDR_TYPE;
#define MEMC_SEQ_ACC_VIO_ADDR_ADDR_MASK (0xffffffffUL)
#define MEMC_SEQ_ACC_VIO_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_ACC_VIO_ID_TYPE;
#define MEMC_SEQ_ACC_VIO_ID_PORT_ID_MASK (0x70000UL)
#define MEMC_SEQ_ACC_VIO_ID_PORT_ID_SHIFT (16UL)
#define MEMC_SEQ_ACC_VIO_ID_AXI_ID_MASK (0x1fffUL)
#define MEMC_SEQ_ACC_VIO_ID_AXI_ID_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_ACC_VIO_INFO_TYPE;
#define MEMC_SEQ_ACC_VIO_INFO_INTR_OVERRUN_MASK (0x200000UL)
#define MEMC_SEQ_ACC_VIO_INFO_INTR_OVERRUN_SHIFT (21UL)
#define MEMC_SEQ_ACC_VIO_INFO_INTR_MASK (0x100000UL)
#define MEMC_SEQ_ACC_VIO_INFO_INTR_SHIFT (20UL)
#define MEMC_SEQ_ACC_VIO_INFO_REASON_MASK (0x70000UL)
#define MEMC_SEQ_ACC_VIO_INFO_REASON_SHIFT (16UL)
#define MEMC_SEQ_ACC_VIO_INFO_REGION_MASK (0x1ff0UL)
#define MEMC_SEQ_ACC_VIO_INFO_REGION_SHIFT (4UL)
#define MEMC_SEQ_ACC_VIO_INFO_TYPE_MASK (0x1UL)
#define MEMC_SEQ_ACC_VIO_INFO_TYPE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_STATS_CONTROL_TYPE;
#define MEMC_SEQ_STATS_CONTROL_MODE_MASK (0x30UL)
#define MEMC_SEQ_STATS_CONTROL_MODE_SHIFT (4UL)
#define MEMC_SEQ_STATS_CONTROL_ENABLE_MASK (0x1UL)
#define MEMC_SEQ_STATS_CONTROL_ENABLE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_STATS_PERIOD_TYPE;
#define MEMC_SEQ_STATS_PERIOD_COUNT_MASK (0xffffffffUL)
#define MEMC_SEQ_STATS_PERIOD_COUNT_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_STATS_COUNT_TYPE;
#define MEMC_SEQ_STATS_COUNT_COUNT_MASK (0xffffffffUL)
#define MEMC_SEQ_STATS_COUNT_COUNT_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_STATS_STATUS_TYPE;
#define MEMC_SEQ_STATS_STATUS_DONE_MASK (0x1UL)
#define MEMC_SEQ_STATS_STATUS_DONE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DFI_CNTRL_TYPE;
#define MEMC_SEQ_DFI_CNTRL_T_PHY_WRDATA_MASK (0x300UL)
#define MEMC_SEQ_DFI_CNTRL_T_PHY_WRDATA_SHIFT (8UL)
#define MEMC_SEQ_DFI_CNTRL_PHY_WRLAT_MASK (0xf0UL)
#define MEMC_SEQ_DFI_CNTRL_PHY_WRLAT_SHIFT (4UL)
#define MEMC_SEQ_DFI_CNTRL_T_RDDATA_EN_MASK (0xfUL)
#define MEMC_SEQ_DFI_CNTRL_T_RDDATA_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_ERR_GEN_MODE_TYPE;
#define MEMC_SEQ_ERR_GEN_MODE_MODE_MASK (0x1UL)
#define MEMC_SEQ_ERR_GEN_MODE_MODE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_RSTN_CKE_OVERRIDE_TYPE;
#define MEMC_SEQ_RSTN_CKE_OVERRIDE_CKE_OVERRIDE_MASK (0x20UL)
#define MEMC_SEQ_RSTN_CKE_OVERRIDE_CKE_OVERRIDE_SHIFT (5UL)
#define MEMC_SEQ_RSTN_CKE_OVERRIDE_CKE_VAL_MASK (0x10UL)
#define MEMC_SEQ_RSTN_CKE_OVERRIDE_CKE_VAL_SHIFT (4UL)
#define MEMC_SEQ_RSTN_CKE_OVERRIDE_DDR3_RSTN_VAL_MASK (0x1UL)
#define MEMC_SEQ_RSTN_CKE_OVERRIDE_DDR3_RSTN_VAL_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_PHY_PD_CONTROL_TYPE;
#define MEMC_SEQ_PHY_PD_CONTROL_PLL_WAKEUP_MASK (0x80000000UL)
#define MEMC_SEQ_PHY_PD_CONTROL_PLL_WAKEUP_SHIFT (31UL)
#define MEMC_SEQ_PHY_PD_CONTROL_PLL_PD_EN_MASK (0x10000000UL)
#define MEMC_SEQ_PHY_PD_CONTROL_PLL_PD_EN_SHIFT (28UL)
#define MEMC_SEQ_PHY_PD_CONTROL_PLL_PD_IDLE_CNT_MASK (0xffff000UL)
#define MEMC_SEQ_PHY_PD_CONTROL_PLL_PD_IDLE_CNT_SHIFT (12UL)
#define MEMC_SEQ_PHY_PD_CONTROL_CKIO_PD_EN_MASK (0x800UL)
#define MEMC_SEQ_PHY_PD_CONTROL_CKIO_PD_EN_SHIFT (11UL)
#define MEMC_SEQ_PHY_PD_CONTROL_CKIO_PD_IDLE_CNT_MASK (0x1ffUL)
#define MEMC_SEQ_PHY_PD_CONTROL_CKIO_PD_IDLE_CNT_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DFI_WAKEUP_CODE_TYPE;
#define MEMC_SEQ_DFI_WAKEUP_CODE_SREF_PD_CODE_MASK (0xf0UL)
#define MEMC_SEQ_DFI_WAKEUP_CODE_SREF_PD_CODE_SHIFT (4UL)
#define MEMC_SEQ_DFI_WAKEUP_CODE_CKE_PD_CODE_MASK (0xfUL)
#define MEMC_SEQ_DFI_WAKEUP_CODE_CKE_PD_CODE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_MISC_CNTRL_TYPE;
#define MEMC_SEQ_MISC_CNTRL_RD_EN_DFI_COMPLIANCE_MASK (0x10UL)
#define MEMC_SEQ_MISC_CNTRL_RD_EN_DFI_COMPLIANCE_SHIFT (4UL)
#define MEMC_SEQ_MISC_CNTRL_RESTRICT_CAS_PH_EN_MASK (0x2UL)
#define MEMC_SEQ_MISC_CNTRL_RESTRICT_CAS_PH_EN_SHIFT (1UL)
#define MEMC_SEQ_MISC_CNTRL_RESTRICT_CAS_PH_MASK (0x1UL)
#define MEMC_SEQ_MISC_CNTRL_RESTRICT_CAS_PH_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_RD_LVL_MODE_TYPE;
#define MEMC_SEQ_RD_LVL_MODE_ENABLE_MASK (0x1UL)
#define MEMC_SEQ_RD_LVL_MODE_ENABLE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_RD_VLD_TIMEOUT_TYPE;
#define MEMC_SEQ_RD_VLD_TIMEOUT_PERIOD_MASK (0x1f0UL)
#define MEMC_SEQ_RD_VLD_TIMEOUT_PERIOD_SHIFT (4UL)
#define MEMC_SEQ_RD_VLD_TIMEOUT_FREEZE_MASK (0x4UL)
#define MEMC_SEQ_RD_VLD_TIMEOUT_FREEZE_SHIFT (2UL)
#define MEMC_SEQ_RD_VLD_TIMEOUT_ENABLE_MASK (0x1UL)
#define MEMC_SEQ_RD_VLD_TIMEOUT_ENABLE_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_DUMMY_RD_VLD_STATUS_TYPE;
#define MEMC_SEQ_DUMMY_RD_VLD_STATUS_OVERFLOW_MASK (0x100UL)
#define MEMC_SEQ_DUMMY_RD_VLD_STATUS_OVERFLOW_SHIFT (8UL)
#define MEMC_SEQ_DUMMY_RD_VLD_STATUS_COUNT_MASK (0xffUL)
#define MEMC_SEQ_DUMMY_RD_VLD_STATUS_COUNT_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_MAX_LOAD_THRESHOLD_TYPE;
#define MEMC_SEQ_MAX_LOAD_THRESHOLD_THRESHOLD_MASK (0xffffffffUL)
#define MEMC_SEQ_MAX_LOAD_THRESHOLD_THRESHOLD_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_MIN_LOAD_THRESHOLD_TYPE;
#define MEMC_SEQ_MIN_LOAD_THRESHOLD_THRESHOLD_MASK (0xffffffffUL)
#define MEMC_SEQ_MIN_LOAD_THRESHOLD_THRESHOLD_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_FORCE_SELF_REF_TYPE;
#define MEMC_SEQ_FORCE_SELF_REF_REF_MASK (0x1UL)
#define MEMC_SEQ_FORCE_SELF_REF_REF_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_USE_BYPASS_TIMINGS_TYPE;
#define MEMC_SEQ_USE_BYPASS_TIMINGS_TIMING_REGISTERS_MASK (0x1UL)
#define MEMC_SEQ_USE_BYPASS_TIMINGS_TIMING_REGISTERS_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_STATS_CLIENT_SELECT_TAG_TYPE;
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_PORT_TAG_MASK (0xf0000UL)
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_PORT_TAG_SHIFT (16UL)
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_AXI_ID_TAG_MASK (0x1fffUL)
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_AXI_ID_TAG_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_STATS_CLIENT_SELECT_TAG_EN_TYPE;
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_EN_PORT_EN_MASK (0xf0000UL)
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_EN_PORT_EN_SHIFT (16UL)
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_EN_AXI_ID_EN_MASK (0x1fffUL)
#define MEMC_SEQ_STATS_CLIENT_SELECT_TAG_EN_AXI_ID_EN_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_SPR_TYPE;
#define MEMC_SEQ_SPR_SPR_MASK (0xffffffffUL)
#define MEMC_SEQ_SPR_SPR_SHIFT (0UL)




typedef uint32_t MEMC_SEQ_CORE_SPR_RW_TYPE;
#define MEMC_SEQ_CORE_SPR_RW_SPR_MASK (0xffffffffUL)
#define MEMC_SEQ_CORE_SPR_RW_SPR_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MEMC_SEQ_RDBType {
    MEMC_SEQ_SW_INIT_DONE_TYPE sw_init_done; /* OFFSET: 0x0 */
    MEMC_SEQ_CS_SWITCH_NOP_TYPE cs_switch_nop; /* OFFSET: 0x4 */
    MEMC_SEQ_DDR_RL_WL_TYPE ddr_rl_wl; /* OFFSET: 0x8 */
    MEMC_SEQ_DRAM_TIMING0_TYPE dram_timing0; /* OFFSET: 0xc */
    MEMC_SEQ_DRAM_TIMING1_TYPE dram_timing1; /* OFFSET: 0x10 */
    MEMC_SEQ_DRAM_TIMING2_TYPE dram_timing2; /* OFFSET: 0x14 */
    MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TYPE dram_zq_calib_timing; /* OFFSET: 0x18 */
    MEMC_SEQ_MEMC_SWAP_CS0_CS1_TYPE memc_swap_cs0_cs1; /* OFFSET: 0x1c */
    MEMC_SEQ_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x20 */
    MEMC_SEQ_CLK_GATING_CONTROL_TYPE clk_gating_control; /* OFFSET: 0x24 */
    MEMC_SEQ_CKE_PD_CONTROL_TYPE cke_pd_control; /* OFFSET: 0x28 */
    MEMC_SEQ_SREF_PD_CONTROL_TYPE sref_pd_control; /* OFFSET: 0x2c */
    MEMC_SEQ_DDR_PD_STATUS_TYPE ddr_pd_status; /* OFFSET: 0x30 */
    MEMC_SEQ_ATE_MODE_CONTROL_TYPE ate_mode_control; /* OFFSET: 0x34 */
    MEMC_SEQ_ACC_VIO_ADDR_TYPE acc_vio_addr; /* OFFSET: 0x38 */
    MEMC_SEQ_ACC_VIO_ID_TYPE acc_vio_id; /* OFFSET: 0x3c */
    MEMC_SEQ_ACC_VIO_INFO_TYPE acc_vio_info; /* OFFSET: 0x40 */
    MEMC_SEQ_STATS_CONTROL_TYPE stats_control; /* OFFSET: 0x44 */
    MEMC_SEQ_STATS_PERIOD_TYPE stats_period; /* OFFSET: 0x48 */
    MEMC_SEQ_STATS_COUNT_TYPE stats_cnt_rd; /* OFFSET: 0x4c */
    MEMC_SEQ_STATS_COUNT_TYPE stats_cnt_wr; /* OFFSET: 0x50 */
    MEMC_SEQ_STATS_COUNT_TYPE stats_cnt_act; /* OFFSET: 0x54 */
    MEMC_SEQ_STATS_COUNT_TYPE stats_cnt_ref; /* OFFSET: 0x58 */
    MEMC_SEQ_STATS_STATUS_TYPE stats_status; /* OFFSET: 0x5c */
    MEMC_SEQ_DFI_CNTRL_TYPE dfi_cntrl; /* OFFSET: 0x60 */
    MEMC_SEQ_ERR_GEN_MODE_TYPE err_gen_mode; /* OFFSET: 0x64 */
    MEMC_SEQ_RSTN_CKE_OVERRIDE_TYPE rstn_cke_override; /* OFFSET: 0x68 */
    MEMC_SEQ_PHY_PD_CONTROL_TYPE phy_pd_control; /* OFFSET: 0x6c */
    MEMC_SEQ_DFI_WAKEUP_CODE_TYPE dfi_wakeup_code; /* OFFSET: 0x70 */
    MEMC_SEQ_MISC_CNTRL_TYPE misc_cntrl; /* OFFSET: 0x74 */
    MEMC_SEQ_RD_LVL_MODE_TYPE rd_lvl_mode; /* OFFSET: 0x78 */
    MEMC_SEQ_RD_VLD_TIMEOUT_TYPE rd_vld_timeout; /* OFFSET: 0x7c */
    MEMC_SEQ_DUMMY_RD_VLD_STATUS_TYPE dummy_rd_vld_status; /* OFFSET: 0x80 */
    MEMC_SEQ_CS_SWITCH_NOP_TYPE bypass_cs_switch_nop; /* OFFSET: 0x84 */
    MEMC_SEQ_DDR_RL_WL_TYPE bypass_ddr_rl_wl; /* OFFSET: 0x88 */
    MEMC_SEQ_DRAM_TIMING0_TYPE bypass_dram_timing0; /* OFFSET: 0x8c */
    MEMC_SEQ_DRAM_TIMING1_TYPE bypass_dram_timing1; /* OFFSET: 0x90 */
    MEMC_SEQ_DRAM_TIMING2_TYPE bypass_dram_timing2; /* OFFSET: 0x94 */
    MEMC_SEQ_DRAM_ZQ_CALIB_TIMING_TYPE bypass_dram_zq_calib_timing; /* OFFSET: 0x98 */
    MEMC_SEQ_MAX_LOAD_THRESHOLD_TYPE max_load_threshold; /* OFFSET: 0x9c */
    MEMC_SEQ_RESERVED_TYPE rsvd1[96]; /* OFFSET: 0xa0 */
    MEMC_SEQ_MIN_LOAD_THRESHOLD_TYPE min_load_threshold; /* OFFSET: 0x100 */
    MEMC_SEQ_FORCE_SELF_REF_TYPE force_self_ref; /* OFFSET: 0x104 */
    MEMC_SEQ_USE_BYPASS_TIMINGS_TYPE use_bypass_timing_registers; /* OFFSET: 0x108 */
    MEMC_SEQ_DFI_CNTRL_TYPE bypass_dfi_cntrl; /* OFFSET: 0x10c */
    MEMC_SEQ_STATS_CLIENT_SELECT_TAG_TYPE stats_client_select_tag; /* OFFSET: 0x110 */
    MEMC_SEQ_STATS_CLIENT_SELECT_TAG_EN_TYPE stats_client_select_tag_en; /* OFFSET: 0x114 */
    MEMC_SEQ_SPR_TYPE core_spr_ro; /* OFFSET: 0x118 */
    MEMC_SEQ_CORE_SPR_RW_TYPE core_spr_rw; /* OFFSET: 0x11c */
} MEMC_SEQ_RDBType;


#define MEMC_SEQ_BASE                   (0xE020A200UL)



#define MEMC_SEQ_MAX_HW_ID              (1UL)

#endif /* MEMC_SEQ_RDB_H */
