/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file mfd_rdb.h
    @brief RDB File for MFD

    @version 2018May25_rdb
*/

#ifndef MFD_RDB_H
#define MFD_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MFD_REVISION_ID_TYPE;
#define MFD_REVISION_ID_MAJOR_MASK (0xff00UL)
#define MFD_REVISION_ID_MAJOR_SHIFT (8UL)
#define MFD_REVISION_ID_MINOR_MASK (0xffUL)
#define MFD_REVISION_ID_MINOR_SHIFT (0UL)




typedef uint32_t MFD_HW_CONFIGURATION_TYPE;
#define MFD_HW_CONFIGURATION_SUPPORTS_BT2020_MASK (0x100UL)
#define MFD_HW_CONFIGURATION_SUPPORTS_BT2020_SHIFT (8UL)
#define MFD_HW_CONFIGURATION_SUPPORTS_4K_MASK (0x80UL)
#define MFD_HW_CONFIGURATION_SUPPORTS_4K_SHIFT (7UL)
#define MFD_HW_CONFIGURATION_CORE_BVB_WIDTH_10_MASK (0x40UL)
#define MFD_HW_CONFIGURATION_CORE_BVB_WIDTH_10_SHIFT (6UL)
#define MFD_HW_CONFIGURATION_OUT_BVB_WIDTH_10_MASK (0x20UL)
#define MFD_HW_CONFIGURATION_OUT_BVB_WIDTH_10_SHIFT (5UL)
#define MFD_HW_CONFIGURATION_BVB_CLOCK_IS_2X_MASK (0x10UL)
#define MFD_HW_CONFIGURATION_BVB_CLOCK_IS_2X_SHIFT (4UL)
#define MFD_HW_CONFIGURATION_BVB_IS_DUAL_PIXEL_MASK (0x8UL)
#define MFD_HW_CONFIGURATION_BVB_IS_DUAL_PIXEL_SHIFT (3UL)
#define MFD_HW_CONFIGURATION_MAX_BURST_SIZE_MASK (0x6UL)
#define MFD_HW_CONFIGURATION_MAX_BURST_SIZE_SHIFT (1UL)
#define MFD_HW_CONFIGURATION_CLB_CONFIG_MASK (0x1UL)
#define MFD_HW_CONFIGURATION_CLB_CONFIG_SHIFT (0UL)




typedef uint32_t MFD_FEEDER_CNTL_TYPE;
#define MFD_FEEDER_CNTL_BOT_INIT_PHASE_MASK (0x7f000000UL)
#define MFD_FEEDER_CNTL_BOT_INIT_PHASE_SHIFT (24UL)
#define MFD_FEEDER_CNTL_TOP_INIT_PHASE_MASK (0x7f0000UL)
#define MFD_FEEDER_CNTL_TOP_INIT_PHASE_SHIFT (16UL)
#define MFD_FEEDER_CNTL_BOT_SKIP_FIRST_LINE_MASK (0x8000UL)
#define MFD_FEEDER_CNTL_BOT_SKIP_FIRST_LINE_SHIFT (15UL)
#define MFD_FEEDER_CNTL_TOP_SKIP_FIRST_LINE_MASK (0x4000UL)
#define MFD_FEEDER_CNTL_TOP_SKIP_FIRST_LINE_SHIFT (14UL)
#define MFD_FEEDER_CNTL_MEM_VIDEO_MASK (0x800UL)
#define MFD_FEEDER_CNTL_MEM_VIDEO_SHIFT (11UL)
#define MFD_FEEDER_CNTL_BVB_VIDEO_MASK (0x300UL)
#define MFD_FEEDER_CNTL_BVB_VIDEO_SHIFT (8UL)
#define MFD_FEEDER_CNTL_SCB_CLIENT_SEL_MASK (0x80UL)
#define MFD_FEEDER_CNTL_SCB_CLIENT_SEL_SHIFT (7UL)
#define MFD_FEEDER_CNTL_LINE_REPEAT_MASK (0x40UL)
#define MFD_FEEDER_CNTL_LINE_REPEAT_SHIFT (6UL)
#define MFD_FEEDER_CNTL_PIXEL_SATURATION_ENABLE_MASK (0x20UL)
#define MFD_FEEDER_CNTL_PIXEL_SATURATION_ENABLE_SHIFT (5UL)
#define MFD_FEEDER_CNTL_FIXED_COLOUR_ENABLE_MASK (0x10UL)
#define MFD_FEEDER_CNTL_FIXED_COLOUR_ENABLE_SHIFT (4UL)
#define MFD_FEEDER_CNTL_IMAGE_FORMAT_MASK (0x3UL)
#define MFD_FEEDER_CNTL_IMAGE_FORMAT_SHIFT (0UL)




typedef uint32_t MFD_LAC_CNTL_TYPE;
#define MFD_LAC_CNTL_STRIPE_WIDTH_SEL_MASK (0x60UL)
#define MFD_LAC_CNTL_STRIPE_WIDTH_SEL_SHIFT (5UL)
#define MFD_LAC_CNTL_SEPARATE_FIELD_BUFFER_MASK (0x10UL)
#define MFD_LAC_CNTL_SEPARATE_FIELD_BUFFER_SHIFT (4UL)
#define MFD_LAC_CNTL_CHROMA_INTERPOLATION_MASK (0x8UL)
#define MFD_LAC_CNTL_CHROMA_INTERPOLATION_SHIFT (3UL)
#define MFD_LAC_CNTL_OUTPUT_FIELD_POLARITY_MASK (0x4UL)
#define MFD_LAC_CNTL_OUTPUT_FIELD_POLARITY_SHIFT (2UL)
#define MFD_LAC_CNTL_OUTPUT_TYPE_MASK (0x2UL)
#define MFD_LAC_CNTL_OUTPUT_TYPE_SHIFT (1UL)
#define MFD_LAC_CNTL_CHROMA_TYPE_MASK (0x1UL)
#define MFD_LAC_CNTL_CHROMA_TYPE_SHIFT (0UL)




typedef uint32_t MFD_FIXED_COLOUR_TYPE;
#define MFD_FIXED_COLOUR_LUMA_MASK (0xff0000UL)
#define MFD_FIXED_COLOUR_LUMA_SHIFT (16UL)
#define MFD_FIXED_COLOUR_CB_MASK (0xff00UL)
#define MFD_FIXED_COLOUR_CB_SHIFT (8UL)
#define MFD_FIXED_COLOUR_CR_MASK (0xffUL)
#define MFD_FIXED_COLOUR_CR_SHIFT (0UL)




typedef uint32_t MFD_STRIDE_TYPE;
#define MFD_STRIDE_CHROMA_LINE_STRIDE_MASK (0xffff0000UL)
#define MFD_STRIDE_CHROMA_LINE_STRIDE_SHIFT (16UL)
#define MFD_STRIDE_LUMA_LINE_STRIDE_MASK (0xffffUL)
#define MFD_STRIDE_LUMA_LINE_STRIDE_SHIFT (0UL)
#define MFD_STRIDE_LINE_STRIDE_MASK (0xffffUL)
#define MFD_STRIDE_LINE_STRIDE_SHIFT (0UL)




typedef uint32_t MFD_DISP_HSIZE_TYPE;
#define MFD_DISP_HSIZE_VALUE_MASK (0x1fffUL)
#define MFD_DISP_HSIZE_VALUE_SHIFT (0UL)




typedef uint32_t MFD_DISP_VSIZE_TYPE;
#define MFD_DISP_VSIZE_VALUE_MASK (0x1fffUL)
#define MFD_DISP_VSIZE_VALUE_SHIFT (0UL)




typedef uint32_t MFD_DATA_MODE_TYPE;
#define MFD_DATA_MODE_DEMO_MODE_MASK (0x4UL)
#define MFD_DATA_MODE_DEMO_MODE_SHIFT (2UL)
#define MFD_DATA_MODE_PRECISION_MASK (0x2UL)
#define MFD_DATA_MODE_PRECISION_SHIFT (1UL)
#define MFD_DATA_MODE_PIXEL_WIDTH_MASK (0x1UL)
#define MFD_DATA_MODE_PIXEL_WIDTH_SHIFT (0UL)




typedef uint32_t MFD_DITHER_CTRL_TYPE;
#define MFD_DITHER_CTRL_MODE_MASK (0xc0000000UL)
#define MFD_DITHER_CTRL_MODE_SHIFT (30UL)
#define MFD_DITHER_CTRL_OFFSET_CH2_MASK (0x3e000000UL)
#define MFD_DITHER_CTRL_OFFSET_CH2_SHIFT (25UL)
#define MFD_DITHER_CTRL_SCALE_CH2_MASK (0x1f00000UL)
#define MFD_DITHER_CTRL_SCALE_CH2_SHIFT (20UL)
#define MFD_DITHER_CTRL_OFFSET_CH1_MASK (0xf8000UL)
#define MFD_DITHER_CTRL_OFFSET_CH1_SHIFT (15UL)
#define MFD_DITHER_CTRL_SCALE_CH1_MASK (0x7c00UL)
#define MFD_DITHER_CTRL_SCALE_CH1_SHIFT (10UL)
#define MFD_DITHER_CTRL_OFFSET_CH0_MASK (0x3e0UL)
#define MFD_DITHER_CTRL_OFFSET_CH0_SHIFT (5UL)
#define MFD_DITHER_CTRL_SCALE_CH0_MASK (0x1fUL)
#define MFD_DITHER_CTRL_SCALE_CH0_SHIFT (0UL)




typedef uint32_t MFD_DITHER_LFSR_INIT_TYPE;
#define MFD_DITHER_LFSR_INIT_SEQ_MASK (0x300000UL)
#define MFD_DITHER_LFSR_INIT_SEQ_SHIFT (20UL)
#define MFD_DITHER_LFSR_INIT_VALUE_MASK (0xfffffUL)
#define MFD_DITHER_LFSR_INIT_VALUE_SHIFT (0UL)




typedef uint32_t MFD_DITHER_LFSR_CTRL_TYPE;
#define MFD_DITHER_LFSR_CTRL_T2_MASK (0x700UL)
#define MFD_DITHER_LFSR_CTRL_T2_SHIFT (8UL)
#define MFD_DITHER_LFSR_CTRL_T1_MASK (0x70UL)
#define MFD_DITHER_LFSR_CTRL_T1_SHIFT (4UL)
#define MFD_DITHER_LFSR_CTRL_T0_MASK (0x7UL)
#define MFD_DITHER_LFSR_CTRL_T0_SHIFT (0UL)




typedef uint32_t MFD_COMP_ORDER_TYPE;
#define MFD_COMP_ORDER_3_SEL_MASK (0xc0UL)
#define MFD_COMP_ORDER_3_SEL_SHIFT (6UL)
#define MFD_COMP_ORDER_2_SEL_MASK (0x30UL)
#define MFD_COMP_ORDER_2_SEL_SHIFT (4UL)
#define MFD_COMP_ORDER_1_SEL_MASK (0xcUL)
#define MFD_COMP_ORDER_1_SEL_SHIFT (2UL)
#define MFD_COMP_ORDER_0_SEL_MASK (0x3UL)
#define MFD_COMP_ORDER_0_SEL_SHIFT (0UL)




typedef uint32_t MFD_ADDR_0_TYPE;
#define MFD_ADDR_0_LUMA_ADDR_MASK (0xffffffffUL)
#define MFD_ADDR_0_LUMA_ADDR_SHIFT (0UL)
#define MFD_ADDR_0_LUMA_CHROMA_ADDR_MASK (0xffffffffUL)
#define MFD_ADDR_0_LUMA_CHROMA_ADDR_SHIFT (0UL)




typedef uint32_t MFD_ADDR_1_TYPE;
#define MFD_ADDR_1_CHROMA_ADDR_MASK (0xffffffffUL)
#define MFD_ADDR_1_CHROMA_ADDR_SHIFT (0UL)




typedef uint32_t MFD_LUMA_NMBY_TYPE;
#define MFD_LUMA_NMBY_VALUE_MASK (0x3ffUL)
#define MFD_LUMA_NMBY_VALUE_SHIFT (0UL)




typedef uint32_t MFD_CHROMA_NMBY_TYPE;
#define MFD_CHROMA_NMBY_VALUE_MASK (0x3ffUL)
#define MFD_CHROMA_NMBY_VALUE_SHIFT (0UL)




typedef uint32_t MFD_PIC_OFFSET_TYPE;
#define MFD_PIC_OFFSET_H_R_MASK (0x70UL)
#define MFD_PIC_OFFSET_H_R_SHIFT (4UL)
#define MFD_PIC_OFFSET_H_OFFSET_MASK (0x7UL)
#define MFD_PIC_OFFSET_H_OFFSET_SHIFT (0UL)




typedef uint32_t MFD_RANGE_EXP_REMAP_CNTL_TYPE;
#define MFD_RANGE_EXP_REMAP_CNTL_SCALE_C_MASK (0x3e0UL)
#define MFD_RANGE_EXP_REMAP_CNTL_SCALE_C_SHIFT (5UL)
#define MFD_RANGE_EXP_REMAP_CNTL_SCALE_Y_MASK (0x1fUL)
#define MFD_RANGE_EXP_REMAP_CNTL_SCALE_Y_SHIFT (0UL)




typedef uint32_t MFD_CHROMA_SAMPLING_CNTL_TYPE;
#define MFD_CHROMA_SAMPLING_CNTL_REPOSITION_ENABLE_R_MASK (0x2UL)
#define MFD_CHROMA_SAMPLING_CNTL_REPOSITION_ENABLE_R_SHIFT (1UL)
#define MFD_CHROMA_SAMPLING_CNTL_REPOSITION_ENABLE_MASK (0x1UL)
#define MFD_CHROMA_SAMPLING_CNTL_REPOSITION_ENABLE_SHIFT (0UL)




typedef uint32_t MFD_DERING_ENABLE_TYPE;
#define MFD_DERING_ENABLE_EN_MASK (0x1UL)
#define MFD_DERING_ENABLE_EN_SHIFT (0UL)




typedef uint32_t MFD_PIC_FEED_CMD_TYPE;
#define MFD_PIC_FEED_CMD_START_FEED_MASK (0x1UL)
#define MFD_PIC_FEED_CMD_START_FEED_SHIFT (0UL)




typedef uint32_t MFD_FEED_STATUS_TYPE;
#define MFD_FEED_STATUS_LAST_LINE_MASK (0x20000000UL)
#define MFD_FEED_STATUS_LAST_LINE_SHIFT (29UL)
#define MFD_FEED_STATUS_LINE_COUNT_MASK (0x1fffUL)
#define MFD_FEED_STATUS_LINE_COUNT_SHIFT (0UL)




typedef uint32_t MFD_LAC_ADDR_0_TYPE;
#define MFD_LAC_ADDR_0_LUMA_ADDR_MASK (0xffffffffUL)
#define MFD_LAC_ADDR_0_LUMA_ADDR_SHIFT (0UL)
#define MFD_LAC_ADDR_0_LUMA_CHROMA_ADDR_MASK (0xffffffffUL)
#define MFD_LAC_ADDR_0_LUMA_CHROMA_ADDR_SHIFT (0UL)




typedef uint32_t MFD_LAC_ADDR_1_TYPE;
#define MFD_LAC_ADDR_1_CHROMA_ADDR_MASK (0xffffffffUL)
#define MFD_LAC_ADDR_1_CHROMA_ADDR_SHIFT (0UL)




typedef uint32_t MFD_LAC_CHROMA_VERT_FILTER_STATUS_TYPE;
#define MFD_LAC_CHROMA_VERT_FILTER_STATUS_REUSING_INPUT_MASK (0x10000UL)
#define MFD_LAC_CHROMA_VERT_FILTER_STATUS_REUSING_INPUT_SHIFT (16UL)
#define MFD_LAC_CHROMA_VERT_FILTER_STATUS_COEFF_TOP_MASK (0x7f00UL)
#define MFD_LAC_CHROMA_VERT_FILTER_STATUS_COEFF_TOP_SHIFT (8UL)
#define MFD_LAC_CHROMA_VERT_FILTER_STATUS_COEFF_BOT_MASK (0x7fUL)
#define MFD_LAC_CHROMA_VERT_FILTER_STATUS_COEFF_BOT_SHIFT (0UL)




typedef uint32_t MFD_LINE_FEED_STATUS_TYPE;
#define MFD_LINE_FEED_STATUS_FIRST_LINE_MASK (0x2UL)
#define MFD_LINE_FEED_STATUS_FIRST_LINE_SHIFT (1UL)
#define MFD_LINE_FEED_STATUS_START_FEED_MASK (0x1UL)
#define MFD_LINE_FEED_STATUS_START_FEED_SHIFT (0UL)




typedef uint32_t MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_TYPE;
#define MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_FEEDER_TIMEOUT_ENABLE_MASK (0x2000000UL)
#define MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_FEEDER_TIMEOUT_ENABLE_SHIFT (25UL)
#define MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_REPEAT_PIC_ENABLE_MASK (0x1000000UL)
#define MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_REPEAT_PIC_ENABLE_SHIFT (24UL)
#define MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_TIMEOUT_COUNT_MASK (0xffffffUL)
#define MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_TIMEOUT_COUNT_SHIFT (0UL)




typedef uint32_t MFD_BVB_RX_STALL_TIMEOUT_CNTL_TYPE;
#define MFD_BVB_RX_STALL_TIMEOUT_CNTL_RX_STALL_ENABLE_MASK (0x1000000UL)
#define MFD_BVB_RX_STALL_TIMEOUT_CNTL_RX_STALL_ENABLE_SHIFT (24UL)
#define MFD_BVB_RX_STALL_TIMEOUT_CNTL_COUNT_MASK (0xffffffUL)
#define MFD_BVB_RX_STALL_TIMEOUT_CNTL_COUNT_SHIFT (0UL)




typedef uint32_t MFD_FEEDER_ERROR_INTERRUPT_STATUS_TYPE;
#define MFD_FEEDER_ERROR_INTERRUPT_STATUS_PIC_FEED_CMD_OVER_WR_MASK (0x4UL)
#define MFD_FEEDER_ERROR_INTERRUPT_STATUS_PIC_FEED_CMD_OVER_WR_SHIFT (2UL)
#define MFD_FEEDER_ERROR_INTERRUPT_STATUS_RX_STALL_TIMEOUT_MASK (0x2UL)
#define MFD_FEEDER_ERROR_INTERRUPT_STATUS_RX_STALL_TIMEOUT_SHIFT (1UL)
#define MFD_FEEDER_ERROR_INTERRUPT_STATUS_FEEDER_TIMEOUT_MASK (0x1UL)
#define MFD_FEEDER_ERROR_INTERRUPT_STATUS_FEEDER_TIMEOUT_SHIFT (0UL)




typedef uint32_t MFD_FEISC_TYPE;
#define MFD_FEISC_PIC_FEED_CMD_OVER_WR_CLR_MASK (0x4UL)
#define MFD_FEISC_PIC_FEED_CMD_OVER_WR_CLR_SHIFT (2UL)
#define MFD_FEISC_RX_STALL_TIMEOUT_CLR_MASK (0x2UL)
#define MFD_FEISC_RX_STALL_TIMEOUT_CLR_SHIFT (1UL)
#define MFD_FEISC_FEEDER_TIMEOUT_CLR_MASK (0x1UL)
#define MFD_FEISC_FEEDER_TIMEOUT_CLR_SHIFT (0UL)




typedef uint32_t MFD_FEEDER_BVB_STATUS_TYPE;
#define MFD_FEEDER_BVB_STATUS_EOF_MASK (0x2UL)
#define MFD_FEEDER_BVB_STATUS_EOF_SHIFT (1UL)
#define MFD_FEEDER_BVB_STATUS_EOL_MASK (0x1UL)
#define MFD_FEEDER_BVB_STATUS_EOL_SHIFT (0UL)




typedef uint32_t MFD_FEEDER_BVB_STATUS_CLR_TYPE;
#define MFD_FEEDER_BVB_STATUS_CLR_EOF_CLR_MASK (0x2UL)
#define MFD_FEEDER_BVB_STATUS_CLR_EOF_CLR_SHIFT (1UL)
#define MFD_FEEDER_BVB_STATUS_CLR_EOL_CLR_MASK (0x1UL)
#define MFD_FEEDER_BVB_STATUS_CLR_EOL_CLR_SHIFT (0UL)




typedef uint32_t MFD_TEST_MODE_CNTL_TYPE;
#define MFD_TEST_MODE_CNTL_BVB_TEST_MODE_MASK (0x4UL)
#define MFD_TEST_MODE_CNTL_BVB_TEST_MODE_SHIFT (2UL)
#define MFD_TEST_MODE_CNTL_ACCEPT_STATE_MASK (0x2UL)
#define MFD_TEST_MODE_CNTL_ACCEPT_STATE_SHIFT (1UL)
#define MFD_TEST_MODE_CNTL_ACCEPT_PULSE_MASK (0x1UL)
#define MFD_TEST_MODE_CNTL_ACCEPT_PULSE_SHIFT (0UL)




typedef uint32_t MFD_BVB_SAMPLE_DATA_TYPE;
#define MFD_BVB_SAMPLE_DATA_LINE_SYNC_MASK (0xc0000000UL)
#define MFD_BVB_SAMPLE_DATA_LINE_SYNC_SHIFT (30UL)
#define MFD_BVB_SAMPLE_DATA_LUMA_MASK (0x3ff00000UL)
#define MFD_BVB_SAMPLE_DATA_LUMA_SHIFT (20UL)
#define MFD_BVB_SAMPLE_DATA_CB_MASK (0xffc00UL)
#define MFD_BVB_SAMPLE_DATA_CB_SHIFT (10UL)
#define MFD_BVB_SAMPLE_DATA_CR_MASK (0x3ffUL)
#define MFD_BVB_SAMPLE_DATA_CR_SHIFT (0UL)




typedef uint32_t MFD_TEST_PORT_CNTL_TYPE;
#define MFD_TEST_PORT_CNTL_TP_ADDR_MASK (0x7UL)
#define MFD_TEST_PORT_CNTL_TP_ADDR_SHIFT (0UL)




typedef uint32_t MFD_TEST_PORT_DATA_TYPE;
#define MFD_TEST_PORT_DATA_HAC_LUMA_ADDR_MASK (0xffffffffUL)
#define MFD_TEST_PORT_DATA_HAC_LUMA_ADDR_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_HAC_CHROMA_ADDR_MASK (0xffffffffUL)
#define MFD_TEST_PORT_DATA_HAC_CHROMA_ADDR_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_FIRST_LINE_TRIG_MASK (0x20000000UL)
#define MFD_TEST_PORT_DATA_FIRST_LINE_TRIG_SHIFT (29UL)
#define MFD_TEST_PORT_DATA_LAC_SOL_MASK (0x10000000UL)
#define MFD_TEST_PORT_DATA_LAC_SOL_SHIFT (28UL)
#define MFD_TEST_PORT_DATA_LAC_BUSY_MASK (0x8000000UL)
#define MFD_TEST_PORT_DATA_LAC_BUSY_SHIFT (27UL)
#define MFD_TEST_PORT_DATA_LINE_ADDR_SEL_MASK (0x2000000UL)
#define MFD_TEST_PORT_DATA_LINE_ADDR_SEL_SHIFT (25UL)
#define MFD_TEST_PORT_DATA_LINE_ADDR_INCR_MASK (0x1800000UL)
#define MFD_TEST_PORT_DATA_LINE_ADDR_INCR_SHIFT (23UL)
#define MFD_TEST_PORT_DATA_CSM_TRIG_MASK (0x400000UL)
#define MFD_TEST_PORT_DATA_CSM_TRIG_SHIFT (22UL)
#define MFD_TEST_PORT_DATA_LUMA_LINE_PHASE_MASK (0x200000UL)
#define MFD_TEST_PORT_DATA_LUMA_LINE_PHASE_SHIFT (21UL)
#define MFD_TEST_PORT_DATA_BUF_AVIAL_MASK (0x100000UL)
#define MFD_TEST_PORT_DATA_BUF_AVIAL_SHIFT (20UL)
#define MFD_TEST_PORT_DATA_CURRENT_BUF_MASK (0x80000UL)
#define MFD_TEST_PORT_DATA_CURRENT_BUF_SHIFT (19UL)
#define MFD_TEST_PORT_DATA_DBUF_DEPTH_MASK (0x60000UL)
#define MFD_TEST_PORT_DATA_DBUF_DEPTH_SHIFT (17UL)
#define MFD_TEST_PORT_DATA_WSM_TRIG_MASK (0x10000UL)
#define MFD_TEST_PORT_DATA_WSM_TRIG_SHIFT (16UL)
#define MFD_TEST_PORT_DATA_WSM_WR_DONE_MASK (0x8000UL)
#define MFD_TEST_PORT_DATA_WSM_WR_DONE_SHIFT (15UL)
#define MFD_TEST_PORT_DATA_WSM_CUR_STATE_MASK (0x6000UL)
#define MFD_TEST_PORT_DATA_WSM_CUR_STATE_SHIFT (13UL)
#define MFD_TEST_PORT_DATA_LUMA_HORZ_CURSOR_MASK (0x1fffUL)
#define MFD_TEST_PORT_DATA_LUMA_HORZ_CURSOR_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_BUF_READY_MASK (0x20000000UL)
#define MFD_TEST_PORT_DATA_BUF_READY_SHIFT (29UL)
#define MFD_TEST_PORT_DATA_NUM_ACTIVE_PIXEL_MASK (0x1ff80000UL)
#define MFD_TEST_PORT_DATA_NUM_ACTIVE_PIXEL_SHIFT (19UL)
#define MFD_TEST_PORT_DATA_INIT_PIX_OFFSET_MASK (0x78000UL)
#define MFD_TEST_PORT_DATA_INIT_PIX_OFFSET_SHIFT (15UL)
#define MFD_TEST_PORT_DATA_RSM_CUR_STATE_MASK (0x7000UL)
#define MFD_TEST_PORT_DATA_RSM_CUR_STATE_SHIFT (12UL)
#define MFD_TEST_PORT_DATA_DBUF_RD_ON_MASK (0x800UL)
#define MFD_TEST_PORT_DATA_DBUF_RD_ON_SHIFT (11UL)
#define MFD_TEST_PORT_DATA_RD_PIXEL_CNT_MASK (0x7feUL)
#define MFD_TEST_PORT_DATA_RD_PIXEL_CNT_SHIFT (1UL)
#define MFD_TEST_PORT_DATA_BUF_RD_DONE_MASK (0x1UL)
#define MFD_TEST_PORT_DATA_BUF_RD_DONE_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_PICTURE_SYNC_MASK (0xc0000000UL)
#define MFD_TEST_PORT_DATA_PICTURE_SYNC_SHIFT (30UL)
#define MFD_TEST_PORT_DATA_CSM_CUR_STATE_MASK (0x38000000UL)
#define MFD_TEST_PORT_DATA_CSM_CUR_STATE_SHIFT (27UL)
#define MFD_TEST_PORT_DATA_DBUF_WR_ADDR_MASK (0x7e00000UL)
#define MFD_TEST_PORT_DATA_DBUF_WR_ADDR_SHIFT (21UL)
#define MFD_TEST_PORT_DATA_DBUF_RD_ADDR_MASK (0x1f8000UL)
#define MFD_TEST_PORT_DATA_DBUF_RD_ADDR_SHIFT (15UL)
#define MFD_TEST_PORT_DATA_FIRST_BUF_MASK (0x4000UL)
#define MFD_TEST_PORT_DATA_FIRST_BUF_SHIFT (14UL)
#define MFD_TEST_PORT_DATA_LAST_BUF_MASK (0x2000UL)
#define MFD_TEST_PORT_DATA_LAST_BUF_SHIFT (13UL)
#define MFD_TEST_PORT_DATA_PIXEL_STROBE_MASK (0x1000UL)
#define MFD_TEST_PORT_DATA_PIXEL_STROBE_SHIFT (12UL)
#define MFD_TEST_PORT_DATA_CHROMA_PHASE_MASK (0x800UL)
#define MFD_TEST_PORT_DATA_CHROMA_PHASE_SHIFT (11UL)
#define MFD_TEST_PORT_DATA_FIRST_PIXEL_MASK (0x400UL)
#define MFD_TEST_PORT_DATA_FIRST_PIXEL_SHIFT (10UL)
#define MFD_TEST_PORT_DATA_LAST_PIXEL_MASK (0x200UL)
#define MFD_TEST_PORT_DATA_LAST_PIXEL_SHIFT (9UL)
#define MFD_TEST_PORT_DATA_FIRST_LINE_MASK (0x100UL)
#define MFD_TEST_PORT_DATA_FIRST_LINE_SHIFT (8UL)
#define MFD_TEST_PORT_DATA_LAST_LINE_MASK (0x80UL)
#define MFD_TEST_PORT_DATA_LAST_LINE_SHIFT (7UL)
#define MFD_TEST_PORT_DATA_FIFO_FULL_MASK (0x40UL)
#define MFD_TEST_PORT_DATA_FIFO_FULL_SHIFT (6UL)
#define MFD_TEST_PORT_DATA_FIFO_EMPTY_MASK (0x20UL)
#define MFD_TEST_PORT_DATA_FIFO_EMPTY_SHIFT (5UL)
#define MFD_TEST_PORT_DATA_FIFO_DEPTH_CNT_MASK (0x18UL)
#define MFD_TEST_PORT_DATA_FIFO_DEPTH_CNT_SHIFT (3UL)
#define MFD_TEST_PORT_DATA_PIXEL_STOP_MASK (0x4UL)
#define MFD_TEST_PORT_DATA_PIXEL_STOP_SHIFT (2UL)
#define MFD_TEST_PORT_DATA_BVB_EOL_MASK (0x2UL)
#define MFD_TEST_PORT_DATA_BVB_EOL_SHIFT (1UL)
#define MFD_TEST_PORT_DATA_BVB_EOF_MASK (0x1UL)
#define MFD_TEST_PORT_DATA_BVB_EOF_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_BURST_SIZE_MASK (0x7c000000UL)
#define MFD_TEST_PORT_DATA_BURST_SIZE_SHIFT (26UL)
#define MFD_TEST_PORT_DATA_TOP_TAP_SEL_MASK (0x3000000UL)
#define MFD_TEST_PORT_DATA_TOP_TAP_SEL_SHIFT (24UL)
#define MFD_TEST_PORT_DATA_BOT_TAP_SEL_MASK (0xc00000UL)
#define MFD_TEST_PORT_DATA_BOT_TAP_SEL_SHIFT (22UL)
#define MFD_TEST_PORT_DATA_ADDR_A_MASK (0x3ff000UL)
#define MFD_TEST_PORT_DATA_ADDR_A_SHIFT (12UL)
#define MFD_TEST_PORT_DATA_ADDR_B_MASK (0xffcUL)
#define MFD_TEST_PORT_DATA_ADDR_B_SHIFT (2UL)
#define MFD_TEST_PORT_DATA_WR_RDB_A_MASK (0x2UL)
#define MFD_TEST_PORT_DATA_WR_RDB_A_SHIFT (1UL)
#define MFD_TEST_PORT_DATA_WR_RDB_B_MASK (0x1UL)
#define MFD_TEST_PORT_DATA_WR_RDB_B_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_WR_DATA_A_MASK (0xffff0000UL)
#define MFD_TEST_PORT_DATA_WR_DATA_A_SHIFT (16UL)
#define MFD_TEST_PORT_DATA_RD_DATA_B_MASK (0xffffUL)
#define MFD_TEST_PORT_DATA_RD_DATA_B_SHIFT (0UL)
#define MFD_TEST_PORT_DATA_ACCEPT_MASK (0x80000000UL)
#define MFD_TEST_PORT_DATA_ACCEPT_SHIFT (31UL)
#define MFD_TEST_PORT_DATA_READY_MASK (0x40000000UL)
#define MFD_TEST_PORT_DATA_READY_SHIFT (30UL)
#define MFD_TEST_PORT_DATA_LUMA_DATA_MASK (0x3ff00000UL)
#define MFD_TEST_PORT_DATA_LUMA_DATA_SHIFT (20UL)
#define MFD_TEST_PORT_DATA_CHROMA_CB_DATA_MASK (0xffc00UL)
#define MFD_TEST_PORT_DATA_CHROMA_CB_DATA_SHIFT (10UL)
#define MFD_TEST_PORT_DATA_CHROMA_CR_DATA_MASK (0x3ffUL)
#define MFD_TEST_PORT_DATA_CHROMA_CR_DATA_SHIFT (0UL)




typedef uint32_t MFD_SCB_STATUS_TYPE;
#define MFD_SCB_STATUS_SCB2_CLIENT1_INIT_STATUS_MASK (0x20UL)
#define MFD_SCB_STATUS_SCB2_CLIENT1_INIT_STATUS_SHIFT (5UL)
#define MFD_SCB_STATUS_SCB2_CLIENT0_INIT_STATUS_MASK (0x10UL)
#define MFD_SCB_STATUS_SCB2_CLIENT0_INIT_STATUS_SHIFT (4UL)
#define MFD_SCB_STATUS_SCB1_CLIENT1_INIT_STATUS_MASK (0x8UL)
#define MFD_SCB_STATUS_SCB1_CLIENT1_INIT_STATUS_SHIFT (3UL)
#define MFD_SCB_STATUS_SCB1_CLIENT0_INIT_STATUS_MASK (0x4UL)
#define MFD_SCB_STATUS_SCB1_CLIENT0_INIT_STATUS_SHIFT (2UL)
#define MFD_SCB_STATUS_SCB0_CLIENT1_INIT_STATUS_MASK (0x2UL)
#define MFD_SCB_STATUS_SCB0_CLIENT1_INIT_STATUS_SHIFT (1UL)
#define MFD_SCB_STATUS_SCB0_CLIENT0_INIT_STATUS_MASK (0x1UL)
#define MFD_SCB_STATUS_SCB0_CLIENT0_INIT_STATUS_SHIFT (0UL)




typedef uint32_t MFD_DEMO_SETTING_4K_TYPE;
#define MFD_DEMO_SETTING_4K_L_R_MASK (0x10000UL)
#define MFD_DEMO_SETTING_4K_L_R_SHIFT (16UL)
#define MFD_DEMO_SETTING_4K_BOUNDARY_MASK (0x1fffUL)
#define MFD_DEMO_SETTING_4K_BOUNDARY_SHIFT (0UL)




typedef uint8_t MFD_RESERVED_TYPE;




typedef uint32_t MFD_CCA_CONFIG_TYPE;
#define MFD_CCA_CONFIG_CONFIG_MASK (0x3UL)
#define MFD_CCA_CONFIG_CONFIG_SHIFT (0UL)




typedef uint32_t MFD_CRC_CTRL_TYPE;
#define MFD_CRC_CTRL_TYPE_MASK (0x18UL)
#define MFD_CRC_CTRL_TYPE_SHIFT (3UL)
#define MFD_CRC_CTRL_ENABLE_MASK (0x4UL)
#define MFD_CRC_CTRL_ENABLE_SHIFT (2UL)
#define MFD_CRC_CTRL_MODE_MASK (0x2UL)
#define MFD_CRC_CTRL_MODE_SHIFT (1UL)
#define MFD_CRC_CTRL_LOAD_CRC_SEED_MASK (0x1UL)
#define MFD_CRC_CTRL_LOAD_CRC_SEED_SHIFT (0UL)




typedef uint32_t MFD_CRC_SEED_TYPE;
#define MFD_CRC_SEED_VALUE_MASK (0xffffffffUL)
#define MFD_CRC_SEED_VALUE_SHIFT (0UL)




typedef uint32_t MFD_CRC_TYPE;
#define MFD_CRC_VALUE_MASK (0xffffffffUL)
#define MFD_CRC_VALUE_SHIFT (0UL)




typedef uint32_t MFD_MTG_FRAME_SIZE_TYPE;
#define MFD_MTG_FRAME_SIZE_SIZE_MASK (0xffffffUL)
#define MFD_MTG_FRAME_SIZE_SIZE_SHIFT (0UL)




typedef uint32_t MFD_MTG_FORCE_TYPE;
#define MFD_MTG_FORCE_REPEAT_POLARITY_MASK (0x4UL)
#define MFD_MTG_FORCE_REPEAT_POLARITY_SHIFT (2UL)
#define MFD_MTG_FORCE_TRIGGER1_MASK (0x2UL)
#define MFD_MTG_FORCE_TRIGGER1_SHIFT (1UL)
#define MFD_MTG_FORCE_TRIGGER0_MASK (0x1UL)
#define MFD_MTG_FORCE_TRIGGER0_SHIFT (0UL)




typedef uint32_t MFD_MTG_CONTROL_TYPE;
#define MFD_MTG_CONTROL_REPEAT_POLARITY_STATUS_MASK (0x80000000UL)
#define MFD_MTG_CONTROL_REPEAT_POLARITY_STATUS_SHIFT (31UL)
#define MFD_MTG_CONTROL_TIMEBASE_SEL_MASK (0xf0UL)
#define MFD_MTG_CONTROL_TIMEBASE_SEL_SHIFT (4UL)
#define MFD_MTG_CONTROL_SCAN_MODE_MASK (0x2UL)
#define MFD_MTG_CONTROL_SCAN_MODE_SHIFT (1UL)
#define MFD_MTG_CONTROL_ENABLE_MASK (0x1UL)
#define MFD_MTG_CONTROL_ENABLE_SHIFT (0UL)




typedef uint32_t MFD_FORMERLY_SCRATCH_0_TYPE;
#define MFD_FORMERLY_SCRATCH_0_BR_CTRL_MASK (0xfffffff8UL)
#define MFD_FORMERLY_SCRATCH_0_BR_CTRL_SHIFT (3UL)
#define MFD_FORMERLY_SCRATCH_0_LUMA_CHR_BIT_MAP_MASK (0x6UL)
#define MFD_FORMERLY_SCRATCH_0_LUMA_CHR_BIT_MAP_SHIFT (1UL)
#define MFD_FORMERLY_SCRATCH_0_CHR_INT_START_VAL_MASK (0x1UL)
#define MFD_FORMERLY_SCRATCH_0_CHR_INT_START_VAL_SHIFT (0UL)




typedef uint32_t MFD_SCRATCH_TYPE;
#define MFD_SCRATCH_VALUE_MASK (0xffffffffUL)
#define MFD_SCRATCH_VALUE_SHIFT (0UL)




typedef volatile struct COMP_PACKED _MFD_RDBType {
    MFD_REVISION_ID_TYPE revision_id; /* OFFSET: 0x0 */
    MFD_HW_CONFIGURATION_TYPE hw_configuration; /* OFFSET: 0x4 */
    MFD_FEEDER_CNTL_TYPE feeder_cntl; /* OFFSET: 0x8 */
    MFD_LAC_CNTL_TYPE lac_cntl; /* OFFSET: 0xc */
    MFD_FIXED_COLOUR_TYPE fixed_colour; /* OFFSET: 0x10 */
    MFD_STRIDE_TYPE stride; /* OFFSET: 0x14 */
    MFD_DISP_HSIZE_TYPE disp_hsize; /* OFFSET: 0x18 */
    MFD_DISP_VSIZE_TYPE disp_vsize; /* OFFSET: 0x1c */
    MFD_DATA_MODE_TYPE data_mode; /* OFFSET: 0x20 */
    MFD_DITHER_CTRL_TYPE dither_ctrl; /* OFFSET: 0x24 */
    MFD_DITHER_LFSR_INIT_TYPE dither_lfsr_init; /* OFFSET: 0x28 */
    MFD_DITHER_LFSR_CTRL_TYPE dither_lfsr_ctrl; /* OFFSET: 0x2c */
    MFD_COMP_ORDER_TYPE comp_order; /* OFFSET: 0x30 */
    MFD_ADDR_0_TYPE picture0_line_addr_0; /* OFFSET: 0x34 */
    MFD_ADDR_0_TYPE picture0_line_addr_0_r; /* OFFSET: 0x38 */
    MFD_ADDR_1_TYPE picture0_line_addr_1; /* OFFSET: 0x3c */
    MFD_ADDR_1_TYPE picture0_line_addr_1_r; /* OFFSET: 0x40 */
    MFD_ADDR_0_TYPE picture1_line_addr_0; /* OFFSET: 0x44 */
    MFD_ADDR_0_TYPE picture1_line_addr_0_r; /* OFFSET: 0x48 */
    MFD_ADDR_1_TYPE picture1_line_addr_1; /* OFFSET: 0x4c */
    MFD_ADDR_1_TYPE picture1_line_addr_1_r; /* OFFSET: 0x50 */
    MFD_LUMA_NMBY_TYPE luma_nmby; /* OFFSET: 0x54 */
    MFD_CHROMA_NMBY_TYPE chroma_nmby; /* OFFSET: 0x58 */
    MFD_PIC_OFFSET_TYPE pic_offset; /* OFFSET: 0x5c */
    MFD_RANGE_EXP_REMAP_CNTL_TYPE range_exp_remap_cntl; /* OFFSET: 0x60 */
    MFD_CHROMA_SAMPLING_CNTL_TYPE chroma_sampling_cntl; /* OFFSET: 0x64 */
    MFD_DERING_ENABLE_TYPE chroma_reposition_dering_enable; /* OFFSET: 0x68 */
    MFD_PIC_FEED_CMD_TYPE pic_feed_cmd; /* OFFSET: 0x6c */
    MFD_FEED_STATUS_TYPE feed_status; /* OFFSET: 0x70 */
    MFD_LAC_ADDR_0_TYPE lac_line_addr_0_status; /* OFFSET: 0x74 */
    MFD_LAC_ADDR_1_TYPE lac_line_addr_1_status; /* OFFSET: 0x78 */
    MFD_LAC_CHROMA_VERT_FILTER_STATUS_TYPE picture0_lac_chroma_vert_filter_status; /* OFFSET: 0x7c */
    MFD_LINE_FEED_STATUS_TYPE line_feed_status; /* OFFSET: 0x80 */
    MFD_FEEDER_TIMEOUT_REPEAT_PIC_CNTL_TYPE feeder_timeout_repeat_pic_cntl; /* OFFSET: 0x84 */
    MFD_BVB_RX_STALL_TIMEOUT_CNTL_TYPE bvb_rx_stall_timeout_cntl; /* OFFSET: 0x88 */
    MFD_FEEDER_ERROR_INTERRUPT_STATUS_TYPE feeder_error_interrupt_status; /* OFFSET: 0x8c */
    MFD_FEISC_TYPE feeder_error_interrupt_status_clr; /* OFFSET: 0x90 */
    MFD_FEEDER_BVB_STATUS_TYPE feeder_bvb_status; /* OFFSET: 0x94 */
    MFD_FEEDER_BVB_STATUS_CLR_TYPE feeder_bvb_status_clr; /* OFFSET: 0x98 */
    MFD_TEST_MODE_CNTL_TYPE test_mode_cntl; /* OFFSET: 0x9c */
    MFD_BVB_SAMPLE_DATA_TYPE bvb_sample_data; /* OFFSET: 0xa0 */
    MFD_TEST_PORT_CNTL_TYPE test_port_cntl; /* OFFSET: 0xa4 */
    MFD_TEST_PORT_DATA_TYPE test_port_data; /* OFFSET: 0xa8 */
    MFD_SCB_STATUS_TYPE scb_status; /* OFFSET: 0xac */
    MFD_DEMO_SETTING_4K_TYPE demo_setting; /* OFFSET: 0xb0 */
    MFD_RESERVED_TYPE rsvd0[260]; /* OFFSET: 0xb4 */
    MFD_CCA_CONFIG_TYPE cca_config; /* OFFSET: 0x1b8 */
    MFD_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x1bc */
    MFD_CRC_CTRL_TYPE crc_ctrl; /* OFFSET: 0x1c0 */
    MFD_CRC_SEED_TYPE crc_seed; /* OFFSET: 0x1c4 */
    MFD_CRC_TYPE luma_crc; /* OFFSET: 0x1c8 */
    MFD_CRC_TYPE chroma_crc; /* OFFSET: 0x1cc */
    MFD_CRC_TYPE chroma_1_crc; /* OFFSET: 0x1d0 */
    MFD_CRC_TYPE luma_crc_r; /* OFFSET: 0x1d4 */
    MFD_CRC_TYPE chroma_crc_r; /* OFFSET: 0x1d8 */
    MFD_CRC_TYPE chroma_1_crc_r; /* OFFSET: 0x1dc */
    MFD_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x1e0 */
    MFD_MTG_FRAME_SIZE_TYPE mtg_frame_size; /* OFFSET: 0x1ec */
    MFD_MTG_FORCE_TYPE mtg_force; /* OFFSET: 0x1f0 */
    MFD_MTG_CONTROL_TYPE mtg_control; /* OFFSET: 0x1f4 */
    MFD_FORMERLY_SCRATCH_0_TYPE scratch_register_0; /* OFFSET: 0x1f8 */
    MFD_SCRATCH_TYPE scratch_register_1; /* OFFSET: 0x1fc */
} MFD_RDBType;


#define MFD_0_BASE                      (0x400A0000UL)



#define MFD_MAX_HW_ID                   (1UL)


#define MFD_ERR_INTSTAT_RESERVED0_MASK  (0xfffffff8UL)


#define MFD_FEEDER_CNTL_BOT_INIT_PHASE_16  (0x00000010UL)


#define MFD_FEEDER_CNTL_MEM_VID_MODE_2D  (0UL)


#define MFD_FEEDER_CNTL_BVB_VID_MODE_2D  (0UL)


#define MFD_FEEDER_CNTL_IMG_FMT_AVC_MPEG  (0UL)


#define MFD_FEEDER_CNTL_TOP_INIT_PHASE_112  (0x00000070UL)


#define MFD_FEEDER_CNTL_IMG_FMT_SHIFT   (0UL)


#define MFD_LAC_CNTL_CR_TYPE_CHROMA_422  (1UL)


#define MFD_LAC_CNTL_CR_TYPE_SHIFT      (0UL)


#define MFD_LAC_CNTL_O_TYPE_PROGRESSIVE  (1UL)


#define MFD_LAC_CNTL_CR_INTERPOLATION_FRAME  (1UL)


#define MFD_LAC_CNTL_STRIPE_WIDTH_SEL_128  (1UL)


#define MFD_LUMA_NMBY_VALUE_36          (0x00000024UL)


#define MFD_CHROMA_NMBY_VALUE_20        (0x00000014UL)


#define MFD_VGC_ORDER_COMP_3_SEL_CB     (0UL)


#define MFD_VGC_ORDER_COMP_2_SEL_Y0     (1UL)


#define MFD_VGC_ORDER_COMP_1_SEL_CR     (2UL)


#define MFD_VGC_ORDER_COMP_0_SEL_Y1     (3UL)

#endif /* MFD_RDB_H */
