/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file pp_irq_rdb.h
    @brief RDB File for PP_IRQ

    @version 2018May25_rdb
*/

#ifndef PP_IRQ_RDB_H
#define PP_IRQ_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t PP_IRQ_GP_IRQ_STATUS_TYPE;
#define PP_IRQ_GP_IRQ_STATUS_STAT_SP_1_MASK (0x200000UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_SP_1_SHIFT (21UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_SP_0_MASK (0x100000UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_SP_0_SHIFT (20UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_7_MASK (0x80UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_7_SHIFT (7UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_6_MASK (0x40UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_6_SHIFT (6UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_5_MASK (0x20UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_5_SHIFT (5UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_4_MASK (0x10UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_4_SHIFT (4UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_3_MASK (0x8UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_3_SHIFT (3UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_2_MASK (0x4UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_2_SHIFT (2UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_1_MASK (0x2UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_1_SHIFT (1UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_0_MASK (0x1UL)
#define PP_IRQ_GP_IRQ_STATUS_STAT_MP_0_SHIFT (0UL)




typedef uint8_t PP_IRQ_RESERVED_TYPE;




typedef uint32_t PP_IRQ_GP_IRQ_MASK_TYPE;
#define PP_IRQ_GP_IRQ_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_GP_IRQ_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_GP_IRQ_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_GP_IRQ_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_GP_IRQ_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_GP_IRQ_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_GP_IRQ_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_GP_IRQ_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_GP_IRQ_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_GP_IRQ_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_GP_IRQ_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_GP_IRQ_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_GP_IRQ_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_GP_IRQ_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_GP_IRQ_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_GP_IRQ_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_GP_IRQ_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_GP_IRQ_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_GP_IRQ_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_GP_IRQ_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_GP_IRQ_SET_EN_TYPE;
#define PP_IRQ_GP_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_GP_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_GP_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_GP_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_NC_IRQ_STATUS_TYPE;
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_NC_IRQ_STATUS_STAT_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_NC_IRQ_CLEAR_TYPE;
#define PP_IRQ_ECC_NC_IRQ_CLEAR_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_NC_IRQ_MASK_TYPE;
#define PP_IRQ_ECC_NC_IRQ_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_NC_IRQ_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_NC_IRQ_SET_EN_TYPE;
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_NC_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_NC_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_NC_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_NC_IRQ_SET_TYPE;
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_NC_IRQ_SET_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_C_IRQ_STATUS_TYPE;
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_C_IRQ_STATUS_STAT_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_C_IRQ_CLEAR_TYPE;
#define PP_IRQ_ECC_C_IRQ_CLEAR_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_C_IRQ_MASK_TYPE;
#define PP_IRQ_ECC_C_IRQ_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_C_IRQ_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_C_IRQ_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_C_IRQ_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_C_IRQ_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_C_IRQ_SET_EN_TYPE;
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_C_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_C_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_C_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ECC_C_IRQ_SET_TYPE;
#define PP_IRQ_ECC_C_IRQ_SET_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ECC_C_IRQ_SET_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_BUS_ERR_IRQ_STATUS_TYPE;
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_SP_1_MASK (0x200000UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_SP_1_SHIFT (21UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_SP_0_MASK (0x100000UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_SP_0_SHIFT (20UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_7_MASK (0x80UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_7_SHIFT (7UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_6_MASK (0x40UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_6_SHIFT (6UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_5_MASK (0x20UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_5_SHIFT (5UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_4_MASK (0x10UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_4_SHIFT (4UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_3_MASK (0x8UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_3_SHIFT (3UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_2_MASK (0x4UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_2_SHIFT (2UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_1_MASK (0x2UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_1_SHIFT (1UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_0_MASK (0x1UL)
#define PP_IRQ_BUS_ERR_IRQ_STATUS_STAT_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_BUS_ERR_IRQ_CLEAR_TYPE;
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_SP_1_MASK (0x200000UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_SP_1_SHIFT (21UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_SP_0_MASK (0x100000UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_SP_0_SHIFT (20UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_7_MASK (0x80UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_7_SHIFT (7UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_6_MASK (0x40UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_6_SHIFT (6UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_5_MASK (0x20UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_5_SHIFT (5UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_4_MASK (0x10UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_4_SHIFT (4UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_3_MASK (0x8UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_3_SHIFT (3UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_2_MASK (0x4UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_2_SHIFT (2UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_1_MASK (0x2UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_1_SHIFT (1UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_0_MASK (0x1UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_BUS_ERR_IRQ_MASK_TYPE;
#define PP_IRQ_BUS_ERR_IRQ_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_BUS_ERR_IRQ_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_BUS_ERR_IRQ_SET_EN_TYPE;
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_BUS_ERR_IRQ_SET_TYPE;
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_BUS_ERR_IRQ_SET_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_WD_IRQ_STATUS_TYPE;
#define PP_IRQ_WD_IRQ_STATUS_STAT_SP_1_MASK (0x200000UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_SP_1_SHIFT (21UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_SP_0_MASK (0x100000UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_SP_0_SHIFT (20UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_7_MASK (0x80UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_7_SHIFT (7UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_6_MASK (0x40UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_6_SHIFT (6UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_5_MASK (0x20UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_5_SHIFT (5UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_4_MASK (0x10UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_4_SHIFT (4UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_3_MASK (0x8UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_3_SHIFT (3UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_2_MASK (0x4UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_2_SHIFT (2UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_1_MASK (0x2UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_1_SHIFT (1UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_0_MASK (0x1UL)
#define PP_IRQ_WD_IRQ_STATUS_STAT_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_WD_IRQ_MASK_TYPE;
#define PP_IRQ_WD_IRQ_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_WD_IRQ_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_WD_IRQ_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_WD_IRQ_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_WD_IRQ_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_WD_IRQ_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_WD_IRQ_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_WD_IRQ_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_WD_IRQ_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_WD_IRQ_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_WD_IRQ_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_WD_IRQ_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_WD_IRQ_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_WD_IRQ_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_WD_IRQ_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_WD_IRQ_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_WD_IRQ_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_WD_IRQ_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_WD_IRQ_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_WD_IRQ_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_WD_IRQ_SET_EN_TYPE;
#define PP_IRQ_WD_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_WD_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_WD_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_WD_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP0_IRQ_STATUS_TYPE;
#define PP_IRQ_ISP0_IRQ_STATUS_STAT_ISP_MASK (0x1UL)
#define PP_IRQ_ISP0_IRQ_STATUS_STAT_ISP_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP0_IRQ_BMASK_TYPE;
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ISP0_IRQ_BMASK_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP0_IRQ_SET_EN_TYPE;
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ISP0_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP0_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ISP0_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP1_IRQ_STATUS_TYPE;
#define PP_IRQ_ISP1_IRQ_STATUS_STAT_ISP_MASK (0x1UL)
#define PP_IRQ_ISP1_IRQ_STATUS_STAT_ISP_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP1_IRQ_BMASK_TYPE;
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ISP1_IRQ_BMASK_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP1_IRQ_SET_EN_TYPE;
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ISP1_IRQ_SET_EN_MASK_MP_0_SHIFT (0UL)




typedef uint32_t PP_IRQ_ISP1_IRQ_CLEAR_EN_TYPE;
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_SP_1_MASK (0x200000UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_SP_1_SHIFT (21UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_SP_0_MASK (0x100000UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_SP_0_SHIFT (20UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_7_MASK (0x80UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_7_SHIFT (7UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_6_MASK (0x40UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_6_SHIFT (6UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_5_MASK (0x20UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_5_SHIFT (5UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_4_MASK (0x10UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_4_SHIFT (4UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_3_MASK (0x8UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_3_SHIFT (3UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_2_MASK (0x4UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_2_SHIFT (2UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_1_MASK (0x2UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_1_SHIFT (1UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_0_MASK (0x1UL)
#define PP_IRQ_ISP1_IRQ_CLEAR_EN_MASK_MP_0_SHIFT (0UL)


typedef volatile struct COMP_PACKED _PP_IRQ_ISPTYPE {
    PP_IRQ_ISP0_IRQ_STATUS_TYPE isp0_status; /* OFFSET: 0x100 */
    PP_IRQ_RESERVED_TYPE rsvd26[4]; /* OFFSET: 0x104 */
    PP_IRQ_ISP0_IRQ_BMASK_TYPE isp0_bmask; /* OFFSET: 0x108 */
    PP_IRQ_RESERVED_TYPE rsvd27[4]; /* OFFSET: 0x10c */
    PP_IRQ_ISP0_IRQ_SET_EN_TYPE isp0_set_en; /* OFFSET: 0x110 */
    PP_IRQ_RESERVED_TYPE rsvd28[4]; /* OFFSET: 0x114 */
    PP_IRQ_ISP0_IRQ_CLEAR_EN_TYPE isp0_clear_en; /* OFFSET: 0x118 */
    PP_IRQ_RESERVED_TYPE rsvd29[4]; /* OFFSET: 0x11c */
} PP_IRQ_ISPTYPE;



typedef volatile struct COMP_PACKED _PP_IRQ_RDBType {
    PP_IRQ_GP_IRQ_STATUS_TYPE gp_status; /* OFFSET: 0x0 */
    PP_IRQ_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x4 */
    PP_IRQ_GP_IRQ_MASK_TYPE gp_mask; /* OFFSET: 0x8 */
    PP_IRQ_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0xc */
    PP_IRQ_GP_IRQ_SET_EN_TYPE gp_set_en; /* OFFSET: 0x10 */
    PP_IRQ_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x14 */
    PP_IRQ_GP_IRQ_CLEAR_EN_TYPE gp_clear_en; /* OFFSET: 0x18 */
    PP_IRQ_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x1c */
    PP_IRQ_ECC_NC_IRQ_STATUS_TYPE ecc_nc_status; /* OFFSET: 0x20 */
    PP_IRQ_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x24 */
    PP_IRQ_ECC_NC_IRQ_CLEAR_TYPE ecc_nc_clear; /* OFFSET: 0x28 */
    PP_IRQ_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0x2c */
    PP_IRQ_ECC_NC_IRQ_MASK_TYPE ecc_nc_mask; /* OFFSET: 0x30 */
    PP_IRQ_RESERVED_TYPE rsvd6[4]; /* OFFSET: 0x34 */
    PP_IRQ_ECC_NC_IRQ_SET_EN_TYPE ecc_nc_set_en; /* OFFSET: 0x38 */
    PP_IRQ_RESERVED_TYPE rsvd7[4]; /* OFFSET: 0x3c */
    PP_IRQ_ECC_NC_IRQ_CLEAR_EN_TYPE ecc_nc_clear_en; /* OFFSET: 0x40 */
    PP_IRQ_RESERVED_TYPE rsvd8[4]; /* OFFSET: 0x44 */
    PP_IRQ_ECC_NC_IRQ_SET_TYPE ecc_nc_set; /* OFFSET: 0x48 */
    PP_IRQ_RESERVED_TYPE rsvd9[4]; /* OFFSET: 0x4c */
    PP_IRQ_ECC_C_IRQ_STATUS_TYPE ecc_c_status; /* OFFSET: 0x50 */
    PP_IRQ_RESERVED_TYPE rsvd10[4]; /* OFFSET: 0x54 */
    PP_IRQ_ECC_C_IRQ_CLEAR_TYPE ecc_c_clear; /* OFFSET: 0x58 */
    PP_IRQ_RESERVED_TYPE rsvd11[4]; /* OFFSET: 0x5c */
    PP_IRQ_ECC_C_IRQ_MASK_TYPE ecc_c_mask; /* OFFSET: 0x60 */
    PP_IRQ_RESERVED_TYPE rsvd12[4]; /* OFFSET: 0x64 */
    PP_IRQ_ECC_C_IRQ_SET_EN_TYPE ecc_c_set_en; /* OFFSET: 0x68 */
    PP_IRQ_RESERVED_TYPE rsvd13[4]; /* OFFSET: 0x6c */
    PP_IRQ_ECC_C_IRQ_CLEAR_EN_TYPE ecc_c_clear_en; /* OFFSET: 0x70 */
    PP_IRQ_RESERVED_TYPE rsvd14[4]; /* OFFSET: 0x74 */
    PP_IRQ_ECC_C_IRQ_SET_TYPE ecc_c_set; /* OFFSET: 0x78 */
    PP_IRQ_RESERVED_TYPE rsvd15[4]; /* OFFSET: 0x7c */
    PP_IRQ_BUS_ERR_IRQ_STATUS_TYPE bus_err_status; /* OFFSET: 0x80 */
    PP_IRQ_RESERVED_TYPE rsvd16[4]; /* OFFSET: 0x84 */
    PP_IRQ_BUS_ERR_IRQ_CLEAR_TYPE bus_err_clear; /* OFFSET: 0x88 */
    PP_IRQ_RESERVED_TYPE rsvd17[4]; /* OFFSET: 0x8c */
    PP_IRQ_BUS_ERR_IRQ_MASK_TYPE bus_err_mask; /* OFFSET: 0x90 */
    PP_IRQ_RESERVED_TYPE rsvd18[4]; /* OFFSET: 0x94 */
    PP_IRQ_BUS_ERR_IRQ_SET_EN_TYPE bus_err_set_en; /* OFFSET: 0x98 */
    PP_IRQ_RESERVED_TYPE rsvd19[4]; /* OFFSET: 0x9c */
    PP_IRQ_BUS_ERR_IRQ_CLEAR_EN_TYPE bus_err_clear_en; /* OFFSET: 0xa0 */
    PP_IRQ_RESERVED_TYPE rsvd20[4]; /* OFFSET: 0xa4 */
    PP_IRQ_BUS_ERR_IRQ_SET_TYPE bus_err_set; /* OFFSET: 0xa8 */
    PP_IRQ_RESERVED_TYPE rsvd21[4]; /* OFFSET: 0xac */
    PP_IRQ_WD_IRQ_STATUS_TYPE wd_status; /* OFFSET: 0xb0 */
    PP_IRQ_RESERVED_TYPE rsvd22[4]; /* OFFSET: 0xb4 */
    PP_IRQ_WD_IRQ_MASK_TYPE wd_mask; /* OFFSET: 0xb8 */
    PP_IRQ_RESERVED_TYPE rsvd23[4]; /* OFFSET: 0xbc */
    PP_IRQ_WD_IRQ_SET_EN_TYPE wd_set_en; /* OFFSET: 0xc0 */
    PP_IRQ_RESERVED_TYPE rsvd24[4]; /* OFFSET: 0xc4 */
    PP_IRQ_WD_IRQ_CLEAR_EN_TYPE wd_clear_en; /* OFFSET: 0xc8 */
    PP_IRQ_RESERVED_TYPE rsvd25[52]; /* OFFSET: 0xcc */
    PP_IRQ_ISPTYPE isp[2]; /* OFFSET: 0x100 */
} PP_IRQ_RDBType;


#define PP_IRQ_BASE                     (0xE023F000UL)

#define PP_IRQ_ISPTYPE_OFFSET           (0xe023f100UL)



#define PP_IRQ_MAX_HW_ID                (1UL)

#endif /* PP_IRQ_RDB_H */
