/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file pp_vmp_rdb.h
    @brief RDB File for PP_VMP

    @version 2018May25_rdb
*/

#ifndef PP_VMP_RDB_H
#define PP_VMP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t PP_VMP_RESERVED_TYPE;




typedef uint32_t PP_VMP_GPDATA0_TYPE;
#define PP_VMP_GPDATA0_GPDATA0_MASK (0xffffffffUL)
#define PP_VMP_GPDATA0_GPDATA0_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA1_TYPE;
#define PP_VMP_GPDATA1_GPDATA1_MASK (0xffffffffUL)
#define PP_VMP_GPDATA1_GPDATA1_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA2_TYPE;
#define PP_VMP_GPDATA2_GPDATA2_MASK (0xfUL)
#define PP_VMP_GPDATA2_GPDATA2_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA3_TYPE;
#define PP_VMP_GPDATA3_GPDATA3_MASK (0xfUL)
#define PP_VMP_GPDATA3_GPDATA3_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA4_TYPE;
#define PP_VMP_GPDATA4_GPDATA4_MASK (0xfUL)
#define PP_VMP_GPDATA4_GPDATA4_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA5_TYPE;
#define PP_VMP_GPDATA5_GPDATA5_MASK (0xfUL)
#define PP_VMP_GPDATA5_GPDATA5_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA6_TYPE;
#define PP_VMP_GPDATA6_GPDATA6_MASK (0xfUL)
#define PP_VMP_GPDATA6_GPDATA6_SHIFT (0UL)




typedef uint32_t PP_VMP_GPDATA7_TYPE;
#define PP_VMP_GPDATA7_GPDATA7_MASK (0xfUL)
#define PP_VMP_GPDATA7_GPDATA7_SHIFT (0UL)




typedef uint32_t PP_VMP_IRQOUT_TYPE;
#define PP_VMP_IRQOUT_IRQ_MASK (0x1UL)
#define PP_VMP_IRQOUT_IRQ_SHIFT (0UL)




typedef uint32_t PP_VMP_IRQIN_TYPE;
#define PP_VMP_IRQIN_IRQ_MASK (0x1UL)
#define PP_VMP_IRQIN_IRQ_SHIFT (0UL)




typedef uint32_t PP_VMP_INSTR_LEFT_TYPE;
#define PP_VMP_INSTR_LEFT_LEFT_MASK (0xffffffffUL)
#define PP_VMP_INSTR_LEFT_LEFT_SHIFT (0UL)




typedef uint32_t PP_VMP_INSTR_RIGHT_TYPE;
#define PP_VMP_INSTR_RIGHT_RIGHT_MASK (0xffffffffUL)
#define PP_VMP_INSTR_RIGHT_RIGHT_SHIFT (0UL)




typedef uint32_t PP_VMP_PC_TYPE;
#define PP_VMP_PC_PC_MASK (0xffffffffUL)
#define PP_VMP_PC_PC_SHIFT (0UL)




typedef uint32_t PP_VMP_STATE_TYPE;
#define PP_VMP_STATE_MP_STATE_MASK (0x7UL)
#define PP_VMP_STATE_MP_STATE_SHIFT (0UL)




typedef uint32_t PP_VMP_BP_ADDR_TYPE;
#define PP_VMP_BP_ADDR_ADDR_MASK (0xfffUL)
#define PP_VMP_BP_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t PP_VMP_BP_CTRL_TYPE;
#define PP_VMP_BP_CTRL_CTRL_MASK (0x1UL)
#define PP_VMP_BP_CTRL_CTRL_SHIFT (0UL)




typedef uint32_t PP_VMP_BOOT_ADDR_TYPE;
#define PP_VMP_BOOT_ADDR_ADDR_MASK (0xffffffffUL)
#define PP_VMP_BOOT_ADDR_ADDR_SHIFT (0UL)




typedef uint32_t PP_VMP_CORE_CTRL_TYPE;
#define PP_VMP_CORE_CTRL_CORE_CLK_DISABLE_MASK (0x8UL)
#define PP_VMP_CORE_CTRL_CORE_CLK_DISABLE_SHIFT (3UL)
#define PP_VMP_CORE_CTRL_RESET_N_MASK (0x1UL)
#define PP_VMP_CORE_CTRL_RESET_N_SHIFT (0UL)




typedef uint32_t PP_VMP_TEST_AND_SET_0_TYPE;
#define PP_VMP_TEST_AND_SET_0_0_MASK (0x1UL)
#define PP_VMP_TEST_AND_SET_0_0_SHIFT (0UL)




typedef uint32_t PP_VMP_TEST_AND_SET_1_TYPE;
#define PP_VMP_TEST_AND_SET_1_1_MASK (0x1UL)
#define PP_VMP_TEST_AND_SET_1_1_SHIFT (0UL)




typedef uint32_t PP_VMP_ECC_IMEM_CNT_TYPE;
#define PP_VMP_ECC_IMEM_CNT_CNT_MASK (0xfUL)
#define PP_VMP_ECC_IMEM_CNT_CNT_SHIFT (0UL)




typedef uint32_t PP_VMP_SRAM_CTRL_MP_GEN_TYPE;
#define PP_VMP_SRAM_CTRL_MP_GEN_TM_SRF_MASK (0x1f00UL)
#define PP_VMP_SRAM_CTRL_MP_GEN_TM_SRF_SHIFT (8UL)
#define PP_VMP_SRAM_CTRL_MP_GEN_TM_SP_MASK (0x7fUL)
#define PP_VMP_SRAM_CTRL_MP_GEN_TM_SP_SHIFT (0UL)




typedef uint32_t PP_VMP_SRAM_CTRL_MP_IMEM_TYPE;
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_7_MASK (0xf0000000UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_7_SHIFT (28UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_6_MASK (0xf000000UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_6_SHIFT (24UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_5_MASK (0xf00000UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_5_SHIFT (20UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_4_MASK (0xf0000UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_4_SHIFT (16UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_3_MASK (0xf000UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_3_SHIFT (12UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_2_MASK (0xf00UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_2_SHIFT (8UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_1_MASK (0xf0UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_1_SHIFT (4UL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_0_MASK (0xfUL)
#define PP_VMP_SRAM_CTRL_MP_IMEM_PWR_0_SHIFT (0UL)




typedef uint32_t PP_VMP_SRAM_CTRL_MP_DMEM_TYPE;
#define PP_VMP_SRAM_CTRL_MP_DMEM_PWR_D2_MASK (0xf00UL)
#define PP_VMP_SRAM_CTRL_MP_DMEM_PWR_D2_SHIFT (8UL)
#define PP_VMP_SRAM_CTRL_MP_DMEM_PWR_D_1_MASK (0xf0UL)
#define PP_VMP_SRAM_CTRL_MP_DMEM_PWR_D_1_SHIFT (4UL)
#define PP_VMP_SRAM_CTRL_MP_DMEM_PWR_D_0_MASK (0xfUL)
#define PP_VMP_SRAM_CTRL_MP_DMEM_PWR_D_0_SHIFT (0UL)




typedef uint32_t PP_VMP_SRAM_CTRL_MP_PO_TYPE;
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_D2_MASK (0x200000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_D2_SHIFT (21UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_D2_MASK (0x100000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_D2_SHIFT (20UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_D_1_MASK (0x80000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_D_1_SHIFT (19UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_D_1_MASK (0x40000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_D_1_SHIFT (18UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_D_0_MASK (0x20000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_D_0_SHIFT (17UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_D_0_MASK (0x10000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_D_0_SHIFT (16UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_7_MASK (0x8000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_7_SHIFT (15UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_7_MASK (0x4000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_7_SHIFT (14UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_6_MASK (0x2000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_6_SHIFT (13UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_6_MASK (0x1000UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_6_SHIFT (12UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_5_MASK (0x800UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_5_SHIFT (11UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_5_MASK (0x400UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_5_SHIFT (10UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_4_MASK (0x200UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_4_SHIFT (9UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_4_MASK (0x100UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_4_SHIFT (8UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_3_MASK (0x80UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_3_SHIFT (7UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_3_MASK (0x40UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_3_SHIFT (6UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_2_MASK (0x20UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_2_SHIFT (5UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_2_MASK (0x10UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_2_SHIFT (4UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_1_MASK (0x8UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_1_SHIFT (3UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_1_MASK (0x4UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_1_SHIFT (2UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_0_MASK (0x2UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWEROKOUT_I_0_SHIFT (1UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_0_MASK (0x1UL)
#define PP_VMP_SRAM_CTRL_MP_PO_POWERONOUT_I_0_SHIFT (0UL)


typedef volatile struct COMP_PACKED _PP_VMP_GPDATATYPE {
    PP_VMP_GPDATA0_TYPE gpdata0; /* OFFSET: 0x4 */
    PP_VMP_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x8 */
} PP_VMP_GPDATATYPE;

typedef volatile struct COMP_PACKED _PP_VMP_SEM0Type {
    PP_VMP_TEST_AND_SET_0_TYPE test_and_set_0; /* OFFSET: 0x220 */
} PP_VMP_SEM0Type;

typedef volatile struct COMP_PACKED _PP_VMP_SEM1Type {
    PP_VMP_TEST_AND_SET_1_TYPE test_and_set_1; /* OFFSET: 0x240 */
} PP_VMP_SEM1Type;



typedef volatile struct COMP_PACKED _PP_VMP_RDBType {
    PP_VMP_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x0 */
    PP_VMP_GPDATATYPE gpdata[8]; /* OFFSET: 0x4 */
    PP_VMP_RESERVED_TYPE rsvd8[64]; /* OFFSET: 0x44 */
    PP_VMP_IRQOUT_TYPE irqout; /* OFFSET: 0x84 */
    PP_VMP_RESERVED_TYPE rsvd9[4]; /* OFFSET: 0x88 */
    PP_VMP_IRQIN_TYPE irqin; /* OFFSET: 0x8c */
    PP_VMP_RESERVED_TYPE rsvd10[52]; /* OFFSET: 0x90 */
    PP_VMP_INSTR_LEFT_TYPE instr_left; /* OFFSET: 0xc4 */
    PP_VMP_RESERVED_TYPE rsvd11[4]; /* OFFSET: 0xc8 */
    PP_VMP_INSTR_RIGHT_TYPE instr_right; /* OFFSET: 0xcc */
    PP_VMP_RESERVED_TYPE rsvd12[4]; /* OFFSET: 0xd0 */
    PP_VMP_PC_TYPE pc; /* OFFSET: 0xd4 */
    PP_VMP_RESERVED_TYPE rsvd13[4]; /* OFFSET: 0xd8 */
    PP_VMP_STATE_TYPE mp_state; /* OFFSET: 0xdc */
    PP_VMP_RESERVED_TYPE rsvd14[4]; /* OFFSET: 0xe0 */
    PP_VMP_BP_ADDR_TYPE bp_addr; /* OFFSET: 0xe4 */
    PP_VMP_RESERVED_TYPE rsvd15[4]; /* OFFSET: 0xe8 */
    PP_VMP_BP_CTRL_TYPE bp_ctrl; /* OFFSET: 0xec */
    PP_VMP_RESERVED_TYPE rsvd16[272]; /* OFFSET: 0xf0 */
    PP_VMP_BOOT_ADDR_TYPE boot_addr; /* OFFSET: 0x200 */
    PP_VMP_RESERVED_TYPE rsvd17[4]; /* OFFSET: 0x204 */
    PP_VMP_CORE_CTRL_TYPE core_ctrl; /* OFFSET: 0x208 */
    PP_VMP_RESERVED_TYPE rsvd18[20]; /* OFFSET: 0x20c */
    PP_VMP_SEM0Type sem0; /* OFFSET: 0x220 */
    PP_VMP_RESERVED_TYPE rsvd19[28]; /* OFFSET: 0x224 */
    PP_VMP_SEM1Type sem1; /* OFFSET: 0x240 */
    PP_VMP_RESERVED_TYPE rsvd20[188]; /* OFFSET: 0x244 */
    PP_VMP_ECC_IMEM_CNT_TYPE ecc_imem_cnt; /* OFFSET: 0x300 */
    PP_VMP_RESERVED_TYPE rsvd21[4]; /* OFFSET: 0x304 */
    PP_VMP_SRAM_CTRL_MP_GEN_TYPE sram_ctrl_mp_gen; /* OFFSET: 0x308 */
    PP_VMP_RESERVED_TYPE rsvd22[4]; /* OFFSET: 0x30c */
    PP_VMP_SRAM_CTRL_MP_IMEM_TYPE sram_ctrl_mp_imem; /* OFFSET: 0x310 */
    PP_VMP_RESERVED_TYPE rsvd23[4]; /* OFFSET: 0x314 */
    PP_VMP_SRAM_CTRL_MP_DMEM_TYPE sram_ctrl_mp_dmem; /* OFFSET: 0x318 */
    PP_VMP_RESERVED_TYPE rsvd24[4]; /* OFFSET: 0x31c */
    PP_VMP_SRAM_CTRL_MP_PO_TYPE sram_ctrl_mp_po; /* OFFSET: 0x320 */
} PP_VMP_RDBType;


#define MP0_BASE                        (0xE0220000UL)

#define PP_VMP_GPDATATYPE_MP0_OFFSET    (0xe0220004UL)

#define PP_VMP_SEM0TYPE_MP0_OFFSET      (0xe0220220UL)

#define PP_VMP_SEM1TYPE_MP0_OFFSET      (0xe0220240UL)

#define MP1_BASE                        (0xE0221000UL)

#define PP_VMP_GPDATATYPE_MP1_OFFSET    (0xe0221004UL)

#define PP_VMP_SEM0TYPE_MP1_OFFSET      (0xe0221220UL)

#define PP_VMP_SEM1TYPE_MP1_OFFSET      (0xe0221240UL)

#define MP2_BASE                        (0xE0222000UL)

#define PP_VMP_GPDATATYPE_MP2_OFFSET    (0xe0222004UL)

#define PP_VMP_SEM0TYPE_MP2_OFFSET      (0xe0222220UL)

#define PP_VMP_SEM1TYPE_MP2_OFFSET      (0xe0222240UL)

#define MP3_BASE                        (0xE0223000UL)

#define PP_VMP_GPDATATYPE_MP3_OFFSET    (0xe0223004UL)

#define PP_VMP_SEM0TYPE_MP3_OFFSET      (0xe0223220UL)

#define PP_VMP_SEM1TYPE_MP3_OFFSET      (0xe0223240UL)

#define MP4_BASE                        (0xE0224000UL)

#define PP_VMP_GPDATATYPE_MP4_OFFSET    (0xe0224004UL)

#define PP_VMP_SEM0TYPE_MP4_OFFSET      (0xe0224220UL)

#define PP_VMP_SEM1TYPE_MP4_OFFSET      (0xe0224240UL)

#define MP5_BASE                        (0xE0225000UL)

#define PP_VMP_GPDATATYPE_MP5_OFFSET    (0xe0225004UL)

#define PP_VMP_SEM0TYPE_MP5_OFFSET      (0xe0225220UL)

#define PP_VMP_SEM1TYPE_MP5_OFFSET      (0xe0225240UL)

#define MP6_BASE                        (0xE0226000UL)

#define PP_VMP_GPDATATYPE_MP6_OFFSET    (0xe0226004UL)

#define PP_VMP_SEM0TYPE_MP6_OFFSET      (0xe0226220UL)

#define PP_VMP_SEM1TYPE_MP6_OFFSET      (0xe0226240UL)

#define MP7_BASE                        (0xE0227000UL)

#define PP_VMP_GPDATATYPE_MP7_OFFSET    (0xe0227004UL)

#define PP_VMP_SEM0TYPE_MP7_OFFSET      (0xe0227220UL)

#define PP_VMP_SEM1TYPE_MP7_OFFSET      (0xe0227240UL)



#define PP_VMP_MAX_HW_ID                (8UL)

#endif /* PP_VMP_RDB_H */
