/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sd_host_ip_rdb.h
    @brief RDB File for SD_HOST_IP

    @version 2018May25_rdb
*/

#ifndef SD_HOST_IP_RDB_H
#define SD_HOST_IP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SD_HOST_IP_SDMASYSTEMADDRESSARGUMENT_TYPE;
#define SD_HOST_IP_SDMASYSTEMADDRESSARGUMENT_SDMASYSTEMADDRESSARGUMENT2_MASK (0xffffffffUL)
#define SD_HOST_IP_SDMASYSTEMADDRESSARGUMENT_SDMASYSTEMADDRESSARGUMENT2_SHIFT (0UL)




typedef uint16_t SD_HOST_IP_BLOCKSIZE_TYPE;
#define SD_HOST_IP_BLOCKSIZE_HOSTSDMABUFFERSIZE_MASK (0x7000U)
#define SD_HOST_IP_BLOCKSIZE_HOSTSDMABUFFERSIZE_SHIFT (12U)
#define SD_HOST_IP_BLOCKSIZE_TRANSFERBLOCKSIZE_MASK (0xfffU)
#define SD_HOST_IP_BLOCKSIZE_TRANSFERBLOCKSIZE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_BLOCKCOUNT_TYPE;
#define SD_HOST_IP_BLOCKCOUNT_BLOCKSCOUNTFORCURRENTTRANSFER_MASK (0xffffU)
#define SD_HOST_IP_BLOCKCOUNT_BLOCKSCOUNTFORCURRENTTRANSFER_SHIFT (0U)




typedef uint32_t SD_HOST_IP_ARGUMENT1_TYPE;
#define SD_HOST_IP_ARGUMENT1_COMMANDARGUMENT1_MASK (0xffffffffUL)
#define SD_HOST_IP_ARGUMENT1_COMMANDARGUMENT1_SHIFT (0UL)




typedef uint16_t SD_HOST_IP_TRANSFERMODE_TYPE;
#define SD_HOST_IP_TRANSFERMODE_MULTISINGLEBLOCKSELECT_MASK (0x20U)
#define SD_HOST_IP_TRANSFERMODE_MULTISINGLEBLOCKSELECT_SHIFT (5U)
#define SD_HOST_IP_TRANSFERMODE_DATATRANSFERDIRECTIONSELECT_MASK (0x10U)
#define SD_HOST_IP_TRANSFERMODE_DATATRANSFERDIRECTIONSELECT_SHIFT (4U)
#define SD_HOST_IP_TRANSFERMODE_AUTOCMDENABLE_MASK (0xcU)
#define SD_HOST_IP_TRANSFERMODE_AUTOCMDENABLE_SHIFT (2U)
#define SD_HOST_IP_TRANSFERMODE_BLOCKCOUNTENABLE_MASK (0x2U)
#define SD_HOST_IP_TRANSFERMODE_BLOCKCOUNTENABLE_SHIFT (1U)
#define SD_HOST_IP_TRANSFERMODE_DMAENABLE_MASK (0x1U)
#define SD_HOST_IP_TRANSFERMODE_DMAENABLE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_COMMAND_TYPE;
#define SD_HOST_IP_COMMAND_COMMANDINDEX_MASK (0x3f00U)
#define SD_HOST_IP_COMMAND_COMMANDINDEX_SHIFT (8U)
#define SD_HOST_IP_COMMAND_COMMANDTYPE_MASK (0xc0U)
#define SD_HOST_IP_COMMAND_COMMANDTYPE_SHIFT (6U)
#define SD_HOST_IP_COMMAND_DATAPRESENTSELECT_MASK (0x20U)
#define SD_HOST_IP_COMMAND_DATAPRESENTSELECT_SHIFT (5U)
#define SD_HOST_IP_COMMAND_COMMANDINDEXCHECKENABLE_MASK (0x10U)
#define SD_HOST_IP_COMMAND_COMMANDINDEXCHECKENABLE_SHIFT (4U)
#define SD_HOST_IP_COMMAND_COMMANDCRCCHECKENABLE_MASK (0x8U)
#define SD_HOST_IP_COMMAND_COMMANDCRCCHECKENABLE_SHIFT (3U)
#define SD_HOST_IP_COMMAND_RESPONSETYPESELECT_MASK (0x3U)
#define SD_HOST_IP_COMMAND_RESPONSETYPESELECT_SHIFT (0U)




typedef uint16_t SD_HOST_IP_RESPONSE_TYPE;
#define SD_HOST_IP_RESPONSE_COMMAND_RESPONSE_MASK (0xffffU)
#define SD_HOST_IP_RESPONSE_COMMAND_RESPONSE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_BUFFER_DATA_PORT_TYPE;
#define SD_HOST_IP_BUFFER_DATA_PORT_BUFFERDATA_MASK (0xffffU)
#define SD_HOST_IP_BUFFER_DATA_PORT_BUFFERDATA_SHIFT (0U)




typedef uint32_t SD_HOST_IP_PRESENT_STATE_TYPE;
#define SD_HOST_IP_PRESENT_STATE_DAT7TO4LINESIGNALLEVEL_MASK (0x1e000000UL)
#define SD_HOST_IP_PRESENT_STATE_DAT7TO4LINESIGNALLEVEL_SHIFT (25UL)
#define SD_HOST_IP_PRESENT_STATE_CMDLINESIGNALLEVEL_MASK (0x1000000UL)
#define SD_HOST_IP_PRESENT_STATE_CMDLINESIGNALLEVEL_SHIFT (24UL)
#define SD_HOST_IP_PRESENT_STATE_DAT3TO0LINESIGNALLEVEL_MASK (0xf00000UL)
#define SD_HOST_IP_PRESENT_STATE_DAT3TO0LINESIGNALLEVEL_SHIFT (20UL)
#define SD_HOST_IP_PRESENT_STATE_WRITEPROTECTSWITCHPINLEVEL_MASK (0x80000UL)
#define SD_HOST_IP_PRESENT_STATE_WRITEPROTECTSWITCHPINLEVEL_SHIFT (19UL)
#define SD_HOST_IP_PRESENT_STATE_CARDDETECTPINLEVEL_MASK (0x40000UL)
#define SD_HOST_IP_PRESENT_STATE_CARDDETECTPINLEVEL_SHIFT (18UL)
#define SD_HOST_IP_PRESENT_STATE_CARDSTATESTABLE_MASK (0x20000UL)
#define SD_HOST_IP_PRESENT_STATE_CARDSTATESTABLE_SHIFT (17UL)
#define SD_HOST_IP_PRESENT_STATE_CARDINSERTED_MASK (0x10000UL)
#define SD_HOST_IP_PRESENT_STATE_CARDINSERTED_SHIFT (16UL)
#define SD_HOST_IP_PRESENT_STATE_BUFFERREADENABLE_MASK (0x800UL)
#define SD_HOST_IP_PRESENT_STATE_BUFFERREADENABLE_SHIFT (11UL)
#define SD_HOST_IP_PRESENT_STATE_BUFFERWRITEENABLE_MASK (0x400UL)
#define SD_HOST_IP_PRESENT_STATE_BUFFERWRITEENABLE_SHIFT (10UL)
#define SD_HOST_IP_PRESENT_STATE_READTRANSFERACTIVE_MASK (0x200UL)
#define SD_HOST_IP_PRESENT_STATE_READTRANSFERACTIVE_SHIFT (9UL)
#define SD_HOST_IP_PRESENT_STATE_WRITETRANSFERACTIVE_MASK (0x100UL)
#define SD_HOST_IP_PRESENT_STATE_WRITETRANSFERACTIVE_SHIFT (8UL)
#define SD_HOST_IP_PRESENT_STATE_RETUNINGREQUEST_MASK (0x8UL)
#define SD_HOST_IP_PRESENT_STATE_RETUNINGREQUEST_SHIFT (3UL)
#define SD_HOST_IP_PRESENT_STATE_DATLINEACTIVE_MASK (0x4UL)
#define SD_HOST_IP_PRESENT_STATE_DATLINEACTIVE_SHIFT (2UL)
#define SD_HOST_IP_PRESENT_STATE_COMMANDINHIBITDAT_MASK (0x2UL)
#define SD_HOST_IP_PRESENT_STATE_COMMANDINHIBITDAT_SHIFT (1UL)
#define SD_HOST_IP_PRESENT_STATE_COMMANDINHIBITCMD_MASK (0x1UL)
#define SD_HOST_IP_PRESENT_STATE_COMMANDINHIBITCMD_SHIFT (0UL)




typedef uint8_t SD_HOST_IP_HOST_CONTROL_1_TYPE;
#define SD_HOST_IP_HOST_CONTROL_1_CARDDETECTSIGNALDETECTION_MASK (0x80U)
#define SD_HOST_IP_HOST_CONTROL_1_CARDDETECTSIGNALDETECTION_SHIFT (7U)
#define SD_HOST_IP_HOST_CONTROL_1_CARDDETECTTESTLEVEL_MASK (0x40U)
#define SD_HOST_IP_HOST_CONTROL_1_CARDDETECTTESTLEVEL_SHIFT (6U)
#define SD_HOST_IP_HOST_CONTROL_1_EXTENDEDDATATRANSFERWIDTH_MASK (0x20U)
#define SD_HOST_IP_HOST_CONTROL_1_EXTENDEDDATATRANSFERWIDTH_SHIFT (5U)
#define SD_HOST_IP_HOST_CONTROL_1_TRANSFERWIDTHDMASELECT_MASK (0x18U)
#define SD_HOST_IP_HOST_CONTROL_1_TRANSFERWIDTHDMASELECT_SHIFT (3U)
#define SD_HOST_IP_HOST_CONTROL_1_HIGHSPEEDENABLE_MASK (0x4U)
#define SD_HOST_IP_HOST_CONTROL_1_HIGHSPEEDENABLE_SHIFT (2U)
#define SD_HOST_IP_HOST_CONTROL_1_DATATRANSFERWIDTHSD1ORSD4_MASK (0x2U)
#define SD_HOST_IP_HOST_CONTROL_1_DATATRANSFERWIDTHSD1ORSD4_SHIFT (1U)
#define SD_HOST_IP_HOST_CONTROL_1_LEDCONTROL_MASK (0x1U)
#define SD_HOST_IP_HOST_CONTROL_1_LEDCONTROL_SHIFT (0U)




typedef uint8_t SD_HOST_IP_POWER_CONTROL_TYPE;
#define SD_HOST_IP_POWER_CONTROL_HARDWARERESET_MASK (0x10U)
#define SD_HOST_IP_POWER_CONTROL_HARDWARERESET_SHIFT (4U)
#define SD_HOST_IP_POWER_CONTROL_SDBUSVOLTAGESELECT_MASK (0xeU)
#define SD_HOST_IP_POWER_CONTROL_SDBUSVOLTAGESELECT_SHIFT (1U)
#define SD_HOST_IP_POWER_CONTROL_SDBUSPOWER_MASK (0x1U)
#define SD_HOST_IP_POWER_CONTROL_SDBUSPOWER_SHIFT (0U)




typedef uint8_t SD_HOST_IP_BLOCK_GAP_CONTROL_TYPE;
#define SD_HOST_IP_BLOCK_GAP_CONTROL_BOOT_ACK_CHK_MASK (0x80U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_BOOT_ACK_CHK_SHIFT (7U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_ALT_BOOT_EN_MASK (0x40U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_ALT_BOOT_EN_SHIFT (6U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_BOOT_EN_MASK (0x20U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_BOOT_EN_SHIFT (5U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_SPI_MODE_MASK (0x10U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_SPI_MODE_SHIFT (4U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_INTERRUPTATBLOCKGAP_MASK (0x8U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_INTERRUPTATBLOCKGAP_SHIFT (3U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_READWAITCONTROL_MASK (0x4U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_READWAITCONTROL_SHIFT (2U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_CONTINUEREQUEST_MASK (0x2U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_CONTINUEREQUEST_SHIFT (1U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_STOPATBLOCKGAPREQUEST_MASK (0x1U)
#define SD_HOST_IP_BLOCK_GAP_CONTROL_STOPATBLOCKGAPREQUEST_SHIFT (0U)




typedef uint8_t SD_HOST_IP_WAKE_CONT_TYPE;
#define SD_HOST_IP_WAKE_CONT_WAKEUPEVENTENABLEONSDCARDREMOVAL_MASK (0x4U)
#define SD_HOST_IP_WAKE_CONT_WAKEUPEVENTENABLEONSDCARDREMOVAL_SHIFT (2U)
#define SD_HOST_IP_WAKE_CONT_WAKEUPEVENTENABLEONSDCARDINSERTION_MASK (0x2U)
#define SD_HOST_IP_WAKE_CONT_WAKEUPEVENTENABLEONSDCARDINSERTION_SHIFT (1U)
#define SD_HOST_IP_WAKE_CONT_WAKEUPEVENTENABLEONCARDINTERRUPT_MASK (0x1U)
#define SD_HOST_IP_WAKE_CONT_WAKEUPEVENTENABLEONCARDINTERRUPT_SHIFT (0U)




typedef uint16_t SD_HOST_IP_CLOC_CONT_TYPE;
#define SD_HOST_IP_CLOC_CONT_SDCLKFREQUENCYSELECT_MASK (0xff00U)
#define SD_HOST_IP_CLOC_CONT_SDCLKFREQUENCYSELECT_SHIFT (8U)
#define SD_HOST_IP_CLOC_CONT_UPPERBITSOFSDCLKFREQUENCYSELECT_MASK (0xc0U)
#define SD_HOST_IP_CLOC_CONT_UPPERBITSOFSDCLKFREQUENCYSELECT_SHIFT (6U)
#define SD_HOST_IP_CLOC_CONT_FREQUENCYSELECTCLOCKGENERATORSELECT_MASK (0x20U)
#define SD_HOST_IP_CLOC_CONT_FREQUENCYSELECTCLOCKGENERATORSELECT_SHIFT (5U)
#define SD_HOST_IP_CLOC_CONT_SDCLOCKENABLE_MASK (0x4U)
#define SD_HOST_IP_CLOC_CONT_SDCLOCKENABLE_SHIFT (2U)
#define SD_HOST_IP_CLOC_CONT_INTERNALCLOCKSTABLE_MASK (0x2U)
#define SD_HOST_IP_CLOC_CONT_INTERNALCLOCKSTABLE_SHIFT (1U)
#define SD_HOST_IP_CLOC_CONT_INTERNALCLOCKENABLE_MASK (0x1U)
#define SD_HOST_IP_CLOC_CONT_INTERNALCLOCKENABLE_SHIFT (0U)




typedef uint8_t SD_HOST_IP_TIMEOUT_CONTROL_TYPE;
#define SD_HOST_IP_TIMEOUT_CONTROL_DATATIMEOUTCOUNTERVALUE_MASK (0xfU)
#define SD_HOST_IP_TIMEOUT_CONTROL_DATATIMEOUTCOUNTERVALUE_SHIFT (0U)




typedef uint8_t SD_HOST_IP_SOFTWARE_RESET_TYPE;
#define SD_HOST_IP_SOFTWARE_RESET_SOFTWARERESETFORDATLINE_MASK (0x4U)
#define SD_HOST_IP_SOFTWARE_RESET_SOFTWARERESETFORDATLINE_SHIFT (2U)
#define SD_HOST_IP_SOFTWARE_RESET_SOFTWARERESETFORCMDLINE_MASK (0x2U)
#define SD_HOST_IP_SOFTWARE_RESET_SOFTWARERESETFORCMDLINE_SHIFT (1U)
#define SD_HOST_IP_SOFTWARE_RESET_SOFTWARERESETFORALL_MASK (0x1U)
#define SD_HOST_IP_SOFTWARE_RESET_SOFTWARERESETFORALL_SHIFT (0U)




typedef uint16_t SD_HOST_IP_NORMAL_INTERRUPT_STATUS_TYPE;
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_ERRORINTERRUPT_MASK (0x8000U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_ERRORINTERRUPT_SHIFT (15U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BOOTTERMINATEINTERRUPT_MASK (0x4000U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BOOTTERMINATEINTERRUPT_SHIFT (14U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BOOTACKRCV_MASK (0x2000U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BOOTACKRCV_SHIFT (13U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_RETUNINGEVENT_MASK (0x1000U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_RETUNINGEVENT_SHIFT (12U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_INT_C_MASK (0x800U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_INT_C_SHIFT (11U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_INT_B_MASK (0x400U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_INT_B_SHIFT (10U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_INT_A_MASK (0x200U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_INT_A_SHIFT (9U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_CARDINTERRUPT_MASK (0x100U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_CARDINTERRUPT_SHIFT (8U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_CARDREMOVAL_MASK (0x80U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_CARDREMOVAL_SHIFT (7U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_CARDINSERTION_MASK (0x40U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_CARDINSERTION_SHIFT (6U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BUFFERREADREADY_MASK (0x20U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BUFFERREADREADY_SHIFT (5U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BUFFERWRITEREADY_MASK (0x10U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BUFFERWRITEREADY_SHIFT (4U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_DMAINTERRUPT_MASK (0x8U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_DMAINTERRUPT_SHIFT (3U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BLOCKGAPEVENT_MASK (0x4U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_BLOCKGAPEVENT_SHIFT (2U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_TRANSFERCOMPLETE_MASK (0x2U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_TRANSFERCOMPLETE_SHIFT (1U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_COMMANDCOMPLETE_MASK (0x1U)
#define SD_HOST_IP_NORMAL_INTERRUPT_STATUS_COMMANDCOMPLETE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_ERROR_INTERRUPT_STATUS_TYPE;
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_TARGETRESPONSEERROR_MASK (0x1000U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_TARGETRESPONSEERROR_SHIFT (12U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_ADMAERROR_MASK (0x200U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_ADMAERROR_SHIFT (9U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_AUTOCMDERROR_MASK (0x100U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_AUTOCMDERROR_SHIFT (8U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_CURRENTLIMITERROR_MASK (0x80U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_CURRENTLIMITERROR_SHIFT (7U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_DATAENDBITERROR_MASK (0x40U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_DATAENDBITERROR_SHIFT (6U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_DATACRCERROR_MASK (0x20U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_DATACRCERROR_SHIFT (5U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_DATATIMEOUTERROR_MASK (0x10U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_DATATIMEOUTERROR_SHIFT (4U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDINDEXERROR_MASK (0x8U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDINDEXERROR_SHIFT (3U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDENDBITERROR_MASK (0x4U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDENDBITERROR_SHIFT (2U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDCRCERROR_MASK (0x2U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDCRCERROR_SHIFT (1U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDTIMEOUTERROR_MASK (0x1U)
#define SD_HOST_IP_ERROR_INTERRUPT_STATUS_COMMANDTIMEOUTERROR_SHIFT (0U)




typedef uint16_t SD_HOST_IP_NISE_TYPE;
#define SD_HOST_IP_NISE_FIXEDTO0_MASK (0x8000U)
#define SD_HOST_IP_NISE_FIXEDTO0_SHIFT (15U)
#define SD_HOST_IP_NISE_BOOTTERMINATEINTERRUPTENABLE_MASK (0x4000U)
#define SD_HOST_IP_NISE_BOOTTERMINATEINTERRUPTENABLE_SHIFT (14U)
#define SD_HOST_IP_NISE_BOOTACKRCVENABLE_MASK (0x2000U)
#define SD_HOST_IP_NISE_BOOTACKRCVENABLE_SHIFT (13U)
#define SD_HOST_IP_NISE_RETUNINGEVENTSTATUSENABLE_MASK (0x1000U)
#define SD_HOST_IP_NISE_RETUNINGEVENTSTATUSENABLE_SHIFT (12U)
#define SD_HOST_IP_NISE_INT_CSTATUSENABLE_MASK (0x800U)
#define SD_HOST_IP_NISE_INT_CSTATUSENABLE_SHIFT (11U)
#define SD_HOST_IP_NISE_INT_BSTATUSENABLE_MASK (0x400U)
#define SD_HOST_IP_NISE_INT_BSTATUSENABLE_SHIFT (10U)
#define SD_HOST_IP_NISE_INT_ASTATUSENABLE_MASK (0x200U)
#define SD_HOST_IP_NISE_INT_ASTATUSENABLE_SHIFT (9U)
#define SD_HOST_IP_NISE_CARDINTERRUPTSTATUSENABLE_MASK (0x100U)
#define SD_HOST_IP_NISE_CARDINTERRUPTSTATUSENABLE_SHIFT (8U)
#define SD_HOST_IP_NISE_CARDREMOVALSTATUSENABLE_MASK (0x80U)
#define SD_HOST_IP_NISE_CARDREMOVALSTATUSENABLE_SHIFT (7U)
#define SD_HOST_IP_NISE_CARDINSERTIONSTATUSENABLE_MASK (0x40U)
#define SD_HOST_IP_NISE_CARDINSERTIONSTATUSENABLE_SHIFT (6U)
#define SD_HOST_IP_NISE_BUFFERREADREADYSTATUSENABLE_MASK (0x20U)
#define SD_HOST_IP_NISE_BUFFERREADREADYSTATUSENABLE_SHIFT (5U)
#define SD_HOST_IP_NISE_BUFFERWRITEREADYSTATUSENABLE_MASK (0x10U)
#define SD_HOST_IP_NISE_BUFFERWRITEREADYSTATUSENABLE_SHIFT (4U)
#define SD_HOST_IP_NISE_DMAINTERRUPTSTATUSENABLE_MASK (0x8U)
#define SD_HOST_IP_NISE_DMAINTERRUPTSTATUSENABLE_SHIFT (3U)
#define SD_HOST_IP_NISE_BLOCKGAPEVENTSTATUSENABLE_MASK (0x4U)
#define SD_HOST_IP_NISE_BLOCKGAPEVENTSTATUSENABLE_SHIFT (2U)
#define SD_HOST_IP_NISE_TRANSFERCOMPLETESTATUSENABLE_MASK (0x2U)
#define SD_HOST_IP_NISE_TRANSFERCOMPLETESTATUSENABLE_SHIFT (1U)
#define SD_HOST_IP_NISE_COMMANDCOMPLETESTATUSENABLE_MASK (0x1U)
#define SD_HOST_IP_NISE_COMMANDCOMPLETESTATUSENABLE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_EISE_TYPE;
#define SD_HOST_IP_EISE_TARGETRESPONSEERRORHOSTERRORSTATUSENABLE_MASK (0x1000U)
#define SD_HOST_IP_EISE_TARGETRESPONSEERRORHOSTERRORSTATUSENABLE_SHIFT (12U)
#define SD_HOST_IP_EISE_TUNINGERRORSTATUSENABLE_MASK (0x400U)
#define SD_HOST_IP_EISE_TUNINGERRORSTATUSENABLE_SHIFT (10U)
#define SD_HOST_IP_EISE_ADMAERRORSTATUSENABLE_MASK (0x200U)
#define SD_HOST_IP_EISE_ADMAERRORSTATUSENABLE_SHIFT (9U)
#define SD_HOST_IP_EISE_AUTOCMD12ERRORSTATUSENABLE_MASK (0x100U)
#define SD_HOST_IP_EISE_AUTOCMD12ERRORSTATUSENABLE_SHIFT (8U)
#define SD_HOST_IP_EISE_CURRENTLIMITERRORSTATUSENABLE_MASK (0x80U)
#define SD_HOST_IP_EISE_CURRENTLIMITERRORSTATUSENABLE_SHIFT (7U)
#define SD_HOST_IP_EISE_DATAENDBITERRORSTATUSENABLE_MASK (0x40U)
#define SD_HOST_IP_EISE_DATAENDBITERRORSTATUSENABLE_SHIFT (6U)
#define SD_HOST_IP_EISE_DATACRCERRORSTATUSENABLE_MASK (0x20U)
#define SD_HOST_IP_EISE_DATACRCERRORSTATUSENABLE_SHIFT (5U)
#define SD_HOST_IP_EISE_DATATIMEOUTERRORSTATUSENABLE_MASK (0x10U)
#define SD_HOST_IP_EISE_DATATIMEOUTERRORSTATUSENABLE_SHIFT (4U)
#define SD_HOST_IP_EISE_COMMANDINDEXERRORSTATUSENABLE_MASK (0x8U)
#define SD_HOST_IP_EISE_COMMANDINDEXERRORSTATUSENABLE_SHIFT (3U)
#define SD_HOST_IP_EISE_COMMANDENDBITERRORSTATUSENABLE_MASK (0x4U)
#define SD_HOST_IP_EISE_COMMANDENDBITERRORSTATUSENABLE_SHIFT (2U)
#define SD_HOST_IP_EISE_COMMANDCRCERRORSTATUSENABLE_MASK (0x2U)
#define SD_HOST_IP_EISE_COMMANDCRCERRORSTATUSENABLE_SHIFT (1U)
#define SD_HOST_IP_EISE_COMMANDTIMEOUTERRORSTATUSENABLE_MASK (0x1U)
#define SD_HOST_IP_EISE_COMMANDTIMEOUTERRORSTATUSENABLE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_NISE1_TYPE;
#define SD_HOST_IP_NISE1_FIXEDTO0_MASK (0x8000U)
#define SD_HOST_IP_NISE1_FIXEDTO0_SHIFT (15U)
#define SD_HOST_IP_NISE1_BOOTTERMINATEINTERRUPTSIGNALENABLE_MASK (0x4000U)
#define SD_HOST_IP_NISE1_BOOTTERMINATEINTERRUPTSIGNALENABLE_SHIFT (14U)
#define SD_HOST_IP_NISE1_BOOTACKRCVSIGNALENABLE_MASK (0x2000U)
#define SD_HOST_IP_NISE1_BOOTACKRCVSIGNALENABLE_SHIFT (13U)
#define SD_HOST_IP_NISE1_RETUNINGEVENTSIGNALENABLE_MASK (0x1000U)
#define SD_HOST_IP_NISE1_RETUNINGEVENTSIGNALENABLE_SHIFT (12U)
#define SD_HOST_IP_NISE1_INT_CSIGNALENABLE_MASK (0x800U)
#define SD_HOST_IP_NISE1_INT_CSIGNALENABLE_SHIFT (11U)
#define SD_HOST_IP_NISE1_INT_BSIGNALENABLE_MASK (0x400U)
#define SD_HOST_IP_NISE1_INT_BSIGNALENABLE_SHIFT (10U)
#define SD_HOST_IP_NISE1_INT_ASIGNALENABLE_MASK (0x200U)
#define SD_HOST_IP_NISE1_INT_ASIGNALENABLE_SHIFT (9U)
#define SD_HOST_IP_NISE1_CARDINTERRUPTSIGNALENABLE_MASK (0x100U)
#define SD_HOST_IP_NISE1_CARDINTERRUPTSIGNALENABLE_SHIFT (8U)
#define SD_HOST_IP_NISE1_CARDREMOVALSIGNALENABLE_MASK (0x80U)
#define SD_HOST_IP_NISE1_CARDREMOVALSIGNALENABLE_SHIFT (7U)
#define SD_HOST_IP_NISE1_CARDINSERTIONSIGNALENABLE_MASK (0x40U)
#define SD_HOST_IP_NISE1_CARDINSERTIONSIGNALENABLE_SHIFT (6U)
#define SD_HOST_IP_NISE1_BUFFERREADREADYSIGNALENABLE_MASK (0x20U)
#define SD_HOST_IP_NISE1_BUFFERREADREADYSIGNALENABLE_SHIFT (5U)
#define SD_HOST_IP_NISE1_BUFFERWRITEREADYSIGNALENABLE_MASK (0x10U)
#define SD_HOST_IP_NISE1_BUFFERWRITEREADYSIGNALENABLE_SHIFT (4U)
#define SD_HOST_IP_NISE1_DMAINTERRUPTSIGNALENABLE_MASK (0x8U)
#define SD_HOST_IP_NISE1_DMAINTERRUPTSIGNALENABLE_SHIFT (3U)
#define SD_HOST_IP_NISE1_BLOCKGAPEVENTSIGNALENABLE_MASK (0x4U)
#define SD_HOST_IP_NISE1_BLOCKGAPEVENTSIGNALENABLE_SHIFT (2U)
#define SD_HOST_IP_NISE1_TRANSFERCOMPLETESIGNALENABLE_MASK (0x2U)
#define SD_HOST_IP_NISE1_TRANSFERCOMPLETESIGNALENABLE_SHIFT (1U)
#define SD_HOST_IP_NISE1_COMMANDCOMPLETESIGNALENABLE_MASK (0x1U)
#define SD_HOST_IP_NISE1_COMMANDCOMPLETESIGNALENABLE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_EISE1_TYPE;
#define SD_HOST_IP_EISE1_VENDORSPECIFICERRORSIGNALENABLE_MASK (0xe000U)
#define SD_HOST_IP_EISE1_VENDORSPECIFICERRORSIGNALENABLE_SHIFT (13U)
#define SD_HOST_IP_EISE1_TARGETRESPONSEERRORSIGNALENABLE_MASK (0x1000U)
#define SD_HOST_IP_EISE1_TARGETRESPONSEERRORSIGNALENABLE_SHIFT (12U)
#define SD_HOST_IP_EISE1_TUNINGERRORSIGNALENABLE_MASK (0x400U)
#define SD_HOST_IP_EISE1_TUNINGERRORSIGNALENABLE_SHIFT (10U)
#define SD_HOST_IP_EISE1_ADMAERRORSIGNALENABLE_MASK (0x200U)
#define SD_HOST_IP_EISE1_ADMAERRORSIGNALENABLE_SHIFT (9U)
#define SD_HOST_IP_EISE1_AUTOCMD12ERRORSIGNALENABLE_MASK (0x100U)
#define SD_HOST_IP_EISE1_AUTOCMD12ERRORSIGNALENABLE_SHIFT (8U)
#define SD_HOST_IP_EISE1_CURRENTLIMITERRORSIGNALENABLE_MASK (0x80U)
#define SD_HOST_IP_EISE1_CURRENTLIMITERRORSIGNALENABLE_SHIFT (7U)
#define SD_HOST_IP_EISE1_DATAENDBITERRORSIGNALENABLE_MASK (0x40U)
#define SD_HOST_IP_EISE1_DATAENDBITERRORSIGNALENABLE_SHIFT (6U)
#define SD_HOST_IP_EISE1_DATACRCERRORSIGNALENABLE_MASK (0x20U)
#define SD_HOST_IP_EISE1_DATACRCERRORSIGNALENABLE_SHIFT (5U)
#define SD_HOST_IP_EISE1_DATATIMEOUTERRORSIGNALENABLE_MASK (0x10U)
#define SD_HOST_IP_EISE1_DATATIMEOUTERRORSIGNALENABLE_SHIFT (4U)
#define SD_HOST_IP_EISE1_COMMANDINDEXERRORSIGNALENABLE_MASK (0x8U)
#define SD_HOST_IP_EISE1_COMMANDINDEXERRORSIGNALENABLE_SHIFT (3U)
#define SD_HOST_IP_EISE1_COMMANDENDBITERRORSIGNALENABLE_MASK (0x4U)
#define SD_HOST_IP_EISE1_COMMANDENDBITERRORSIGNALENABLE_SHIFT (2U)
#define SD_HOST_IP_EISE1_COMMANDCRCERRORSIGNALENABLE_MASK (0x2U)
#define SD_HOST_IP_EISE1_COMMANDCRCERRORSIGNALENABLE_SHIFT (1U)
#define SD_HOST_IP_EISE1_COMMANDTIMEOUTERRORSIGNALENABLE_MASK (0x1U)
#define SD_HOST_IP_EISE1_COMMANDTIMEOUTERRORSIGNALENABLE_SHIFT (0U)




typedef uint16_t SD_HOST_IP_AC12ES_TYPE;
#define SD_HOST_IP_AC12ES_COMMANDNOTISSUEDBYAUTOCMD12ERROR_MASK (0x80U)
#define SD_HOST_IP_AC12ES_COMMANDNOTISSUEDBYAUTOCMD12ERROR_SHIFT (7U)
#define SD_HOST_IP_AC12ES_AUTOCMDINDEXERROR_MASK (0x10U)
#define SD_HOST_IP_AC12ES_AUTOCMDINDEXERROR_SHIFT (4U)
#define SD_HOST_IP_AC12ES_AUTOCMDENDBITERROR_MASK (0x8U)
#define SD_HOST_IP_AC12ES_AUTOCMDENDBITERROR_SHIFT (3U)
#define SD_HOST_IP_AC12ES_AUTOCMDCRCERROR_MASK (0x4U)
#define SD_HOST_IP_AC12ES_AUTOCMDCRCERROR_SHIFT (2U)
#define SD_HOST_IP_AC12ES_AUTOCMDTIMEOUTERROR_MASK (0x2U)
#define SD_HOST_IP_AC12ES_AUTOCMDTIMEOUTERROR_SHIFT (1U)
#define SD_HOST_IP_AC12ES_AUTOCMD12NOTEXECUTED_MASK (0x1U)
#define SD_HOST_IP_AC12ES_AUTOCMD12NOTEXECUTED_SHIFT (0U)




typedef uint16_t SD_HOST_IP_HOST_CONTROL_2_TYPE;
#define SD_HOST_IP_HOST_CONTROL_2_PRESETVALUEENABLE_MASK (0x8000U)
#define SD_HOST_IP_HOST_CONTROL_2_PRESETVALUEENABLE_SHIFT (15U)
#define SD_HOST_IP_HOST_CONTROL_2_INTERRUPTENABLE_MASK (0x4000U)
#define SD_HOST_IP_HOST_CONTROL_2_INTERRUPTENABLE_SHIFT (14U)
#define SD_HOST_IP_HOST_CONTROL_2_SAMPLINGCLOCKSELECT_MASK (0x80U)
#define SD_HOST_IP_HOST_CONTROL_2_SAMPLINGCLOCKSELECT_SHIFT (7U)
#define SD_HOST_IP_HOST_CONTROL_2_EXECUTETUNING_MASK (0x40U)
#define SD_HOST_IP_HOST_CONTROL_2_EXECUTETUNING_SHIFT (6U)
#define SD_HOST_IP_HOST_CONTROL_2_DRIVERSTRENGTHSELECT_MASK (0x30U)
#define SD_HOST_IP_HOST_CONTROL_2_DRIVERSTRENGTHSELECT_SHIFT (4U)
#define SD_HOST_IP_HOST_CONTROL_2_V1P8SIGNALINGENABLE_MASK (0x8U)
#define SD_HOST_IP_HOST_CONTROL_2_V1P8SIGNALINGENABLE_SHIFT (3U)
#define SD_HOST_IP_HOST_CONTROL_2_UHSMODESELECT_MASK (0x7U)
#define SD_HOST_IP_HOST_CONTROL_2_UHSMODESELECT_SHIFT (0U)




typedef uint32_t SD_HOST_IP_CAPABILITIES_0_TYPE;
#define SD_HOST_IP_CAPABILITIES_0_SLOTTYPE_MASK (0xc0000000UL)
#define SD_HOST_IP_CAPABILITIES_0_SLOTTYPE_SHIFT (30UL)
#define SD_HOST_IP_CAPABILITIES_0_ASYNCHRONOUSINTERRUPTSUPPORT_MASK (0x20000000UL)
#define SD_HOST_IP_CAPABILITIES_0_ASYNCHRONOUSINTERRUPTSUPPORT_SHIFT (29UL)
#define SD_HOST_IP_CAPABILITIES_0_SYSTEMBUSSUPPORT64BIT_MASK (0x10000000UL)
#define SD_HOST_IP_CAPABILITIES_0_SYSTEMBUSSUPPORT64BIT_SHIFT (28UL)
#define SD_HOST_IP_CAPABILITIES_0_VOLTAGESUPPORT1P8V_MASK (0x4000000UL)
#define SD_HOST_IP_CAPABILITIES_0_VOLTAGESUPPORT1P8V_SHIFT (26UL)
#define SD_HOST_IP_CAPABILITIES_0_VOLTAGESUPPORT3P0V_MASK (0x2000000UL)
#define SD_HOST_IP_CAPABILITIES_0_VOLTAGESUPPORT3P0V_SHIFT (25UL)
#define SD_HOST_IP_CAPABILITIES_0_VOLTAGESUPPORT3P3V_MASK (0x1000000UL)
#define SD_HOST_IP_CAPABILITIES_0_VOLTAGESUPPORT3P3V_SHIFT (24UL)
#define SD_HOST_IP_CAPABILITIES_0_SUSPENDRESUMESUPPORT_MASK (0x800000UL)
#define SD_HOST_IP_CAPABILITIES_0_SUSPENDRESUMESUPPORT_SHIFT (23UL)
#define SD_HOST_IP_CAPABILITIES_0_SDMASUPPORT_MASK (0x400000UL)
#define SD_HOST_IP_CAPABILITIES_0_SDMASUPPORT_SHIFT (22UL)
#define SD_HOST_IP_CAPABILITIES_0_HIGHSPEEDSUPPORT_MASK (0x200000UL)
#define SD_HOST_IP_CAPABILITIES_0_HIGHSPEEDSUPPORT_SHIFT (21UL)
#define SD_HOST_IP_CAPABILITIES_0_ADMA2SUPPORT_MASK (0x80000UL)
#define SD_HOST_IP_CAPABILITIES_0_ADMA2SUPPORT_SHIFT (19UL)
#define SD_HOST_IP_CAPABILITIES_0_EXTENDEDMEDIABUSSUPPORT_MASK (0x40000UL)
#define SD_HOST_IP_CAPABILITIES_0_EXTENDEDMEDIABUSSUPPORT_SHIFT (18UL)
#define SD_HOST_IP_CAPABILITIES_0_MAXBLOCKLENGTH_MASK (0x30000UL)
#define SD_HOST_IP_CAPABILITIES_0_MAXBLOCKLENGTH_SHIFT (16UL)
#define SD_HOST_IP_CAPABILITIES_0_BASECLOCKFREQUENCYFORSDCLOCK_MASK (0xff00UL)
#define SD_HOST_IP_CAPABILITIES_0_BASECLOCKFREQUENCYFORSDCLOCK_SHIFT (8UL)
#define SD_HOST_IP_CAPABILITIES_0_TIMEOUTCLOCKUNIT_MASK (0x80UL)
#define SD_HOST_IP_CAPABILITIES_0_TIMEOUTCLOCKUNIT_SHIFT (7UL)
#define SD_HOST_IP_CAPABILITIES_0_TIMEOUTCLOCKFREQUENCY_MASK (0x3fUL)
#define SD_HOST_IP_CAPABILITIES_0_TIMEOUTCLOCKFREQUENCY_SHIFT (0UL)




typedef uint32_t SD_HOST_IP_CAPABILITIES_1_TYPE;
#define SD_HOST_IP_CAPABILITIES_1_SPIBLOCKMODE_MASK (0x2000000UL)
#define SD_HOST_IP_CAPABILITIES_1_SPIBLOCKMODE_SHIFT (25UL)
#define SD_HOST_IP_CAPABILITIES_1_SPIMODE_MASK (0x1000000UL)
#define SD_HOST_IP_CAPABILITIES_1_SPIMODE_SHIFT (24UL)
#define SD_HOST_IP_CAPABILITIES_1_CLOCKMULTIPLIER_MASK (0xff0000UL)
#define SD_HOST_IP_CAPABILITIES_1_CLOCKMULTIPLIER_SHIFT (16UL)
#define SD_HOST_IP_CAPABILITIES_1_RETUNINGMODES_MASK (0xc000UL)
#define SD_HOST_IP_CAPABILITIES_1_RETUNINGMODES_SHIFT (14UL)
#define SD_HOST_IP_CAPABILITIES_1_USETUNINGFORSDR50_MASK (0x2000UL)
#define SD_HOST_IP_CAPABILITIES_1_USETUNINGFORSDR50_SHIFT (13UL)
#define SD_HOST_IP_CAPABILITIES_1_TIMERCOUNTFORRETUNING_MASK (0xf00UL)
#define SD_HOST_IP_CAPABILITIES_1_TIMERCOUNTFORRETUNING_SHIFT (8UL)
#define SD_HOST_IP_CAPABILITIES_1_DRIVERTYPEDSUPPORT_MASK (0x40UL)
#define SD_HOST_IP_CAPABILITIES_1_DRIVERTYPEDSUPPORT_SHIFT (6UL)
#define SD_HOST_IP_CAPABILITIES_1_DRIVERTYPECSUPPORT_MASK (0x20UL)
#define SD_HOST_IP_CAPABILITIES_1_DRIVERTYPECSUPPORT_SHIFT (5UL)
#define SD_HOST_IP_CAPABILITIES_1_DRIVERTYPEASUPPORT_MASK (0x10UL)
#define SD_HOST_IP_CAPABILITIES_1_DRIVERTYPEASUPPORT_SHIFT (4UL)
#define SD_HOST_IP_CAPABILITIES_1_DDR50SUPPORT_MASK (0x4UL)
#define SD_HOST_IP_CAPABILITIES_1_DDR50SUPPORT_SHIFT (2UL)
#define SD_HOST_IP_CAPABILITIES_1_SDR104SUPPORT_MASK (0x2UL)
#define SD_HOST_IP_CAPABILITIES_1_SDR104SUPPORT_SHIFT (1UL)
#define SD_HOST_IP_CAPABILITIES_1_SDR50SUPPORT_MASK (0x1UL)
#define SD_HOST_IP_CAPABILITIES_1_SDR50SUPPORT_SHIFT (0UL)




typedef uint32_t SD_HOST_IP_MCC0_TYPE;
#define SD_HOST_IP_MCC0_MAXIMUMCURRENTFOR1P8V_MASK (0xff0000UL)
#define SD_HOST_IP_MCC0_MAXIMUMCURRENTFOR1P8V_SHIFT (16UL)
#define SD_HOST_IP_MCC0_MAXIMUMCURRENTFOR3P0V_MASK (0xff00UL)
#define SD_HOST_IP_MCC0_MAXIMUMCURRENTFOR3P0V_SHIFT (8UL)
#define SD_HOST_IP_MCC0_MAXIMUMCURRENTFOR3P3V_MASK (0xffUL)
#define SD_HOST_IP_MCC0_MAXIMUMCURRENTFOR3P3V_SHIFT (0UL)




typedef uint32_t SD_HOST_IP_MAXIMUM_CURRENT_CAPABILITIES_1_TYPE;




typedef uint16_t SD_HOST_IP_FEFACES_TYPE;
#define SD_HOST_IP_FEFACES_FORCEEVENTFORCOMMANDNOTISSUEDBYAUTOCMD12ERROR_MASK (0x80U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORCOMMANDNOTISSUEDBYAUTOCMD12ERROR_SHIFT (7U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDINDEXERROR_MASK (0x10U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDINDEXERROR_SHIFT (4U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDENDBITERROR_MASK (0x8U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDENDBITERROR_SHIFT (3U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDCRCERROR_MASK (0x4U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDCRCERROR_SHIFT (2U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDTIMEOUTERROR_MASK (0x2U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMDTIMEOUTERROR_SHIFT (1U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMD12NOTEXECUTED_MASK (0x1U)
#define SD_HOST_IP_FEFACES_FORCEEVENTFORAUTOCMD12NOTEXECUTED_SHIFT (0U)




typedef uint16_t SD_HOST_IP_FEFEIS_TYPE;
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORVENDORSPECIFICERRORSTATUS_MASK (0xf000U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORVENDORSPECIFICERRORSTATUS_SHIFT (12U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORADMAERROR_MASK (0x200U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORADMAERROR_SHIFT (9U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORAUTOCMDERROR_MASK (0x100U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORAUTOCMDERROR_SHIFT (8U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCURRENTLIMITERROR_MASK (0x80U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCURRENTLIMITERROR_SHIFT (7U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORDATAENDBITERROR_MASK (0x40U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORDATAENDBITERROR_SHIFT (6U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORDATACRCERROR_MASK (0x20U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORDATACRCERROR_SHIFT (5U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORDATATIMEOUTERROR_MASK (0x10U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORDATATIMEOUTERROR_SHIFT (4U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDINDEXERROR_MASK (0x8U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDINDEXERROR_SHIFT (3U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDENDBITERROR_MASK (0x4U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDENDBITERROR_SHIFT (2U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDCRCERROR_MASK (0x2U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDCRCERROR_SHIFT (1U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDTIMEOUTERROR_MASK (0x1U)
#define SD_HOST_IP_FEFEIS_FORCEEVENTFORCOMMANDTIMEOUTERROR_SHIFT (0U)




typedef uint8_t SD_HOST_IP_ADMA_ERROR_STATUS_TYPE;
#define SD_HOST_IP_ADMA_ERROR_STATUS_ADMALENGTHMISMATCHERROR_MASK (0x4U)
#define SD_HOST_IP_ADMA_ERROR_STATUS_ADMALENGTHMISMATCHERROR_SHIFT (2U)
#define SD_HOST_IP_ADMA_ERROR_STATUS_ADMAERRORSTATE_MASK (0x3U)
#define SD_HOST_IP_ADMA_ERROR_STATUS_ADMAERRORSTATE_SHIFT (0U)




typedef uint8_t SD_HOST_IP_RESERVED_TYPE;




typedef uint16_t SD_HOST_IP_ADMA_SYSTEM_ADDRESS_TYPE;
#define SD_HOST_IP_ADMA_SYSTEM_ADDRESS_ADMASYSTEMADDRESS_MASK (0xffffU)
#define SD_HOST_IP_ADMA_SYSTEM_ADDRESS_ADMASYSTEMADDRESS_SHIFT (0U)




typedef uint16_t SD_HOST_IP_PRESET_VALUE_TYPE;
#define SD_HOST_IP_PRESET_VALUE_DRIVERSTRENGTHSELECTVALUE_MASK (0xc000U)
#define SD_HOST_IP_PRESET_VALUE_DRIVERSTRENGTHSELECTVALUE_SHIFT (14U)
#define SD_HOST_IP_PRESET_VALUE_CLOCKGENERATORSELECTVALUE_MASK (0x400U)
#define SD_HOST_IP_PRESET_VALUE_CLOCKGENERATORSELECTVALUE_SHIFT (10U)
#define SD_HOST_IP_PRESET_VALUE_CLOCKGENERATORSDCLKFREQUENCYSELECTVALUE_MASK (0x3ffU)
#define SD_HOST_IP_PRESET_VALUE_CLOCKGENERATORSDCLKFREQUENCYSELECTVALUE_SHIFT (0U)




typedef uint32_t SD_HOST_IP_BDTC_TYPE;
#define SD_HOST_IP_BDTC_BOOTDATATIMEOUTCOUNTERVALUE_MASK (0xffffffffUL)
#define SD_HOST_IP_BDTC_BOOTDATATIMEOUTCOUNTERVALUE_SHIFT (0UL)




typedef uint32_t SD_HOST_IP_SHARED_BUS_CONTROL_TYPE;




typedef uint16_t SD_HOST_IP_SLOT_INTERRUPT_STATUS_TYPE;
#define SD_HOST_IP_SLOT_INTERRUPT_STATUS_INTERRUPTSIGNALFORSLOT0_MASK (0x1U)
#define SD_HOST_IP_SLOT_INTERRUPT_STATUS_INTERRUPTSIGNALFORSLOT0_SHIFT (0U)




typedef uint16_t SD_HOST_IP_HCV_TYPE;
#define SD_HOST_IP_HCV_NUMBER_MASK (0xff00U)
#define SD_HOST_IP_HCV_NUMBER_SHIFT (8U)
#define SD_HOST_IP_HCV_SPECIFICATIONVERSIONNUMBER_MASK (0xffU)
#define SD_HOST_IP_HCV_SPECIFICATIONVERSIONNUMBER_SHIFT (0U)




typedef volatile struct COMP_PACKED _SD_HOST_IP_RDBType {
    SD_HOST_IP_SDMASYSTEMADDRESSARGUMENT_TYPE sdmasystemaddressargument; /* OFFSET: 0x0 */
    SD_HOST_IP_BLOCKSIZE_TYPE blocksize; /* OFFSET: 0x4 */
    SD_HOST_IP_BLOCKCOUNT_TYPE blockcount; /* OFFSET: 0x6 */
    SD_HOST_IP_ARGUMENT1_TYPE argument1; /* OFFSET: 0x8 */
    SD_HOST_IP_TRANSFERMODE_TYPE transfermode; /* OFFSET: 0xc */
    SD_HOST_IP_COMMAND_TYPE command; /* OFFSET: 0xe */
    SD_HOST_IP_RESPONSE_TYPE response0; /* OFFSET: 0x10 */
    SD_HOST_IP_RESPONSE_TYPE response1; /* OFFSET: 0x12 */
    SD_HOST_IP_RESPONSE_TYPE response2; /* OFFSET: 0x14 */
    SD_HOST_IP_RESPONSE_TYPE response3; /* OFFSET: 0x16 */
    SD_HOST_IP_RESPONSE_TYPE response4; /* OFFSET: 0x18 */
    SD_HOST_IP_RESPONSE_TYPE response5; /* OFFSET: 0x1a */
    SD_HOST_IP_RESPONSE_TYPE response6; /* OFFSET: 0x1c */
    SD_HOST_IP_RESPONSE_TYPE response7; /* OFFSET: 0x1e */
    SD_HOST_IP_BUFFER_DATA_PORT_TYPE buffer_data_port0; /* OFFSET: 0x20 */
    SD_HOST_IP_BUFFER_DATA_PORT_TYPE buffer_data_port1; /* OFFSET: 0x22 */
    SD_HOST_IP_PRESENT_STATE_TYPE present_state; /* OFFSET: 0x24 */
    SD_HOST_IP_HOST_CONTROL_1_TYPE host_control_1; /* OFFSET: 0x28 */
    SD_HOST_IP_POWER_CONTROL_TYPE power_control; /* OFFSET: 0x29 */
    SD_HOST_IP_BLOCK_GAP_CONTROL_TYPE block_gap_control; /* OFFSET: 0x2a */
    SD_HOST_IP_WAKE_CONT_TYPE wakeup_control; /* OFFSET: 0x2b */
    SD_HOST_IP_CLOC_CONT_TYPE clock_control; /* OFFSET: 0x2c */
    SD_HOST_IP_TIMEOUT_CONTROL_TYPE timeout_control; /* OFFSET: 0x2e */
    SD_HOST_IP_SOFTWARE_RESET_TYPE software_reset; /* OFFSET: 0x2f */
    SD_HOST_IP_NORMAL_INTERRUPT_STATUS_TYPE normal_interrupt_status; /* OFFSET: 0x30 */
    SD_HOST_IP_ERROR_INTERRUPT_STATUS_TYPE error_interrupt_status; /* OFFSET: 0x32 */
    SD_HOST_IP_NISE_TYPE normal_interrupt_status_enable; /* OFFSET: 0x34 */
    SD_HOST_IP_EISE_TYPE error_interrupt_status_enable; /* OFFSET: 0x36 */
    SD_HOST_IP_NISE1_TYPE normal_interrupt_signal_enable; /* OFFSET: 0x38 */
    SD_HOST_IP_EISE1_TYPE error_interrupt_signal_enable; /* OFFSET: 0x3a */
    SD_HOST_IP_AC12ES_TYPE auto_cmd12_error_status; /* OFFSET: 0x3c */
    SD_HOST_IP_HOST_CONTROL_2_TYPE host_control_2; /* OFFSET: 0x3e */
    SD_HOST_IP_CAPABILITIES_0_TYPE capabilities_0; /* OFFSET: 0x40 */
    SD_HOST_IP_CAPABILITIES_1_TYPE capabilities_1; /* OFFSET: 0x44 */
    SD_HOST_IP_MCC0_TYPE maximum_current_capabilities_0; /* OFFSET: 0x48 */
    SD_HOST_IP_MAXIMUM_CURRENT_CAPABILITIES_1_TYPE maximum_current_capabilities_1; /* OFFSET: 0x4c */
    SD_HOST_IP_FEFACES_TYPE force_event_for_auto_cmd_error_status; /* OFFSET: 0x50 */
    SD_HOST_IP_FEFEIS_TYPE force_event_for_error_int_status; /* OFFSET: 0x52 */
    SD_HOST_IP_ADMA_ERROR_STATUS_TYPE adma_error_status; /* OFFSET: 0x54 */
    SD_HOST_IP_RESERVED_TYPE rsvd0[3]; /* OFFSET: 0x55 */
    SD_HOST_IP_ADMA_SYSTEM_ADDRESS_TYPE adma_system_address0; /* OFFSET: 0x58 */
    SD_HOST_IP_ADMA_SYSTEM_ADDRESS_TYPE adma_system_address1; /* OFFSET: 0x5a */
    SD_HOST_IP_ADMA_SYSTEM_ADDRESS_TYPE adma_system_address2; /* OFFSET: 0x5c */
    SD_HOST_IP_ADMA_SYSTEM_ADDRESS_TYPE adma_system_address3; /* OFFSET: 0x5e */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value0; /* OFFSET: 0x60 */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value1; /* OFFSET: 0x62 */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value2; /* OFFSET: 0x64 */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value3; /* OFFSET: 0x66 */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value4; /* OFFSET: 0x68 */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value5; /* OFFSET: 0x6a */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value6; /* OFFSET: 0x6c */
    SD_HOST_IP_PRESET_VALUE_TYPE preset_value7; /* OFFSET: 0x6e */
    SD_HOST_IP_BDTC_TYPE boot_data_timeout_control; /* OFFSET: 0x70 */
    SD_HOST_IP_RESERVED_TYPE rsvd1[108]; /* OFFSET: 0x74 */
    SD_HOST_IP_SHARED_BUS_CONTROL_TYPE shared_bus_control; /* OFFSET: 0xe0 */
    SD_HOST_IP_RESERVED_TYPE rsvd2[24]; /* OFFSET: 0xe4 */
    SD_HOST_IP_SLOT_INTERRUPT_STATUS_TYPE slot_interrupt_status; /* OFFSET: 0xfc */
    SD_HOST_IP_HCV_TYPE host_controller_version; /* OFFSET: 0xfe */
} SD_HOST_IP_RDBType;


#define SD_HOST_IP_BASE                 (0x4001A000UL)



#define SD_HOST_IP_MAX_HW_ID            (1UL)

#endif /* SD_HOST_IP_RDB_H */
