/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sd_host_rdb.h
    @brief RDB File for SD_HOST

    @version 2018May25_rdb
*/

#ifndef SD_HOST_RDB_H
#define SD_HOST_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SD_HOST_CORECFG_DDR50_PRESET_TYPE;
#define SD_HOST_CORECFG_DDR50_PRESET_DDR50PRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_DDR50_PRESET_DDR50PRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_SDR104_PRESET_TYPE;
#define SD_HOST_CORECFG_SDR104_PRESET_SDR104PRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_SDR104_PRESET_SDR104PRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_SDR50_PRESET_TYPE;
#define SD_HOST_CORECFG_SDR50_PRESET_SDR50PRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_SDR50_PRESET_SDR50PRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_SDR25_PRESET_TYPE;
#define SD_HOST_CORECFG_SDR25_PRESET_SDR25PRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_SDR25_PRESET_SDR25PRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_SDR12_PRESET_TYPE;
#define SD_HOST_CORECFG_SDR12_PRESET_SDR12PRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_SDR12_PRESET_SDR12PRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_HSPD_PRESET_TYPE;
#define SD_HOST_CORECFG_HSPD_PRESET_HSPDPRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_HSPD_PRESET_HSPDPRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_DSPD_PRESET_TYPE;
#define SD_HOST_CORECFG_DSPD_PRESET_DSPDPRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_DSPD_PRESET_DSPDPRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CORECFG_INIT_PRESET_TYPE;
#define SD_HOST_CORECFG_INIT_PRESET_INITPRESETVAL_MASK (0x1fffUL)
#define SD_HOST_CORECFG_INIT_PRESET_INITPRESETVAL_SHIFT (0UL)




typedef uint32_t SD_HOST_CAPAB_REG_IN_0_TYPE;
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_SLOTTYPE_MASK (0xc0000000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_SLOTTYPE_SHIFT (30UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_ASYNCINTR_MASK (0x20000000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_ASYNCINTR_SHIFT (29UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_64BITSUPPORT_MASK (0x10000000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_64BITSUPPORT_SHIFT (28UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_1P8VOLTSUPPORT_MASK (0x4000000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_1P8VOLTSUPPORT_SHIFT (26UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_3P0VOLTSUPPORT_MASK (0x2000000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_3P0VOLTSUPPORT_SHIFT (25UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_3P3VOLTSUPPORT_MASK (0x1000000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_3P3VOLTSUPPORT_SHIFT (24UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_SUSPRESSUPPORT_MASK (0x800000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_SUSPRESSUPPORT_SHIFT (23UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_SDMASUPPORT_MASK (0x400000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_SDMASUPPORT_SHIFT (22UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_HIGHSPEEDSUPPORT_MASK (0x200000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_HIGHSPEEDSUPPORT_SHIFT (21UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_ADMA2SUPPORT_MASK (0x80000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_ADMA2SUPPORT_SHIFT (19UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_8BITSUPPORT_MASK (0x40000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_8BITSUPPORT_SHIFT (18UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_MAXBLKLENGTH_MASK (0x30000UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_MAXBLKLENGTH_SHIFT (16UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_BASECLKFREQ_MASK (0xff00UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_BASECLKFREQ_SHIFT (8UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_TIMEOUTCLKUNIT_MASK (0x80UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_TIMEOUTCLKUNIT_SHIFT (7UL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_TIMEOUTCLKFREQ_MASK (0x3fUL)
#define SD_HOST_CAPAB_REG_IN_0_CORECFG_TIMEOUTCLKFREQ_SHIFT (0UL)




typedef uint32_t SD_HOST_CAPAB_REG_IN_1_TYPE;
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SPIBLKMODE_MASK (0x2000000UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SPIBLKMODE_SHIFT (25UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SPISUPPORT_MASK (0x1000000UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SPISUPPORT_SHIFT (24UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_CLOCKMULTIPLIER_MASK (0xff0000UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_CLOCKMULTIPLIER_SHIFT (16UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_RETUNINGMODES_MASK (0xc000UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_RETUNINGMODES_SHIFT (14UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_TUNINGFORSDR50_MASK (0x2000UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_TUNINGFORSDR50_SHIFT (13UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_RETUNINGTIMERCNT_MASK (0xf00UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_RETUNINGTIMERCNT_SHIFT (8UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_DDRIVERSUPPORT_MASK (0x40UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_DDRIVERSUPPORT_SHIFT (6UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_CDRIVERSUPPORT_MASK (0x20UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_CDRIVERSUPPORT_SHIFT (5UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_ADRIVERSUPPORT_MASK (0x10UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_ADRIVERSUPPORT_SHIFT (4UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_DDR50SUPPORT_MASK (0x4UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_DDR50SUPPORT_SHIFT (2UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SDR104SUPPORT_MASK (0x2UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SDR104SUPPORT_SHIFT (1UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SDR50SUPPORT_MASK (0x1UL)
#define SD_HOST_CAPAB_REG_IN_1_CORECFG_SDR50SUPPORT_SHIFT (0UL)




typedef uint8_t SD_HOST_RESERVED_TYPE;




typedef uint32_t SD_HOST_MAX_CUR_CAPAB_REG_IN_TYPE;
#define SD_HOST_MAX_CUR_CAPAB_REG_IN_CORECFG_CURR_1P8V_MASK (0xff0000UL)
#define SD_HOST_MAX_CUR_CAPAB_REG_IN_CORECFG_CURR_1P8V_SHIFT (16UL)
#define SD_HOST_MAX_CUR_CAPAB_REG_IN_CORECFG_CURR_3P0V_MASK (0xff00UL)
#define SD_HOST_MAX_CUR_CAPAB_REG_IN_CORECFG_CURR_3P0V_SHIFT (8UL)
#define SD_HOST_MAX_CUR_CAPAB_REG_IN_CORECFG_CURR_3P3V_MASK (0xffUL)
#define SD_HOST_MAX_CUR_CAPAB_REG_IN_CORECFG_CURR_3P3V_SHIFT (0UL)




typedef uint32_t SD_HOST_MEM_CTL_TYPE;
#define SD_HOST_MEM_CTL_POWEROKIN_MASK (0x80UL)
#define SD_HOST_MEM_CTL_POWEROKIN_SHIFT (7UL)
#define SD_HOST_MEM_CTL_POWERONIN_MASK (0x40UL)
#define SD_HOST_MEM_CTL_POWERONIN_SHIFT (6UL)
#define SD_HOST_MEM_CTL_ISO_MASK (0x20UL)
#define SD_HOST_MEM_CTL_ISO_SHIFT (5UL)
#define SD_HOST_MEM_CTL_TM_MASK (0x1fUL)
#define SD_HOST_MEM_CTL_TM_SHIFT (0UL)




typedef uint32_t SD_HOST_DELAY_LINE_CTL_TYPE;
#define SD_HOST_DELAY_LINE_CTL_ASYNCWKUPENA_MASK (0x400000UL)
#define SD_HOST_DELAY_LINE_CTL_ASYNCWKUPENA_SHIFT (22UL)
#define SD_HOST_DELAY_LINE_CTL_TUNINGCOUNT_MASK (0x3f0000UL)
#define SD_HOST_DELAY_LINE_CTL_TUNINGCOUNT_SHIFT (16UL)
#define SD_HOST_DELAY_LINE_CTL_OTAPDLYENA_MASK (0x1000UL)
#define SD_HOST_DELAY_LINE_CTL_OTAPDLYENA_SHIFT (12UL)
#define SD_HOST_DELAY_LINE_CTL_OTAPDLYSEL_MASK (0xf00UL)
#define SD_HOST_DELAY_LINE_CTL_OTAPDLYSEL_SHIFT (8UL)
#define SD_HOST_DELAY_LINE_CTL_ITAPCHGWIN_MASK (0x40UL)
#define SD_HOST_DELAY_LINE_CTL_ITAPCHGWIN_SHIFT (6UL)
#define SD_HOST_DELAY_LINE_CTL_ITAPDLYENA_MASK (0x20UL)
#define SD_HOST_DELAY_LINE_CTL_ITAPDLYENA_SHIFT (5UL)
#define SD_HOST_DELAY_LINE_CTL_ITAPDLYSEL_MASK (0x1fUL)
#define SD_HOST_DELAY_LINE_CTL_ITAPDLYSEL_SHIFT (0UL)




typedef uint32_t SD_HOST_MISC_CTL_TYPE;
#define SD_HOST_MISC_CTL_AXIMST_ARPROT_MASK (0x70000UL)
#define SD_HOST_MISC_CTL_AXIMST_ARPROT_SHIFT (16UL)
#define SD_HOST_MISC_CTL_AXIMST_ARCACHE_MASK (0xf000UL)
#define SD_HOST_MISC_CTL_AXIMST_ARCACHE_SHIFT (12UL)
#define SD_HOST_MISC_CTL_AXIMST_ARLOCK_MASK (0xc00UL)
#define SD_HOST_MISC_CTL_AXIMST_ARLOCK_SHIFT (10UL)
#define SD_HOST_MISC_CTL_AXIMST_AWPROT_MASK (0x380UL)
#define SD_HOST_MISC_CTL_AXIMST_AWPROT_SHIFT (7UL)
#define SD_HOST_MISC_CTL_AXIMST_AWCACHE_MASK (0x78UL)
#define SD_HOST_MISC_CTL_AXIMST_AWCACHE_SHIFT (3UL)
#define SD_HOST_MISC_CTL_AXIMST_AWLOCK_MASK (0x6UL)
#define SD_HOST_MISC_CTL_AXIMST_AWLOCK_SHIFT (1UL)
#define SD_HOST_MISC_CTL_AHB_BURST_EN_MASK (0x1UL)
#define SD_HOST_MISC_CTL_AHB_BURST_EN_SHIFT (0UL)




typedef uint32_t SD_HOST_DEBUG_CTL_TYPE;
#define SD_HOST_DEBUG_CTL_SEL_MASK (0xfUL)
#define SD_HOST_DEBUG_CTL_SEL_SHIFT (0UL)




typedef volatile struct COMP_PACKED _SD_HOST_RDBType {
    SD_HOST_CORECFG_DDR50_PRESET_TYPE corecfg_ddr50_preset; /* OFFSET: 0x0 */
    SD_HOST_CORECFG_SDR104_PRESET_TYPE corecfg_sdr104_preset; /* OFFSET: 0x4 */
    SD_HOST_CORECFG_SDR50_PRESET_TYPE corecfg_sdr50_preset; /* OFFSET: 0x8 */
    SD_HOST_CORECFG_SDR25_PRESET_TYPE corecfg_sdr25_preset; /* OFFSET: 0xc */
    SD_HOST_CORECFG_SDR12_PRESET_TYPE corecfg_sdr12_preset; /* OFFSET: 0x10 */
    SD_HOST_CORECFG_HSPD_PRESET_TYPE corecfg_hspd_preset; /* OFFSET: 0x14 */
    SD_HOST_CORECFG_DSPD_PRESET_TYPE corecfg_dspd_preset; /* OFFSET: 0x18 */
    SD_HOST_CORECFG_INIT_PRESET_TYPE corecfg_init_preset; /* OFFSET: 0x1c */
    SD_HOST_CAPAB_REG_IN_0_TYPE capab_reg_in_0; /* OFFSET: 0x20 */
    SD_HOST_CAPAB_REG_IN_1_TYPE capab_reg_in_1; /* OFFSET: 0x24 */
    SD_HOST_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x28 */
    SD_HOST_MAX_CUR_CAPAB_REG_IN_TYPE max_cur_capab_reg_in; /* OFFSET: 0x30 */
    SD_HOST_MEM_CTL_TYPE mem_ctl; /* OFFSET: 0x34 */
    SD_HOST_DELAY_LINE_CTL_TYPE delay_line_ctl; /* OFFSET: 0x38 */
    SD_HOST_MISC_CTL_TYPE misc_ctl; /* OFFSET: 0x3c */
    SD_HOST_DEBUG_CTL_TYPE debug_ctl; /* OFFSET: 0x40 */
} SD_HOST_RDBType;


#define SD_HOST_BASE                    (0x4001A800UL)



#define SD_HOST_MAX_HW_ID               (1UL)

#endif /* SD_HOST_RDB_H */
