/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file spi_rdb.h
    @brief RDB File for SPI

    @version 2018May25_rdb
*/

#ifndef SPI_RDB_H
#define SPI_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SPI_SSPCR0_TYPE;
#define SPI_SSPCR0_SCR_MASK (0xff00UL)
#define SPI_SSPCR0_SCR_SHIFT (8UL)
#define SPI_SSPCR0_SPH_MASK (0x80UL)
#define SPI_SSPCR0_SPH_SHIFT (7UL)
#define SPI_SSPCR0_SPO_MASK (0x40UL)
#define SPI_SSPCR0_SPO_SHIFT (6UL)
#define SPI_SSPCR0_FRF_MASK (0x30UL)
#define SPI_SSPCR0_FRF_SHIFT (4UL)
#define SPI_SSPCR0_DSS_MASK (0xfUL)
#define SPI_SSPCR0_DSS_SHIFT (0UL)




typedef uint32_t SPI_SSPCR1_TYPE;
#define SPI_SSPCR1_SOD_MASK (0x8UL)
#define SPI_SSPCR1_SOD_SHIFT (3UL)
#define SPI_SSPCR1_MS_MASK (0x4UL)
#define SPI_SSPCR1_MS_SHIFT (2UL)
#define SPI_SSPCR1_SSE_MASK (0x2UL)
#define SPI_SSPCR1_SSE_SHIFT (1UL)




typedef uint32_t SPI_SSPDR_TYPE;
#define SPI_SSPDR_DATA_MASK (0xffffUL)
#define SPI_SSPDR_DATA_SHIFT (0UL)




typedef uint32_t SPI_SSPSR_TYPE;
#define SPI_SSPSR_BSY_MASK (0x10UL)
#define SPI_SSPSR_BSY_SHIFT (4UL)
#define SPI_SSPSR_RFF_MASK (0x8UL)
#define SPI_SSPSR_RFF_SHIFT (3UL)
#define SPI_SSPSR_RNE_MASK (0x4UL)
#define SPI_SSPSR_RNE_SHIFT (2UL)
#define SPI_SSPSR_TNF_MASK (0x2UL)
#define SPI_SSPSR_TNF_SHIFT (1UL)
#define SPI_SSPSR_TFE_MASK (0x1UL)
#define SPI_SSPSR_TFE_SHIFT (0UL)




typedef uint32_t SPI_SSPCPSR_TYPE;
#define SPI_SSPCPSR_CPSDVSR_MASK (0xffUL)
#define SPI_SSPCPSR_CPSDVSR_SHIFT (0UL)




typedef uint32_t SPI_SSPIMSC_TYPE;
#define SPI_SSPIMSC_TXIM_MASK (0x8UL)
#define SPI_SSPIMSC_TXIM_SHIFT (3UL)
#define SPI_SSPIMSC_RXIM_MASK (0x4UL)
#define SPI_SSPIMSC_RXIM_SHIFT (2UL)
#define SPI_SSPIMSC_RTIM_MASK (0x2UL)
#define SPI_SSPIMSC_RTIM_SHIFT (1UL)
#define SPI_SSPIMSC_RORIM_MASK (0x1UL)
#define SPI_SSPIMSC_RORIM_SHIFT (0UL)




typedef uint32_t SPI_SSPRIS_TYPE;
#define SPI_SSPRIS_TXRIS_MASK (0x8UL)
#define SPI_SSPRIS_TXRIS_SHIFT (3UL)
#define SPI_SSPRIS_RXRIS_MASK (0x4UL)
#define SPI_SSPRIS_RXRIS_SHIFT (2UL)
#define SPI_SSPRIS_RTRIS_MASK (0x2UL)
#define SPI_SSPRIS_RTRIS_SHIFT (1UL)
#define SPI_SSPRIS_RORRIS_MASK (0x1UL)
#define SPI_SSPRIS_RORRIS_SHIFT (0UL)




typedef uint32_t SPI_SSPMIS_TYPE;
#define SPI_SSPMIS_TXMIS_MASK (0x8UL)
#define SPI_SSPMIS_TXMIS_SHIFT (3UL)
#define SPI_SSPMIS_RXMIS_MASK (0x4UL)
#define SPI_SSPMIS_RXMIS_SHIFT (2UL)
#define SPI_SSPMIS_RTMIS_MASK (0x2UL)
#define SPI_SSPMIS_RTMIS_SHIFT (1UL)
#define SPI_SSPMIS_RORMIS_MASK (0x1UL)
#define SPI_SSPMIS_RORMIS_SHIFT (0UL)




typedef uint32_t SPI_SSPICR_TYPE;
#define SPI_SSPICR_RTIC_MASK (0x2UL)
#define SPI_SSPICR_RTIC_SHIFT (1UL)
#define SPI_SSPICR_RORIC_MASK (0x1UL)
#define SPI_SSPICR_RORIC_SHIFT (0UL)




typedef uint32_t SPI_SSPDMACR_TYPE;
#define SPI_SSPDMACR_TXDMAE_MASK (0x2UL)
#define SPI_SSPDMACR_TXDMAE_SHIFT (1UL)
#define SPI_SSPDMACR_RXDMAE_MASK (0x1UL)
#define SPI_SSPDMACR_RXDMAE_SHIFT (0UL)




typedef uint8_t SPI_RESERVED_TYPE;




typedef uint32_t SPI_SSPTCR_TYPE;
#define SPI_SSPTCR_TESTFIFO_MASK (0x2UL)
#define SPI_SSPTCR_TESTFIFO_SHIFT (1UL)
#define SPI_SSPTCR_ITEN_MASK (0x1UL)
#define SPI_SSPTCR_ITEN_SHIFT (0UL)




typedef uint32_t SPI_SSPITIP_TYPE;
#define SPI_SSPITIP_SSPTXDMACLR_MASK (0x10UL)
#define SPI_SSPITIP_SSPTXDMACLR_SHIFT (4UL)
#define SPI_SSPITIP_SSPRXDMACLR_MASK (0x8UL)
#define SPI_SSPITIP_SSPRXDMACLR_SHIFT (3UL)
#define SPI_SSPITIP_SSPCLKIN_MASK (0x4UL)
#define SPI_SSPITIP_SSPCLKIN_SHIFT (2UL)
#define SPI_SSPITIP_SSPFSSIN_MASK (0x2UL)
#define SPI_SSPITIP_SSPFSSIN_SHIFT (1UL)
#define SPI_SSPITIP_SSPRXD_MASK (0x1UL)
#define SPI_SSPITIP_SSPRXD_SHIFT (0UL)




typedef uint32_t SPI_SSPITOP_TYPE;
#define SPI_SSPITOP_SSPTXDMASREQ_MASK (0x2000UL)
#define SPI_SSPITOP_SSPTXDMASREQ_SHIFT (13UL)
#define SPI_SSPITOP_SSPTXDMABREQ_MASK (0x1000UL)
#define SPI_SSPITOP_SSPTXDMABREQ_SHIFT (12UL)
#define SPI_SSPITOP_SSPRXDMASREQ_MASK (0x800UL)
#define SPI_SSPITOP_SSPRXDMASREQ_SHIFT (11UL)
#define SPI_SSPITOP_SSPRXDMABREQ_MASK (0x400UL)
#define SPI_SSPITOP_SSPRXDMABREQ_SHIFT (10UL)
#define SPI_SSPITOP_SSPINTR_MASK (0x200UL)
#define SPI_SSPITOP_SSPINTR_SHIFT (9UL)
#define SPI_SSPITOP_SSPTXINTR_MASK (0x100UL)
#define SPI_SSPITOP_SSPTXINTR_SHIFT (8UL)
#define SPI_SSPITOP_SSPRXINTR_MASK (0x80UL)
#define SPI_SSPITOP_SSPRXINTR_SHIFT (7UL)
#define SPI_SSPITOP_SSPRTINTR_MASK (0x40UL)
#define SPI_SSPITOP_SSPRTINTR_SHIFT (6UL)
#define SPI_SSPITOP_SSPRORINTR_MASK (0x20UL)
#define SPI_SSPITOP_SSPRORINTR_SHIFT (5UL)
#define SPI_SSPITOP_NSSPOE_MASK (0x10UL)
#define SPI_SSPITOP_NSSPOE_SHIFT (4UL)
#define SPI_SSPITOP_NSSPCTLOE_MASK (0x8UL)
#define SPI_SSPITOP_NSSPCTLOE_SHIFT (3UL)
#define SPI_SSPITOP_SSPCLKOUT_MASK (0x4UL)
#define SPI_SSPITOP_SSPCLKOUT_SHIFT (2UL)
#define SPI_SSPITOP_SSPFSSOUT_MASK (0x2UL)
#define SPI_SSPITOP_SSPFSSOUT_SHIFT (1UL)
#define SPI_SSPITOP_SSPTXD_MASK (0x1UL)
#define SPI_SSPITOP_SSPTXD_SHIFT (0UL)




typedef uint32_t SPI_SSPTDR_TYPE;
#define SPI_SSPTDR_DATA_MASK (0xffffUL)
#define SPI_SSPTDR_DATA_SHIFT (0UL)




typedef uint32_t SPI_SSPPERIPHID0_TYPE;
#define SPI_SSPPERIPHID0_PARTNUMBER0_MASK (0xffUL)
#define SPI_SSPPERIPHID0_PARTNUMBER0_SHIFT (0UL)




typedef uint32_t SPI_SSPPERIPHID1_TYPE;
#define SPI_SSPPERIPHID1_DESIGNER0_MASK (0xf0UL)
#define SPI_SSPPERIPHID1_DESIGNER0_SHIFT (4UL)
#define SPI_SSPPERIPHID1_PARTNUMBER1_MASK (0xfUL)
#define SPI_SSPPERIPHID1_PARTNUMBER1_SHIFT (0UL)




typedef uint32_t SPI_SSPPERIPHID2_TYPE;
#define SPI_SSPPERIPHID2_REVISION_MASK (0xf0UL)
#define SPI_SSPPERIPHID2_REVISION_SHIFT (4UL)
#define SPI_SSPPERIPHID2_DESIGNER1_MASK (0xfUL)
#define SPI_SSPPERIPHID2_DESIGNER1_SHIFT (0UL)




typedef uint32_t SPI_SSPPERIPHID3_TYPE;
#define SPI_SSPPERIPHID3_CONFIGURATION_MASK (0xffUL)
#define SPI_SSPPERIPHID3_CONFIGURATION_SHIFT (0UL)




typedef uint32_t SPI_SSPPCELLID0_TYPE;
#define SPI_SSPPCELLID0_SSPPCELLID0_MASK (0xffUL)
#define SPI_SSPPCELLID0_SSPPCELLID0_SHIFT (0UL)




typedef uint32_t SPI_SSPPCELLID1_TYPE;
#define SPI_SSPPCELLID1_SSPPCELLID1_MASK (0xffUL)
#define SPI_SSPPCELLID1_SSPPCELLID1_SHIFT (0UL)




typedef uint32_t SPI_SSPPCELLID2_TYPE;
#define SPI_SSPPCELLID2_SSPPCELLID2_MASK (0xffUL)
#define SPI_SSPPCELLID2_SSPPCELLID2_SHIFT (0UL)




typedef uint32_t SPI_SSPPCELLID3_TYPE;
#define SPI_SSPPCELLID3_SSPPCELLID3_MASK (0xffUL)
#define SPI_SSPPCELLID3_SSPPCELLID3_SHIFT (0UL)




typedef volatile struct COMP_PACKED _SPI_RDBType {
    SPI_SSPCR0_TYPE sspcr0; /* OFFSET: 0x0 */
    SPI_SSPCR1_TYPE sspcr1; /* OFFSET: 0x4 */
    SPI_SSPDR_TYPE sspdr; /* OFFSET: 0x8 */
    SPI_SSPSR_TYPE sspsr; /* OFFSET: 0xc */
    SPI_SSPCPSR_TYPE sspcpsr; /* OFFSET: 0x10 */
    SPI_SSPIMSC_TYPE sspimsc; /* OFFSET: 0x14 */
    SPI_SSPRIS_TYPE sspris; /* OFFSET: 0x18 */
    SPI_SSPMIS_TYPE sspmis; /* OFFSET: 0x1c */
    SPI_SSPICR_TYPE sspicr; /* OFFSET: 0x20 */
    SPI_SSPDMACR_TYPE sspdmacr; /* OFFSET: 0x24 */
    SPI_RESERVED_TYPE rsvd0[88]; /* OFFSET: 0x28 */
    SPI_SSPTCR_TYPE ssptcr; /* OFFSET: 0x80 */
    SPI_SSPITIP_TYPE sspitip; /* OFFSET: 0x84 */
    SPI_SSPITOP_TYPE sspitop; /* OFFSET: 0x88 */
    SPI_SSPTDR_TYPE ssptdr; /* OFFSET: 0x8c */
    SPI_RESERVED_TYPE rsvd1[3920]; /* OFFSET: 0x90 */
    SPI_SSPPERIPHID0_TYPE sspperiphid0; /* OFFSET: 0xfe0 */
    SPI_SSPPERIPHID1_TYPE sspperiphid1; /* OFFSET: 0xfe4 */
    SPI_SSPPERIPHID2_TYPE sspperiphid2; /* OFFSET: 0xfe8 */
    SPI_SSPPERIPHID3_TYPE sspperiphid3; /* OFFSET: 0xfec */
    SPI_SSPPCELLID0_TYPE ssppcellid0; /* OFFSET: 0xff0 */
    SPI_SSPPCELLID1_TYPE ssppcellid1; /* OFFSET: 0xff4 */
    SPI_SSPPCELLID2_TYPE ssppcellid2; /* OFFSET: 0xff8 */
    SPI_SSPPCELLID3_TYPE ssppcellid3; /* OFFSET: 0xffc */
} SPI_RDBType;


#define SPI0_BASE                       (0x4000A000UL)

#define SPI1_BASE                       (0x4000B000UL)

#define SPI2_BASE                       (0x4000C000UL)



#define SPI_MAX_HW_ID                   (3UL)

#endif /* SPI_RDB_H */
