/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file tim_rdb.h
    @brief RDB File for TIM

    @version 2018May25_rdb
*/

#ifndef TIM_RDB_H
#define TIM_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t TIM_ER1LOAD_TYPE;
#define TIM_ER1LOAD_TIMER1LOAD_MASK (0xffffffffUL)
#define TIM_ER1LOAD_TIMER1LOAD_SHIFT (0UL)




typedef uint32_t TIM_ER1VALUE_TYPE;
#define TIM_ER1VALUE_TIMER1VALUE_MASK (0xffffffffUL)
#define TIM_ER1VALUE_TIMER1VALUE_SHIFT (0UL)




typedef uint32_t TIM_ER1CONTROL_TYPE;
#define TIM_ER1CONTROL_TIMER1EN_MASK (0x80UL)
#define TIM_ER1CONTROL_TIMER1EN_SHIFT (7UL)
#define TIM_ER1CONTROL_TIMER1MODE_MASK (0x40UL)
#define TIM_ER1CONTROL_TIMER1MODE_SHIFT (6UL)
#define TIM_ER1CONTROL_INTENABLE1_MASK (0x20UL)
#define TIM_ER1CONTROL_INTENABLE1_SHIFT (5UL)
#define TIM_ER1CONTROL_TIMER1PRE_MASK (0xcUL)
#define TIM_ER1CONTROL_TIMER1PRE_SHIFT (2UL)
#define TIM_ER1CONTROL_TIMER1SIZE_MASK (0x2UL)
#define TIM_ER1CONTROL_TIMER1SIZE_SHIFT (1UL)
#define TIM_ER1CONTROL_ONESHOT_TIMER1_MASK (0x1UL)
#define TIM_ER1CONTROL_ONESHOT_TIMER1_SHIFT (0UL)




typedef uint32_t TIM_ER1INTCLR_TYPE;
#define TIM_ER1INTCLR_TIMER1INTCLR_MASK (0x1UL)
#define TIM_ER1INTCLR_TIMER1INTCLR_SHIFT (0UL)




typedef uint32_t TIM_ER1RIS_TYPE;
#define TIM_ER1RIS_TIMER1RIS_MASK (0x1UL)
#define TIM_ER1RIS_TIMER1RIS_SHIFT (0UL)




typedef uint32_t TIM_ER1MIS_TYPE;
#define TIM_ER1MIS_TIMER1MIS_MASK (0x1UL)
#define TIM_ER1MIS_TIMER1MIS_SHIFT (0UL)




typedef uint32_t TIM_ER1BGLOAD_TYPE;
#define TIM_ER1BGLOAD_TIMER1BGLOAD_MASK (0xffffffffUL)
#define TIM_ER1BGLOAD_TIMER1BGLOAD_SHIFT (0UL)




typedef uint8_t TIM_RESERVED_TYPE;




typedef uint32_t TIM_ER2LOAD_TYPE;
#define TIM_ER2LOAD_TIMER2LOAD_MASK (0xffffffffUL)
#define TIM_ER2LOAD_TIMER2LOAD_SHIFT (0UL)




typedef uint32_t TIM_ER2VALUE_TYPE;
#define TIM_ER2VALUE_TIMER2VALUE_MASK (0xffffffffUL)
#define TIM_ER2VALUE_TIMER2VALUE_SHIFT (0UL)




typedef uint32_t TIM_ER2CONTROL_TYPE;
#define TIM_ER2CONTROL_TIMER2EN_MASK (0x80UL)
#define TIM_ER2CONTROL_TIMER2EN_SHIFT (7UL)
#define TIM_ER2CONTROL_TIMER2MODE_MASK (0x40UL)
#define TIM_ER2CONTROL_TIMER2MODE_SHIFT (6UL)
#define TIM_ER2CONTROL_INTENABLE2_MASK (0x20UL)
#define TIM_ER2CONTROL_INTENABLE2_SHIFT (5UL)
#define TIM_ER2CONTROL_TIMER2PRE_MASK (0xcUL)
#define TIM_ER2CONTROL_TIMER2PRE_SHIFT (2UL)
#define TIM_ER2CONTROL_TIMER2SIZE_MASK (0x2UL)
#define TIM_ER2CONTROL_TIMER2SIZE_SHIFT (1UL)
#define TIM_ER2CONTROL_ONESHOT_TIMER2_MASK (0x1UL)
#define TIM_ER2CONTROL_ONESHOT_TIMER2_SHIFT (0UL)




typedef uint32_t TIM_ER2INTCLR_TYPE;
#define TIM_ER2INTCLR_TIMER2INTCLR_MASK (0x1UL)
#define TIM_ER2INTCLR_TIMER2INTCLR_SHIFT (0UL)




typedef uint32_t TIM_ER2RIS_TYPE;
#define TIM_ER2RIS_TIMER2RIS_MASK (0x1UL)
#define TIM_ER2RIS_TIMER2RIS_SHIFT (0UL)




typedef uint32_t TIM_ER2MIS_TYPE;
#define TIM_ER2MIS_TIMER2MIS_MASK (0x1UL)
#define TIM_ER2MIS_TIMER2MIS_SHIFT (0UL)




typedef uint32_t TIM_ER2BGLOAD_TYPE;
#define TIM_ER2BGLOAD_TIMER2BGLOAD_MASK (0xffffffffUL)
#define TIM_ER2BGLOAD_TIMER2BGLOAD_SHIFT (0UL)




typedef uint32_t TIM_ERITCR_TYPE;
#define TIM_ERITCR_ITEN_MASK (0x1UL)
#define TIM_ERITCR_ITEN_SHIFT (0UL)




typedef uint32_t TIM_ERITOP_TYPE;
#define TIM_ERITOP_TIMINT2_MASK (0x2UL)
#define TIM_ERITOP_TIMINT2_SHIFT (1UL)
#define TIM_ERITOP_TIMINT1_MASK (0x1UL)
#define TIM_ERITOP_TIMINT1_SHIFT (0UL)




typedef uint32_t TIM_ERPERIPHID0_TYPE;
#define TIM_ERPERIPHID0_PARTNUMBER0_MASK (0xffUL)
#define TIM_ERPERIPHID0_PARTNUMBER0_SHIFT (0UL)




typedef uint32_t TIM_ERPERIPHID1_TYPE;
#define TIM_ERPERIPHID1_DESIGNER0_MASK (0xf0UL)
#define TIM_ERPERIPHID1_DESIGNER0_SHIFT (4UL)
#define TIM_ERPERIPHID1_PARTNUMBER1_MASK (0xfUL)
#define TIM_ERPERIPHID1_PARTNUMBER1_SHIFT (0UL)




typedef uint32_t TIM_ERPERIPHID2_TYPE;
#define TIM_ERPERIPHID2_REVISION_MASK (0xf0UL)
#define TIM_ERPERIPHID2_REVISION_SHIFT (4UL)
#define TIM_ERPERIPHID2_DESIGNER1_MASK (0xfUL)
#define TIM_ERPERIPHID2_DESIGNER1_SHIFT (0UL)




typedef uint32_t TIM_ERPERIPHID3_TYPE;
#define TIM_ERPERIPHID3_CONFIGURATION_MASK (0xffUL)
#define TIM_ERPERIPHID3_CONFIGURATION_SHIFT (0UL)




typedef uint32_t TIM_ERPCELLID0_TYPE;
#define TIM_ERPCELLID0_TIMERPCELLID0_MASK (0xffUL)
#define TIM_ERPCELLID0_TIMERPCELLID0_SHIFT (0UL)




typedef uint32_t TIM_ERPCELLID1_TYPE;
#define TIM_ERPCELLID1_TIMERPCELLID1_MASK (0xffUL)
#define TIM_ERPCELLID1_TIMERPCELLID1_SHIFT (0UL)




typedef uint32_t TIM_ERPCELLID2_TYPE;
#define TIM_ERPCELLID2_TIMERPCELLID2_MASK (0xffUL)
#define TIM_ERPCELLID2_TIMERPCELLID2_SHIFT (0UL)




typedef uint32_t TIM_ERPCELLID3_TYPE;
#define TIM_ERPCELLID3_TIMERPCELLID3_MASK (0xffUL)
#define TIM_ERPCELLID3_TIMERPCELLID3_SHIFT (0UL)


typedef volatile struct COMP_PACKED _TIM_CHAN_RDBType {
    TIM_ER1LOAD_TYPE timer1load; /* OFFSET: 0x0 */
    TIM_ER1VALUE_TYPE timer1value; /* OFFSET: 0x4 */
    TIM_ER1CONTROL_TYPE timer1control; /* OFFSET: 0x8 */
    TIM_ER1INTCLR_TYPE timer1intclr; /* OFFSET: 0xc */
    TIM_ER1RIS_TYPE timer1ris; /* OFFSET: 0x10 */
    TIM_ER1MIS_TYPE timer1mis; /* OFFSET: 0x14 */
    TIM_ER1BGLOAD_TYPE timer1bgload; /* OFFSET: 0x18 */
    TIM_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x1c */
} TIM_CHAN_RDBType;



typedef volatile struct COMP_PACKED _TIM_RDBType {
    TIM_CHAN_RDBType tim_chan_regs[2]; /* OFFSET: 0x0 */
    TIM_RESERVED_TYPE rsvd1[3776]; /* OFFSET: 0x40 */
    TIM_ERITCR_TYPE timeritcr; /* OFFSET: 0xf00 */
    TIM_ERITOP_TYPE timeritop; /* OFFSET: 0xf04 */
    TIM_RESERVED_TYPE rsvd2[216]; /* OFFSET: 0xf08 */
    TIM_ERPERIPHID0_TYPE timerperiphid0; /* OFFSET: 0xfe0 */
    TIM_ERPERIPHID1_TYPE timerperiphid1; /* OFFSET: 0xfe4 */
    TIM_ERPERIPHID2_TYPE timerperiphid2; /* OFFSET: 0xfe8 */
    TIM_ERPERIPHID3_TYPE timerperiphid3; /* OFFSET: 0xfec */
    TIM_ERPCELLID0_TYPE timerpcellid0; /* OFFSET: 0xff0 */
    TIM_ERPCELLID1_TYPE timerpcellid1; /* OFFSET: 0xff4 */
    TIM_ERPCELLID2_TYPE timerpcellid2; /* OFFSET: 0xff8 */
    TIM_ERPCELLID3_TYPE timerpcellid3; /* OFFSET: 0xffc */
} TIM_RDBType;


#define TIM_BASE                        (0x40010000UL)

#define TIM_CHAN_RDBTYPE_OFFSET         (0x40010000UL)



#define TIM_MAX_HW_ID                   (1UL)


#define TIM_CLOCK                       (50000000UL)


#define TIM_MAX_CHANNELS                (2UL)

#endif /* TIM_RDB_H */
