/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file uart_rdb.h
    @brief RDB File for UART

    @version 2018May25_rdb
*/

#ifndef UART_RDB_H
#define UART_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t UART_UARTDR_TYPE;
#define UART_UARTDR_OE_MASK (0x800UL)
#define UART_UARTDR_OE_SHIFT (11UL)
#define UART_UARTDR_BE_MASK (0x400UL)
#define UART_UARTDR_BE_SHIFT (10UL)
#define UART_UARTDR_PE_MASK (0x200UL)
#define UART_UARTDR_PE_SHIFT (9UL)
#define UART_UARTDR_FE_MASK (0x100UL)
#define UART_UARTDR_FE_SHIFT (8UL)
#define UART_UARTDR_DATA_MASK (0xffUL)
#define UART_UARTDR_DATA_SHIFT (0UL)




typedef uint32_t UART_UARTRSR_UARTECR_TYPE;
#define UART_UARTRSR_UARTECR_RECEIVE_OE_MASK (0x8UL)
#define UART_UARTRSR_UARTECR_RECEIVE_OE_SHIFT (3UL)
#define UART_UARTRSR_UARTECR_RECEIVE_BE_MASK (0x4UL)
#define UART_UARTRSR_UARTECR_RECEIVE_BE_SHIFT (2UL)
#define UART_UARTRSR_UARTECR_RECEIVE_PE_MASK (0x2UL)
#define UART_UARTRSR_UARTECR_RECEIVE_PE_SHIFT (1UL)
#define UART_UARTRSR_UARTECR_RECEIVE_FE_MASK (0x1UL)
#define UART_UARTRSR_UARTECR_RECEIVE_FE_SHIFT (0UL)




typedef uint8_t UART_RESERVED_TYPE;




typedef uint32_t UART_UARTFR_TYPE;
#define UART_UARTFR_RI_MASK (0x100UL)
#define UART_UARTFR_RI_SHIFT (8UL)
#define UART_UARTFR_TXFE_MASK (0x80UL)
#define UART_UARTFR_TXFE_SHIFT (7UL)
#define UART_UARTFR_RXFF_MASK (0x40UL)
#define UART_UARTFR_RXFF_SHIFT (6UL)
#define UART_UARTFR_TXFF_MASK (0x20UL)
#define UART_UARTFR_TXFF_SHIFT (5UL)
#define UART_UARTFR_RXFE_MASK (0x10UL)
#define UART_UARTFR_RXFE_SHIFT (4UL)
#define UART_UARTFR_BUSY_MASK (0x8UL)
#define UART_UARTFR_BUSY_SHIFT (3UL)
#define UART_UARTFR_DCD_MASK (0x4UL)
#define UART_UARTFR_DCD_SHIFT (2UL)
#define UART_UARTFR_DSR_MASK (0x2UL)
#define UART_UARTFR_DSR_SHIFT (1UL)
#define UART_UARTFR_CTS_MASK (0x1UL)
#define UART_UARTFR_CTS_SHIFT (0UL)




typedef uint32_t UART_UARTILPR_TYPE;
#define UART_UARTILPR_ILPDVSR_MASK (0xffUL)
#define UART_UARTILPR_ILPDVSR_SHIFT (0UL)




typedef uint32_t UART_UARTIBRD_TYPE;
#define UART_UARTIBRD_BAUD_DIVINT_MASK (0xffffUL)
#define UART_UARTIBRD_BAUD_DIVINT_SHIFT (0UL)




typedef uint32_t UART_UARTFBRD_TYPE;
#define UART_UARTFBRD_BAUD_DIVFRAC_MASK (0x3fUL)
#define UART_UARTFBRD_BAUD_DIVFRAC_SHIFT (0UL)




typedef uint32_t UART_UARTLCR_TYPE;
#define UART_UARTLCR_SPS_MASK (0x80UL)
#define UART_UARTLCR_SPS_SHIFT (7UL)
#define UART_UARTLCR_WLEN_MASK (0x60UL)
#define UART_UARTLCR_WLEN_SHIFT (5UL)
#define UART_UARTLCR_FEN_MASK (0x10UL)
#define UART_UARTLCR_FEN_SHIFT (4UL)
#define UART_UARTLCR_STP2_MASK (0x8UL)
#define UART_UARTLCR_STP2_SHIFT (3UL)
#define UART_UARTLCR_EPS_MASK (0x4UL)
#define UART_UARTLCR_EPS_SHIFT (2UL)
#define UART_UARTLCR_PEN_MASK (0x2UL)
#define UART_UARTLCR_PEN_SHIFT (1UL)
#define UART_UARTLCR_BRK_MASK (0x1UL)
#define UART_UARTLCR_BRK_SHIFT (0UL)




typedef uint32_t UART_UARTCR_TYPE;
#define UART_UARTCR_CTSEN_MASK (0x8000UL)
#define UART_UARTCR_CTSEN_SHIFT (15UL)
#define UART_UARTCR_OUT2_MASK (0x2000UL)
#define UART_UARTCR_OUT2_SHIFT (13UL)
#define UART_UARTCR_OUT1_MASK (0x1000UL)
#define UART_UARTCR_OUT1_SHIFT (12UL)
#define UART_UARTCR_RTS_MASK (0x800UL)
#define UART_UARTCR_RTS_SHIFT (11UL)
#define UART_UARTCR_DTR_MASK (0x400UL)
#define UART_UARTCR_DTR_SHIFT (10UL)
#define UART_UARTCR_RXE_MASK (0x200UL)
#define UART_UARTCR_RXE_SHIFT (9UL)
#define UART_UARTCR_TXE_MASK (0x100UL)
#define UART_UARTCR_TXE_SHIFT (8UL)
#define UART_UARTCR_LBE_MASK (0x80UL)
#define UART_UARTCR_LBE_SHIFT (7UL)
#define UART_UARTCR_SIRLP_MASK (0x4UL)
#define UART_UARTCR_SIRLP_SHIFT (2UL)
#define UART_UARTCR_SIREN_MASK (0x2UL)
#define UART_UARTCR_SIREN_SHIFT (1UL)
#define UART_UARTCR_UARTEN_MASK (0x1UL)
#define UART_UARTCR_UARTEN_SHIFT (0UL)




typedef uint32_t UART_UARTIFLS_TYPE;
#define UART_UARTIFLS_RXIFLSEL_MASK (0x38UL)
#define UART_UARTIFLS_RXIFLSEL_SHIFT (3UL)
#define UART_UARTIFLS_TXIFLSEL_MASK (0x7UL)
#define UART_UARTIFLS_TXIFLSEL_SHIFT (0UL)




typedef uint32_t UART_UARTIMSC_TYPE;
#define UART_UARTIMSC_OEIM_MASK (0x400UL)
#define UART_UARTIMSC_OEIM_SHIFT (10UL)
#define UART_UARTIMSC_BEIM_MASK (0x200UL)
#define UART_UARTIMSC_BEIM_SHIFT (9UL)
#define UART_UARTIMSC_PEIM_MASK (0x100UL)
#define UART_UARTIMSC_PEIM_SHIFT (8UL)
#define UART_UARTIMSC_FEIM_MASK (0x80UL)
#define UART_UARTIMSC_FEIM_SHIFT (7UL)
#define UART_UARTIMSC_RTIM_MASK (0x40UL)
#define UART_UARTIMSC_RTIM_SHIFT (6UL)
#define UART_UARTIMSC_TXIM_MASK (0x20UL)
#define UART_UARTIMSC_TXIM_SHIFT (5UL)
#define UART_UARTIMSC_RXIM_MASK (0x10UL)
#define UART_UARTIMSC_RXIM_SHIFT (4UL)
#define UART_UARTIMSC_DSRMIM_MASK (0x8UL)
#define UART_UARTIMSC_DSRMIM_SHIFT (3UL)
#define UART_UARTIMSC_DCDMIM_MASK (0x4UL)
#define UART_UARTIMSC_DCDMIM_SHIFT (2UL)
#define UART_UARTIMSC_CTSMIM_MASK (0x2UL)
#define UART_UARTIMSC_CTSMIM_SHIFT (1UL)
#define UART_UARTIMSC_RIMIM_MASK (0x1UL)
#define UART_UARTIMSC_RIMIM_SHIFT (0UL)




typedef uint32_t UART_UARTRIS_TYPE;
#define UART_UARTRIS_OERIS_MASK (0x400UL)
#define UART_UARTRIS_OERIS_SHIFT (10UL)
#define UART_UARTRIS_BERIS_MASK (0x200UL)
#define UART_UARTRIS_BERIS_SHIFT (9UL)
#define UART_UARTRIS_PERIS_MASK (0x100UL)
#define UART_UARTRIS_PERIS_SHIFT (8UL)
#define UART_UARTRIS_FERIS_MASK (0x80UL)
#define UART_UARTRIS_FERIS_SHIFT (7UL)
#define UART_UARTRIS_RTRIS_MASK (0x40UL)
#define UART_UARTRIS_RTRIS_SHIFT (6UL)
#define UART_UARTRIS_TXRIS_MASK (0x20UL)
#define UART_UARTRIS_TXRIS_SHIFT (5UL)
#define UART_UARTRIS_RXRIS_MASK (0x10UL)
#define UART_UARTRIS_RXRIS_SHIFT (4UL)
#define UART_UARTRIS_DSRRMIS_MASK (0x8UL)
#define UART_UARTRIS_DSRRMIS_SHIFT (3UL)
#define UART_UARTRIS_DCDRMIS_MASK (0x4UL)
#define UART_UARTRIS_DCDRMIS_SHIFT (2UL)
#define UART_UARTRIS_CTSRMIS_MASK (0x2UL)
#define UART_UARTRIS_CTSRMIS_SHIFT (1UL)
#define UART_UARTRIS_RIRMIS_MASK (0x1UL)
#define UART_UARTRIS_RIRMIS_SHIFT (0UL)




typedef uint32_t UART_UARTMIS_TYPE;
#define UART_UARTMIS_OEMIS_MASK (0x400UL)
#define UART_UARTMIS_OEMIS_SHIFT (10UL)
#define UART_UARTMIS_BEMIS_MASK (0x200UL)
#define UART_UARTMIS_BEMIS_SHIFT (9UL)
#define UART_UARTMIS_PEMIS_MASK (0x100UL)
#define UART_UARTMIS_PEMIS_SHIFT (8UL)
#define UART_UARTMIS_FEMIS_MASK (0x80UL)
#define UART_UARTMIS_FEMIS_SHIFT (7UL)
#define UART_UARTMIS_RTMIS_MASK (0x40UL)
#define UART_UARTMIS_RTMIS_SHIFT (6UL)
#define UART_UARTMIS_TXMIS_MASK (0x20UL)
#define UART_UARTMIS_TXMIS_SHIFT (5UL)
#define UART_UARTMIS_RXMIS_MASK (0x10UL)
#define UART_UARTMIS_RXMIS_SHIFT (4UL)
#define UART_UARTMIS_DSRMMIS_MASK (0x8UL)
#define UART_UARTMIS_DSRMMIS_SHIFT (3UL)
#define UART_UARTMIS_DCDMMIS_MASK (0x4UL)
#define UART_UARTMIS_DCDMMIS_SHIFT (2UL)
#define UART_UARTMIS_CTSMMIS_MASK (0x2UL)
#define UART_UARTMIS_CTSMMIS_SHIFT (1UL)
#define UART_UARTMIS_RIMMIS_MASK (0x1UL)
#define UART_UARTMIS_RIMMIS_SHIFT (0UL)




typedef uint32_t UART_UARTICR_TYPE;
#define UART_UARTICR_OEIC_MASK (0x400UL)
#define UART_UARTICR_OEIC_SHIFT (10UL)
#define UART_UARTICR_BEIC_MASK (0x200UL)
#define UART_UARTICR_BEIC_SHIFT (9UL)
#define UART_UARTICR_PEIC_MASK (0x100UL)
#define UART_UARTICR_PEIC_SHIFT (8UL)
#define UART_UARTICR_FEIC_MASK (0x80UL)
#define UART_UARTICR_FEIC_SHIFT (7UL)
#define UART_UARTICR_RTIC_MASK (0x40UL)
#define UART_UARTICR_RTIC_SHIFT (6UL)
#define UART_UARTICR_TXIC_MASK (0x20UL)
#define UART_UARTICR_TXIC_SHIFT (5UL)
#define UART_UARTICR_RXIC_MASK (0x10UL)
#define UART_UARTICR_RXIC_SHIFT (4UL)
#define UART_UARTICR_DSRMIC_MASK (0x8UL)
#define UART_UARTICR_DSRMIC_SHIFT (3UL)
#define UART_UARTICR_DCDMIC_MASK (0x4UL)
#define UART_UARTICR_DCDMIC_SHIFT (2UL)
#define UART_UARTICR_CTSMIC_MASK (0x2UL)
#define UART_UARTICR_CTSMIC_SHIFT (1UL)
#define UART_UARTICR_RIMIC_MASK (0x1UL)
#define UART_UARTICR_RIMIC_SHIFT (0UL)




typedef uint32_t UART_UARTDMACR_TYPE;
#define UART_UARTDMACR_DMAONERR_MASK (0x4UL)
#define UART_UARTDMACR_DMAONERR_SHIFT (2UL)
#define UART_UARTDMACR_TXDMAE_MASK (0x2UL)
#define UART_UARTDMACR_TXDMAE_SHIFT (1UL)
#define UART_UARTDMACR_RXDMAE_MASK (0x1UL)
#define UART_UARTDMACR_RXDMAE_SHIFT (0UL)




typedef uint32_t UART_UARTPERIPHID0_TYPE;
#define UART_UARTPERIPHID0_PARTNUMBER0_MASK (0xffUL)
#define UART_UARTPERIPHID0_PARTNUMBER0_SHIFT (0UL)




typedef uint32_t UART_UARTPERIPHID1_TYPE;
#define UART_UARTPERIPHID1_DESIGNER0_MASK (0xf0UL)
#define UART_UARTPERIPHID1_DESIGNER0_SHIFT (4UL)
#define UART_UARTPERIPHID1_PARTNUMBER1_MASK (0xfUL)
#define UART_UARTPERIPHID1_PARTNUMBER1_SHIFT (0UL)




typedef uint32_t UART_UARTPERIPHID2_TYPE;
#define UART_UARTPERIPHID2_REVISION_MASK (0xf0UL)
#define UART_UARTPERIPHID2_REVISION_SHIFT (4UL)
#define UART_UARTPERIPHID2_DESIGNER1_MASK (0xfUL)
#define UART_UARTPERIPHID2_DESIGNER1_SHIFT (0UL)




typedef uint32_t UART_UARTPERIPHID3_TYPE;
#define UART_UARTPERIPHID3_CONFIGURATION_MASK (0xffUL)
#define UART_UARTPERIPHID3_CONFIGURATION_SHIFT (0UL)




typedef uint32_t UART_UARTPCELLID0_TYPE;
#define UART_UARTPCELLID0_UARTPCELLID0_MASK (0xffUL)
#define UART_UARTPCELLID0_UARTPCELLID0_SHIFT (0UL)




typedef uint32_t UART_UARTPCELLID1_TYPE;
#define UART_UARTPCELLID1_UARTPCELLID1_MASK (0xffUL)
#define UART_UARTPCELLID1_UARTPCELLID1_SHIFT (0UL)




typedef uint32_t UART_UARTPCELLID2_TYPE;
#define UART_UARTPCELLID2_UARTPCELLID2_MASK (0xffUL)
#define UART_UARTPCELLID2_UARTPCELLID2_SHIFT (0UL)




typedef uint32_t UART_UARTPCELLID3_TYPE;
#define UART_UARTPCELLID3_UARTPCELLID3_MASK (0xffUL)
#define UART_UARTPCELLID3_UARTPCELLID3_SHIFT (0UL)




typedef volatile struct COMP_PACKED _UART_RDBType {
    UART_UARTDR_TYPE uartdr; /* OFFSET: 0x0 */
    UART_UARTRSR_UARTECR_TYPE uartrsr_uartecr; /* OFFSET: 0x4 */
    UART_RESERVED_TYPE rsvd0[16]; /* OFFSET: 0x8 */
    UART_UARTFR_TYPE uartfr; /* OFFSET: 0x18 */
    UART_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x1c */
    UART_UARTILPR_TYPE uartilpr; /* OFFSET: 0x20 */
    UART_UARTIBRD_TYPE uartibrd; /* OFFSET: 0x24 */
    UART_UARTFBRD_TYPE uartfbrd; /* OFFSET: 0x28 */
    UART_UARTLCR_TYPE uartlcr; /* OFFSET: 0x2c */
    UART_UARTCR_TYPE uartcr; /* OFFSET: 0x30 */
    UART_UARTIFLS_TYPE uartifls; /* OFFSET: 0x34 */
    UART_UARTIMSC_TYPE uartimsc; /* OFFSET: 0x38 */
    UART_UARTRIS_TYPE uartris; /* OFFSET: 0x3c */
    UART_UARTMIS_TYPE uartmis; /* OFFSET: 0x40 */
    UART_UARTICR_TYPE uarticr; /* OFFSET: 0x44 */
    UART_UARTDMACR_TYPE uartdmacr; /* OFFSET: 0x48 */
    UART_RESERVED_TYPE rsvd2[3988]; /* OFFSET: 0x4c */
    UART_UARTPERIPHID0_TYPE uartperiphid0; /* OFFSET: 0xfe0 */
    UART_UARTPERIPHID1_TYPE uartperiphid1; /* OFFSET: 0xfe4 */
    UART_UARTPERIPHID2_TYPE uartperiphid2; /* OFFSET: 0xfe8 */
    UART_UARTPERIPHID3_TYPE uartperiphid3; /* OFFSET: 0xfec */
    UART_UARTPCELLID0_TYPE uartpcellid0; /* OFFSET: 0xff0 */
    UART_UARTPCELLID1_TYPE uartpcellid1; /* OFFSET: 0xff4 */
    UART_UARTPCELLID2_TYPE uartpcellid2; /* OFFSET: 0xff8 */
    UART_UARTPCELLID3_TYPE uartpcellid3; /* OFFSET: 0xffc */
} UART_RDBType;


#define URT0_BASE                       (0x40002000UL)

#define URT1_BASE                       (0x40003000UL)

#define URT2_BASE                       (0x40004000UL)



#define UART_MAX_HW_ID                  (3UL)


#define UART_CLOCK                      (25000000UL)

#endif /* UART_RDB_H */
