/*****************************************************************************
 Copyright 2019 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file unicam_rdb.h
    @brief RDB File for UNICAM

    @version 2018May25_rdb
*/

#ifndef UNICAM_RDB_H
#define UNICAM_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t UNICAM_CTL_TYPE;
#define UNICAM_CTL_TRIG_FB_UPDATE_MASK (0x80000000UL)
#define UNICAM_CTL_TRIG_FB_UPDATE_SHIFT (31UL)
#define UNICAM_CTL_PAUSE_CAMRX_MASK (0x40000000UL)
#define UNICAM_CTL_PAUSE_CAMRX_SHIFT (30UL)
#define UNICAM_CTL_DISABLE_256CROSS_BURST_W_MASK (0x20000000UL)
#define UNICAM_CTL_DISABLE_256CROSS_BURST_W_SHIFT (29UL)
#define UNICAM_CTL_DISABLE_256CROSS_BURST_R_MASK (0x10000000UL)
#define UNICAM_CTL_DISABLE_256CROSS_BURST_R_SHIFT (28UL)
#define UNICAM_CTL_INT_ON_256_CROSS_MASK (0x8000000UL)
#define UNICAM_CTL_INT_ON_256_CROSS_SHIFT (27UL)
#define UNICAM_CTL_CPI_YUV422_PACK_MASK (0x4000000UL)
#define UNICAM_CTL_CPI_YUV422_PACK_SHIFT (26UL)
#define UNICAM_CTL_INT_ON_TO_HW_SYNC_MASK (0x2000000UL)
#define UNICAM_CTL_INT_ON_TO_HW_SYNC_SHIFT (25UL)
#define UNICAM_CTL_DIS_DB_IE_MASK (0x400000UL)
#define UNICAM_CTL_DIS_DB_IE_SHIFT (22UL)
#define UNICAM_CTL_CPM_MASK (0x300000UL)
#define UNICAM_CTL_CPM_SHIFT (20UL)
#define UNICAM_CTL_OET_MASK (0xff000UL)
#define UNICAM_CTL_OET_SHIFT (12UL)
#define UNICAM_CTL_PFT_MASK (0xf00UL)
#define UNICAM_CTL_PFT_SHIFT (8UL)
#define UNICAM_CTL_SLS_MASK (0x40UL)
#define UNICAM_CTL_SLS_SHIFT (6UL)
#define UNICAM_CTL_SOE_MASK (0x10UL)
#define UNICAM_CTL_SOE_SHIFT (4UL)
#define UNICAM_CTL_CPR_DPHY_MASK (0x8UL)
#define UNICAM_CTL_CPR_DPHY_SHIFT (3UL)
#define UNICAM_CTL_CPR_MASK (0x4UL)
#define UNICAM_CTL_CPR_SHIFT (2UL)
#define UNICAM_CTL_MEN_MASK (0x2UL)
#define UNICAM_CTL_MEN_SHIFT (1UL)
#define UNICAM_CTL_CPE_MASK (0x1UL)
#define UNICAM_CTL_CPE_SHIFT (0UL)




typedef uint32_t UNICAM_STA_TYPE;
#define UNICAM_STA_TO_HW_SYNC_MASK (0x20000000UL)
#define UNICAM_STA_TO_HW_SYNC_SHIFT (29UL)
#define UNICAM_STA_READ_256CROSS_MASK (0x10000000UL)
#define UNICAM_STA_READ_256CROSS_SHIFT (28UL)
#define UNICAM_STA_WRITE_256CROSS_MASK (0x8000000UL)
#define UNICAM_STA_WRITE_256CROSS_SHIFT (27UL)
#define UNICAM_STA_AXIERR_MASK (0x4000000UL)
#define UNICAM_STA_AXIERR_SHIFT (26UL)
#define UNICAM_STA_FIFO_W_ERR_MASK (0x2000000UL)
#define UNICAM_STA_FIFO_W_ERR_SHIFT (25UL)
#define UNICAM_STA_BUF1_NO_MASK (0x800000UL)
#define UNICAM_STA_BUF1_NO_SHIFT (23UL)
#define UNICAM_STA_BUF1_RDY_MASK (0x400000UL)
#define UNICAM_STA_BUF1_RDY_SHIFT (22UL)
#define UNICAM_STA_BUF0_NO_MASK (0x200000UL)
#define UNICAM_STA_BUF0_NO_SHIFT (21UL)
#define UNICAM_STA_BUF0_RDY_MASK (0x100000UL)
#define UNICAM_STA_BUF0_RDY_SHIFT (20UL)
#define UNICAM_STA_PI1_MASK (0x10000UL)
#define UNICAM_STA_PI1_SHIFT (16UL)
#define UNICAM_STA_PI0_MASK (0x8000UL)
#define UNICAM_STA_PI0_SHIFT (15UL)
#define UNICAM_STA_IS_MASK (0x4000UL)
#define UNICAM_STA_IS_SHIFT (14UL)
#define UNICAM_STA_PS_MASK (0x2000UL)
#define UNICAM_STA_PS_SHIFT (13UL)
#define UNICAM_STA_DL_MASK (0x1000UL)
#define UNICAM_STA_DL_SHIFT (12UL)
#define UNICAM_STA_BFO_MASK (0x800UL)
#define UNICAM_STA_BFO_SHIFT (11UL)
#define UNICAM_STA_OFO_MASK (0x400UL)
#define UNICAM_STA_OFO_SHIFT (10UL)
#define UNICAM_STA_IFO_MASK (0x200UL)
#define UNICAM_STA_IFO_SHIFT (9UL)
#define UNICAM_STA_OES_MASK (0x100UL)
#define UNICAM_STA_OES_SHIFT (8UL)
#define UNICAM_STA_CRCE_MASK (0x80UL)
#define UNICAM_STA_CRCE_SHIFT (7UL)
#define UNICAM_STA_PLE_MASK (0x20UL)
#define UNICAM_STA_PLE_SHIFT (5UL)
#define UNICAM_STA_HOE_MASK (0x10UL)
#define UNICAM_STA_HOE_SHIFT (4UL)
#define UNICAM_STA_PBE_MASK (0x8UL)
#define UNICAM_STA_PBE_SHIFT (3UL)
#define UNICAM_STA_SBE_MASK (0x4UL)
#define UNICAM_STA_SBE_SHIFT (2UL)
#define UNICAM_STA_CS_MASK (0x2UL)
#define UNICAM_STA_CS_SHIFT (1UL)
#define UNICAM_STA_SYN_MASK (0x1UL)
#define UNICAM_STA_SYN_SHIFT (0UL)




typedef uint32_t UNICAM_ANA_TYPE;
#define UNICAM_ANA_CORERDY_MASK (0x20000UL)
#define UNICAM_ANA_CORERDY_SHIFT (17UL)
#define UNICAM_ANA_LDO_PU_MASK (0x10000UL)
#define UNICAM_ANA_LDO_PU_SHIFT (16UL)
#define UNICAM_ANA_PTATADJ_MASK (0xf00UL)
#define UNICAM_ANA_PTATADJ_SHIFT (8UL)
#define UNICAM_ANA_CTATADJ_MASK (0xf0UL)
#define UNICAM_ANA_CTATADJ_SHIFT (4UL)
#define UNICAM_ANA_DDL_MASK (0x8UL)
#define UNICAM_ANA_DDL_SHIFT (3UL)
#define UNICAM_ANA_AR_MASK (0x4UL)
#define UNICAM_ANA_AR_SHIFT (2UL)
#define UNICAM_ANA_BPD_MASK (0x2UL)
#define UNICAM_ANA_BPD_SHIFT (1UL)
#define UNICAM_ANA_APD_MASK (0x1UL)
#define UNICAM_ANA_APD_SHIFT (0UL)




typedef uint32_t UNICAM_PRI_TYPE;
#define UNICAM_PRI_EXT_OET_MSB_MASK (0xff000000UL)
#define UNICAM_PRI_EXT_OET_MSB_SHIFT (24UL)
#define UNICAM_PRI_BL_MASK (0x30000UL)
#define UNICAM_PRI_BL_SHIFT (16UL)
#define UNICAM_PRI_BS_MASK (0xf000UL)
#define UNICAM_PRI_BS_SHIFT (12UL)
#define UNICAM_PRI_PP_MASK (0xf00UL)
#define UNICAM_PRI_PP_SHIFT (8UL)
#define UNICAM_PRI_NP_MASK (0xf0UL)
#define UNICAM_PRI_NP_SHIFT (4UL)
#define UNICAM_PRI_PT_MASK (0x6UL)
#define UNICAM_PRI_PT_SHIFT (1UL)
#define UNICAM_PRI_PE_MASK (0x1UL)
#define UNICAM_PRI_PE_SHIFT (0UL)




typedef uint32_t UNICAM_CLK_TYPE;
#define UNICAM_CLK_CLDN_MASK (0x80000000UL)
#define UNICAM_CLK_CLDN_SHIFT (31UL)
#define UNICAM_CLK_CLDP_MASK (0x40000000UL)
#define UNICAM_CLK_CLDP_SHIFT (30UL)
#define UNICAM_CLK_CLSTE_MASK (0x20000000UL)
#define UNICAM_CLK_CLSTE_SHIFT (29UL)
#define UNICAM_CLK_CLS_MASK (0xf000000UL)
#define UNICAM_CLK_CLS_SHIFT (24UL)
#define UNICAM_CLK_CLTRE_MASK (0x10UL)
#define UNICAM_CLK_CLTRE_SHIFT (4UL)
#define UNICAM_CLK_CLHSE_MASK (0x8UL)
#define UNICAM_CLK_CLHSE_SHIFT (3UL)
#define UNICAM_CLK_CLLPE_MASK (0x4UL)
#define UNICAM_CLK_CLLPE_SHIFT (2UL)
#define UNICAM_CLK_CLPD_MASK (0x2UL)
#define UNICAM_CLK_CLPD_SHIFT (1UL)
#define UNICAM_CLK_CLE_MASK (0x1UL)
#define UNICAM_CLK_CLE_SHIFT (0UL)




typedef uint32_t UNICAM_CLT_TYPE;
#define UNICAM_CLT_CLT2_MASK (0xff00UL)
#define UNICAM_CLT_CLT2_SHIFT (8UL)
#define UNICAM_CLT_CLT1_MASK (0xffUL)
#define UNICAM_CLT_CLT1_SHIFT (0UL)




typedef uint32_t UNICAM_DAT0_TYPE;
#define UNICAM_DAT0_DLDNN_MASK (0x80000000UL)
#define UNICAM_DAT0_DLDNN_SHIFT (31UL)
#define UNICAM_DAT0_DLDPN_MASK (0x40000000UL)
#define UNICAM_DAT0_DLDPN_SHIFT (30UL)
#define UNICAM_DAT0_DLSTEN_MASK (0x20000000UL)
#define UNICAM_DAT0_DLSTEN_SHIFT (29UL)
#define UNICAM_DAT0_DLFON_MASK (0x10000000UL)
#define UNICAM_DAT0_DLFON_SHIFT (28UL)
#define UNICAM_DAT0_DLSN_MASK (0xf000000UL)
#define UNICAM_DAT0_DLSN_SHIFT (24UL)
#define UNICAM_DAT0_DLSEN_MASK (0x800000UL)
#define UNICAM_DAT0_DLSEN_SHIFT (23UL)
#define UNICAM_DAT0_DLSMN_MASK (0x20UL)
#define UNICAM_DAT0_DLSMN_SHIFT (5UL)
#define UNICAM_DAT0_DLTREN_MASK (0x10UL)
#define UNICAM_DAT0_DLTREN_SHIFT (4UL)
#define UNICAM_DAT0_DLHSEN_MASK (0x8UL)
#define UNICAM_DAT0_DLHSEN_SHIFT (3UL)
#define UNICAM_DAT0_DLLPEN_MASK (0x4UL)
#define UNICAM_DAT0_DLLPEN_SHIFT (2UL)
#define UNICAM_DAT0_DLPDN_MASK (0x2UL)
#define UNICAM_DAT0_DLPDN_SHIFT (1UL)
#define UNICAM_DAT0_DLEN_MASK (0x1UL)
#define UNICAM_DAT0_DLEN_SHIFT (0UL)




typedef uint32_t UNICAM_DLT_TYPE;
#define UNICAM_DLT_DLT3_MASK (0xff0000UL)
#define UNICAM_DLT_DLT3_SHIFT (16UL)
#define UNICAM_DLT_DLT2_MASK (0xff00UL)
#define UNICAM_DLT_DLT2_SHIFT (8UL)
#define UNICAM_DLT_DLT1_MASK (0xffUL)
#define UNICAM_DLT_DLT1_SHIFT (0UL)




typedef uint32_t UNICAM_CMP0_TYPE;
#define UNICAM_CMP0_PCEN_MASK (0x80000000UL)
#define UNICAM_CMP0_PCEN_SHIFT (31UL)
#define UNICAM_CMP0_GIN_MASK (0x200UL)
#define UNICAM_CMP0_GIN_SHIFT (9UL)
#define UNICAM_CMP0_CPHN_MASK (0x100UL)
#define UNICAM_CMP0_CPHN_SHIFT (8UL)
#define UNICAM_CMP0_PCVCN_MASK (0xc0UL)
#define UNICAM_CMP0_PCVCN_SHIFT (6UL)
#define UNICAM_CMP0_PCDTN_MASK (0x3fUL)
#define UNICAM_CMP0_PCDTN_SHIFT (0UL)




typedef uint32_t UNICAM_CAP0_TYPE;
#define UNICAM_CAP0_CPHV_MASK (0x80000000UL)
#define UNICAM_CAP0_CPHV_SHIFT (31UL)
#define UNICAM_CAP0_CECCN_MASK (0x3f000000UL)
#define UNICAM_CAP0_CECCN_SHIFT (24UL)
#define UNICAM_CAP0_CWCN_MASK (0xffff00UL)
#define UNICAM_CAP0_CWCN_SHIFT (8UL)
#define UNICAM_CAP0_CVCN_MASK (0xc0UL)
#define UNICAM_CAP0_CVCN_SHIFT (6UL)
#define UNICAM_CAP0_CDTN_MASK (0x3fUL)
#define UNICAM_CAP0_CDTN_SHIFT (0UL)




typedef uint32_t UNICAM_CLKACTL_TYPE;
#define UNICAM_CLKACTL_CLAC_MASK (0xffffffffUL)
#define UNICAM_CLKACTL_CLAC_SHIFT (0UL)




typedef uint32_t UNICAM_DATACTL_TYPE;
#define UNICAM_DATACTL_CLAC_MASK (0xffffffffUL)
#define UNICAM_DATACTL_CLAC_SHIFT (0UL)




typedef uint32_t UNICAM_LDOCTL_TYPE;
#define UNICAM_LDOCTL_LDOCTL_MASK (0x3ffffUL)
#define UNICAM_LDOCTL_LDOCTL_SHIFT (0UL)




typedef uint32_t UNICAM_PIOCTL_TYPE;
#define UNICAM_PIOCTL_PIO_CTL_RES_MASK (0x180UL)
#define UNICAM_PIOCTL_PIO_CTL_RES_SHIFT (7UL)
#define UNICAM_PIOCTL_PIO_LPRX_EN_CLK_MASK (0x40UL)
#define UNICAM_PIOCTL_PIO_LPRX_EN_CLK_SHIFT (6UL)
#define UNICAM_PIOCTL_PIO_RX0_EN_MASK (0x20UL)
#define UNICAM_PIOCTL_PIO_RX0_EN_SHIFT (5UL)
#define UNICAM_PIOCTL_PIO_RX1_EN_MASK (0x10UL)
#define UNICAM_PIOCTL_PIO_RX1_EN_SHIFT (4UL)
#define UNICAM_PIOCTL_PIO_RX2_EN_MASK (0x8UL)
#define UNICAM_PIOCTL_PIO_RX2_EN_SHIFT (3UL)
#define UNICAM_PIOCTL_PIO_RX3_EN_MASK (0x4UL)
#define UNICAM_PIOCTL_PIO_RX3_EN_SHIFT (2UL)
#define UNICAM_PIOCTL_PIO_LANE_RX0_EN_MASK (0x2UL)
#define UNICAM_PIOCTL_PIO_LANE_RX0_EN_SHIFT (1UL)
#define UNICAM_PIOCTL_PIO_LANE_RX1_EN_MASK (0x1UL)
#define UNICAM_PIOCTL_PIO_LANE_RX1_EN_SHIFT (0UL)




typedef uint8_t UNICAM_RESERVED_TYPE;




typedef uint32_t UNICAM_DBG0_TYPE;
#define UNICAM_DBG0_L3PK_MASK (0xf8000UL)
#define UNICAM_DBG0_L3PK_SHIFT (15UL)
#define UNICAM_DBG0_L2PK_MASK (0x7c00UL)
#define UNICAM_DBG0_L2PK_SHIFT (10UL)
#define UNICAM_DBG0_L1PK_MASK (0x3e0UL)
#define UNICAM_DBG0_L1PK_SHIFT (5UL)
#define UNICAM_DBG0_L0PK_MASK (0x1fUL)
#define UNICAM_DBG0_L0PK_SHIFT (0UL)




typedef uint32_t UNICAM_DBG1_TYPE;
#define UNICAM_DBG1_BFPK_MASK (0xffff0000UL)
#define UNICAM_DBG1_BFPK_SHIFT (16UL)
#define UNICAM_DBG1_DFPK_MASK (0xffffUL)
#define UNICAM_DBG1_DFPK_SHIFT (0UL)




typedef uint32_t UNICAM_DBG2_TYPE;
#define UNICAM_DBG2_BFC_MASK (0xffff0000UL)
#define UNICAM_DBG2_BFC_SHIFT (16UL)
#define UNICAM_DBG2_DFC_MASK (0xffffUL)
#define UNICAM_DBG2_DFC_SHIFT (0UL)




typedef uint32_t UNICAM_DBG3_TYPE;
#define UNICAM_DBG3_IFPK_MASK (0xffff0000UL)
#define UNICAM_DBG3_IFPK_SHIFT (16UL)
#define UNICAM_DBG3_PFS_MASK (0x70UL)
#define UNICAM_DBG3_PFS_SHIFT (4UL)
#define UNICAM_DBG3_HSSYNC_MASK (0xfUL)
#define UNICAM_DBG3_HSSYNC_SHIFT (0UL)




typedef uint32_t UNICAM_ICTL_TYPE;
#define UNICAM_ICTL_DLSTE_EN_LN3_MASK (0x80000000UL)
#define UNICAM_ICTL_DLSTE_EN_LN3_SHIFT (31UL)
#define UNICAM_ICTL_DLSTE_EN_LN2_MASK (0x40000000UL)
#define UNICAM_ICTL_DLSTE_EN_LN2_SHIFT (30UL)
#define UNICAM_ICTL_CAMSTAT_IB_DIS_MASK (0x20000000UL)
#define UNICAM_ICTL_CAMSTAT_IB_DIS_SHIFT (29UL)
#define UNICAM_ICTL_LCIE_MASK (0x1fff0000UL)
#define UNICAM_ICTL_LCIE_SHIFT (16UL)
#define UNICAM_ICTL_DLSTE_EN_LN1_MASK (0x8000UL)
#define UNICAM_ICTL_DLSTE_EN_LN1_SHIFT (15UL)
#define UNICAM_ICTL_DLSTE_EN_LN0_MASK (0x4000UL)
#define UNICAM_ICTL_DLSTE_EN_LN0_SHIFT (14UL)
#define UNICAM_ICTL_CLSTE_EN_MASK (0x2000UL)
#define UNICAM_ICTL_CLSTE_EN_SHIFT (13UL)
#define UNICAM_ICTL_CRCE_EN_MASK (0x1000UL)
#define UNICAM_ICTL_CRCE_EN_SHIFT (12UL)
#define UNICAM_ICTL_PLE_EN_MASK (0x800UL)
#define UNICAM_ICTL_PLE_EN_SHIFT (11UL)
#define UNICAM_ICTL_HOE_EN_MASK (0x400UL)
#define UNICAM_ICTL_HOE_EN_SHIFT (10UL)
#define UNICAM_ICTL_PBE_EN_MASK (0x200UL)
#define UNICAM_ICTL_PBE_EN_SHIFT (9UL)
#define UNICAM_ICTL_SBE_EN_MASK (0x100UL)
#define UNICAM_ICTL_SBE_EN_SHIFT (8UL)
#define UNICAM_ICTL_AXIERR_INT_EN_MASK (0x80UL)
#define UNICAM_ICTL_AXIERR_INT_EN_SHIFT (7UL)
#define UNICAM_ICTL_LIP_MASK (0x60UL)
#define UNICAM_ICTL_LIP_SHIFT (5UL)
#define UNICAM_ICTL_TFC_MASK (0x10UL)
#define UNICAM_ICTL_TFC_SHIFT (4UL)
#define UNICAM_ICTL_FCM_MASK (0x8UL)
#define UNICAM_ICTL_FCM_SHIFT (3UL)
#define UNICAM_ICTL_IBOB_MASK (0x4UL)
#define UNICAM_ICTL_IBOB_SHIFT (2UL)
#define UNICAM_ICTL_FEIE_MASK (0x2UL)
#define UNICAM_ICTL_FEIE_SHIFT (1UL)
#define UNICAM_ICTL_FSIE_MASK (0x1UL)
#define UNICAM_ICTL_FSIE_SHIFT (0UL)




typedef uint32_t UNICAM_ISTA_TYPE;
#define UNICAM_ISTA_LCI_MASK (0x4UL)
#define UNICAM_ISTA_LCI_SHIFT (2UL)
#define UNICAM_ISTA_FEI_MASK (0x2UL)
#define UNICAM_ISTA_FEI_SHIFT (1UL)
#define UNICAM_ISTA_FSI_MASK (0x1UL)
#define UNICAM_ISTA_FSI_SHIFT (0UL)




typedef uint32_t UNICAM_IDI0_TYPE;
#define UNICAM_IDI0_IDI3_MASK (0xff000000UL)
#define UNICAM_IDI0_IDI3_SHIFT (24UL)
#define UNICAM_IDI0_IDI2_MASK (0xff0000UL)
#define UNICAM_IDI0_IDI2_SHIFT (16UL)
#define UNICAM_IDI0_IDI1_MASK (0xff00UL)
#define UNICAM_IDI0_IDI1_SHIFT (8UL)
#define UNICAM_IDI0_IDI0_MASK (0xffUL)
#define UNICAM_IDI0_IDI0_SHIFT (0UL)




typedef uint32_t UNICAM_IPIPE_TYPE;
#define UNICAM_IPIPE_DDM_MASK (0xf0UL)
#define UNICAM_IPIPE_DDM_SHIFT (4UL)
#define UNICAM_IPIPE_PUM_MASK (0xfUL)
#define UNICAM_IPIPE_PUM_SHIFT (0UL)




typedef uint32_t UNICAM_IBSA0_TYPE;
#define UNICAM_IBSA0_IBSA0_MASK (0xffffffffUL)
#define UNICAM_IBSA0_IBSA0_SHIFT (0UL)




typedef uint32_t UNICAM_IBEA0_TYPE;
#define UNICAM_IBEA0_IBEA0_MASK (0xffffffffUL)
#define UNICAM_IBEA0_IBEA0_SHIFT (0UL)




typedef uint32_t UNICAM_IBLS_TYPE;
#define UNICAM_IBLS_IBLS_MASK (0xffffUL)
#define UNICAM_IBLS_IBLS_SHIFT (0UL)




typedef uint32_t UNICAM_IBWP_TYPE;
#define UNICAM_IBWP_IBWP_MASK (0xffffffffUL)
#define UNICAM_IBWP_IBWP_SHIFT (0UL)




typedef uint32_t UNICAM_ICTL_SE_TYPE;
#define UNICAM_ICTL_SE_DI_END_EN_MASK (0x40000UL)
#define UNICAM_ICTL_SE_DI_END_EN_SHIFT (18UL)
#define UNICAM_ICTL_SE_DI_EN_MASK (0x20000UL)
#define UNICAM_ICTL_SE_DI_EN_SHIFT (17UL)
#define UNICAM_ICTL_SE_LCI_EN_MASK (0x7ffcUL)
#define UNICAM_ICTL_SE_LCI_EN_SHIFT (2UL)
#define UNICAM_ICTL_SE_FEI_EN_MASK (0x2UL)
#define UNICAM_ICTL_SE_FEI_EN_SHIFT (1UL)
#define UNICAM_ICTL_SE_FSI_EN_MASK (0x1UL)
#define UNICAM_ICTL_SE_FSI_EN_SHIFT (0UL)




typedef uint32_t UNICAM_ISTA_SE_TYPE;
#define UNICAM_ISTA_SE_DI_END_SE_MASK (0x10UL)
#define UNICAM_ISTA_SE_DI_END_SE_SHIFT (4UL)
#define UNICAM_ISTA_SE_DI_SE_MASK (0x8UL)
#define UNICAM_ISTA_SE_DI_SE_SHIFT (3UL)
#define UNICAM_ISTA_SE_LCI_SE_MASK (0x4UL)
#define UNICAM_ISTA_SE_LCI_SE_SHIFT (2UL)
#define UNICAM_ISTA_SE_FEI_SE_MASK (0x2UL)
#define UNICAM_ISTA_SE_FEI_SE_SHIFT (1UL)
#define UNICAM_ISTA_SE_FSI_SE_MASK (0x1UL)
#define UNICAM_ISTA_SE_FSI_SE_SHIFT (0UL)




typedef uint32_t UNICAM_IDATA_SE_TYPE;
#define UNICAM_IDATA_SE_EDL_END_SE_MASK (0xff000UL)
#define UNICAM_IDATA_SE_EDL_END_SE_SHIFT (12UL)
#define UNICAM_IDATA_SE_EDL_SE_MASK (0xffUL)
#define UNICAM_IDATA_SE_EDL_SE_SHIFT (0UL)




typedef uint32_t UNICAM_DCS_TYPE;
#define UNICAM_DCS_EDL_END_MASK (0x3fc0000UL)
#define UNICAM_DCS_EDL_END_SHIFT (18UL)
#define UNICAM_DCS_DI_END_MASK (0x20000UL)
#define UNICAM_DCS_DI_END_SHIFT (17UL)
#define UNICAM_DCS_DIE_END_MASK (0x10000UL)
#define UNICAM_DCS_DIE_END_SHIFT (16UL)
#define UNICAM_DCS_EDL_MASK (0xff00UL)
#define UNICAM_DCS_EDL_SHIFT (8UL)
#define UNICAM_DCS_LDP_MASK (0x20UL)
#define UNICAM_DCS_LDP_SHIFT (5UL)
#define UNICAM_DCS_DBOB_MASK (0x8UL)
#define UNICAM_DCS_DBOB_SHIFT (3UL)
#define UNICAM_DCS_DI_MASK (0x4UL)
#define UNICAM_DCS_DI_SHIFT (2UL)
#define UNICAM_DCS_DIE_MASK (0x1UL)
#define UNICAM_DCS_DIE_SHIFT (0UL)




typedef uint32_t UNICAM_DBSA0_TYPE;
#define UNICAM_DBSA0_DBSA0_MASK (0xffffffffUL)
#define UNICAM_DBSA0_DBSA0_SHIFT (0UL)




typedef uint32_t UNICAM_DBEA0_TYPE;
#define UNICAM_DBEA0_DBEA0_MASK (0xffffffffUL)
#define UNICAM_DBEA0_DBEA0_SHIFT (0UL)




typedef uint32_t UNICAM_DBWP_TYPE;
#define UNICAM_DBWP_DBWP_MASK (0xffffffffUL)
#define UNICAM_DBWP_DBWP_SHIFT (0UL)




typedef uint32_t UNICAM_DBCTL_TYPE;
#define UNICAM_DBCTL_DB_EN_DATA_MASK (0x8UL)
#define UNICAM_DBCTL_DB_EN_DATA_SHIFT (3UL)
#define UNICAM_DBCTL_BUF1_IE_MASK (0x4UL)
#define UNICAM_DBCTL_BUF1_IE_SHIFT (2UL)
#define UNICAM_DBCTL_BUF0_IE_MASK (0x2UL)
#define UNICAM_DBCTL_BUF0_IE_SHIFT (1UL)
#define UNICAM_DBCTL_DB_EN_MASK (0x1UL)
#define UNICAM_DBCTL_DB_EN_SHIFT (0UL)




typedef uint32_t UNICAM_IBSA1_TYPE;
#define UNICAM_IBSA1_IBSA1_MASK (0xffffffffUL)
#define UNICAM_IBSA1_IBSA1_SHIFT (0UL)




typedef uint32_t UNICAM_IBEA1_TYPE;
#define UNICAM_IBEA1_IBEA1_MASK (0xffffffffUL)
#define UNICAM_IBEA1_IBEA1_SHIFT (0UL)




typedef uint32_t UNICAM_IDI1_TYPE;
#define UNICAM_IDI1_IDI7_MASK (0xff000000UL)
#define UNICAM_IDI1_IDI7_SHIFT (24UL)
#define UNICAM_IDI1_IDI6_MASK (0xff0000UL)
#define UNICAM_IDI1_IDI6_SHIFT (16UL)
#define UNICAM_IDI1_IDI5_MASK (0xff00UL)
#define UNICAM_IDI1_IDI5_SHIFT (8UL)
#define UNICAM_IDI1_IDI4_MASK (0xffUL)
#define UNICAM_IDI1_IDI4_SHIFT (0UL)




typedef uint32_t UNICAM_DBSA1_TYPE;
#define UNICAM_DBSA1_DBSA1_MASK (0xffffffffUL)
#define UNICAM_DBSA1_DBSA1_SHIFT (0UL)




typedef uint32_t UNICAM_DBEA1_TYPE;
#define UNICAM_DBEA1_DBEA1_MASK (0xffffffffUL)
#define UNICAM_DBEA1_DBEA1_SHIFT (0UL)




typedef uint32_t UNICAM_FRSZ_TYPE;
#define UNICAM_FRSZ_CTL_FRAME_HEIGHT_MASK (0xffff0000UL)
#define UNICAM_FRSZ_CTL_FRAME_HEIGHT_SHIFT (16UL)
#define UNICAM_FRSZ_CTL_LINE_LENGTH_MASK (0xffffUL)
#define UNICAM_FRSZ_CTL_LINE_LENGTH_SHIFT (0UL)




typedef uint32_t UNICAM_LINCTL_TYPE;
#define UNICAM_LINCTL_CTL_CHECK_LE_SYNC_MASK (0x40UL)
#define UNICAM_LINCTL_CTL_CHECK_LE_SYNC_SHIFT (6UL)
#define UNICAM_LINCTL_CTL_GEN_LE_SYNC_MASK (0x20UL)
#define UNICAM_LINCTL_CTL_GEN_LE_SYNC_SHIFT (5UL)
#define UNICAM_LINCTL_CTL_GEN_LS_SYNC_MASK (0x10UL)
#define UNICAM_LINCTL_CTL_GEN_LS_SYNC_SHIFT (4UL)
#define UNICAM_LINCTL_UNPACK_FLUSH_LE_MASK (0x8UL)
#define UNICAM_LINCTL_UNPACK_FLUSH_LE_SHIFT (3UL)
#define UNICAM_LINCTL_USE_LE_MASK (0x4UL)
#define UNICAM_LINCTL_USE_LE_SHIFT (2UL)
#define UNICAM_LINCTL_PASS_LE_MASK (0x2UL)
#define UNICAM_LINCTL_PASS_LE_SHIFT (1UL)
#define UNICAM_LINCTL_PASS_LS_MASK (0x1UL)
#define UNICAM_LINCTL_PASS_LS_SHIFT (0UL)




typedef uint32_t UNICAM_EXP1CTL_TYPE;
#define UNICAM_EXP1CTL_PIXF_EXP1_MASK (0xf0UL)
#define UNICAM_EXP1CTL_PIXF_EXP1_SHIFT (4UL)
#define UNICAM_EXP1CTL_PIXF_EXP0_MASK (0xfUL)
#define UNICAM_EXP1CTL_PIXF_EXP0_SHIFT (0UL)




typedef uint32_t UNICAM_HDRCTL_TYPE;
#define UNICAM_HDRCTL_MULTI_RES_HDR_MASK (0x80000000UL)
#define UNICAM_HDRCTL_MULTI_RES_HDR_SHIFT (31UL)
#define UNICAM_HDRCTL_PASS_OB_LINES_MASK (0x40000UL)
#define UNICAM_HDRCTL_PASS_OB_LINES_SHIFT (18UL)
#define UNICAM_HDRCTL_SONY_HDR_MODE_MASK (0x20000UL)
#define UNICAM_HDRCTL_SONY_HDR_MODE_SHIFT (17UL)
#define UNICAM_HDRCTL_HDR_INIT_EXP_MASK (0x10000UL)
#define UNICAM_HDRCTL_HDR_INIT_EXP_SHIFT (16UL)
#define UNICAM_HDRCTL_HDR_LINE_OFFSET_MASK (0xff00UL)
#define UNICAM_HDRCTL_HDR_LINE_OFFSET_SHIFT (8UL)
#define UNICAM_HDRCTL_HDR_CSI2_SE_VC_MASK (0x30UL)
#define UNICAM_HDRCTL_HDR_CSI2_SE_VC_SHIFT (4UL)
#define UNICAM_HDRCTL_HDR_CSI2_LE_VC_MASK (0xcUL)
#define UNICAM_HDRCTL_HDR_CSI2_LE_VC_SHIFT (2UL)
#define UNICAM_HDRCTL_HDR_CSI2_VC_EN_MASK (0x2UL)
#define UNICAM_HDRCTL_HDR_CSI2_VC_EN_SHIFT (1UL)
#define UNICAM_HDRCTL_HDR_EN_MASK (0x1UL)
#define UNICAM_HDRCTL_HDR_EN_SHIFT (0UL)




typedef uint32_t UNICAM_ISP_HWSYC_CTL_TYPE;
#define UNICAM_ISP_HWSYC_CTL_EN_AXI_HWSYNC_MASK (0x80000000UL)
#define UNICAM_ISP_HWSYC_CTL_EN_AXI_HWSYNC_SHIFT (31UL)
#define UNICAM_ISP_HWSYC_CTL_EN_FE_AXI_SYNC_MASK (0x40000000UL)
#define UNICAM_ISP_HWSYC_CTL_EN_FE_AXI_SYNC_SHIFT (30UL)
#define UNICAM_ISP_HWSYC_CTL_TIMEOUT_EN_MASK (0x10000000UL)
#define UNICAM_ISP_HWSYC_CTL_TIMEOUT_EN_SHIFT (28UL)
#define UNICAM_ISP_HWSYC_CTL_TIMEOUT_VAL_MASK (0xfff0000UL)
#define UNICAM_ISP_HWSYC_CTL_TIMEOUT_VAL_SHIFT (16UL)
#define UNICAM_ISP_HWSYC_CTL_LINE_LENGTHMEM_MASK (0xffffUL)
#define UNICAM_ISP_HWSYC_CTL_LINE_LENGTHMEM_SHIFT (0UL)




typedef uint32_t UNICAM_ISP_HWSYC_STA_TYPE;
#define UNICAM_ISP_HWSYC_STA_LINE_DONE1_CNT_MASK (0xffff0000UL)
#define UNICAM_ISP_HWSYC_STA_LINE_DONE1_CNT_SHIFT (16UL)
#define UNICAM_ISP_HWSYC_STA_LINE_DONE_CNT_MASK (0xffffUL)
#define UNICAM_ISP_HWSYC_STA_LINE_DONE_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_ISP_MISC_TYPE;
#define UNICAM_ISP_MISC_CTL_CAM_ISP_RES_MASK (0xfffff000UL)
#define UNICAM_ISP_MISC_CTL_CAM_ISP_RES_SHIFT (12UL)
#define UNICAM_ISP_MISC_CTL_FRAME_HT_SONY_MASK (0xfffUL)
#define UNICAM_ISP_MISC_CTL_FRAME_HT_SONY_SHIFT (0UL)




typedef uint32_t UNICAM_DBG_TYPE;
#define UNICAM_DBG_NO_CHAN_INT_EN_MASK (0x4UL)
#define UNICAM_DBG_NO_CHAN_INT_EN_SHIFT (2UL)
#define UNICAM_DBG_WRAP_MID_BURST_MASK (0x2UL)
#define UNICAM_DBG_WRAP_MID_BURST_SHIFT (1UL)
#define UNICAM_DBG_SEND_WHOLE_FRAMES_MASK (0x1UL)
#define UNICAM_DBG_SEND_WHOLE_FRAMES_SHIFT (0UL)




typedef uint32_t UNICAM_IDI2_TYPE;
#define UNICAM_IDI2_IDI11_MASK (0xff000000UL)
#define UNICAM_IDI2_IDI11_SHIFT (24UL)
#define UNICAM_IDI2_IDI10_MASK (0xff0000UL)
#define UNICAM_IDI2_IDI10_SHIFT (16UL)
#define UNICAM_IDI2_IDI9_MASK (0xff00UL)
#define UNICAM_IDI2_IDI9_SHIFT (8UL)
#define UNICAM_IDI2_IDI8_MASK (0xffUL)
#define UNICAM_IDI2_IDI8_SHIFT (0UL)




typedef uint32_t UNICAM_IDI3_TYPE;
#define UNICAM_IDI3_IDI15_MASK (0xff000000UL)
#define UNICAM_IDI3_IDI15_SHIFT (24UL)
#define UNICAM_IDI3_IDI14_MASK (0xff0000UL)
#define UNICAM_IDI3_IDI14_SHIFT (16UL)
#define UNICAM_IDI3_IDI13_MASK (0xff00UL)
#define UNICAM_IDI3_IDI13_SHIFT (8UL)
#define UNICAM_IDI3_IDI12_MASK (0xffUL)
#define UNICAM_IDI3_IDI12_SHIFT (0UL)




typedef uint32_t UNICAM_VER_TYPE;
#define UNICAM_VER_UP_VER_MASK (0xffff0000UL)
#define UNICAM_VER_UP_VER_SHIFT (16UL)
#define UNICAM_VER_LOW_VER_MASK (0xffffUL)
#define UNICAM_VER_LOW_VER_SHIFT (0UL)




typedef uint32_t UNICAM_FET_TYPE;
#define UNICAM_FET_AXI_ID_MASK (0xff000000UL)
#define UNICAM_FET_AXI_ID_SHIFT (24UL)
#define UNICAM_FET_SCALAR_MASK (0x100000UL)
#define UNICAM_FET_SCALAR_SHIFT (20UL)
#define UNICAM_FET_PIX_CORR_MASK (0x80000UL)
#define UNICAM_FET_PIX_CORR_SHIFT (19UL)
#define UNICAM_FET_CPI_MASK (0x40000UL)
#define UNICAM_FET_CPI_SHIFT (18UL)
#define UNICAM_FET_CCP2_MASK (0x20000UL)
#define UNICAM_FET_CCP2_SHIFT (17UL)
#define UNICAM_FET_CSI2_MASK (0x10000UL)
#define UNICAM_FET_CSI2_SHIFT (16UL)
#define UNICAM_FET_CAM_LANES_MASK (0xf000UL)
#define UNICAM_FET_CAM_LANES_SHIFT (12UL)
#define UNICAM_FET_FET_VER_MASK (0xffUL)
#define UNICAM_FET_FET_VER_SHIFT (0UL)




typedef uint32_t UNICAM_WRAP_TYPE;
#define UNICAM_WRAP_WRAP_MASK (0xffffUL)
#define UNICAM_WRAP_WRAP_SHIFT (0UL)




typedef uint32_t UNICAM_DBG_PIX_CMP_FIF_TYPE;
#define UNICAM_DBG_PIX_CMP_FIF_FIF_MASK (0xffffffffUL)
#define UNICAM_DBG_PIX_CMP_FIF_FIF_SHIFT (0UL)




typedef uint32_t UNICAM_DBG_PIX_RET_UPK_TYPE;
#define UNICAM_DBG_PIX_RET_UPK_UPK_MASK (0xffffffffUL)
#define UNICAM_DBG_PIX_RET_UPK_UPK_SHIFT (0UL)




typedef uint32_t UNICAM_DBG_PIX_OPE_DPM_TYPE;
#define UNICAM_DBG_PIX_OPE_DPM_DPM_MASK (0xffffffffUL)
#define UNICAM_DBG_PIX_OPE_DPM_DPM_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_PHYCTL0_TYPE;
#define UNICAM_PRBS_PHYCTL0_PRBS_PHYCTL0_RES_MASK (0xf800UL)
#define UNICAM_PRBS_PHYCTL0_PRBS_PHYCTL0_RES_SHIFT (11UL)
#define UNICAM_PRBS_PHYCTL0_HSTX_RESET_CLK_MASK (0x400UL)
#define UNICAM_PRBS_PHYCTL0_HSTX_RESET_CLK_SHIFT (10UL)
#define UNICAM_PRBS_PHYCTL0_HSTX_EN_CLK_MASK (0x200UL)
#define UNICAM_PRBS_PHYCTL0_HSTX_EN_CLK_SHIFT (9UL)
#define UNICAM_PRBS_PHYCTL0_HSTX_EN_MASK (0x1e0UL)
#define UNICAM_PRBS_PHYCTL0_HSTX_EN_SHIFT (5UL)
#define UNICAM_PRBS_PHYCTL0_TXDDRCLKEN_MASK (0x10UL)
#define UNICAM_PRBS_PHYCTL0_TXDDRCLKEN_SHIFT (4UL)
#define UNICAM_PRBS_PHYCTL0_TXDDRCLK2EN_MASK (0x8UL)
#define UNICAM_PRBS_PHYCTL0_TXDDRCLK2EN_SHIFT (3UL)
#define UNICAM_PRBS_PHYCTL0_LDORSTB_MASK (0x4UL)
#define UNICAM_PRBS_PHYCTL0_LDORSTB_SHIFT (2UL)
#define UNICAM_PRBS_PHYCTL0_LDOCNTLEN_MASK (0x2UL)
#define UNICAM_PRBS_PHYCTL0_LDOCNTLEN_SHIFT (1UL)
#define UNICAM_PRBS_PHYCTL0_FS2X_EN_CLK_MASK (0x1UL)
#define UNICAM_PRBS_PHYCTL0_FS2X_EN_CLK_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_PHYCTL1_TYPE;
#define UNICAM_PRBS_PHYCTL1_PRBS_PHYCTL1_RES_MASK (0xf00000UL)
#define UNICAM_PRBS_PHYCTL1_PRBS_PHYCTL1_RES_SHIFT (20UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_EN_CLK_MASK (0x80000UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_EN_CLK_SHIFT (19UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DP_IN_CLK_MASK (0x40000UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DP_IN_CLK_SHIFT (18UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DM_IN_CLK_MASK (0x20000UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DM_IN_CLK_SHIFT (17UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_EN_MASK (0x1e000UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_EN_SHIFT (13UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DP_IN_MASK (0x1e00UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DP_IN_SHIFT (9UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DM_IN_MASK (0x1e0UL)
#define UNICAM_PRBS_PHYCTL1_LPTX_DM_IN_SHIFT (5UL)
#define UNICAM_PRBS_PHYCTL1_LPCD_EN_MASK (0x1eUL)
#define UNICAM_PRBS_PHYCTL1_LPCD_EN_SHIFT (1UL)
#define UNICAM_PRBS_PHYCTL1_LP_EN_MASK (0x1UL)
#define UNICAM_PRBS_PHYCTL1_LP_EN_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN0_CTL_TYPE;
#define UNICAM_PRBS_LN0_CTL_CONST_REG_EN_MASK (0x1000000UL)
#define UNICAM_PRBS_LN0_CTL_CONST_REG_EN_SHIFT (24UL)
#define UNICAM_PRBS_LN0_CTL_CONSTANT_REG_MASK (0xff0000UL)
#define UNICAM_PRBS_LN0_CTL_CONSTANT_REG_SHIFT (16UL)
#define UNICAM_PRBS_LN0_CTL_PM_INV_MASK (0x2000UL)
#define UNICAM_PRBS_LN0_CTL_PM_INV_SHIFT (13UL)
#define UNICAM_PRBS_LN0_CTL_PRBS_LN0_CTL_RES_MASK (0x1000UL)
#define UNICAM_PRBS_LN0_CTL_PRBS_LN0_CTL_RES_SHIFT (12UL)
#define UNICAM_PRBS_LN0_CTL_PM_ORDER_MASK (0xc00UL)
#define UNICAM_PRBS_LN0_CTL_PM_ORDER_SHIFT (10UL)
#define UNICAM_PRBS_LN0_CTL_PM_ERR_CLR_MASK (0x200UL)
#define UNICAM_PRBS_LN0_CTL_PM_ERR_CLR_SHIFT (9UL)
#define UNICAM_PRBS_LN0_CTL_PM_ENABLE_MASK (0x100UL)
#define UNICAM_PRBS_LN0_CTL_PM_ENABLE_SHIFT (8UL)
#define UNICAM_PRBS_LN0_CTL_PM_WIDTH_SEL_MASK (0x80UL)
#define UNICAM_PRBS_LN0_CTL_PM_WIDTH_SEL_SHIFT (7UL)
#define UNICAM_PRBS_LN0_CTL_PM_SOFTRST_N_MASK (0x40UL)
#define UNICAM_PRBS_LN0_CTL_PM_SOFTRST_N_SHIFT (6UL)
#define UNICAM_PRBS_LN0_CTL_PG_ORDER_MASK (0x30UL)
#define UNICAM_PRBS_LN0_CTL_PG_ORDER_SHIFT (4UL)
#define UNICAM_PRBS_LN0_CTL_PG_INV_MASK (0x8UL)
#define UNICAM_PRBS_LN0_CTL_PG_INV_SHIFT (3UL)
#define UNICAM_PRBS_LN0_CTL_PG_ENABLE_MASK (0x4UL)
#define UNICAM_PRBS_LN0_CTL_PG_ENABLE_SHIFT (2UL)
#define UNICAM_PRBS_LN0_CTL_PG_WIDTH_SEL_MASK (0x2UL)
#define UNICAM_PRBS_LN0_CTL_PG_WIDTH_SEL_SHIFT (1UL)
#define UNICAM_PRBS_LN0_CTL_PG_SOFTRST_N_MASK (0x1UL)
#define UNICAM_PRBS_LN0_CTL_PG_SOFTRST_N_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN0_ST_TYPE;
#define UNICAM_PRBS_LN0_ST_RPBS_ERRORS_MASK (0x3fff0000UL)
#define UNICAM_PRBS_LN0_ST_RPBS_ERRORS_SHIFT (16UL)
#define UNICAM_PRBS_LN0_ST_PRBS_STATE_MASK (0xf0UL)
#define UNICAM_PRBS_LN0_ST_PRBS_STATE_SHIFT (4UL)
#define UNICAM_PRBS_LN0_ST_PRBS_STKY_MASK (0x2UL)
#define UNICAM_PRBS_LN0_ST_PRBS_STKY_SHIFT (1UL)
#define UNICAM_PRBS_LN0_ST_PRBS_LOCK_MASK (0x1UL)
#define UNICAM_PRBS_LN0_ST_PRBS_LOCK_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN1_CTL_TYPE;
#define UNICAM_PRBS_LN1_CTL_CONST_REG_EN_MASK (0x1000000UL)
#define UNICAM_PRBS_LN1_CTL_CONST_REG_EN_SHIFT (24UL)
#define UNICAM_PRBS_LN1_CTL_CONSTANT_REG_MASK (0xff0000UL)
#define UNICAM_PRBS_LN1_CTL_CONSTANT_REG_SHIFT (16UL)
#define UNICAM_PRBS_LN1_CTL_PM_INV_MASK (0x2000UL)
#define UNICAM_PRBS_LN1_CTL_PM_INV_SHIFT (13UL)
#define UNICAM_PRBS_LN1_CTL_PRBS_LN0_CTL_RES_MASK (0x1000UL)
#define UNICAM_PRBS_LN1_CTL_PRBS_LN0_CTL_RES_SHIFT (12UL)
#define UNICAM_PRBS_LN1_CTL_PM_ORDER_MASK (0xc00UL)
#define UNICAM_PRBS_LN1_CTL_PM_ORDER_SHIFT (10UL)
#define UNICAM_PRBS_LN1_CTL_PM_ERR_CLR_MASK (0x200UL)
#define UNICAM_PRBS_LN1_CTL_PM_ERR_CLR_SHIFT (9UL)
#define UNICAM_PRBS_LN1_CTL_PM_ENABLE_MASK (0x100UL)
#define UNICAM_PRBS_LN1_CTL_PM_ENABLE_SHIFT (8UL)
#define UNICAM_PRBS_LN1_CTL_PM_WIDTH_SEL_MASK (0x80UL)
#define UNICAM_PRBS_LN1_CTL_PM_WIDTH_SEL_SHIFT (7UL)
#define UNICAM_PRBS_LN1_CTL_PM_SOFTRST_N_MASK (0x40UL)
#define UNICAM_PRBS_LN1_CTL_PM_SOFTRST_N_SHIFT (6UL)
#define UNICAM_PRBS_LN1_CTL_PG_ORDER_MASK (0x30UL)
#define UNICAM_PRBS_LN1_CTL_PG_ORDER_SHIFT (4UL)
#define UNICAM_PRBS_LN1_CTL_PG_INV_MASK (0x8UL)
#define UNICAM_PRBS_LN1_CTL_PG_INV_SHIFT (3UL)
#define UNICAM_PRBS_LN1_CTL_PG_ENABLE_MASK (0x4UL)
#define UNICAM_PRBS_LN1_CTL_PG_ENABLE_SHIFT (2UL)
#define UNICAM_PRBS_LN1_CTL_PG_WIDTH_SEL_MASK (0x2UL)
#define UNICAM_PRBS_LN1_CTL_PG_WIDTH_SEL_SHIFT (1UL)
#define UNICAM_PRBS_LN1_CTL_PG_SOFTRST_N_MASK (0x1UL)
#define UNICAM_PRBS_LN1_CTL_PG_SOFTRST_N_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN1_ST_TYPE;
#define UNICAM_PRBS_LN1_ST_RPBS_ERRORS_MASK (0x3fff0000UL)
#define UNICAM_PRBS_LN1_ST_RPBS_ERRORS_SHIFT (16UL)
#define UNICAM_PRBS_LN1_ST_PRBS_STATE_MASK (0xf0UL)
#define UNICAM_PRBS_LN1_ST_PRBS_STATE_SHIFT (4UL)
#define UNICAM_PRBS_LN1_ST_PRBS_STKY_MASK (0x2UL)
#define UNICAM_PRBS_LN1_ST_PRBS_STKY_SHIFT (1UL)
#define UNICAM_PRBS_LN1_ST_PRBS_LOCK_MASK (0x1UL)
#define UNICAM_PRBS_LN1_ST_PRBS_LOCK_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN2_CTL_TYPE;
#define UNICAM_PRBS_LN2_CTL_CONST_REG_EN_MASK (0x1000000UL)
#define UNICAM_PRBS_LN2_CTL_CONST_REG_EN_SHIFT (24UL)
#define UNICAM_PRBS_LN2_CTL_CONSTANT_REG_MASK (0xff0000UL)
#define UNICAM_PRBS_LN2_CTL_CONSTANT_REG_SHIFT (16UL)
#define UNICAM_PRBS_LN2_CTL_PM_INV_MASK (0x2000UL)
#define UNICAM_PRBS_LN2_CTL_PM_INV_SHIFT (13UL)
#define UNICAM_PRBS_LN2_CTL_PRBS_LN0_CTL_RES_MASK (0x1000UL)
#define UNICAM_PRBS_LN2_CTL_PRBS_LN0_CTL_RES_SHIFT (12UL)
#define UNICAM_PRBS_LN2_CTL_PM_ORDER_MASK (0xc00UL)
#define UNICAM_PRBS_LN2_CTL_PM_ORDER_SHIFT (10UL)
#define UNICAM_PRBS_LN2_CTL_PM_ERR_CLR_MASK (0x200UL)
#define UNICAM_PRBS_LN2_CTL_PM_ERR_CLR_SHIFT (9UL)
#define UNICAM_PRBS_LN2_CTL_PM_ENABLE_MASK (0x100UL)
#define UNICAM_PRBS_LN2_CTL_PM_ENABLE_SHIFT (8UL)
#define UNICAM_PRBS_LN2_CTL_PM_WIDTH_SEL_MASK (0x80UL)
#define UNICAM_PRBS_LN2_CTL_PM_WIDTH_SEL_SHIFT (7UL)
#define UNICAM_PRBS_LN2_CTL_PM_SOFTRST_N_MASK (0x40UL)
#define UNICAM_PRBS_LN2_CTL_PM_SOFTRST_N_SHIFT (6UL)
#define UNICAM_PRBS_LN2_CTL_PG_ORDER_MASK (0x30UL)
#define UNICAM_PRBS_LN2_CTL_PG_ORDER_SHIFT (4UL)
#define UNICAM_PRBS_LN2_CTL_PG_INV_MASK (0x8UL)
#define UNICAM_PRBS_LN2_CTL_PG_INV_SHIFT (3UL)
#define UNICAM_PRBS_LN2_CTL_PG_ENABLE_MASK (0x4UL)
#define UNICAM_PRBS_LN2_CTL_PG_ENABLE_SHIFT (2UL)
#define UNICAM_PRBS_LN2_CTL_PG_WIDTH_SEL_MASK (0x2UL)
#define UNICAM_PRBS_LN2_CTL_PG_WIDTH_SEL_SHIFT (1UL)
#define UNICAM_PRBS_LN2_CTL_PG_SOFTRST_N_MASK (0x1UL)
#define UNICAM_PRBS_LN2_CTL_PG_SOFTRST_N_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN2_ST_TYPE;
#define UNICAM_PRBS_LN2_ST_RPBS_ERRORS_MASK (0x3fff0000UL)
#define UNICAM_PRBS_LN2_ST_RPBS_ERRORS_SHIFT (16UL)
#define UNICAM_PRBS_LN2_ST_PRBS_STATE_MASK (0xf0UL)
#define UNICAM_PRBS_LN2_ST_PRBS_STATE_SHIFT (4UL)
#define UNICAM_PRBS_LN2_ST_PRBS_STKY_MASK (0x2UL)
#define UNICAM_PRBS_LN2_ST_PRBS_STKY_SHIFT (1UL)
#define UNICAM_PRBS_LN2_ST_PRBS_LOCK_MASK (0x1UL)
#define UNICAM_PRBS_LN2_ST_PRBS_LOCK_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN3_CTL_TYPE;
#define UNICAM_PRBS_LN3_CTL_CONST_REG_EN_MASK (0x1000000UL)
#define UNICAM_PRBS_LN3_CTL_CONST_REG_EN_SHIFT (24UL)
#define UNICAM_PRBS_LN3_CTL_CONSTANT_REG_MASK (0xff0000UL)
#define UNICAM_PRBS_LN3_CTL_CONSTANT_REG_SHIFT (16UL)
#define UNICAM_PRBS_LN3_CTL_PM_INV_MASK (0x2000UL)
#define UNICAM_PRBS_LN3_CTL_PM_INV_SHIFT (13UL)
#define UNICAM_PRBS_LN3_CTL_PRBS_LN0_CTL_RES_MASK (0x1000UL)
#define UNICAM_PRBS_LN3_CTL_PRBS_LN0_CTL_RES_SHIFT (12UL)
#define UNICAM_PRBS_LN3_CTL_PM_ORDER_MASK (0xc00UL)
#define UNICAM_PRBS_LN3_CTL_PM_ORDER_SHIFT (10UL)
#define UNICAM_PRBS_LN3_CTL_PM_ERR_CLR_MASK (0x200UL)
#define UNICAM_PRBS_LN3_CTL_PM_ERR_CLR_SHIFT (9UL)
#define UNICAM_PRBS_LN3_CTL_PM_ENABLE_MASK (0x100UL)
#define UNICAM_PRBS_LN3_CTL_PM_ENABLE_SHIFT (8UL)
#define UNICAM_PRBS_LN3_CTL_PM_WIDTH_SEL_MASK (0x80UL)
#define UNICAM_PRBS_LN3_CTL_PM_WIDTH_SEL_SHIFT (7UL)
#define UNICAM_PRBS_LN3_CTL_PM_SOFTRST_N_MASK (0x40UL)
#define UNICAM_PRBS_LN3_CTL_PM_SOFTRST_N_SHIFT (6UL)
#define UNICAM_PRBS_LN3_CTL_PG_ORDER_MASK (0x30UL)
#define UNICAM_PRBS_LN3_CTL_PG_ORDER_SHIFT (4UL)
#define UNICAM_PRBS_LN3_CTL_PG_INV_MASK (0x8UL)
#define UNICAM_PRBS_LN3_CTL_PG_INV_SHIFT (3UL)
#define UNICAM_PRBS_LN3_CTL_PG_ENABLE_MASK (0x4UL)
#define UNICAM_PRBS_LN3_CTL_PG_ENABLE_SHIFT (2UL)
#define UNICAM_PRBS_LN3_CTL_PG_WIDTH_SEL_MASK (0x2UL)
#define UNICAM_PRBS_LN3_CTL_PG_WIDTH_SEL_SHIFT (1UL)
#define UNICAM_PRBS_LN3_CTL_PG_SOFTRST_N_MASK (0x1UL)
#define UNICAM_PRBS_LN3_CTL_PG_SOFTRST_N_SHIFT (0UL)




typedef uint32_t UNICAM_PRBS_LN3_ST_TYPE;
#define UNICAM_PRBS_LN3_ST_RPBS_ERRORS_MASK (0x3fff0000UL)
#define UNICAM_PRBS_LN3_ST_RPBS_ERRORS_SHIFT (16UL)
#define UNICAM_PRBS_LN3_ST_PRBS_STATE_MASK (0xf0UL)
#define UNICAM_PRBS_LN3_ST_PRBS_STATE_SHIFT (4UL)
#define UNICAM_PRBS_LN3_ST_PRBS_STKY_MASK (0x2UL)
#define UNICAM_PRBS_LN3_ST_PRBS_STKY_SHIFT (1UL)
#define UNICAM_PRBS_LN3_ST_PRBS_LOCK_MASK (0x1UL)
#define UNICAM_PRBS_LN3_ST_PRBS_LOCK_SHIFT (0UL)




typedef uint32_t UNICAM_CPIS_TYPE;
#define UNICAM_CPIS_REGF_MASK (0x80000000UL)
#define UNICAM_CPIS_REGF_SHIFT (31UL)
#define UNICAM_CPIS_HERROR_MASK (0x40000000UL)
#define UNICAM_CPIS_HERROR_SHIFT (30UL)
#define UNICAM_CPIS_SOFTRST_MASK (0x20UL)
#define UNICAM_CPIS_SOFTRST_SHIFT (5UL)
#define UNICAM_CPIS_DISACT_MASK (0x10UL)
#define UNICAM_CPIS_DISACT_SHIFT (4UL)
#define UNICAM_CPIS_CAPT_MASK (0x4UL)
#define UNICAM_CPIS_CAPT_SHIFT (2UL)
#define UNICAM_CPIS_ACT_MASK (0x2UL)
#define UNICAM_CPIS_ACT_SHIFT (1UL)
#define UNICAM_CPIS_ENB_MASK (0x1UL)
#define UNICAM_CPIS_ENB_SHIFT (0UL)




typedef uint32_t UNICAM_CPIR_TYPE;
#define UNICAM_CPIR_DATASHIFT_MASK (0x1e00UL)
#define UNICAM_CPIR_DATASHIFT_SHIFT (9UL)
#define UNICAM_CPIR_DWID_MASK (0x180UL)
#define UNICAM_CPIR_DWID_SHIFT (7UL)
#define UNICAM_CPIR_HSYNC_MASK (0x40UL)
#define UNICAM_CPIR_HSYNC_SHIFT (6UL)
#define UNICAM_CPIR_VSYNC_MASK (0x20UL)
#define UNICAM_CPIR_VSYNC_SHIFT (5UL)
#define UNICAM_CPIR_DRSYNC_MASK (0x10UL)
#define UNICAM_CPIR_DRSYNC_SHIFT (4UL)
#define UNICAM_CPIR_HSRM_MASK (0x8UL)
#define UNICAM_CPIR_HSRM_SHIFT (3UL)
#define UNICAM_CPIR_VSRM_MASK (0x4UL)
#define UNICAM_CPIR_VSRM_SHIFT (2UL)
#define UNICAM_CPIR_HSAL_MASK (0x2UL)
#define UNICAM_CPIR_HSAL_SHIFT (1UL)
#define UNICAM_CPIR_VSAL_MASK (0x1UL)
#define UNICAM_CPIR_VSAL_SHIFT (0UL)




typedef uint32_t UNICAM_CPIF_TYPE;
#define UNICAM_CPIF_FIELD_BIT_MASK (0xf000000UL)
#define UNICAM_CPIF_FIELD_BIT_SHIFT (24UL)
#define UNICAM_CPIF_HSYNC_BIT_MASK (0xf00000UL)
#define UNICAM_CPIF_HSYNC_BIT_SHIFT (20UL)
#define UNICAM_CPIF_VSYNC_BIT_MASK (0xf0000UL)
#define UNICAM_CPIF_VSYNC_BIT_SHIFT (16UL)
#define UNICAM_CPIF_SHIFT_SYNC_MASK (0x6000UL)
#define UNICAM_CPIF_SHIFT_SYNC_SHIFT (13UL)
#define UNICAM_CPIF_EMB_SYNCSHIFT_EN_MASK (0x1000UL)
#define UNICAM_CPIF_EMB_SYNCSHIFT_EN_SHIFT (12UL)
#define UNICAM_CPIF_FDETECT_MASK (0x800UL)
#define UNICAM_CPIF_FDETECT_SHIFT (11UL)
#define UNICAM_CPIF_STATE_MASK (0x700UL)
#define UNICAM_CPIF_STATE_SHIFT (8UL)
#define UNICAM_CPIF_SCMODE_MASK (0x80UL)
#define UNICAM_CPIF_SCMODE_SHIFT (7UL)
#define UNICAM_CPIF_FMODE_MASK (0x60UL)
#define UNICAM_CPIF_FMODE_SHIFT (5UL)
#define UNICAM_CPIF_HMODE_MASK (0x18UL)
#define UNICAM_CPIF_HMODE_SHIFT (3UL)
#define UNICAM_CPIF_VMODE_MASK (0x6UL)
#define UNICAM_CPIF_VMODE_SHIFT (1UL)
#define UNICAM_CPIF_SMODE_MASK (0x1UL)
#define UNICAM_CPIF_SMODE_SHIFT (0UL)




typedef uint32_t UNICAM_CPIWM_TYPE;
#define UNICAM_CPIWM_HLINE_MIN_MASK (0xffff0000UL)
#define UNICAM_CPIWM_HLINE_MIN_SHIFT (16UL)
#define UNICAM_CPIWM_FRM_CNT_MASK (0xffUL)
#define UNICAM_CPIWM_FRM_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_CPIB_TYPE;
#define UNICAM_CPIB_CHANCODE_MASK (0x8UL)
#define UNICAM_CPIB_CHANCODE_SHIFT (3UL)
#define UNICAM_CPIB_LINECODE_MASK (0x7UL)
#define UNICAM_CPIB_LINECODE_SHIFT (0UL)




typedef uint32_t UNICAM_CPIVCM_TYPE;
#define UNICAM_CPIVCM_VSYNC_FALL_CNT_MAX_MASK (0x3ff0000UL)
#define UNICAM_CPIVCM_VSYNC_FALL_CNT_MAX_SHIFT (16UL)
#define UNICAM_CPIVCM_VSYNC_RISE_CNT_MAX_MASK (0x3ffUL)
#define UNICAM_CPIVCM_VSYNC_RISE_CNT_MAX_SHIFT (0UL)




typedef uint32_t UNICAM_CPIHCM_TYPE;
#define UNICAM_CPIHCM_HSYNC_FALL_CNT_MAX_MASK (0x3ff0000UL)
#define UNICAM_CPIHCM_HSYNC_FALL_CNT_MAX_SHIFT (16UL)
#define UNICAM_CPIHCM_HSYNC_RISE_CNT_MAX_MASK (0x3ffUL)
#define UNICAM_CPIHCM_HSYNC_RISE_CNT_MAX_SHIFT (0UL)




typedef uint32_t UNICAM_CPILECM_TYPE;
#define UNICAM_CPILECM_LE_DLY_CNT_MAX_MASK (0x3fUL)
#define UNICAM_CPILECM_LE_DLY_CNT_MAX_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_CTL_TYPE;
#define UNICAM_HISPI_CTL_CRC_INIT_VAL_MASK (0xffff0000UL)
#define UNICAM_HISPI_CTL_CRC_INIT_VAL_SHIFT (16UL)
#define UNICAM_HISPI_CTL_CTL_RES_MASK (0x600UL)
#define UNICAM_HISPI_CTL_CTL_RES_SHIFT (9UL)
#define UNICAM_HISPI_CTL_CRC_OP_REFLC_MASK (0x100UL)
#define UNICAM_HISPI_CTL_CRC_OP_REFLC_SHIFT (8UL)
#define UNICAM_HISPI_CTL_CRC_IP_REFLC_MASK (0x80UL)
#define UNICAM_HISPI_CTL_CRC_IP_REFLC_SHIFT (7UL)
#define UNICAM_HISPI_CTL_CRC_INT_EN_MASK (0x40UL)
#define UNICAM_HISPI_CTL_CRC_INT_EN_SHIFT (6UL)
#define UNICAM_HISPI_CTL_LANE_MSB_COMES_FIRST_MASK (0x20UL)
#define UNICAM_HISPI_CTL_LANE_MSB_COMES_FIRST_SHIFT (5UL)
#define UNICAM_HISPI_CTL_CRC_EN_MASK (0x10UL)
#define UNICAM_HISPI_CTL_CRC_EN_SHIFT (4UL)
#define UNICAM_HISPI_CTL_FILLER_EN_MASK (0x8UL)
#define UNICAM_HISPI_CTL_FILLER_EN_SHIFT (3UL)
#define UNICAM_HISPI_CTL_MODE_MASK (0x7UL)
#define UNICAM_HISPI_CTL_MODE_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_STA_TYPE;
#define UNICAM_HISPI_STA_STA_RES_MASK (0xff0UL)
#define UNICAM_HISPI_STA_STA_RES_SHIFT (4UL)
#define UNICAM_HISPI_STA_CRC_ERR_LANES_MASK (0xfUL)
#define UNICAM_HISPI_STA_CRC_ERR_LANES_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_DBG1_TYPE;
#define UNICAM_HISPI_DBG1_DBG_REG_MASK (0xffffffffUL)
#define UNICAM_HISPI_DBG1_DBG_REG_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_DBG_FIFO_0_TYPE;
#define UNICAM_HISPI_DBG_FIFO_0_LANE_0_MASK (0xffffffffUL)
#define UNICAM_HISPI_DBG_FIFO_0_LANE_0_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_DBG_FIFO_1_TYPE;
#define UNICAM_HISPI_DBG_FIFO_1_LANE_1_MASK (0xffffffffUL)
#define UNICAM_HISPI_DBG_FIFO_1_LANE_1_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_DBG_FIFO_2_TYPE;
#define UNICAM_HISPI_DBG_FIFO_2_LANE_2_MASK (0xffffffffUL)
#define UNICAM_HISPI_DBG_FIFO_2_LANE_2_SHIFT (0UL)




typedef uint32_t UNICAM_HISPI_DBG_FIFO_3_TYPE;
#define UNICAM_HISPI_DBG_FIFO_3_LANE_3_MASK (0xffffffffUL)
#define UNICAM_HISPI_DBG_FIFO_3_LANE_3_SHIFT (0UL)




typedef uint32_t UNICAM_DBG_PORT_CTL_TYPE;
#define UNICAM_DBG_PORT_CTL_MUX_SEL_SRC_MASK (0x400UL)
#define UNICAM_DBG_PORT_CTL_MUX_SEL_SRC_SHIFT (10UL)
#define UNICAM_DBG_PORT_CTL_MUX_SEL_MASK (0x3ffUL)
#define UNICAM_DBG_PORT_CTL_MUX_SEL_SHIFT (0UL)




typedef uint32_t UNICAM_DBG_PORT_STAT_TYPE;
#define UNICAM_DBG_PORT_STAT_BUS_VAL_MASK (0xffffffffUL)
#define UNICAM_DBG_PORT_STAT_BUS_VAL_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TGCTL_TYPE;
#define UNICAM_VC5_TGCTL_PRE_B_MASK (0xffff0000UL)
#define UNICAM_VC5_TGCTL_PRE_B_SHIFT (16UL)
#define UNICAM_VC5_TGCTL_MODE_MASK (0x2000UL)
#define UNICAM_VC5_TGCTL_MODE_SHIFT (13UL)
#define UNICAM_VC5_TGCTL_CFG_BYPASS_MASK (0x1000UL)
#define UNICAM_VC5_TGCTL_CFG_BYPASS_SHIFT (12UL)
#define UNICAM_VC5_TGCTL_BPP_MASK (0xf00UL)
#define UNICAM_VC5_TGCTL_BPP_SHIFT (8UL)
#define UNICAM_VC5_TGCTL_CHAN_MASK (0x80UL)
#define UNICAM_VC5_TGCTL_CHAN_SHIFT (7UL)
#define UNICAM_VC5_TGCTL_ED_MASK (0x40UL)
#define UNICAM_VC5_TGCTL_ED_SHIFT (6UL)
#define UNICAM_VC5_TGCTL_BAYER_MASK (0x30UL)
#define UNICAM_VC5_TGCTL_BAYER_SHIFT (4UL)
#define UNICAM_VC5_TGCTL_DIS_EN_MASK (0x8UL)
#define UNICAM_VC5_TGCTL_DIS_EN_SHIFT (3UL)
#define UNICAM_VC5_TGCTL_TR_EN_MASK (0x4UL)
#define UNICAM_VC5_TGCTL_TR_EN_SHIFT (2UL)
#define UNICAM_VC5_TGCTL_START_MASK (0x2UL)
#define UNICAM_VC5_TGCTL_START_SHIFT (1UL)
#define UNICAM_VC5_TGCTL_TG_ENABLE_MASK (0x1UL)
#define UNICAM_VC5_TGCTL_TG_ENABLE_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TGISZ_TYPE;
#define UNICAM_VC5_TGISZ_TG_HEIGHT_MASK (0xffff0000UL)
#define UNICAM_VC5_TGISZ_TG_HEIGHT_SHIFT (16UL)
#define UNICAM_VC5_TGISZ_TG_WIDTH_MASK (0xffffUL)
#define UNICAM_VC5_TGISZ_TG_WIDTH_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TGBL_TYPE;
#define UNICAM_VC5_TGBL_VBLANK_MASK (0xffff0000UL)
#define UNICAM_VC5_TGBL_VBLANK_SHIFT (16UL)
#define UNICAM_VC5_TGBL_HBLANK_MASK (0xffffUL)
#define UNICAM_VC5_TGBL_HBLANK_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TGBSZ_TYPE;
#define UNICAM_VC5_TGBSZ_BYSIZE_MASK (0xf0UL)
#define UNICAM_VC5_TGBSZ_BYSIZE_SHIFT (4UL)
#define UNICAM_VC5_TGBSZ_BXSIZE_MASK (0xfUL)
#define UNICAM_VC5_TGBSZ_BXSIZE_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TGLFS_TYPE;
#define UNICAM_VC5_TGLFS_VALUE_MASK (0xffffffUL)
#define UNICAM_VC5_TGLFS_VALUE_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TGPS_TYPE;
#define UNICAM_VC5_TGPS_B_PRESCALE_MASK (0xffff0000UL)
#define UNICAM_VC5_TGPS_B_PRESCALE_SHIFT (16UL)




typedef uint32_t UNICAM_VC5_TGISTAT_TYPE;
#define UNICAM_VC5_TGISTAT_FIFO_FULL_MASK (0x10UL)
#define UNICAM_VC5_TGISTAT_FIFO_FULL_SHIFT (4UL)
#define UNICAM_VC5_TGISTAT_RESP_DECERR_MASK (0x8UL)
#define UNICAM_VC5_TGISTAT_RESP_DECERR_SHIFT (3UL)
#define UNICAM_VC5_TGISTAT_RESP_SLVERR_MASK (0x4UL)
#define UNICAM_VC5_TGISTAT_RESP_SLVERR_SHIFT (2UL)
#define UNICAM_VC5_TGISTAT_RESP_EXOKAY_MASK (0x2UL)
#define UNICAM_VC5_TGISTAT_RESP_EXOKAY_SHIFT (1UL)
#define UNICAM_VC5_TGISTAT_RESP_OKAY_MASK (0x1UL)
#define UNICAM_VC5_TGISTAT_RESP_OKAY_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_TG_IEN_TYPE;
#define UNICAM_VC5_TG_IEN_FIFO_FULL_MASK (0x10UL)
#define UNICAM_VC5_TG_IEN_FIFO_FULL_SHIFT (4UL)
#define UNICAM_VC5_TG_IEN_RESP_DECERR_MASK (0x8UL)
#define UNICAM_VC5_TG_IEN_RESP_DECERR_SHIFT (3UL)
#define UNICAM_VC5_TG_IEN_RESP_SLVERR_MASK (0x4UL)
#define UNICAM_VC5_TG_IEN_RESP_SLVERR_SHIFT (2UL)
#define UNICAM_VC5_TG_IEN_RESP_EXOKAY_MASK (0x2UL)
#define UNICAM_VC5_TG_IEN_RESP_EXOKAY_SHIFT (1UL)
#define UNICAM_VC5_TG_IEN_RESP_OKAY_MASK (0x1UL)
#define UNICAM_VC5_TG_IEN_RESP_OKAY_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_ACFG_TYPE;
#define UNICAM_VC5_ACFG_CONT_MASK (0x1UL)
#define UNICAM_VC5_ACFG_CONT_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_ASTA_TYPE;
#define UNICAM_VC5_ASTA_STATE_MASK (0xf0UL)
#define UNICAM_VC5_ASTA_STATE_SHIFT (4UL)
#define UNICAM_VC5_ASTA_GW_MASK (0x1UL)
#define UNICAM_VC5_ASTA_GW_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_ASA_TYPE;
#define UNICAM_VC5_ASA_SA_MASK (0xfffffff0UL)
#define UNICAM_VC5_ASA_SA_SHIFT (4UL)




typedef uint32_t UNICAM_VC5_AEA_TYPE;
#define UNICAM_VC5_AEA_EA_MASK (0xfffffff0UL)
#define UNICAM_VC5_AEA_EA_SHIFT (4UL)




typedef uint32_t UNICAM_VC5_ASL_TYPE;
#define UNICAM_VC5_ASL_LENGTH_MASK (0xffff0000UL)
#define UNICAM_VC5_ASL_LENGTH_SHIFT (16UL)
#define UNICAM_VC5_ASL_STRIDE_MASK (0xfff0UL)
#define UNICAM_VC5_ASL_STRIDE_SHIFT (4UL)




typedef uint32_t UNICAM_VC5_ALC_TYPE;
#define UNICAM_VC5_ALC_LC_MASK (0xffffUL)
#define UNICAM_VC5_ALC_LC_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_AT_TYPE;
#define UNICAM_VC5_AT_TIMER_MASK (0xffffUL)
#define UNICAM_VC5_AT_TIMER_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_AMM_TYPE;
#define UNICAM_VC5_AMM_MAX_MASK (0xff0000UL)
#define UNICAM_VC5_AMM_MAX_SHIFT (16UL)
#define UNICAM_VC5_AMM_MIN_MASK (0xffUL)
#define UNICAM_VC5_AMM_MIN_SHIFT (0UL)




typedef uint32_t UNICAM_VC5_ATRIG_TYPE;
#define UNICAM_VC5_ATRIG_TRIG_MASK (0x1UL)
#define UNICAM_VC5_ATRIG_TRIG_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_CTL_TYPE;
#define UNICAM_IB0_DBG_CTL_NUM_LINES_MASK (0x7ff0000UL)
#define UNICAM_IB0_DBG_CTL_NUM_LINES_SHIFT (16UL)
#define UNICAM_IB0_DBG_CTL_NUM_LINES_WRAP_MASK (0x7fcUL)
#define UNICAM_IB0_DBG_CTL_NUM_LINES_WRAP_SHIFT (2UL)
#define UNICAM_IB0_DBG_CTL_WRAP_MODE_MASK (0x2UL)
#define UNICAM_IB0_DBG_CTL_WRAP_MODE_SHIFT (1UL)
#define UNICAM_IB0_DBG_CTL_ENABLE_MASK (0x1UL)
#define UNICAM_IB0_DBG_CTL_ENABLE_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_LAST_ADDR_TYPE;
#define UNICAM_IB0_DBG_LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_LAST_CMD1_TYPE;
#define UNICAM_IB0_DBG_LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_LAST_CMD2_TYPE;
#define UNICAM_IB0_DBG_LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_2LAST_ADDR_TYPE;
#define UNICAM_IB0_DBG_2LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_2LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_2LAST_CMD1_TYPE;
#define UNICAM_IB0_DBG_2LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_2LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_2LAST_CMD2_TYPE;
#define UNICAM_IB0_DBG_2LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_2LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_W_CHAN_TYPE;
#define UNICAM_IB0_DBG_W_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_W_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_W_DATA_TYPE;
#define UNICAM_IB0_DBG_W_DATA_LAST_DATA_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_W_DATA_LAST_DATA_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_B_CHAN_TYPE;
#define UNICAM_IB0_DBG_B_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_B_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_BRST_XN_CNT_TYPE;
#define UNICAM_IB0_DBG_BRST_XN_CNT_XN_COUNTER_MASK (0xffff0000UL)
#define UNICAM_IB0_DBG_BRST_XN_CNT_XN_COUNTER_SHIFT (16UL)
#define UNICAM_IB0_DBG_BRST_XN_CNT_OUT_OF_RANGE_MASK (0xff00UL)
#define UNICAM_IB0_DBG_BRST_XN_CNT_OUT_OF_RANGE_SHIFT (8UL)
#define UNICAM_IB0_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_MASK (0x1fUL)
#define UNICAM_IB0_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_IB0_DBG_LINE_CNT_TYPE;
#define UNICAM_IB0_DBG_LINE_CNT_CNT_MASK (0xffffffffUL)
#define UNICAM_IB0_DBG_LINE_CNT_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_CTL_TYPE;
#define UNICAM_IB1_DBG_CTL_NUM_LINES_MASK (0x7ff0000UL)
#define UNICAM_IB1_DBG_CTL_NUM_LINES_SHIFT (16UL)
#define UNICAM_IB1_DBG_CTL_NUM_LINES_WRAP_MASK (0x7fcUL)
#define UNICAM_IB1_DBG_CTL_NUM_LINES_WRAP_SHIFT (2UL)
#define UNICAM_IB1_DBG_CTL_WRAP_MODE_MASK (0x2UL)
#define UNICAM_IB1_DBG_CTL_WRAP_MODE_SHIFT (1UL)
#define UNICAM_IB1_DBG_CTL_ENABLE_MASK (0x1UL)
#define UNICAM_IB1_DBG_CTL_ENABLE_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_LAST_ADDR_TYPE;
#define UNICAM_IB1_DBG_LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_LAST_CMD1_TYPE;
#define UNICAM_IB1_DBG_LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_LAST_CMD2_TYPE;
#define UNICAM_IB1_DBG_LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_2LAST_ADDR_TYPE;
#define UNICAM_IB1_DBG_2LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_2LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_2LAST_CMD1_TYPE;
#define UNICAM_IB1_DBG_2LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_2LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_2LAST_CMD2_TYPE;
#define UNICAM_IB1_DBG_2LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_2LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_W_CHAN_TYPE;
#define UNICAM_IB1_DBG_W_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_W_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_W_DATA_TYPE;
#define UNICAM_IB1_DBG_W_DATA_LAST_DATA_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_W_DATA_LAST_DATA_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_B_CHAN_TYPE;
#define UNICAM_IB1_DBG_B_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_B_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_BRST_XN_CNT_TYPE;
#define UNICAM_IB1_DBG_BRST_XN_CNT_XN_COUNTER_MASK (0xffff0000UL)
#define UNICAM_IB1_DBG_BRST_XN_CNT_XN_COUNTER_SHIFT (16UL)
#define UNICAM_IB1_DBG_BRST_XN_CNT_OUT_OF_RANGE_MASK (0xff00UL)
#define UNICAM_IB1_DBG_BRST_XN_CNT_OUT_OF_RANGE_SHIFT (8UL)
#define UNICAM_IB1_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_MASK (0x1fUL)
#define UNICAM_IB1_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_IB1_DBG_LINE_CNT_TYPE;
#define UNICAM_IB1_DBG_LINE_CNT_CNT_MASK (0xffffffffUL)
#define UNICAM_IB1_DBG_LINE_CNT_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_CTL_TYPE;
#define UNICAM_DB0_DBG_CTL_NUM_LINES_MASK (0x7ff0000UL)
#define UNICAM_DB0_DBG_CTL_NUM_LINES_SHIFT (16UL)
#define UNICAM_DB0_DBG_CTL_NUM_LINES_WRAP_MASK (0x7fcUL)
#define UNICAM_DB0_DBG_CTL_NUM_LINES_WRAP_SHIFT (2UL)
#define UNICAM_DB0_DBG_CTL_WRAP_MODE_MASK (0x2UL)
#define UNICAM_DB0_DBG_CTL_WRAP_MODE_SHIFT (1UL)
#define UNICAM_DB0_DBG_CTL_ENABLE_MASK (0x1UL)
#define UNICAM_DB0_DBG_CTL_ENABLE_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_LAST_ADDR_TYPE;
#define UNICAM_DB0_DBG_LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_LAST_CMD1_TYPE;
#define UNICAM_DB0_DBG_LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_LAST_CMD2_TYPE;
#define UNICAM_DB0_DBG_LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_2LAST_ADDR_TYPE;
#define UNICAM_DB0_DBG_2LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_2LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_2LAST_CMD1_TYPE;
#define UNICAM_DB0_DBG_2LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_2LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_2LAST_CMD2_TYPE;
#define UNICAM_DB0_DBG_2LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_2LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_W_CHAN_TYPE;
#define UNICAM_DB0_DBG_W_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_W_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_W_DATA_TYPE;
#define UNICAM_DB0_DBG_W_DATA_LAST_DATA_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_W_DATA_LAST_DATA_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_B_CHAN_TYPE;
#define UNICAM_DB0_DBG_B_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_B_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_BRST_XN_CNT_TYPE;
#define UNICAM_DB0_DBG_BRST_XN_CNT_XN_COUNTER_MASK (0xffff0000UL)
#define UNICAM_DB0_DBG_BRST_XN_CNT_XN_COUNTER_SHIFT (16UL)
#define UNICAM_DB0_DBG_BRST_XN_CNT_OUT_OF_RANGE_MASK (0xff00UL)
#define UNICAM_DB0_DBG_BRST_XN_CNT_OUT_OF_RANGE_SHIFT (8UL)
#define UNICAM_DB0_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_MASK (0x1fUL)
#define UNICAM_DB0_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_DB0_DBG_LINE_CNT_TYPE;
#define UNICAM_DB0_DBG_LINE_CNT_CNT_MASK (0xffffffffUL)
#define UNICAM_DB0_DBG_LINE_CNT_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_CTL_TYPE;
#define UNICAM_DB1_DBG_CTL_NUM_LINES_MASK (0x7ff0000UL)
#define UNICAM_DB1_DBG_CTL_NUM_LINES_SHIFT (16UL)
#define UNICAM_DB1_DBG_CTL_NUM_LINES_WRAP_MASK (0x7fcUL)
#define UNICAM_DB1_DBG_CTL_NUM_LINES_WRAP_SHIFT (2UL)
#define UNICAM_DB1_DBG_CTL_WRAP_MODE_MASK (0x2UL)
#define UNICAM_DB1_DBG_CTL_WRAP_MODE_SHIFT (1UL)
#define UNICAM_DB1_DBG_CTL_ENABLE_MASK (0x1UL)
#define UNICAM_DB1_DBG_CTL_ENABLE_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_LAST_ADDR_TYPE;
#define UNICAM_DB1_DBG_LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_LAST_CMD1_TYPE;
#define UNICAM_DB1_DBG_LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_LAST_CMD2_TYPE;
#define UNICAM_DB1_DBG_LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_2LAST_ADDR_TYPE;
#define UNICAM_DB1_DBG_2LAST_ADDR_ADDRESS_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_2LAST_ADDR_ADDRESS_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_2LAST_CMD1_TYPE;
#define UNICAM_DB1_DBG_2LAST_CMD1_COMMAND1_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_2LAST_CMD1_COMMAND1_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_2LAST_CMD2_TYPE;
#define UNICAM_DB1_DBG_2LAST_CMD2_COMMAND2_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_2LAST_CMD2_COMMAND2_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_W_CHAN_TYPE;
#define UNICAM_DB1_DBG_W_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_W_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_W_DATA_TYPE;
#define UNICAM_DB1_DBG_W_DATA_LAST_DATA_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_W_DATA_LAST_DATA_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_B_CHAN_TYPE;
#define UNICAM_DB1_DBG_B_CHAN_LAST_CHAN_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_B_CHAN_LAST_CHAN_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_BRST_XN_CNT_TYPE;
#define UNICAM_DB1_DBG_BRST_XN_CNT_XN_COUNTER_MASK (0xffff0000UL)
#define UNICAM_DB1_DBG_BRST_XN_CNT_XN_COUNTER_SHIFT (16UL)
#define UNICAM_DB1_DBG_BRST_XN_CNT_OUT_OF_RANGE_MASK (0xff00UL)
#define UNICAM_DB1_DBG_BRST_XN_CNT_OUT_OF_RANGE_SHIFT (8UL)
#define UNICAM_DB1_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_MASK (0x1fUL)
#define UNICAM_DB1_DBG_BRST_XN_CNT_OUTSTDNG_XN_CNT_SHIFT (0UL)




typedef uint32_t UNICAM_DB1_DBG_LINE_CNT_TYPE;
#define UNICAM_DB1_DBG_LINE_CNT_CNT_MASK (0xffffffffUL)
#define UNICAM_DB1_DBG_LINE_CNT_CNT_SHIFT (0UL)




typedef volatile struct COMP_PACKED _UNICAM_RDBType {
    UNICAM_CTL_TYPE camctl; /* OFFSET: 0x0 */
    UNICAM_STA_TYPE camsta; /* OFFSET: 0x4 */
    UNICAM_ANA_TYPE camana; /* OFFSET: 0x8 */
    UNICAM_PRI_TYPE campri; /* OFFSET: 0xc */
    UNICAM_CLK_TYPE camclk; /* OFFSET: 0x10 */
    UNICAM_CLT_TYPE camclt; /* OFFSET: 0x14 */
    UNICAM_DAT0_TYPE camdat[4]; /* OFFSET: 0x18 */
    UNICAM_DLT_TYPE camdlt; /* OFFSET: 0x28 */
    UNICAM_CMP0_TYPE camcmp[2]; /* OFFSET: 0x2c */
    UNICAM_CAP0_TYPE camcap[2]; /* OFFSET: 0x34 */
    UNICAM_CLKACTL_TYPE camclkactl; /* OFFSET: 0x3c */
    UNICAM_DATACTL_TYPE camdatactl[4]; /* OFFSET: 0x40 */
    UNICAM_LDOCTL_TYPE camldoctl; /* OFFSET: 0x50 */
    UNICAM_PIOCTL_TYPE campioctl; /* OFFSET: 0x54 */
    UNICAM_RESERVED_TYPE rsvd0[152]; /* OFFSET: 0x58 */
    UNICAM_DBG0_TYPE camdbg0; /* OFFSET: 0xf0 */
    UNICAM_DBG1_TYPE camdbg1; /* OFFSET: 0xf4 */
    UNICAM_DBG2_TYPE camdbg2; /* OFFSET: 0xf8 */
    UNICAM_DBG3_TYPE camdbg3; /* OFFSET: 0xfc */
    UNICAM_ICTL_TYPE camictl; /* OFFSET: 0x100 */
    UNICAM_ISTA_TYPE camista; /* OFFSET: 0x104 */
    UNICAM_IDI0_TYPE camidi0; /* OFFSET: 0x108 */
    UNICAM_IPIPE_TYPE camipipe; /* OFFSET: 0x10c */
    UNICAM_IBSA0_TYPE camibsa0; /* OFFSET: 0x110 */
    UNICAM_IBEA0_TYPE camibea0; /* OFFSET: 0x114 */
    UNICAM_IBLS_TYPE camibls; /* OFFSET: 0x118 */
    UNICAM_IBWP_TYPE camibwp; /* OFFSET: 0x11c */
    UNICAM_RESERVED_TYPE rsvd1[80]; /* OFFSET: 0x120 */
    UNICAM_ICTL_SE_TYPE camictl_se; /* OFFSET: 0x170 */
    UNICAM_ISTA_SE_TYPE camista_se; /* OFFSET: 0x174 */
    UNICAM_IDATA_SE_TYPE camidata_se; /* OFFSET: 0x178 */
    UNICAM_RESERVED_TYPE rsvd2[132]; /* OFFSET: 0x17c */
    UNICAM_DCS_TYPE camdcs; /* OFFSET: 0x200 */
    UNICAM_DBSA0_TYPE camdbsa0; /* OFFSET: 0x204 */
    UNICAM_DBEA0_TYPE camdbea0; /* OFFSET: 0x208 */
    UNICAM_DBWP_TYPE camdbwp; /* OFFSET: 0x20c */
    UNICAM_RESERVED_TYPE rsvd3[240]; /* OFFSET: 0x210 */
    UNICAM_DBCTL_TYPE camdbctl; /* OFFSET: 0x300 */
    UNICAM_IBSA1_TYPE camibsa1; /* OFFSET: 0x304 */
    UNICAM_IBEA1_TYPE camibea1; /* OFFSET: 0x308 */
    UNICAM_IDI1_TYPE camidi1; /* OFFSET: 0x30c */
    UNICAM_DBSA1_TYPE camdbsa1; /* OFFSET: 0x310 */
    UNICAM_DBEA1_TYPE camdbea1; /* OFFSET: 0x314 */
    UNICAM_RESERVED_TYPE rsvd4[8]; /* OFFSET: 0x318 */
    UNICAM_FRSZ_TYPE camfrsz; /* OFFSET: 0x320 */
    UNICAM_LINCTL_TYPE camlinctl; /* OFFSET: 0x324 */
    UNICAM_EXP1CTL_TYPE camexp1ctl; /* OFFSET: 0x328 */
    UNICAM_RESERVED_TYPE rsvd5[4]; /* OFFSET: 0x32c */
    UNICAM_HDRCTL_TYPE camhdrctl; /* OFFSET: 0x330 */
    UNICAM_ISP_HWSYC_CTL_TYPE camisp_hwsyc_ctl; /* OFFSET: 0x334 */
    UNICAM_ISP_HWSYC_STA_TYPE camisp_hwsyc_sta; /* OFFSET: 0x338 */
    UNICAM_ISP_MISC_TYPE camisp_misc; /* OFFSET: 0x33c */
    UNICAM_DBG_TYPE camdbg; /* OFFSET: 0x340 */
    UNICAM_RESERVED_TYPE rsvd6[28]; /* OFFSET: 0x344 */
    UNICAM_IDI2_TYPE camidi2; /* OFFSET: 0x360 */
    UNICAM_IDI3_TYPE camidi3; /* OFFSET: 0x364 */
    UNICAM_RESERVED_TYPE rsvd7[160]; /* OFFSET: 0x368 */
    UNICAM_VER_TYPE camver; /* OFFSET: 0x408 */
    UNICAM_FET_TYPE camfet; /* OFFSET: 0x40c */
    UNICAM_WRAP_TYPE camwrap; /* OFFSET: 0x410 */
    UNICAM_RESERVED_TYPE rsvd8[76]; /* OFFSET: 0x414 */
    UNICAM_DBG_PIX_CMP_FIF_TYPE dbg_pix_cmp_fif; /* OFFSET: 0x460 */
    UNICAM_DBG_PIX_RET_UPK_TYPE dbg_pix_ret_upk; /* OFFSET: 0x464 */
    UNICAM_DBG_PIX_OPE_DPM_TYPE dbg_pix_ope_dpm; /* OFFSET: 0x468 */
    UNICAM_RESERVED_TYPE rsvd9[4]; /* OFFSET: 0x46c */
    UNICAM_PRBS_PHYCTL0_TYPE prbs_phyctl0; /* OFFSET: 0x470 */
    UNICAM_PRBS_PHYCTL1_TYPE prbs_phyctl1; /* OFFSET: 0x474 */
    UNICAM_PRBS_LN0_CTL_TYPE prbs_ln0_ctl; /* OFFSET: 0x478 */
    UNICAM_PRBS_LN0_ST_TYPE prbs_ln0_st; /* OFFSET: 0x47c */
    UNICAM_PRBS_LN1_CTL_TYPE prbs_ln1_ctl; /* OFFSET: 0x480 */
    UNICAM_PRBS_LN1_ST_TYPE prbs_ln1_st; /* OFFSET: 0x484 */
    UNICAM_PRBS_LN2_CTL_TYPE prbs_ln2_ctl; /* OFFSET: 0x488 */
    UNICAM_PRBS_LN2_ST_TYPE prbs_ln2_st; /* OFFSET: 0x48c */
    UNICAM_PRBS_LN3_CTL_TYPE prbs_ln3_ctl; /* OFFSET: 0x490 */
    UNICAM_PRBS_LN3_ST_TYPE prbs_ln3_st; /* OFFSET: 0x494 */
    UNICAM_RESERVED_TYPE rsvd10[104]; /* OFFSET: 0x498 */
    UNICAM_CPIS_TYPE camcpis; /* OFFSET: 0x500 */
    UNICAM_CPIR_TYPE camcpir; /* OFFSET: 0x504 */
    UNICAM_CPIF_TYPE camcpif; /* OFFSET: 0x508 */
    UNICAM_RESERVED_TYPE rsvd11[20]; /* OFFSET: 0x50c */
    UNICAM_CPIWM_TYPE camcpiwm; /* OFFSET: 0x520 */
    UNICAM_CPIB_TYPE camcpib; /* OFFSET: 0x524 */
    UNICAM_RESERVED_TYPE rsvd12[8]; /* OFFSET: 0x528 */
    UNICAM_CPIVCM_TYPE camcpivcm; /* OFFSET: 0x530 */
    UNICAM_CPIHCM_TYPE camcpihcm; /* OFFSET: 0x534 */
    UNICAM_CPILECM_TYPE camcpilecm; /* OFFSET: 0x538 */
    UNICAM_RESERVED_TYPE rsvd13[196]; /* OFFSET: 0x53c */
    UNICAM_HISPI_CTL_TYPE camhispi_ctl; /* OFFSET: 0x600 */
    UNICAM_HISPI_STA_TYPE camhispi_sta; /* OFFSET: 0x604 */
    UNICAM_RESERVED_TYPE rsvd14[24]; /* OFFSET: 0x608 */
    UNICAM_HISPI_DBG1_TYPE hispi_dbg1; /* OFFSET: 0x620 */
    UNICAM_HISPI_DBG_FIFO_0_TYPE hispi_dbg_fifo_0; /* OFFSET: 0x624 */
    UNICAM_HISPI_DBG_FIFO_1_TYPE hispi_dbg_fifo_1; /* OFFSET: 0x628 */
    UNICAM_HISPI_DBG_FIFO_2_TYPE hispi_dbg_fifo_2; /* OFFSET: 0x62c */
    UNICAM_HISPI_DBG_FIFO_3_TYPE hispi_dbg_fifo_3; /* OFFSET: 0x630 */
    UNICAM_RESERVED_TYPE rsvd15[140]; /* OFFSET: 0x634 */
    UNICAM_DBG_PORT_CTL_TYPE dbg_port_ctl; /* OFFSET: 0x6c0 */
    UNICAM_DBG_PORT_STAT_TYPE dbg_port_stat; /* OFFSET: 0x6c4 */
    UNICAM_RESERVED_TYPE rsvd16[56]; /* OFFSET: 0x6c8 */
    UNICAM_VC5_TGCTL_TYPE cam_vc5_tgctl; /* OFFSET: 0x700 */
    UNICAM_VC5_TGISZ_TYPE cam_vc5_tgisz; /* OFFSET: 0x704 */
    UNICAM_VC5_TGBL_TYPE cam_vc5_tgbl; /* OFFSET: 0x708 */
    UNICAM_VC5_TGBSZ_TYPE cam_vc5_tgbsz; /* OFFSET: 0x70c */
    UNICAM_VC5_TGLFS_TYPE cam_vc5_tglfs; /* OFFSET: 0x710 */
    UNICAM_VC5_TGPS_TYPE cam_vc5_tgps; /* OFFSET: 0x714 */
    UNICAM_VC5_TGISTAT_TYPE cam_vc5_tgistat; /* OFFSET: 0x718 */
    UNICAM_VC5_TG_IEN_TYPE cam_vc5_tg_ien; /* OFFSET: 0x71c */
    UNICAM_VC5_ACFG_TYPE cam_vc5_acfg; /* OFFSET: 0x720 */
    UNICAM_VC5_ASTA_TYPE cam_vc5_asta; /* OFFSET: 0x724 */
    UNICAM_VC5_ASA_TYPE cam_vc5_asa; /* OFFSET: 0x728 */
    UNICAM_VC5_AEA_TYPE cam_vc5_aea; /* OFFSET: 0x72c */
    UNICAM_VC5_ASL_TYPE cam_vc5_asl; /* OFFSET: 0x730 */
    UNICAM_VC5_ALC_TYPE cam_vc5_alc; /* OFFSET: 0x734 */
    UNICAM_VC5_AT_TYPE cam_vc5_at; /* OFFSET: 0x738 */
    UNICAM_VC5_AMM_TYPE cam_vc5_amm; /* OFFSET: 0x73c */
    UNICAM_VC5_ATRIG_TYPE cam_vc5_atrig; /* OFFSET: 0x740 */
    UNICAM_RESERVED_TYPE rsvd17[700]; /* OFFSET: 0x744 */
    UNICAM_IB0_DBG_CTL_TYPE ib0_dbg_ctl; /* OFFSET: 0xa00 */
    UNICAM_IB0_DBG_LAST_ADDR_TYPE ib0_dbg_last_addr; /* OFFSET: 0xa04 */
    UNICAM_IB0_DBG_LAST_CMD1_TYPE ib0_dbg_last_cmd1; /* OFFSET: 0xa08 */
    UNICAM_IB0_DBG_LAST_CMD2_TYPE ib0_dbg_last_cmd2; /* OFFSET: 0xa0c */
    UNICAM_IB0_DBG_2LAST_ADDR_TYPE ib0_dbg_2last_addr; /* OFFSET: 0xa10 */
    UNICAM_IB0_DBG_2LAST_CMD1_TYPE ib0_dbg_2last_cmd1; /* OFFSET: 0xa14 */
    UNICAM_IB0_DBG_2LAST_CMD2_TYPE ib0_dbg_2last_cmd2; /* OFFSET: 0xa18 */
    UNICAM_IB0_DBG_W_CHAN_TYPE ib0_dbg_w_chan; /* OFFSET: 0xa1c */
    UNICAM_IB0_DBG_W_DATA_TYPE ib0_dbg_w_data; /* OFFSET: 0xa20 */
    UNICAM_IB0_DBG_B_CHAN_TYPE ib0_dbg_b_chan; /* OFFSET: 0xa24 */
    UNICAM_IB0_DBG_BRST_XN_CNT_TYPE ib0_dbg_brst_xn_cnt; /* OFFSET: 0xa28 */
    UNICAM_IB0_DBG_LINE_CNT_TYPE ib0_dbg_line_cnt; /* OFFSET: 0xa2c */
    UNICAM_RESERVED_TYPE rsvd18[16]; /* OFFSET: 0xa30 */
    UNICAM_IB1_DBG_CTL_TYPE ib1_dbg_ctl; /* OFFSET: 0xa40 */
    UNICAM_IB1_DBG_LAST_ADDR_TYPE ib1_dbg_last_addr; /* OFFSET: 0xa44 */
    UNICAM_IB1_DBG_LAST_CMD1_TYPE ib1_dbg_last_cmd1; /* OFFSET: 0xa48 */
    UNICAM_IB1_DBG_LAST_CMD2_TYPE ib1_dbg_last_cmd2; /* OFFSET: 0xa4c */
    UNICAM_IB1_DBG_2LAST_ADDR_TYPE ib1_dbg_2last_addr; /* OFFSET: 0xa50 */
    UNICAM_IB1_DBG_2LAST_CMD1_TYPE ib1_dbg_2last_cmd1; /* OFFSET: 0xa54 */
    UNICAM_IB1_DBG_2LAST_CMD2_TYPE ib1_dbg_2last_cmd2; /* OFFSET: 0xa58 */
    UNICAM_IB1_DBG_W_CHAN_TYPE ib1_dbg_w_chan; /* OFFSET: 0xa5c */
    UNICAM_IB1_DBG_W_DATA_TYPE ib1_dbg_w_data; /* OFFSET: 0xa60 */
    UNICAM_IB1_DBG_B_CHAN_TYPE ib1_dbg_b_chan; /* OFFSET: 0xa64 */
    UNICAM_IB1_DBG_BRST_XN_CNT_TYPE ib1_dbg_brst_xn_cnt; /* OFFSET: 0xa68 */
    UNICAM_IB1_DBG_LINE_CNT_TYPE ib1_dbg_line_cnt; /* OFFSET: 0xa6c */
    UNICAM_RESERVED_TYPE rsvd19[16]; /* OFFSET: 0xa70 */
    UNICAM_DB0_DBG_CTL_TYPE db0_dbg_ctl; /* OFFSET: 0xa80 */
    UNICAM_DB0_DBG_LAST_ADDR_TYPE db0_dbg_last_addr; /* OFFSET: 0xa84 */
    UNICAM_DB0_DBG_LAST_CMD1_TYPE db0_dbg_last_cmd1; /* OFFSET: 0xa88 */
    UNICAM_DB0_DBG_LAST_CMD2_TYPE db0_dbg_last_cmd2; /* OFFSET: 0xa8c */
    UNICAM_DB0_DBG_2LAST_ADDR_TYPE db0_dbg_2last_addr; /* OFFSET: 0xa90 */
    UNICAM_DB0_DBG_2LAST_CMD1_TYPE db0_dbg_2last_cmd1; /* OFFSET: 0xa94 */
    UNICAM_DB0_DBG_2LAST_CMD2_TYPE db0_dbg_2last_cmd2; /* OFFSET: 0xa98 */
    UNICAM_DB0_DBG_W_CHAN_TYPE db0_dbg_w_chan; /* OFFSET: 0xa9c */
    UNICAM_DB0_DBG_W_DATA_TYPE db0_dbg_w_data; /* OFFSET: 0xaa0 */
    UNICAM_DB0_DBG_B_CHAN_TYPE db0_dbg_b_chan; /* OFFSET: 0xaa4 */
    UNICAM_DB0_DBG_BRST_XN_CNT_TYPE db0_dbg_brst_xn_cnt; /* OFFSET: 0xaa8 */
    UNICAM_DB0_DBG_LINE_CNT_TYPE db0_dbg_line_cnt; /* OFFSET: 0xaac */
    UNICAM_RESERVED_TYPE rsvd20[16]; /* OFFSET: 0xab0 */
    UNICAM_DB1_DBG_CTL_TYPE db1_dbg_ctl; /* OFFSET: 0xac0 */
    UNICAM_DB1_DBG_LAST_ADDR_TYPE db1_dbg_last_addr; /* OFFSET: 0xac4 */
    UNICAM_DB1_DBG_LAST_CMD1_TYPE db1_dbg_last_cmd1; /* OFFSET: 0xac8 */
    UNICAM_DB1_DBG_LAST_CMD2_TYPE db1_dbg_last_cmd2; /* OFFSET: 0xacc */
    UNICAM_DB1_DBG_2LAST_ADDR_TYPE db1_dbg_2last_addr; /* OFFSET: 0xad0 */
    UNICAM_DB1_DBG_2LAST_CMD1_TYPE db1_dbg_2last_cmd1; /* OFFSET: 0xad4 */
    UNICAM_DB1_DBG_2LAST_CMD2_TYPE db1_dbg_2last_cmd2; /* OFFSET: 0xad8 */
    UNICAM_DB1_DBG_W_CHAN_TYPE db1_dbg_w_chan; /* OFFSET: 0xadc */
    UNICAM_DB1_DBG_W_DATA_TYPE db1_dbg_w_data; /* OFFSET: 0xae0 */
    UNICAM_DB1_DBG_B_CHAN_TYPE db1_dbg_b_chan; /* OFFSET: 0xae4 */
    UNICAM_DB1_DBG_BRST_XN_CNT_TYPE db1_dbg_brst_xn_cnt; /* OFFSET: 0xae8 */
    UNICAM_DB1_DBG_LINE_CNT_TYPE db1_dbg_line_cnt; /* OFFSET: 0xaec */
} UNICAM_RDBType;


#define UNICAM_BASE                     (0x40080000UL)



#define UNICAM_MAX_HW_ID                (1UL)

#endif /* UNICAM_RDB_H */
